### ISSUE TITLE
Add creator from Iterator of `i128` to get the decimalarray

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-rs#1009]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
From this comments in the datafusion.
https://github.com/apache/arrow-datafusion/pull/1394#discussion_r762053386

https://github.com/apache/arrow-datafusion/pull/1394

Creating an `DecimalArray` from an array of `Option<i128>` using `DecimalBuilder` is quite painful (see https://github.com/apache/arrow-datafusion/pull/1394)

Ideally it would be possible to do something similar to the PrimitiveArrays, such as https://docs.rs/arrow/6.3.0/arrow/array/type.UInt32Array.html#example-using-collect

```rust
// get an iterator over `Option<i128>`
let data: Vec<Option<i128>> = ....;
let array: DecimalArray = data.into_iter().collect();
```

**Describe the solution you'd like**
However, since `DecimalArray` has `precision` and `scale` in its `DataType`, we need some way to specify that. 

One thought, would be a function such as (for `precision` 20 and `scale` 5): 

```rust
let array = DecimalArray::from_iter_and_scale(20, 5, data.iter())
```

An alternate might be something more like:
```rust
// creates a decimal array with default precision 32 and scale 0 (could be something else)
let array: DecimalArray = data.into_iter().collect();
// consume the existing array and make a new one with a different declared precision and scale
let array = array.with_precision_and_scale(20, 5);
```

**Describe alternatives you've considered**

**Additional context**

**Comment by liukun4515** [comment]
Please assign this to me.

**Comment by alamb** [comment]
Hi @liukun4515  -- thanks for the ticket; I added some more description to this ticket and some ideas which hopefully would help.

**Comment by liukun4515** [comment]
> Hi @liukun4515 -- thanks for the ticket; I added some more description to this ticket and some ideas which hopefully would help.

Thank you.
I think the decimal type is more complex than other types, I will start this task when the tasks in the datafusion ends.

**Comment by alamb** [comment]
BTW the more I tried playing around with this, the nicer I think it would be to be able to do something like

```rust
    let array : DecimalArray = vec![1,2,3].into()
        .with_precision(10)
        .with_scale(5);
```

**Comment by liukun4515** [comment]
> BTW the more I tried playing around with this, the nicer I think it would be to be able to do something like

Yes, we can follow the usage of other primitive arrays to implement the necessary utils function first.

**Comment by alamb** [comment]
i took a crack at this in https://github.com/apache/arrow-rs/pull/1223
