### ISSUE TITLE
SIMD for decimal data type

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-rs#1010]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

From this [datafusion issue](https://github.com/apache/arrow-datafusion/issues/122), we will add the decimal data type 
in the datafusion.
But some basic operations like `+,-` we implemented do not support SIMD.

In order to speed up the calculation, we need to add the SIMD feature for the decimal data type.

I have not figured out how to implement it.

**Describe the solution you'd like**
TODO

**Describe alternatives you've considered**
TODO

**Additional context**
TODO

**Comment by liukun4515** [comment]
please assign this to me.

**Comment by alamb** [comment]
FYI @liukun4515  -- before implementing explicit SIMD versions of these kernels, it may be worth doing some profiling / disassembly of what `rustc` creates for the current kernels. 

Perhaps a good start would be to add Decimal support to the existing kernels in https://docs.rs/arrow/6.3.0/arrow/compute/kernels/aggregate/index.html if it doesn't alread exist

I have not reviewed the code in the datafusion aggregate functions for a while, so I am not familiar with how much they do / don't use the arrow compute kernels.

**Comment by liukun4515** [comment]
> disassembly

Thanks for your suggestion, I will follow this.

**Comment by alamb** [comment]
FWIW I believe https://rust.godbolt.org/ is a popular tool for such work

**Comment by chadbrewbaker** [comment]
https://ispc.github.io etc are probably the way to go. For any expensive query you will want to shell out to LLVM and custom compile the worker binaries before the run - also probably blast the query plan with an SMT solver to reduce the expense/runtime depending on your constraints. I would avoid dynamic linking like the plague - be like the IBM Blue Gene/L.

**Comment by chadbrewbaker** [comment]
Before mucking with simd - probably good idea to have a repo like Rust coreutils that leverages existing regression tests for the SQL engine. Especially perf regressions.

https://github.com/postgres/postgres/tree/master/src/test/regress

https://github.com/s3team/Squirrel

**Comment by chadbrewbaker** [comment]
Here is the Google SIMD assembler https://github.com/google/zetasql/blob/master/zetasql/base/mathutil.h

**Comment by tustvold** [comment]
Implemented by #2881

**Comment by liukun4515** [comment]
> Implemented by #2881

Thanks @tustvold
