### ISSUE TITLE
Take on strings incorrect on slices

### ISSUE THREAD

**Issue by bjchambers** [apache/arrow-rs#1049]
**Describe the bug**

```
#[test]
fn test_take_slice_string() {
    let strings =
        StringArray::from(vec![Some("hello"), None, Some("world"), None, Some("hi")]);
    let indices = Int32Array::from(vec![Some(0), Some(1), None, Some(0), Some(2)]);
    let indices_slice = indices.slice(1, 4);
    let indices_slice = indices_slice
        .as_ref()
        .as_any()
        .downcast_ref::<Int32Array>()
        .unwrap();

    let expected = StringArray::from(vec![None, None, Some("hello"), Some("world")]);
    let result = take(&strings, indices_slice, None).unwrap();
    assert_eq!(result.as_ref(), &expected);
}
```

```
thread 'compute::kernels::take::tests::test_take_slice_string' panicked at 'assertion failed: `(left == right)`
  left: `StringArray
[
  null,
  null,
  null,
  "world",
]`,
 right: `StringArray
[
  null,
  null,
  "hello",
  "world",
]`', arrow/src/compute/kernels/take.rs:1950:9
```

**To Reproduce**

See test. It looks like the null bits aren't being properly shifted when used in the take kernel.

**Expected behavior**

Test passes.

**Additional context**

**Comment by chadbrewbaker** [comment]
I looked into this last night. The code is crazy complex.

At the small end composing permutations/transformations over null free u8 could be SIMD specialized. At the large end there need to be tests on worst case buffer explosion. Probably need to bring in https://docs.rs/proptest/latest/proptest/

**Comment by chadbrewbaker** [comment]
I think I narrowed the bug to this function:
https://github.com/apache/arrow-rs/blob/99b7d01103495607932343146c973b6fba0eb8d5/arrow/src/compute/kernels/take.rs#L621

and this block of code:

https://github.com/apache/arrow-rs/blob/99b7d01103495607932343146c973b6fba0eb8d5/arrow/src/compute/kernels/take.rs#L694-L720
