### ISSUE TITLE
Parquet Fuzz Tests

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#1053]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Whilst working on #1037 I've introduced bugs that have then been caught by the arrow array benchmarks. 

It would therefore appear that these tests are exercising code paths not found in the other tests, and we could therefore increase the test coverage by including some variant of them.

**Describe the solution you'd like**

A set of fuzz tests that create various types of `PageIterator` with multiple column chunks, and multiple pages per column chunk. This can likely reuse much of the fuzz plumbing found in the arrow_array_reader benchmarks.

The tests would then use the `ArrayReader` abstractions to read this data and verify it is what was written.

**Describe alternatives you've considered**

We could not add fuzz tests, but there would be an increased likelihood of regressions.

**Comment by chadbrewbaker** [comment]
After thinking about this for a week - I'm inclined to start driving with [ Arrow Python/Hypothesis](https://github.com/apache/arrow/blob/master/python/pyarrow/tests/strategies.py)  and [Python Parquet tests](https://github.com/apache/arrow/tree/master/python/pyarrow/tests/parquet) then gradually add Proptest. AWS Labs has the [best proptest examples](https://github.com/search?q=org%3Aawslabs+proptest).

Zooming out a bit more, DataFusion needs to be integrated in [sqlancer](https://github.com/sqlancer/sqlancer) cross SQL engine tests. We also want to be like AWS Redshift where you write a query in Python/SQL - and it emits Rust code that gets compiled and sent to worker nodes.

**Comment by tustvold** [comment]
FYI I'm experimenting with extending the [existing fuzz tests](https://github.com/apache/arrow-rs/blob/master/parquet/src/arrow/arrow_reader.rs#L459) to support nulls, dictionaries, etc...
