### ISSUE TITLE
Docs: Improve clarity by rewriting 'Any' -> 'All unless overwritten'

### ISSUE THREAD

**Issue by corneliusroemer** [apache/arrow-rs#1064]
**Describe the bug**
In the parquet documentation, the following word choice (using *any*) is common:
> Sets max statistics for **any** column

https://github.com/apache/arrow-rs/blob/99b7d01103495607932343146c973b6fba0eb8d5/parquet/src/file/properties.rs#L347

I don't think this is the clearest, most unambiguous word to use here.

I think that the meaning intended is: "Sets max statistics for _all_ columns (or _every_ column)"

Any is sloppy, because it could mean "more than one" and does not guarantee "all" when "all" is guaranteed.

This usage of _any_ appears a couple of times in parquet. I think it should be edited for all occurences.

https://github.com/apache/arrow-rs/blob/99b7d01103495607932343146c973b6fba0eb8d5/parquet/src/file/properties.rs#L311-L320

https://github.com/apache/arrow-rs/blob/99b7d01103495607932343146c973b6fba0eb8d5/parquet/src/file/properties.rs#L326

https://github.com/apache/arrow-rs/blob/99b7d01103495607932343146c973b6fba0eb8d5/parquet/src/file/properties.rs#L332

https://github.com/apache/arrow-rs/blob/99b7d01103495607932343146c973b6fba0eb8d5/parquet/src/file/properties.rs#L341

https://github.com/apache/arrow-rs/blob/99b7d01103495607932343146c973b6fba0eb8d5/parquet/src/file/properties.rs#L347

I noticed this confusing wording in the docs for csv2parquet CLI and opened an issue there: https://github.com/domoritz/csv2parquet/issues/42

@domoritz then pointed me here as he just copied from upstream.

**Comment by alamb** [comment]
Thanks @corneliusroemer  -- can you submit a PR to improve the docs in arrow-rs?

**Comment by domoritz** [comment]
I can make the pull request. I don't understand this comment, though

```
    /// If dictionary is not enabled, this is treated as a primary encoding for all
    /// columns. In case when dictionary is enabled for any column, this value is
    /// considered to be a fallback encoding for that column.
```

What does `this` or `this value` refer to? The whole comment probably should be rewritten to be clearer.

For now, I assume it meant to say

```
    /// If dictionary is not enabled, the provided value is treated as a primary
    /// encoding for all columns. When dictionary is enabled for a column, this
    /// value is considered to be a fallback encoding for that column.
```

**Comment by domoritz** [comment]
Fixed in https://github.com/apache/arrow-rs/pull/1126
