### ISSUE TITLE
Remove the `integration-testing/unskip.patch` file

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#1067]
Context from @b41sh  -- https://github.com/apache/arrow-rs/pull/779#issuecomment-989605395

This file is a local change that is applied to the overall arrow integration tests. Once the upstream arrow pr https://github.com/apache/arrow/pull/11238 has been merged, we will not have to apply this patch anymore in arrow. 

This ticket tracks removing it

**Comment by b41sh** [comment]
sorry, I have removed this file before the PR merge, we can close this issue.
