### ISSUE TITLE
Arrow comparison `LIKE`/`ILIKE`/`NLIKE` kernels do not escape all special characters

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#1069]
**Describe the bug**

Characters such as `[` and `.` are sometimes treated as regular expressions rather than literals in regular expressions

The arrow regular expression kernels such as `like_utf8` https://github.com/apache/arrow-rs/blob/master/arrow/src/compute/kernels/comparison.rs#L311-L323 take limited SQL style string matching patterns (e.g. `%`). 

However, under the covers a regular expression matching library is used but special regular expression characters are not escaped. @ovr  added code to handle `(` and `)` in https://github.com/apache/arrow-rs/pull/1042 but there are other special characters as well

**To Reproduce**

```rust
    let array: StringArray = vec!["foo", "bar", "baz"]
        .into_iter()
        .map(Some)
        .collect();

    let comparison = arrow::compute::like_utf8_scalar(&array, "foo%.*").unwrap();

    let expected: BooleanArray = vec![false, false, false]
        .into_iter()
        .map(Some)
        .collect();

    assert_eq!(comparison, expected);
```

**Expected behavior**
This test should pass (is what postgres produces)

```sql
alamb=# select * from foo;
  x  
-----
 foo
 bar
 baz
(3 rows)

alamb=# select x, x like 'foo%.*' from foo;
  x  | ?column? 
-----+----------
 foo | f
 bar | f
 baz | f
(3 rows)
```

**Additional context**
Follow on to https://github.com/apache/arrow-rs/pull/1042 where @ovr  fixed the parenthesis issue

**Comment by alamb** [comment]
@jwdeitch  suggests the use of `escape` here: https://github.com/apache/arrow-rs/pull/1042#discussion_r768188149

**Comment by alamb** [comment]
Fixing this bug is likely a matter of using the code suggested by @jwdeitch  and writing some tests. 🙏  thank you to whoever picks it up

**Comment by Dandandan** [comment]
I am working on this - was annoyed by this already. Using `escape` seems like a great solution.
