### ISSUE TITLE
Considers scientific notation when inferring schema from csv

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#108]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-10132

 
||col||
|1.2|
|1.3e-2|
|1.4|

Currently this column would be inferred as Utf8 type, since csv::reader::DECIMAL_RE is defined as r"^-?(\d+\.\d+)$". Maybe we could change this to r"^-?(\d+\.\d+)(e-?(\d+))?$" or similar stuff to allow scientific notation of real number inferred as float?

 

(The RE I currently proposed doesn't handle "5e-4" correctly though)

 

And I would wish we could infer "3." or ".3" as float too. I will come up with an exact RE when I get time.

**Comment by Jefffrey** [comment]
Resolved by https://github.com/apache/arrow-rs/pull/1216
