### ISSUE TITLE
Add into iter for decimal array

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-rs#1083]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
In some cases https://github.com/apache/arrow-rs/pull/1073#discussion_r773211954 , we need iter the decimal array, but the method of the accessor is below
![image](https://user-images.githubusercontent.com/7450163/147020320-4ca45d61-93ba-4b6e-b423-83371ce0b28b.png)

We need to use the loop/for the method to iter the decimal array.

We need to implement the into iter for the decimal array

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
I took a crack at this one in https://github.com/apache/arrow-rs/pull/1223
