### ISSUE TITLE
Possible `like`/`ilike`/`not_like` kernels= escaping problems 

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#1087]
**Describe the bug**
@jwdeitch  noted on https://github.com/apache/arrow-rs/pull/1085#issuecomment-999627965 that there may be a problem with `regex` kernels:

> I think there may be an outstanding escaping issue in where right-hand side is '%%%' and you want to match on '(literal%)_(literal%)'.... but this problem may be outside the scope of this fix. :)

**To Reproduce**
TO BE FILED

**Comment by jwdeitch** [comment]
Thanks for filing Andrew!

Here is a reproducer test case:

```
    test_utf8!(
        ilike_utf8_scalar_regex,
        vec!["%%%"],
        vec![r#"\%_\%"#],
        ilike_utf8,
        vec![true]
    );

```

the 
```... pat.replace("%", ".*") ... ```
areas might need to consider a leading `\` to know to _not_ make the `.*` replacement

**Comment by Dandandan** [comment]
> Thanks for filing Andrew!
> 
> Here is a reproducer test case:
> 
> ```
>     test_utf8!(
>         ilike_utf8_scalar_regex,
>         vec!["%%%"],
>         vec![r#"\%_\%"#],
>         ilike_utf8,
>         vec![true]
>     );
> ```
> 
> the `... pat.replace("%", ".*") ... ` areas might need to consider a leading `\` to know to _not_ make the `.*` replacement

I guess that's the same as 
https://github.com/apache/arrow-rs/issues/415 ?

Do you think so as well?

**Comment by jwdeitch** [comment]
ah right on. thanks!! that's the same issue

**Comment by jwdeitch** [comment]
I'll try to submit a patch for this today

**Comment by alamb** [comment]
@Dandandan  sorry about the duplicate -- closing as dupe of #415

**Comment by Dandandan** [comment]
> @Dandandan  sorry about the duplicate -- closing as dupe of #415 

No worries, thanks for tracking the issue.
