### ISSUE TITLE
arithmetic without SIMD does unnecesary copy

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#110]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-10274

The arithmetic kernels that don't use SIMD create a `vec` in memory and later copy that data into a Buffer. Maybe we could directly write the arithmetic result to a mutable buffer and prevent this redundant copy?

 

 
{code:java}
    let values = (0..left.len())
                .map(|i| op(left.value(i), right.value(i))) 
                .collect::<Vec<T::Native>>();
     
      
            let data = ArrayData::new(
          T::get_data_type(),
                left.len(),
                None,
                null_bit_buffer,
                0,
                vec![Buffer::from(values.to_byte_slice())],
                vec![],
            );{code}

**Comment by alamb** [comment]
Comment from Jorge Leitão(jorgecarleitao) @ 2020-10-11T08:50:04.358+0000:
<pre>> Maybe we could directly write the arithmetic result to a mutable buffer and prevent this redundant copy?

Yes :)</pre>

**Comment by tustvold** [comment]
I think this is no longer relevant
