### ISSUE TITLE
Implement dyn scalar comparison kernels

### ISSUE THREAD

**Issue by matthewmturner** [apache/arrow-rs#1113]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Following the design set in #1074 we would like to add the remaining dynamic comparison kernels.

**Scalar**
- [ ] lt_dyn_scalar
- [ ] lt_eq_dyn_scalar
- [ ] gt_dyn_scalar
- [ ] gt_eq_dyn_scalar
- [ ] neq_dyn_scalar

**UTF8 Scalar**
- [ ] lt_dyn_utf8_scalar
- [ ] lt_eq_dyn_utf8_scalar
- [ ] gt_dyn_utf8_scalar
- [ ] gt_eq_dyn_utf8_scalar
- [ ] neq_dyn_utf8_scalar

**Boolean**
- [ ] lt_dyn_bool_scalar
- [ ] lt_eq_dyn_bool_scalar
- [ ] gt_dyn_bool_scalar
- [ ] gt_eq_dyn_bool_scalar
- [ ] neq_dyn_bool_scalar

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by matthewmturner** [comment]
@alamb @liukun4515 

I am submitting a bunch of the PRs now branching off my existing `eq_dyn_scalar` branch.  The PRs now currently show all the changes because we havent merged that one in to master yet. Im hoping once that is merged i can simply rebase and these will be good to go.

**Comment by matthewmturner** [comment]
Going to stop here at the scalar kernels to make sure all good.  If this approach is good ill do the utf8 and bool kernels

**Comment by liukun4515** [comment]
> @alamb @liukun4515
> 
> I am submitting a bunch of the PRs now branching off my existing `eq_dyn_scalar` branch. The PRs now currently show all the changes because we havent merged that one in to master yet. Im hoping once that is merged i can simply rebase and these will be good to go.

@matthewmturner https://github.com/apache/arrow-rs/pull/1074 has been merged, you can rebase other prs, but I think we should merge the prs one by one and reduce the conflict. @alamb

**Comment by matthewmturner** [comment]
> > @alamb @liukun4515
> 
> > 
> 
> > I am submitting a bunch of the PRs now branching off my existing `eq_dyn_scalar` branch. The PRs now currently show all the changes because we havent merged that one in to master yet. Im hoping once that is merged i can simply rebase and these will be good to go.
> 
> 
> 
> @matthewmturner https://github.com/apache/arrow-rs/pull/1074 has been merged, you can rebase other prs, but I think we should merge the prs one by one and reduce the conflict. @alamb 

Agree. I was expecting to do that
