### ISSUE TITLE
Formatting of markdown with Prettier

### ISSUE THREAD

**Issue by bkmgit** [apache/arrow-rs#1139]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
If editing markdown files in the browser, CI checks with [Prettier](https://prettier.io) only give a warning message that a file is improperly formatted. This can make editing markdown in the browser tedious.

**Describe the solution you'd like**
Since only markdown files are checked by prettier, a javascript dependency, it may be good to change the [CI configuration](https://github.com/bkmgit/arrow-rs/blob/simd/.github/workflows/dev.yml) to 
```
npx prettier@2.3.0 --write {arrow,arrow-flight,dev,integration-testing,parquet}/**/*.md README.md CODE_OF_CONDUCT.md CONTRIBUTING.md
```
Or otherwise ensure that CI checks are able to output the suggested changes.

**Describe alternatives you've considered**
- Consider a rust based formatter to minimize local toolchain project dependencies such as [comrak](https://github.com/kivikakk/comrak)
- Suggest using an online formatter in the [CONTRIBUTING.md](https://github.com/apache/arrow-rs/blob/master/CONTRIBUTING.md), such as https://codebeautify.org/javascript-pretty-print or https://codebeautify.org/markdown-formatter

**Comment by alamb** [comment]
This is a good idea -- datafusion does something similar so it should be a strightforward change

https://github.com/apache/arrow-datafusion/blob/4ea865230d5bc1d916926acc7fb7f008481e8c6c/.github/workflows/dev.yml#L67-L74
