### ISSUE TITLE
support more mathematics kernels for array and scalar value

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#1153]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We only have `powf_scalar`, `modulus_scalar` and `divide_scalar`. We need more mathematics kernels for array and scalar value that could be used by downstream projects e.g. datafusion.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
Related to https://github.com/apache/arrow-datafusion/issues/1513 I think

**Comment by liukun4515** [comment]
> We only have `powf_scalar`, `modulus_scalar` and `divide_scalar`. We need more mathematics kernels for array and scalar value that could be used by downstream projects e.g. datafusion.

thank you @viirya 
I'm implementing some mathematics operation for decimal data type in datafusion, and finding the enhancement for arrow-rs kernel.
