### ISSUE TITLE
Nicer API to create `MapArrays`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#1158]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Right now it is quite cumbersome to create  a `MapArray` as one has to create  an `ArrayData` from a `StructArray` . `MapArray` was contributed by @nevi-me  in https://github.com/apache/arrow-rs/pull/491

https://github.com/apache/arrow-rs/blob/e898de57e4587c64387939f8a557bc5fa2dffeb8/arrow/src/array/array_map.rs#L243-L282

**Describe the solution you'd like**

It would be great to be able to create a `MapArray` directly from the appropriate `StructArray`. Something like this perhaps (though other proposals more than welcome):

```rust
let entry_array = StructArray::from(vec![
            (keys, make_array(keys_data)),
            (values, make_array(values_data)),
        ]); 

let map_array = MapArray::from(&entry_array).unwrap();
```

Where `entry_array` would need to have two fields where the first was strings 

The impl might look like

```
impl From<&StructArray> for MapArray {
...
}
```

**Describe alternatives you've considered**

It might also be cool to have other ways of constructing the key/value pairs 

```rust
impl MapArray {
  fn new_from_strings(keys: impl Iterator<Item=&str>, values: &dyn Array) -> Result<Self> {
    ..
  }
}
```

Or whatever
**Additional context**
https://github.com/apache/arrow-rs/pull/1149#discussion_r782433887

**Comment by viirya** [comment]
I think for the proposed API, we don't know the `entry_offsets` which is necessary when constructing a `MapArray`?

**Comment by viirya** [comment]
For alternative one `new_from_strings`, we can add offset parameters:

```rust
impl MapArray {
  fn new_from_strings(keys: impl Iterator<Item=&str>, values: &dyn Array, entry_offsets: &[u8]) -> Result<Self> {
    ..
  }
}
```

**Comment by alamb** [comment]
Thanks @viirya
