### ISSUE TITLE
Duration array values cannot be pretty printed

### ISSUE THREAD

**Issue by e-dard** [apache/arrow-rs#1168]
**Describe the bug**

Whilst attempting to pretty print a value in a `DurationMillisecondArray` I hit an error because the plumbing to pretty print durations has not been done here:

https://github.com/apache/arrow-rs/blob/231cf788879f12b3cfbc6da776e2360117567d17/arrow/src/util/display.rs#L291-L403

**To Reproduce**

Create a `DurationMillisecondArray` and try to call `arrow::util::display::array_value_to_string(arr, 0)` on the array.

**Expected behaviour**

I expect the first row to be printed in a format consistent with how Rust's `std::time::Duration` types are formatted when debug printed.

**Comment by alamb** [comment]
Came up in the context of https://github.com/influxdata/influxdb_iox/pull/3460 /  https://github.com/influxdata/influxdb_iox/pull/3460#discussion_r784272714 in case anyone is curious

**Comment by e-dard** [comment]
@alamb i think there was a formatting issue on my ticket description - it was just showing "describe the bug" 😅
