### ISSUE TITLE
Support casting to/from DictionaryArray <--> LargeUTF8, Binary and LargeBinary in Cast Kernels

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#1179]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently if you try to cast a LargeStringArray, BinaryArray or LargeBinaryArray into a dictionary an error is returned

For example

```
CastError("Unsupported output type for dictionary packing: LargeUtf8")'
```

**Describe the solution you'd like**

Ideally this would work

**Comment by alamb** [comment]
Specifically, we would like to add support to the cast and cast_with_options kernels:
https://docs.rs/arrow/20.0.0/arrow/compute/kernels/cast/index.html
https://docs.rs/arrow/20.0.0/arrow/compute/kernels/cast/fn.cast_with_options.html
