### ISSUE TITLE
[Rust]: Make full integration of ARMv7

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#118]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-10507

Arrow is not ready for ARMv7. It needs an effort to finalize the full integration.

**Comment by ByteBaker** [comment]
@alamb need some context here. How do I verify this and proceed?

**Comment by ByteBaker** [comment]
Seems like in Arrow we [merged it already](https://github.com/apache/arrow/issues/26478).

**Comment by alamb** [comment]
I am not sure there is anything actionable about this ticket (I don't know what its original intent was for). Let's close it down and file a new one if / when we find something else that is needed

THanks @ByteBaker  and @Xuanwo for cleaning this stuff up
