### ISSUE TITLE
Optimize `take` kernel for `Decimal`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#1190]
The idea is to avoid using DecimalBuilder and create the `DecimalArray` directly using an iterator (or `MutableBuffer`) 

_Originally posted by @alamb in https://github.com/apache/arrow-rs/pull/1172#pullrequestreview-854562444_

**Comment by tfeda** [comment]
This seems to have been resolved in #1249. I think this issue can be closed

**Comment by alamb** [comment]
Good point @tfeda  -- thank you
