### ISSUE TITLE
Broken CI SIMD and wasm checks on master:  unknown feature `llvm_asm`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#1198]
The CI wasm and SIMD tests are now failing on master:

https://github.com/apache/arrow-rs/runs/4852992130?check_suite_focus=true
https://github.com/apache/arrow-rs/runs/4852992553?check_suite_focus=true

complaining about missing llvm_asm, which appears to relate to https://github.com/rust-lang/packed_simd/issues/340 as pointed out by @gangliao on #1195

_Originally posted by @tustvold in https://github.com/apache/arrow-rs/issues/1189#issuecomment-1015258084_

**Comment by alamb** [comment]
Reverting #1189  did not appear to fix the issue. Perhaps another crate accidentally released a breaking change

**Comment by jorgecarleitao** [comment]
We are observing the same on arrow2. This seems to be upstream :(

**Comment by alamb** [comment]
I plan to look into this more carefully tomorrow morning (US eastern time)

**Comment by alamb** [comment]
I am pretty confident that this is an issue in `packed_simd` -- in the sense that the library depends on some feature in rust nightly which has since been removed. Here is a PR that should fix it:

https://github.com/rust-lang/packed_simd/pull/341

In theory if we can get the maintainers to release an updated version this will be fixed for us

**Comment by alamb** [comment]
We can always follow the lead of arrow2 here if no one is willing to publish a new fix for `packed_simd` and switch to `stdsimd` --  https://github.com/jorgecarleitao/arrow2/pull/747

I suppose "code that compiles but is slower" is better than "code that doesn't compile"

**Comment by alamb** [comment]
Datapoints: 

Works:
```
cargo +nightly-2021-12-08-x86_64-apple-darwin test -p arrow --features=simd
cargo +nightly-2022-01-14-x86_64-apple-darwin test -p arrow --features=simd
cargo +nightly-2022-01-15-x86_64-apple-darwin test -p arrow --features=simd
cargo +nightly-2022-01-16-x86_64-apple-darwin test -p arrow --features=simd
cargo +nightly-2022-01-17-x86_64-apple-darwin test -p arrow --features=simd
```

Doesn't work:
```
cargo +nightly test -p arrow --features=simd
```

(aka I think it was the nightly version that was released today -- `2022-01-18`)

**Comment by tustvold** [comment]
I think this can be closed now
