### ISSUE TITLE
Implement DecimalArray support in `eq_dyn`, `neq_dyn`, `lt_dyn`, `lt_eq_dyn`, `gt_dyn`, `gt_eq_dyn`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#1200]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Rationale make it as easier (more ergonomic) to implement array comparison, both for DataFusion and other users. See rationale in https://github.com/apache/arrow-rs/issues/843

**Describe the solution you'd like**
The idea would basically be to implement the same thing as @viirya did for timestamp types in https://github.com/apache/arrow-rs/pull/1095 but for `DecimalArrays` 

That is the following code should not assert and compare the decimal arrays element by element: 

```rust
let arr1: DecimalArray = ...;
let arr2: DecimalArray = ...;
let result = eq_dyn(&arr1, &arr2);
assert!(result.is_ok())
```

**Describe alternatives you've considered**
For completeness, we could also add `eq_decimal`, `neq_decimal`, etc as well, though I personally think focusing on the dyn kernels would be the easiest thing.

**Additional context**

@liukun4515 has added kernels in DataFusion here which could be adapted
https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/physical_plan/expressions/binary.rs#L80-L231

other context:
I am trying to move datafusion over to using the dyn kernels here: https://github.com/apache/arrow-datafusion/pull/1475

**Comment by liukun4515** [comment]
@alamb Do you begin to do this?
If not, I try it.

**Comment by alamb** [comment]
@liukun4515  I have not started this

**Comment by viirya** [comment]
Any more progress? If no, I may find some time working on this.

**Comment by alamb** [comment]
I have not made any progress on this sadly

**Comment by liukun4515** [comment]
> Any more progress? If no, I may find some time working on this.

I will do this when the kernel functions are ready in the datafusion side.
@viirya

**Comment by alamb** [comment]
I think the idea is to
1.  port / move the `eq_decimal` from datafusion to arrow-rs 
2. hook  up the kernels to the dispatch in  `eq_dyn`, etc

Here is the code in datafusion
https://github.com/apache/arrow-datafusion/blob/7b7edf9c43383c1d3310286b69d2d037db72c967/datafusion/physical-expr/src/expressions/binary.rs#L169

Needs to  brought to https://sourcegraph.com/github.com/apache/arrow-rs/-/blob/arrow/src/compute/kernels/comparison.rs?L7&subtree=true

and then also added to `eq_dyn` https://sourcegraph.com/github.com/apache/arrow-rs/-/blob/arrow/src/compute/kernels/comparison.rs?L2324:8-2324:14

**Comment by liukun4515** [comment]
I think it has been done.
cc @alamb @tustvold

**Comment by liukun4515** [comment]
we can close it.
