### ISSUE TITLE
Add doc examples for `eq_dyn` etc.

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#1202]
The comparison kernels have a somewhat bewildering array of options for a new developer

https://docs.rs/arrow/7.0.0/arrow/compute/kernels/comparison/index.html

We have been making the API easier to use with so called `dyn` kernels (such as `eq_dyn`, etc) but this may not be as discoverable as would be ideal. 

Thus it would be great to add some doctests to the `comparison` module that demonstrated how to use those kernels with an example of creating two arrays, and then calling `eq_dyn` on them

**Comment by alamb** [comment]
Perhaps one could follow the example of

https://docs.rs/arrow/7.0.0/arrow/array/type.StringArray.html

```rust
use arrow::array::StringArray;
let array1 = StringArray::from(vec![Some("foo"), None, Some("bar")]);
let array2 = StringArray::from(vec![Some("foo"), None, Some("baz")]);
let result = eq_dyn(&array1, &array2).unwrap();
assert_eq!(BooleanArray::from(vec![Some(true), None, Some(false)]), result))
```

**Comment by HaoYang670** [comment]
I can work on it! Please assign to me @alamb

**Comment by alamb** [comment]
Thanks @HaoYang670
