### ISSUE TITLE
Rename `Bitmap::len` to `Bitmap::bit_len`

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#1233]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

#1231 was caused by a somewhat confusingly named method on `Bitmap`

**Describe the solution you'd like**

Rename the method to avoid future confusion

**Describe alternatives you've considered**

Document the method extensively

**Comment by HaoYang670** [comment]
Do we still need to rename it, as the documentation has been improved? If so, I would like to solve this issue.
