### ISSUE TITLE
Add `test_validate` feature flag  + CI check

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#1239]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

For better or worse `arrow-rs` makes use of unsafe in various places. Whilst there are ongoing efforts to reduce the use of unsafe, occasionally bugs will slip through. Both `arrow-rs` and `arrow-datafusion` run with MIRI in order to catch many of these, however, MIRI is extremely slow and fiddly to setup which acts as a limiting factor on crowd-sourced test coverage. Additionally it will not catch the arguably more common types of logic bug, e.g. inconsistent null counts, non-consecutive array offsets, etc...

**Describe the solution you'd like**

Add a `test_validate` feature flag that when enabled will cause various "unchecked" methods to actually perform validation. The most obvious being `ArrayDataBuilder::build_unchecked`. This will allow projects to contribute to crowd-sourced nasal demon hunting, without imposing on them all the costs of setting up and running MIRI.

**Describe alternatives you've considered**

This could also be enabled based on [debug_assertions](https://doc.rust-lang.org/reference/conditional-compilation.html#debug_assertions) being enabled, but this is a global setting that is on by default in debug builds. A feature flag gives people the ability to opt-out of the validation. FWIW this is what the parquet crate currently does.

**Comment by alamb** [comment]
Maybe `force_validate` might be a more descriptive name for this flag.

I actually did this (forced `ArrayData::new_unchecked` to actually check) to manually test the original validation logic

**Comment by jhorstmann** [comment]
Agree, this sounds useful. Making it independent of `debug_assertions` is also a good idea and would allow enabling it also in some staging/pre-production environments.

**Comment by tustvold** [comment]
Had a brief stab at adding this, the good news is it doesn't show any new problems, the bad news is it causes a lot of the tests of the validation logic to fail :laughing: I need to have a think about how best to handle this...

**Comment by alamb** [comment]
> Had a brief stab at adding this, the good news is it doesn't show any new problems, the bad news is it causes a lot of the tests of the validation logic to fail 😆 I need to have a think about how best to handle this...


Maybe we could just `#cfg` out the test suite for `ArrayData`  🤔
