### ISSUE TITLE
Get `Unknown configuration option rust-version` when running the rust format command

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-rs#1240]
**Describe the bug**
On my desktop, when I run the command
```
cargo +stable fmt --all -- --check
```
I always get the warning
```
Warning: Unknown configuration option `rust-version`
```
When I run the command
```
rustfmt --help=config
```
I could not find a configuration option called `rust-version`
I am not sure whether it is a bug or my problem.

**To Reproduce**
Run the command 
```
cargo +stable fmt --all -- --check
```

**Expected behavior**
Remove the warning.

**Additional context**
[Developer's guide to Arrow Rust.](https://github.com/apache/arrow-rs/blob/794929835dd32f2c2e6897d7f606606e3e5aab29/CONTRIBUTING.md#:~:text=cargo%20%2Bstable%20fmt%20%2D%2Dall%20%2D%2D%20%2D%2Dcheck)

**Comment by HaoYang670** [comment]
Should we delete this line:

**Comment by HaoYang670** [comment]
Does anyone meet the same problem?

**Comment by HaoYang670** [comment]
@alamb Could you reproduce the problem?

**Comment by alamb** [comment]
Hi @HaoYang670  -- I do see the same problem and I agree with your assessment of the problem.

I had assumed it was related to not using nightly, but it happens for me with nightly and with stable rust. 

```
cd /Users/alamb/Software/arrow-rs && CARGO_TARGET_DIR=/Users/alamb/Software/df-target cargo fmt
Warning: Unknown configuration option `rust-version`
Warning: Unknown configuration option `rust-version`
Warning: Unknown configuration option `rust-version`
```



```
cargo +nightly  fmt
Warning: Unknown configuration option `rust-version`
Warning: Unknown configuration option `rust-version`
Warning: Unknown configuration option `rust-version`
```
