### ISSUE TITLE
Fix all clippy lints in parquet crate

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#1254]
**Describe the bug**
Due to "historical reasons" there are several clippy lints that are disabled in the parquet crate
https://github.com/apache/arrow-rs/blob/master/parquet/src/lib.rs#L18-L36

```rust
#![allow(incomplete_features)]
#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(
    clippy::approx_constant,
    clippy::cast_ptr_alignment,
    clippy::float_cmp,
    clippy::float_equality_without_abs,
    clippy::from_over_into,
    clippy::many_single_char_names,
    clippy::needless_range_loop,
    clippy::new_without_default,
    clippy::or_fun_call,
    clippy::same_item_push,
    clippy::too_many_arguments,
    clippy::transmute_ptr_to_ptr,
    clippy::upper_case_acronyms,
    clippy::vec_init_then_push
)]
```

It would be great to clean up the code to pass these lints for tidiness

**To Reproduce**
Remove one of the `#[allow]` lines above, run `clippy`

**Expected behavior**
Clippy runs cleanly without blank `#allow` across the whole crate

**Additional context**

**Comment by soham4abc** [comment]
I Would like to work on the issue... If possible please assign

**Comment by HaoYang670** [comment]
I'd like to have a try if no one else has been doing it! 
Rust Clippy is really interesting!

**Comment by HaoYang670** [comment]
There are many dead code and unused public functions. I am not sure whether to clean them up.

**Comment by alamb** [comment]
> There are many dead code and unused public functions. I am not sure whether to clean them up.

I recommend doing this issue in a few PRs -- in the first take care of the easier lints, and then in follow ons we can sort out dead code / public function nonsense together

**Comment by alamb** [comment]
Sorry for the late reply @HaoYang670 

> Lots of pub members are detected as dead code. I am not sure whether to clean them up. For example:

If the code is dead I think we should remove it. One way for `pub` functions to be dead is if the module they are defined in is not `pub`.

I am not sure how you are running clippy, but it may also be that some of these structs are only used when certain features of the `parquet` crate are enabled.

I believe our CI system has good coverage so feel free to try removing them and if the CI passes I think it is a good change

**Comment by HaoYang670** [comment]
>  but it may also be that some of these structs are only used when certain features of the `parquet` crate are enabled.

Thank you @alamb. There are some experimental mods under `parquet`. And I must add `--features experimental` to make them public. But I am not sure whether our CI adds this flag.

**Comment by alamb** [comment]
Clippy is run like this:

https://github.com/apache/arrow-rs/blob/master/.github/workflows/rust.yml#L211-L250

```
          cargo clippy --features test_common --features prettyprint  --features=async --all-targets --workspace -- -D warnings
```

Perhaps we can also add the `experimental` features to this list?

**Comment by alamb** [comment]
After https://github.com/apache/arrow-rs/pull/2190 clippy is run just for the parquet crate (which now includes the `--experimental` flag)

So once that is merged, the first order of business will be to make this command run cleanly:

```shell
cargo clippy -p parquet --all-targets --all-features -- -D warnings
```

And then we can move on to removing the additional lints
