### ISSUE TITLE
Fix all clippy lints in arrow crate

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#1255]
**Describe the bug**
Due to "historical reasons" there are several clippy lints that are disabled in the `arrow` crate
https://github.com/apache/arrow-rs/blob/master/arrow/src/lib.rs#L130-L141

```rust
#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![deny(clippy::redundant_clone)]
#![allow(
    // introduced to ignore lint errors when upgrading from 2020-04-22 to 2020-11-14
    clippy::float_equality_without_abs,
    clippy::type_complexity,
    // upper_case_acronyms lint was introduced in Rust 1.51.
    // It is triggered in the ffi module, and ipc::gen, which we have no control over
    clippy::upper_case_acronyms,
    clippy::vec_init_then_push
)]
```

It would be great to clean up the code to pass these lints for tidiness

**To Reproduce**
Remove one of the `#[allow]` lines above, run `clippy`

**Expected behavior**
Clippy runs cleanly without blank `#allow` across the whole crate

**Additional context**

**Comment by gsserge** [comment]
I'd like to work on this one. One PR per lint rule should make it easier to review and integrate.

**Comment by alamb** [comment]
Thanks @gsserge  that would be great!
