### ISSUE TITLE
Provide an `async` ParquetWriter for arrow

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#1269]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
As it is nice to be able to read parquet files using rust `async` IO https://github.com/apache/arrow-rs/issues/111, it would be nice to write them as well 

 
**Describe the solution you'd like**
A `async` writer similar in spirit to the reader created in https://github.com/apache/arrow-rs/issues/111

**Comment by alamb** [comment]
Thanks @xudong963  - I personally suggest starting with the API design. As in write an example program showing how you would use the feature. Something like the following (sorting out what types to use for streams, etc):

```rust
async fn main() { 
  // get output stream
  let writer = AsyncParquet::new(...);
  // write batches to the writer somehow (not sure how??)
  for batch in batches {
    ....
  }
}
```

**Comment by xudong963** [comment]
Thanks for your nice suggestion! @alamb, I'll start the task tomorrow.

**Comment by xudong963** [comment]
I felt the need to provide these new APIs and structs.

```rust
pub struct AsyncArrowWriter<W: W: AsyncWrite + Unpin + Send> {
    writer: FileStream<W>,
    ...
}

pub struct FileStream<W: AsyncWriter + Send + Unpined> {
    writer: W
}

impl <...> FileStream {
    pub async fn write(&mut self, ...) -> Result<> {
        // 1. firstly, write header
        write_header().await?;
        // 2. secondly, write rowgroups
        write_row_groups().await?;
        // 3. thirdly, write metadata
        write_metadata().await?;
    }
}
```

I noticed that we have a **buffer** optimization in the sync write part. I'm not sure if we need to keep the buffer in the async write part.

**Comment by tustvold** [comment]
> I noticed that we have a buffer optimization in the sync write part. I'm not sure if we need to keep the buffer in the async write part.

Are you referring to the buffer added in #1214 as it would be really cool to keep that if possible? `RecordBatch` are likely significantly smaller than the ideal size for a row group

**Comment by xudong963** [comment]
@tustvold Yep, thanks! I'll take a look at #1214 and reorganize my thoughts.

**Comment by ShiKaiWi** [comment]
@tustvold Hi, this feature will help us a lot if it is implemented. Is there anyone working on this issue? I'm glad to try it if not.

**Comment by xudong963** [comment]
@ShiKaiWi Thanks!  Feel free to try it. I'm busy with other things.

**Comment by ShiKaiWi** [comment]
@tustvold Thanks for your quick response. Here are my some thoughts about your proposal:
> This would then allow providing a Vec<u8> as the writer, and then periodically gaining access to it and flushing its contents asynchronously. We could provide an AsyncWriter that encapsulates this logic, but we could also just provide a code example in a doc comment.

I guess the **periodically gaining access** is not an elegant way (but it indeed can solve the problem we encounter), because the polling frequency can't be determined easily, that is to say, polling with high frequency may introduce overhead and with slow frequency may lead to high memory usage by the inner writer `Vec<u8>`.

> The nature of parquet is that an entire row group is buffered up and written in one shot, as data for different columns cannot be interleaved, so I'm not sure it is possible to do better than this

For now, I doesn't know the details of the writer very well, but I guess the buffer logic can still be kept in the async writer.

**Comment by tustvold** [comment]
> because the polling frequency can't be determined easily

Checking after each call to [write](https://docs.rs/parquet/latest/parquet/arrow/arrow_writer/struct.ArrowWriter.html#method.write) should be fine. A more sophisticated writer could track the number of written rows and only check once they exceed the max row group size, in practice this is highly unlikely to be make a tangible performance difference

> may lead to high memory usage by the inner writer Vec<u8>

Assuming a single RecordBatch does not exceed the maximum size of a row group, the above approach should be optimal in this respect.

 > guess the buffer logic can still be kept in the async writer

If we can share as much between the sync and async implementations as possible, that would be beneficial. The separate async read path, whilst a necessary evil, is a non-trivial maintenance burden

**Comment by ShiKaiWi** [comment]
> Checking after each call to [write](https://docs.rs/parquet/latest/parquet/arrow/arrow_writer/struct.ArrowWriter.html#method.write) should be fine. A more sophisticated writer could track the number of written rows and only check once they exceed the max row group size, in practice this is highly unlikely to be make a tangible performance difference

👍. This way is good enough to solve the problem we encounter.

> share as much between the sync and async implementations as possible
After digging into the code, I find this is the hardest part to implement async writer.

I guess your suggested way is the best workaround before the most codes of the sync and async implementation can be shared.

**Comment by ShiKaiWi** [comment]
@tustvold Maybe I can solve this issue by implementing your proposal:
> We could provide an AsyncWriter that encapsulates this logic, but we could also just provide a code example in a doc comment.

Please let me know when you make the decision.

**Comment by tustvold** [comment]
> Please let me know when you make the decision.

How about we implement an AsyncWriter and see what it looks like, using the buffering approach, and see what it looks like

**Comment by ShiKaiWi** [comment]
> > Please let me know when you make the decision.
> 
> How about we implement an AsyncWriter and see what it looks like, using the buffering approach, and see what it looks like

Ok. I'll give it a try.

**Comment by ShiKaiWi** [comment]
> > Please let me know when you make the decision.
> 
> How about we implement an AsyncWriter and see what it looks like, using the buffering approach, and see what it looks like

@tustvold I find it is hard for me to implement the `AsyncWriter` by sharing the codes with current sync writer. And I try the initial proposal by you, which looks simple and pretty: https://github.com/ShiKaiWi/arrow-rs/commit/40f9d5a7e2fb7818decb0dffa00dff2b39be7eb1

What do you think about the demo?
