### ISSUE TITLE
how to create arrow::array from streamReader

### ISSUE THREAD

**Issue by Tudyx** [apache/arrow-rs#1278]
I want to create an `arrow::table`  from a `StreamReader` object to be able to call the `slice` method on it. So far i have read my arrow file into my `StreamReader` but i don't find the good functions to make it into an `arrow::table`.  I don't have any assumption on the type of the data that the stream contains. 
```rust
let file = File::open("foo.arrow").unwrap();
let mut stream_reader = arrow::ipc::reader::StreamReader::try_new(file).unwrap();
```
I tried
```rust
let table = stream_reader.collect();
```
and i also tried accessing the `BufReader<R>` of `StreamReader struct`  directly but without success.
The behavior i seek is similar of the C++ function `Status arrow::RecordBatch::ReadAll(std::shared_ptr<Table>* table) `, the function that put all content of a stream into one table.
Please, do you have any ideas how i could reach my goal?

**Comment by fnicastri** [comment]
Can you share the solution?
