### ISSUE TITLE
Test failure: bit_chunk_iterator

### ISSUE THREAD

**Issue by nevi-me** [apache/arrow-rs#1294]
**Describe the bug**
The `test_unaligned_bit_chunk_iterator()` test fails to run on aarch64 because of an assertion `assert!(ALIGNMENT > 64)`.  There are several platforms that support 64-bit or lower alignment, and this assertion will also fail on them.

**To Reproduce**

Run arrow tests with arm, aarch64 or other platform with a lower alignment than the assertion

**Expected behavior**

Not sure of what the implication of > 64 alignment is, as I haven't been following the codebase

**Additional context**

Here's the alignment for aarch64 https://github.com/apache/arrow-rs/blob/master/arrow/src/alloc/alignment.rs#L119. CC @tustvold from #1228

**Comment by tustvold** [comment]
IIRC this will just impact the correctness of the test and not the code, but I'll take a look. Thanks for reporting :+1:
