### ISSUE TITLE
Release arrow ~10.0.0~ 9.1.0

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#1304]
EDIT: suggestion is to release this as arrow 9.1.0 as there are no breaking changes.

**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Arrow 10.0.0 is scheduled for release (RC on Feb 18, 2022 release on Feb 21, 2022 if we follow the same schedule as other releases)

I will not be able to contribute to the project for these dates as I will be away, though I will be available again starting Feb 28 2022

**Describe the solution you'd like**
This might be a great time for some others to try out creating a release if they are available and are interested in doing so

The instructions are here:
https://github.com/apache/arrow-rs/blob/master/dev/release/README.md

I believe you need to be a committer to run the `./dev/release/create-tarball.sh 4.1.0 2` script, but making the changelog and updating the version would be straight forward. 

@andygrove @kou  and @kszucs  have access to publish on crates.io.

**Describe alternatives you've considered**
An alternative is to postpone the release until sometime after Feb 28

**Additional context**
Arrow 9.0.0 was delayed by about a week due to some issues encountered while testing. See https://lists.apache.org/thread/2yyq5x7cx4f16q68x8vlftf3ksbrckxb for more details

**Comment by tustvold** [comment]
I'd be happy to help out with preparing the release, but would of course need the assistance of a committer to cut the actual release. It may be easier for a single committer to handle the whole thing, but thought I'd offer :smile:

**Comment by nevi-me** [comment]
I can cut an RC over the weekend, on Saturday

**Comment by alamb** [comment]
Thanks @nevi-me  -- I'll try and make a PR with some proposed release notes and a version bump as well to help out

**Comment by alamb** [comment]
https://github.com/apache/arrow-rs/pull/1325

**Comment by alamb** [comment]
After reviewing the changelog, it seems like this could actually be a 9.1.0 release (see comment from @tafia https://github.com/apache/arrow-rs/issues/1120#issuecomment-1042672561 , 

Thoughts @tustvold ?

**Comment by tustvold** [comment]
@alamb We are of the same mind :laughing: - https://github.com/apache/arrow-rs/pull/1325#issuecomment-1042762455

**Comment by alamb** [comment]
Cool will update the versions in #1325

**Comment by tafia** [comment]
Thanks !!

**Comment by alamb** [comment]
Thank you so much @nevi-me  and everyone else who helped with this release!

**Comment by rdettai** [comment]
sorry for not reacting to this, this last months have been very busy for me! I'll try to help out next time 😉
