### ISSUE TITLE
Add  `as_decimal_array(arr: &dyn Array) -> &DecimalArray`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#1312]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
There are many `as_XXX` functions  such as [`as_boolean_array`](https://docs.rs/arrow/9.0.2/arrow/array/fn.as_boolean_array.html) to conveniently downcast arrays to the appropriate concrete Array types, but not one for `DecimalArray` 😢 . 

The full list of supported ones is in the doc  https://docs.rs/arrow/9.0.2/arrow/array/index.html#functions) 

**Describe the solution you'd like**
I would like one for DecimalArray:

```
fn as_decimal_array(arr: &dyn Array) -> &DecimalArray {
...
}
```

**Additional context**
Context: I found while working on https://github.com/apache/arrow-datafusion/pull/1475

**Comment by alamb** [comment]
cc @liukun4515

**Comment by liukun4515** [comment]
> cc @liukun4515

If no one takes this, I am glad to do this task.
@alamb  Please assign it to me.

**Comment by liukun4515** [comment]
I will do this in the weekend, and focus on some knowledge about ballista and distributed scheduler.
