### ISSUE TITLE
`len` is not a parameter of `MutableArrayData::extend`

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-rs#1316]
**Describe the bug**
Noticed while working on #1230 .
The document of `MutableArrayData::extend` contains a weird value `len` which is not a parameter of this function.

![image](https://user-images.githubusercontent.com/59198230/154194965-54a17735-a171-4db2-a9fc-8183543ebe5c.png)

**To Reproduce**

**Expected behavior**
Replace `len` by `end - start` in the document, or change the function's API

**Additional context**
```rust
    /// Extends this [MutableArrayData] with elements from the bounded [ArrayData] at `start`
    /// and for a size of `len`.
    /// # Panic
    /// This function panics if the range is out of bounds, i.e. if `start + len >= array.len()`.
    pub fn extend(&mut self, index: usize, start: usize, end: usize) {
        let len = end - start;
        (self.extend_null_bits[index])(&mut self.data, start, len);
        (self.extend_values[index])(&mut self.data, index, start, len);
        self.data.len += len;
    }
```

**Comment by alamb** [comment]
I think fixing the doc comment would be the best approach here
