### ISSUE TITLE
Consider support / implementation of  Arrow Flight SQL

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#1323]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Arrow Flight SQL has just been officially announced https://arrow.apache.org/blog/2022/02/16/introducing-arrow-flight-sql/

It would be very cool if we had a Rust implementation of this protocol to make it easier to build systems in Rust that used this efficient new protocol and would allow better ecosystem integration. 

Self servingly, we would likely use it in [influxdb_iox](https://github.com/influxdata/influxdb_iox) and contribute to such an implementation, but it isn't high on our priority list quite yet.

Implementation steps: 
- [x] https://github.com/apache/arrow-rs/pull/1386
- [x] https://github.com/apache/arrow-rs/issues/1413

**Describe the solution you'd like**
I propose creating an `ArrowFlightSQLService` type structure that handles the protocol details, and present an idiomatic rust `trait` for users.

Something like: 

```rust
pub trait SqlService {
  /// get  list of database schemas as an array of Strings
  fn schemas(&self, catalog_name: Option<&str>, db_schema_filter_pattern: Option<&str>) -> Result<ArrayRef>;

  /// Execute the query and return an async stream of record batches
  fn query(&self, sql: &str) -> Result<SendableRecordBatchStream>;
 ... 
}

/// Implementation of Arrow Flight SQL for a `SqlService`
struct ArrowFlightSQLService<S: SqlService>  {
  inner: S
}

/// implement service from https://github.com/apache/arrow/blob/release-7.0.0/format/Flight.proto
/// That handles messages in https://github.com/apache/arrow/blob/release-7.0.0/format/FlightSql.proto
impl protobuf::generated::FlightService for ArrowFlightSQLService {

... code to translate to/from protobuf messages

}
```

**Describe alternatives you've considered**
One alternative is to make this part of the official arrow-rs release (perhaps with a `sql` feature in the `arrow-flight` crate)?

Another alternative is to make this a separate project (e.g. in https://github.com/apache/arrow-datafusion or in https://github.com/datafusion-contrib )

**Additional context**
[DataFusion](https://arrow.apache.org/datafusion/)

**Comment by andygrove** [comment]
Ideally, the Ballista scheduler should also implement a Flight SQL interface.

**Comment by alamb** [comment]
> Ideally, the Ballista scheduler should also implement a Flight SQL interface.

Yeah, I was thinking that if we had this adapter that handled the lower level protocol details, connecting to Ballista would be fairly straightforward

**Comment by e-dard** [comment]
I have been working on a (very clunky right now) Rust prototype that speaks the server side PostgreSQL wire protocol, parses queries and then will dispatch them to anything that speaks SQL over flight, e.g., our IOx project. 

In terms of the translation between a PG query/command and a backend datasource request, I suspect that I am going to end up doing a lot of the work that an implementation of the Arrow Flight SQL protocol would do. 

I would be happy to try and make some progress on this, though it's not quite clear to me yet which bits would live in Arrow or Datafusion yet.

**Comment by alamb** [comment]
Just so that it is clear, Arrow Flight SQL is a replacement for the pg wire protocol (both the command messages and data format).

**Comment by e-dard** [comment]
That's super interesting @nevi-me!

I'n primarily interested in making it possible for services/projects that can talk to PG to be able to talk to IOx, where IOx really means Datafusion. My approach has been to implement the PG wire protocol and then handoff a sub-set of supported PG behaviours to a backend over Flight (e.g., queries). Then translate responses (record batches) in PG responses. 

I suspect (assume) a lot of the mapping between PG commands and Flight SQL commands are the same, so making progress on a Rust implementation of the flightSQL spec will get a lot of that work done.

Whilst Flight SQL is intended to replace heterogeneous client/server DB protocols, the existing ones aren't going anywhere any time soon. I think Flight SQL will make it easier to map from specific DB protocols to anything whatever speaks Flight SQL.

**Comment by nevi-me** [comment]
> I'm primarily interested in making it possible for services/projects that can talk to PG to be able to talk to IOx, where IOx really means Datafusion. My approach has been to implement the PG wire protocol and then handoff a sub-set of supported PG behaviours to a backend over Flight (e.g., queries). Then translate responses (record batches) in PG responses.

That's a great use-case, supporting the Postgres protocol makes sense as tools (esp BI) that support reading the protocol could treat IOx as a source, similar to CockroachDB and others.

___

I've dumped my rough drafts of the code I mentioned here: https://github.com/nevi-me/datafusion-rdbms-ext. Nothing of decent quality, but could serve as motivation for someone who has the interest and bandwidth to make DataFusion > RDMBS happen

**Comment by GavinRay97** [comment]
@nevi-me That link is super interesting, thank you!

**Comment by wangfenjin** [comment]
@nevi-me I checked your code, the idea is to have a to_sql() method for LogicalPlan. I think it's a good idea, actually yesterday I also try to read datafusion's codebase to find this kind of method, but got no clue.

I suggest we implement this method in datacusion, at least can covert to sql dialect datafusion itself can understand.

**Comment by seddonm1** [comment]
I have an implementation of datafusion querying directly against postgres I can share. It too uses the catalog but it allows joining a postgres table to a parquet table to now a parquet from a S3 compatible source. It would be easy enough to define a proper trait so multiple implementations could be done.

I also did the auth and part of a rust postgres protocol server (so pgcli can connect to rust) but ran out of time.

**Comment by nevi-me** [comment]
@seddonm1 does your implementation have support for Postgres' NUMERIC type? I'm struggling with figuring out how to convert that doe `DataType::Decimal(p, s)`, and could do with some help

**Comment by alamb** [comment]
FWIW there is a proposed implementation in https://github.com/apache/arrow-rs/pull/1386
