### ISSUE TITLE
Fix csv Writer::new to accept delimiter and make WriterBuilder::build use it  

### ISSUE THREAD

**Issue by gsserge** [apache/arrow-rs#1328]
Discovered in https://github.com/apache/arrow-rs/pull/1324#discussion_r808432375

The delimiter can be correctly configured via `WriterBuilder`. `WriterBuilder::build()` constructs the `Writer` in-line and does not use `Write::new()`. 

Currently, `Write::new()` does not have the ability to configure the delimiter. The function should be changed to accept it as a parameter, and then `WriterBuilder::build()` should use `Write::new()` instead of duplicating the code. The `delimiter` field in `struct Writer` can be removed, because it can only be configured when creating `Writer`.

**Comment by HaoYang670** [comment]
Just a small nit. The title should be `Fix CSV` not `Fix cvs`.
