### ISSUE TITLE
Files written with Julia's Arrow.jl in IPC format cannot be read by arrow-rs

### ISSUE THREAD

**Issue by pcjentsch** [apache/arrow-rs#1335]
**Describe the bug**
Files written with Julia's Arrow.jl IPC format have a footer that causes arrow-rs to panic. I think this is a bug on the side of `arrow-rs` because `arrow2` can read them.

**To Reproduce**
Reproduced in [this small repository](https://github.com/pcjentsch/testing_ipc_issue). 

```
git clone https://github.com/pcjentsch/testing_ipc_issue.git
cd testing_ipc_issue/test_ipc
cargo run
```

output
```
Ok((Schema { fields: [Field { name: "a", data_type: Int64, is_nullable: false, metadata: {} }], metadata: {} }, [Chunk { arrays: [Int64[1, 2, 3]] }]))
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/workaccount/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-9.0.2/src/ipc/reader.rs:636:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior**
`arrow-rs` should open the file as `arrow2` does.

**Comment by alamb** [comment]
Looks like there is a function that assumes there is a footer when there may not be -- looks pretty straight forward to me. I'll try and get a fix up in the next few days if no one else beats me to to it.

https://github.com/apache/arrow-rs/blob/573744953884c8860c9419439759c124c7d4186e/arrow/src/ipc/reader.rs#L636

Thank you for the great report @pcjentsch
