### ISSUE TITLE
Refactor `RecordBatch::validate_new_batch`

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-rs#1350]
**Describe the bug**
The function `validate_new_batch` constains some repetitive code. We could find a way to refactor it.
https://github.com/apache/arrow-rs/blob/master/arrow/src/record_batch.rs#L133-L166

**To Reproduce**

**Expected behavior**
Clean and readable code

**Additional context**

**Comment by HaoYang670** [comment]
Using `Iterator.find` or `Iterator.any` may be a good choice.

**Comment by HaoYang670** [comment]
@alamb Is this refactoring worth doing?

**Comment by alamb** [comment]
Hi @HaoYang670  -- sorry i am just getting back from a week away. I will check this (and the linked PR out) over the next day or two
