### ISSUE TITLE
Arrow release 10.0.0

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#1391]
Next weekly release follow on from #1304 

**Describe the solution you'd like**
Release the next version of arrow-rs

I think that there are certain API changes (https://github.com/apache/arrow-rs/pull/1345 and https://github.com/apache/arrow-rs/pull/1346 that will require a major version bump -- 10.0.0)

I plan to create a release candidate as ususal

cc @nevi-me @velvia @liukun4515  @tustvold

**Comment by liukun4515** [comment]
@alamb 
Please take this pull request https://github.com/apache/arrow-rs/pull/1388 in this release.
Thank you.

**Comment by alamb** [comment]
> Please take this pull request https://github.com/apache/arrow-rs/pull/1388 in this release.

Will do 👍

**Comment by alamb** [comment]
One of the CI tests is failing on master: https://github.com/apache/arrow-rs/issues/1398 which I think needs to be looked at prior to releasing 10.0.0

I can probably find time in a few hours to look into it, but if anyone else has time, that would be greatly appreciated 🙏

**Comment by alamb** [comment]
Update: I believe I have a fix for https://github.com/apache/arrow-rs/issues/1398 on  https://github.com/apache/arrow-rs/pull/1402

It is a test only fix so I will move ahead with creating a release candidate for arrow now even without that fix

**Comment by alamb** [comment]
RC is available: https://lists.apache.org/thread/0qdntovo308g1cxsj1h113b1lr6gfvhh

**Comment by alamb** [comment]
Released
