### ISSUE TITLE
Add doc examples for creating FixedSizeListArray

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#1392]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I wanted to quickly create an example for `FixedSizeListArray` but did not find any quickly on docs.rs:
https://docs.rs/arrow/9.1.0/arrow/array/struct.FixedSizeListArray.html

**Describe the solution you'd like**
Add a doc example, like XXX for `FixedSizeListArray`, perhaps by adapting an exsisting test

**Additional context**
Came up while I was reviewing https://github.com/apache/arrow-rs/pull/1379 and trying to file follow on tickets

**Comment by HaoYang670** [comment]
I can work on this !
