### ISSUE TITLE
Document use of unsafe in memory.rs

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#143]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-10974

There are ~10 uses of unsafe in memory.rs and we should document them according to the guidelines in the Arrow crate README

 
{code:java}
// JUSTIFICATION
//  Benefit
//      Describe the benefit of using unsafe. E.g.
//      "30% performance degradation if the safe counterpart is used, see bench X."
//  Soundness
//      Describe why the code remains sound (according to the definition of rust's unsafe code guidelines). E.g.
//      "We bounded check these values at initialization and the array is immutable."
let ... = unsafe { ... }; {code}

**Comment by ByteBaker** [comment]
There are no more `unsafe` blocks in the file. We can close this. @alamb

**Comment by alamb** [comment]
I agree -- I double checked and there are no more unsafe blocks in https://github.com/apache/arrow-rs/blob/master/object_store/src/memory.rs
