### ISSUE TITLE
Release version 9.1.1 and 10.0.1

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#1442]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
* https://github.com/apache/arrow-rs/pull/1418 introduced a bug in 9.1.0 for the parqet reader for delta pack encoding
* https://github.com/apache/arrow-rs/pull/1334 introduced a change in behavior (see https://github.com/apache/arrow-rs/issues/1425) in 10.0.0 that we would like to revert

**Describe the solution you'd like**
This ticket proposes creating patch releases 10.0.1 and 9.1.1 that contain fixes for the two issues listed above

**Describe alternatives you've considered**
Wait until version 10.1 (or 11) to come out, later this week

**Additional context**
Both @tustvold  and @sunchao  have offered to help make this release

The release process is documented in https://github.com/apache/arrow-rs/blob/master/dev/release/README.md

We don't have how to make a "patchset" documented however. I think the basic idea would be:

1. Create a branch at the appropriate release tag (aka make `9.1_maintenance` branch from the `9.0.0` tag)
2. `cherry-pick` / backport the changes to that new branch
2. Update the versions and CHANGELOG on the branch
3. Create a release candidate using `./dev/release/create-tarball.sh`

**Comment by tustvold** [comment]
I'm not sure there is much value in this now given that v11 has been released

**Comment by alamb** [comment]
Yeah, the value would be if someone couldn't update to 11 but needed to stay on 9 or 10

**Comment by tustvold** [comment]
Closing this as there doesn't appear to have been much community interest
