### ISSUE TITLE
Fix generate_interval_case integration test failure

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#1445]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

This ticket is for `generate_interval_case` case in integration test.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
See https://github.com/apache/arrow-rs/issues/1404

**Comment by liukun4515** [comment]
@viirya  Can you list the plan or missing item for IT in #1404 ?

**Comment by viirya** [comment]
Sure. Where should I put them? In #1404?
