### ISSUE TITLE
Document use of unsafe in buffer.rs

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#145]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-10976

There are ~32 uses of unsafe in buffer.rs and we should document them according to the guidelines in the Arrow crate README

 
{code:java}
// JUSTIFICATION
//  Benefit
//      Describe the benefit of using unsafe. E.g.
//      "30% performance degradation if the safe counterpart is used, see bench X."
//  Soundness
//      Describe why the code remains sound (according to the definition of rust's unsafe code guidelines). E.g.
//      "We bounded check these values at initialization and the array is immutable."
let ... = unsafe { ... }; {code}

**Comment by ByteBaker** [comment]
There are no more `unsafe` blocks in the file. We can close this. @alamb

**Comment by alamb** [comment]
Agreed -- this code has been rewritten since this ticket was filed so we can close it now
