### ISSUE TITLE
Hang due to infinite loop when reading some parquet files with RLE encoding and bit packing

### ISSUE THREAD

**Issue by anliakho2** [apache/arrow-rs#1458]
**Describe the bug**
Some parquet writers produce RLE encoded dictionaries with bit packing even if value count is not divisible by 8. 
This violates the assumption decoder makes about the number of values present in the bit-packed run, causing infinite loop and hang.

**To Reproduce**
Attempt to read parquet file where number of values is not power of 2 but RLE encoding with bit packing was used.

**Expected behavior**
File should be read correctly.

**Additional context**

**Comment by alamb** [comment]
Thank you for the report @anliakho2
