### ISSUE TITLE
The length kernel should work with `BinaryArray`s

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-rs#1464]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
The `length` kernel only supports `StringArray`s so far. I think it is reasonable to let it support `BinaryArray`s.

**Describe the solution you'd like**
let the function `length` and `bit_length` work with binary arrays

**Comment by HaoYang670** [comment]
@alamb I have this idea because BinaryArray and StringArray are very similar. But I'm not sure whether we need this feature.

**Comment by alamb** [comment]
I think supporting length for `BinaryArray` makes sense and would be good to add for completeness

**Comment by HaoYang670** [comment]
> I think supporting length for `BinaryArray` makes sense and would be good to add for completeness

Great! I will file a PR today!
