### ISSUE TITLE
Use Arrow take kernel Within ListArrayReader

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#1482]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The `ListArrayReader` currently uses a custom `remove_indices` function in order to strip nulls from its values array.

**Describe the solution you'd like**

This function is very similar to the arrow take kernel, and with some minor tweaks we can likely eliminate a non-trivial amount of code from the parquet crate, whilst also potentially improving performance

**Describe alternatives you've considered**

The code could remain unchanged

**Additional context**

Originally pointed out [here](https://github.com/apache/arrow-rs/pull/1448#discussion_r831080215)

**Comment by viirya** [comment]
@tustvold Do you plan to do this? If not, I might take some time in the weekend to play with this.

**Comment by tustvold** [comment]
That would be great if you could 👍
