### ISSUE TITLE
Add SIMD support for the `length` kernel

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-rs#1489]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
We could calculate `offset[1 ..] - offset[.. offset.len()]`  by simd.

**Describe the solution you'd like**
1. simd support for `length` kernel
2. some benchmark results.

**Comment by jhorstmann** [comment]
The compiler should be able to autovectorize the existing length kernel, at least it does in a smaller example: https://rust.godbolt.org/z/7sjrrfxqf

If this does not happen in the actual arrow kernel then we probably need to investigate whether `MutableBuffer::from_trusted_len_iter` somehow prevents that optimization.
