### ISSUE TITLE
Document use of unsafe in remaining files

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#150]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-10981

There are ~11 uses of unsafe in the following files and we should document them according to the guidelines in the Arrow crate README
{code:java}
 ./arrow/src/bytes.rs:5
 ./arrow/src/arch/avx512.rs:4
 ./arrow/src/bitmap.rs:1
 ./arrow/src/zz_memory_check.rs:1 {code}
{code:java}
// JUSTIFICATION
//  Benefit
//      Describe the benefit of using unsafe. E.g.
//      "30% performance degradation if the safe counterpart is used, see bench X."
//  Soundness
//      Describe why the code remains sound (according to the definition of rust's unsafe code guidelines). E.g.
//      "We bounded check these values at initialization and the array is immutable."
let ... = unsafe { ... }; 

{code}

**Comment by ByteBaker** [comment]
These files no longer exist and therefore the issue is no longer valid. @alamb

**Comment by alamb** [comment]
I agree this isn't tracking anything actionable now. Let's close this and file specific tickets when we encounter undocumented unsafe code
