### ISSUE TITLE
Document use of unsafe in datatypes.rs

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#152]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-10983

There are ~12 uses of unsafe in datatypes and we should document them according to the guidelines in the Arrow crate README

 
{code:java}
// JUSTIFICATION
//  Benefit
//      Describe the benefit of using unsafe. E.g.
//      "30% performance degradation if the safe counterpart is used, see bench X."
//  Soundness
//      Describe why the code remains sound (according to the definition of rust's unsafe code guidelines). E.g.
//      "We bounded check these values at initialization and the array is immutable."
let ... = unsafe { ... }; {code}

**Comment by ByteBaker** [comment]
No file with the name exists. I could find `datatype.rs` in `arrow-schema` which had no instances of `unsafe`. I found `data_type.rs` in `parquet` with 10 instances of `unsafe`. Not sure if the issue represents which one, since the context is old now.

Your call @alamb

**Comment by alamb** [comment]
I agree this isn't tracking anything actionable now. Let's close this and file specific tickets when we encounter undocumented unsafe code
