### ISSUE TITLE
Redundant error checking in ListArray, BooleanArray, BinaryArray and PrimitiveArray

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#1545]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
https://github.com/apache/arrow-rs/pull/1546 revealed that several Array types have error checking that is now redundant with `ArrayData::validate_full()`.

**Describe the solution you'd like**
Remove the redudant error checks and stop ignoring them during force validate run:

```rust
    #[cfg(not(feature = "force_validate"))]
```

The tests should continue to pass when run with 
```shell
cargo test --features=force_validate -p arrow
```

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
I believe this is no longer the case, feel free to reopen if I am mistaken
