### ISSUE TITLE
upgrade dependency "flatbuffers" to release after 0.8

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#156]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-10997

When the next version of [flatbuffers]([https://crates.io/crates/flatbuffers]) after 0.8.0 is released, we should upgrade arrow

See more detail on https://github.com/apache/arrow/pull/8936#pullrequestreview-555956172

**Comment by tustvold** [comment]
Closed by #2895
