### ISSUE TITLE
Improve Unit Test Coverage of MapArrayReader

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#1561]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

There is no unit test coverage of `MapArrayReader` that I can find

**Describe the solution you'd like**

We should have some unit tests

**Comment by frolovdev** [comment]
@tustvold I guess I can help, could you assign it to me?

**Comment by tustvold** [comment]
Thank you, FWIW I think MapArrayReader may currently be incorrect, see #1699, but up to you if you want to tackle that - Dremel encoding is very head hurty
