### ISSUE TITLE
protoc failed: Unknown flag: `--experimental_allow_proto3_optional`

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-rs#1574]
**Describe the bug**

I get an error when running `cargo test`. This is apparently due to a recent upgrade to prost and likely related to having an old protoc installed (I am using `libprotoc 3.11.4`). I am filing this issue to help others that hit the same problem.

```
error: failed to run custom build command for `arrow-flight v12.0.0 (/tmp/arrow-12.0.0.PitgR/apache-arrow-rs-12.0.0/arrow-flight)`

Caused by:
  process didn't exit successfully: `/tmp/arrow-12.0.0.PitgR/apache-arrow-rs-12.0.0/target/debug/build/arrow-flight-32d1e9d97d680e87/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=../format/Flight.proto

  --- stderr
  Error: Custom { kind: Other, error: "protoc failed: Unknown flag: --experimental_allow_proto3_optional\n" }

```

**To Reproduce**
Run `cargo test`

**Expected behavior**
Should not fail.

**Additional context**

**Comment by tustvold** [comment]
Yes, protoc no longer bundles protoc binaries and instead uses the system versions if available, or builds from source if not - see https://github.com/tokio-rs/prost/pull/610

Unfortunately the arrow-flight specification is using the somewhat new [explicit presence](https://github.com/protocolbuffers/protobuf/blob/main/docs/field_presence.md#how-to-enable-explicit-presence-in-proto3) feature of protobuf, and this will cause issues if compiling with an older version of protoc which doesn't support it.

Perhaps we could check the version of the protoc binary and return a more helpful error message if it is too old 🤔

**Comment by Ismail-Maj** [comment]
Building protobuf from source solved this problem for me, I had to also uninstall the ubuntu package `protobuf-compiler`.

**Comment by tustvold** [comment]
FWIW I believe if you uninstall `protobuf-compiler` and have `cmake` installed, prost will automatically compile the `protobuf-compiler` from source.

**Comment by alamb** [comment]
I think we have concluded this is not a bug but a "feature" of newer versions of prost

**Comment by alamb** [comment]
Thanks for the report @XinyuZeng  -- if you can contribute such an improvement that would be great ❤️
