### ISSUE TITLE
Require CI Checks

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#1578]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently prior to merge you need to check all the CI bar MIRI has run to completion. This is somewhat tiresome and potentially error prone.

**Describe the solution you'd like**

All CI checks bar MIRI should be required prior to merge. I don't know who has access to change this, perhaps @andygrove ??

**Describe alternatives you've considered**

We could not do this

**Comment by alamb** [comment]
I personally like the flexibility of not requiring CI checks (it allows me to accelerate things like README updates or if clippy has released a new breaking change).

That being said, I am not opposed to this change; I just feel like it actually adds more burden on the maintainers.

In terms of changing settings, I think apache projects don't control github settings directly, instead they check in a config file that then sets the permissions. 

https://github.com/apache/arrow-rs/blob/master/.asf.yaml

**Comment by tustvold** [comment]
If memory serves there is a way to override on a case-by-case basis, but potentially that require repos admin 🤔

I'll close this as I don't feel particularly strongly, I just thought it might be an oversight

**Comment by alamb** [comment]
> I'll close this as I don't feel particularly strongly, I just thought it might be an oversight

I think it is more like "arrow has always done it this way and it seems useful to me"
