### ISSUE TITLE
Update parquet thrift to 2.9.0 to support `LZ4_RAW` compression

### ISSUE THREAD

**Issue by kylebarron** [apache/arrow-rs#1604]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I'd like to support reading Parquet files with [`LZ4_RAW` compression](https://github.com/apache/parquet-format/blob/master/Compression.md#lz4_raw). It looks like this change happened in Parquet [version 2.9.0](https://github.com/apache/parquet-format/blob/master/CHANGES.md#version-290).

I see that arrow-rs depends on the `parquet-format` crate, so I'll also make an issue there. Ref https://github.com/sunchao/parquet-format-rs/pull/20

**Comment by tustvold** [comment]
Support for the codec within the metadata has been added, however, support for the compression codec has not been added.

This should be a case of adding a new `compression::Codec` and should be relatively straightforward

**Comment by marioloko** [comment]
It seems that the estimation of lz4 `uncompress_size` can cause overflow for small compress size. Any compress size smaller than 10 will overflow and though it will panic.

So now that we pass the `uncompressed_size` to the `decompress` method, I see too options now:

1. To change predictions formula to return 255 for any compressed size smaller than 10.
2. To only allow lz4_raw if `uncompressed_size` is provided, and to return an error saying 'LZ4_RAW without known `uncompressed_size` is unsupported'.

I would go with the second one, as even if the overflow error is only for small compression sizes, if the compressed size is 1G it will reserve ~250GB which is too much. So I would avoid prediction.

What do you think?

**Comment by tustvold** [comment]
2. seems sensible to me
