### ISSUE TITLE
Improve arrow-rs examples

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#1613]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
To help people get up to speed with a new library quickly, it is helpful to start with compiling examples. The arrow-rs [docs](https://docs.rs/arrow/latest/arrow/) have many small working examples,  but it would also be nice to also include some full featured examples.

clap-rs has a nice example of examples: https://github.com/clap-rs/clap/blob/v3.1.12/examples/README.md

This is especially useful as we start making them easier to find such as https://github.com/apache/arrow-cookbook/pull/185

**Describe the solution you'd like**
Here are some possible improvements
- [x] https://github.com/apache/arrow-rs/pull/1615
- [x] https://github.com/apache/arrow-rs/pull/1614
- [x] https://github.com/apache/arrow-rs/pull/3153
- [ ] Add example of reading from a CSV File, and computing some simple calculation (max of each columns?)
- [ ] Add example of calling computation kernels (showing how to downcast)
- [ ] Add automated checking (the way that clap does https://github.com/clap-rs/clap/blob/v3.1.12/examples/README.md#contributing)

**Comment by datapythonista** [comment]
I'm planning to work on this. What I'd personally do, is to have many small examples of increasing complexity. So, besides examples and recipes, it can be used as a tutorial, to learn Arrow topics step by step.

If people are happy with this, I'll start working on PRs for the next:

- Creating arrays for primitive types
  - With the array constructor (e.g. `Int32Array::from(vec![...])`)
  - With a builder (using `append_value` and `append_null)
  - With `collect()`
 - Creating arrays with null values. I'm unsure about this one, if the above are simple enough, probably we can have this in the above examples. But worth having this here for consideration for now
 - Creating arrays of more complex types (e.g. `Dictionary`, `Struct`...)
 - Creating `Schema`
 - Creating `RecordBatch`
 - Reading from different formats
   - Parquet
   - CSV
   - JSON
 - Writing to different formats (same)
 - Data manipulation and kernels. Will expand on this when the rest are done, for now just couple of simple examples to have something.

Not sure how feasible it is, but would be amazing if we could render those examples (which will have documentation explaining what's going on) direct to the Arrow cookbook. I think it's a bit tricky, but doable. And I think it's better than having to maintain two different cookbooks/examples, or just having them in one place.

Feedback on any of this very welcome.

**Comment by alamb** [comment]
I don't think this is tracking anything actionable now, so closing this ticket
