### ISSUE TITLE
Published Parquet documentation missing `arrow::async_reader`

### ISSUE THREAD

**Issue by kylebarron** [apache/arrow-rs#1617]
**Describe the bug**

As of today, the published docs at https://docs.rs/parquet/latest/parquet/ have a missing link to `arrow::async_reader`:

<img width="660" alt="image" src="https://user-images.githubusercontent.com/15164633/164988290-1fd6140a-0a0d-4e32-a3f3-7401152fe5aa.png">

Checking out the repo locally, I can reproduce this with `cargo doc --open`, whereas with `cargo doc --all-features --open` I am able to see the async docs. I'm not sure exactly how docs are published, but presumably this process just needs to add `--all-features`?

**To Reproduce**

```
git clone https://github.com/apache/arrow-rs
git checkout 5374289f
cd parquet
cargo doc --open
```

**Comment by tustvold** [comment]
Likely related to #1349
