### ISSUE TITLE
Validate array properties against schema

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#162]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11061

We have a problem when it comes to nested arrays, where one could create a <list[null]<primitive[non-null]>> where the array fields can't be null, but the list can have null slots.

This creates a lot of work when working with such nested arrays, because we have to create work-arounds to account for this, and take unnecessarily slower paths.

I propose that we prevent this problem at the source, by:
 * checking that a batch can't be created with arrays that have incompatible null contracts
 * preventing list and struct children from being non-null if any descendant of such children are null (might be less of an issue for structs)

**Comment by alamb** [comment]
Comment from Neville Dipale(nevi_me) @ 2020-12-29T10:44:06.932+0000:
<pre>[~andygrove] [~alamb] [~jorgecarleitao] I don't know if you've encountered the issues above, but they're making my work veery difficult on the parquet writer. There are equivalent checks in the C++ implementation, but I haven't looked at them in detail yet.</pre>

Comment from Andrew Lamb(alamb) @ 2021-01-03T13:58:53.658+0000:
<pre>I haven't encountered this [~nevi_me] -- but the basic idea of preventing batch creation with incompatible null contracts sounds like a good one to me</pre>

Comment from Neal Richardson(npr) @ 2021-04-09T17:59:59.579+0000:
<pre>This is listed as release blocking for 4.0--is that accurate?</pre>

**Comment by tustvold** [comment]
Closed by https://github.com/apache/arrow-rs/pull/3244
