### ISSUE TITLE
Ensure there is a single zero in the offsets buffer for an empty ListArray.

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#1620]
Good idea checking the C++ version. The docs for binary layout also mention

> The offsets buffer contains length + 1 signed integers
> ...
> and the last slot is the length of the values array

which would mean there has to be a single zero in the offsets buffer for an empty `ListArray`.

If this is a requirements it would be better to validate it when creating `ArrayData`. The code in [`ArrayData::validate_each_offset`](https://github.com/apache/arrow-rs/blob/b4642ecf9cb4a3d8b5741655fdc7d06b71bf41e6/arrow/src/array/data.rs#L1045) explicitly allow this case though:

```rust
        // An empty binary-like array can have 0 offsets
        if self.len == 0 && offset_buffer.is_empty() {
            return Ok(());
        }
```

I'm more hesitant to change this now, maybe let's wait for some more eyes on this.

_Originally posted by @jhorstmann in https://github.com/apache/arrow-rs/pull/1602#discussion_r854389543_

**Comment by HaoYang670** [comment]
I got this error:
```rust
---- ipc::reader::tests::read_generated_files_014 stdout ----
---- ipc::reader::tests::read_generated_files_014 stdout ----
thread 'ipc::reader::tests::read_generated_files_014' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("Offsets buffer size (bytes): 0 isn't large enough for Binary. Length 0 needs 1")', arrow/src/ipc/reader.rs:276:29

---- ipc::reader::tests::read_generated_streams_014 stdout ----
thread 'ipc::reader::tests::read_generated_streams_014' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("Offsets buffer size (bytes): 0 isn't large enough for Binary. Length 0 needs 1")', arrow/src/ipc/reader.rs:276:29

---- ipc::writer::tests::read_and_rewrite_generated_files_014 stdout ----
thread 'ipc::writer::tests::read_and_rewrite_generated_files_014' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("Offsets buffer size (bytes): 0 isn't large enough for Binary. Length 0 needs 1")', arrow/src/ipc/reader.rs:276:29

---- ipc::writer::tests::read_and_rewrite_generated_streams_014 stdout ----
thread 'ipc::writer::tests::read_and_rewrite_generated_streams_014' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("Offsets buffer size (bytes): 0 isn't large enough for Binary. Length 0 needs 1")', arrow/src/ipc/reader.rs:276:29
```
after deleting
https://github.com/apache/arrow-rs/blob/master/arrow/src/array/data.rs#L737-L740 
and
https://github.com/apache/arrow-rs/blob/master/arrow/src/array/data.rs#L1052-L1055

I don't know how data is generated in arrow-testing. Do empty arrays have empty offsets buffer in the testing data?

**Comment by HaoYang670** [comment]
@alamb Could you please help to recheck that whether empty array has empty offsets buffer in arrow-testing?

**Comment by alamb** [comment]
Hi @HaoYang670. I looked at the C++ implementation and I think it does allow an empty offsets buffer for an empty array -- namely the validation code skips doing any checks if `data.len == 0`:

https://github.com/apache/arrow/blob/c715bebbd89089f385c9996560866da23ea1ddda/cpp/src/arrow/array/validate.cc#L550

> I don't know how data is generated in arrow-testing.

I also don't know how this data was generated

**Comment by HaoYang670** [comment]
Does it mean that for empty (list array, binary array, and string array), both an empty offsets buffer and an offsets buffer with a single zero are allowed?

**Comment by HaoYang670** [comment]
But I also find list array does not allow empty offsets:
https://github.com/apache/arrow/blob/c70426f73326b3852d1bd7c31d98be4743f3fcba/cpp/src/arrow/array/array_nested.cc#L111-L113

**Comment by alamb** [comment]
> But it seems like list array does not allow empty offsets:

I think that code is for constructing a new array programatically. The validation code I think may be more permissive to support arrays that come in from other arrow implementations. 

Maybe it is time to ask on the dev@arrow.apache.org mailing list 🤔  I am out of ideas

**Comment by HaoYang670** [comment]
I will send an email

**Comment by HaoYang670** [comment]
It seems like Arrow tends to be ambiguous in this case, and an empty buffer or a buffer with just a 0 in it both are valid.

**Comment by HaoYang670** [comment]
Personally, I prefer keeping the current implementation.

**Comment by alamb** [comment]
Email link for cross reference: https://lists.apache.org/thread/w7g1zfqrjxx0bvrct0mt5zwxvdnc9nob

**Comment by HaoYang670** [comment]
Could we close this issue, or open it for more discussions?

**Comment by alamb** [comment]
I think the conclusion is "we should keep the current implementation, as imperfect as it may be, for backwards compatibility reasons"

Agree with closing -- anyone who disagrees please let me know and I'll reopen it

Thanks for the effort @HaoYang670
