### ISSUE TITLE
Release next version of arrow-rs after 12.0.0 (13.0.0)

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#1623]
This is a tracking ticket for whatever version will be released after 12.0.0 -- due around May 2 2022

**Comment by alamb** [comment]
I believe there have been some API changes like https://github.com/apache/arrow-rs/pull/1571 so we will need a new major version. 

Thus, I will plan for "lucky" release number 13.0.0

**Comment by zeroflaw** [comment]
I don't want to open a new ticket for this.

`parquet = { version = "12.0.0", default-features = false, features = ["zstd"] }`

Fails to compile with

`format!("{}", dt.format("%Y-%m-%d %H:%M:%S %:z"))
    |                      ^^^^^^ method not found in DateTime<Utc>`

https://github.com/apache/arrow-rs/blob/7da41c7328820241a1e9a06eb83cade2e1f08da4/parquet/Cargo.toml#L41

This should not have default-features = false

**Comment by alamb** [comment]
And we have an arrow-rs 13.0.0 release candidate: https://lists.apache.org/thread/zqfx9v1j8onwtfv98xqbn0zy9x5pvc04
