### ISSUE TITLE
Question: Why are there 3 types of `OffsetSizeTrait`s?

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-rs#1638]
**Which part is this question about**
In our code, there are 3 different `OffsetSizeTrait`: `OffsetSizeTrait`, `BinaryOffsetSizeTrait` and `StringOffsetSizeTrait`. The only difference between them is that `BinaryOffsetSizeTrait` and `StringOffsetSizeTrait` have a const `dataType`. 

My questions are: 
1. Why do we need three of them? Do we have to declare `dataType` as a const?
2. Could we just use one `OffsetSizeTrait` and get the `dataType` like this:
```rust
pub struct GenericBinaryArray<OffsetSize: OffsetSizeTrait> {
    data: ArrayData,
    value_offsets: RawPtrBox<OffsetSize>,
    value_data: RawPtrBox<u8>,
}

impl<OffsetSize: OffsetSizeTrait> GenericBinaryArray<OffsetSize> {
    ...
    pub fn get_datatype() -> DataType {
        if OffsetSize::is_large() {
            DataType::LargeBinary
        } else {
            DataType::Binary
        }
    }
    ...
}
```

**Comment by tustvold** [comment]
I don't see an obvious reason why they need to be separate traits, especially given that `get_datatype()` could be a `const fn`...

Perhaps @alamb or @jorgecarleitao remember some context of why these are the way they are?

**Comment by alamb** [comment]
> Perhaps @alamb or @jorgecarleitao remember some context of why these are the way they are?

They pre-date my time with the project. Maybe @nevi-me  or @andygrove  or @paddyhoran  have some memories or context to share

**Comment by jorgecarleitao** [comment]
I introduced them. At the time BinaryArray, LargeBinaryArray, StringArray and LargeStringArray were 4 different structs. The `OffsetSize`s were introduced to simplify the code via generics. At the time I did not realize that it could be even simpler. I agree that it can be simplified (arrow2 [has only one](https://github.com/jorgecarleitao/arrow2/blob/main/src/types/offset.rs#L5)).

**Comment by HaoYang670** [comment]
So I guess we can simplify the code by just reserving one `offsetTrait` and adding function `const fn get_datatype()` for `GenericBInaryArray` and `GenericStringArray` to get the `DataType` of the array.

**Comment by HaoYang670** [comment]
Close this issue as #1645 has been merged! Thank you for your all opinions!
