### ISSUE TITLE
[Rust]: Comparison of list arrays with differing offsets fails

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#166]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11267

Found this while reviewing the fix for ARROW-11239. The reason for the failure seems to be related to the combining of null bitmaps of parent/child data. When I changed `create_list_array` to not include null buffers the test passes.
{code:java}
    #[test]
    fn test_list_different_offsets() {
        let a =
            create_list_array(&[Some(&[0, 0]), Some(&[1, 2]), Some(&[3, 4])]);
        let b =
            create_list_array(&[Some(&[1, 2]), Some(&[3, 4]), Some(&[5, 6])]);        let a_slice = a.slice(1, 2);
        let b_slice = b.slice(0, 2);
        test_equal(&a_slice, &b_slice, true);
    } {code}
[~jorgecarleitao] [~nevi_me] FYI

**Comment by alamb** [comment]
Comment from Andrew Lamb(alamb) @ 2021-01-19T21:13:19.582+0000:
<pre>When I tested on https://github.com/apache/arrow/pull/9211/files -- this test case still fails (aka https://github.com/apache/arrow/pull/9211 does not seem to fix it)</pre>

**Comment by tustvold** [comment]
I think this was fixed by #1589

**Comment by alamb** [comment]
I ported the test above into a PR https://github.com/apache/arrow-rs/pull/1756
