### ISSUE TITLE
Unpin Flatbuffer version dependency

### ISSUE THREAD

**Issue by Cheappie** [apache/arrow-rs#1667]
Combining DataFusion 7.1.0 and Arrow 12.0.0 pose a challenge due to pinned flat buffer version, or at least that is what error message tells me. From what I have seen version pinning was a temporary fix to workaround incompatible changes in flatbuffers, but that doesn't apply anymore. Because these versions of flatbuffers dep were dropped from crates.io and anyway right now Arrow uses newest version of FlatBuffer dependency.

**Comment by tustvold** [comment]
FWIW Datafusion 7.1.0 has a version pin on arrow 9.0.0, and so cannot be used with arrow 12.0.0 regardless... What will likely end up happening is cargo will [link in](https://stackoverflow.com/questions/51714866/is-it-documented-that-cargo-can-download-and-bundle-multiple-versions-of-the-sam) both versions of arrow and complain if you try to mix types from one version with the other.
