### ISSUE TITLE
Support writing parquet to stdout

### ISSUE THREAD

**Issue by pacman82** [apache/arrow-rs#1687]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

I would like to write parquet files to "true" streams. E.g. stdout. This is in the context of the downstream `odbc2parquet` tool, for which I would like provide the option. This would allow my users to stream the parquet directly into a key value store or other sink just using pipes in their shell.

**Describe the solution you'd like**
I would like to see the `Seek` + `TryClone` requirement dropped as a requirement to initialize a `SerializedFileWriter`. From what I've seen at least the `Seek` requirement is used to determine the length of the Metadata written into the stream. Or tracking stream position in general. I feel `Seek` is to strong a requirement to just keep track of a position, or bytes written.

**Describe alternatives you've considered**
I have not considered any alternatives. Happy to hear about them, though.

**Comment by alamb** [comment]
This may be related to some work @tustvold  has planned for the parquet reader such as https://github.com/apache/arrow-rs/issues/1605

I haven't heard him discuss anything about the writer yet though

**Comment by tustvold** [comment]
As described in https://github.com/apache/arrow-rs/issues/937 it should be relatively straightforward to drop the seek requirement. A PR would be most welcome, otherwise I can try to take a stab when I have time

**Comment by pacman82** [comment]
Great. Sorry for missing the existing issue. I looked, but not thouroghly enough it seems. I also found it would be rather straight forward to drop it. Might become my first contribution, if I am not kept busy with issues on the downstream artefacts. My intention with this issue, was exactly to verify that such a PR indee would be welcome.

Thanks for the quick response!

**Comment by tustvold** [comment]
I'm currently working on this as part of fixing #1717

**Comment by pacman82** [comment]
@tustvold Great! This will unblock new features in downstream crate `odbc2parqet`. 🙇

**Comment by alamb** [comment]
Specifically, https://github.com/apache/arrow-rs/pull/1719 allows `SerializedFileWriter` to write to anything that implements `std::io::Write` as is common in the rust ecosystem 🎉
