### ISSUE TITLE
Release next version of arrow-rs after 13.0.0 (14.0.0) 

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#1692]
Tracking ticket for next release -- eta 

* release candidate ~ Friday May 13
* release ~ May 16, 2022

Things I am tracking as important to review prior to release:

- [x] ~merge (?)  https://github.com/apache/arrow-rs/pull/1682~
- [x] review https://github.com/apache/arrow-rs/issues/1660
- [x] fix https://github.com/apache/arrow-rs/issues/1695
- [x] Test with DataFusion https://github.com/apache/arrow-datafusion/pull/2528

**Comment by alamb** [comment]
I planned to make the release candidate tomorrow (Friday) but there is no pressing deadline for that either

**Comment by sunchao** [comment]
@alamb nothing from my side. Thanks for working on the release! 👍

**Comment by viirya** [comment]
Same from my side. Thanks @alamb!

**Comment by alamb** [comment]
It turns out I broke the docs.rs build https://github.com/apache/arrow-rs/issues/1695 -- I would like to fix that prior to release.

**Comment by alamb** [comment]
https://docs.rs/parquet/0.18.1/parquet/ seems to have worked! I'll make a real PR to arrow

The link is even correct 🎉 

![Screen Shot 2022-05-12 at 4 11 49 PM](https://user-images.githubusercontent.com/490673/168160047-322d2c80-07a1-4bf7-852a-58e088fcdfaa.png)

**Comment by tustvold** [comment]
Disappointing, but fair enough

**Comment by alamb** [comment]
> Disappointing, but fair enough

I need to find more capacity to review PRs / get them through - I struggle to find the time 😞  😿
