### ISSUE TITLE
Parquet command line tool installs "globally"?

### ISSUE THREAD

**Issue by kazuk** [apache/arrow-rs#1710]
**Describe the bug**

on this documentation.

https://github.com/apache/arrow-rs/blob/master/parquet/src/bin/parquet-rowcount.rs#L26
```
//! After this `parquet-rowcount` should be globally available:
```

showing `cargo install --help` as bellow.

```
$ cargo install --help
cargo-install 
Install a Rust binary. Default location is $HOME/.cargo/bin
<snip>
```

 I think, this is not globally. install for user.

**To Reproduce**

1. install `parquet`

```
cargo install parquet --features=cli
```

2. switch other user.
3. run `parquet-rowcount`

Error command not found.

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
Thanks for the report @kazuk  -- any help to fix this with a PR would be great!
