### ISSUE TITLE
Why `Parquet` is a part of `Arrow`?

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-rs#1715]
**Which part is this question about**
I find this description in the README of parquet crate:
```
This crate contains the official Native Rust implementation of Apache Parquet, which is part of the Apache Arrow project.
```

**Describe your question**
1. Why parquet is a part of Arrow? They should be independent, aren't they?
2. Arrow2 and Parquet2 are independent crates. Could we move parquet to a top level repo, for example `Apache/parquet-rs`?
https://github.com/jorgecarleitao/parquet2
4. Parquet should be maintained by Apache Parquet committee. Is it a little weird to let Apache Arrow contributors to maintain this crate ?

**Additional context**
No.

**Comment by HaoYang670** [comment]
@alamb Look forward to your opinion.

**Comment by alamb** [comment]
> Why parquet is a part of Arrow? They should be independent, aren't they?

My understanding is that the parquet project is a separate top level ASF project. 

https://projects.apache.org/committee.html?arrow

https://projects.apache.org/committee.html?parquet

> Arrow2 and Parquet2 are independent crates. Could we move parquet to a top level repo, for example Apache/parquet-rs?

Yes that would be fine -- right now they are in the same repo as the same people maintain them and it lowers the maintenance burden to have them in the same repo. I would personally not be opposed to separating them

I think it is a similar setup to the C++ implementation https://github.com/apache/arrow/tree/master/cpp which has arrow and parquet in the same foramt

> Parquet should be maintained by Apache Parquet committee. Is it a little weird to let Apache Arrow contributors to maintain this crate ?

I don't disagree -- the reason I am helping with both is that we need both in our project. 

Also, I think fast conversion between `arrow` <--> `parquet` is important and having them in the same repo may help with that.

**Comment by Ted-Jiang** [comment]
>Also, I think fast conversion between arrow <--> parquet is important and having them in the same repo may help with that.
+1 👍

@alamb  And i have a question, if parquet-rs is only schema compatible or full functional support as parquet-mr?
And is there any benchmark between java and rust?

**Comment by tustvold** [comment]
We intend to be fully functionally compatible with parquet-mr, please do file feature requests if you find any areas where we aren't. I think we're mostly there, aside from page index support.

As for performance comparison, I would be disappointed if we aren't significantly faster, but I do not have any benchmarks to verify this. Again I would be very interested in areas where we are slower.

**Comment by ahmedriza** [comment]
We've been using `arrow-rs` in place of a legacy Scala code base that uses `parquet-mr` and found that the `arrow-rs`  is catching up quite nicely now.
