### ISSUE TITLE
GenericBinaryArray::from_list and GenericStringArray::from_list Ignores Offset

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#1726]
**Describe the bug**

Whilst perusing the code I noticed that `GenericBinaryArray::from_list` and `GenericBinaryArray::from_list` have the following logic

```
let mut builder = ArrayData::builder(Self::get_data_type())
    .len(v.len())
    .add_buffer(v.data_ref().buffers()[0].clone())
    .add_buffer(v.data_ref().child_data()[0].buffers()[0].clone());
if let Some(bitmap) = v.data_ref().null_bitmap() {
    builder = builder.null_bit_buffer(bitmap.bits.clone())
}

let data = unsafe { builder.build_unchecked() };
```

This does not propagate any offset that might be present in the source data

**To Reproduce**

I suspect if you slice an ArrayList and then pass it to this method, you will lose the offset position.

**Expected behavior**

The offset, and probably the null count, should be preserved by both methods

**Comment by tustvold** [comment]
The issue also seems to appear in `From<FixedSizeListArray> for FixedSizeBinaryArray` and similar methods

**Comment by HaoYang670** [comment]
I will work on this if no one else what to do it.
