### ISSUE TITLE
Rename the `string` kernel to `concatenate_elements`

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-rs#1747]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
This is a follow-up of #1720.
We have added `concatenate by elements` support for string array and put it into the new created `string` kernel.
I suggest we should rename the kernel `concatenate_elements`.

There are some reasons I thought why `concatenate_elements` is better than `string`:
1. The name of the compute kernel should express what kind of operation will be done on an array, such as `cast`, `aggregate` ...
2. We can support the `concatenate_elements` operation on binary array, list array and other nested types. So `string` is not an appropriate name.
3. In cudf (which is based on Arrow c++, and more GPU supported), there are similar kernels and we can refer to their names.: https://github.com/rapidsai/cudf/blob/branch-22.08/cpp/src/lists/combine/concatenate_list_elements.cu
https://github.com/rapidsai/cudf/blob/branch-22.08/cpp/src/lists/combine/concatenate_rows.cu

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HaoYang670** [comment]
cc @alamb @tustvold @viirya. Looking forward to your opinions!

**Comment by alamb** [comment]
Hi @HaoYang670 
> I suggest we should rename the kernel concatenate_elements.

If you mean rename `arrow/src/compute/kernels/string.rs` to ``arrow/src/compute/kernels/concat_elements.rs` I think it is a great idea (and ideally we could do it in the next day or two before we released arrow 15 avoiding a breaking change in a released version)
