### ISSUE TITLE
[CI]docker-compose setup should enable caching

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#175]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11485

Our docker-compose setup is able to cache C++ compilation artifacts accross invocations, see
https://github.com/apache/arrow/blob/master/docker-compose.yml#L58
and
https://github.com/apache/arrow/blob/master/docker-compose.yml#L129

Ideally the same should be doable for Rust as well.

**Comment by jorgecarleitao** [comment]
No longer applicable.
