### ISSUE TITLE
 Enable column_page_reader read specific row ranges record

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/arrow-rs#1792]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
I would recommend the approach I described https://github.com/apache/arrow-rs/pull/1791#pullrequestreview-996352857 critically, a page does not know what constitutes a row. This highly non-trivial logic is handled in RecordReader, which will therefore need to drive the interpretation of any row-based filtering.

**Comment by Ted-Jiang** [comment]
> I would recommend the approach I described [#1791 (review)](https://github.com/apache/arrow-rs/pull/1791#pullrequestreview-996352857) critically, a page does not know what constitutes a row. This highly non-trivial logic is handled in RecordReader, which will therefore need to drive the interpretation of any row-based filtering.

Thanks ❤️

**Comment by jeffbski-sketch** [comment]
I was just wondering what the status and ETA of this item is. I see maybe there is a non-public partial implementation already in the code. What's left to do for this? Thanks!

**Comment by tustvold** [comment]
I intend to polish up the remaining bits and pieces in time for the next release - https://github.com/apache/arrow-rs/issues/2382
