### ISSUE TITLE
Sliceable BitMap

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#1802]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently `BitMap` is a simple wrapper around a `Buffer`. This limits it to slicing on multiples of 8, as `Buffer` can only slice at byte boundaries.

**Describe the solution you'd like**

Add an offset and length to `BitMap`, updating the accessors to take this into account. This may require deprecating and removing `buffer_ref`, and/or making it panic if non-zero offset.

Add a slice method to `BitMap` that uses the offset and length to perform zero-copy slicing.

**Describe alternatives you've considered**

We could not do this.

**Additional context**

Feeds into https://github.com/apache/arrow-rs/issues/1799

**Comment by HaoYang670** [comment]
Related to this issue: https://github.com/apache/arrow-rs/issues/1728
