### ISSUE TITLE
Rename ArrayData::validate_dictionary_offset

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#1812]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

`ArrayData::validate_dictionary_offset` no longer just validates dictionary offsets and instead verifies array offsets, decimal precision, etc..

**Describe the solution you'd like**

I would like to propose renaming `ArrayData::validate_dictionary_offset` to `ArrayData::validate_values`. Potentially first deprecating the old method.

**Describe alternatives you've considered**

We could not do this.

**Additional context**

**Comment by viirya** [comment]
+1 for this.
