### ISSUE TITLE
Larger CI Runners to Prevent MIRI OOMing and Improve CI Times

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#1833]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Since updating MIRI in #1828 it is periodically OOMing - https://github.com/apache/arrow-rs/actions/workflows/miri.yaml

![image](https://user-images.githubusercontent.com/1781103/173018511-f61ee955-f90a-467e-8666-f9e1f017d088.png)

https://github.com/apache/arrow-rs/actions/runs/2473012537

**Describe the solution you'd like**

I'm not entirely sure what the best course of action here is, rolling back to a 6 month old MIRI is not ideal and would require backing out changes in #1822, but then neither is having it randomly fail.

It has been a long-time annoyance of mine that the the CI currently takes ~40 minutes to chug through, despite significant caching. This is largely because the runners are rather piddly - https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources. This also precludes automatically running any meaningful benchmarks (#1274). Perhaps we should invest some time into a more powerful CI system such as [buildkite](https://buildkite.com/apache-arrow) which is used by other arrow projects...

**Describe alternatives you've considered**

None

**Comment by alamb** [comment]
other parts of the arrow project (e.g. C++) was talking about this -- there may be more beefy infrastructure we could take advantage of there

**Comment by jhorstmann** [comment]
I recently noticed some of the fuzzing tests for filters running for a long time. Watching `htop` also showed memory usage increasing while running `fuzz_filter`. Memory usage was already at ~8Gb before that test though.

Maybe some of those tests could be excluded from running in the miri cfg.

**Comment by tustvold** [comment]
Another dimension this may provide improvement is disk space, with the 14GB proving insufficient for some use-cases (#2004)

**Comment by viirya** [comment]
Recently I saw many times of running out of disk space in CI. Although it seems better now.

**Comment by alamb** [comment]
I got inspired this afternoon while waiting for some other PRs to finish up CI and started a few improvements using the github runners via https://github.com/apache/arrow-rs/issues/2149

**Comment by tustvold** [comment]
The improvements to split up the CI have largely addressed this, so closing
