### ISSUE TITLE
Interval is out of spec

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#187]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11645

The DataType interval is currently implemented as a i32 or i64. However, that is incorrect and does not follow the spec.
{code:java}
// DAY_TIME - Indicates the number of elapsed days and milliseconds,
//   stored as 2 contiguous 32-bit integers (8-bytes in total).  Support
//   of this IntervalUnit is not required for full arrow compatibility.
{code}
See [https://github.com/apache/arrow/blob/master/format/Schema.fbs]

E.g. I think that IntervalDayTimeType should be a `struct(i32,i32)` with a C representation or something, which is how it is defined in the spec.

This would also make it easier to read from and write to, as we do not need to transmute or bitmask the values to get the correct values.

**Comment by waitingkuo** [comment]
@alamb is it solved?

https://github.com/apache/arrow-rs/blob/7a74465f2b8b622428e562f23298b7cce16886f7/arrow/src/datatypes/types.rs#L99-L103

https://github.com/apache/arrow-rs/blob/7a74465f2b8b622428e562f23298b7cce16886f7/arrow/src/datatypes/types.rs#L224-L264

**Comment by alamb** [comment]
I agree this issue is not tracking anything actionable anymore. Thanks for the spot @waitingkuo
