### ISSUE TITLE
Explicitly declare the features used for each dependency

### ISSUE THREAD

**Issue by martin-g** [apache/arrow-rs#1876]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Verifying Arrow-rs release [requires](https://lists.apache.org/thread/fo8w7zz94xl2551vp6qpc66m22nzqdoo) 15GB of disk space.

**Describe the solution you'd like**

For each dependency in all Cargo.toml files explicitly disable the default features and list explicitly the features used by Arrow-rs.
This should reduce the disk space and CPU usage.

**Describe alternatives you've considered**

Option 1: Split the repository/project into several ones, e.g. extract `parquet` to its own repository.

The Arrow team prefers to keep the code in one repository for easier maintainance and development.

**Additional context**

N/A

**Comment by liukun4515** [comment]
Hi @martin-g 
Please take a look this issue https://github.com/apache/arrow-datafusion/issues/2835 about datafusion.
