### ISSUE TITLE
Disallow cast from other datatypes to NullType

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#1923]
**Describe the bug**

We allow casting from other datatypes to NullType (see `can_cast_types`). I suspect that this is a mistake.

For example, Spark doesn't allow casting from any datatypes to NullType.

I also checked C++ Cast kernels. Mostly the datatypes cannot cast to NullType (e.g. https://github.com/apache/arrow/blob/53752adc6b81166cd4ee7db5a819494042f29197/cpp/src/arrow/compute/kernels/scalar_cast_test.cc#L187-L211). I said "mostly" because I don't see explicit tests for other cases like Decimal, but I suspect that it is not allowed but just lack of test coverage.

I don't see there is cast kernel in C++ for casting to NullType except for a special case (`dict<null> -> null`): https://github.com/apache/arrow/blob/53752adc6b81166cd4ee7db5a819494042f29197/cpp/src/arrow/compute/kernels/scalar_cast_numeric.cc#L748-L751. Even for that, there is a comment questioning about it.

**To Reproduce**

**Expected behavior**

Cast kernel should not allow casting from any datatypes to NullType.

**Additional context**

**Comment by liukun4515** [comment]
The result of discussion: https://github.com/apache/arrow-rs/pull/1922#discussion_r905436410

**Comment by liukun4515** [comment]
I will give a follow-up pr to remove casting other data type to Null Data type.
