### ISSUE TITLE
Specify behavior of filter kernel on `null`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#194]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11846

Currently, the behavior of `filter` is undefined on null values.

This leads to a few issues in cases where you may have a `boolean` array containing `null` values. For instance, I created a `null_to_false` which has to manipulate the underlying buffers in order to combine the null-bits with false. The C++ `filter` kernel allows specifying the behavior on nulls. Thoughts on adding a method that takes an additional parameter to configure the behavior, and then picking a "default" behavior for the existing implementation?
{code:java}
pub enum NullFilterBehavior {
  // Include values where the filter was NULL.
  EMIT,
  // Exclude values where the filter was NULL.
  SKIP,
  // Ignore the null bits. Behavior is undefined.
  UNDEFINED,
}

pub struct FilterConfig {
  null_behavior: NullFilterBehavior
}

impl Default for FilterConfig {
  fn default() -> Self {
    Self {
      null_behavior: NullFilterBehavior::UNDEFINED,
    }
  }
}

pub fn filter(array: &Array, filter: &BooleanArray) -> Result<ArrayRef> {
  filter_config(array, filter, FilterConfig::default()
}

pub fn filter(array: &Array, filter: &BooleanArray, config: FilterConfig) -> Result<ArrayRef> {
 ...
}
{code}
It seems like implementing such a method could be done by allowing the BitChunksIterator to AND / OR each of the chunks before passing it to the BitSlices iterator.

**Comment by alamb** [comment]
Comment from Andrew Lamb(alamb) @ 2021-03-04T19:34:47.785+0000:
<pre>[~bchambers] the idea of allowing a choice for behavior seems reasonable to me</pre>

**Comment by tustvold** [comment]
The filter kernel consistently interprets null as false
