### ISSUE TITLE
Different sort behavior for floats between single-column and lexicographical sort

### ISSUE THREAD

**Issue by jhorstmann** [apache/arrow-rs#1941]
**Describe the bug**

Single column `sort_to_indices` uses the total order relation: https://github.com/apache/arrow-rs/blob/d52be30f779240b7aa621ebee5d5a6d942445be0/arrow/src/compute/kernels/sort.rs#L203

Lexicographical comparison uses a custom comparator that puts any NaN last: https://github.com/apache/arrow-rs/blob/d52be30f779240b7aa621ebee5d5a6d942445be0/arrow/src/array/ord.rs#L70

These could give different results for negative NaN values.

**To Reproduce**

I'll try to come up with a test that shows differing behavior.

**Expected behavior**

Sorting behavior should be the same for both kernels.

Ideally also min/max kernels should use the same ordering, but that gets more difficult to implement generically with the simd kernels.

**Additional context**

**Comment by tustvold** [comment]
Closed by #3510
