### ISSUE TITLE
Write error ColumnChunk to the Parquet File instead of ColumnMetaData

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-rs#1946]
**Describe the bug**
I'm working on the https://github.com/apache/arrow-rs/pull/1935, and go through the write path of rust-version.

I find that parquet-write write some error data which is ColumnChunk to the file, you can find the logic from https://github.com/apache/arrow-rs/blob/9f7b6004d365b0c0bac8e30170b49bdd66cc7df0/parquet/src/file/writer.rs#L441

From my knowledge about parquet format in this https://github.com/apache/parquet-format/blob/54e53e5d7794d383529dd30746378f19a12afd58/src/main/thrift/parquet.thrift#L789 and https://github.com/apache/parquet-format#file-format, the data after column data is  `ColumnMetaData`, not ColumnChunk

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by liukun4515** [comment]
I will write to fix the this point.

**Comment by liukun4515** [comment]
@sunchao @alamb  PTAL

**Comment by liukun4515** [comment]
@tustvold 
I read the java version of parquet write in the https://github.com/apache/parquet-mr/blob/e06384455567c56d5906fc3a152ab00fd8dfdf33/parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetFileWriter.java#L916, and it do't follow the format https://github.com/apache/parquet-mr/blob/e06384455567c56d5906fc3a152ab00fd8dfdf33/parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetFileWriter.java#L916 writing the Column Metadata behind each column chunk.
Is there any missing information for me? 
I'm confused about the logic about write path between rust-parquet and java-parquet.

**Comment by liukun4515** [comment]
I created a ticket in the Parquet-MR for java version
https://issues.apache.org/jira/browse/PARQUET-2162

**Comment by tustvold** [comment]
The TLDR is we wrote the wrong thing after the column chunk, but no implementations actually read this data as it is already present in the footer, and so we never noticed

**Comment by alamb** [comment]
Thank you -- added to the original description
