### ISSUE TITLE
Reduce macro usage by abstracting over arrays that have a value or value_unchecked method

### ISSUE THREAD

**Issue by jhorstmann** [apache/arrow-rs#1948]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Many Array types have a `value` and `value_unchecked` method. This method is not part of the `Array` trait because the return type would need to be a generic parameter, which would make the `Array` trait no longer object safe.

The absence of such a method makes it more difficult to abstract over different array types. For example the [iterators have a lot of code duplication](https://github.com/apache/arrow-rs/blob/9f7b6004d365b0c0bac8e30170b49bdd66cc7df0/arrow/src/array/iterator.rs#L135) or the [comparison functions use macros as a workaround](https://github.com/apache/arrow-rs/blob/9f7b6004d365b0c0bac8e30170b49bdd66cc7df0/arrow/src/compute/kernels/comparison.rs#L60).

**Describe the solution you'd like**

I propose to add another trait (maybe named `ArrayAccessor`) that would unify the types:

```rust
trait ArrayAccessor: Array {
    type Item;
    fn value(&self, index: usize) -> Self::Item;
    unsafe fn value_unchecked(&self, index: usize) -> Self::Item;
}
```

This could be implemented by `PrimitiveArray`, `BooleanArray`, `StringArray`, `BinaryArray, `ListArray` and maybe more.

An interesting case is `DictionaryArray` where we might want two different accessors, one for keys and another that resolves keys to their corresponding values (haven't checked whether this would be possible to implement in a generic way).

Iterators and comparison kernels could then be implement in a generic way using this trait, reducing the amount of macros in the code base.

**Describe alternatives you've considered**

We could keep using macros.

**Comment by jhorstmann** [comment]
After reading https://doc.rust-lang.org/reference/items/traits.html#object-safety again this could also work as an associated type on `Array` itself, as long as it is only used by methods that have an explicit `where Self: Sized` bound.

**Comment by martin-g** [comment]
> ```rust
>  fn value(&self, index: usize) -> Self::Item;

Shouldn't this return `Option<Self::Item>` ?

**Comment by tustvold** [comment]
> as long as it is only used by methods that have an explicit where Self: Sized bound.

Unfortunately this would require you to specify the associated type as part of constructing the trait object, i.e. `Box<dyn Array<Item = Foo>>`.

That being said, having a separate `ArrayAccessor` trait makes a lot of sense to me

**Comment by tustvold** [comment]
The ArrayAccessor trait has been added and is slowly being integrated, I think this issue can now be closed as it isn't tracking anything specific
