### ISSUE TITLE
Incorrect null_count of DictionaryArray

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#1962]
**Describe the bug**

`null_count` of `DictionaryArray` calls the default implementation which gets null count of its `data` member. So basically it looks at the null count of keys. If a corresponding value of a key is null, `null_count` cannot get correct null count.

`is_null` and `is_valid` also have same issue.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
Removing bug as it was determined that this was not a bug

**Comment by viirya** [comment]
Yea, thanks @alamb
