### ISSUE TITLE
Support DictionaryArray in Like Kernels

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#1975]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Noticed whilst implementing https://github.com/apache/arrow-datafusion/pull/2808, we currently lack support for dictionary arrays in the like comparison kernels

**Describe the solution you'd like**

We should support dictionary arrays in these kernels

**Describe alternatives you've considered**

We could not support them

**Additional context**
None

**Comment by psvri** [comment]
Hello,

I would like to pick this up if no else is working on it.

**Comment by tustvold** [comment]
That would be brilliant, you may be able to make use of the new ArrayAccessor plumbing to avoid code duplication
