### ISSUE TITLE
Parquet Writer Ignores Statistics specification in `WriterProperties`

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2014]
**Describe the bug**

The parquet writer does not respect the settings in WriterProperties for whether to compute statistics, and the max size of the computed statistics.

**To Reproduce**

Inspect code

**Expected behavior**

We should not have configuration options that have no effect

**Comment by alamb** [comment]
Update here: https://github.com/apache/arrow-rs/pull/2022 fixes the writer to respect the "do/don't compute stats", however the "max size of computed statistics" setting is still ignored, which is presumably why @tustvold  left it open.

@tustvold  do you mind if I break out the "max size of stats setting is ignored" into a separate ticket to make the current state of affairs clearer?

**Comment by tustvold** [comment]
SGTM or feel free to modify this ticket directly

**Comment by alamb** [comment]
Follow on ticket is https://github.com/apache/arrow-rs/issues/2033
