### ISSUE TITLE
Document patch release process

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#202]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11934

Now that we moved to voting on source releases for patch releases, we need to document the process for doing so in the Rust implementation.

 

Google doc for discussion / collaboration: https://docs.google.com/document/d/1i2Elk6J0H4nhPeQZdLDyqvHoRbsabx2iOTXLHxxNqRE/edit?usp=sharing

**Comment by alamb** [comment]
Comment from Andy Grove(andygrove) @ 2021-03-12T17:37:02.618+0000:
<pre>[~npr] Could I ask you to take a look at this google doc when you get a chance. In particular, could you participate in the conversation I am having with [~emkornfield] about whether we can make language-specific patch releases?</pre>

**Comment by jorgecarleitao** [comment]
I think that this as since been deprecated, as we have full release independence. Closing. cc @andygrove @alamb
