### ISSUE TITLE
3.0.1 patch release

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#204]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11948

Spreadsheet where I am tracking the fixes that get merged to maint-3.0.x

 

https://docs.google.com/spreadsheets/d/111k0PGEVzxg1k7Q_d_1kV7E24VRB3DVJP1MnQImVrCc/edit?usp=sharing

**Comment by jorgecarleitao** [comment]
Closing as not applicable.
