### ISSUE TITLE
Casting between timestamp types should use scalar multiply/divide kernels

### ISSUE THREAD

**Issue by jhorstmann** [apache/arrow-rs#2074]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

See https://github.com/apache/arrow-rs/blob/86543a4b835f898308bd28a33d0da9d2ea7a9b35/arrow/src/compute/kernels/cast.rs#L1045

This creates a temporary array initialized with all same values. Instead it should use the scalar multiply/divide kernels for improved performance.

**Comment by tustvold** [comment]
This was implemented in #2846
