### ISSUE TITLE
Make skip value in ByteArrayDecoderDictionary avoid decoding

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/arrow-rs#2088]
Possibly something for a follow up PR, but it would be nice if we could avoid decoding values only to dump them on the floor

_Originally posted by @tustvold in https://github.com/apache/arrow-rs/pull/2076#discussion_r922305417_

**Comment by tustvold** [comment]
I think a lot of this has been implemented by @thinkharderdev in #2089 🎉
