### ISSUE TITLE
Why does `serde_json` specify the `preserve_order` feature in `arrow` pacakge

### ISSUE THREAD

**Issue by togami2864** [apache/arrow-rs#2095]
**Which part is this question about**
library

**Describe your question**
I want to know why is `preseve_order` specified in `arrow`.
https://github.com/apache/arrow-rs/blob/02371d2be6b9fd276ea3423d51122c47935b7714/arrow/Cargo.toml#L43
Because this feature turned on, our application using `arrow` wouldn't work well when getting the output of serialized JSON.
In my local env, all of the tests pass in this repository after removing the feature like this.
```
// Cargo.toml
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
```

**Additional context**
- arrow v18.0.0
- [Cargo enables all feature of the dependencies.](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification)(we can't exclude features that dependencies have.)

**Comment by tustvold** [comment]
@nevi-me 's comment https://github.com/apache/arrow-rs/issues/1882#issuecomment-1169528840 would suggest this can likely be removed
