### ISSUE TITLE
IP clearance for object_store_rs donation

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#2096]
# Description

This ticket serves as a coordination point for the ip clearance process in  https://github.com/apache/arrow-rs/issues/2030

https://github.com/apache/arrow-rs/pull/2081 brings in code from `object_store_rs` https://github.com/influxdata/object_store_rs/commit/3c51870ac41a90942c2e45bb499a893d514ed1da

These are the authors (according to `git shortlog 3c51870ac41a90942c2e45bb499a893d514ed1da -se`):
- [ ] Dom <dom@itsallbroken.com> @domodwyer 
- [ ] Marco Neumann <marco@crepererum.net> @crepererum 
- [ ] Marko Mikulicic <mkm@influxdata.com> @mkmik 
- [ ] Marko Mikulicic <mmikulicic@gmail.com> @mkmik 
- [ ]  Raphael Taylor-Davies <1781103+tustvold@users.noreply.github.com> @tustvold 
- [ ] Raphael Taylor-Davies <r.taylordavies@googlemail.com> @tustvold 
- [ ] Robert Pack <42610831+roeap@users.noreply.github.com>  @roeap
- [ ]  Tim Van Wassenhove <github@timvw.be> @timvw
- [x]  Will Jones <willjones127@gmail.com> @wjones127
- [ ]   kodiakhq[bot] <49736102+kodiakhq[bot]@users.noreply.github.com> (BOT)

SVN location of ip-clearance (in https://svn.apache.org/repos/asf/incubator/public/trunk/content/ip-clearance/)

# To Do List:
- [x] Complete ip-clearance form https://svn.apache.org/repos/asf/incubator/public/trunk/content/ip-clearance/arrow-rust-object-store.xml
- [x] Send InfluxData Corporate Software Grant to ASF
- [x] Receipt acknowledged from ASF
- [x] Notify all contributors

**Comment by tustvold** [comment]
Not sure if relevant, but all contributors will have signed the InfluxData CLA which may be sufficient

**Comment by alamb** [comment]
@tustvold , @crepererum, @domodwyer, @mkmik and @timvw and @wjones127 , as part of the IP clearance process to donate the object_store_rs code to the Apache Software Foundation,  I am required to remind you that you are responsible for ensuring that you have all the necessary agreements. 

Specifically, please ensure that a Corporate CLA is recorded if such is required to authorize their contributions under their individual CLA.

Please let me know if you have any questions

**Comment by wjones127** [comment]
I've submitted my ICLA. Thanks for coordinating @alamb ! 🙌

**Comment by alamb** [comment]
This is great @roeap  -- thanks -- I will fix the XML

**Comment by alamb** [comment]
https://svn.apache.org/repos/asf/incubator/public/trunk/content/ip-clearance/arrow-rust-object-store.xml is updated

**Comment by alamb** [comment]
Ok, its official 🎉 
https://incubator.apache.org/ip-clearance/

Lists https://incubator.apache.org/ip-clearance/arrow-rust-object-store.html

(built from https://svn.apache.org/repos/asf/incubator/public/trunk/content/ip-clearance/arrow-rust-object-store.xml)

![Screen Shot 2022-07-22 at 1 43 49 PM](https://user-images.githubusercontent.com/490673/180495030-b21ea5b4-510c-4f94-ba08-84f8155d3017.png)

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#2096](https://github.com/apache/arrow-rs/issues/2096)
