### ISSUE TITLE
Support skip_rep_levels in ColumnLevelDecoder

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/arrow-rs#2108]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
https://github.com/apache/arrow-rs/blob/c58554453bec8f4a78d503e79576b85108b210b5/parquet/src/column/reader/decoder.rs#L84-L90
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ted-Jiang** [comment]
@tustvold please add `help wanted` 😊

**Comment by tustvold** [comment]
Why is this closed?

**Comment by Ted-Jiang** [comment]
```
 fn skip_rep_levels(&mut self, _num_records: usize) -> Result<(usize, usize)> {
        Err(nyi_err!("https://github.com/apache/arrow-rs/issues/1792"))
    }
```
Not finished reopen it.😂
