### ISSUE TITLE
Publicly export MapFieldNames

### ISSUE THREAD

**Issue by alanhe** [apache/arrow-rs#2118]
**Describe your question**
`arrow::array::MapBuilder` is public (https://github.com/apache/arrow-rs/pull/1355), but `MapFieldNames` is not, making it impossible to call `new()` and `with_capacity()` with a proper value.

https://github.com/apache/arrow-rs/blob/3096591520d303eb34a432c82733e86f34999232/arrow/src/array/builder/map_builder.rs#L61-L68

I guess `MapFieldNames` should be exported too, should it?

**Comment by tustvold** [comment]
This was an accidental bug introduced by #1879

**Comment by alamb** [comment]
@tustvold  is this a regression in 19.0.0 (aka should I cut a new release candidate)?

**Comment by tustvold** [comment]
I think it was a regression that landed in 17.0.0 and was only just noticed...
