### ISSUE TITLE
Please make the MapBuilder values_field nullable a configurable value

### ISSUE THREAD

**Issue by alanhe** [apache/arrow-rs#2119]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
With `MapBuilder`, it's not possible to build the sample schema described in the spec: https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#backward-compatibility-rules-1
```
optional group my_map (MAP) {
  repeated group map {
    required binary str (UTF8);
    required int32 num;
  }
}
```

because in Line 141, nullable is hard-coded to `true`.

https://github.com/apache/arrow-rs/blob/3096591520d303eb34a432c82733e86f34999232/arrow/src/array/builder/map_builder.rs#L138-L142

So, it will also be `optional int32 num`.

**Describe the solution you'd like**
Can we make it configurable?

**Comment by LiShiZhensPi** [comment]
hi, I would like try to fix this :)

**Comment by Weijun-H** [comment]
After reviewing the code, it appears that the bug has been resolved.

``` rust
// optional group my_map (MAP_KEY_VALUE) {
//   repeated group map {
//     required binary key (UTF8);
//     optional int32 value;
//   }
// }
{
    arrow_fields.push(Field::new(
        "my_map3",
        DataType::Map(
            Box::new(Field::new(
                "map",
                DataType::Struct(vec![
                    Field::new("key", DataType::Utf8, false),
                    Field::new("value", DataType::Int32, true),
                ]),
                false, // (#1697)
            )),
            false,
        ),
        true,
    ));
}
```
