### ISSUE TITLE
Support filter for parquet data type

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-rs#2126]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Currently, we want to filter a column in parquet file whose logical data type is decimal or string.

In the parquet, the data of decimal and string will be stored as `binary` and `fixed_len_binary`.

parquet-rs doesn't has the `filter` system or the comparison system.

**Describe the solution you'd like**

implement the `filter` system and comparison system in parquet-rs.

**Describe alternatives you've considered**

**Additional context**

**Comment by liukun4515** [comment]
Do you have any opinions and suggestions?
@tustvold @Ted-Jiang @alamb

**Comment by tustvold** [comment]
Could you perhaps expand a bit on what API you are expecting for this, I'm not entirely sure what you mean by supporting a `filter` or comparison system within parquet-rs?

**Comment by alamb** [comment]
Are you thinking about something like "apply some predicate on a parquet binary column and then only decode pages from other columns that might have matching positions" 🤔

**Comment by liukun4515** [comment]
This has been resolved in the datafusion I have found.
we convert the parquet statistic data to arrow array/ arrow data and apply the filter/predication to them.

Thanks @alamb @tustvold 
I will close this issue
