### ISSUE TITLE
Use BitIndexIterator in Array Iterators

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2132]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The various array iterators such as `PrimitiveIter`, `GenericStringIter`, etc... check the validity map individually for each element. This is likely sub-optimal

**Describe the solution you'd like**

`BitIndexIterator` provides a way to iterate over null masks, that will outperform checking the mask for individual elements. We should use this instead.

**Describe alternatives you've considered**

We could not do this

**Comment by jhorstmann** [comment]
Related to #1857. I haven't looked at BitIndexIterator in detail, so maybe this ticket is a better alternative.
