### ISSUE TITLE
Use ArrayAccessor in Comparison Kernels

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2135]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently the comparison kernels make extensive use of macros, with #2133 it is possible to rework these to instead make use of the `ArrayAccessor` trait. This should reduce code duplication and make the code easier to read and maintain.

**Describe the solution you'd like**

Rework the comparison kernels to use ArrayAccessor instead of `PrimitiveArray`, `GenericStringArray`, etc...

**Describe alternatives you've considered**

We could not do this

**Additional context**

**Comment by viirya** [comment]
I may try to work on this in this weekend.
