### ISSUE TITLE
object_store unit test might be flaky

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#2141]
**Describe the bug**

Saw a object_store unit test failure in CI:

```
---- throttle::tests::delete_test stdout ----
thread 'throttle::tests::delete_test' panicked at '206.888913ms must be < than 200ms', object_store/src/throttle.rs:313:9
```

**To Reproduce**

https://github.com/apache/arrow-rs/runs/7475787343?check_suite_focus=true
https://github.com/apache/arrow-rs/runs/7476237155?check_suite_focus=true

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#2141](https://github.com/apache/arrow-rs/issues/2141)
