### ISSUE TITLE
Need update version to 1.62

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/arrow-rs#2143]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
After merge #2131 
Get 
```
error[E0658]: use of unstable library feature 'total_cmp'
   --> arrow/src/compute/kernels/sort.rs:178:22
    |
178 |             |x, y| x.total_cmp(&y),
    |                      ^^^^^^^^^
    |
    = note: see issue #72599 <https://github.com/rust-lang/rust/issues/72599> for more information

```
https://doc.rust-lang.org/stable/std/primitive.f64.html#method.total_cmp

Do we need update rust version to 1.62 @alamb @Dandandan 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ted-Jiang** [comment]
If we update it to 1.62, we should also do in datafusion right?

**Comment by Dandandan** [comment]
Yes, `total_cmp` is a stable feature since 1.62, so requires at least this rust version to compile.
