### ISSUE TITLE
object_store: Support assuming roles directly when using AWS S3

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#2178]
Originally from https://github.com/influxdata/object_store_rs/issues/31 by @timvw

**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Users have an expectation that a correctly configured AWS credentials or profile file will cause systems to assume configured roles. Unfortunately Rusoto does not do this out of the box ([issue](https://github.com/rusoto/rusoto/issues/1758), [pr](https://github.com/rusoto/rusoto/pull/1842)).

One possible way to mitigate this is by migrating to [aws-sdk-rust](https://github.com/awslabs/aws-sdk-rust), but does not seem compatible with https://github.com/influxdata/object_store_rs/issues/18 .

**Describe the solution you'd like**
Proposed solution is in https://github.com/influxdata/object_store_rs/pull/37

**Describe alternatives you've considered**

**Additional context**

**Comment by timvw** [comment]
Existing implementation can be found in aws-sdk-rust [sso.rs](https://github.com/awslabs/aws-sdk-rust/blob/b8050cb19f4f11270150315a45c42b6f01d934fc/sdk/aws-config/src/sso.rs)


This is typically used by devs, while awaiting this feature, one can run the following commands to acquire temporal credentials:

```bash
ACCOUNT_ID="XXX"
ROLE_NAME="XXX"
ACCOUNT_ROLE_NAME="${ACCOUNT_ID}-${ROLE_NAME}"
ACCESS_TOKEN="$(cat ~/.aws/sso/cache/*.json | jq -r ".accessToken" | grep -v null)"
ROLE_CREDENTIALS="$(aws sso get-role-credentials --account-id="${ACCOUNT_ID}" --role-name="${ACCOUNT_ROLE_NAME}" --access-token="${ACCESS_TOKEN}")"

export AWS_ACCESS_KEY_ID="$(echo "${ROLE_CREDENTIALS}" | jq -r ".roleCredentials.accessKeyId")"
export AWS_SECRET_ACCESS_KEY="$(echo "${ROLE_CREDENTIALS}" | jq -r ".roleCredentials.secretAccessKey")"
export AWS_SESSION_TOKEN="$(echo "${ROLE_CREDENTIALS}" | jq -r ".roleCredentials.sessionToken")"
```

**Comment by tustvold** [comment]
I don't think it is a practical goal to support the full suite of AWS auth options as provided by `AWS_CONFIG`, we'd be opening ourselves up to supporting SSO, MFA, credential caching, etc... I think we should aim to support the authentication options used by workloads, which I think we have covered now, and delegate supporting the more esoteric auth options to tools designed for the purpose.

I would personally recommend [aws-vault](https://github.com/99designs/aws-vault).

**Comment by alamb** [comment]
Maybe there would be some way (feature flag perhaps) to use the official SDK (with its massive dependency chain) for users who want to be able to use some of the more sophisticated auth options

**Comment by tustvold** [comment]
Part of the motivation for moving away from the SDKs was we had serious difficulties providing consistent behaviour across stores, with missing functionality and inconsistent error handling to name a few of the problems. I think I would much rather keep the implementation here as lightweight as possible, primarily to reduce the maintenance burden on our limited set of maintainers, with the benefits this provides to users just an added bonus.

I think my preferred path forward would be for SDK-based implementations to be maintained out of tree, in the same vein as HDFS, if there are people who are willing to take on that effort.

**Comment by alamb** [comment]
> I think my preferred path forward would be for SDK-based implementations to be maintained out of tree, in the same vein as HDFS

This is a neat idea 👍

**Comment by timvw** [comment]
I am not willing to do a full implementation of an object store anymore but I have documented on how to acquire credentials from the aws-rust-sdk and build an AmazonS3 object store (Because using aws-vault felt tedious).

-> https://github.com/timvw/datafusion-examples/blob/main/s3-sdk-credentials/src/main.rs

**Comment by tustvold** [comment]
I bashed out a quick solution to this - https://github.com/apache/arrow-rs/pull/2891

It's pretty ugly, but it is slightly less ugly than working around this in downstreams

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#2178](https://github.com/apache/arrow-rs/issues/2178)
