### ISSUE TITLE
Update instructions on How to join the slack #arrow-rust channel -- or maybe try to switch to discord??

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#2192]
### Discussed in https://github.com/apache/arrow-rs/discussions/2039

<div type='discussions-op-text'>

<sup>Originally posted by **HaoYang670** July 10, 2022</sup>
Hi all. 
I want to join the slack #arrow-rust channel, but it needs someone to invite me. 
Could you help me?</div>

Basically the instructions on https://github.com/apache/arrow-rs#arrow-rust-community don't really give enough information on how to join the ASF slack channel -- specifically someone already a memory needs to invite you to slack ... 🤔 

I would update the instructions but I am not quite sure what it should say -- should it be file a 'question' issue? Or add a ping on the discussion thread? Or something else 🤔

**Comment by HaoYang670** [comment]
Oh, I've found the general instruction of how to join the Apache Slack channel here: https://infra.apache.org/slack.html
But for arrow-rs, there is more specific instruction (such as who to contact or where to send the request).

Personally, I prefer the `@dev mailing list` as a good area for sending request, which follows the Apache's style. 
We can update the README to add something like that: 
**If you want to join the Slack channel, please send a request to dev@arrow.apache.org with title `[RUST]Request joining the Slack arrow-rs channel`**

Also, the `GitHub Discussion` maybe also a good choice for sending request. But I'm not sure if this would break the Apache rule.

**Comment by alamb** [comment]
For what it is worth, @houqp  made a discord channel a while ago: https://discord.com/channels/885562378132000778/885562378132000781

but mostly it serves as a place for people to ask for an invite to the ASF slack
🤷

**Comment by HaoYang670** [comment]
Not sure what happened, but I failed to join the discord channel.

**Comment by alamb** [comment]
Does this link work to join discord? https://discord.gg/YAb2TdazKQ I don't really know discord well (I think @houqp  set it up originally)

**Comment by HaoYang670** [comment]
This works!
