### ISSUE TITLE
ArrayReader::skip_records API

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2197]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The skip records API added to the ArrayReader trait as part of #1998 does not provide a way to combine multiple selections into the same batch. This is unfortunate as columnar query engines will often want consistently large `RecordBatch` so that any dispatch overheads can be amortised over many rows. Whilst it could concatenate batches together, e.g. DataFusion's CoalesceBatchesExec, it would be more efficient to do this directly on read and eliminate an additional copy.

Ultimately doing this is supported by the underlying machinery, i.e. RecordReader, it just isn't exposed by ArrayReader

**Describe the solution you'd like**

Much like `RecordReader` we need to separate `read_records` from consuming the resulting data, i.e. replace `ArrayReader::next_batch` with `ArrayReader::read_records` and `ArrayReader::consume_batch`.

**Describe alternatives you've considered**

We could not do this, however, if we are going to make this change we should probably do it before we make the record skipping API public (#1792)

**Comment by Ted-Jiang** [comment]
Yes, I agree this need improvement before make api public.

> Much like RecordReader we need to separate read_records from consuming the resulting data, i.e. replace ArrayReader::next_batch with ArrayReader::read_records and ArrayReader::consume_batch.

I think you mean: we can call `read_records` multiple times until there are enough values in buf then we can call  `consume_batch`. To make sure avoid small data patch (now if selection_len less than batch_size will return a batch with selection_len rows ).

How about make this combine logic in `impl Iterator for ParquetRecordBatchReader` ，if we call  `read_records` multiple times it should depend on the `selections`,  why not  add a loop check in Iterator to feed enough rows in result batch🤔

**Comment by tustvold** [comment]
> why not add a loop check in Iterator to feed enough rows in result batch

Agreed, ParquetRecordBatchReader will need to have its logic modified to drive these new methods

**Comment by Ted-Jiang** [comment]
@tustvold Are you working one this ? Maybe i can implement this tomorrow 😊?
