### ISSUE TITLE
Integrate Record Skipping into Column Reader Fuzz Tests

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2198]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

`parquet::arrow::arrow_reader` contains a fairly extensive set of tests under `run_single_column_reader_tests` that are used to fuzz test the arrow readers. It would significantly boost the coverage of the record skipping logic if we could integrate the row skipping logic into this harness

**Describe the solution you'd like**

Add an optional row selection to `TestOptions` and add examples of using this to the `all_options` list in `run_single_column_reader_tests`.

**Describe alternatives you've considered**

We could not do this

**Additional context**

- #2197 
- #1792

FYI @Ted-Jiang

**Comment by Ted-Jiang** [comment]
Will cover it up 😄, hope no bug any more!

**Comment by tustvold** [comment]
Where did we get with this, I think this is the major thing to be confident enough to make the APIs public?

**Comment by Ted-Jiang** [comment]
I will try to finish this until this weekend.

**Comment by tustvold** [comment]
Awesome, absolutely no rush on this, was purely curious if you wanted me to pick this up :smile:

**Comment by Ted-Jiang** [comment]
haha,  i will try to figure this out !  I feel I can learn a lot from it😄
