### ISSUE TITLE
[Rust]: Tracking issue for AVX-512

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#220]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-10612

This issue will track AVX-512 feature development in its entirety.

**Comment by jorgecarleitao** [comment]
Github does not support sub-issues / tracking, so will close this and address this on the children.

**Comment by Dandandan** [comment]
@jorgecarleitao might it be useful to enable the milestone functionality to allow tracking bigger changes?
