### ISSUE TITLE
Add parquet reader / writer for decimal types

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#222]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-10926

Decimal values, stored physically as e.g. Fixed Size Binary should be represented by DecimalArray when the logical type indicates decimal.

**Comment by sweb** [comment]
I think this is done for Fixed Size Binary - there may be an implementation missing for decimal stored as other physical types.

**Comment by nevi-me** [comment]
It's i32, i64 and binary that I think we're missing

**Comment by tustvold** [comment]
I believe this is now complete
