### ISSUE TITLE
Umbrella issue for parquet 2.6.0 support

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#223]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11364

This is the umbrella issue where we can collect everything related to parquet 2.6.0 support (parquet-format-rs: 2.6.1).

It looks like there's some plumbing needed on the typesystem + parsing logic to fully support writing and reading v2 of the file format.

Existing compatibility issues can also be linked to this, or added as sub-tasks.

**Comment by tustvold** [comment]
I think all that remains is support for [DeltaByteStreamSplit](https://github.com/apache/parquet-format/blob/master/Encodings.md#byte-stream-split-byte_stream_split--9)

**Comment by tustvold** [comment]
Closed by https://github.com/apache/arrow-rs/pull/5293
