### ISSUE TITLE
Fix maximum and minimum for decimal values for precision greater than 38

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#2246]
**Describe the bug**

I made a mistake when filling out `MAX_DECIMAL_FOR_LARGER_PRECISION` and `MIN_DECIMAL_FOR_EACH_PRECISION`. It is less one digit for each value.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
FWIW this was found by the arrow integration test https://github.com/apache/arrow/pull/13685#issuecomment-1200248799 🎉
