### ISSUE TITLE
Add support for writing sliced arrays

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#225]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-8424

The initial Parquet writer does not consider array offsets. This is to ensure that we add tests for offsets

**Comment by tustvold** [comment]
Closing this as I don't think it is tracking anything anymore, @nevi-me added support for sliced arrays in https://github.com/apache/arrow-rs/pull/381, and https://github.com/apache/arrow-rs/pull/1214 added further test coverage (and fixed two bugs).
