### ISSUE TITLE
Switch object_store to log crate from tokio-tracing

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2255]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently the object_store crate makes use of tokio-tracing, this is likely significant overkill for some basic logging support.

**Describe the solution you'd like**

The [log](https://docs.rs/log/latest/log/) crate is lightweight, well-supported within the Rust ecosystem, and allows filtering out callsites at both runtime and compile time. It is also used downstream by [DataFusion](https://github.com/apache/arrow-datafusion/blob/master/datafusion/Cargo.toml#L70).

Users of tokio-tracing can make use of [tracing_log](https://docs.rs/tracing-log/latest/tracing_log/) to connect the systems together. 

**Describe alternatives you've considered**

We could not do this

**Additional context**

**Comment by tustvold** [comment]
Actually `h2` already depends on `tokio-tracing` and so our hand is somewhat forced here

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#2255](https://github.com/apache/arrow-rs/issues/2255)
