### ISSUE TITLE
Error order for comparing the decimal128 or decimal256

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-rs#2256]
**Describe the bug**
Decimal128 as a example, we use the [u8;16] to store the value of the decimal.

In order to compare the decimal128, we should use the signed compare order.

But the current implementation just compare the [u8;16] to get the order.

For example:
`Decimal128(-1, 10,0)`.cmp(`Decimal128(129,10,0)` will get the result of Greater.

**To Reproduce**

```
    #[test]
    fn compare_i128() {
        let v: i128 = -1;
        let b1: [u8; 16] = v.to_le_bytes();
        let b2: [u8; 16] = 129_i128.to_le_bytes();
        println!("{:?}", b1);
        println!("{:?}", b2);
        if b1.eq(&b2) {
            println!("=")
        }
        println!("{:?}", b1.cmp(&b2));
    }
```

**Expected behavior**

**Additional context**

**Comment by liukun4515** [comment]
@viirya 
I will fix it.

**Comment by viirya** [comment]
Good catch!
