### ISSUE TITLE
Windows / Mac and Coverage jobs are no longer running: arduino/setup-protoc@v1 is not allowed to be used in apache/arrow-rs

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2279]
**Describe the bug**

https://github.com/apache/arrow-rs/actions/runs/2781430582
```


Error: .github#L1arduino/setup-protoc@v1 is not allowed to be used in apache/arrow-rs. Actions in this workflow must be: within a repository owned by apache, created by GitHub, verified in the GitHub Marketplace, or matching the following: */*@[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]+, AdoptOpenJDK/install-jdk@*, JamesIves/github-pages-deploy-action@5dc1d5a192aeb5ab5b7d5a77b7d36aea4a7f5c92, TobKed/label-when-approved-action@*, actions-cool/issues-helper@*, actions-rs/*, al-cheb/configure-pagefile-action@*, amannn/action-semantic-pull-request@*, apache/*, burrunan/gradle-cache-action@*, bytedeco/javacpp-presets/.github/actions/*, chromaui/action@*, codecov/codecov-action@*, conda-incubator/setup-miniconda@*, container-tools/kind-action@*, container-tools/microshift-action@*, dawidd6/action-download-artifact@*, delaguardo/setup-graalvm@*, docker://jekyll/jekyll:*, docker://pandoc/core:2.9, eps1lon/actions-label-merge-conflict@*, gaurav-nelson/github-action-markdown-link-check@*, golang...
--
[Error: .github#L1](https://github.com/apache/arrow-rs/commit/ed9fc565f6b3bf0653ff342b523dbd1e2192d847#annotation_4184443006)
arduino/setup-protoc@v1 is not allowed to be used in apache/arrow-rs. Actions in this workflow must be: within a repository owned by apache, created by GitHub, verified in the GitHub Marketplace, or matching the following: */*@[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]+, AdoptOpenJDK/install-jdk@*, JamesIves/github-pages-deploy-action@5dc1d5a192aeb5ab5b7d5a77b7d36aea4a7f5c92, TobKed/label-when-approved-action@*, actions-cool/issues-helper@*, actions-rs/*, al-cheb/configure-pagefile-action@*, amannn/action-semantic-pull-request@*, apache/*, burrunan/gradle-cache-action@*, bytedeco/javacpp-presets/.github/actions/*, chromaui/action@*, codecov/codecov-action@*, conda-incubator/setup-miniconda@*, container-tools/kind-action@*, container-tools/microshift-action@*, dawidd6/action-download-artifact@*, delaguardo/setup-graalvm@*, docker://jekyll/jekyll:*, docker://pandoc/core:2.9, eps1lon/actions-label-merge-conflict@*, gaurav-nelson/github-action-markdown-link-check@*, golang...
```

This results in getting emails like this:

![Screen Shot 2022-08-02 at 9 23 19 AM](https://user-images.githubusercontent.com/490673/182385761-63699f6a-e264-4693-a8a2-563d4133cb34.png)

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
I believe this came in via https://github.com/apache/arrow-rs/pull/2268 from @carols10cents

**Comment by alamb** [comment]
I previously had to deal with the 'prost stopped bundling protoc' with linux -- and I added our own action https://github.com/apache/arrow-rs/tree/master/.github/actions/setup-builder to do so.

**Comment by alamb** [comment]
In this case, since it is for the `mac` and `windows` job, I recommend either:
1. Copy the contents of the `setup-protoc` action from `arduino` to this repository (which is ok under policy as then we control its contents)
2. Stop testing `arrow-flight` on on mac and windows

For option 2 I was thinking we might be able to claim that the arrow-flight usecase is not sufficiently important to warrant figuring out the CI actions to run them

However, as I write this I realize that at least ensuring `arrow-flight` builds is important on mac and linux, and checking the build does require getting protoc running.

@tustvold  I am happy to try and get this working, if you don't have the time

**Comment by alamb** [comment]
I'll take a crack at this one

**Comment by tustvold** [comment]
I think this is also stopping format jobs from running

**Comment by alamb** [comment]
That is also likely . I am plodding along getting the windows builder running again. If I can't get it working in the next hour or two I'll get a PR up that at least fixes mac / formating

**Comment by alamb** [comment]
I am very close 🤞

**Comment by alamb** [comment]
PR to fix everything other than windows

**Comment by alamb** [comment]
I fixed fmt and mac jobs: https://github.com/apache/arrow-rs/pull/2287

I am still working on coverage and windows (I hate protoc)

**Comment by alamb** [comment]
In finally have a fix: https://github.com/apache/arrow-rs/pull/2280 😅  -- lots of putzing with windows

**Comment by carols10cents** [comment]
Whoops! Sorry about that-- thank you for handling it @alamb 🙏🏻
