### ISSUE TITLE
Support get_multi_ranges in ObjectStore

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/arrow-rs#2293]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
now we have
https://github.com/apache/arrow-rs/blob/6c3f9a299ad10a66160563f7580a1062c2e8af7e/object_store/src/lib.rs#L115-L118

I found in  #2110 already support multi ranges
https://github.com/apache/arrow-rs/blob/aeb277642d1267673055aa0f705646db96dad340/parquet/src/arrow/async_reader.rs#L115-L124

we should support same location  path with multi ranges read in object_store,

like 
```
async fn get_ranges(&self, location: &Path, range: &[<usize>]) -> Result<Bytes>; 
```

This will reduce some overhead like in HDFS:
We need to get file metadata for each `location` from metadata server(nameNode),  if we can get multi ranges in one location will reduce some rpc call in system.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ted-Jiang** [comment]
@alamb what do you think 😊

**Comment by tustvold** [comment]
Perhaps

```
async fn get_ranges(&self, location: &Path, ranges: &[usize]) -> Result<Vec<Bytes>>; 
```

With a default serial implementation?

**Comment by Ted-Jiang** [comment]
> Perhaps
> 
> ```
> async fn get_ranges(&self, location: &Path, ranges: &[usize]) -> Result<Vec<Bytes>>; 
> ```
> 
> With a default serial implementation?

Sure!

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#2293](https://github.com/apache/arrow-rs/issues/2293)
