### ISSUE TITLE
Add support for pretty-printing Decimal numbers

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#230]
In the context of https://github.com/apache/arrow-datafusion/issues/107 from @joshuataylor 

**Describe the solution you'd like**
It should be possible to pretty-print columns of `DataType::Decimal` type. Pretty printing is used for datafusion and other projects to make human readable versions of Arrow arrays.

To do so, we would add support here:  https://github.com/apache/arrow-rs/blob/cf0c7d2cbecc2ca6ceeb7459417cef3501f64ad1/arrow/src/util/display.rs#L269-L271

Right now, you get an error such as 
```
ArrowError(InvalidArgumentError("Pretty printing not implemented for Decimal(9, 0) type"))
```

**Comment by mgill25** [comment]
Hi @alamb I'd like to take this issue up if that's ok.

Looks like the change should be simple enough - just add the `Decimal` pattern to the  match expression. I have a silly question however: Is this being tested somewhere?

Seems like there is no test in `display.rs`, but there _are_ tests in `pretty.rs`. Which I tried to run these tests, it seems cargo is skipping them, and yet it doesn't skip the tests in other neighboring modules.

<img width="1257" alt="Screenshot 2021-05-02 at 21 14 50" src="https://user-images.githubusercontent.com/1311924/116824681-c8a51d00-ab8b-11eb-8f33-03a6cfafe8c9.png">

Am I overthinking this a bit? Let me know how to figure this one out. :) Thanks!

**Comment by nevi-me** [comment]
@mgill25 the `pretty` tests are likely skipped because `prettyprint`is an optional feature

**Comment by alamb** [comment]
Thanks @mgill25 ! As @nevi-me  says the pretty print feature is behind a feature flag (as it baloons the dependency stack with something that does not support for WASM builds, as I recall)

To answer your question, the pretty print feature is tested here in CI:
https://github.com/apache/arrow-rs/blob/master/.github/workflows/rust.yml#L114

To test it locally, you can run `cargo` like:
```
          cargo test --features=prettyprint
```
