### ISSUE TITLE
Make FFI support Optional via Feature Flag

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2302]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Many use-cases will not need FFI support, and as such being able to disable FFI support will allow eliminating a large amount of non-trivial, unsafe code from their build

**Describe the solution you'd like**

I would like a feature flag to disable FFI support

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
added documentation about this flag in https://github.com/apache/arrow-rs/pull/2324
