### ISSUE TITLE
Update `FlightSqlService` trait to pass session info along

### ISSUE THREAD

**Issue by avantgardnerio** [apache/arrow-rs#2308]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Ballista requires keeping session state for things like what tables are registered. In order to look up this state, we need a key. According to the [arrow docs](https://arrow.apache.org/docs/format/Flight.html#authentication), this key is in the request metadata. This metadata is not passed to the `impl`s in the existing trait, so Ballista is not able to run any query more advanced than `select 1;`. 

**Describe the solution you'd like**

Agree on a format to pass session data to implements. 

**Describe alternatives you've considered**

1. Passing raw tonic metadata
2. handling all authentication in the base impl
3. passing the 1 header info as a generic string
4. decoding it and forcing it to be a UUID
5. ...

**Comment by avantgardnerio** [comment]
CC @andygrove and @alamb

**Comment by alamb** [comment]
> so Ballista is not able to run any query more advanced than select 1;

LOL
