### ISSUE TITLE
Specialize FixedLenByteArrayReader for Parquet

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2318]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We have optimised implementations for reading most types directly to their arrow representations, however, we fallback to reading `FixedLenByteArray` and then using `ComplexObjectArrayReader` to cast it to the desired type.

This is problematic for a couple of reasons:

* We want to remove `ComplexObjectArrayReader` - #1661 
* `FixedLenByteArray` has a `Box<[u8]>` which is very expensive

**Describe the solution you'd like**

I would like an optimized `FixedLenByteArrayReader<const N: usize>` that can be used to efficiently read values where the type is known up front, e.g. decimals and intervals. We can fallback to using `FixedLenByteArray` for the general case.

**Describe alternatives you've considered**

We could not do this

**Additional context**

**Comment by liukun4515** [comment]
If your pr ready, feel free to at me and request me to review
@tustvold
