### ISSUE TITLE
AmazonS3 Support IMDSv2

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2350]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

IMDSv1 has [known vulnerabilities](http://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/) consequently is commonly disabled, currently rusoto does not support this - https://github.com/rusoto/rusoto/issues/1818

**Describe the solution you'd like**

Migrating away from rusoto as part of #2176 would achieve this

**Describe alternatives you've considered**

We could also move to the new AWS SDKs, although they are marked experimental, and have a huge dependency footprint

**Additional context**

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#2350](https://github.com/apache/arrow-rs/issues/2350)
