### ISSUE TITLE
Azure/S3 Storage Fails to Copy Blob with URL-encoded Path

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2353]
**Describe the bug**

https://github.com/apache/arrow-rs/runs/7713310841?check_suite_focus=true#step:8:330

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by tustvold** [comment]
It would appear rusoto has the same issue

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#2353](https://github.com/apache/arrow-rs/issues/2353)
