### ISSUE TITLE
AmazonS3Builder::from_env to populate credentials from environment

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2361]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

There are various common environment variables for configuring AWS credentials, e.g. `AWS_SECRET_ACCESS_KEY`, `AWS_REGION`, etc... We should add a `from_env` method that respects these

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by amrltqt** [comment]
I can help on this one. 

Is it better to bring a full support of the builder properties through environment or just the minimum to leverage AWS_* regular environment setup?

**Solution 1** we bring everything from environment but we need to introduce new  variables to match each builder properties.
 
```rust
let object_store = AmazonS3Builder::from_env().build();

// or even ?
let object_store = AmazonS3::from_env();
```

**Solution 2** we match existing AWS variable and provide support for AWS_* variables described [there](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html#envvars-set) 

```rust
let object_store = AmazonS3Builder::from_env()
    .with_bucket_name("the-bucket-name")
    .with_allow_http(true);
```

**Solution 3** we support only the 4 variables used in integration test for now 
(those ones: https://github.com/apache/arrow-rs/blob/master/object_store/src/aws/mod.rs#

Which one is the most suitable for you?

**Comment by tustvold** [comment]
Thank you for volunteering, I think option 2 makes the most sense. The idea is to get people up and running quickly, much like the standard AWS SDKs, not necessarily to expose the full set of customisation as environment variables.

**Comment by alamb** [comment]
Migrated from arrow-rs issue [#2361](https://github.com/apache/arrow-rs/issues/2361)
