### ISSUE TITLE
Re-export parquet-format

### ISSUE THREAD

**Issue by nevi-me** [apache/arrow-rs#237]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We now return `parquet_format::FileMetadata` when closing a writer. For users to use this struct, they need to include `parquet-format` as a Cargo dependency.

This will cause problems if users import incompatible versions of the format crate.

**Describe the solution you'd like**

Re-export `parquet_format` as `parquet::format`, or export parts of the crate as required.

**Describe alternatives you've considered**

Probably the option to export the whole crate vs parts of it,

**Additional context**

None

**Comment by tustvold** [comment]
Closed by #2626
