### ISSUE TITLE
[object store] Add TokenProvider authorization to azure

### ISSUE THREAD

**Issue by roeap** [apache/arrow-rs#2373]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

AccessKey authorization is often not permitted in corporate environments. As such it would be great to offer more authorization options - like service principal, managed identities etc - specifically to the azure store.

**Describe the solution you'd like**

Ability to provide other means of authorization other than master key.

**Describe alternatives you've considered**

not offer alternative auth.

**Additional context**

**Comment by alamb** [comment]
Migrated from arrow-rs issue [#2373](https://github.com/apache/arrow-rs/issues/2373)
