### ISSUE TITLE
Rewrite Decimal Array using `const_generic`

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-rs#2384]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Why I prefer using `const_generic` on Decimal?
- Decimal128 and Decimal256 are different datatype. However all of their fields have same data type except the length of the value buffer `[u8; 16] or [u8; 32]`.  This is the situation which `const_generic` is very suitable. 
- In the Rust standard library, there is a famous type using `const_generic`: the Array type: https://doc.rust-lang.org/std/primitive.array.html `Decimal` is very similar to `Array`
- Remove some repeated code.
- More constant evaluation
-  Easy to extend: We might add more Decimal type in the future. For example in arrow2, there is a PR to add Decimal 32 and 64: https://github.com/jorgecarleitao/arrow2/pull/896

Will the rewriting leads to many API changes?
Yes, But for users, the answer is no. Because this is just an internal refactor.

Checked List
- [x] BasicDecimal (#2383 )
- [x] BasicDecimalArray (#2383 )
- [x] #2390 

**Describe alternatives you've considered**
We could not do this.

**Additional context**
Related to #2362 and #2274.

**Comment by liukun4515** [comment]
@HaoYang670 
The refactor is reasonable for me.

**Comment by liukun4515** [comment]
Do you want to do all the checklist in the one pull request?

**Comment by HaoYang670** [comment]
> Do you want to do all the checklist in the one pull request?
No.
In the first PR, I will update `BasicDecimal` and `BasicDecimalArray`. I tried to make change step by step, but I have to update these 2 in one PR 😅.
