### ISSUE TITLE
DecimalArray Benchmarks

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2388]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We lack any benchmark coverage of `DecimalArray` and `DecimalBuilder`

**Describe the solution you'd like**

Some basic benchmarks of constructing, iterating and filtering decimal arrays

**Describe alternatives you've considered**

**Additional context**

Perhaps @liukun4515 you might want to pick this up in advance of making any changes?

**Comment by alamb** [comment]
There are some benchmarks in https://github.com/apache/arrow-rs/pull/2360 -- see https://github.com/apache/arrow-rs/pull/2360#issuecomment-1209180343 from @liukun4515

**Comment by liukun4515** [comment]
pick up this issue. thanks @tustvold @alamb

**Comment by liukun4515** [comment]
we have many case using the decimal data type, the benchmark and improvement for decimal are important for us.

**Comment by liukun4515** [comment]
I have added the benchmark for validation decimalarray for decimal128 and decimal256 in https://github.com/apache/arrow-rs/pull/2360.

In the pr https://github.com/apache/arrow-rs/pull/2360, I doesn't refactor the validation of decimal128 because I got wired benchmark result.

After the pr merge, I will submit a new pr or issue to discuss this.
@alamb @tustvold

**Comment by liukun4515** [comment]
- [ ] add test for decimal decoder from primitive reader: https://github.com/apache/arrow-rs/issues/2408
- [ ] add benchmark for reading primitive data to decimal

**Comment by liukun4515** [comment]
The performance of reading decimal data from bytes or fixed length bytes improves by https://github.com/apache/arrow-rs/pull/2528 https://github.com/apache/arrow-rs/pull/2522

**Comment by alamb** [comment]
🌮

**Comment by tustvold** [comment]
Closing as we have fairly good benchmark coverage now, and decimal array is now a primitive array yielding additional coverage
