### ISSUE TITLE
Support casting from utf8 to binary

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-rs#2402]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Casting from utf8 to binary is missing.

**Describe the solution you'd like**

Implement cast for utf8(large) to binary(large).

**Describe alternatives you've considered**

n/a
**Additional context**

n/a

**Comment by HaoYang670** [comment]
I guess this should be straight forward by changing the data type:
```rust
let binary_array_data = utf8_array_data.into_builder()
    .datatype(DataType::Binary)
    .build_unchecked()
```

This could be a good first issue for developers who want to get familiar with the arrow data type.

**Comment by psvri** [comment]
I want to pick this up, but I was just a little confused . If i am not mistaken we already have a function to convert into binary array https://docs.rs/arrow/20.0.0/arrow/array/fn.as_generic_binary_array.html . 

So based on my understanding, If we need to implement, then we need to implement trait from<GenericStringArray> for GenericBinaryArray.

**Comment by HaoYang670** [comment]
> then we need to implement trait from< GenericStringArray > for GenericBinaryArray.

I guess this is what @Dandandan want.

**Comment by Dandandan** [comment]
Thanks for the interest in this issue. I think the description wasn't fully clear.

Currently the `cast` kernel in Arrow doesn't support casting string arrays of  to binary, so my suggestion is to implement this. It should be pretty straightforward indeed to build an existing string array to a binary array.
