### ISSUE TITLE
Avoid unecessary copies in Arrow IPC reader

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#2437]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
The Arrow IPC format is designed to avoid memory copies when moving data from one implementation to another. However, as noted by @tustvold  on https://github.com/apache/arrow-rs/pull/2369#discussion_r944214515, the arrow-rs ipc reader implementation is actually copying data unnecessarily

**Describe the solution you'd like**
In the ipc code, create a Buffer initially and rewrite the ipc implementation in terms of `Buffer` rather than `&[u8]`  (as the final output needs to be in a `Buffer`

**Describe alternatives you've considered**
N/A

**Additional context**

Came up in the context of https://github.com/apache/arrow-rs/pull/2369

Possibly also related to https://github.com/apache/arrow-rs/issues/189

**Comment by HaoYang670** [comment]
I'd like to have a try to get familiar with the IPC code.
