### ISSUE TITLE
Incorrect null handling at boolean kernels

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#2469]
**Describe the bug**

null AND false should be false, instead of null. 
null OR true should be true, instead of null.

Currently `and` and `or` are incorrect on null handling.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by tustvold** [comment]
Because NULLs are wild and counter-intuitive I double-checked this with DuckDB

```
>>> duckdb.query("SELECT TRUE OR NULL").fetchall()
[(True,)]

>>> duckdb.query("SELECT FALSE AND NULL").fetchall()
[(False,)]
```

Nice find :+1:

**Comment by viirya** [comment]
Thanks @tustvold. Yea, just encountered this issue on an internal project. I've verified with Spark SQL behavior.

**Comment by jhorstmann** [comment]
Note the standard sql behavior is available in the separate `and_kleene` / `or_kleene` kernels introduced in #9772 (https://issues.apache.org/jira/browse/ARROW-11973). From the jira ticket it sounds like this distinction was kept because the C++ impl does the same.

**Comment by viirya** [comment]
Ah, thanks @jhorstmann. I didn't be aware there are separate kernels for the sql behavior. That makes sense.
