### ISSUE TITLE
feat: display NULL instead of empty String when value is Null

### ISSUE THREAD

**Issue by JasonLi-cn** [apache/arrow-rs#2474]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Now, array_value_to_string() display empty String when value is Null. 
https://github.com/apache/arrow-rs/blob/ecc62104bb72fd96cb54534732f6d29362a8c573/arrow/src/util/display.rs#L297-L300

I think should display NULL like MySQL and ClickHouse.

**Describe the solution you'd like**

Clickhouse: 
```shell
localhost.localdomain :) select NULL from v2 limit 10;

SELECT NULL
FROM v2
LIMIT 10

Query id: xxx-

┌─NULL─┐
│ ᴺᵁᴸᴸ │
│ ᴺᵁᴸᴸ │
│ ᴺᵁᴸᴸ │
│ ᴺᵁᴸᴸ │
│ ᴺᵁᴸᴸ │
│ ᴺᵁᴸᴸ │
│ ᴺᵁᴸᴸ │
│ ᴺᵁᴸᴸ │
│ ᴺᵁᴸᴸ │
│ ᴺᵁᴸᴸ │
└──────┘
```

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
For what it is worth, `postgres` prints nulls as `""` (I realize arrow isn't necessarily following postgres)

```
alamb=# select null, 1;
 ?column? | ?column? 
----------+----------
          |        1
(1 row)
```
