### ISSUE TITLE
add into_inner method to ArrowWriter

### ISSUE THREAD

**Issue by jiacai2050** [apache/arrow-rs#2491]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

For now,  there is no way to retrieve `Writer` passed into `ArrowWriter` back, this means that we have to use Arc(or something similar) to wrap `Writer` in order to get ownership.

**Describe the solution you'd like**

Add into_inner method to [ArrowWriter](https://docs.rs/parquet/20.0.0/parquet/arrow/arrow_writer/struct.ArrowWriter.html), just like parquet2
- https://docs.rs/parquet2/0.15.1/parquet2/write/struct.FileWriter.html#method.into_inner

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
Have you tried passing &mut W to the writer instead?

**Comment by tustvold** [comment]
> I need ownership(or static lifetime) since if it's behind a trait object.

FWIW trait objects need not have static lifetimes, but I concede your point that there are situations where a `static` lifetime is necessary to avoid self-referential structures.
