### ISSUE TITLE
Use u8 for Decimal Precision and Scale

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2496]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The maximum precision and scale for decimal types is 76, and yet we consume an entire `usize` to store this information. This is most pronounced on `BasicDecimal` where the precision and scale take up more memory than the actual value data :scream: 

**Describe the solution you'd like**

I would like to propose using `u8` for these instead of `usize`

**Describe alternatives you've considered**

**Additional context**

Thoughts @liukun4515

**Comment by liukun4515** [comment]
It's reasonable for me.
I think the data type of `Decimal128(usize, usize),` should be changed too

**Comment by psvri** [comment]
Hello, 

I will pick this up if no one has started working on it.

**Comment by liukun4515** [comment]
> It's reasonable for me. I think the data type of `Decimal128(usize, usize),` should be changed too

Do you have some comments about the data type of the decimal128?
FYI @psvri  @tustvold

**Comment by psvri** [comment]
I have changed datatype to Decimal128(u8, u8) and Decimal256(u8, u8) .
