### ISSUE TITLE
Inline Generated Thift Code Into Parquet Crate

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2502]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently parquet-format, which contains the generated code from the parquet thrift definitions, is published as a separate [crate](https://crates.io/crates/parquet-format) from a separate [repo](https://github.com/sunchao/parquet-format-rs)

There is [discussion](https://github.com/sunchao/parquet-format-rs/pull/18#issuecomment-1219811367) about potentially donating parquet-format and I wanted to create an issue to discuss this

**Describe the solution you'd like**

It's necessarily an incomplete picture, but looking at the [reverse dependencies](https://crates.io/crates/parquet-format/reverse_dependencies) of parquet-format they all already have a dependency on `parquet`. As such I would like to propose inlining the generated code in a `format` module within `parquet`. This would avoid maintenance burden associated with an additional crate

**Describe alternatives you've considered**

We could not do this or we could donate the code, but still vend it as a separate crate. This would not address the maintenance burden of additional dependencies, but perhaps updates are infrequent enough that this doesn't matter

**Additional context**

If we are happy to proceed with this, I would be willing to help with the mechanics of moving the code across

FYI @sunchao @nevi-me

**Comment by alamb** [comment]
I also agree that incorporating the code generated from thrift into the parquet crate and removing the dependency on parquet-format would be a good idea because:
1. I think it would easier to use for users (can't have a version mismatch with parquet and another crate)
2. The generated thrift code seems like an implementation detail.

**Comment by sunchao** [comment]
+1. Let me know if you need any help. 

>  I'd be in favour of deprecating and eventually archiving parquet-format-rs, then generating the code here.

I'd prefer to do the deprecating & archiving later, since we have internal projects that are still using `parquet-format-rs`.

**Comment by alamb** [comment]
Automatically added labels {'api-change'} from #2626
