### ISSUE TITLE
UnionBuilder Create Children With Capacity

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2523]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

`UnionBuilder` is created with a capacity, but this is only used to pre-allocate its type_ids buffer. The child buffers are created with a capacity of 1.

**Describe the solution you'd like**

We should save this capacity and  pass it to `FieldData::new`. In the case of a sparse union, we should pass the maximum of the currently length and the capacity.

**Describe alternatives you've considered**

**Additional context**

**Comment by kastolars** [comment]
Hi, has anyone started on this issue?

**Comment by tustvold** [comment]
No, would you like me to assign it to you?

**Comment by kastolars** [comment]
I can give it a shot yeah, I'll try to get a PR out today.
