### ISSUE TITLE
Add the `length` field for `Buffer`

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-rs#2524]
**Which part is this question about**
So far, the `Buffer` doesn't have its own length, which means you can't slice on data with the length you want.:
```rust
pub struct Buffer {
    /// the internal byte buffer.
    data: Arc<Bytes>,

    /// The offset into the buffer.
    offset: usize,
}
```
This is an old question, and related to some bugs (such as #807), and some performance issues (such as #2510)
I reopen this question because we don't reach a consensus.

Personally, I hope `Buffer` could behave like `&[u8]` or `Arc<Vector>`, but we need more discussion.

Additionally, I hope we could reach a consensus, for example:
- We should add the `length` field, because ... 
- we don't need to add this field, because ...

**Describe your question**

**Additional context**

**Comment by tustvold** [comment]
I would suggest lifting the length out of `Bytes` onto `Buffer`, this way we avoid redundant information

**Comment by HaoYang670** [comment]
Thank you, @tustvold. I will try your suggestion and file a draft PR. (maybe need more help from you)
