### ISSUE TITLE
Compare dictionary with non-dictionary arrays in comparison kernels

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#2534]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Comparison kernels currently only support comparison among non-dictionary arrays and dictionary arrays separately. But in many use cases, we cannot prevent dictionary array to be compared with non-dictionary array. We should extend comparison kernels functionalities.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by viirya** [comment]
Subtasks:

- [ ] #2535

**Comment by tustvold** [comment]
I think this is now complete?

**Comment by viirya** [comment]
Yea, I think so.
