### ISSUE TITLE
object_store: use different AWS environment variable name in integration

### ISSUE THREAD

**Issue by amrltqt** [apache/arrow-rs#2550]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Follow-up on https://github.com/apache/arrow-rs/pull/2536#discussion_r950711802 

Using regular AWS environment variables in integration to build AmazonS3Builder can introduce confusion or clash with tests.

**Describe the solution you'd like**

Rename variable in integration (there: https://github.com/apache/arrow-rs/blob/master/.github/workflows/object_store.yml#L75) and propagate them in tests.

**Comment by alamb** [comment]
Migrated from arrow-rs issue [#2550](https://github.com/apache/arrow-rs/issues/2550)
