### ISSUE TITLE
Support Coalescing Out-of-Order Ranges

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2561]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The basic logic added for coalescing ranges in #2336 does not attempt to handle out of order ranges, this leaves potential savings on the floor.

**Describe the solution you'd like**

I would like get_ranges to support out of order ranges

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
Migrated from https://github.com/apache/arrow-rs/issues/2561
