### ISSUE TITLE
Coalesce Ranges Parallel Fetch

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2562]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

`coalesce_ranges` currently fetches the coalesced ranges serially, we could make use of `StreamExt::buffered` to fetch in parallel

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#2562](https://github.com/apache/arrow-rs/issues/2562)
