### ISSUE TITLE
update the `flight.proto` and fix schema to SchemaResult

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-rs#2571]
**Describe the bug**

The issue is described in https://github.com/apache/arrow-rs/issues/2445

How to fix this issue:
1. update the `flight.proto`
2. update the implementation of  `impl From<SchemaAsIpc<'_>> for SchemaResult {` using the ipc format instead of raw flatbuffer

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
Automatically added labels {'arrow'} from #2586

**Comment by alamb** [comment]
Automatically added labels {'api-change'} from #2586
