### ISSUE TITLE
Print Response Body On Error

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2572]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We currently use `error_for_status` to map HTTP status codes to errors, unfortunately this does not include the response body. This can complicate debugging issues, as often the response text can help identify what the issue is. 

This is especially useful for 4xx errors, where there may be multiple possible causes

**Describe the solution you'd like**

Include the response body on 4xx errors

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#2572](https://github.com/apache/arrow-rs/issues/2572)
