### ISSUE TITLE
Retry Logic Fails to Retry Server Errors

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2573]
**Describe the bug**

The logic in `send_retry` only retries errors returned by [send](https://docs.rs/reqwest/latest/reqwest/struct.RequestBuilder.html#method.send) which critically does not include errors due to reponse status.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#2573](https://github.com/apache/arrow-rs/issues/2573)
