### ISSUE TITLE
IMDSv1 Fallback

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2609]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Not all systems support IMDSv2, in particular kubernetes environments where the necessary multihop tweaks have not been made, or running old versions of kube2iam

**Describe the solution you'd like**

On receiving a 403 response we should fallback to using IMDSv1.

**Describe alternatives you've considered**

**Additional context**

Prior to #2574 we had fallback logic by accident, as we weren't validating the status code returned :scream:

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#2609](https://github.com/apache/arrow-rs/issues/2609)
