### ISSUE TITLE
`DataType::is_numeric` should match the `is_numeric` function in Datafusion.

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-rs#2611]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
In datafusion, we have:
```rust
/// Determine if a DataType is signed numeric or not
pub fn is_signed_numeric(dt: &DataType) -> bool {
    matches!(
        dt,
        DataType::Int8
            | DataType::Int16
            | DataType::Int32
            | DataType::Int64
            | DataType::Float16
            | DataType::Float32
            | DataType::Float64
            | DataType::Decimal128(_, _)
    )
}

/// Determine if a DataType is numeric or not
pub fn is_numeric(dt: &DataType) -> bool {
    is_signed_numeric(dt)
        || matches!(
            dt,
            DataType::UInt8 | DataType::UInt16 | DataType::UInt32 | DataType::UInt64
        )
}
```

We should update `DataType::is_numeric` to contain these constructors so that we could remove the redundant `is_numeric` in datafusion (https://github.com/apache/arrow-datafusion/issues/1613)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HaoYang670** [comment]
Hi @alamb, any background of why we don't support `Float16` in the cast kernel?

**Comment by liukun4515** [comment]
Because we are missing some kernel  function for some data type which may be not used by the upstream project or other user, the checker of data type maybe duplicated and redundant.

**Comment by HaoYang670** [comment]
Thank you @liukun4515. 
I guess we cannot support `Float16` as a numeric type so far because `lexical_core::FromLexical` doesn't implement for `half::f16`.

Then, the next question is that should we update the `is_numeric` function in datafusion to match the arrow-rs. (aka removing float16 and decimal128)? Or should we rename it if it provides different functionality from `DataType::is_numeric`?

**Comment by alamb** [comment]
I think f16 support was relatively recent -- added by @Jimexist  in https://github.com/apache/arrow-rs/pull/888 . I don't think there was any specific reason that f16 doesn't have as wide support as the other types.

I would be in favor of having arrow-rs and datafusion match. I think decimal128 is a critical usecase for datafusion - as at least @liukun4515  and his team are using it heavily.

I don't know of anyone using f16 at the moment (but maybe there are) so I don't think it is as important
