### ISSUE TITLE
Bulk delete support for object-store

### ISSUE THREAD

**Issue by wjones127** [apache/arrow-rs#2615]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

This is useful for deleting a whole partitioned table of files without having to make a request for each file. Though unfortunately it seems only S3 implements this (even GCS doesn't have it in their XML API).

S3: https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html

**Describe the solution you'd like**

It seems like it might be worth having this with the optimized version for S3, and otherwise have the generic version make individual requests concurrently.

**Describe alternatives you've considered**

**Additional context**

Our use case is the VACUUM operation in delta-rs, which has to delete many files in bulk.

**Comment by roeap** [comment]
I think azure can support this as well via [blob batch](https://docs.microsoft.com/en-us/rest/api/storageservices/blob-batch).

**Comment by roeap** [comment]
also just stumbled across [this](https://cloud.google.com/storage/docs/batch) for gcp :)

**Comment by tustvold** [comment]
This makes sense to me 👍
