### ISSUE TITLE
Expose option to use GCS object store in integration tests

### ISSUE THREAD

**Issue by roeap** [apache/arrow-rs#2627]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

When running integration tests is is useful to be able to work against emulated services. As such it would be great to publicly expose an option to configure the GCS backend in object store for use with fake-gcs.

**Describe the solution you'd like**

Expose an option on GoogleBuilder to configure use with fake-gcs.

**Describe alternatives you've considered**

Not doing it.

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'object-store'} from #2628

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#2627](https://github.com/apache/arrow-rs/issues/2627)
