### ISSUE TITLE
Implement StringBuilder::append_option

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#263]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I am frustrated when trying to build `StringArray`s using the `StringBuilder`. 

Specifically, yhere are some places I have to / find it more convenience to use a builder (rather than the `From` impl) to build `StringArray`s, such as https://github.com/influxdata/influxdb_iox/blob/main/server/src/db/system_tables.rs#L125 where we are building system tables in  IOX

With `PrimitiveArrayBuilder` based builders such as `UInt64Builder`, I can use the [`append_option`](https://docs.rs/arrow/4.0.0/arrow/array/struct.PrimitiveBuilder.html#method.append_option) function in the following way:

```
int_builder.append_option(size)?;
```
Which is 👍 

However, since there is  no corresponding `append_option` on  [`GenericStringBuilder`](https://docs.rs/arrow/4.0.0/arrow/array/struct.GenericStringBuilder.html)  I have have to do something this which takes more time and is 👎 
```
                if let Some(v) = column.stats.min_as_str() {
                    min_values.append_value(v)?;
                } else {
                    min_values.append(false)?;
                }
```

**Describe the solution you'd like**
Add a function `StringBuilder::append_option` that takes `Option<AsRef<str>>`

```
pub fn append_option(&mut self, v: Option<AsRef<str>) -> Result<()> {
...
}
```

**Describe alternatives you've considered**
Continued frustration :)

**Additional context**

**Comment by tzzed** [comment]
Can I take this one ?

**Comment by alamb** [comment]
@tzzed  that would be great!
