### ISSUE TITLE
Lexsort LargeString Panics

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2654]
**Describe the bug**

Calling `lexsort_to_indices` on a `LargeStringArray` results in a panic

```
[Large]StringArray expects Datatype::[Large]Utf8
```

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by 00Masato** [comment]
Hi,
Can I try this issue?

**Comment by tustvold** [comment]
Sure thing, let me know if you would like some further guidance 😄

**Comment by 00Masato** [comment]
@tustvold 
Sorry,
May I have few more details? - e.g. code sample.

**Comment by tustvold** [comment]
Hi @00Masato sorry for the delay. In light of #2687 and other issues related to this part of the codebase, I think the fix will probably be to just migrate away from DynComparator and so I'm not sure this is worth fixing. Apologies for the mixed messaging

**Comment by 00Masato** [comment]
OK!
Thank you for your response!
