### ISSUE TITLE
clippy error: unresolved import `crate::array::layout`

### ISSUE THREAD

**Issue by wangfenjin** [apache/arrow-rs#2659]
Version 22.0.0 will report clippy error: https://github.com/wangfenjin/duckdb-rs/runs/8198338828?check_suite_focus=true

Seems related to this commit: https://github.com/apache/arrow-rs/pull/1960

**Comment by viirya** [comment]
It is not due to #1960 which was merged since 18.0.0.

`layout` was only exported if the `ipc` feature is enabled since #2601. But it is also required by `ffi` feature.
