### ISSUE TITLE
add overflow-checking for negative arithmetic kernel

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-rs#2662]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

follow up of the https://github.com/apache/arrow-rs/issues/2642

cc @viirya 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
I believe this has now been implemented?

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #2893
