### ISSUE TITLE
`arrow` crate does not build with `features = ["ffi"]` and `default_features = false`.

### ISSUE THREAD

**Issue by pacman82** [apache/arrow-rs#2670]
**Describe the bug**

`arrow` crate does not build with `features = ["ffi"]` and `default_features = false`.

**To Reproduce**

inculde this in any `Cargo.toml`

```toml
[dependencies]
arrow = { version = "22.0.0", default-features = false, features = ["ffi"] }
```

yields error

```
error[E0432]: unresolved import `crate::array::layout`
   --> C:\Users\Markus\.cargo\registry\src\github.com-1ecc6299db9ec823\arrow-22.0.0\src\ffi.rs:125:20
    |
125 | use crate::array::{layout, ArrayData};
    |                    ^^^^^^ no `layout` in `array`
```

**Expected behavior**

I expected the build to work with only the `ffi` feature enabled. `ffi` should then imply all the other features it depends on.

**Additional context**

Build breaks due to missing `layout` in this use declaration: https://github.com/apache/arrow-rs/blob/463240adc92197c3f2260007cc6e5e574cbd1942/arrow/src/ffi.rs#L125

This broke the downstream build of `arrow-odbc-py`. Default features are enabled in build as a workaround.

**Comment by viirya** [comment]
This was duplicated to #2659 and was fixed.

**Comment by pacman82** [comment]
My bad, I did only browse the open issues to avoid duplication. Thanks!

**Comment by viirya** [comment]
No worries. Thanks @pacman82 for reporting this.
