### ISSUE TITLE
Support sorting dictionary encoded primitive integer arrays

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#2679]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Sorting kernels (`sort`, `sort_to_indices`) don't support non-string (such as integer) dictionary arrays currently. We should extend support coverage for other cases such as dictionary encoded primitive integer arrays.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
Automatically added labels {'arrow'} from #2680
