### ISSUE TITLE
DictionaryBuilders can Create Invalid DictionaryArrays

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2684]
**Describe the bug**

Both `StringDictionaryBuilder` and `PrimitiveDictionaryBuilder` are created with existing builders. This is problematic if the key builders are not empty, as these already inserted keys will not be validated

**To Reproduce**

**Expected behavior**

Requiring the builders to create a dictionary builder is a pretty strange API, and I would like to propose just removing it

**Additional context**

**Comment by alamb** [comment]
Automatically added labels {'parquet'} from #2685

**Comment by alamb** [comment]
Automatically added labels {'api-change'} from #2685
