### ISSUE TITLE
Golang Integration Tests Failing

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2688]
**Describe the bug**

The arrow integration tests are failing on master, https://github.com/apache/arrow-rs/runs/8249872730?check_suite_focus=true, this appears to be caused by https://github.com/apache/arrow/pull/14067 which bumps the minimum required Golang version to 1.17.

Unfortunately the version in `apache/arrow-dev:amd64-conda-integration` is 1.16

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by tustvold** [comment]
And now the C++ tests are failing...

**Comment by viirya** [comment]
😅
