### ISSUE TITLE
Support empty projection in `RecordBatch::project`

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-rs#2690]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
When trying to work on removing the workaround for empty projections  in DataFusion, I saw `RecordBatch::project` currently doesn't support  empty projections. Doing so would make it easier to remove this workaround in the future.

**Describe the solution you'd like**

We can add support for this.

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #2691
