### ISSUE TITLE
Sort indices of dictionary string values

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#2697]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We added support of sorting dictionary of primitive integers. That approach is to sort dictionary values only and get sorted indices which will be used when sorting dictionary keys. We can extend this approach to sorting dictionary string.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #2698
