### ISSUE TITLE
Add `DataType` function to detect nested types

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#2704]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
DataFusion handles structured types specially in some cases. It would be nice to have a function in `DataType` to detect this case such as `DataType::is_nested`

Ideally it would follow a similar model to https://docs.rs/arrow/22.0.0/arrow/datatypes/enum.DataType.html#method.is_numeric

**Describe the solution you'd like**
I would like a function like `DataType::is_nested()` or something similar that returns true for `FixedSizeList`, `LargeList`, etc. I think the list is:

```rust
    !matches!(
        field.data_type(),
        DataType::List(_)
            | DataType::FixedSizeList(_, _)
            | DataType::LargeList(_)
            | DataType::Struct(_)
            | DataType::Union(_, _, _)
            | DataType::Map(_, _)
    )
}
```

**Describe alternatives you've considered**

**Additional context**
See https://github.com/apache/arrow-datafusion/pull/3380/files#r967640804

**Comment by alamb** [comment]
This is a pretty straightforward feature to add and would be a great way for someone to contribute

**Comment by kfastov** [comment]
This is my first pull request here, any comments are welcome

**Comment by alamb** [comment]
Automatically added labels {'logical-expr'} from #3380

**Comment by alamb** [comment]
Automatically added labels {'core'} from #3380
