### ISSUE TITLE
Allow creating of TimeUnit instances without directy dependency on parquet-format

### ISSUE THREAD

**Issue by pacman82** [apache/arrow-rs#2708]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Maintaimer of the downstream `odbc2parquet` tool here. I would like to switch from converted type to logical types. One bump in the road of doing so is the fact that `odbc2parquet` now directly needs to depend also on the `parquet-format` crate instead of just `parquet`. The cause being, that it is impossible to create an instance of `TimeUnit` for the logical type, due to it being depended on e.g. `MilliSeconds` or `MicroSeconds` type of the `parquet-format` crate.

**Describe the solution you'd like**

I think I do not fully grasp why the current design has been choosen, so I am not particularly biased towards any solution. I could brainstorm a few ideas though:

* Drop the `MilliSeconds` type tag from the `TimeUnit::MILLIS` variant.
* Give `TimeUnit` constructors for milliseconds, microseconds, etc.
* Reexport `MilliSeconds`, `MicroSeconds`, etc. ..

**Describe alternatives you've considered**

Currently I'll just add the extra **direct** dependency to `parquet-format`. If this is what you want me to do, consider this issue void.
**Additional context**

**Comment by alamb** [comment]
👋  I believe https://github.com/apache/arrow-rs/pull/2626 from @tustvold has removed the dependency entirely on `parquet-format` (by inlining the definitions) so hopefully you won't need any direct dependencies after the next release (tracked by #2665 )

**Comment by pacman82** [comment]
@alamb Thanks for the information and quick response.
@tustvold Thanks for inlining.

Cheers, Markus

**Comment by alamb** [comment]
I believe this is now resolved

**Comment by pacman82** [comment]
> I believe this is now resolved

Yes it is. Already in use downstream. Thanks!
