### ISSUE TITLE
Add overflow-checking variants of arithmetic scalar dyn kernels

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#2712]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Similar to arithmetic scalar kernels, we are going to add overflow-checking variants of arithmetic scalar dyn kernels.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
Automatically added labels {'arrow'} from #2713
