### ISSUE TITLE
`try_binary` should not panic on unequaled array length.

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-rs#2715]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
The function `try_binary` currently panic on `a.len() != b.len()`:
```rust
pub fn try_binary<A, B, F, O>(
    a: &PrimitiveArray<A>,
    b: &PrimitiveArray<B>,
    op: F,
) -> Result<PrimitiveArray<O>>
where
    A: ArrowPrimitiveType,
    B: ArrowPrimitiveType,
    O: ArrowPrimitiveType,
    F: Fn(A::Native, B::Native) -> Result<O::Native>,
{
    assert_eq!(a.len(), b.len());
    ...
```

It is better to let the function return an error in such case because:
1. The return type of the function is a Result;
2. `a.length() != b.length()` is a recoverable error

**Describe the solution you'd like**
1. Replace panic with Err
2. Update the docs

**Describe alternatives you've considered**
We could not do this

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #2717
