### ISSUE TITLE
Float Array should not panic on `DivideByZero` in the `Divide` kernel

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-rs#2719]
**Describe the bug**

Currently, the `math_divide_op` checks the `DivideByZero` error for all primitive types: https://github.com/apache/arrow-rs/blob/master/arrow/src/compute/kernels/arithmetic.rs#L130-L138
This is not correct for the float type because `0.0/0.0 = NaN` and `NotZero/0.0 = (+/-) Infinity`

**To Reproduce**

**Expected behavior**
Don't check the `DivideByZero` error for float type.

**Additional context**

**Comment by HaoYang670** [comment]
Close this issue as we should follow the c++ impl

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #2717
