### ISSUE TITLE
Arrow does not support computing kernel for Decimal type 

### ISSUE THREAD

**Issue by jinmingjian** [apache/arrow-rs#272]
My project is using DataFusion as a query engine. I am surprised to find DF does not support agg on Decimal. Further looking shows, the more foundational problem is Arrow does not support computing kernel for Decimal type.  Am I right? or I make some misunderstanding?

**Comment by jorgecarleitao** [comment]
You are right, it is still not implemented, and it is a valid feature to implement. 👍

**Comment by jinmingjian** [comment]
@jorgecarleitao thanks for confirmation. We may consider to help on this in a near future if no one is planning on this:)

**Comment by sergiimk** [comment]
Ran into this too ... and after I already spent few weeks patching Decimal support in Apache Flink.
A large portion of the datasets we're dealing with are financial, so this is a serious gap in functionality.
Decimal type deserves more love :)

**Comment by tustvold** [comment]
Closed by #2881
