### ISSUE TITLE
The `binary` function should not panic on unequaled array length.

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-rs#2721]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
We've seen somewhere in the code that there are duplicate length checking because `binary` panics on unequaled length:
https://github.com/apache/arrow-rs/blob/master/arrow/src/compute/kernels/arithmetic.rs#L60-L77
https://github.com/apache/arrow-rs/blob/master/arrow/src/compute/kernels/arity.rs#L188

**Describe the solution you'd like**
1. It is bettter to let the result type of `binary` be `Result` and return an error when arrays have different length.
2. We should also update the docs to comment when the function will return an error or panic

**Describe alternatives you've considered**
We could not do this.

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #2750
