### ISSUE TITLE
Automate labeling of `CHANGELOG.md` entries

### ISSUE THREAD

**Issue by iajoiner** [apache/arrow-rs#2727]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Labeling of `CHANGELOG.md` entries should be automated.

**Describe the solution you'd like**

Update `dev/release/update_change_log.sh` to fix this.
**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
I monkeyed around with the github API for a while and I couldn't find any good way to find the issue which was closed by a particular PR (aka I need a way to find the back reference).

Maybe I will simply scrape the CHANGELOG.md and find the issue numbers there 🤔  

https://docs.github.com/en/rest/issues/issues

**Comment by alamb** [comment]
While messing around here, I decided it was best (for me) to develop / test on the actual https://github.com/apache/arrow-rs/pull/2734 PR. So I have committed my script in that PR

**Comment by alamb** [comment]
Here is an example of a ticket that was automatically labeled: https://github.com/apache/arrow-rs/issues/2719#issuecomment-1249451392
