### ISSUE TITLE
API for more ergonomic construction of `RecordBatchOptions`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#2728]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
When creating a `RecordBatchOption`s object it would be nice to use a standard Rust patterns of either

A builder interface :

```rust
let options = RecordBatchOptions::new()
  .with_rows_count(Some(row_count))
```

Or `Default::default()` for `pub` structs:
```rust
let options = RecordBatchOptions{
      row_count:Some(row_count),
      ..Default::default()
    };
```

However, there is no builder interface provided and `RecordBatchOptions` is marked as non-exhaustive so you get this error 

```
error[E0639]: cannot create non-exhaustive struct using struct expression
   --> /home/isidentical/projects/arrow-datafusion/datafusion/core/src/physical_plan/coalesce_batches.rs:295:19
    |
295 |       let options = RecordBatchOptions {
    |  ___________________^
296 | |         row_count: Some(row_count),
297 | |         ..Default::default()
298 | |     };
    | |_____^

For more information about this error, try `rustc --explain E0639`.
```

This means you have to use `mut` like:

```rust
  let mut options = RecordBatchOptions::default();
  options.row_count = Some(row_count);
```

**Describe the solution you'd like**
Add a builder interface for RecordBatchOptions

**Additional context**

See comments from @isidentical https://github.com/apache/arrow-datafusion/pull/3439#discussion_r968556985

**Comment by askoa** [comment]
`let options = RecordBatchOptions{
      row_count:Some(row_count),
      ..Default::default()
    };`

I don't think the above option is possible due to non-exhaustive clause. There is already default implemented for this struct and not working.
