### ISSUE TITLE
Docs CI test is broken with latest nightly

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#2733]
**Describe the bug**
The docs CI test is failing on master

**To Reproduce**
https://github.com/apache/arrow-rs/actions/runs/3062071013/jobs/4942618618

```
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: broken MIR in DefId(
...
```

**Expected behavior**
Tests should pass

**Additional context**
@tustvold  notes in https://github.com/apache/arrow-rs/pull/2693#issuecomment-1248120845 that this is due to https://github.com/rust-lang/rust/issues/101844

**Comment by HaoYang670** [comment]
Could we close this issue? The patch has been merged
```rust
remziy@remziy-mlt:Arrow-rs$ rustup default nightly
info: using existing install for 'nightly-aarch64-apple-darwin'
info: default toolchain set to 'nightly-aarch64-apple-darwin'

  nightly-aarch64-apple-darwin unchanged - rustc 1.65.0-nightly (95a992a68 2022-09-16)
```

**Comment by tustvold** [comment]
It does appear to no longer be failing - https://github.com/apache/arrow-rs/actions/runs/3072636649/jobs/4964248404
