### ISSUE TITLE
Cleanup like and nlike utf8 kernels

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-rs#2744]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
There is quite some repitition in the like / nlike utf8 kernels.

**Describe the solution you'd like**

Create a generic method that can handle like/nlike kernels.

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #2743
