### ISSUE TITLE
Escape contains patterns for utf8 like kernels

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-rs#2745]
**Describe the bug**

@jhorstmann  identified in https://github.com/apache/arrow-rs/pull/2521

> like supports escape characters now (https://github.com/apache/arrow-rs/pull/2258), so I think this also needs to check that the string does not end with '\%'

**To Reproduce**

Fails on master:
```
    test_utf8_scalar!(
        test_utf8_scalar_like_escape_contains,
        vec!["ba%", "ba\\x"],
        "%a\\%",
        like_utf8_scalar,
        vec![true, false]
    );
```

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #2743
