### ISSUE TITLE
`try_unary_dict` should check value type of dictionary array

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#2754]
**Describe the bug**

`try_unary_dict` takes a dictionary array and performs an operation on its value array. But it currently doesn't check the value type. It is possible that the operation takes a different input type than the dictionary array's value type.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #2755
