### ISSUE TITLE
add comparation kernel for decimal array

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-rs#2766]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

In the datafusion, we have implemented them.

We should move them to arrow-rs, and make it compatible with arrow-rs

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
This is currently blocked by #2842

**Comment by tustvold** [comment]
Implemented by #4701
