### ISSUE TITLE
Object Store S3 Alibaba Cloud OSS support

### ISSUE THREAD

**Issue by wjones127** [apache/arrow-rs#2777]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

For supporting Alibaba Cloud OSS, we need to support:

 1. [Virtual-hosted–style requests](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#virtual-hosted-style-access): bucket name in hostname instead of in the path
 2. [Signature version s3v4](https://docs.aws.amazon.com/AmazonS3/latest/API/bucket-policy-s3-sigv4-conditions.html)

See downstream issue delta-io/delta-rs#835.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
Unless I'm mistaken we already sign requests using sigv4 - https://github.com/apache/arrow-rs/blob/master/object_store/src/aws/credential.rs#L49

I think the only requirement therefore is switching to virtual host styled requests, which should be relatively straightforward. The only complicating factor I foresee is how this works when overriding the endpoint

**Comment by askoa** [comment]
I'll pick this up.

**Comment by jiacai2050** [comment]
Hi, I wonder how OSS support is fixed in this PR? it seems #2782 only handle virtual host for S3.

**Comment by tustvold** [comment]
What remains to be supported, I had understood Alibaba Cloud OSS to be S3-compatible like minio or R2?

**Comment by jiacai2050** [comment]
> I had understood Alibaba Cloud OSS to be S3-compatible like minio or R2?

According to docs [here](https://www.alibabacloud.com/help/en/object-storage-service/latest/use-aws-s3-sdk-to-access-oss), yes they are compatible.

I will try to access OSS via S3 client to see if there are any issues.

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#2777](https://github.com/apache/arrow-rs/issues/2777)
