### ISSUE TITLE
Move Primitive arity kernels to arrow-array

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2787]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

#2769 split out the arrays into a separate crate, in order to allow crates to depend on just arrow-array it is important to support basic operations on primitive arrays.

Parquet and IPC, need to perform a basic casts, e.g. Int32 -> Int64 or Date32 -> Date64. These could make use of the cast kernel but this supports a much wider range of types and conversions than is needed, and consequently has a significant dependency and codegen footprint.

**Describe the solution you'd like**

I would like to move the unary, try_unary, binary and try_binary kernels onto PrimitiveArray. The dyn and dictionary variants would remain in their current location for now.

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #2789
