### ISSUE TITLE
ObjectStore Treats Redirect Responses as Success

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2794]
**Describe the bug**

[reqwest::error_for_status_by_ref](https://docs.rs/reqwest/latest/reqwest/struct.Response.html#method.error_for_status_ref) treats a 300 response as a successful request.

**To Reproduce**

Currently there is a bug where if S3 has the wrong region, it receives a redirect response which doesn't get handled correctly. This gets interpreted as a success.

**Expected behavior**

An unhandled redirect should be an error

**Additional context**

**Comment by tustvold** [comment]
Actually this relates to TLS

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#2794](https://github.com/apache/arrow-rs/issues/2794)
