### ISSUE TITLE
S3 Signature Error Performing List With Prefix Containing Spaces 

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2800]
**Describe the bug**

Attempting to perform a list request using a prefix containing a space results in a signature error. 

```
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method
...
```

This is because IAM requires always percent encoding all spaces - https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html

> Percent-encode all other characters with %XY, where X and Y are hexadecimal characters (0-9 and uppercase A-F). For example, the space character must be encoded as %20 (not using '+', as some encoding schemes do)

This is normally the case as we explicitly percent encode paths - https://github.com/apache/arrow-rs/blob/master/object_store/src/aws/client.rs#L471

However, we delegate to reqwest for percent encoding of query parameters, and it uses `+` instead of `%20`.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'object-store'} from #2801

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#2800](https://github.com/apache/arrow-rs/issues/2800)
