### ISSUE TITLE
object_store: support AWS ECS instance credentials

### ISSUE THREAD

**Issue by wjones127** [apache/arrow-rs#2802]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

For EC2, we look at a certain hardcoded IP address to get credentials:

https://github.com/apache/arrow-rs/blob/178319b9f0978fa9be538661981fbfc5925dc17c/object_store/src/aws/credential.rs#L295

For ECS / Fargate, this address needs to be appended with a particular endpoint:

```
169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
```

See: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

This was reported downstream at https://github.com/delta-io/delta-rs/issues/854

**Comment by timvw** [comment]
Does the approach suggested in https://github.com/datafusion-contrib/datafusion-cookbook/tree/main/content/docs/s3-sdk-credentials work for you? (eg: works for me when using aws sso profiles)

**Comment by tustvold** [comment]
I would recommend:

* Provide an option on `AmazonS3Builder` to override the metadata endpoint
* Update [from_env](https://docs.rs/object_store/latest/object_store/aws/struct.AmazonS3Builder.html#method.from_env) to understand `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#2802](https://github.com/apache/arrow-rs/issues/2802)
