### ISSUE TITLE
Allow HTTP S3 URLs

### ISSUE THREAD

**Issue by avantgardnerio** [apache/arrow-rs#2806]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

At Space & Time, we have to be cloud-agnostic, so we are relying on minio deployed inside kubernetes. As such, traffic can be trusted since it is only routed internally within the kubernetes network. We also have automated scripts to stand up new k8s environments for each pull request to enable testing.

This set up works well for us, but it seems like TLS buys us little value and would be difficult to configure (wildcard cert, domain, certificate authority, cert request per PR, etc). We can definitely do this, but it highlights the value to users to have a simpler solution available.

**Describe the solution you'd like**

Expose the existing `allow_http` flag as an environment variable that can be configured at run time.

**Describe alternatives you've considered**

1. A command line arg?
2. Setting up TLS for minio as described above

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#2806](https://github.com/apache/arrow-rs/issues/2806)
