### ISSUE TITLE
Regression: `the trait bound for<'de> arrow::datatypes::Schema: serde::de::Deserialize<'de> is not satisfied`

### ISSUE THREAD

**Issue by domoritz** [apache/arrow-rs#2825]
**Describe the bug**
Arrow 24 does not support de-serializing schemas with the flow code anymore. 

**To Reproduce**
```rust
let schema: Result<arrow::datatypes::Schema, serde_json::Error> =
                serde_json::from_reader(schema_file)
```

The same code used to work with previous arrow versions. See https://github.com/domoritz/csv2parquet

**Comment by tustvold** [comment]
Have you enabled the serde feature on arrow_schema?

**Comment by domoritz** [comment]
No. Do I need to make arrow schema an explicit dependency?

**Comment by tustvold** [comment]
I think you may need to, yes. I didn't plumb a feature flag through when I split the crates apart. This wasn't intentional, but I think I would rather leave it as is, less default features the better even if it was accidental 😅

**Comment by domoritz** [comment]
Thank you. Adding `arrow-schema = { version = "24.0.0", features = ["serde"] }` fixed it. 

Having to update multiple crates concurrently is a bit tricky since dependabot cannot do it right now. It would be awesome if you could make it so that the parquet crate automatically imported arrow and arrow schema at some point. 

I'll close this issue since my issue is solved. Thank you @tustvold!
