### ISSUE TITLE
Deprecate MutableArrayData

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2832]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

`MutableArrayData` provides an API to copy chunks of data from source arrays into an output array, it is extremely flexible, however, its performance leaves a lot to be desired. In particular its reliance on dynamic dispatch per-run not only incurs dispatch overheads, but prevents the compiler from properly vectorising the code. There are also a number of other issues relating to capacity allocation (#347), null mask handling (#1230), dictionary handling (#506)

There has been a fairly concerted effort over the last year or so to move away from use of MutableArrayData:

* Improvements to the Array Builders
* Ability to construct Array from iterators
* Specialized take and filter kernels that only use MutableArrayData as a fallback for nested types

**Describe the solution you'd like**

I would like to eventually deprecate and remove MutableArrayData. I think the only major blockers to this are:

* The filter kernel uses MutableArrayData as a fallback for filtering nested types
* The concat kernel uses MutableArrayData
* No kernel for interleaving multiple arrays together (#1523)

**Describe alternatives you've considered**

**Additional context**

This can be viewed through the lens of porting @jorgecarleitao 's ideas from arrow2 and bringing them into arrow-rs

**Comment by viirya** [comment]
Hm, except for `MutableArrayData`, is there a way to easily copy arrays?

**Comment by tustvold** [comment]
The hope was that all use-cases would be covered by a combination of the `take`, `filter` and `interleave` kernels

**Comment by viirya** [comment]
The most close one is `take`. But I quickly take a look and seems it is not as efficient as `MutableArrayData` for simple copy usage, although I don't run a formal benchmark to verify it.

**Comment by tustvold** [comment]
I think I have made peace with the existence of MutableArrayData
