### ISSUE TITLE
Unsound ArrayData to Array Conversions

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2834]
**Describe the bug**

Not all `Array` validate the `DataType` of the `ArrayData` they are being created from, which can potentially lead to unsound behaviour

**To Reproduce**

This should panic
```
#[test]
fn test_primitive_validation() {
    let foo = PrimitiveArray::<Int32Type>::from_iter([1, 2, 3]);
    PrimitiveArray::<Int64Type>::from(foo.into_data());
}
```

**Expected behavior**

All arrays should verify the type is as expected

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #2835

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #2835
