### ISSUE TITLE
Add pub api for checking column index is sorted

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/arrow-rs#2848]
I think parquet `23.0.0` will have properly exposed arrow definitions (added by @tustvold  in https://github.com/apache/arrow-rs/pull/2626) 

Though now that I see this, I see the proposal is probably to move the functions `columns_sorted` and `check_is_ordered` into the `parquet` crate which makes sense to me (and will likely get reviewed by some others with more parquet knowledge)

@Ted-Jiang can you file a ticket / PR to do so?

_Originally posted by @alamb in https://github.com/apache/arrow-datafusion/pull/3477#discussion_r971211638_

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #2849
