### ISSUE TITLE
More consideration to `Decimal(precision = 0, ..)`

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-rs#2852]
**Which part is this question about**

The definition of the `Decimal` type.

**Describe your question**

The current definition of the decimal type is `Decimal(u8, u8)`, which allows the precision to be zero.
In the Datafusion, we meet as error which the zero precision leads the system to panic: https://github.com/apache/arrow-datafusion/issues/3665.

My questions are:
1. Does `precision = 0` make sense? 
2. If it is, what is the value of `Decimal(0, ..)`?
3. If it is not, how should we avoid the zero precision? Here are 2 ways I think:
    a. Add runtime check to all decimal functions when creating a new decimal type.
    b. Using the `NonZeroU8` to represent precision: https://doc.rust-lang.org/std/num/struct.NonZeroU8.html. Actually, `NonZeroU8` also does runtime checking when creating a value. But the benefit is that the type system help us find where to add the checking. The disadvantage it that we will change the API.

**Additional context**

**Comment by HaoYang670** [comment]
cc @tustvold @liukun4515 @viirya. PTAL. Thank you!

**Comment by tustvold** [comment]
We already have validation that checks if the precision is too high, I think we should just extend that logic. I don't think encoding it in the type system is necessary

**Comment by liukun4515** [comment]
In the datafusion, we can check the value of precision in the SQL level, and make sure the input precision and scale is valid.

**Comment by liukun4515** [comment]
I don't see any system use the `precision = 0`

**Comment by HaoYang670** [comment]
> In the datafusion, we can check the value of precision in the SQL level, and make sure the input precision and scale is valid.

If we can check all `precision = 0` cases during the constant folding stage in Datafusion, then it is great. 👍

However, as this is a bug in arrow-rs, we should also add the zero checking here, because arrow-rs is open to all projects, not only the Datafusion.

My suggestion is to use `NonZeroU8`, which can avoid duplicated checkings. (avoid checking twice in Datafusion and arrow-rs)

**Comment by psvri** [comment]
Hello,

Should we rather refactor the function [`validate_precision_scale`](https://github.com/apache/arrow-rs/blob/master/arrow-array/src/array/primitive_array.rs#L1023) into [`DecimalType`](https://github.com/apache/arrow-rs/blob/master/arrow-array/src/types.rs#L489) . This way we can avoid code duplication in datafusion and expose it to others as well.

**Comment by psvri** [comment]
Okay, I will do the refactor in another PR.

**Comment by tustvold** [comment]
Closed by #3162
