### ISSUE TITLE
Support merge RowSelectors when creating RowSelection

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/arrow-rs#2858]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

When i implementing https://github.com/apache/arrow-datafusion/pull/3780/files#r992227669
find out if we create 
```
let mut selection = RowSelection::from(vec![
            RowSelector::skip(10),
            RowSelector::select(10),
            RowSelector::skip(5),
            RowSelector::skip(5),
        ]);
```
we have tree pages each have 10 rows.
Before introduced #2473, when skipping two  `RowSelector::skip(5)`:
the first one is not enough to skip the whole page, so we need read the page bytes to skip 5 values decoding.
But after #2473,  parquet reader not fetch the third page's bytes according to the `selection` 

**Describe the solution you'd like**

Add annotation at 
https://github.com/apache/arrow-rs/blob/7c8080c6752a55256630f6f6e6c82bf8a540d20b/parquet/src/arrow/arrow_reader/selection.rs#L298-L301
and add one API call `from_and_combine` merge it into
```
            RowSelector::skip(10),
            RowSelector::select(10),
            RowSelector::skip(10),
```

**Describe alternatives you've considered**

**Additional context**

**Comment by Ted-Jiang** [comment]
@tustvold @thinkharderdev  @alamb

**Comment by alamb** [comment]
@Ted-Jiang  I remember some code that combines RowSelectors somewhere -- perhaps https://docs.rs/parquet/24.0.0/parquet/arrow/arrow_reader/struct.RowSelection.html has some inspiration

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #2994
