### ISSUE TITLE
Don't try to infer nulls in CSV schema inference

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-rs#2859]
**Describe the bug**

This came up in https://github.com/apache/arrow-datafusion/issues/3783

I believe it is safer choice to infer nullable types always, and the benefit of having non-null inferred is relatively limited.

**To Reproduce**

Infer csv with nulls that occur after beyond the number of rows schema inference is using.

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #2860
