### ISSUE TITLE
Fix various invalid_html_tags clippy error

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#2861]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Just saw some clippy errors bumped out suddenly when working on other PR. Seems `invalid_html_tags` becomes to warn by default recently.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #2862

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #2862

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow-flight'} from #2862

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet-derive'} from #2862
