### ISSUE TITLE
object_store: Add Put and Multipart Upload Doc Examples

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#2863]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
We hit got an error from S3 when uploading a 5GB file, even though S3 supports objects up to 5TB. The reason we think is that there is a 5GB limit per "part" of a multi-part upload.

Relevant AWS docs:

[A single S3 PUT cannot exceed 5GB](https://docs.aws.amazon.com/AmazonS3/latest/userguide/upload-objects.html)
[Multipart uploads can be 5GB per part, up to 5TB total](https://docs.aws.amazon.com/AmazonS3/latest/userguide/qfacts.html)

**Describe the solution you'd like**
object_store uploads data in multiple parts so the size limit is higher. Perhaps it will also be faster

**Describe alternatives you've considered**

**Additional context**
Hit in the context of https://github.com/influxdata/influxdb_iox/pull/5834

**Comment by tustvold** [comment]
I think this is already supported by the put_multipart API?

**Comment by alamb** [comment]
Maybe some improved documentation examples would help

**Comment by tustvold** [comment]
Updating this issue to cover improving the documentation, in particular adding write examples to the crate docs - https://docs.rs/object_store/latest/object_store/ which already cover listing and fetching objects.

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#2863](https://github.com/apache/arrow-rs/issues/2863)
