### ISSUE TITLE
Pointer freed error when deallocating ArrayData with shared memory buffer

### ISSUE THREAD

**Issue by jyericlin** [apache/arrow-rs#2874]
**Describe the bug**
When creating a ArrayData object with Buffer that uses shared memory, it seems there is a memory freed error when the ArrayData object is being dropped. I think the reason is Rust is trying to free the pointer that is pointing to the shared memory region which is not allowed.
Error:
```
data: ArrayData { data_type: UInt8, len: 4, null_count: 0, offset: 0, buffers: [Buffer { data: Bytes { ptr: 0x1018c2000, len: 4, data: [0, 0, 0, 0] }, offset: 0, length: 4 }], child_data: [], null_bitmap: None }
rust_playground(34082,0x10aa78600) malloc: *** error for object 0x1018c2000: pointer being freed was not allocated
rust_playground(34082,0x10aa78600) malloc: *** set a breakpoint in malloc_error_break to debug
```

**To Reproduce**
The following code can be use to reproduce the error.
```rust
use std::ptr::NonNull;
use shared_memory::{ShmemConf, ShmemError};
use arrow::{array::{ArrayData}, datatypes::DataType, buffer::Buffer};
use tracing::error;

fn main(){
    let os_id = "test_200";
    let shmem = match ShmemConf::new().size(1024).os_id(os_id).create() {
        Ok(m) => m,
        Err(ShmemError::MappingIdExists) => ShmemConf::new().os_id(os_id).open().unwrap(),
        Err(e) => {error!("Unable to create or open shmem os_id {} : {}",os_id, e);
            return
        }
    };
    let ptr = shmem.as_ptr();
    let data = unsafe{        
        let buf = Buffer::from_raw_parts(NonNull::new(ptr).unwrap(), 4, 1024); 
        
        let data = ArrayData::builder(DataType::UInt8)
            .len(4)
            .add_buffer(buf)
            .build()
            .unwrap();

        data
    };
    println!("data: {:?}", data);
    //let _ = std::mem::ManuallyDrop::new(data);   
}
```
Version: 
arrow = "24.0.0"
shared_memory = "0.12.4"

**Analysis and Thought**
Adding ManuallyDrop (shown below) seems to remove the error, but I suspect it would cause some sort of memory leak. 

```let _ = std::mem::ManuallyDrop::new(data);```

Maybe the ArrayData struct can 
1. Have flags to support whether one of its ```buffers: Vec<Buffer>``` should be dropped or not, or
2. Allow removal of buffer from its  ```buffers: Vec<Buffer>```.

Not sure if this is considered a bug or a feature request, but I would like to see if there is solution to this.

**Comment by tustvold** [comment]
@jhorstmann is more familiar with this part of the codebase than myself, but I suspect you need to use [Buffer::from_custom_allocation](https://docs.rs/arrow-buffer/latest/arrow_buffer/buffer/struct.Buffer.html#method.from_custom_allocation). You can then attach an `Arc` to the shared memory segment to ensure it has the appropriate lifetime

Perhaps something like (not tested)

```
use std::ptr::NonNull;
use shared_memory::{ShmemConf, ShmemError};
use arrow::{array::{ArrayData}, datatypes::DataType, buffer::Buffer};
use tracing::error;
use std::sync::Arc;

fn main(){
    let os_id = "test_200";
    let shmem = match ShmemConf::new().size(1024).os_id(os_id).create() {
        Ok(m) => m,
        Err(ShmemError::MappingIdExists) => ShmemConf::new().os_id(os_id).open().unwrap(),
        Err(e) => {error!("Unable to create or open shmem os_id {} : {}",os_id, e);
            return
        }
    };
    let ptr = shmem.as_ptr();
    let allocation = Arc::new(shmem);
    let data = unsafe{        
        let buf = Buffer::from_custom_allocation(NonNull::new(ptr).unwrap(), 1024, allocation); 
        
        let data = ArrayData::builder(DataType::UInt8)
            .len(4)
            .add_buffer(buf)
            .build()
            .unwrap();

        data
    };
    println!("data: {:?}", data);   
}
```

This will drop the shmem segment after the Buffer has been dropped

**Comment by jyericlin** [comment]
Thank you very much @tustvold for the suggestions. I appreciate it. The `Buffer::from_custom_allocation` works well. The only thing I had to modify is to create a dummy object as the allocation instead of `Arc::new(shmem)` as the shmem contains a `*mut u8` which can not be sent between threads safely. Then I can manage the shared memory (creation and free) manually.

**Comment by tustvold** [comment]
> as the shmem contains a *mut u8 which can not be sent between threads safely.

FWIW this sounds like a bug in the shmem crate, they are possibly missing an `unsafe impl Send for ShmemConf` or something.

**Comment by tustvold** [comment]
Going to close this as I think the question has been answered, feel free to re-open if I am mistaken

**Comment by jyericlin** [comment]
> > as the shmem contains a *mut u8 which can not be sent between threads safely.
> 
> FWIW this sounds like a bug in the shmem crate, they are possibly missing an `unsafe impl Send for ShmemConf` or something.

Thanks for mentioning that. I will raise an issue over there to discuss this.
