### ISSUE TITLE
Add Send to ArrayBuilder

### ISSUE THREAD

**Issue by Max-Meldrum** [apache/arrow-rs#290]
Problem:  I'm using a ``StructBuilder`` in [Arcon](https://github.com/cda-group/arcon) to build up Arrow tables.  The threading model ensures exclusive access to the builder but may move it across threads.  The main problem is that ``ArrayBuilder`` does not implement ``Send`` so it fails to compile..

Solution:
```rust
// Old
pub trait ArrayBuilder: Any { .... }
// New
pub trait ArrayBuilder: Any + Send { .... }
```

**Comment by jorgecarleitao** [comment]
Thanks for this.

Honest curiosity: what is the use-case where the ArrayBuilder is passed around?

Also, isn't it possible to use `&dyn ArrayBuilder + Send` on the code to enforce this?

**Comment by Max-Meldrum** [comment]
> Thanks for this.
> 
> Honest curiosity: what is the use-case where the ArrayBuilder is passed around?
> 
> Also, isn't it possible to use `&dyn ArrayBuilder + Send` on the code to enforce this?

Well it is not so much the ArrayBuilder being sent around, but it is a StructBuilder that is passed around which itself contains a bunch of field builders of ``Box<ArrayBuilder>``.  The use case is that a ``StructBuilder`` is used to build up columnar data in a streaming window. During the length of this window, the "worker" may move across threads as the underlying thread model uses a workstealing scheduler.

**Comment by jorgecarleitao** [comment]
makes sense, thanks!
