### ISSUE TITLE
Support reading DecimalArray from JSON data

### ISSUE THREAD

**Issue by nevi-me** [apache/arrow-rs#2900]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The JSON reader doesn't support producing DecimalArray types. I have a `TODO: this is incomplete` that I left on the reader 2 years ago, which was from when DecimalArray support was incomplete/not implemented.

**Describe the solution you'd like**

For the JSON reader to be able to produce decimal arrays if specified in the schema.

**Describe alternatives you've considered**

Coercing decimals to strings or f64, and then casting them after reading. This is inefficient and requires one to programmatically check each field of a schema for JSON fields in order to cast them. Worse as the decimal could be nested inside a list or struct.

**Additional context**

Systems have some freedom when producing JSON data. For example, Debezium has 3 modes for handling decimals [0], where decimals can either be binary, strings or floats. I also vaguely remember some system/process writing the data as bytes.
It would be useful for us to be able to handle at least the modes supported by Debezium.

[0] https://debezium.io/documentation/reference/stable/connectors/sqlserver.html#sqlserver-property-decimal-handling-mode

**Comment by tustvold** [comment]
#2580 is possibly related / could share some logic
