### ISSUE TITLE
support `[+/-]hhmm` and `[+/-]hh` as fixedoffset timezone format

### ISSUE THREAD

**Issue by waitingkuo** [apache/arrow-rs#2910]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

as mentioned in #2909 by @tustvold 
our parsing function for fixedoffset only support format like `+09:00` now. i'd like to extend it to support `+09` and `+0900` as chrono already has this

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #2936
