### ISSUE TITLE
Add `freeze_with_dictionary` API to `MutableArrayData`

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#2914]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We use `MutableArrayData` to copy array data for certain operation. One issue we faced is for DictionaryArray on which the dictionary array value is not extended from too. Because in our usage, arrays can be reused so we cannot rely on same dictionary value array (as it is possibly modified later). We can extend dictionary value array, but  `MutableArrayData` lacks of an API to assign while freezing it.

**Describe the solution you'd like**

Add `freeze_with_dictionary` API to `MutableArrayData`.

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #2915
