### ISSUE TITLE
Add timezone offset for debug format of Timestamp with Timezone

### ISSUE THREAD

**Issue by waitingkuo** [apache/arrow-rs#2917]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

```rust
fn main() {
    let arr = TimestampSecondArray::from_vec(vec![0], Some("America/New_York".to_string()));
    println!("{:?}", a);
}
```

this outputs followings for now
```bash
PrimitiveArray<Timestamp(Second, None)>
[
  1970-01-01 00:00:00,
]
```

**Describe the solution you'd like**

outputs something like this
```bash
PrimitiveArray<Timestamp(Second, Some("America/New_York"))>
[
  1969-12-31 19:00:00 -05:00,
]
```

**Describe alternatives you've considered**

**Additional context**

we could extends 
https://github.com/apache/arrow-rs/blob/22e742bc76b5db333ab2384a92c362662cca3879/arrow-array/src/array/primitive_array.rs#L554-L560

by `as_datetime_with_timezone`  which will be added in #2909

**Comment by waitingkuo** [comment]
@tustvold do you think we should show 
`1970-01-01T00:00:00`
`1969-12-31T19:00:00-05:00`
in this case?

in prettyprint i prefer the one with timezone shift. but for the Debug, should we just show the underline datetime without the offset shift?

**Comment by tustvold** [comment]
My vote would be for consistently outputting RFC3339

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3072
