### ISSUE TITLE
Implement biweekly releases for arrow-rs, parquet-rs

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#292]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Implement the process that will allow us to release to crates.io every 2 weeks as described in the [proposal](https://docs.google.com/document/d/1tMQ67iu8XyGGZuj--h9WQYB9inCk6c2sL_4xMTwENGc/edit?ts=60961758)

See [official vote email chain](https://lists.apache.org/thread.html/rf13d8165728f1083a7d6c7374906c35af8d0b7ecff7fcf2021aa1621%40%3Cdev.arrow.apache.org%3E)

I plan to use this ticket to track the work related to implementing this new process

High level plan / updates:
- [x] Created the active master branch
- [x] PR to update `active_release` to to 4.1.0 version, and create release notes (https://github.com/apache/arrow-rs/pull/305)
- [x] Create example release tarball and ask @andygrove  if it would be uploadable to crates.io
- [x] Create proposed release tarball and send to mailing list for a vote [Mailing List Thread](https://lists.apache.org/thread.html/rd9029f094ee0a75bb774b77bfea8624320c351cff3a4cca428f66813%40%3Cdev.arrow.apache.org%3E)
- [x] (if passed) Promote release tarball to official build and then deploy to crates.io
- [x] Document Process (https://github.com/apache/arrow-rs/pull/299)
- [ ] Put automation in place to automatically cherry-pick PRs to `active_release`
- [x] Remove release scripts left over from apache/arrow repo

**Comment by alamb** [comment]
@jorgecarleitao  is working on changelog creation in https://github.com/apache/arrow-rs/issues/274

There is a packaging issue here: https://github.com/apache/arrow-rs/issues/212

**Comment by alamb** [comment]
Here is what I am thinking for the release workflow (based on the main apache release flow. The major difference is that there is no Release Candidate)

Proposal:
1. Update version on active_release branch with proposed release number 
2. create tag from active_release branch with proposed release number
1. Make a candidate release .tar.gz file with signatures + Upload to apache distro dev dev, e.g. https://dist.apache.org/repos/dist/dev/arrow/apache-arrow-rs-4.1.0/
3. Propose release of that rc on the mailing list
4. if approved: move tarball to release, e.g. https://dist.apache.org/repos/dist/release/arrow/apache-arrow-rs-4.1.0/
5. If not approved, fix whatever the problem is and make a new tag, with a new minor release (aka don't make "RC / release candidates, just skip minor versions)

We will then treat uploading to crates.io as a post official release task done from the official source

I hope to have a script for most of this process (other than the email / approval).

**Comment by alamb** [comment]
High level plan / updates:
- [x] Created the active master branch (taken from `master` @ 3665296b4e985a840ad21815b839e5fa3fc462d5): https://github.com/apache/arrow-rs/tree/active_master
- [ ] PR to update `active_master` to to 4.0.1 version, and create release notes
- [ ] Create proposed release tarball and send to mailing list for a vote
- [ ] (if passed) Promote release tarball to official build and then deploy to crates.io

**Comment by alamb** [comment]
I need help verifying the proposed source tarball format for the Arrow Rust releases;

Specifically, can someone please:
1. Download the example files and ensure they can successfully validate the signatures
2. Ensure that the contents of this tarball could be used to publish to crates.io

Background: I have been working on the new release process for
arrow-rs (updates in [2]).  The contents and changelog in this example
release tarball are from [3] and were created using the scripts /
instructions in [1].

[1] https://github.com/apache/arrow-rs/pull/299
[2] https://github.com/apache/arrow-rs/issues/292
[3] https://github.com/apache/arrow-rs/pull/305

Here is an example output (including Vote Email) generated by script in [1]:

Example output:

```

cd /Users/alamb/Software/arrow-rs/ && ./dev/release/create-tarball.sh  0.0.3
Attempting to create /Users/alamb/Software/arrow-rs/dev/dist/apache-arrow-rs-0.0.3/apache-arrow-rs-0.0.3-f3959f59a.tar.gz from tag 0.0.3
Draft email for dev@arrow.apache.org mailing list

---------------------------------------------------------
To: dev@arrow.apache.org
Subject: [VOTE][RUST] Release Apache Arrow

Hi,

I would like to propose a release of Apache Arrow Rust
Implementation, version 0.0.3.

This release candidate is based on commit: f3959f59a6119dab23818e6eef87e0d7b58c820e [1]

The proposed release tarball and signatures are hosted at [2].
The changelog is located at [3].

Please download, verify checksums and signatures, run the unit tests,
and vote on the release.

The vote will be open for at least 72 hours.

[ ] +1 Release this as Apache Arrow Rust
[ ] +0
[ ] -1 Do not release this as Apache Arrow Rust  because...

[1]: https://github.com/apache/arrow-rs/tree/f3959f59a6119dab23818e6eef87e0d7b58c820e
[2]: https://dist.apache.org/repos/dist/dev/arrow/apache-arrow-rs-0.0.3
[3]: https://github.com/apache/arrow-rs/blob/f3959f59a6119dab23818e6eef87e0d7b58c820e/CHANGELOG.md
---------------------------------------------------------
Running rat license checker on /Users/alamb/Software/arrow-rs/dev/dist/apache-arrow-rs-0.0.3/apache-arrow-rs-0.0.3-f3959f59a.tar.gz
OK
No unapproved licenses
Signing tarball and creating checksums
Uploading to apache dist/dev to https://dist.apache.org/repos/dist/dev/arrow/apache-arrow-rs-0.0.3
Checked out revision 47764.
A         dev/dist/apache-arrow-rs-0.0.3
A  (bin)  dev/dist/apache-arrow-rs-0.0.3/apache-arrow-rs-0.0.3-f3959f59a.tar.gz
A         dev/dist/apache-arrow-rs-0.0.3/apache-arrow-rs-0.0.3-f3959f59a.tar.gz.sha512
A         dev/dist/apache-arrow-rs-0.0.3/apache-arrow-rs-0.0.3-f3959f59a.tar.gz.asc
A         dev/dist/apache-arrow-rs-0.0.3/apache-arrow-rs-0.0.3-f3959f59a.tar.gz.sha256
Adding         dev/dist/apache-arrow-rs-0.0.3
Adding  (bin)  dev/dist/apache-arrow-rs-0.0.3/apache-arrow-rs-0.0.3-f3959f59a.tar.gz
Adding         dev/dist/apache-arrow-rs-0.0.3/apache-arrow-rs-0.0.3-f3959f59a.tar.gz.asc
Adding         dev/dist/apache-arrow-rs-0.0.3/apache-arrow-rs-0.0.3-f3959f59a.tar.gz.sha256
Adding         dev/dist/apache-arrow-rs-0.0.3/apache-arrow-rs-0.0.3-f3959f59a.tar.gz.sha512
Transmitting file data ....done
Committing transaction...
Committed revision 47765.

```

**Comment by andygrove** [comment]
The tarball contains the directory `0.0.3` and it would be better if that were renamed to `apache-arrow-rs-0.0.3`.

**Comment by andygrove** [comment]
I ran the following steps:

- Downloaded tarball
- Checked signatures
- Untarred tarball (see note above suggesting a change to the directory name)
- Ran `cargo test`
- From the arrow directory, ran `cargo publish --dry-run`. Looked good.
- I cannot test publishing other jars because they depend on the arrow jar being published but I ran some grep commands to check that there were no SNAPSHOT versions and that looked good.

So I would say that this format looks ready to go.

**Comment by alamb** [comment]
Thank you @andygrove

**Comment by alamb** [comment]
I'll wait until tomorrow for any other comments, and prepare a release candidate build and send to the mailing list

**Comment by alamb** [comment]
> The tarball contains the directory 0.0.3 and it would be better if that were renamed to apache-arrow-rs-0.0.3.

Sorry @andygrove  I just saw this comment (after I made a release candidate). I will update my script so subsequent releases are named this way

**Comment by alamb** [comment]
Update: we have released version 4.1.0 to crates.io 🎉 

This week I will begin putting in place the code / process for the next release (4.2.0 perhaps?) so we can test the process and tools

**Comment by alamb** [comment]
I started figuring out how to backport individual PRs from master to active_release

Some notes:


Here is the common ancestor commit:
```
git merge-base  apache/master apache/active_release
c863a2c44bffa5c092a49e07910d5e9225483193
```

Thus, you can get the list of commits that are on master but not active release via:a
```
git rev-list `git merge-base  apache/master apache/active_release`..apache/master
```

Here is the list in pretty format:
```
git rev-list --pretty=oneline `git merge-base  apache/master apache/active_release`..apache/master
```

5295e253c46f217a7b75dd8d7f3d751cfc34a460 Document and automate new release process (#299)
5ac771a6831c243e4fd8560b9cb5e13f8a81af34 respect offset in utf8 and list casts (#335)
4c17ac8e27a899c8a1d205657e1861c3b5eec3e5 feature gate ipc reader/writer (#336)
b2de5446cc1e45a0559fb39039d0545df1ac0d26 parquet: Speed up `BitReader`/`DeltaBitPackDecoder` (#325)
91ef8e9bc6b8e4e0f40c0456e01251251b063362 Enable wasm32 as a target architecture for the SIMD feature  (#324)
b88ef807555e5c8e8335afc86d76cbd1796406eb fix comparison of dictionaries with different values arrays (#332) (#333)
f316798749f902e11a27b349781053d2dd55be80 Fix undefined behavior in FFI (#323)
a25cafb5e1e5cbd371433b0ff251386279c0aa6c Add ported Rust release verification script (#331)
71c21595a0856e4f87838c8c3bb5f2b04fb88024 return reference from DictionaryArray::values() (#313) (#314)
dde86b96206b94dde48f2fd0a39103120a18c4ff feature gate csv functionality (#312)
f042191578cbc2329957015fa0b8d2f01d51ddbd fix invalid null handling in filter (#296)
e18b356b1310d5b178f7b6290993b920d3fe7edd Doctests for StringArray and LargeStringArray. (#330)
087cf17edcabce032a473a80fcd1d952904b4b13 inline PrimitiveArray::value (#329)
7f37a7f2a119dd83c497766265707a64d9b82307 Mutablebuffer::shrink_to_fit (#318)

I have  started working through this list (from bottom) creating prs using the script in https://github.com/apache/arrow-rs/pull/339 with an initial PR https://github.com/apache/arrow-rs/pull/344:

```
ARROW_GITHUB_API_TOKEN=$ARROW_GITHUB_API_TOKEN CHECKOUT_ROOT=/tmp/arrow-rs CHERRY_PICK_SHA=7f37a7f2a119dd83c497766265707a64d9b82307 python3 dev/release/cherry-pick-pr.py
```

**Comment by alamb** [comment]
I made several more PRs: #354 #355 #356 #357 #358 #359 as an attempt to cherry pick to release

**Comment by jorgecarleitao** [comment]
IMO the is no need to PR these? We could just cherry-pick and merge based on whether they have the label "breaking-change" or not. Alternatively, use an inverse label, "minor-change" (i.e. if we want to be explicit over what to include vs what not to include).

**Comment by alamb** [comment]
@jorgecarleitao  I will think about this -- the  extra human control / auditing of "we explicitly wanted to include this change in the release" is important I think.  However there may be too many PRs with this method 🤔

**Comment by alamb** [comment]
@jorgecarleitao , upon more thought I plan to keep doing PRs for the following reason:
1. It is a natural place to run the CI tests to make sure there are no logical conflicts
2. It offers a place for the original author / committers to comment and say it should/should not be backported.
3. It offers a way to make cleanups / fixups and approve (if needed) for non cherry pick PRs

For clean cherry-pick PRs I will plan on just merging the backport PRs when they are green in CI rather than waiting for a re-approval (given the code was already approved and we will have another "approve the whole release" vote). If the PR needs changes, we can get it approved prior to merging

**Comment by jorgecarleitao** [comment]
Sounds good 👍 . One idea would be to have a single PR with all the cherry-picks, so that we only have to review one PR. We could then merge then without squashing; no strong feelings, though; was just trying to avoid a bunch of PRs that were already reviewed. ^_^

**Comment by alamb** [comment]
👍  Let's give this PR per backport a try for a while and see how it goes

**Comment by alamb** [comment]
I have added some labels to help the process here: https://github.com/apache/arrow-rs/pull/409

**Comment by alamb** [comment]
This is about as done as I expect it to be. Closing this ticket 🎉
