### ISSUE TITLE
Cast Timestamps to RFC3339 strings

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2934]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently timestamps are cast to the default chrono format, such as `2018-01-26 18:30:09.453829 +08:00`. This is not a defined standard, it appears to be RFC3339 but using spaces.

**Describe the solution you'd like**

Cast timestamps to strings as RFC3339

**Describe alternatives you've considered**

We could not do this

**Additional context**

**Comment by waitingkuo** [comment]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=42768115ab784d65df24ca371c09f985

the debug version follows RFC3339

```rust
use chrono; // 0.4.22
use chrono::{TimeZone, FixedOffset};

fn main() {
    let dt = FixedOffset::east(8 * 60 * 60).ymd(2018, 1, 26).and_hms_micro(18, 30, 9, 453_829);
    println!("{}", dt);
    println!("{:?}", dt);
}
```

```
2018-01-26 18:30:09.453829 +08:00
2018-01-26T18:30:09.453829+08:00
```

**Comment by waitingkuo** [comment]
i think we could use `to_rfc3339()` while displaying
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=42768115ab784d65df24ca371c09f985

**Comment by jhorstmann** [comment]
[`to_rfc3339_opts`](https://docs.rs/chrono/latest/chrono/struct.DateTime.html#method.to_rfc3339_opts) also allows specifying how many fractional digits and whether to use a `Z` instead of `+00:00` for UTC.
