### ISSUE TITLE
SerializedFileWriter comments about multiple call on consumed self

### ISSUE THREAD

**Issue by pier-oliviert** [apache/arrow-rs#2935]
**Which part is this question about**

I was reading comments surrounding the `SerializedFileWriter` code as I was implementing the writer on a codebase I'm working on and noticed this comment: 
> Can be called multiple times. It is up to implementation to either result in
    no-op, or return an `Err` for subsequent calls.

https://github.com/apache/arrow-rs/blob/master/parquet/src/file/writer.rs#L180-L181

**Describe your question**

The code itself is clear enough to understand what is going on but I noted that the signature consumes `self` which makes me think that it's not really possible, in general, to call this method twice since `self` will be consumed and is not included in `FileMetaData`.

Should the comment be modified? Or am I missing something else with regards to the writer.

**Comment by tustvold** [comment]
Aah, thank you yeah this is out of date. The writer was changed to be consuming in #1719

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #2938
