### ISSUE TITLE
Add Page Row Count Limit

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2941]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Skipping pages is often significantly cheaper than skipping values within a page, as such we want a reasonable granularity of pages within a column chunk. However, parquet's encodings can be very efficient leading to a very large number of rows in a single page before hitting the page size limit

**Describe the solution you'd like**

Add an optional page row count limit to the parquet writer, that limits the maximum number of rows within a page. 

**Describe alternatives you've considered**

**Additional context**

Impala has such an option for the same reason

**Comment by alamb** [comment]
related to https://github.com/apache/arrow-datafusion/issues/3462
