### ISSUE TITLE
Pass Decompressed Size to Parquet Codec::decompress

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2956]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We know the size of the decompressed data, as this information is provided in the page header. We can potentially avoid unnecessary reallocations by passing this down to the codecs.

**Describe the solution you'd like**

Add an optional `uncompressed_size: Option<usize>` to `Codec::decompress`

**Describe alternatives you've considered**

**Additional context**

**Comment by marioloko** [comment]
Then, I guess that the internal behavior of the `decompress` methods should be something like:

```
let uncompressed_size = uncompressed_size
    .unwrap_or_else(|| estimate_max_size(compressed_size));
```
