### ISSUE TITLE
Use unary function for numeric to decimal cast

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#2972]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

There are a few functions written for casting numeric array to decimal array. But its functionality can be achieved by existing `unary` function. We should use `unary` to reduce duplicateion.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
This should also be significantly faster
