### ISSUE TITLE
Decimal Casts are Unchecked

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#2986]
**Describe the bug**

Most numeric casts, e.g. Int16 - Int8, are checked and will return an error (or null) on overflow. By contrast the decimal conversions are not. In particular:

* decimal to decimal conversion
* float to decimal conversion
* decimal to integer
* integer to decimal

**To Reproduce**

**Expected behavior**

**Additional context**

I believe @viirya intends to work on this, but wanted to create a ticket so it didn't get lost

**Comment by viirya** [comment]
Yea, thanks @tustvold

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3076

**Comment by tustvold** [comment]
Not sure if this should be reopened or a new issue created, but https://github.com/apache/arrow-rs/pull/3203 would suggest that truncation is not properly checked yet
