### ISSUE TITLE
I would like to round rather than truncate when casting f64 to decimal

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-rs#2997]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

If I convert `0.06999999` to a decimal with scale 2 I would like to get `0.07` rather than `0.06`

```rust
    #[test]
    #[cfg(not(feature = "force_validate"))]
    fn test_cast_f64_to_decimal128() {
        let decimal_type = DataType::Decimal128(18, 2);
        let array = Float64Array::from(vec![
            Some(0.0699999999),
        ]);
        let array = Arc::new(array) as ArrayRef;
        generate_cast_test_case!(
            &array,
            Decimal128Array,
            &decimal_type,
            vec![
                Some(7_i128),
            ]
        );
    }
```

This fails with:

```
Left:  6
Right: 7
```

**Describe the solution you'd like**

Provide an option for round vs truncate?
Default to round?

**Describe alternatives you've considered**

**Additional context**

**Comment by andygrove** [comment]
@liukun4515 @viirya fyi

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3000
