### ISSUE TITLE
Add `RowSelection::intersection`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#3003]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
While @Ted-Jiang  was working on https://github.com/apache/arrow-datafusion/pull/3967 he needed code to intersect two row selections:

```rust
// combine two `RowSelection` return the intersection
// For example:
// self:     NNYYYYNNY
// other:    NYNNNNNNY
//
// returned: NNNNNNNNY
// set `need_combine` true will combine result: Select(2) + Select(1) + Skip(2) -> Select(3) + Skip(2)
```

The code and tests are in DataFusion

**Describe the solution you'd like**
I would like to code and tests brought to arrow-rs 

see `pub(crate) fn intersect_row_selection(` specifically

**Describe alternatives you've considered**
Leave in DataFusion

**Additional context**

**Comment by paddyhoran** [comment]
+1 for moving this down into `arrow-rs`
