### ISSUE TITLE
Replace temporal _generic kernels with dyn

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#3004]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The temporal _generic methods exist to handle dictionaries, but do so in a way inconsistent with the other kernels such as arithmetic:

* Don't return a dictionary array
* Require explicitly downcasting the dictionary

**Describe the solution you'd like**

Instead of _generic kernels I would like an _dyn kernel that takes an `&dyn Array`.

In the case of a dictionary, this will recurse calling itself on the dictionary values, and then use 
https://docs.rs/arrow-array/latest/arrow_array/array/struct.DictionaryArray.html#method.with_values to replace the values with the newly computed

**Describe alternatives you've considered**

We could not do this

**Additional context**

FYI @viirya

**Comment by viirya** [comment]
> Don't return a dictionary array
> Require explicitly downcasting the dictionary

I think that arithmetic kernels don't return a dictionary array for input dictionaries?
But for temporal kernels, it sounds reasonable to do as the keys should be the same.

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3041
