### ISSUE TITLE
Replace hour_generic with hour_dyn

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#3005]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Part of #3004.

Replace `hour_generic` with `hour_dyn`:

* Keep consistent with other kernels
* Return dictionary for dictionary input

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3006
