### ISSUE TITLE
Add macro downcast_temporal_array

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#3008]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

While I'm working on replacing temporal `_generic` with `_dyn` kernel, it needs to match temporal types. A macro `downcast_temporal_array` will be useful.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3007
