### ISSUE TITLE
More examples of how to construct Arrays

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#301]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Imagine a user who wants to make a StringArray. They go to the docs, and find [StringArray](https://docs.rs/arrow/4.0.0/arrow/array/type.StringArray.html)
And now what?

![Screen Shot 2021-05-16 at 7 42 57 AM](https://user-images.githubusercontent.com/490673/118395815-6122af00-b61a-11eb-8bbc-55d30fd8afc1.png)

**Describe the solution you'd like**
Adding an example (or a pointer to such an example) to each of the Array types (e.g things that implement [Array](https://docs.rs/arrow/4.0.0/arrow/array/trait.Array.html) of how to construct them (from iterators) such as 

```
let array = StringArray::from(vec![Some("foo"), None, Some("bar")]);
```

(and taking inspiration from the examples in the main docs https://docs.rs/arrow/4.0.0/arrow/index.html)

would probably be super helpful.

**Describe alternatives you've considered**

**Additional context**

**Comment by novemberkilo** [comment]
Thanks for the write up @alamb - I will pick this up if that’s ok?

**Comment by novemberkilo** [comment]
@alamb it looks like there are several other array types that do not have examples. Shall I continue in the same vein as #330 to annotate them with doctests?

**Comment by alamb** [comment]
@novemberkilo  yes I think adding examples / documentation to all the array types (including Boolean array) would be great! 

Thank you so much

**Comment by alamb** [comment]
Reopening as @novemberkilo  has plans for additional PRs

**Comment by novemberkilo** [comment]
keep-alive -- I'm still on this // @alamb
