### ISSUE TITLE
Some clippy errors after updating rust toolchain

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#3011]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

There are some clippy errors after updating rust toolchain, e.g.:

```
error: parameter is only used in recursion
   --> arrow-schema/src/field.rs:208:24
    |
208 |     fn _fields<'a>(&'a self, dt: &'a DataType) -> Vec<&Field> {
    |                        ^^^^
    |
    = note: `-D clippy::only-used-in-recursion` implied by `-D warnings`
note: parameter used here
   --> arrow-schema/src/field.rs:217:53
    |
217 |             DataType::Dictionary(_, value_field) => self._fields(value_field.as_ref()),
    |                                                     ^^^^
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#only_used_in_recursion
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'object-store'} from #3015

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #3010

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3010

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet-derive'} from #3010

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#3011](https://github.com/apache/arrow-rs/issues/3011)
