### ISSUE TITLE
Document `from_iter` methods and

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#302]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Users  can create arrow arrays in one of two ways:
1. Directly from an `Iterator` or `vec` (via methods such as [from_iter](https://docs.rs/arrow/4.0.0/arrow/array/struct.GenericStringArray.html#method.from_iter) and this we can use `collect()`)
2. Using a builder (something that implements [ArrayBuilder](https://docs.rs/arrow/4.0.0/arrow/array/trait.ArrayBuilder.html)) 

Typically the `from_iterator` method is both easier to use and faster, but it is not well documented in the doc strings

**Describe the solution you'd like**
1. Add doc examples for `from_iter` methods (we can file additional issues for subsets of these iterators)
2. Add doc examples for the builders (such as https://docs.rs/arrow/4.0.0/arrow/array/struct.BooleanBuilder.html) and also link to the `from_iter` methods

**Comment by novemberkilo** [comment]
Am also good to run with this. Please assign to me as appropriate. Thanks @alamb

**Comment by alamb** [comment]
BTW @novemberkilo  there are probably lots of good examples to from the tests that can be pulled into the doc examples

**Comment by novemberkilo** [comment]
@alamb I'm not sure what else I should try and cover in this issue. Can you please help identify what the gap is to closing this issue? Thanks.

**Comment by alamb** [comment]
Thanks @novemberkilo  -- basically I think this is a very common pattern when using Arrow to create arrays via the `collect` method:

```
let arr : Int32Array = [Some(1), Some(2)].into_iter().collect();
```

I am not sure if that is already documented

**Comment by novemberkilo** [comment]
Roger - will add such to examples 👍🏽

**Comment by ByteBaker** [comment]
@alamb can we close this probably?
