### ISSUE TITLE
Check overflow when casting floating point value to decimal128

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#3020]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Part of https://github.com/apache/arrow-rs/issues/2986.

This deals with the case of casting floating point value to decimal128.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3021
