### ISSUE TITLE
Compare i256 in validate_decimal256_precision

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#3024]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

`validate_decimal256_precision` validates decimal 256 values by comparing little-endian bytes of decimal value with const byte values. As we moved to i256 now, we can compare i256 directly.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3025
