### ISSUE TITLE
[object_store] Support signed URLs

### ISSUE THREAD

**Issue by milesj** [apache/arrow-rs#3027]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Generate signed URLs so that a user can temporarily download a private file.

- S3 - https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html
- GCS - https://cloud.google.com/storage/docs/access-control/signed-urls

**Describe the solution you'd like**

A method on the `ObjectStore` trait that will generate a signed URL using the configured credentials. Something like:

```
store.generate_signed_url(path, Duration::from_secs(120));
```

**Describe alternatives you've considered**

None.

**Additional context**

It would be nice if this crate supported this functionality, otherwise I'm having to interact with the S3 and GCS clients directly, which is me basically duplicating a lot of functionality this crate already has.

**Comment by tustvold** [comment]
I would be very happy to review a PR adding support for this, as you say most of the necessary functionality already exists

**Comment by milesj** [comment]
Yeah I'll look into it when I have a few hours to spare.

**Comment by ByteBaker** [comment]
Hi,

I wanna take this issue up. Have a piece of code ready for S3 & ADLS. Will write the code for GCS. My question is, what should be the behaviour for local file system?

**Comment by ByteBaker** [comment]
Hi,

I wanna code this feature. Have some code ready for S3 & ADLS. Will write the code for GCS. My question is, what should be the behaviour for local file system?

**Comment by alamb** [comment]
@milesj  FYI there is some more discussion about this idea on https://github.com/apache/arrow-rs/issues/4763 in case you have time to help

**Comment by tustvold** [comment]
I have split this ticket into two smaller tickets:

- https://github.com/apache/arrow-rs/issues/5232
- https://github.com/apache/arrow-rs/issues/5233

Therefore going to close this one
