### ISSUE TITLE
RLEDecoder::get_batch_with_dict may panic on bit-packed runs longer than 1024

### ISSUE THREAD

**Issue by wolfv** [apache/arrow-rs#3029]
**Describe the bug**

Reading a specific parquet file triggers: thread 'main' panicked at 'index out of bounds: the len is 1024 but the index is 1024', /Users/wolfvollprecht/Programs/arrow-rs/parquet/src/encodings/rle.rs:492:25

The max-index size computation is wrong.

**Comment by tustvold** [comment]
I've found the underlying cause of this is an accounting bug in `RLEDecoder::get_batch_with_dict`

In particular if the runs are longer than 1024, it may try to read more values from the underlying bit reader than there is capacity for. If the actual number of values is not a multiple of 8, this will return more values, as the length of bit packed runs is actually ambiguous. Such a scenario will result in a panic when it tries to copy these values across.

Will post a PR to fix shortly

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #3036
