### ISSUE TITLE
Support casting Date64 to Timestamp

### ISSUE THREAD

**Issue by gruuya** [apache/arrow-rs#3037]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Currently the cast kernel supports casting from Timestamp to Date64, but not the other way around
```
Unsupported CAST from Date64 to Timestamp(Nanosecond, None)
```

**Describe the solution you'd like**
In principle I think there should be no problem casting back from Date64 into Timestamps with adequate unit conversions, having in mind the time resolution of Date64 (milliseconds).

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3038
