### ISSUE TITLE
Improved UX of  creating `TimestampNanosecondArray` with timezones

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#3042]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
While working on https://github.com/apache/arrow-datafusion/pull/4039 and https://github.com/influxdata/influxdb_iox/pull/6061 I ended up having to do this many times:

```rust
Arc::new(TimestampNanosecondArray::from(vec![...],)
  .with_timezone("+0:00".into())
```

While this API is already nicer than previously, there are two more improvements that might help:

**Describe the solution you'd like**
Allow passing `&str` as well as `String` to `with_timezone`:

```rust
Arc::new(TimestampNanosecondArray::from(vec![...],)
  .with_timezone("+0:00")
```

Add an alias for UTC:
```rust
Arc::new(TimestampNanosecondArray::from(vec![...],)
  .with_timezone_utc()
```

**Describe alternatives you've considered**

**Additional context**
cc @waitingkuo  who is actively working to improve the timezone situation in arrow / datafusion ❤️ 

I think this is a good first issue as the code and tests are already there, all that is needed is a signature change (from `String` to `impl Into<String>`) and some tests

**Comment by waitingkuo** [comment]
i'll take it if there's no one take it this week or next.
if there's anyone interested in, i happy to point out the codes to modify

**Comment by src255** [comment]
@waitingkuo I can help with this. Which file(s) should I modify?

**Comment by waitingkuo** [comment]
@src255 
you could add the `with_timezone_utc()` here
https://github.com/apache/arrow-rs/blob/master/arrow-array/src/array/primitive_array.rs#L762-L797

and follow this to add a test case
https://github.com/apache/arrow-rs/blob/master/arrow-array/src/array/primitive_array.rs#L1340-L1353
