### ISSUE TITLE
Errata in the Row Format blog

### ISSUE THREAD

**Issue by doki23** [apache/arrow-rs#3059]
I'm reading the [blog](https://arrow.apache.org/blog/2022/11/07/multi-column-sorts-in-arrow-rust-part-2/) and confusing about the example of format of `Byte Arrays` which is shown as the following:
```
"Defenestration"      ┌───┬───┬───┬───┬───┬───┐
                      │02 │'D'│'e'│'f'│'e'│FF │
                      └───┼───┼───┼───┼───┼───┤
                          │'n'│'e'│'s'│'t'│FF │
                          ├───┼───┼───┼───┼───┤
                          │'r'│'a'│'t'│'r'│FF │
                          ├───┼───┼───┼───┼───┤
                          │'a'│'t'│'i'│'o'│FF │
                          ├───┼───┼───┼───┼───┤
                          │'n'│00 │00 │00 │17 │
                          └───┴───┴───┴───┴───┘
```
The length of remainder should be `0x01` instead of `0x17`, right?

**Comment by tustvold** [comment]
You are quite correct, filed https://github.com/apache/arrow-site/pull/270

**Comment by tustvold** [comment]
Closed by https://github.com/apache/arrow-site/pull/270
