### ISSUE TITLE
Deprecate Buffer::count_set_bits

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#3067]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

`Buffer::count_set_bits` is easy to incorrectly use, as `Buffer` does not know its accurate length in bits, only in bytes.

This led to #3061

**Describe the solution you'd like**

I would like to deprecate `Buffer::count_set_bits` in favour of `Buffer::count_set_bits_offset` which is less easy to accidentally misuse.

**Describe alternatives you've considered**

**Additional context**

**Comment by viirya** [comment]
Looks good to me. I think mostly we care about `count_set_bits_offset`, not `count_set_bits`.

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3062
