### ISSUE TITLE
Debug format for timestamp ignores timezone

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#3069]
**Describe the bug**

The `Debug` implementation for `PrimitiveArray` ignores the timestamp of timestamp arrays.

**To Reproduce**

```
let a = TimestampSecondArray::from(vec![Some(86405), Some(1), None])
     .with_timezone("+01:00".to_string());

    println!("{:?}", a);
```

Returns

```
PrimitiveArray<Timestamp(Second, Some("+01:00"))>
[
  1970-01-02T00:00:05,
  1970-01-01T00:00:01,
  null,
]
```

Whereas

```
let a = Arc::new(TimestampSecondArray::from(vec![Some(86405), Some(1), None])
            .with_timezone("+01:00".to_string())) as ArrayRef;
    let t = cast(&a, &DataType::Utf8).unwrap();
    println!("{:?}", t);
```

Returns

```
StringArray
[
  "1970-01-02 01:00:05 +01:00",
  "1970-01-01 01:00:01 +01:00",
  null,
]
```

**Expected behavior**

The string cast was fixed by @viirya in #2608

**Additional context**

FYI @waitingkuo

**Comment by waitingkuo** [comment]
@tustvold 
i think this is similar as #2917 
i only fixed the prettyprint one but not the debut information because i'm not sure is it intended to let the user to see the underline timestamp

**Comment by waitingkuo** [comment]
i can submit a pr for this if showing timestamp with time zone shift is preffered

**Comment by tustvold** [comment]
Aah yes closing as duplicate of #2917

And I at least found the inconsistency very confusing

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3016
