### ISSUE TITLE
Inconsistent Nan Handling Between Scalar and Non-Scalar Comparison Kernels

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#3074]
**Describe the bug**

The scalar kernels use ArrowNativeTypeOp and therefore `total_cmp` to order values, the non-scalar kernels do not.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by viirya** [comment]
Oh, I may miss this piece. I will work on filling this gap after verifying it.

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3075
