### ISSUE TITLE
Row Format: API to check if datatypes are supported

### ISSUE THREAD

**Issue by crepererum** [apache/arrow-rs#3077]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I'm trying to use the arrow row format in DataFusion. For that it would be helpful to know early (read: before piping any actual payload through physical execution) if a certain data type is supported by the row format or not.

**Describe the solution you'd like**
`RowConverter::new` should check supported types and return a `Result<>` if types are not supported. `RowConverter::convert_{columns,rows}` should never bail out due to unsupported types.

**Describe alternatives you've considered**
Piping some one-row payload through the converter to check if the types would be supported. This seems to be a hack though.

**Additional context**
\-

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3080
