### ISSUE TITLE
Implement some way to self assign tickets without having full edit access to github

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#308]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

When someone selects an issue to work on in arrow-rs there is no good way for them to "assign" the ticket to themselves and they have to resort to comments like "I would like to work on this one" or ask one of the maintainers to assign the ticket to themselves

**Describe the solution you'd like**
One idea would be a "claim"-bot that let's you self-assign unassigned tickets w/o the need to have full edit permissions

**Describe alternatives you've considered**
TBD

**Additional context**
Suggested by @crepererum

**Comment by dsgibbons** [comment]
This ticket can be closed now #6059 has been merged.

**Comment by alamb** [comment]
Thank you @dsgibbons
