### ISSUE TITLE
Change Field::metadata to HashMap

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#3086]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently Schema::metadata is `HashMap<String, String>`, whereas Field::metadata is `Option<BTreeMap<String, String>>`. This is not only inconsistent, but it is unclear why there is an additional `Option`

**Describe the solution you'd like**

I would like to change `Field::metadata` to a `HashMap` for consistency with Schema

**Describe alternatives you've considered**

**Additional context**

**Comment by askoa** [comment]
I'll pick this up.

**Comment by askoa** [comment]
I am also having difficulty in removing Optional in below function

https://github.com/apache/arrow-rs/blob/01396822eb68a90565cf8b177aab4b0ce8af40e1/arrow-schema/src/field.rs#L133-L138

I changed the function as below 

```
    #[inline]
    pub const fn metadata(&self) -> &BTreeMap<String, String> {
        &self.metadata
    }

```


and getting lot of compile errors in `decimal.rs`. I don't see how the function `i256::from_le_bytes` is impacted by changing the above function. Any ideas?

```
"cannot call non-const fn `i256::from_le_bytes` in constants\ncalls in constants are limited to constant functions, tuple structs and tuple variants",
```

**Comment by tustvold** [comment]
That sounds like a compiler bug to me, I'd try a clean rebuild and see if it goes away.

Regarding Ord, etc... I'm not entirely sure why they are implemented for Field... Perhaps this is something to understand before proceeding with this.

Perhaps @alamb has some recollection?

**Comment by alamb** [comment]
As I recall the reason it was initially implemented as a `Ord` was something related to JSON serialization which is likely no longer relevant. Maybe @nevi-me  has more historical context. 

BTW if we are going to have all downstream consumers have to change their code, perhaps we can change this to `Option<HashMap<....>>` while we are at it to make creating fields more efficient

**Comment by tustvold** [comment]
What is the purpose of the additional Option?

**Comment by alamb** [comment]
>  An empty HashMap doesn't cost anything?

I guess I assumed (though have not verified) that having to do `HashMap::new()` whenever a new Field is created requires non zero effort.

**Comment by tustvold** [comment]
I think if we need to keep cmp, it makes sense to continue to use BTreeMap.

If you don't need ordering, HashMap is almost always faster

**Comment by askoa** [comment]
I think the `keys` should be sorted while calculating the hash. So I think both `cmp` and `hash` functions will have overhead while using `HashMap`

**Comment by tustvold** [comment]
Agreed, if these are important use cases we should stick with a BTreeMap. I am, however, unclear on the use-case for them

**Comment by askoa** [comment]
I have created PR #3091 to remove `Option` from `Field::metadata`. Will update the PR to change from `BTreeMap` to `HashMap` based on what is agreed in this thread.

**Comment by askoa** [comment]
I was wondering if there is a way to determine the impact of removing `cmp` and `hash` functions?

**Comment by tustvold** [comment]
Nothing like a good old-fashioned scream test? i.e. remove them and see if anyone complains :sweat_smile:

**Comment by tustvold** [comment]
Aah yeah, the issue is that we want to provide `Hash` and `PartialOrd` for `DataType`, and some of the complex datatypes such as lists contain `Field`. Sticking with BTreeMap makes sense as a result :+1:

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #3148

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3148
