### ISSUE TITLE
csv feature gate

### ISSUE THREAD

**Issue by ritchie46** [apache/arrow-rs#309]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
We would like optional IO features

**Describe the solution you'd like**
Putting certain IO logic behind a feature gate and thereby reducing compilation size (including some dependencies)

**Comment by Dandandan** [comment]
From the thread on Slack:

what about separating json / csv from the arrow crate just like the parquet crate? IMO this is easier to manage and also easier to use/understand. 
[...] I think features / conditional compilation introduce more complexity than a separate crate would in terms of organization, discoverability and testing.
