### ISSUE TITLE
Improve "Fail to merge schema" error messages

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-rs#3095]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I am seeing this error:

```
ArrowError(SchemaError("Fail to merge schema Field due to conflicting datatype"))
```

It does not tell me which field has the issue or what the conflicting data types are.

**Describe the solution you'd like**

I would like the error to give me more information.

**Describe alternatives you've considered**

**Additional context**

**Comment by askoa** [comment]
I'll pick this up.

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3098
