### ISSUE TITLE
Be able to parse time formatted strings

### ISSUE THREAD

**Issue by Jefffrey** [apache/arrow-rs#3100]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Original issue: https://github.com/apache/arrow-datafusion/issues/3176

Be able to parse strings of format like `00:00:00.000` (and its variants) into respective `Time32`/`Time64` type, especially when reading in from CSV file.

**Describe the solution you'd like**

Enable more than simple primitive parsing for `Time32`/`Time64` type

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3101
