### ISSUE TITLE
Upgrade to thrift 0.17

### ISSUE THREAD

**Issue by Jimexist** [apache/arrow-rs#3105]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Upgrade to thrift 0.17

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #3104

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3104
