### ISSUE TITLE
Implements more temporal kernels using time_fraction_dyn

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#3108]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

This change implements more temporal kernels using `time_fraction_dyn`: https://github.com/apache/arrow-rs/pull/3046#discussion_r1017724762

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3107
