### ISSUE TITLE
Should be the rounding vs truncation when cast decimal to smaller scale 

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-rs#3137]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

**Describe the solution you'd like**

https://github.com/apache/arrow-rs/issues/1043#issuecomment-1313193183

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3139
