### ISSUE TITLE
support comparison for decimal128 array with scalar in kernel

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-rs#3140]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

in order to replace all comparison operation in the [datafusion](https://github.com/apache/arrow-datafusion/issues/4289) using the arrow-rs kernel

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3141
