### ISSUE TITLE
create an integration test set for parquet crate against pyspark for working with bloom filters

### ISSUE THREAD

**Issue by Jimexist** [apache/arrow-rs#3167]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

**Describe the solution you'd like**

as title. the work can be done using pytest
**Describe alternatives you've considered**

**Additional context**

this shall be considered a part of:
- #3023

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #3165
