### ISSUE TITLE
Use RegexSet in arrow_csv::infer_field_schema

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#3211]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Using a [RegexSet](https://docs.rs/regex/latest/regex/struct.RegexSet.html) for matching multiple expressions simultaneously should yield a non-trivial speedup

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by askoa** [comment]
I'll pick this up.

**Comment by tustvold** [comment]
I _think_ @Jefffrey might already plan to pick this one up - https://github.com/apache/arrow-rs/pull/3209#discussion_r1033981345

**Comment by Jefffrey** [comment]
Feel free to go ahead and pick this one up, I'm in no rush to attempt this anyway @askoa
