### ISSUE TITLE
precision is not considered when cast value to decimal

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-rs#3223]
**Describe the bug**

If the `CastOptions {safe: true}` and cast INT32(120) to decimal(3,1), the result should be `None`, but 
we get the result of `decimal(Some(1200),3,1)`

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by liukun4515** [comment]
Do you have any thoughts about this? cc @tustvold @viirya

**Comment by tustvold** [comment]
I thought we had agreed to only care about overflow of the underlying type, and leave it to users to validate decimals if they care about precision. Provided we aren't overflowing and losing data, I'm not sure why we would validate precision at all?

**Comment by liukun4515** [comment]
> I thought we had agreed to only care about overflow of the underlying type, and leave it to users to validate decimals if 
they care about precision. Provided we aren't overflowing and losing data, I'm not sure why we would validate precision at all?

Now arrow-rs has the API of `pub fn validate_decimal_precision(&self, precision: u8) -> Result<(), ArrowError> ` to check the precision for the decimal array.
I think we need a method to do the above requirements, if the value is overflow the precision, and it should be converted to None.
Maybe we should provide the api to change the `null_bit_map` in the DecimalArray, If user want to validate precision to get `None` or `Error`.

@tustvold

**Comment by tustvold** [comment]
Adding a `null_if_overflowed_precision` method makes sense to me

**Comment by viirya** [comment]
Currently we did as @tustvold mentioned. We validate decimals by `validate_decimal_precision` after casting and put nulls for overflowing slots in an array.

I think it is trivial to do by users. Okay for me if you want to add something like `null_if_overflowed_precision` to do that.

**Comment by liukun4515** [comment]
@viirya @tustvold  thanks for your advice.
In the user case, some cases want to get the error when the data is overflow for the precision, and some cases don't want to get the error instead of the None for the overflowed slot in the array.
