### ISSUE TITLE
Release `object_store` `0.5.2` (next release after`0.5.1`)

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#3229]
Follow on from https://github.com/apache/arrow-rs/issues/2845

* Planned Release Candidate: 2022-12-02
* Planned Release and Publish to crates.io: 2022-12-5

Items:
- [x] Update changelog and readme: https://github.com/apache/arrow-rs/pull/3253
- [x] Create release candidate: https://lists.apache.org/thread/401vvbspv689jo7d5yx9bojsvk9y6g6q
- [x] Release candidate approved: https://lists.apache.org/thread/kypwh29y90vr44xsfllc0qhskgho0rqo
- [x] Release to crates.io: https://crates.io/crates/object_store/0.5.2

**Comment by tustvold** [comment]
I think it should be a patch release, I don't recall merging anything breaking

**Comment by alamb** [comment]
It looks like there are a few PRs that would be good to get into this release; https://github.com/apache/arrow-rs/pulls?q=is%3Apr+is%3Aopen+label%3Aobject-store 

https://github.com/apache/arrow-rs/pull/3252 and https://github.com/apache/arrow-rs/pull/3236 specifically

Thus I plan to prepare a PR with version update but delay creating a release candidate until they are in

**Comment by alamb** [comment]
I am beginning to create the RC

**Comment by alamb** [comment]
The release candidate is ready and voting has begun: https://lists.apache.org/thread/401vvbspv689jo7d5yx9bojsvk9y6g6q

**Comment by alamb** [comment]
The release candidate was approved and it is available on crates.io

https://lists.apache.org/thread/kypwh29y90vr44xsfllc0qhskgho0rqo

🎉

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#3229](https://github.com/apache/arrow-rs/issues/3229)
