### ISSUE TITLE
object_store(gcp): GCP complains about content-length for copy

### ISSUE THREAD

**Issue by wjones127** [apache/arrow-rs#3235]
**Describe the bug**

An error in the GCP `copy_if_not_exist` was reported upstream in delta-rs: https://github.com/delta-io/delta-rs/issues/878#issue-1404449207

```
PyDeltaTableError: Failed to read delta log object: Generic GCS error: Error performing copy request 
Error 411 (Length Required)
```

I haven't been able to reproduce this yet, but seems like it couldn't hurt to put `Content-Length: 0` in the request.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'object-store'} from #3236
