### ISSUE TITLE
Enable casting between Dictionary of DecimalArray and DecimalArray

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#3237]
**Describe the bug**

`can_cast_types` returns true for casting between Dictionary of DecimalArray and DecimalArray, but actually cast kernel doesn't cast them. We should enable it.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3238
