### ISSUE TITLE
using ahash `compile-time-rng` kills reproducible builds

### ISSUE THREAD

**Issue by Fuuzetsu** [apache/arrow-rs#3271]
**Describe the bug**
In https://github.com/apache/arrow-rs/commit/f812d2cda1379933fca22d9979e3df5be19792fa, `ahash` feature `compile-time-rng` was enabled. This causes builds to _not_ be reproducible. If you now build anything with `ahash` in the tree multiple times, it's going to give different results a lot of the time. This completely kills any systems that cache builds and such.

**To Reproduce**
Build `parquet-rs` few times and compare outputs.

**Expected behavior**
Outputs should be the same each time.

**Additional context**
It seems it was added strictly for WASM so it's a big shame that it impacts every other platform too, if it's actually necessary.

You can see some previous precedent in people having this exact problem with the feature here: https://github.com/rust-lang/hashbrown/issues/149

**Comment by Fuuzetsu** [comment]
We will set CONST_RANDOM_SEED in our builds for now but would be good to not have to do this...

https://crates.io/crates/const-random

**Comment by Fuuzetsu** [comment]
> We will set CONST_RANDOM_SEED in our builds for now but would be good to not have to do this...
> 
> https://crates.io/crates/const-random

Actually, we patched the relevant crate to hardcode the seed instead of faffing around with it...

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #3277
