### ISSUE TITLE
Add HttpStore

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#3294]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Systems like DataFusion would like to be able to query data stored in arbitrary HTTP servers. These necessarily cannot support the full suite of functionality, but the following should be possible:

* get
* head
* get_range
* delete

Things that would not be possible to support

* list
* list_with_delimiter
* rename
* copy

**Describe the solution you'd like**

An `HTTPStore` that supports the limited subset above, using the existing client plumbing used by the cloud object stores

**Describe alternatives you've considered**

We could potentially extend the scope of this to support the [WebDAV](https://en.wikipedia.org/wiki/WebDAV) specification which would allow for the remaining operations

**Additional context**

**Comment by poelzi** [comment]
That would be awesome for storing files in owncloud (webdav)

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'object-store'} from #3380

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#3294](https://github.com/apache/arrow-rs/issues/3294)
