### ISSUE TITLE
Reduce Duplication in Like Kernels

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#3296]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The like kernels contain a significant amount of copy-pasted code with very minor modifications for the various like, ilike, nlike, nilike variants. It would be good to reduce this

**Describe the solution you'd like**

The existing `like_scalar_op` should allow for significant reduction in the code duplication

**Describe alternatives you've considered**

**Additional context**

**Comment by askoa** [comment]
I can pick up some of these.

**Comment by tustvold** [comment]
That would be awesome, thank you :+1:

**Comment by Dandandan** [comment]
Good idea 👍. I remember those kernels were non-trivial to change before and are in need of some good cleanup.
