### ISSUE TITLE
Add support for content-type while uploading files through ObjectStore API

### ISSUE THREAD

**Issue by ByteBaker** [apache/arrow-rs#3300]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I use **ObjectStore** in a project that requires uploading files (mostly PDF) to AzureBlobStorage, and sometimes to S3. These files are later displayed on a web page using the ***<iframe>*** tag.

Since **object_store** doesn't support including **content-type** header with the file to be uploaded, it becomes a problem with AzureBlobStorage, which defaults the ***content-type*** to **application/octet-stream**. In such case, ***<iframe>*** downloads the file instead of displaying it. Also mentioned in [this StackOverflow question](https://stackoverflow.com/questions/50949201/iframe-downloads-the-html-source-instead-of-displaying-it).

**Describe the solution you'd like**

Have the ability to add a **content-type** header while uploading a file using **ObjectStore**.

**Describe alternatives you've considered**

I've written some code modifying the ObjectStore trait's method definition, adding an additional argument **content_type: Option<&str>**

```
pub async fn put_request<T: Serialize + crate::Debug + ?Sized + Sync>(
        &self,
        path: &Path,
        bytes: Option<Bytes>,
        is_block_op: bool,
        query: &T,
        content_type: Option<&str>,
    ) -> Result<Response> {
        let credential = self.get_credential().await?;
        let url = self.config.path_url(path);

        let mut builder = self.client.request(Method::PUT, url);

        if !is_block_op {
            builder = builder.header(&BLOB_TYPE, "BlockBlob").query(query);
        } else {
            builder = builder.query(query);
        }

        if let Some(ct) = content_type {
            builder = builder.header(&CONTENT_TYPE, ct);
        }

        if let Some(bytes) = bytes {
            builder = builder
                .header(CONTENT_LENGTH, HeaderValue::from(bytes.len()))
                .body(bytes)
        } else {
            builder = builder.header(CONTENT_LENGTH, HeaderValue::from_static("0"));
        }

        let response = builder
            .with_azure_authorization(&credential, &self.config.account)
            .send_retry(&self.config.retry_config)
            .await
            .context(PutRequestSnafu {
                path: path.as_ref(),
            })?;

        Ok(response)
    }
```

**Additional context**

This solution works very well for me, and I have it in my local setup. The problem I face is that I also use **delta-rs** crate, where I need to use **ObjectStore** as the backend. Therefore I cannot use my code, because it then says `trait not satisfied`.

**Comment by tustvold** [comment]
This is tricky, the aim of `ObjectStore` is to provide a common set of functionality across filesystems, memory, and object stores. Here the complication is filesystems don't have a concept of a MIME type, and so I don't think we can easily add this to the `ObjectStore` trait itself.

Perhaps we could add mime settings to [ClientOptions](https://docs.rs/object_store/latest/object_store/struct.ClientOptions.html)?

Perhaps something like

```
/// Set the default CONTENT_TYPE for uploads
fn with_default_mime_type(self, mime: impl Into<String>)

/// Set the CONTENT_TYPE for a given file extension
fn with_mime_type_for_suffix(self, mime: impl Into<String>, extension: impl Into<String>)
```

Would that work for your use-case?

**Comment by ByteBaker** [comment]
I think so, yes. Because the first problem I faced was the inability to make any changes to the HTTP client, since that's where one would add any header.

In the changes I've made, I was able to add it to the trait itself, but had to ignore the **content_type** argument for local file system by underscoring it. Even though it works without any problems, I'm afraid its presence will confuse users using local file system as the backend.

In such a case, should I write the code for the solution you've proposed above? I think it's rather straightforward with one question. 

What's the purpose of having both `mime` and `extension` in `fn with_content_type_for_suffix(self, mime: impl Into<String>, extension: impl Into<String>)`? I mean, couldn't we have a mime type for the given file type anyway?

**Comment by tustvold** [comment]
> should I write the code

If you would like to, I'd be happy to review it. Otherwise I can add this to my list

> What's the purpose of having both mime and extension in fn

Mainly to avoid having to bring in a dependency on a mime inference crate, and also to support non-standard file extensions.

So you'd be able to do something like

```
with_content_type_for_extension("myjson", "application/json")
```

**Comment by ByteBaker** [comment]
Sounds like a plan. I'll write the code and get back once I have something tangible ready.

**Comment by ByteBaker** [comment]
This may sound like a stupid question, but I can you tell me in which header should I keep the `extension`, and if it's supposed to be kept as an optional parameter in the content-type header after the forward slash? I'm not sure if I should keep it inside `content-disposition` either. This seems new to me.

In other words, would be nice if you explained the flow to me when it comes to handling the extension.

**Comment by tustvold** [comment]
> This may sound like a stupid question, but I can you tell me in which header should I keep the extension

I meant for the config to contain a HashMap from file extension to ContentType, on writing a file it would first lookup the extension in this HashMap, on match it would use the corresponding ContentType entry, otherwise it would use the default. Does that make sense?

**Comment by ByteBaker** [comment]
Yep, totally. Correct me if I've misunderstood.

The extension is the key to get the corresponding `content-type` (e.g. `application/json` if extension is `json`) already stored in a HashMap. The `content-type` argument is the default value if that fails. And I can populate the said HashMap from something like [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types).

**Comment by ByteBaker** [comment]
I see. This explaination is so much better. Thanks.

**Comment by ByteBaker** [comment]
I've committed the solution. Though this still won't work for GCP. The reason for this is the fact that calling `build()` on any of the cloud provider's builder `e.g., MicrosoftAzureBuilder::default().build()` generates the underlying client for that provider by calling `.client()` on `ClientOptions` (default or user provided).

This client obviously cannot handle our requirement above, and therefore the content type must be handled within the implementation of `put()`. And we need to be able to access `ClientOptions` for that to be possible.

While the upload object for Azure and AWS still contain the underlying `ClientOptions` when we call `build()` on their builders, GCP does not. Therefore I couldn't handle it now. Also couldn't think of a way to achieve it without changing any of the original `struct`s.

**Comment by tustvold** [comment]
Feel free to change the GCP implementation as required, none of those details are public and can therefore be changed without issue

**Comment by ByteBaker** [comment]
I've made the necessary changes in the PR, including the test cases for `filename()` and `extension()`. Please take a look and let me know if everything looks correct.

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'object-store'} from #3358

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#3300](https://github.com/apache/arrow-rs/issues/3300)
