### ISSUE TITLE
Coverage is Failing on Master

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#3302]
**Describe the bug**

Coverage is failing on master with

```
Error: "Failed to get test coverage! Error: Failed to run tests: Error: Timed out waiting for test response"
```

https://github.com/apache/arrow-rs/actions/runs/3651786788/jobs/6169412108
https://github.com/apache/arrow-rs/actions/runs/3650327783/jobs/6166169908

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
I think this is a symptom of something more serious: https://github.com/apache/arrow-rs/issues/3318

**Comment by alamb** [comment]
Likely fixed by https://github.com/apache/arrow-rs/pull/3319

**Comment by tustvold** [comment]
This appears to now be fixed
