### ISSUE TITLE
Binary Arity Kernels Don't Preserve DataType

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#3307]
**Describe the bug**

Adding together two primitive arrays with non-default precision/scale, produces an array with the default precision/scale

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by tustvold** [comment]
This is complicated by the fact the binary kernels allow a return type that differs from the input types... Not sure how best to handle this :thinking:

**Comment by alamb** [comment]
Is this ticket actionable? As in what is the expected behavior ?
