### ISSUE TITLE
[FlightSQL] Client Allow users to set arbitrary headers (rather than only the `"authorization"`)

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#3310]
Rather than hard coding a `token` what do you thunk about having a HeaderMap here so that whoever used this client could set whatever headers they wanted (rather than only the `"authorization"`)?

This could definitely be done as a follow on PR

_Originally posted by @alamb in https://github.com/apache/arrow-rs/pull/3207#discussion_r1039947123_

**Comment by alamb** [comment]
Thanks @yukkit

**Comment by yukkit** [comment]
@alamb  😊 I see this feature is already implemented in https://github.com/apache/arrow-rs/pull/3788

https://github.com/apache/arrow-rs/blob/7bac07aa41e75286d8bb7995be311731b7d07688/arrow-flight/src/sql/client.rs#L97

**Comment by alamb** [comment]
Thanks @yukkit 👍
