### ISSUE TITLE
ILIKE Kernels Inconsistent Case Folding

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#3311]
**Describe the bug**

The regex crate only implements the [simple loose matching](https://docs.rs/regex/latest/regex/#unicode) as defined by the [unicode standard](https://unicode.org/reports/tr18/#Simple_Loose_Matches).

In particular the `ﬀ` ligature will not be considered to be case insensitive equal to `ff`, `Ff`, etc... `ß` will not be considered as a lower-case of `SS`, etc...

However, the Rust standard library function `to_uppercase()` implements the full unicode conversion specification. Consequently there is a mismatch in the semantics between the ilike kernels with short-circuit implementations (i.e. starts_with) and the regex versions.

**To Reproduce**

```
test_utf8_scalar!(
    test_utf8_array_ilike_unicode_ends,
    test_utf8_array_ilike_unicode_ends_dyn,
    vec![
        "sdlkdfFFooß",
        "sdlkdfFFooSS",
        "sdlkdfFFooss",
        "FFooS",
        "FFoos",
        "ﬀooSS",
        "ﬀooß"
    ],
    "%FFooSS",
    ilike_utf8_scalar,
    ilike_utf8_scalar_dyn,
    vec![true, true, true, false, false, true, true]
);

test_utf8_scalar!(
    test_utf8_array_ilike_unicode_contains,
    test_utf8_array_ilike_unicode_contains_dyn,
    vec![
        "sdlkdfFooßsdfs",
        "sdlkdfFooSSdggs",
        "sdlkdfFoosssdsd",
        "FooS",
        "Foos",
        "ﬀooSS",
        "ﬀooß"
    ],
    "%FFooSS%",
    ilike_utf8_scalar,
    ilike_utf8_scalar_dyn,
    vec![true, true, true, false, false, true, true]
);

test_utf8_scalar!(
    test_utf8_array_ilike_unicode_complex,
    test_utf8_array_ilike_unicode_complex_dyn,
    vec![
        "sdlkdfFooßsdfs",
        "sdlkdfFooSSdggs",
        "sdlkdfFoosssdsd",
        "FooS",
        "Foos",
        "ﬀooSS",
        "ﬀooß"
    ],
    "%FF__SS%",
    ilike_utf8_scalar,
    ilike_utf8_scalar_dyn,
    vec![true, true, true, false, false, true, true]
);
```

**Expected behavior**

DuckDB at least appears to only handle the simple conversion as well

```
>>> duckdb.query("Select 'ﬀooß' ILIKE 'ffooss'").fetchall()
[(False,)]
>>> duckdb.query("Select 'FFooß' ILIKE 'ffooss'").fetchall()
[(False,)]
>>> duckdb.query("Select 'FFooSS' ILIKE 'ffooss'").fetchall()
[(True,)]
```

We should handle this consistently

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3306
