### ISSUE TITLE
Document / Deprecate arrow_flight::utils::flight_data_from_arrow_batch

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-rs#3312]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Something I discovered while working on code base at Coralogix and in Ballista.
`arrow_flight::utils::flight_data_from_arrow_batch` is used as method to convert a single`RecordBatch` to `FlightData`.
This method extracts both the dictionaries as the `RecordBatches`.
While convenient, if the dictionary is the shared across batches, the caller will probably send the `FlightData` for these dictionaries over and over again over in the stream.

**Describe the solution you'd like**

Mark the method as deprecated to encourage users to use the `IpcDataGenerator` API instead.

https://docs.rs/arrow-ipc/28.0.0/arrow_ipc/writer/struct.IpcDataGenerator.html

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
🤔  looks like we use `flight_data_from_arrow_batch` in IOx as well

https://github.com/influxdata/influxdb_iox/blob/061d582a9b4ca1493a875acd4d27ad5850a61659/service_grpc_flight/src/lib.rs#L423

**Comment by alamb** [comment]
It looks like the comments around https://docs.rs/arrow-ipc/28.0.0/arrow_ipc/writer/struct.IpcDataGenerator.html are non existent so some description there as well as some examples would also likely help

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3353

**Comment by Frankonly** [comment]
What should we use to replace `flight_data_from_arrow_batch` ?
