### ISSUE TITLE
Pretty print not implemented for Map

### ISSUE THREAD

**Issue by andrei-ionescu** [apache/arrow-rs#3322]
**Describe the bug**

The pretty print implementation for Map is missing.

```
Error: ArrowError(InvalidArgumentError("Pretty printing not implemented for Map(Field { name: \"map\", data_type: Struct([Field { name: \"key\", data_type: Utf8, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \"value\", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }]), nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, false) type"))
```

**To Reproduce**
```
let df = ctx.read_parquet(glob_path, ParquetReadOptions::default()).await?;
df.show().await?
```

**Expected behavior**
To print either the map's content or a hash representation of that map.

**Additional context**
This is in the context of using DataFusion and loading some parquet files containing Maps.

The code that does the pretty print is here: https://github.com/apache/arrow-rs/blob/master/arrow-cast/src/display.rs

**Comment by tustvold** [comment]
This should be relatively straightforward, I believe a row should be rendered as

```
{"key": "value", "key2": "value"}
```

i.e. flattening the list part.

The first version can probably use `array_value_to_string`, whilst very slow, we can always optimise it later

**Comment by askoa** [comment]
I'll give this a try.

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3339
