### ISSUE TITLE
Add a constant prefix object store wrapper

### ISSUE THREAD

**Issue by roeap** [apache/arrow-rs#3328]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

In certain situations is useful or convenient to have a constant prefix applied to all paths handled by an `ObjectStore`. Examples might be to simplify paths handling or to avoid illegal operations - e.g. listing the root when only permissions are available on some directory in an ADLS Gen2 storage account. 

The C++ implementation provides an equivalent concept via the [`SubTreeFilesSytem`](https://arrow.apache.org/docs/python/generated/pyarrow.fs.SubTreeFileSystem.html#pyarrow.fs.SubTreeFileSystem).

**Describe the solution you'd like**

A an `ObjectStore` implementation that applies / strips a prefix to all paths exposed in the ObjectStore apis. 

**Describe alternatives you've considered**

Letting consumers handle this.

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'object-store'} from #3329

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#3328](https://github.com/apache/arrow-rs/issues/3328)
