### ISSUE TITLE
Decimal arithmetic computation fails to run because decimal type equality

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#3344]
**Describe the bug**

The functions like `unary_dyn` fails to compute if it finds inequality between array type and operation operand type:

For decimal types, just precision/scale can also fail the type equality. Because decimal types have default precision and scale, such check makes no sense for decimal types:

```
NotYetImplemented("Cannot perform unary operation of type Decimal128(38, 10) on array of type Decim
al128(38, 2)")'
```

This makes scalar arithmetic kernels cannot work on decimal types mostly.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3345
