### ISSUE TITLE
CSV Reader Bounds Incorrectly Handles Header

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#3364]
**Describe the bug**

The following table illustrates the current behaviour

|range|has_header|num_rows
|---|---|---|
|0..4|false|4|
|0..4|true|3|
|1..4|false|3|
|1..4|true|2|

The first two could be justified if the start offset included the header, but this is inconsistent with the two subsequent results

**To Reproduce**

```
#[test]
    fn test_header_bounds() {
        let csv = "a,b\na,b\na,b\na,b\na,b\n";
        let tests = [
            (None, false, 5),
            (None, true, 4),
            (Some((0, 4)), false, 4),
            (Some((1, 4)), false, 3),
            (Some((0, 4)), true, 4),
            (Some((1, 4)), true, 3),
        ];

        for (bounds, has_header, expected) in tests {
            let mut reader = ReaderBuilder::new().has_header(has_header);
            if let Some((start, end)) = bounds {
                reader = reader.with_bounds(start, end);
            }
            let b = reader
                .build(Cursor::new(csv.as_bytes()))
                .unwrap()
                .next()
                .unwrap()
                .unwrap();
            assert_eq!(b.num_rows(), expected);
        }
    }
```

**Expected behavior**

The bounds shouldn't include the header, i.e. an offset of 1 will return the 2nd row of data irrespective of the presence or not of a header.

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3365
