### ISSUE TITLE
Speed up TrackedWrite

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#3366]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

As `TrackedWrite` is used for writing Parquet files, we can speed it up by adding BufWriter into TrackedWrite.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #3361
