### ISSUE TITLE
object_store(aws): percent encoding test fails with latest localstack

### ISSUE THREAD

**Issue by wjones127** [apache/arrow-rs#3379]
**Describe the bug**

When testing with the latest localstack (1.0 and onward), we get this failure from S3 tests:

```
---- aws::tests::s3_test stdout ----
thread 'aws::tests::s3_test' panicked at 'assertion failed: `(left == right)`
  left: `[Path { raw: "a/b/c/foo.file" }]`,
 right: `[Path { raw: "a/b%2Fc/foo.file" }]`', object_store/src/lib.rs:638:9


failures:
    aws::credential::tests::test_instance_metadata
    aws::tests::s3_test
```

Not sure yet if this is a bug in localstack, or our implementation.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by wjones127** [comment]
This is an issue upstream: https://github.com/localstack/localstack/issues/7374

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#3379](https://github.com/apache/arrow-rs/issues/3379)
