### ISSUE TITLE
Add derived implementations of Clone and Debug for `ParquetObjectReader`

### ISSUE THREAD

**Issue by kszlim** [apache/arrow-rs#3381]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I'm trying to create an infinite stream that samples from a parquet file endlessly, it's handy being able to clone `ParquetObjectReader`, having a `Debug` implementation also seems nice to have.

**Describe the solution you'd like**
Implement Clone and Debug for `ParquetObjectReader`

**Describe alternatives you've considered**
None, as this seems purely additive as cost free (except maybe a very slight compile time increase)

**Additional context**
n/a

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #3382
