### ISSUE TITLE
Only flush buffered multi-part data on poll_shutdown not on poll_flush

### ISSUE THREAD

**Issue by liningpan** [apache/arrow-rs#3390]
**Describe the bug**
Although the multipart writer implements AsyncWrite, it is incompatible with the utility [`tokio::io::copy`](https://docs.rs/tokio/latest/tokio/io/fn.copy.html) function in tokio. 

The reason seems to be the copy function in tokio polls flush frequently (https://docs.rs/tokio/1.23.0/src/tokio/io/util/copy.rs.html#99). However, in this case, each call to flush will cause `put_multipart_part` request to be sent.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by tustvold** [comment]
> each call to flush will cause put_multipart_part request to be sent.

What would you expect to happen?

**Comment by liningpan** [comment]
I would expect flush to only poll existing upload tasks, and shutdown to send remaining data first.

On Dec 26, 2022, at 6:09 AM, Raphael Taylor-Davies ***@***.***> wrote:

﻿

each call to flush will cause put_multipart_part request to be sent.

What would you expect to happen?

**Comment by tustvold** [comment]
That would diverge from a strict interpretation of the trait method which states

> Attempts to flush the object, ensuring that any buffered data reach their destination.

But perhaps that is ok, certainly given that some stores have minimum payload sizes it would make sense that poll_shutdown is the only one that triggers the "final" flush. I would be happy to review a PR that changed this behaviour

**Comment by askoa** [comment]
I can pick this up.

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#3390](https://github.com/apache/arrow-rs/issues/3390)
