### ISSUE TITLE
ArrayData`get_slice_memory_size`   or similar

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#3407]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

As part of implementing an Arrow flight client, we have observed that there is a maximum message size for gRPC messages, and thus while encoding the Arrow flight client has a way to limit the size of the messages (see https://github.com/apache/arrow-rs/pull/3391)

However, apparently there is currently no way to get the memory size used by a sliced (aka the array only points to a portion of the overall underlying allocation), which will result in overly conservative re-splitting in the arrow-flight client 

**Describe the solution you'd like**
As suggested by @tustvold  on https://github.com/apache/arrow-rs/pull/3391#discussion_r1058288317

> It is worth noting that this method does not take into account already sliced arrays, we likely need to add a `get_slice_memory_size` or something to `ArrayData` to provide this, it should be relatively straightforward

**Describe alternatives you've considered**
We could leave the users of the client to worry about batch splitting

**Additional context**

**Comment by alamb** [comment]
Thank you @askoa

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3501

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow-flight'} from #3391
