### ISSUE TITLE
Release `object_store` `0.5.3` (next release after`0.5.2`)

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#3422]
Follow on from https://github.com/apache/arrow-rs/issues/3229

* Planned Release Candidate: ~TBD~ 2023-01-05
* Planned Release and Publish to crates.io: ~TBD~ 2023-01-08

Items:
- [ ] Update changelog and readme:  
- [ ] Create release candidate:  
- [ ] Release candidate approved: 
- [ ] Release to crates.io:

**Comment by alamb** [comment]
cc @tustvold -- any thoughts on other features we would want to get in?

**Comment by tustvold** [comment]
I'm not aware of anything outstanding, it's probably about time to make a release 👍

**Comment by alamb** [comment]
unless I hear otherwise I'll plan to cut a release later this week / weekend and release next week

**Comment by tustvold** [comment]
Changelog in https://github.com/apache/arrow-rs/pull/3457

**Comment by tustvold** [comment]
Release thread - https://lists.apache.org/thread/01p1zbpfblw91137oh3hsc9379oczg8t

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#3422](https://github.com/apache/arrow-rs/issues/3422)
