### ISSUE TITLE
Add string comparisons (starts_with, ends_with, and contains) to kernel

### ISSUE THREAD

**Issue by snmvaughan** [apache/arrow-rs#3442]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
The implementation for `like` checks for specific fast paths in order to avoid using a regex, but direct usage of those string comparisons aren't directly available.

**Describe the solution you'd like**
Implement `starts_with`, `ends_with`, and `contains` so that they can be accessed directly.  As an example, there would be an equivalent to `like_dyn` called `starts_with_dyn`, an equivalent to `like_utf8` called `starts_with_utf8`, etc.

**Describe alternatives you've considered**
Clients could use the existing `like` kernel, but this would introduce unnecessary fast path checks.

**Additional context**
Expression optimizers can automatically determine the fast path optimization and avoid using `like`.  As an example a sql statement that references `where name like 'Arro%'` could optimize the filter to `where StartsWith(name, 'Arro')`

**Comment by tustvold** [comment]
Adding explicit scalar kernels of this form makes a lot of sense to me :+1:

Less sure about the utility of a non-scalar version

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3502
