### ISSUE TITLE
object_store: temporary aws credentials not refreshed?

### ISSUE THREAD

**Issue by declark1** [apache/arrow-rs#3446]
I'm using AmazonS3Builder::from_env() to create an AmazonS3 object store in my service, which uses the WebIdentity credential provider. The service runs in Kubernetes and temporary service account credentials are injected into the pods via IAM Roles for Service Accounts (IRSA). It appears that the credentials are not refreshed automatically before expiration. Is there any way to have it do this? I'm hoping to avoid creating a new client for each request. I don't see a way to configure this with the AmazonS3Builder.

**Comment by tustvold** [comment]
I believe this was fixed in https://github.com/apache/arrow-rs/pull/3274 which is due to be released soon. In the short term you could consider using a git patch

**Comment by declark1** [comment]
Thanks! I will git patch for now.

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#3446](https://github.com/apache/arrow-rs/issues/3446)
