### ISSUE TITLE
`nullif` kernel no longer exported

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#3454]
**Describe the bug**
The nullif kernel accidentally got lost in  https://github.com/apache/arrow-rs/pull/3384 and thus is not callable anymore. 

**To Reproduce**
Try to call nullif

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
Fixed in https://github.com/apache/arrow-rs/pull/3451 by @tustvold

**Comment by tustvold** [comment]
Well it is not callable through the arrow top-level crate, it is callable by depending on arrow-select
