### ISSUE TITLE
Release Arrow `30.0.1` (maintenance release for `30.0.0`)

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#3455]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
We recently released arrow 30.0.0: https://github.com/apache/arrow-rs/issues/3336 and found two issues:

- [ ] The upgrade to multiversion https://github.com/apache/arrow-rs/pull/3396 means now all crates that use arrow-rs require rebuild on every compilation (see https://github.com/calebzulawski/target-features/issues/1)
- [x] https://github.com/apache/arrow-rs/issues/3454

**Describe the solution you'd like**
A new release version 30.0.1 with just the fixes for:
- [ ] https://github.com/apache/arrow-rs/pull/3452
- [ ] https://github.com/apache/arrow-rs/pull/3451

**Describe alternatives you've considered**
* Possibly release `30.1.0` (need dependency)?
* Just wait until the release of 31.0.0 #3415 

**Additional context**
Found while trying to update datafusion. This may block the upgrade and possibly delay the release https://github.com/apache/arrow-datafusion/issues/4776 cc @andygrove

**Comment by tustvold** [comment]
Release thread - https://lists.apache.org/thread/p5dqfopymxw0or7hqh1tl5npcj4338qw

**Comment by iajoiner** [comment]
Shall this be closed since the release has already taken place?
