### ISSUE TITLE
Allow `concat_batches` to take non owned RecordBatch

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#3456]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We have code that has `Vec<&RecordBatch>` (not `Vec<RecordBatch>`) and thus we can't call `concat_batches` as that requires taking ownership. I looked at the code for `concat_batches` and it is not at all clear why it needs ownership of the RecordBatch

https://docs.rs/arrow/30.0.0/arrow/compute/fn.concat_batches.html

**Describe the solution you'd like**
I would like some way to call `concat_batches` that doesn't require an bunch of owned RecordBatches

Perhaps something like this would work:

```rust
pub fn concat_batches(
    schema: &Arc<Schema>,
    batches: impl IntoIter<Item = &RecordBatch>
) -> Result<RecordBatch, ArrowError>
```

And existing callers could call concat_batches(&batches)

**Describe alternatives you've considered**

**Additional context**
in a DataFusion PR: https://github.com/apache/arrow-datafusion/pull/4777#discussion_r1060646358

**Comment by alamb** [comment]
I think collecting references into a Vec<&RecordBatch> seems like a very reasonable step to me

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3480
