### ISSUE TITLE
arrow-csv: support decimal256

### ISSUE THREAD

**Issue by 0xYUANTI** [apache/arrow-rs#3474]
I noticed that

https://github.com/apache/arrow-rs/blob/master/arrow-csv/src/reader/mod.rs

only seems to support decimal128 (ended up there via an error message from csv2arrow).
Is there a reason for that? If not, would be amazing if someone could implement support.
Decimal256 is pretty important since its the only way to represent bigints (well big-ish ints) in arrow afaict.

**Comment by LiShiZhensPi** [comment]
hi, Is this still valid？ and I'm happy to contribute to this project.  I'd like to try to fix issue. But no worries if a more experienced contributor wants to take over this issue instead 😀

**Comment by LiShiZhensPi** [comment]
I took a look at the code and found that these functions only support the i128 type：
- [build_decimal_array](https://github.com/apache/arrow-rs/blob/master/arrow-csv/src/reader/mod.rs#L784) 
- [parse_decimal_with_parameter](https://github.com/apache/arrow-rs/blob/master/arrow-csv/src/reader/mod.rs#L819)

It doesn't seem very hard to support i256, I will be submitting a change soon.

**Comment by viirya** [comment]
Thank you @LiShiZhensPi. Usually if an issue is not assigned yet and no others have said they will work on it, it should be open for all contributors to work on. Feel free to take it.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3711
