### ISSUE TITLE
CLI to "rewrite" parquet files

### ISSUE THREAD

**Issue by crepererum** [apache/arrow-rs#3476]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Sometimes I wonder what different settings (compression, row group size, page size, ...) do to a parquet file (in terms of size, number of row groups / pages, performance).

**Describe the solution you'd like**
Have a CLI that takes a parquet file and writes it again w/ different settings. The resulting file can then be inspected by our other CLI tools like [`parquet-layout`](https://github.com/apache/arrow-rs/blob/master/parquet/src/bin/parquet-layout.rs).

**Describe alternatives you've considered**
Always require user code to perform these kind of experiments.

**Additional context**
\-

**Comment by crepererum** [comment]
I'm working on this.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #3477
