### ISSUE TITLE
Use `array_value_to_string` in `arrow-csv` 

### ISSUE THREAD

**Issue by JayjeetAtGithub** [apache/arrow-rs#3483]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Standardize `arrow-csv` writer by using `array_value_to_string` from `arrow-cast`  while writing out record batches to CSV files similar to `arrow-json` (See https://github.com/apache/arrow-rs/pull/3449).

**Comment by JayjeetAtGithub** [comment]
@alamb @tustvold Continuing the discussion from apache/arrow-rs#3417, currently the `arrow-csv` writer allows users to pass custom datetime formats besides the defaults. By using `array_value_to_string`, we would enforce the format and disable the customization. Otherwise, if we still want customization, we can keep both, where we basically fallback to using `array_value_to_string` when no custom format is supplied by the user. Looking forward to hearing your thoughts on this. Thanks.

**Comment by alamb** [comment]
I filed https://github.com/apache/arrow-rs/issues/3513 to describe the end user behavior this would produce

**Comment by JayjeetAtGithub** [comment]
> @alamb @tustvold Continuing the discussion from https://github.com/apache/arrow-rs/pull/3417, currently the arrow-csv writer allows users to pass custom datetime formats besides the defaults. By using array_value_to_string, we would enforce the format and disable the customization. Otherwise, if we still want customization, we can keep both, where we basically fallback to using array_value_to_string when no custom format is supplied by the user. Looking forward to hearing your thoughts on this. Thanks.

I opened #3514 where I removed datetime format customization support for now and use the format enforced by `array_value_to_string`.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3514
