### ISSUE TITLE
Allow providing service account key directly when building GCP object store client

### ISSUE THREAD

**Issue by scsmithr** [apache/arrow-rs#3488]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The current implementation of the GCP builder requires that the service account key is read in from a file. For our use case, we're storing the service account key external to where the object store client is being created. We do not want to have to write the key to a file before constructing the client.

**Describe the solution you'd like**

Allow providing the service account key directly to the builder.

**Describe alternatives you've considered**

For what we're building, we _could_ write the key to a file before constructing the client, but that would lead to some code complexity that we believe should be avoided.

**Additional context**

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#3488](https://github.com/apache/arrow-rs/issues/3488)
