### ISSUE TITLE
Support casting strings like `'2001-01-01'` to timestamp

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#3492]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We are trying to use `'2001-01-01'` as a timestamp (as an argument to the `date_bin` function in DataFusion).

However, we get the following error

```
Arrow error: Cast error: Error parsing '2001-01-01' as timestamp
```

As a workaround we can add `00:00:00` to the end and that works:

`'2001-01-01 00:00:00'` 

**Describe the solution you'd like**
I would like `'2001-01-01'` to be parsed the same as `'2001-01-01 00:00:00'` 

**Describe alternatives you've considered**
I can special case this downstream in datafusion

**Additional context**
I believe this can be achieved by adding the appropriate support to `string_to_timestamp_nanos` and adding a few tests

https://github.com/apache/arrow-rs/blob/c74665808439cb7020fb1cfb74b376a136c73259/arrow-cast/src/parse.rs#L23-L71

**Comment by alamb** [comment]
Marking this as a good first issue as I think the ask is clear and the code/tests straightforward and would be a good chance for someone to help out

**Comment by csphile** [comment]
Would like to investigate into this, could someone assign it to me?

**Comment by alamb** [comment]
Thanks @csphile ❤️  -- I can't explicitly assign the ticket to you because of how github permissions are setup on this project, but your comment is enough to tell others you are doing so !

**Comment by prajjawal05** [comment]
Apologies @csphile , I did not see your comment here. Please go ahead, I have closed my PR for now.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3494
