### ISSUE TITLE
Support casting  Date32 to timestamp

### ISSUE THREAD

**Issue by comphead** [apache/arrow-rs#3504]
**Describe the bug**

Related to https://github.com/apache/arrow-datafusion/issues/4644
Postgresql and datafusion support to cast date32 to timestamp, however its not yet covered by arrow-rs

**To Reproduce**

```
    #[test]
    fn test_cast_date32_to_timestamp() {
        let a = Date32Array::from(vec![10000, 17890]);
        let array = Arc::new(a) as ArrayRef;
        let b = cast(&array, &DataType::Timestamp(TimeUnit::Nanosecond, None)).unwrap();
        let c = b.as_any().downcast_ref::<TimestampNanosecondArray>().unwrap();
    }

thread 'cast::tests::test_cast_date32_to_timestamp' panicked at 'called `Result::unwrap()` on an `Err` value: CastError("Casting from Date32 to Timestamp(Nanosecond, None) not supported")', arrow-cast/src/cast.rs:7701:80
```

**Expected behavior**
Cast should work
**Additional context**

**Comment by comphead** [comment]
Please assign this to me

**Comment by alamb** [comment]
I changed this to to be a new feature rather than a bug (lol -- though I can see how a lack of functionality could be considered a bug)
