### ISSUE TITLE
Implement workload identity and application default credentials for GCP object store.

### ISSUE THREAD

**Issue by winding-lines** [apache/arrow-rs#3533]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently the only authentication implemented for GCP is using service account tokens. Implement the workload identity and application default credentials.

**Describe the solution you'd like**

An application using the `object_store` crate should be able to use the additional credential mechanisms.

**Describe alternatives you've considered**

**Additional context**

**Comment by winding-lines** [comment]
@tustvold this is the more specific issue we were talking about.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #3541

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#3533](https://github.com/apache/arrow-rs/issues/3533)
