### ISSUE TITLE
[question] - Provide description of feature Row record writer

### ISSUE THREAD

**Issue by ysriram** [apache/arrow-rs#3535]
**Which part is this question about**
[README.md](https://github.com/apache/arrow-rs/blob/master/parquet/README.md)

**Describe your question**
In writer support section there is "Row record writer" feature. What does this feature mean ? A detail description with example would be helpful.

**Additional context**
None

**Comment by tustvold** [comment]
I don't believe a row writer abstraction exists (the box isn't checked), we only provide a [record / row-oriented API](https://docs.rs/parquet/latest/parquet/record/index.html) for reading
