### ISSUE TITLE
Arrow CSV writer should not fail when cannot cast the value

### ISSUE THREAD

**Issue by comphead** [apache/arrow-rs#3547]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Original problem reported in https://github.com/apache/arrow-datafusion/issues/4947
Arrow writer uses `.unwrap()` on options and fails when cast is not succeeded
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/github.com-1ecc6299db9ec823/arrow-csv-30.0.1/src/writer.rs:262:18
```
**Describe the solution you'd like**
Investigate on better options
 - fail with meaningful error
 - return and display the error as part of output

**Describe alternatives you've considered**

**Additional context**

**Comment by comphead** [comment]
in old spark versions, if timestamp cast cannot be done then null returned that was really confusing, we should consider a runtime error if such invalid cast happened

**Comment by comphead** [comment]
@tustvold @alamb please assign this to me

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3570
