### ISSUE TITLE
[FlightSQL] Allow access to underlying FlightClient

### ISSUE THREAD

**Issue by amartins23** [apache/arrow-rs#3551]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

A FlightSQL server may implement custom actions beyond what is defined by the FlightSQL protocol. However, the current [FlightSQLServiceClient](https://docs.rs/arrow-flight/31.0.0/arrow_flight/sql/client/struct.FlightSqlServiceClient.html) does not expose the action commands (`do_actions`, `list_actions`) nor allow access to the underlying `FlightServiceClient`.

**Describe the solution you'd like**

The simplest solution is to expose the underlying client by making the [mut_client()](https://github.com/apache/arrow-rs/blob/14545a42ec09782ec0371c05c01d112e0ca37604/arrow-flight/src/sql/client.rs#L131) function `pub`. Perhaps a better approach would be to add a set of `inner`/`inner_mut` functions like [`FlightClient`](https://docs.rs/arrow-flight/31.0.0/arrow_flight/client/struct.FlightClient.html#method.inner) does.

Alternatively, add a `do_action` and `list_actions` methods that forward to the underlying client.

**Describe alternatives you've considered**

The current alternative is to maintain two client instances, a `FlightSQLServiceClient` and a `FlightClient` (or `FlightServiceClient`), to be able to send custom actions.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow-flight'} from #3556
