### ISSUE TITLE
Should we write a "arrow-rs" update blog post?

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#3565]
**Which part is this question about**

We often write DataFusion https://arrow.apache.org/blog/2023/01/19/datafusion-16.0.0/  updates as a way to help grow the community and awareness about arrow.

The main arrow release does the same: https://github.com/apache/arrow-site/pull/300

**Describe your question**
I wonder if it would be useful to write an update for "the state of the arrow-rs project"

There are all sorts of cool things to share: Bloom filters, smaller crates, parquet performance, arrow-flight, many more I probably am missing. 

Thoughts @viirya  / @tustvold  / @andygrove ?

**Comment by tustvold** [comment]
The last post was 6 months ago, lots to potentially cover since then - https://arrow.apache.org/blog/2022/06/16/rust-16.0.0/

**Comment by alamb** [comment]
Can someone take a shot at drafting a post (you can use the one in https://github.com/apache/arrow-site/blob/master/_posts/2022-06-16-rust-16.0.0.md as a template)? I would be very happy to help collaborate

**Comment by tustvold** [comment]
I plan to take a stab at this tomorrow

**Comment by viirya** [comment]
I can help on it too if necessary.

**Comment by tustvold** [comment]
I've put up a rough draft here - https://github.com/apache/arrow-site/pull/305

I have almost certainly missed some things, a lot has happened in the last 6 months :sweat_smile:. Any feedback / help is most appreciated.

**Comment by alamb** [comment]
https://github.com/apache/arrow-site/pull/305 is ready for a wider review I think
