### ISSUE TITLE
Change default branch name from master to main

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-rs#3569]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
For context: https://github.com/github/renaming

**Describe the solution you'd like**
Change default branch name from master to main

**Describe alternatives you've considered**

**Additional context**

**Comment by assignUser** [comment]
Duplicate of #2173  ;)

**Comment by Jefffrey** [comment]
Closed as duplicate
