### ISSUE TITLE
[object_store] support more identity based auth flows for azure

### ISSUE THREAD

**Issue by roeap** [apache/arrow-rs#3580]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

In production deployments within azure. identity based access to resources is often the preferred method of authorization. It would be great for the `object_store` crate to support a larger variety of identity based authorization flows, such as managed identities or federated workload identities.

**Describe the solution you'd like**
 object store should support  managed identities and federated workload identities for authorizing against storage accounts.

**Describe alternatives you've considered**
 not supporting it.

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #3581

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#3580](https://github.com/apache/arrow-rs/issues/3580)
