### ISSUE TITLE
The function `new_buffers` should return `Vec<Buffer>`

### ISSUE THREAD

**Issue by askoa** [apache/arrow-rs#3586]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

from @tustvold https://github.com/apache/arrow-rs/pull/3553#discussion_r1083468505

> We should probably clean up this method to return Vec<Buffer> to be consistent with what ArrayData expects

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
I plan to pick this one up

**Comment by Weijun-H** [comment]
> I plan to pick this one up

Could I try to complete this task?

**Comment by tustvold** [comment]
This will get modified as part of #1176 so I would hold off 😅
