### ISSUE TITLE
Nullif of NULL Predicate is not NULL

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#3589]
**Describe the bug**

SQL NULLIF returns `NULL` if the predicate evaluates to `NULL`.

i.e.

```
> SELECT NULLIF(NULL, 1)
NULL
```

Whereas the `nullif` kernel in arrow preserves the nullability of the input.

This appears to date from the initial implementation of this kernel in https://github.com/apache/arrow/pull/8688/files#diff-d3f27fc6d1b5bf9dcc0eec10fb37f9f13e9dcdf5f608b932d0e0c0151a06b91aR253 by @velvia 

**To Reproduce**

**Expected behavior**

I'm not really sure, I think it is surprising that we break SQL compatibility in this way, but we have been doing so for a while so I'm not sure if this is intentional or just nobody has noticed.

**Additional context**

**Comment by tustvold** [comment]
Looking at how this is typically used I realise the current logic is correct. In particular the common pattern is

```
let cond_array = eq_dyn(lhs, rhs)?;
// Now, invoke nullif on the result
let array = nullif(lhs, as_boolean_array(&cond_array)?)?;
```

In particular if `lhs` or `rhs` is null, `cond_array` will also be null.

The result should only be `null` if `lhs` is null, which is the case if `NULL` passed to `nullif` preserves the nullability of `lhs` in the event of `rhs` being null.

**Comment by alamb** [comment]
Posgres agrees:

```sql
postgres=# Select nullif(null, null);
 nullif 
--------
 
(1 row)

postgres=# Select nullif(null, 1)
postgres-# ;
 nullif 
--------
       
(1 row)

postgres=# Select nullif(1, null);
 nullif 
--------
      1
(1 row)
```

🤯
