### ISSUE TITLE
There should be a `From<Vec<Option<String>>>` impl for `GenericStringArray<OffsetSize>`

### ISSUE THREAD

**Issue by sinistersnare** [apache/arrow-rs#3599]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I have a `Vec<Option<String>>`, and I want it to be a `StringArray`. Right now the only relevant impls to do this are:

* `From<Vec<String>>`
* `From<Vec<&str>>`
* `From<Vec<Option<&str>>>`

[Relevant code here](https://github.com/apache/arrow-rs/blob/d938cd9bf621c9bf3c3bd9e33c4c0a5eb4060534/arrow-array/src/array/string_array.rs#L238)

So it seems reasonable for there to be an impl for `Option<String>`

**Describe the solution you'd like**

Adding this impl would allow me to do 

```rs
let my_string: String = ...;
let stringarray: ArrayRef = Arc::new(StringArray::from(vec![Some(my_string), None]));
```

**Additional context**

I'm happy to add this if yall are interested. Just wanted to write this out to see if it could be considered.

**Comment by tustvold** [comment]
Makes sense to me, would be happy to review a PR that implemented this.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3602
