### ISSUE TITLE
Specified version of helper function to cast binary to string

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#3623]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

**Describe the solution you'd like**

We can avoid re-encoding the offsets when not necessary in the helper function to cast from binary to string.

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3624
