### ISSUE TITLE
Next release of `object_store`?

### ISSUE THREAD

**Issue by winding-lines** [apache/arrow-rs#3626]
**Which part is this question about**

This is a question about the next release.

**Describe your question**

I am doing final testing on a Polars PR (https://github.com/pola-rs/polars/pull/6426) that uses the current GCP authentication changes. It would be cleaner if I depended on a released version of `object_store` instead of a git hash. Do you have an `object_store` release planned in the next week?

**Additional context**

**Comment by tustvold** [comment]
Will do

**Comment by tustvold** [comment]
Release thread - https://lists.apache.org/thread/41d0jy00dzn102bd48tsvf8bf0bqgwow

**Comment by winding-lines** [comment]
Thank you very much!
