### ISSUE TITLE
Improve error messge "batches[0] schema is different with argument schema"

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-rs#3628]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I am getting this error as part of distributed query execution in a research project:

```
Exception: Arrow error: Invalid argument error: batches[0] schema is different with argument schema.
```

This is not too helpful. If the error included some information about the schemas, or how they differ, it would be easier to track down.

**Describe the solution you'd like**

Include some context in the error message.

**Describe alternatives you've considered**

**Additional context**

**Comment by Veeupup** [comment]
hi, I would like to take this ~

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3637
