### ISSUE TITLE
Push limit down into ParquetRecordBatchStream

### ISSUE THREAD

**Issue by thinkharderdev** [apache/arrow-rs#3631]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently, `ParquetRecordBatchStream` can read only data pages required for a given `RowSelection` (if there is an `OffsetIndex`). If we can have limit on the number of rows we want to read there is not really a good way to push that down as an `ArrowPredicate` though 

**Describe the solution you'd like**

`ParquetRecordBatchStream` takes a `limit: Option<usize>` argument. If provided, after evaluating the `RowFilter` the resulting `RowSelection` is truncated to the provided limit (eg after selecting `limit` rows, skip everything else). Then for any remaining projected columns we only need to read enough data pages to satisfy the limit. 

**Describe alternatives you've considered**

Do nothing

**Additional context**

**Comment by thinkharderdev** [comment]
@tustvold

**Comment by tustvold** [comment]
Makes sense to me

**Comment by Ted-Jiang** [comment]
Yes, with `offset index` it may reduce some IO work. 👍

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#3631](https://github.com/apache/arrow-rs/issues/3631)
