### ISSUE TITLE
Panic when accessing RecordBatch from pyarrow

### ISSUE THREAD

**Issue by adriangb** [apache/arrow-rs#3646]
This was tricky to pinpoint but I think I've got a MRE, and I'm guessing the issue is in `PyArrowConvert`. See:
- Repo with code demonstrating that the issue exists when passing in data from Python but not when using pure Rust: https://github.com/adriangb/misc/tree/11c245a5850582c15ebd654e34847e04a0668f1e
- A CI run confirming this finding and with a bit of debug info: https://github.com/adriangb/misc/actions/runs/4067509464/jobs/7004939916

**Comment by tustvold** [comment]
I don't appear to have access to that repo

**Comment by adriangb** [comment]
Apologies just made it public

**Comment by tustvold** [comment]
I will add this to my list to look into, thank you for the report

**Comment by adriangb** [comment]
Thanks for fixing this so quickly!

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3675
