### ISSUE TITLE
object_store: support encoded path as input

### ISSUE THREAD

**Issue by jychen7** [apache/arrow-rs#3651]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
while passing an percentage encoded Path to object store, it re-encode before get object.
e.g.

S3
https://github.com/apache/arrow-rs/blob/2b9bbce44abbd93048c674f49c4eb0db72a0a1c8/object_store/src/aws/client.rs#L459

GCS
https://github.com/apache/arrow-rs/blob/2b9bbce44abbd93048c674f49c4eb0db72a0a1c8/object_store/src/gcp/mod.rs#L270

a workaround is to pass decoded path from upstream application, even though upstream already receive encoded path.

e.g. https://github.com/roapi/roapi/issues/98#issuecomment-1409869735

**Describe the solution you'd like**
ideally, path should just need encode once. One idea is to improve `Path` to include new attribute called 'percent_encoded'

https://github.com/apache/arrow-rs/blob/2b9bbce44abbd93048c674f49c4eb0db72a0a1c8/object_store/src/path/mod.rs#L135-L138

**Describe alternatives you've considered**
auto detect whether already percentage encode?

**Additional context**

**Comment by tustvold** [comment]
Have you tried using `Path::parse`, this shouldn't re-encode

**Comment by jychen7** [comment]
@tustvold yes, I have tried.

I understand that `Path::parse("blogs%20space.parquet")` will NOT re-encode, the result is `Path { raw: "blogs%20space.parquet" }`.

However, when client GET object, it will re-encode at L246 -> L211 -> L459 below
https://github.com/apache/arrow-rs/blob/2b9bbce44abbd93048c674f49c4eb0db72a0a1c8/object_store/src/aws/client.rs#L237-L246
https://github.com/apache/arrow-rs/blob/2b9bbce44abbd93048c674f49c4eb0db72a0a1c8/object_store/src/aws/client.rs#L209-L213
https://github.com/apache/arrow-rs/blob/2b9bbce44abbd93048c674f49c4eb0db72a0a1c8/object_store/src/aws/client.rs#L458-L460

I imagine L211 need to know whether input `Path` is already encoded, either via new attribute or auto detect

**Comment by tustvold** [comment]
> However, when client GET object, it will re-encode at L246 -> L211 -> L459 below

Yes, this is so that the path of the created object matches exactly the `Path` provided. So if you provide `blogs%20space.parquet` that is what will be created in object storage.

> Path::parse("blogs%20space.parquet")

What is percent encoding this input, if you call `Path::parse("blogs space.parquet")` everything should work?

**Comment by jychen7** [comment]
> if you call Path::parse("blogs space.parquet") everything should work?

yes, it work

> What is percent encoding this input
> Is it possible something is receiving a URL and not decoding it properly, and just handing off the raw path?

this is from ROAPI config, the user input can be already percent encoded. ROAPI currently decode it before passing to `object_store`. I am wondering whether `object_store` can support receiving encoded path, so from end to end, we don't need additional `decode -> encode`
More detail here: https://github.com/roapi/roapi/issues/98#issuecomment-1409869735

**Comment by tustvold** [comment]
> can support receiving encoded path

Adding a `Path::from_url_path` that accepts a `Url` argument makes sense to me, I would be happy to review a PR that adds this :+1: 

This would still need to decode the path, in order to ensure [path safety](https://docs.rs/object_store/latest/object_store/path/struct.Path.html#path-safety), but would save users that complexity.

FWIW overheads of encoding and [signing](https://docs.aws.amazon.com/general/latest/gr/create-signed-request.html#create-canonical-request) the requests will dominate any additional latency resulting from this encoding dance, and both will be completely dominated by the latency of the store itself (typically in the 10s or 100s of milliseconds).

**Comment by jychen7** [comment]
> I would be happy to review a PR that adds this

thank you, I have draft the PR here: https://github.com/apache/arrow-rs/pull/3663, waiting CI to start

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #3663

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#3651](https://github.com/apache/arrow-rs/issues/3651)
