### ISSUE TITLE
Regression in CSV reader error handling

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-rs#3656]
**Describe the bug**

I have a tool that reads CSV files using DataFusion. I have a file with an invalid UTF-8 character, apparently.

With DataFusion 16.1.0 (Arrow 29), I get this error:

```
Arrow error: Parser error: Error parsing line 27: Error(Utf8 { pos: Some(Position { byte: 3458, line: 28, record: 27 }), err: Utf8Error { field: 14, valid_up_to: 1 } })"))
```

With DataFusion 17.0.0 (Arrow 31), I get this error:

```
ArrowError("underlying Arrow error: Csv error: Encountered invalid UTF-8 data: invalid utf-8 sequence of 1 bytes from index 2911"))
```

The first error is much more helpful because it gives me the line and field numbers. I was quickly able to locate the bad character.

**To Reproduce**

Try reading a CSV file with invalid UTF-8 characters (perhaps try reading some random binary file).

**Expected behavior**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3657
