### ISSUE TITLE
FFI Fails to Account For Offsets

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#3671]
**Describe the bug**

Passing an `ffi::ArrowArray` with a non-zero offset, results in an `ArrayData` with `Buffer` with truncated lengths, as it assumes they have no offset when recording their length.

This is the cause of #3646

**To Reproduce**

**Expected behavior**

Sliced arrays should round-trip through FFI

**Additional context**

I don't think this can result in UB, it just results in bounds checks failing when they shouldn't

**Comment by viirya** [comment]
I will look at this.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3675
