### ISSUE TITLE
Should Parquet pages begin on the start of a row?

### ISSUE THREAD

**Issue by etseidl** [apache/arrow-rs#3680]
**Which part is this question about**
Parquet writer

**Describe your question**
In #1777 it was brought up [here](https://github.com/apache/arrow-rs/issues/1777#issuecomment-1147686956) that the Parquet spec seems to require that pages begin on record boundaries when writing offset indices.  Additionally, the same can be said for V2 page headers (see comment in the parquet-format [thrift](https://github.com/apache/parquet-format/blob/5205dc7b7c0b910ea6af33cadbd2963c0c47c726/src/main/thrift/parquet.thrift#L564) file). It appears that this reasoning was rejected, and the Parquet writer continues to write files where rows can span multiple pages.  I'm wondering if this should still be considered a bug given how difficult finding individual rows is made with this behavior in place.

**Additional context**
I've been working with the cuDF Parquet reader, and files with large nested rows can create havoc when rows span pages.  Parquet-mr appears to hew to the "pages start with R=0" rule.

**Comment by tustvold** [comment]
I'm not sure it is a bug per se, but I definitely think the APIs shouldn't do it unilaterally as they currently do.

I would support making `GenericColumnWriter::write_batch_internal` call `write_mini_batch` treating the `WriterProperties::write_batch_size` as being a number of rows, as opposed to levels. Tbh this is probably what most people assume it does anyway. I'll try to get something up today

**Comment by etseidl** [comment]
> Will try to ensure this makes the release slated for tomorrow, but will depend on reviews

No rush, this might want some thought.  One thing to consider is that this can lead to very uneven page sizes if the data is very "lumpy".  That's the price to pay when using V2 headers or page indexes, but you may want to consider keeping the current behavior when neither of those is requested.
