### ISSUE TITLE
Allow precision loss on multiplying decimal arrays

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#3689]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Current multiply kernel cannot allow precision loss when performing on decimal arrays. However, this is a requirement for decimal multiplication in practice, e.g. Spark supports it. It is difficult to ask users to manually adjust input data.

**Describe the solution you'd like**

It can image that such operation is slower than current multiply, so making it as default seems not acceptable. It seems more reasonable to provide additional decimal specific multiply kernel for that.

**Describe alternatives you've considered**

We cannot do this.

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3690
