### ISSUE TITLE
Cast Binary to Utf8 With Safe True is Unsound

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#3691]
**Describe the bug**

`cast_binary_to_string` added in #3624 is unsound as it creates a `StringArray` containing invalid UTF-8 data. The data is null, but this is insufficient to meet the ArrayData contract which requires all the data be valid UTF-8.

Fortunately this has not yet been released

**To Reproduce**

```
#[test]
    fn test_cast_invalid_utf8() {
        let v1: &[u8] = b"\xFF invalid";
        let v2: &[u8] = b"\x00 Foo";
        let s = BinaryArray::from(vec![v1, v2]);
        let options = CastOptions { safe: true };
        let array = cast_with_options(&s, &DataType::Utf8, &options).unwrap();
        let a = as_string_array(array.as_ref());
        a.data().validate_full().unwrap();
        
        assert_eq!(a.null_count(), 1);
        assert_eq!(a.len(), 2);
        assert!(a.is_null(0));
        assert_eq!(a.value(0), "");
        assert_eq!(a.value(1), "\x00 Foo");
    }
```

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
FWIW this was found by testing the pre-release version against datafusion https://github.com/apache/arrow-datafusion/pull/5241
