### ISSUE TITLE
object_store: support azure cli credential

### ISSUE THREAD

**Issue by roeap** [apache/arrow-rs#3697]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Especially when developing locally, it is often very convenient to use the azure cli credential for authorization.

**Describe the solution you'd like**

Allow using azure cli for authorization against azure object stores.

**Describe alternatives you've considered**

not supporting azure cli

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #3698
