### ISSUE TITLE
Implement simple RecordBatchReader

### ISSUE THREAD

**Issue by wjones127** [apache/arrow-rs#3704]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

As part of ADBC API, we need to produce `RecordBatchReader` from data. I wasn't able to find any existing struct that produces one from a `RecordBatch` or `Vec<RecordBatch>`. Would be happy to hear if I am mistaken! Otherwise, happy to submit a PR for this.

**Describe the solution you'd like**

Probably something like:

```rust
struct SimpleRecordBatchReader { ... }

impl SimpleRecordBatchReader {
    pub fn new(batches: Vec<RecordBatch>, schema: SchemaRef) -> Self;
}
```

**Describe alternatives you've considered**

Open to any alternatives.

**Additional context**

**Comment by tustvold** [comment]
What do you think of a generic `RecordBatchIterator<I>` that can be created from `I: IntoIterator<Item=Result<RecordBatch>>` and a corresponding `Schema`

**Comment by wjones127** [comment]
That sounds even better!
