### ISSUE TITLE
Support unary_dict_mut in arth 

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/arrow-rs#3710]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

when implementing https://github.com/apache/arrow-rs/pull/3709 , need use copy on write on dictionary Array.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3804
