### ISSUE TITLE
parquet: convert Bytes to ByteArray directly

### ISSUE THREAD

**Issue by dopelsunce** [apache/arrow-rs#3719]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I'm using `SerializedFileWriter` to write byte arrays to parquet files in my project which implements a C# binding to the parquet crate. I find it difficult to construct `ByteArray` from raw bytes received across FFI. A conversion path from `bytes::Bytes` to `ByteArray` would be really useful.

Right now, `ByteArray` only supports conversion from `Vec<u8>` and `&str`.

**Describe the solution you'd like**

Implement `From<Bytes>` for ByteArray,

**Describe alternatives you've considered**

For now, I'm using `util::memory::ByteBufferPtr` hidden behind the `experimental` feature flag to achieve this goal.

**Additional context**

I find `ByteArray` is a wrapper around `Bytes`. Short term, we can add trait `From<Bytes>` for `ByteArray`.

In comments above `ByteBufferPtr`, 
> TODO: Remove and replace with [`bytes::Bytes`]". 

I agree ideally we should remove the internal struct  `ByteBufferPtr`.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #3720
