### ISSUE TITLE
Support compressed CSV/TSV files in `parquet-fromcsv`.

### ISSUE THREAD

**Issue by ghuls** [apache/arrow-rs#3721]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Reading a gzip compressed TSV file with `parquet-fromcsv`.

**Describe the solution you'd like**

Support compressed CSV/TSV files in `parquet-fromcsv`.

Also it would be nice if there was a link to the parquet schema text format, or some example schemas.

**Comment by suxiaogang223** [comment]
I sadly find that this feature could not be implemented elegantly. I want to be able to stream compressed files, although I can use the `flate2` library to process compressed files like normal files, but arrow-csv reader requires Seek trait. 
```Rust
arrow_csv::reader::ReaderBuilder
pub fn build<R>(self, reader: R) -> Result<Reader<R>, ArrowError>
where
    R: Read + Seek,
```

**Comment by suxiaogang223** [comment]
great

**Comment by tustvold** [comment]
https://github.com/apache/arrow-rs/issues/4130 has removed the Seek requirement from all the CSV reader APIs, so it should now be possible to support compressed CSV in addition to stdin input within parquet-fromcsv

**Comment by suxiaogang223** [comment]
@ghuls  Thank you for your feedback. I really didn't think about multi-compressed files🙃, could you please make a new issue so i can continue to track this problem and fix it.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #4160
