### ISSUE TITLE
! (not) operator overload for SortOptions

### ISSUE THREAD

**Issue by berkaysynnada** [apache/arrow-rs#3726]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

`SortOptions` type can be overloaded for `!` operator to take reverse sort.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3727
