### ISSUE TITLE
Add datatime/interval/duration into comparison kernels

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#3729]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We found that for these types, current dyn comparison kernels somehow didn't cover them. That makes DataFusion comparison expressions fail to support such types.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3730
