### ISSUE TITLE
Impl Parser for more types in arrow_array::types

### ISSUE THREAD

**Issue by suxiaogang223** [apache/arrow-rs#3735]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The `Parser` has been impled for these arrow_array::types:
https://docs.rs/arrow-cast/33.0.0/arrow_cast/parse/trait.Parser.html#foreign-impls
Maybe we could impl `Parser` for more types, eg Decimal128 and Decimal256 and so on.
Uniformly resolving the type interface can reduce much code.

**Describe the solution you'd like**

Impl `Parser` for the types in https://docs.rs/arrow-array/33.0.0/arrow_array/types/index.html

**Describe alternatives you've considered**

This may be required to add more methods to `Parser`.

For example, to impl Parser for Decinal we should add this:
```rust
pub trait Parser: ArrowPrimitiveType {
    fn parse(string: &str) -> Option<Self::Native>;

    fn parse_formatted(string: &str, _format: &str) -> Option<Self::Native> {
        Self::parse(string)
    }

    /// add for Parse Decimal
    fn parse_with_parameter(string: &str, _precision: u8, _scale: i8) -> Option<Self::Native> {
        Self::parse(string)
    }
}
```

Or consider making the parse function receive arbitrary arguments so that it can only need itself by `Parser`?

**Additional context**

**Comment by tustvold** [comment]
I think the parsing code would benefit from a more holistic rework, perhaps using #3647 as inspiration, I can add it to my list to write up a proper ticket for this
