### ISSUE TITLE
Support Unsigned S3 Payloads

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#3737]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently the AWS request signer will always sign request payloads as described [here](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html#sigv4-auth-header-overview)

> You can optionally compute the entire payload checksum and include it in signature calculation. This provides added security but you need to read your payload twice or buffer it in memory. 

There is, however, the option to perform unsigned requests as described [here](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html).

> You include the literal string UNSIGNED-PAYLOAD when constructing a canonical request, and set the same value as the x-amz-content-sha256 header value when sending the request to Amazon S3  

**Describe the solution you'd like**

We should provide an option to configure this behaviour, as per AWS recommendation we should default to issuing signed requests, but we could provide an option to configure this.

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#3737](https://github.com/apache/arrow-rs/issues/3737)
