### ISSUE TITLE
Support for Async JSON Writer

### ISSUE THREAD

**Issue by metesynnada** [apache/arrow-rs#3742]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I want an async JSON writer to use it in an async context. The current implementation is blocking even if we are in the tokio environment.

**Describe the solution you'd like**
A writer using `tokio::io::AsyncWrite` might be the solution.

**Describe alternatives you've considered**
NA

**Additional context**
Na

**Comment by tustvold** [comment]
Same as commented on the CSV writer ticket, https://github.com/apache/arrow-rs/issues/3740#issuecomment-1438682974, I would recommend implementing this by buffering an encoded batch in memory using the existing writer, prior to flushing it via async. This avoids code duplication, is more generic, and is likely significantly faster. It has been my experience that async does not optimise very well, especially in tight loops, and is best kept independent of the hot synchronous code.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #3

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#3742](https://github.com/apache/arrow-rs/issues/3742)
