### ISSUE TITLE
Use workspace-level configs to simplify Cargo.toml

### ISSUE THREAD

**Issue by iajoiner** [apache/arrow-rs#3773]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
We have a lot of crates with shared info (especially versions) which makes it necessary to use commands for mass renumbering of versions. It also makes it harder to make sure versions of dependencies are consistent. It will be great if we can unify the versions.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jackwener** [comment]
I think this issue is already resolved by https://github.com/apache/arrow-rs/pull/3936
