### ISSUE TITLE
Creates PrimitiveDictionaryBuilder from provided keys and values builders

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#3776]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We can create `PrimitiveDictionaryBuilder` for key/value types of Dictionary. But for some types like Decimal, we cannot custom the data type parameters like precision and scale. We can customize data type for `PrimitiveBuilder` but we cannot create a `PrimitiveDictionaryBuilder` from custom keys and values builders.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3777
