### ISSUE TITLE
Make `InMemory` object store track last modified time for each entry

### ISSUE THREAD

**Issue by gruuya** [apache/arrow-rs#3782]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
The `InMemory` object stores currently [spoofs](https://github.com/apache/arrow-rs/blob/master/object_store/src/memory.rs#L148) the `last_modified` field of the fetched `ObjectMeta`s. In some cases, it is important for this value to be correct. 

One such case is [deducing the `DeltaTable` version](https://github.com/delta-io/delta-rs/blob/main/rust/src/delta.rs#L737-L739) based on a user-provided timestamp in time travel querying—if the `last_modified` field is wrong the wrong version of the table will be loaded. Admittedly, no one should be using an in-memory store for actual work, but it would still be very handy to have this working for testing.

**Describe the solution you'd like**
Keep a separate map of `last_modified` timestamps, and update it on each write call (`put`, `copy`, etc.).

**Describe alternatives you've considered**
Don't use `InMem` store whenever `last_modified` field is crucial for the logic.

**Additional context**
This could be a good first issue.

**Comment by tustvold** [comment]
Changing `storage` to be

```
storage: Arc<RwLock<BTreeMap<Path, (Bytes, DateTime<Utc>)>>>
```

Makes a lot of sense to me :+1:

**Comment by gruuya** [comment]
> Changing `storage` to be
> 
> ```
> storage: Arc<RwLock<BTreeMap<Path, (Bytes, DateTime<Utc>)>>>
> ```
> 
> Makes a lot of sense to me 👍

Agreed, that is indeed more concise!

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #3796

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#3782](https://github.com/apache/arrow-rs/issues/3782)
