### ISSUE TITLE
Make Parquet CLI args consistent

### ISSUE THREAD

**Issue by XinyuZeng** [apache/arrow-rs#3785]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The  current input argument format is inconsistent across CLI tools. E.g., parquet-layout does not need passing "-f" or "--file" for the input file name. This should be consistent across the binary tools.

**Describe the solution you'd like**

One solution is to flag all clap arguments with short and long.

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #3786
