### ISSUE TITLE
Add ObjectStore::append

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#3790]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Some use-cases, such as https://github.com/apache/arrow-datafusion/issues/5130, would like to re-open a file and append rows to it. 

**Describe the solution you'd like**

I would like an `ObjectStore::append` method that can be implemented for stores that support it. This would need a disclaimer that not all stores can support it, and that the atomicity guarantees are significantly weaker than for the other APIs.

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
What else is left for this ticket, I wonder?

**Comment by tustvold** [comment]
It needs to be actually implemented :sweat_smile: https://github.com/apache/arrow-rs/pull/3791 just added the API

**Comment by tustvold** [comment]
Closed by https://github.com/apache/arrow-rs/pull/3824

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#3790](https://github.com/apache/arrow-rs/issues/3790)
