### ISSUE TITLE
Support Casting Between Binary / LargeBinary and FixedSizeBinary

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#3826]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently arrow_cast does not have any support for FixedSizeBinary outside of casting to a `NullArray`, this should be fixed

**Describe the solution you'd like**

* A conversion to FixedSizeBinary that verifies that all the slices have the correct length
* An conversion to Binary / LargeBinary that creates a new set of offsets, first verifying this won't overflow the offset type

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
@tustvold  what do you think about casting between UTF8 and FixedSizeBinary? If that is worth it I will file a separate ticket

**Comment by Weijun-H** [comment]
Could I pick this up?
