### ISSUE TITLE
(object_store) Update ring to latest version to fix win-64 builds

### ISSUE THREAD

**Issue by chitralverma** [apache/arrow-rs#3829]
**Describe the bug**
`object_store` uses [ring](https://github.com/briansmith/ring/) for signatures and cryptography but ring has issues building on windows 64bit arch.

So any project which cross-compiles and is using object_store as a dependency will have a build failure on win64 builds.

This is a issue for tracking progress of the upgrade as ring itself is yet to publish a fix for this in an upcoming release.

**To Reproduce**
Create a project with object_store as dependency and cargo build it for `aarch64-pc-windows-msvc` target.

See example of a failed build at the link below,
https://github.com/chitralverma/test-native-proj/actions/runs/4373382006

**Expected behavior**
The build should not break.

**Additional context**
More context and discussion at the link below,
https://github.com/briansmith/ring/issues/1167

**Comment by tustvold** [comment]
Closed by #4887
