### ISSUE TITLE
Add as_any() to the ObjectStore to make it able to identify which ObjectStore is using for the related trait object

### ISSUE THREAD

**Issue by yahoNanJing** [apache/arrow-rs#3838]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The context is we are working on introducing a data source cache layer for Ballista & DataFusion https://github.com/apache/arrow-ballista/issues/645. The cache layer will be able to multiple `ObjectStore` data. And we need to leverage the identification of the `ObjectStore`.

**Describe the solution you'd like**

Add as_any() to the ObjectStore to make it able to identify which ObjectStore is using for the related trait object.

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
> And we need to leverage the identification of the ObjectStore.

Could you expand a bit on what you mean by this, why does the cache need to know the backing implementation?
