### ISSUE TITLE
Add compression options (levels)

### ISSUE THREAD

**Issue by spebern** [apache/arrow-rs#3844]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Some compression codecs support different levels (e.g. zstd). In parquet2 levels are supported: https://github.com/jorgecarleitao/parquet2/blob/9eee7eb1130aed4cd0d841e59c325cc366fc3798/src/parquet_bridge.rs#L100

**Describe the solution you'd like**

I'd like to be able to set the compression levels and other options when writing parquet files.

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #3847

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3846
