### ISSUE TITLE
Support `get_row_group` in AsyncFileReader

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/arrow-rs#3851]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
When i implementing https://github.com/apache/arrow-datafusion/issues/4512
I found in `AsyncFileReader`(df used) can not get the specific `RowGroupReader `

If i got the RowGroupReader then call `get_column_bloom_filter` will return the bloomFilter

https://github.com/apache/arrow-rs/blob/f78a9be8b3a7479418cacc5ea6755b1e60c4b03f/parquet/src/file/reader.rs#L77-L94
 async version:
https://github.com/apache/arrow-rs/blob/de9f82693f94721916e37f4896e9394411d8076f/parquet/src/arrow/async_reader/mod.rs#L128-L148

I think they should be consistent, Is there any other reason not supported?
**Describe the solution you'd like**

So i try to create a new struct  `AsyncRowGroupReader`

**Describe alternatives you've considered**

**Additional context**

**Comment by Ted-Jiang** [comment]
@tustvold @alamb Could you take a look, is this a reasonable change 🤔 ?

**Comment by tustvold** [comment]
I don't think it is that simple as the IO to fetch the bloom filter data needs to be done ahead of time. I'll have a think over the next couple of days and write up how to support this

**Comment by Ted-Jiang** [comment]
btw,  i think support read the special bloom filter by row_group_id and col_id unlike page Index.

**Comment by madgene** [comment]
@Ted-Jiang 如果用SerializedFileReader先把parquet文件中的所有bloom filter数据都读取出来，然后调用prune_row_groups_by_bloom_filter方法做prune，PruningPredicate::prune中首先创建一个RecordBatch再通过self.predicate_expr.evaluate(&statistics_batch)方法。请教一下怎么用bloom filter数据构建RecordBatch再evaluate，或者是通过什么别的方式能够evaluate？

**Comment by Ted-Jiang** [comment]
> @Ted-Jiang 如果用SerializedFileReader先把parquet文件中的所有bloom filter数据都读取出来，然后调用prune_row_groups_by_bloom_filter方法做prune，PruningPredicate::prune中首先创建一个RecordBatch再通过self.predicate_expr.evaluate(&statistics_batch)方法。请教一下怎么用bloom filter数据构建RecordBatch再evaluate，或者是通过什么别的方式能够evaluate？

Sorry，plz communicate in English

**Comment by madgene** [comment]
@Ted-Jiang  Perhaps we can prune rowgroups by invoking prune_row_groups_by_bloom_filter method with all bloom filter data which is read with SerializedFileReader. In PruningPredicate::prune, a RecordBatch is first created and then evaluated using the self.predicate_expr.evaluate(&statistics_batch) method. Could you please advise me how to construct a RecordBatch using bloom filter data and then evaluate it, or is there any other way to evaluate?

**Comment by hengfeiyang** [comment]
@tustvold Any suggestions for this? we want to read the bloom filter in Datafusion. https://github.com/apache/arrow-datafusion/issues/4512

**Comment by tustvold** [comment]
The simplest option is likely to add an async function to ParquetRecordBatchStreamBuilder that fetches and decodes the bloom filters for a given column and row group, and returns this.

We likely don't want to eagerly fetch and decode bloom filters as the formulation parquet uses tends to be very large.

**Comment by tustvold** [comment]
Closed by #4917
