### ISSUE TITLE
Enable setting FlightDescriptor on FlightDataEncoderBuilder

### ISSUE THREAD

**Issue by alexwilcoxson-rel** [apache/arrow-rs#3855]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
When using FlightDataEncoder to send arrow batches to a flight do_put endpoint, FlightDescriptor cannot easily be set on first message. https://arrow.apache.org/docs/format/Flight.html#uploading-data

**Describe the solution you'd like**
On FlightDataEncoderBuilder a `with_flight_descriptor` method would be nice. The FlightDescriptor would then be set on the first FlightData retrieved from the encoder.

**Describe alternatives you've considered**
Here is a workaround, I may be missing something simpler
```rust
let mut encoder = FlightDataEncoderBuilder::new()
    .with_schema(schema.clone())
    .build(stream);

let mut first_flight_data = encoder
    .next()
    .await
    .expect("no flight data")
    .expect("flight data was error");
first_flight_data.flight_descriptor = Some(FlightDescriptor {
    r#type: DescriptorType::Path.into(),
    path: vec!["table_name".to_string()],
    cmd: Bytes::default(),
});
let put_stream = stream::once(async { Ok(first_flight_data) }).chain(encoder);
```

**Comment by alamb** [comment]
Thanks for the suggestion @alexwilcoxson-rel  -- I agree this sounds like a nice addition to the API. 

Given the request is well specified and the code is fairly easy to test, I think this would be a good first issue for someone to work on if they wanted, so marking it thusly

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4101
