### ISSUE TITLE
[REGRESSION] Parsing timestamps with fractional seconds / microseconds / milliseconds / nanoseconds

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#3859]
**Describe the bug**
https://github.com/apache/arrow-rs/pull/3801 introduced a regression. Prior to arrow 34 the following timestamp could be parsed:

```
1969-01-01T00:00:00.1' 
```

However, after the upgrade it will generate a parse error. This can be worked around by padding the precision to be a whole number of seconds,  microseconds, milliseconds, or nanoseconds. For example

```
1969-01-01T00:00:00.100' 
```

**To Reproduce**

Try to parse this as a timestamp:
```
1969-01-01T00:00:00.1' 
```

**Expected behavior**
It should be parsed correctly

**Additional context**
Found during DataFusion upgrade: https://github.com/apache/arrow-datafusion/pull/5441

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3860
