### ISSUE TITLE
parquet_derive doesn't support Vec<u8>

### ISSUE THREAD

**Issue by waymost** [apache/arrow-rs#3864]
**Describe the bug**
When I attempt to `#[derive(ParquetRecordWriter)]` on a struct that contains fields of type `Vec<u8>`, the proc-macro panics.

**To Reproduce**
```
#[derive(ParquetRecordWriter)]
pub struct Row {
  foo: Vec<u8>,
}
```

results in

```
message: not implemented: Unsupported: Vec(
    TypePath(
        Path(
            TypePath {
                qself: None,
                path: Path {
                    leading_colon: None,
                    segments: [
                        PathSegment {
                            ident: Ident {
                                ident: "u8",
                                span: #0 bytes(4505..4507),
                            },
                            arguments: None,
                        },
                    ],
                },
            },
        ),
    ),
)
```

**Expected behavior**
Macro successfully generates the code to write a Vec<u8> to a parquet file.

**Additional context**
Support for `Vec<u8>` is explicitly mentioned in the `parquet_derive` readme, but a field of that type is not present in the integration test crate (separately, neither is `Uuid`).

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #3878

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet-derive'} from #3878
