### ISSUE TITLE
Make it easier to match FlightSQL messages

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#3874]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
When implementing FlightSQL the do_get and get_flight_info gRPC methods are called for several of the message types. Thus those endpoints need to decode the incoming message and then do the appropriate action

However, the current way the messages are decoded from `prost::Any` means the only way I have figured out how to check dynamically for each message type is an `if` chain like this

```rust
        } else if let Some(decoded_cmd) = Any::unpack::<CommandGetCatalogs>(&msg)? {
          // act
        } else if let Some(decoded_cmd) = Any::unpack::<CommandGetDbSchemas>(&msg)? {
          // act
        } else if let Some(decoded_cmd) = Any::unpack::<ActionCreatePreparedStatementRequest>(&msg)?
        {
          // ...
        }
```

It would be great to have an enum so a rust `match` statement could be used

**Describe alternatives you've considered**
@stuartcarnie proposed the following in  https://github.com/influxdata/influxdb_iox/pull/7213/files#r1137963627:

 I created [a gist](https://gist.github.com/stuartcarnie/a121def085aaaf3f75ab5e592e4c4343#file-mod-rs-L230-L233) that extends [the sql crate](https://github.com/apache/arrow-rs/blob/9728c676b50b19c06643a23daba4aa4a1dc48055/arrow-flight/src/sql/mod.rs) in arrow-flight, that demonstrates an approach allowing us to remove all the `if Some(..)` to a single match:

```rust
match Commands::unpack(&msg)? {
    Commands::CommandStatementQuery(cmd) => Ok(Self::CommandStatementQuery(cmd)),
    Commands::CommandPreparedStatementQuery(CommandPreparedStatementQuery { prepared_statement_handle }) => Ok(Self::CommandPreparedStatementQuery(preparedstatementhandle::try_decode(prepared_statement_handle)?)),
    // etc
}
```

I extended the `prost_message_ext` macro to create a `Commands` enum with all the messages passed to the macro. The `Commands` macro has a static function, `unpack`, that is capable of unpacking any of the registered messages.

**Additional context**

**Comment by alamb** [comment]
cc @avantgardnerio

**Comment by stuartcarnie** [comment]
@avantgardnerio and @alamb figured I'd clean up the Gist and open the PR:

- https://github.com/apache/arrow-rs/pull/3887

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3887
