### ISSUE TITLE
`take` drops timezone from an input array with type Timestamp

### ISSUE THREAD

**Issue by msalib** [apache/arrow-rs#393]
**Describe the bug**
If you call `take` with an Array of type `Timestamp(Milliseconds, Some(UTC))`, you'll get a result with type `Timestamp(Milliseconds, None)`. I'm looking at version 4.2.0 compiled with rust 1.52.

**To Reproduce**
If you like I can write a test case....

**Expected behavior**
I expect kernels like `take` to return an array with the same data type as their input.

**Additional context**
I think the problem is in `compute/kernels/take.rs`:
```
        DataType::Timestamp(Second, _) => {
            downcast_take!(TimestampSecondType, values, indices)
        }
        DataType::Timestamp(Millisecond, _) => {
            downcast_take!(TimestampMillisecondType, values, indices)
        }
        DataType::Timestamp(Microsecond, _) => {
            downcast_take!(TimestampMicrosecondType, values, indices)
        }
        DataType::Timestamp(Nanosecond, _) => {
            downcast_take!(TimestampNanosecondType, values, indices)
        }
```

Note the 4 `_`s indicating that the timezone information is being dropped and never used in constructing `take`'s output.

**Comment by tustvold** [comment]
Closed by #1046
