### ISSUE TITLE
my contribution not marged in 4.2 release 

### ISSUE THREAD

**Issue by kazuk** [apache/arrow-rs#394]
**Describe the bug**

I add a with_escape and some function into arrow::csv::reader::ReaderBuilder. 

PR: https://github.com/apache/arrow-rs/pull/326

but docs.rs document for 4.2.0 not contains this.
https://docs.rs/arrow/4.2.0/arrow/csv/reader/struct.ReaderBuilder.html

and my own code for 4.2.0, build failed with this error.

```
error[E0599]: no function or associated item named `with_escape` found for struct `arrow::csv::ReaderBuilder` in the current scope
```

**To Reproduce**
Steps to reproduce the behavior: write code using `ReaderBuilder::with_escape` .

**Expected behavior**
compilation success

**Additional context**

tag 4.2.0 seems contains my commits.
https://github.com/apache/arrow-rs/compare/4.2.0...master

seems something error in release process  around  `cargo publish`

**Comment by alamb** [comment]
Sorry @kazuk -- I a still working out the backport procedure. I have created a PR here https://github.com/apache/arrow-rs/pull/407 (which if merged will become part of arrow-rs 4.3).

**Comment by alamb** [comment]
(eta of 4.3 is in ~ 1 week -- I hope to make the RC June 11)

**Comment by kazuk** [comment]
thanks @alamb 
I keep wait 4.3 release.

Can you change release tag page?

https://github.com/apache/arrow-rs/releases/tag/4.2.0

this shows ` 33 commits to master since this tag `.
that's references branch `master`, released binary branch `active_release`.

**Comment by alamb** [comment]
> I keep wait 4.3 release.

Thank you

> Can you change release tag page?
> https://github.com/apache/arrow-rs/releases/tag/4.2.0
> this shows 33 commits to master since this tag.
> that's references branch master, released binary branch active_release.

I am not sure how to change how github reports commits since a branch on the tags page. Can you explain more of what you would like me to do?

However, I have gone and made a 4.0.0 tag in the arrow-rs repo, so now you can see what was included in 4.2.0 compared to 4.0.0 by comparing those tags: https://github.com/apache/arrow-rs/compare/4.0.0...4.2.0

**Comment by kazuk** [comment]
I check repository setting page on github.

that link depends default base branch setting. and not fits this repo.

I close this issue . Thank you.

**Comment by alamb** [comment]
@kazuk  4.3.0 has been released

https://crates.io/crates/arrow/4.3.0

**Comment by kazuk** [comment]
I test arrow-rs and parquet-rs 4.3.0 with my code. 

that works fine!

Thanks again.
