### ISSUE TITLE
RecordBatch From StructArray Silently Discards Nulls

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#3952]
**Describe the bug**

**To Reproduce**

```
#[test]
fn test_from_struct() {
    let s = StructArray::from(ArrayData::new_null(
        &DataType::Struct(vec![Field::new("foo", DataType::Int32, false)]),
        2,
    ));

    let batch = RecordBatch::from(&s);
    assert_eq!(batch.column(0).null_count(), 2);
}
```

**Expected behavior**

The above should fail

**Additional context**

**Comment by SinanGncgl** [comment]
Hi, do we expect a failure something like =>  `left = 0` and `right = 2` `assertion failed: (left == right)` so should we expect an empty batch from `RecordBatch::from`? Could you please elaborate more so that maybe I can take it? Thanks for your time and answer in advance.

**Comment by tustvold** [comment]
There is already a PR to fix this, I just accidentally linked the wrong issue :sweat_smile:

**Comment by SinanGncgl** [comment]
> There is already a PR to fix this, I just accidentally linked the wrong issue sweat_smile

Ah okay, thank you for your swift response :smiley:

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #3953
