### ISSUE TITLE
Support parquet map type in arrow IO

### ISSUE THREAD

**Issue by nevi-me** [apache/arrow-rs#396]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

A continuation of #395, we should be able to read and write parquet maps to and from arrow maps.

**Describe the solution you'd like**

Supporting parquet map types in the arrow reader and writer.

**Describe alternatives you've considered**

None

**Additional context**

Same as #395

**Comment by tustvold** [comment]
With #2500 I'm happy that support for this is complete
