### ISSUE TITLE
Subtracting `Timestamp` from `Timestamp`  should produce a `Duration` (not `Timestamp`) 

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#3964]
**Describe the bug**
Subtracting two `Timestamp` columns results in another Timestamp which is not correct

**To Reproduce**

```rust
fn subtract_timestamps() {
    let arr1 = TimestampNanosecondArray::from(vec![
        1_000,
        1_000_000,
        1_000_000_000,
        1_000_000_000_000,
        1_000_000_000_000_000,
        1_000_000_000_000_000_000,
    ]);

    let arr2 = TimestampNanosecondArray::from(vec![
        2_000,
        2_000_000,
        2_000_000_000,
        2_000_000_000_000,
        2_000_000_000_000_000,
        2_000_000_000_000_000_000,
    ]);

    println!(
        "input:\n{}\n{}",
        pretty_format_columns("arr1", &[Arc::new(arr1.clone()) as _]).unwrap(),
        pretty_format_columns("arr2", &[Arc::new(arr2.clone()) as _]).unwrap(),
    );

    let interval = subtract_dyn(&arr2, &arr1).unwrap();

    println!(
        "output{}:\n{}",
        interval.data_type(),
        pretty_format_columns("interval", &[Arc::new(interval.clone()) as _]).unwrap(),
    );
}
```

Which produces

```
input:
+----------------------------+
| arr1                       |
+----------------------------+
| 1970-01-01T00:00:00.000001 |
| 1970-01-01T00:00:00.001    |
| 1970-01-01T00:00:01        |
| 1970-01-01T00:16:40        |
| 1970-01-12T13:46:40        |
| 2001-09-09T01:46:40        |
+----------------------------+
+----------------------------+
| arr2                       |
+----------------------------+
| 1970-01-01T00:00:00.000002 |
| 1970-01-01T00:00:00.002    |
| 1970-01-01T00:00:02        |
| 1970-01-01T00:33:20        |
| 1970-01-24T03:33:20        |
| 2033-05-18T03:33:20        |
+----------------------------+
output Timestamp(Nanosecond, None):
+----------------------------+
| interval                   |
+----------------------------+
| 1970-01-01T00:00:00.000001 |
| 1970-01-01T00:00:00.001    |
| 1970-01-01T00:00:01        |
| 1970-01-01T00:16:40        |
| 1970-01-12T13:46:40        |
| 2001-09-09T01:46:40        |
+----------------------------+
```

**Expected behavior**
~I expect the output to be an interval of type `Interval(MonthDayNano)` (not Timestamp)~

Updated (after discussion with @tustvold ) I expect the output to be a duration of type `Duration(unit)` where `unit` is the same as the source `Timestamp(unit)` (not Timestamp) 

**Additional context**
Here is what postgres does:

```sql
postgres=# create table test as select now() - now();
SELECT 1
postgres=# \d test
                 Table "public.test"
  Column  |   Type   | Collation | Nullable | Default
----------+----------+-----------+----------+---------
 ?column? | interval |           |          |

postgres=#
```

**Comment by alamb** [comment]
I would also be fine with `Duration ` -- changing ticket

**Comment by alamb** [comment]
I think this is a good first issue because the semantics are well defined and there are some existing examples

**Comment by alamb** [comment]
> I would like to impement antoher function for timestamp types, called timestamp_math_op(), which deals with timestamp type specific operations. And always returns Duration when calculating between two timestamps.

Sounds good to me

**Comment by berkaysynnada** [comment]
> it is my first rust related PR, just want to highlight my plan for implement this:
> 
> Within function subtract_dyn(), we currently use typed_dict_math_op() and math_op().
> 
> I would like to impement antoher function for timestamp types, called timestamp_math_op(), which deals with timestamp type specific operations. And always returns Duration when calculating between two timestamps.

Thanks for working on this issue :)
After merging that [PR](https://github.com/apache/arrow-datafusion/pull/5764) in datafusion, timestamp - timestamp operations give results in Interval types, and it is planned to get arithmetics moved to arrow-rs. Can you check that PR to not have an inconsistent behavior?

**Comment by tustvold** [comment]
> After merging that PR in datafusion, timestamp - timestamp operations give results in Interval types,

Can we revisit this decision in DataFusion, interval types are probably not the correct type to be returning for such an operation

**Comment by alamb** [comment]
I think it would be fine to support converting to duration in arrow-rs (and we can convert to Interval in datafusion as needed)

The reason we are pushing ahead with interval (rather than interval and duration) in DataFusion is to get something working incrementally without having to sort out all the subtleties with Intervals, Durations, arithmetic and conversions. 

Then I think over time we can and will add more sophistication (like making the distinction between Duration and Interval and coercing automatically between them)  to DataFusion

Thus, I suggest we get the kernels correct in arrow-rs (and provide the appropriate casting operations) and then we can upgrade DataFusion to use them. 

So in this case, let's have timestamp - timestamp produce duration in arrow.rs sounds good.

I will also file a ticket about casting to/from Duration and Interval

**Comment by alamb** [comment]
I filed https://github.com/apache/arrow-rs/issues/3998 to track casting durations to/from intervals

**Comment by ozankabak** [comment]
> The latter is significantly easier to reason about, although it would appear postgres lacks such a construct.

Yes, the issue is most DB's (and SQL itself) simply use the timestamp - timestamp = interval pattern. However, from our perspective using durations is fine as long as there is casting/coercing mechanism to take care of the transformation cheaply.

**Comment by ozankabak** [comment]
SGTM

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4244
