### ISSUE TITLE
[REGRESSION] Parsing dates of the form `2022-1-1` that used to parse (now needs `2022-01-01`)

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#3969]
**Describe the bug**
In arrow `34.0.0`, values such as `'2021-1-1T05:11:10.432'` were parsed as a timestamp but now they error

**To Reproduce**

Try to parse this value as a timestamp: `'2021-1-1T05:11:10.432'`

**Expected behavior**

The value `'2021-1-1T05:11:10.432'` parses the same as `'2021-01-01T05:11:10.432'`

Workaround is to change it to (add leading zeros) `'2021-01-01T05:11:10.432'`

**Additional context**
We discovered this as part of the upgrade in DataFusion https://github.com/apache/arrow-datafusion/pull/5685

Per @tustvold it appears that `2021-1-1T05:11:10.432` is supported by chrono even though it is not strictly valid and arrow was not documented to support this format: https://github.com/apache/arrow-datafusion/pull/5685#discussion_r1150732948

It may be that we simply choose not to fix this regression as the previous implementation was working "by accident" but I wanted to file this ticket to track the change in behavior

**Comment by tustvold** [comment]
I'm closing this as 2 months have passed with no complaints
