### ISSUE TITLE
Prevent UnionArray with Repeated Type IDs

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#3982]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently `DataType::Union` has no protection against the same type ID appearing multiple times in its `DataType`.

**Describe the solution you'd like**

We should probably validate that the `type_ids` are unique, and prevent constructing an invalid `DataType`

**Describe alternatives you've considered**

We could not do this, much like currently permit invalid `DataType::Decimal` #2362

**Additional context**

**Comment by Weijun-H** [comment]
Could I pick this ticket up?

**Comment by Weijun-H** [comment]
Should we guarantee that `typeid` is unsigned? The current implementation does not guarantee it.

**Comment by tustvold** [comment]
> Should we guarantee that typeid is unsigned

The arrow format specifies the following - https://arrow.apache.org/docs/format/Columnar.html#union-layout

> A buffer of 8-bit signed integers. Each type in the union has a corresponding type id whose values are found in this buffer. A union with more than 127 possible types can be modeled as a union of unions.

So they should be signed integers, but never negative :sweat_smile:. Most likely this was originally a workaround for Java

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4070

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #3981
