### ISSUE TITLE
Support Decimals cast to Utf8/LargeUtf

### ISSUE THREAD

**Issue by comphead** [apache/arrow-rs#3991]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently the CAST is not supported from Decimal to UTF. This ticket to add the necessary cast

**Describe the solution you'd like**

Support Decimals cast to Utf8/LargeUtf

**Describe alternatives you've considered**

None
**Additional context**

None

**Comment by comphead** [comment]
I will create a PR today

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3994
