### ISSUE TITLE
Handle overflow precision when casting from integer to decimal

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#3995]
**Describe the bug**

Although `cast` kernel uses `CastOptions` when casting from integer to decimal, its behavior on overflow-checking is incomplete.

For now, it'd check division or multiplication if overflowing on underlying decimal native types (i.e., i128 and i256). But it doesn't check if input integer is overflowing on decimal precision. This causes weird behavior when downstream project (e.g., DataFusion) uses `cast` kernel to cast integer to decimal.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #3996
