### ISSUE TITLE
Support casting to/from Interval and Duration

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#3998]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
In DataFusion we are trying to add complete date/time support . IN addition to Interval types some of this arithmetic will also likely result in Durations (e.g. `timestamp - timestamp` -- see https://github.com/apache/arrow-rs/issues/3964)

```
DataType::Duration(TimeUnit::Second)
DataType::Duration(TimeUnit::Millisecond)
DataType::Duration(TimeUnit::Microsecond)
DataType::Duration(TimeUnit::NanoSecond)
```

```
DataType::Interval(IntervalUnit::YearMonth)
DataType::Interval(IntervalUnit::DayTime)
DataType::Interval(IntervalUnit::MonthDayNano)
```

However, there is no easy way currently to convert between `Durations` and `Intervals` 

**Describe the solution you'd like**
Add support for `cast`ing durations to intervals to the cast kernel : https://github.com/apache/arrow-rs/blob/master/arrow-cast/src/cast.rs#L18-L36

The following casts should be always supported as they are lossless (`DataType::Interval(IntervalUnit::MonthDayNano)` has nanosecond precision)

* `DataType::Duration(TimeUnit::Second)` <--> `DataType::Interval(IntervalUnit::MonthDayNano)`
* `DataType::Duration(TimeUnit::Millisecond)` <--> `DataType::Interval(IntervalUnit::MonthDayNano)`
* `DataType::Duration(TimeUnit::Microsecond)` <--> `DataType::Interval(IntervalUnit::MonthDayNano)`
* `DataType::Duration(TimeUnit::NanoSecond)` <--> `DataType::Interval(IntervalUnit::MonthDayNano)`

I am not sure what other, if any, casts should be supported 

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
> as they are lossless

TBC, the duration should be converted into the nanoseconds portion of `MonthDayNano`, returning an error or null (depending on CastOptions::safe) in the event of overflow. 

As a result of daylight savings time, it would be incorrect to assume a day has 24 hours.

> I am not sure what other, if any, casts should be supported

Truncating casts to `MonthDayTime` might also be worthwhile

**Comment by Weijun-H** [comment]
I am glad to pick this up.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4020
