### ISSUE TITLE
Remove non-existent `js` feature from README

### ISSUE THREAD

**Issue by akazukin5151** [apache/arrow-rs#4000]
The `js` feature was removed in PR #674, but it wasn't removed from the feature list in the README:

https://github.com/apache/arrow-rs/blob/591f0ef45c8184c2cbf5d46fc1ddf81c207e55ee/arrow/README.md?plain=1#L49

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4001
