### ISSUE TITLE
object_store: Builders (S3/Azure/GCS) are missing the `get method` to get the actual configuration information 

### ISSUE THREAD

**Issue by r4ntix** [apache/arrow-rs#4021]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The current Builders (S3/Azure/GCS) only provide the `set method`, e.g. `builder.with_access_key_id()`. 

Since the current Builders also support getting configuration information from the `::from_env()`, so we also need the `get method` to verify that the actual configuration is as expected.

**Describe the solution you'd like**

- support `get method`

**Describe alternatives you've considered**

- make struct fields of builders to `pub`

**Additional context**

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4021](https://github.com/apache/arrow-rs/issues/4021)
