### ISSUE TITLE
`ParquetRecordBatchStream` Should Return the Projected Schema

### ISSUE THREAD

**Issue by msalib** [apache/arrow-rs#4023]
**Describe the bug**

Let's say you're trying to async read a Parquet file on S3, and that file has metadata (like "created by"). There's an inconsistency:

`ParquetRecordBatchStream::schema` will produce a `Schema` object that includes that metadata.
But `ParquetRecordBatchStream` will yield `RecordBatch`es that have schema objects that don't have the metadata.

The problem is that if you create an  `ArrowWriter` using the first schema and then try to write batches from the stream to it, the schemas won't match (the writer is expecting metadata but each batch has a schema without metadata).

**Expected behavior**

I'd expect that either:
* `ParquetRecordBatchStream::schema` produces a `Schema` without metadata, or
* the `RecordBatch`es produced by `ParquetRecordBatchStream` have the exact same schema as what `::schema` returns, or
* `ArrowWriter` should tolerate its supplied schema differing from the batch schemas provided to `write()` in metadata

**Comment by tustvold** [comment]
> ArrowWriter should tolerate its supplied schema differing from the batch schemas provided to write() in metadata

https://github.com/apache/arrow-rs/pull/4027 relaxes the check on ArrowWriter

> ParquetRecordBatchStream::schema produces a Schema without metadata, or

I think this would be consistent with `ParquetRecordBatchReader`, and would ensure it matches the `RecordBatch` that are returned. `ParquetRecordBatchStreamBuilder::schema` should return the schema with metadata.

**Comment by tustvold** [comment]
Updated based on https://github.com/apache/arrow-rs/pull/5135#issuecomment-1830663668

I agree this is a bug
