### ISSUE TITLE
Flight SQL Server missing command type.googleapis.com/arrow.flight.protocol.sql.CommandGetXdbcTypeInfo

### ISSUE THREAD

**Issue by c-thiel** [apache/arrow-rs#4054]
**Describe the bug**
In the flight SQL servers' get_flight_info method, there currently is no method for the 
The command itself is defined here: https://github.com/apache/arrow-rs/blob/6b17775f37b939221d855514db4ffb3344deb1f4/arrow-flight/src/sql/arrow.flight.protocol.sql.rs#L104

It should be implemented in this match:
https://github.com/apache/arrow-rs/blob/ee4003328d6615e011303ba57c24264a3f454e12/arrow-flight/src/sql/server.rs#L320

as well as the Server Trait.

**Expected behavior**
I can implement all Flight SQL Commands without overwriting `get_flight_info` or using the Fallback.

**Further Motivation**
This command is actually quite common. When using PowerBI and the Dremio ODBC / Flight driver to connect to a flight server, it get's issued right before the preview of any dataset.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4055

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow-flight'} from #4055
