### ISSUE TITLE
Additional data type groups

### ISSUE THREAD

**Issue by izveigor** [apache/arrow-rs#4056]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
In PyArrow there are some functions that check data type groups:
| Name | Source |
| ------ | -------- |
| is_integer | [link](https://github.com/apache/arrow/blob/main/python/pyarrow/types.py#L68-L76) |
| is_floating | [link](https://github.com/apache/arrow/blob/main/python/pyarrow/types.py#L189-L197)|
| is_unsigned_integer | [link](https://github.com/apache/arrow/blob/main/python/pyarrow/types.py#L90-L98) |
| is_signed_integer | [link](https://github.com/apache/arrow/blob/main/python/pyarrow/types.py#L79-L87)|

I think their implementation will be useful in solving some issues.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4057
