### ISSUE TITLE
Parquet AsyncArrowWriter not shutting down inner async writer. 

### ISSUE THREAD

**Issue by kindly** [apache/arrow-rs#4058]
**Describe the bug**

I have tried to use the new parquet `AsyncArrowWriter` by writing files to S3 using the `object_store` multipart upload.  However, for the upload to complete, the inner writer needs to be `shutdown` and this writer does not do that.

**Additional context**

Pull request to shut down on `close` will be in pull request.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #4059
