### ISSUE TITLE
Better JSON Reader Error Messages

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4076]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The JSON reader currently produces errors like

```
 Error: ArrowError(JsonError("expected { got string"))
```

This is hard to debug, and provides very little information

**Describe the solution you'd like**

Error messages should include row number and some value context

**Describe alternatives you've considered**

**Additional context**

**Comment by Weijun-H** [comment]
willing to take this

**Comment by tustvold** [comment]
I'll pick this up, I'm not sure how easy it will be to avoid regressing performance 😅

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4079
