### ISSUE TITLE
object_store: Incorrect parsing of https Path Style S3 url

### ISSUE THREAD

**Issue by trueleo** [apache/arrow-rs#4078]
**Description**
Currently, the S3 bucket URL parsing for AWS [here](https://docs.rs/object_store/latest/object_store/aws/struct.AmazonS3Builder.html#method.with_url)  is mistakenly parsing the bucket out of URL `https://s3.bucket.amazonaws.com`. However, this URL does not represent a valid S3 bucket URL format. The correct format should be `https://s3.region.amazonaws.com/bucket` for Path style as mentioned in AWS user guide [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-bucket-intro.html)

**Expected behavior**
The `parse_url` method on builder should correctly parse the S3 bucket URL and set region and bucket accordingly.

**Additional context**
[Invalid URL in Test](https://docs.rs/object_store/latest/src/object_store/aws/mod.rs.html#1414)
[parse_url](https://docs.rs/object_store/latest/src/object_store/aws/mod.rs.html#759-762)

**Comment by tustvold** [comment]
I agree that the logic doesn't appear to be consistent with the docs you linked and would support changing it to match

This code was originally contributed in https://github.com/apache/arrow-rs/pull/3327/files#diff-463799e28d6cd175bcf4dd2b296385646ebed96271da65b05a02ab133d31c82cR1028 so tagging @roeap for context

**Comment by roeap** [comment]
Yes, there seems to be a bug.

https://github.com/apache/arrow-rs/blob/f14a6787cae77d9eb7d44a8cbb71d9fcc9f8365a/object_store/src/aws/mod.rs#L811-L821

In the first match we should be assigning the region, nut the bucket.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #4082

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4078](https://github.com/apache/arrow-rs/issues/4078)
