### ISSUE TITLE
lexsort_to_indices may output larger size than input

### ISSUE THREAD

**Issue by jychen7** [apache/arrow-rs#4087]
**Describe the bug**
Not sure if it is arrow-rs bug. This issue is created to track
We find a problem in https://github.com/apache/arrow-datafusion/issues/3747#issuecomment-1271514648

**To Reproduce**
TBD

**Expected behavior**
sort output size should be <= input size (smaller is expected when it is partial sort, i.e. top K)

**Additional context**

**Comment by tustvold** [comment]
I don't think the size of the underlying buffers is something we guarantee, whilst one could argue that we should correctly estimate the output buffers to not be larger than the inputs, this is not guaranteed.

Perhaps you might explain why this is a problem?

**Comment by tustvold** [comment]
Closing this as I've not heard back, feel free to reopen if still an issue

**Comment by jychen7** [comment]
> one could argue that we should correctly estimate the output buffers to not be larger than the inputs, this is not guaranteed.

Thanks, that makes sense
