### ISSUE TITLE
Enhance documentation for parquet

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#41]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-4941

Ultimately this is just one piece of completing ARROW-4683. In order to enable a lint check for missing docs, we'll want to cover any existing gaps in the documentation.

**Comment by ByteBaker** [comment]
@alamb can we also link this to #6424?

**Comment by ByteBaker** [comment]
@alamb can we also link this to #37?

**Comment by ByteBaker** [comment]
@alamb I think we can also link this to #37.

**Comment by alamb** [comment]
Let's track this in https://github.com/apache/arrow-rs/issues/37 and just close this one. Thanks @ByteBaker
