### ISSUE TITLE
add specific error log for empty JSON array

### ISSUE THREAD

**Issue by jiangzhx** [apache/arrow-rs#4105]
**Describe the bug**

#https://github.com/apache/arrow-datafusion/issues/6026

**To Reproduce**

just one line json file 
{"items": []}

**Expected behavior**

error log change from 
```
Arrow error: Not yet implemented: Support for Null in JSON reader
to 
Cannot infer schema for empty JSON array
```

**Additional context**

**Comment by BubbaJoe** [comment]
Btw I was able to fix this error by removing all empty arrays from my json source data.

But it would have been nice if it was possible to pass some option to ignore un-inferable fields like this so I don't get errors on 'SELECT * ...'

**Comment by jiangzhx** [comment]
> Btw I was able to fix this error by removing all empty arrays from my json source data.
> 
> But it would have been nice if it was possible to pass some option to ignore un-inferable fields like this so I don't get errors on 'SELECT * ...'

In fact, you do not need to remove empty arrays. This situation only occurs when a file has just one line, like `{"items": []}`.

If the file contains more than one line, such as:

```
{"items": []}
{"items": [1,2]}
```

then arrow_json::reader::infer_json_schema will use the second line to infer the data type of the items. Therefore, you should not encounter errors when using "SELECT *".

SELECT *  should return 
```
+--------+
| items  |
+--------+
| []     |
| [1, 2] |
+--------+
```

**Comment by BubbaJoe** [comment]
@jiangzhx Exactly, actually my particular dataset only contained empty arrays for some fields. So this is what i meant.

**Comment by tustvold** [comment]
I wonder if we should just add support for nulls, this seems like an unfortunate edge case

**Comment by jiangzhx** [comment]
> I wonder if we should just add support for nulls, this seems like an unfortunate edge case

@tustvold  I have submitted a pull request to support empty arrays. I hope you have some time and could maybe help with the code review?

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4106
