### ISSUE TITLE
Rust Analyzer does not work for object_store files

### ISSUE THREAD

**Issue by berkaysynnada** [apache/arrow-rs#4115]
**Which part is this question about**

Rust analyzer does not work for [object_store](https://github.com/apache/arrow-rs/tree/master/object_store) files. I don't have any problem with other files. Also for Datafusion, in the files under datafusion-cli, the extension does not work. Rust Analyzer Client and Language Server do not show any error. I have tried reinstalling and to work with pre-release versions.

**Describe your question**

**Additional context**

**Comment by tustvold** [comment]
I don't personally use rust-analyser, but some brief searching suggests you can manually configure the two workspaces, with something like

```
{
    "rust-analyzer.linkedProjects": [
        "object_store/Cargo.toml",
    ]
}
```

It would appear rust-analyser auto-configuration fails for multiple workspaces in the same directory hierarchy.

**Comment by berkaysynnada** [comment]
> I don't personally use rust-analyser, but some brief searching suggests you can manually configure the two workspaces, with something like
> 
> ```
> {
>     "rust-analyzer.linkedProjects": [
>         "Cargo.toml"
>         "object_store/Cargo.toml",
>     ]
> }
> ```
> 
> It would appear rust-analyser auto-configuration fails for multiple workspaces in the same directory hierarchy.

Thanks, it worked
