### ISSUE TITLE
[object_store] Retry requests on connection error

### ISSUE THREAD

**Issue by kindly** [apache/arrow-rs#4119]
**Describe the bug**

When doing mulitipart uploads to s3, for larger files, I was getting lots of reqwest/hyper errors, e.g  `broken pipe`, `tls handshake errors` and `channel closed`, meaning some large files become almost impossible to upload.  This could be due to flaky internet or slow processing of data being uploaded.

**To Reproduce**

Hard to reproduce as they were intermittent failures and required large files or delays between requests.

**Expected behaviour**

Ability for the put requests/multiplart uploads to be retried for more failure cases.

**Additional context**

Pull request #4120 does retries for more cases, which fixes these issues for me.

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4119](https://github.com/apache/arrow-rs/issues/4119)
