### ISSUE TITLE
Truncate ColumnIndex ByteArray Statistics

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4126]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
The usecase is if your data has very large binary or string columns (e.g. you have single elements which are 1MB for instance). Perhaps this is embedded logs or some other large payload. 

Without some care, since the parquet statistics have actual column values stored (for their min/max) such columns can cause the resulting metadata / statistics to be pathologically large as a giant value can be stored as the min and max values in the stats for each page

Thankfully, the spec has a solution!

From the [specification](https://github.com/apache/parquet-format/blob/master/PageIndex.md)

> These may be the actual minimum and maximum values found on a page, but can also be (more compact) values that do not exist on a page. For example, instead of storing ""Blart Versenwald III", a writer may set min_values[i]="B", max_values[i]="C". This allows writers to truncate large values and writers should use this to enforce some reasonable bound on the size of the index structures.

**Describe the solution you'd like**

I would like `ColumnIndexBuilder` to provide an option to limit the maximum length of the generated column index statistics, set by WriterProperties. This should probably have a reasonable default of something like 128 bytes.

The specification isn't clear about whether truncation of column chunk statistics is valid, and so we should ensure that they are not truncated to avoid incompatibility.

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
Marking as "good first issue" as I think this should be a relatively straightforward addition

**Comment by AdamGS** [comment]
If no one else picket this up, I might take a stab at it.

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #4389
