### ISSUE TITLE
CSV Schema More Flexible Timestamp Inference

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4131]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The schema inference logic for CSV currently only infers timestamps matching the regex `^\d{4}-\d\d-\d\d[T ]\d\d:\d\d:\d\d.\d{1,9}$`. This is significantly more restrictive than the [parsing](https://docs.rs/arrow-cast/latest/arrow_cast/parse/fn.string_to_datetime.html) logic.

**Describe the solution you'd like**

Infer timestamp for all the types recognised by the [parsing](https://docs.rs/arrow-cast/latest/arrow_cast/parse/fn.string_to_datetime.html) logic

**Describe alternatives you've considered**

**Additional context**

#3744 #4129

**Comment by alamb** [comment]
Both https://github.com/apache/arrow-rs/issues/3744 https://github.com/apache/arrow-rs/issues/4129 are fixed -- I wonder if this ticket can also be closed

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4217
