### ISSUE TITLE
Fixed point decimal multiplication for DictionaryArray

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#4135]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We can do fixed point decimal multiplication for DecimalArray. We need to extend it to DictionaryArray.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4136
