### ISSUE TITLE
InMemory append API

### ISSUE THREAD

**Issue by berkaysynnada** [apache/arrow-rs#4152]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

InMemory implementation of ObjectStore does not have the append API. 

**Describe the solution you'd like**

We can implement an append function returning an object that implements AsyncWrite for InMemory appends.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #4153

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4152](https://github.com/apache/arrow-rs/issues/4152)
