### ISSUE TITLE
Extensible ObjectStore Authentication

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4163]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

All the cloud providers provide CLIs for interacting with their service offering, a number of these come with fairly convoluted configuration setups for sourcing credentials. By and large these do not follow any widely adopted standard, and are inordinately complex.

**Describe the solution you'd like**

Rather than implementing all the various different authentication options, a truly herculean task, we could provide an option to shell out the CLI to obtain the credentials. @roeap added this for Azure in https://github.com/apache/arrow-rs/pull/3698.

Both AWS and GCP support this with

```
aws sts get-session-token
gcloud auth print-access-token
```

This would provide an escape hatch for CLI tools, without requiring a large amount of custom tooling. It would also provide complete coverage of all the options, including functionality that is not supported yet in any Rust library (e.g. GCP workload federation). Finally it would allow for workloads to choose to maximise compatibility by explicitly opting into using CLI-generated credentials #4137

**Describe alternatives you've considered**

**Additional context**

https://github.com/apache/arrow-rs/pull/2891 added experimental support for AWS_PROFILE

https://github.com/apache/arrow-rs/issues/3797 tracks adding support for more complex GCP authentication

**Comment by alamb** [comment]
I recommend something more general than "shell" out -- perhaps we can provide an "Authorizer" or "GetCredential" trait. that would let people shell out to get the credentials if they wanted, as well as write whatever other integrations they wanted

**Comment by roeap** [comment]
> Perhaps we can provide an implementation of the trait that calls out to a CLI

Thats essentially how it is implemented for Azure :). There we have a `TokenCredential` trait, and all token based auth methods implement that trait - including the CLI based one. I guess we could just make that public and allow users to pass that to the builder.

That said, I do believe that configuring the CLI credential via an option on the builder is slightly more convenient and allows for an integration with the property-bag based configuration system we provide.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #4225

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4163](https://github.com/apache/arrow-rs/issues/4163)
