### ISSUE TITLE
Support extended pow arithmetic

### ISSUE THREAD

**Issue by izveigor** [apache/arrow-rs#4166]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
`arrow-arith` supports only `powf_scalar` function (`Float*Array ^ f*` (except `Float16Array`). I think it should also support power functions between integer and float arrays,  and also `powi_scalar` function for exponentiation between integer arrays and `u32`.

**Describe the solution you'd like**
New functions in `array-arith/arithmetic.rs`:
- `powi` (Support: `Int*Array ^ UInt32Array` and `UInt*Array ^ UInt32Array`)
- `powf` (Support: `Float*Array ^ Float*Array` (except: `Float16Array`)
- `powi_scalar` (Support: `Int*Array ^ u32` and `UInt*Array ^ u32`)

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4187
