### ISSUE TITLE
[parquet] add compression info to `print_column_chunk_metadata()`

### ISSUE THREAD

**Issue by SteveLauC** [apache/arrow-rs#4172]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I am trying to work on [(pqrs)Feature request: Compression algorithm information](https://github.com/manojkarthick/pqrs/issues/40)

**Describe the solution you'd like**
Add compression info in `parquet::schema::printer::print_column_chunk_metadata()`

```rust
    writeln!(out, "compression: {}", cc_metadata.compression());
```

**Describe alternatives you've considered**
An alternative way is that we maintain our own `print_column_chunk_metadaa()` in `pqrs` and have that implemented, but it would be great if this can be added in upstream.

**Additional context**
Related code snippet: https://github.com/apache/arrow-rs/blob/c4ac758e13cbd76651d16d06e786bdf7c04f902a/parquet/src/schema/printer.rs#L138-L149

**Comment by SteveLauC** [comment]
Let me file a PR for this:)

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #4176
