### ISSUE TITLE
Support `Interval` +/- `Interval`

### ISSUE THREAD

**Issue by izveigor** [apache/arrow-rs#4178]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
`arrow-rs` does not support arithmetic between intervals, which does not allow full use of these data types. 

The feature can be useful for the following situations:
- know the difference between one period of time and another
- calculate the total time of some action

That feature can also be used by `arrow-datafusion` for interval arithmetics.

**Describe the solution you'd like**
New functions for `IntervalYearMonthType`, `IntervalDayTimeType` and `IntervalMonthDayNanoType`:
- add_day_time
- add_year_months
- add_month_day_nano
- subtract_day_time
- subtract_year_months
- subtract_month_day_nano

The functions `add_dyn` and `substract_dyn` start to support arithmetic between `Intervals`.

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4179
