### ISSUE TITLE
Return Error on Invalid Config Value

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4191]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently if `AWS_CHECKSUM_ALGORITHM` is set to anything other than a capitilization of `sha256` `AmazonS3Builder::from_env` will panic.

Similarly non-truthy string values will be interpreted as `false`, which could lead to a confusing situation where a config value of "enabled" is interpreted as false.

**Describe the solution you'd like**

We should return an error for these

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4191](https://github.com/apache/arrow-rs/issues/4191)
