### ISSUE TITLE
Use XML API for GCS

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4209]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

GoogleCloudStorage currently uses a mix of the XML and JSON APIs. This is unfortunate and causes issues due to some functionality not being properly supported in the JSON APIs.

One challenge is fake-gcs-server lacks proper support for the XML APIs - https://github.com/fsouza/fake-gcs-server/issues/331

**Describe the solution you'd like**

Switch to using the XML API for GCS

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #4207

**Comment by onpaws** [comment]
Just wanted to say as a recent adopter of arrow-rs + GCS buckets, this PR will make an immediate difference for my project. Thank you :)

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4209](https://github.com/apache/arrow-rs/issues/4209)
