### ISSUE TITLE
Casting Timestamp to date is off by one day for dates before 1970-01-01

### ISSUE THREAD

**Issue by parthchandra** [apache/arrow-rs#4211]
If casting a negative number of micros/millis to date, the cast method divides by the number of (micro/milli)seconds to get the number of days from the beginning of the epoch. 
For a timestamp like `1969/12/31 23:59:59.995` (in millis) the number of millis from beginning of the epoch is -5. The division by the number of seconds in a day yields `0` which is off by one day since it should be `-1`. 

**To Reproduce**
```
select '1969-12-31 00:00:01'::timestamp::date;
+-----------------------------+
| Utf8("1969-12-31 00:00:01") |
+-----------------------------+
| 1970-01-01                  |
+-----------------------------+
```
**Expected behavior**
```
select '1969-12-31 00:00:01'::timestamp::date;
+-----------------------------+
| Utf8("1969-12-31 00:00:01") |
+-----------------------------+
| 1960-12-31                  |
+-----------------------------+
```

**Comment by comphead** [comment]
Reverified that on PG it works as @parthchandra expects

```
select '1969-12-31 00:00:01'::timestamp::date;


    date    
------------
 1969-12-31
(1 row)

```

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4323
