### ISSUE TITLE
Make ArrowArrayStreamReader Send

### ISSUE THREAD

**Issue by wjones127** [apache/arrow-rs#4222]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

ArrowArrayStreamReader is not Send, which makes is very difficult to work with in async contexts.

While [FFI_ArrowArrayStream](https://docs.rs/arrow/39.0.0/arrow/ffi_stream/struct.FFI_ArrowArrayStream.html) shouldn't be Sync, I do think it should be marked Send. From the [docs](https://arrow.apache.org/docs/format/CStreamInterface.html#thread-safety):

> The stream source is not assumed to be thread-safe. Consumers wanting to call `get_next` from several threads should ensure those calls are serialized.

**Describe the solution you'd like**

If `FFI_ArrowArrayStream` were marked `Send` and `ArrowArrayStreamReader` were refactored to hold the inner type in a Box rather than an Arc, then it would be `Send`.

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4232
