### ISSUE TITLE
ObjectStore::head Returns Directory for LocalFileSystem and Hierarchical Azure

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4230]
**Describe the bug**

ObjectStore::head returns an `ObjectMeta` for directories in `LocalFileSystem` and hierarchical azure namespaces

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #4231

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4230](https://github.com/apache/arrow-rs/issues/4230)
