### ISSUE TITLE
Have array_to_json_array support FixedSizeList 

### ISSUE THREAD

**Issue by dadepo** [apache/arrow-rs#4248]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Using `array_to_json_array` to convert an arrow `ArrayRef` into a `Vec` of Serde JSON fails if the `ArrayRef` is `FixedSizeList`

Looking at the source [here](https://docs.rs/arrow-json/latest/src/arrow_json/writer.rs.html#141-201) it looks like it is indeed missing handling of `FixedSizeList`

**Describe the solution you'd like**
It should be possible to use `array_to_json_array` to convert  `ArrayRef` into a `Vec` of Serde JSON

Version: `arrow-json = "39.0.0"`

**Comment by alamb** [comment]
Related discussion: https://github.com/apache/arrow-datafusion/discussions/6446
