### ISSUE TITLE
FlightSQL: Add helpers to create `CommandGetSqlInfo` responses (`SqlInfoValue` and builders)

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#4256]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
FlightSQL has several metadata APIs for a server to report its capabilities to the client. One such API is the `CommandGetSqlInfo` message that requires creating a DenseUnion (which is somewhat inconvenient in the Rust API):

https://github.com/apache/arrow/blob/f9324b79bf4fc1ec7e97b32e3cce16e75ef0f5e3/format/FlightSql.proto#L32-L43

@roeap  noted in https://github.com/apache/arrow-rs/pull/4250#issuecomment-1556724021 that some of the existing work we did in IOx could be used by other rust projects implementing FlightSQL:

https://github.com/influxdata/influxdb_iox/blob/31b881376057bf7e50381519c4f5c9e15c1aee33/flightsql/src/sql_info/mod.rs

**Describe the solution you'd like**
1. Create a builder for SqlInfoValue responses in the arrow-rs flightsql implementation: https://github.com/apache/arrow-rs/tree/master/arrow-flight/src/sql
2. Add tests and docstrings showing how to use this builder
3. Update the example server https://github.com/apache/arrow-rs/blob/e2b9b1afebd45ab0dcdef260d662733bb3ac7d82/arrow-flight/examples/flight_sql_server.rs#L268-L276 to use this `SqlInfoBuilder`

I suggest following the model / copying code from IOx's [`SqlInfoList`](https://github.com/influxdata/influxdb_iox/blob/31b881376057bf7e50381519c4f5c9e15c1aee33/flightsql/src/sql_info/mod.rs) and [`SqlInfoValue`](https://github.com/influxdata/influxdb_iox/blob/31b881376057bf7e50381519c4f5c9e15c1aee33/flightsql/src/sql_info/value.rs)

**Describe alternatives you've considered**

**Additional context**
Marking this as a good first issue as it is well specified and the implementation already exists for inspiration

**Comment by alamb** [comment]
I made a PR with some more docs and tests: https://github.com/apache/arrow-rs/pull/4293

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4266
