### ISSUE TITLE
Add Builder for `FlightInfo` to make it easier to create new requests

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#4281]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
When implementing an Arrow Flight based service in Rust (as we did in IOx) it often took a substantial amount of reading in the spec to figure out how to construct the relevant messages

For example:
* How do you get an arrow `Schema` into the `bytes` you need in the message?
* what do you set `FlightInfo::total_bytes` to when responding to a FLightSQL command? 
* What should you sent the FlightEndpoints to?
* do I have to set the FlightDescriptor (protobuf generated code allows it being empty)

This adds additional friction to creating new Flight based services in Rust

**Describe the solution you'd like**
I would like a builder style API (with specific documentation) that helps people craft the correct, common  common case `FlightInfo` messages

```rust
let flight_info = FlightInfoBuilder::new()
  .with_schema(schema),
  .with_ticket(ticket)
  .build()
```

**Describe alternatives you've considered**

**Additional context**
related discussion on https://github.com/apache/arrow-rs/pull/4266/files#r1205473722

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4266
