### ISSUE TITLE
FLightSQL: add helpers to create `CommandGetCatalogs`, `CommandGetSchemas`, and `CommandGetTables` requests

### ISSUE THREAD

**Issue by roeap** [apache/arrow-rs#4295]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

FlightSQL has several APIs for a server to report available catalogs, db schemas, and tables. These APIs require filtering and sorting against the available information, which can be re-used across implementations.

**Describe the solution you'd like**

IOx contains implementations to simplify handling these requests that could benefit other rust implementations.

**Describe alternatives you've considered**

Not doing it.

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4296

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow-flight'} from #4296
