### ISSUE TITLE
export function parquet_to_array_schema_and_fields

### ISSUE THREAD

**Issue by sundy-li** [apache/arrow-rs#4298]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We want to use some low-level APIs to read parquet files by rowgroup (such as `build_array_reader`), but this function need `field: Option<&ParquetField>` that can only constructed by `parquet_to_array_schema_and_fields`.

**Describe the solution you'd like**

Export function `parquet_to_array_schema_and_fields `

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #4307
