### ISSUE TITLE
[parquet] Not following the spec for TIMESTAMP_MILLIS legacy converted types

### ISSUE THREAD

**Issue by sergiimk** [apache/arrow-rs#4308]
**Describe the bug**

[Parquet spec prescribes](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#deprecated-timestamp-convertedtype) that for backward compatibility the legacy converted type `TIMESTAMP_MILLIS` should be interpreted as logical type `TimestampType (isAdjustedToUTC = true, unit = MILLIS)`, but that's currently not the case.

**To Reproduce**

Read a modern Parquet file with schema:
```
message x {
  REQUIRED INT64 system_time (TIMESTAMP(MILLIS,true));
}
````
observe data type `Timestamp(Millisecond, Some("UTC"))`

Read an old Parquet file with schema:
```
message x {
  REQUIRED INT64 system_time (TIMESTAMP_MILLIS);
}
````
observe data type: `Timestamp(Millisecond, None)`

`TIMESTAMP_MILLIS` gets incorrectly interpreted as naive/local timestamp.

**Expected behavior**

Because spec prescribes that `TIMESTAMP_MILLIS` should be interpreted as `TIMESTAMP(MILLIS,true)` I expected to see a timestamp with UTC timezone.

**Additional context**

[These lines seem to be the source of the problem](https://github.com/apache/arrow-rs/blob/ea008922445d84d957cf3f89df793187c22d82d8/parquet/src/arrow/schema/primitive.rs#L209-L214)

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #4309
