### ISSUE TITLE
FlightSQLServer detect if connection is closed

### ISSUE THREAD

**Issue by sundy-li** [apache/arrow-rs#4314]
**Which part is this question about**

Is there any way for FlightSQLServer to actively detect that the client has closed the connection?

**Describe your question**

We are using Flight-SQL in databend.  We also supported MySQL protocol which is TCP based, the server could destroy the session(rust's drop ) when the client closes the connection because it shares the same connection with the server.

But for Flight-SQL, we use a background thread to destroy the inactive session in the map, which is inconvenient. https://github.com/datafuselabs/databend/blob/6659761f9a0fa19887caf3691de75c651b88fce1/src/query/service/src/servers/flight_sql/flight_sql_service/service.rs#L155-L158 

Seems FlightSQL is http2 based, if it's using multiplexing it could be a single connection with streams for the communication.

**Additional context**

**Comment by tustvold** [comment]
You might want to ask on the arrow mailing list how people handle this, gRPC is a message oriented transport not a connection oriented transport, and so it doesn't really have a clear notion of a connection... In fact most libraries purposefully don't expose the TCP lifecycle to allow for transparent reconnection, and non-TCP based transports
