### ISSUE TITLE
Question: Could we move `dict_id, dict_is_ordered` into DataType?

### ISSUE THREAD

**Issue by jackwener** [apache/arrow-rs#4325]
**Which part is this question about**
I have a question about dict_id dict_is_ordered in Field , why them isn’t in DataType ?

**Describe your question**
I think `dict_id: i64, dict_is_ordered: bool,` is just used for Dictionary.

We can move them into `DataType`, like `Dictionary(i64, bool, Box<DataType>, Box<DataType>)`

**Additional context**

**Comment by tustvold** [comment]
What would be the advantage of such a change? I'm mainly just thinking that this will result in a huge amount of code churn, and so would need quite a strong justification

**Comment by jackwener** [comment]
> What would be the advantage of such a change? 

`dict_id: i64, dict_is_ordered: bool` is useless when `DataType` isn't `Dictionary`, so look like they shouldn't be put in `Field`. And it will waste a little memory.

> I'm mainly just thinking that this will result in a huge amount of code churn, and so would need quite a strong justification

I agree with it, I also think we don't have a particularly strong motivation to change it.

I also have a question. If we change it, does this create incompatible behavior?
