### ISSUE TITLE
Make SerializedRowGroupReader::new() Public

### ISSUE THREAD

**Issue by burmecia** [apache/arrow-rs#4330]
**Describe the bug**

The initialize function `SerializedRowGroupReader::new()` is private and cannot be accessed.

**To Reproduce**

1. Go to docs: https://docs.rs/parquet/40.0.0/parquet/file/serialized_reader/struct.SerializedRowGroupReader.html
2. Cannot find `new()` function in the doc page

**Expected behavior**

`SerializedRowGroupReader::new()` must be public so it can be accessed from outside.

**Additional context**

N/A

**Comment by tustvold** [comment]
This is intentional and not a bug, it is intended that people make use of SerializedFileReader to get access to a row group reader. We could probably document this better. Is there a particular reason you wish to instantiate a SerializedRowGroupReader?

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #4331
