### ISSUE TITLE
Refactor CAST tests to use new cast array syntax

### ISSUE THREAD

**Issue by comphead** [apache/arrow-rs#4336]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Going forward we should use new concise syntax as mentioned https://github.com/apache/arrow-rs/pull/4323#discussion_r1211898332

**Describe the solution you'd like**

Refactor `cast.rs` tests to use new concise syntax instead of `downcast_ref` directly. 

**Describe alternatives you've considered**

**Additional context**

Followup on https://github.com/apache/arrow-rs/pull/4323#discussion_r1211898332

**Comment by Weijun-H** [comment]
Could I pick this ticket up?
