### ISSUE TITLE
Update Flight Implementation Status

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4337]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We should update https://arrow.apache.org/docs/status.html with the parts of Flight and FlightSQL that are supported

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

FYI @avantgardnerio @alamb

**Comment by alamb** [comment]
I can take a shot at this.

also cc @roeap

**Comment by Michael-J-Ward** [comment]
triage: Should this be completed now that the arrow docs have been updated?

https://github.com/apache/arrow/pull/39959

**Comment by alamb** [comment]
Yes thank you 🙏
