### ISSUE TITLE
Release 41.0.0 of arrow/arrow-flight/parquet/parquet-derive

### ISSUE THREAD

**Issue by iajoiner** [apache/arrow-rs#4346]
Follow on from #4246
 
* Planned Release Candidate: 2023-06-02
* Planned Release and Publish to crates.io: 2023-06-05
 
 
 Items (from [dev/release/README.md](https://github.com/apache/arrow-rs/blob/master/dev/release/README.md)):
 
* [x]  PR to update version and CHANGELOG: 
* [ ]  Release candidate created:
* [ ]  Release candidate approved:
* [ ]  Release to crates.io:
* [ ] Draft a datafusion upgrade PR
* [ ]  Make ticket for next release
 
 
 See full list here: [40.0.0...master](https://github.com/apache/arrow-rs/compare/40.0.0...master)

**Comment by alamb** [comment]
I would like to volunteer to do the logistics needed for this release like create tarballs and running the vote -- is that ok @iajoiner  and @tustvold ?

**Comment by alamb** [comment]
🤔  it seems like we already have released 41. https://crates.io/crates/arrow/41.0.0

 We probably should close this ticket and file a new one for 42. I'll do so later in the week of no one beats me to it
