### ISSUE TITLE
compute::ord kernel for getting min and max of two scalar/array values

### ISSUE THREAD

**Issue by Jimexist** [apache/arrow-rs#4347]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
https://docs.rs/arrow-arith/latest/arrow_arith/aggregate/index.html perhaps?

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4355
