### ISSUE TITLE
Default ObjectStore::get_range Doesn't Apply Range to GetResult::File

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4350]
**Describe the bug**

The default implementation of `ObjectStore::get_range` added in #4212 incorrectly handles if `GetResult::File` is returned, instead returning the entire byte range. This is incorrect

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4350](https://github.com/apache/arrow-rs/issues/4350)
