### ISSUE TITLE
RecordReader::skip_records Is Incorrect for Repeated Columns

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4368]
**Describe the bug**

Whilst investigating https://github.com/apache/arrow-rs/issues/4365 I realised the implementation of `RecordReader::skip_records` has two issue:

* When counting buffered records to skip, it incorrectly handles the case of the final decoded record, as it doesn't know where it ends
* When skipping buffered records, it doesn't remove the corresponding data from the decoded data, resulting in skipped rows appearing in the output

This only manifests for repeated columns, because `read_records` only reads the necessary number of levels in the case of a non-repeated column, and therefore it never reads more than necessary.

**To Reproduce**

https://github.com/apache/arrow-rs/issues/4365 

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #4376
