### ISSUE TITLE
Default FlightSqlService Implementations

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4372]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Noticed whilst working on https://github.com/apache/arrow-datafusion/pull/6374, this trait is now substantial and requires a significant amount of boilerplate to implement a service, that may not be interested in a significant portion of the API surface

**Describe the solution you'd like**

I would like default implementations that return `Status::unimplemented` for all the trait methods

**Describe alternatives you've considered**

We could only provide impls for some subset, but this is likely more confusing than just providing blanket implementations for all of them

**Additional context**

FYI @alamb @avantgardnerio

**Comment by alamb** [comment]
I think the trait in question is https://docs.rs/arrow-flight/41.0.0/arrow_flight/sql/server/trait.FlightSqlService.html (and it has 40 methods!)

**Comment by avantgardnerio** [comment]
SGTM. 

Another potential cleanup avenue would be exposing higher level abstractions (i.e. the ability to provide an object representing over database structure), then the 20 of these are `get_flight_info XXX` might be consolidated into one, with less onerous demands on the implementer.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4485
