### ISSUE TITLE
Support `millisecond` and `microsecond` functions

### ISSUE THREAD

**Issue by izveigor** [apache/arrow-rs#4374]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
`arrow-rs` supports functions `second`, `second_dyn`, `nanosecond`, `nanosecond_dyn`, but does not `microsecond`, `microsecond_dyn`, `millisecond` and `millisecond_dyn`.

I think these features will be useful for the users who want to know specific microsecond and millisecond.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

https://arrow.apache.org/docs/cpp/compute.html

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4375
