### ISSUE TITLE
Support `Date` - `Date` kernel

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#4383]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
While implementing date/time arithmetic in DataFusion (https://github.com/apache/arrow-datafusion/pull/6578) @jackwener  found lack of Date - Date support in arithmetic kernels

**Describe the solution you'd like**
I would like kernels that can subtract 
1. `Date32Array - Date32Array` and produce an `IntervalYearMonthArray`
2. `Date64Array - Date64Array` and produce `IntervalMonthDayNanoArray`

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
This likely overlaps with #3999

**Comment by sum12** [comment]
was planning to give this a try
> Date32Array - Date32Array and produce an IntervalYearMonthArray

iiuc  `IntervalYearMonthArray` cannot represent interval in of 1 day, for example. How about `IntervalDayTimeType` with millis set to 0.

**Comment by tustvold** [comment]
This will need to wait until after #4465 which reimplements the arithmetic kernels
