### ISSUE TITLE
Parquet error: Not all children array length are the same! when using RowSelection to read a parquet file

### ISSUE THREAD

**Issue by davidsaslawsky-trackinsight** [apache/arrow-rs#4396]
**Describe the bug**

There's a `parquet error Not all children array length are the same!` when trying to read the attached parquet file with a `RowSelection` that selects more than one row.  

**To Reproduce**
Run the attached rust program to read the parquet file.

This triggers the error:
```rust
let selection = RowSelection::from(vec![
    RowSelector::skip(10),
    RowSelector::select(1),
    RowSelector::skip(1),
    RowSelector::select(1),
    RowSelector::skip(7),
    RowSelector::select(1)
]);
```

However without `RowSelection` or with a trivial row selection this works:
```rust
let selection = RowSelection::from(vec![
    RowSelector::skip(10),
    RowSelector::select(1)
]);
```

**Expected behavior**

Should not have the error.

**Additional context**

If you remove the `ticker` column from the file, you no longer have the exception however the row selection is wrong. The first `RowSelection` above returns 11 rows, not 3 as expected in that case.

I'm new at Rust so I haven't been able to narrow the problem further, please let me know if there's anything I can do to help.

[Archive.zip](https://github.com/apache/arrow-rs/files/11714804/Archive.zip)

**Comment by AdamGS** [comment]
Seems to be related to [this](https://github.com/apache/arrow-rs/issues/4368) issue which was recently fixed, try pulling a version of the `parquet` crate from the `master` branch.
