### ISSUE TITLE
Code search is not working in github

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#440]
**Describe the bug**
I want to be able to search for code in the github repo

**To Reproduce**
Search for code that exists in arrow-rs, for example [`get_batch`](https://github.com/apache/arrow-rs/blob/master/parquet/src/util/bit_util.rs#L516):  https://github.com/apache/arrow-rs/search?q=get_batch

Returns no results:
![Screen Shot 2021-06-09 at 2 08 30 PM](https://user-images.githubusercontent.com/490673/121406473-2ca9c680-c92c-11eb-8d0b-2e096b713057.png)

**Expected behavior**
Github search with a link to that function

**Additional context**

**Comment by alamb** [comment]
I don't know what the root cause of this is, but I have found a workaround which is to use sourcegraph search: https://sourcegraph.com/github.com/apache/arrow-rs

**Comment by tustvold** [comment]
This appears to be working now
