### ISSUE TITLE
GCP doesn't fetch public objects

### ISSUE THREAD

**Issue by vrongmeal** [apache/arrow-rs#4417]
**Describe the bug**

When trying to fetch public objects, GCP returns the 401 code. This is because the object store sends the `Authorization: Bearer `. Even when the bearer is empty, it tries to authorize.

**To Reproduce**

Try fetching a public object with the header:

```sh
$ curl -H 'Authorization: Bearer ' https://storage.googleapis.com/<bucket>/<object-location>
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AuthenticationRequired</Code><Message>Authentication required.</Message></Error>

# whereas without the header this works
$ curl https://storage.googleapis.com/<bucket>/<object-location>
```

**Expected behavior**

Should be able to access the public object.

**Additional context**

Once the object is fetched, sometimes GCP caches and returns the result even with the header. But this is not reliable.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #4418

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4417](https://github.com/apache/arrow-rs/issues/4417)
