### ISSUE TITLE
Equality kernel where null==null gives true 

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-rs#4438]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Some operations might need that `null==null` gives back `true` instead of null.

https://github.com/apache/arrow-datafusion/pull/6724

**Describe the solution you'd like**

An equality kernel with null==null -> `true`. 

**Describe alternatives you've considered**

In the PR https://github.com/apache/arrow-datafusion/pull/6724 an alternative implementation can be found:

```rust
            let eq: BooleanArray = eq_dyn(left, right)?;

            let left_is_null = is_null(left)?;
            let right_is_null = is_null(right)?;

            or_kleene(&and(&left_is_null, &right_is_null)?, &eq)
```

**Additional context**

**Comment by tustvold** [comment]
I believe this is the same as `IS NOT DISTINCT FROM`, I'll see what I can come up with

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4716
