### ISSUE TITLE
No longer builds on x86 -- issue with `half` version 2.3.0

### ISSUE THREAD

**Issue by ChristopherRabotin** [apache/arrow-rs#4448]
**Describe the bug**

Arrows no longer builds on the x86 platform since version 2.3.0 of `half`. Related bug report here: https://github.com/starkat99/half-rs/issues/93 .

**To Reproduce**

+ Use arrows version 42
+ Build on x86
+ Failure.

**Expected behavior**

Successful build.

**Additional context**

Github action example of failure: https://github.com/nyx-space/nyx/actions/runs/5370562609/jobs/9742729371?pr=191

**Comment by tustvold** [comment]
The upstream issue appears to have been closed, is this still an issue?

**Comment by ChristopherRabotin** [comment]
Just rising here, and I'm glad to hear that it was quickly fixed upstream.
