### ISSUE TITLE
object_store/InMemory: Make `clone()` non-async

### ISSUE THREAD

**Issue by Turbo87** [apache/arrow-rs#4496]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Some parts of our test suite are not (yet) using async everywhere and we have a need to `clone()` the `InMemory` object store to use it in several parts of the application. The fact that `clone()` is currently async makes this unnecessarily hard, especially since nothing within the `clone()` fn is actually async code anymore.

**Describe the solution you'd like**

I propose to remove the `async` keyword from the `clone()` fn, and then to implement the `Clone` trait since afterwards the function signature should match the one from the trait.

**Describe alternatives you've considered**

The only alternative is keeping the obsolete async keyword on the function. 

**Additional context**

The `async` keyword was there in the [very first commit](https://github.com/influxdata/object_store_rs/commit/56483a119cacbe9814a88b0a4e127b2c95a405de) to the project because at that point an async `RwLock` from tokio was used instead of the `parking_lot` variant which no longer requires the `async` keyword.

**Comment by Turbo87** [comment]
On second thought I'm even more confused by the current `clone()` implementation now. It seems that it copies the data instead of creating a second instance of `InMemory` sharing the backing store with the first instance. Maybe it would be better to rename `clone()` to e.g. `fork()` and use a derived `Clone` implementation, which just cheaply clones the `Arc` of the backing store. 🤔

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #4497

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4496](https://github.com/apache/arrow-rs/issues/4496)
