### ISSUE TITLE
Cannot cast string '2021-01-02' to value of Date64 type

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#4512]
**Describe the bug**
Cannot cast string '2021-01-02' to value of Date64 type

I can cast it to `Date32` type for some reason

**To Reproduce**
This is using `datafusion-cli`

```
❯ select arrow_cast('2021-1-2', 'Date64');
Optimizer rule 'simplify_expressions' failed
caused by
Arrow error: Cast error: Cannot cast string '2021-1-2' to value of Date64 type
❯ select arrow_cast('2021-1-2', 'Date32');
+------------------+
| Utf8("2021-1-2") |
+------------------+
| 2021-01-02       |
+------------------+
1 row in set. Query took 0.000 seconds.
```

I found a workaround to cast the string first to `Date32` and then `Date64`
```
❯ select arrow_cast(arrow_cast('2021-1-2', 'Date32'), 'Date64');
+---------------------+
| Utf8("2021-1-2")    |
+---------------------+
| 2021-01-02T00:00:00 |
+---------------------+
1 row in set. Query took 0.000 seconds.
```

**Expected behavior**
I expect to be able to parse '2021-01-02'  successfully as Date64

**Additional context**

**Comment by tustvold** [comment]
The issue appears to be that the cast kernel implements its own parsing logic independent from the logic contained in Parser. I will get a PR to fix this
