### ISSUE TITLE
object_store: Uploading empty file to S3 results in "411 Length Required"

### ISSUE THREAD

**Issue by Turbo87** [apache/arrow-rs#4514]
**Describe the bug**

When using the S3 implementation of `object_store` a `put()` call with an empty content fails on the server side with a "411 Length Required" error:

> Generic S3 error: response error "\<?xml version="1.0" encoding="UTF-8"?>
\<Error>\<Code>MissingContentLength\</Code>\<Message>You must provide the Content-Length HTTP header.\</Message>\</Error>", after 0 retries: HTTP status client error (411 Length Required) for url (https://s3.us-west-2.amazonaws.com/...)

**To Reproduce**

```rs
s3_store.put(&"foo".into(), Bytes::new()).await.unwrap()
```

**Expected behavior**

The call succeeds and uploads an empty file to S3.

**Additional context**

- https://github.com/rust-lang/crates.io/issues/6793

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #4518

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4514](https://github.com/apache/arrow-rs/issues/4514)
