### ISSUE TITLE
object_store: Export `ClientConfigKey` and make the `HttpBuilder` more consistent with other builders

### ISSUE THREAD

**Issue by thehabbos007** [apache/arrow-rs#4515]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

This feature request is related to using the `http` feature of the `object_store` crate for fetching data. The `HttpBuilder` is slightly different from the other builders in its usage. It doesn't have a `with_config` method nor is the keys used for configuring the client, `ClientConfigKey`, being exported for usage in other libraries/applications.

This would allow `polars` to implement the `http` target in a way that's consistent with the other cloud targets, see https://github.com/pola-rs/polars/blob/96b0e07e75a882eaed7be05e619307bc144aa5b4/polars/polars-core/src/cloud.rs

**Describe the solution you'd like**

Exporting `ClientConfigKey` and adding a `HttpBuilder::with_config` method that can set individual options so it's consistent with the other cloud provider client builders.

**Describe alternatives you've considered**

There could be a distinct `HttpConfigKey`, but since the `ClientOptions` struct is already exported, it would make sense to export the keys too.

The `with_config` method isn't strictly required, but it does make things more consistent in usage.

**Additional context**

This came up while trying to add `http` to polars. This change request isn't from a polars team member, but I thought the changes here would be welcome :)

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #4516

**Comment by winding-lines** [comment]
@tustvold any chance we can get this published to crates.io at some point?

**Comment by tustvold** [comment]
Apologies, been a bit swamped recently, will try to get a release cut soon

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4515](https://github.com/apache/arrow-rs/issues/4515)
