### ISSUE TITLE
Exports are not sufficient for configuring some object stores, for example minio running locally

### ISSUE THREAD

**Issue by winding-lines** [apache/arrow-rs#4530]
**Describe the bug**
When running minio locally for testing the default setup is to use http. The object_store crate supports this setup, however one of the required symbols is not exported.

**To Reproduce**

In order to connect with minio over http you'd use code similar to the following

```
use object_store::AmazonS3ConfigKey as Key;
use object_store::ClientConfigKey; // <- export missing
use object_store::aws::AmazonS3Builder;

def foo() {
        
  let out builder = AmazonS3Builder().new();
  builder = builder.with_config(Key::AccessKeyId, &cred.access_key.unwrap());
  builder = builder.with_config(Key::SecretAccessKey, &cred.secret_key.unwrap());
  builder = builder.with_config(Key::Client(ClientConfigKey::AllowHttp), &"true".into());
  builder = builder.with_config(Key::Endpoint, &"http://localhost:9000".into()));
}
```

**Expected behavior**
The code should compile, but it does not because of the private ClientConfigKey.

**Additional context**

**Comment by winding-lines** [comment]
Looks like this was already fixed as part of https://github.com/apache/arrow-rs/issues/4515

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #4531

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4530](https://github.com/apache/arrow-rs/issues/4530)
