### ISSUE TITLE
[object_store] Derive Clone for AmazonS3 struct

### ISSUE THREAD

**Issue by itytophile** [apache/arrow-rs#4534]
Hi.
I want to be able to clone an `AmazonS3` instance to easily pass the instance between tasks. As `AmazonS3` is using `Arc` internally, adding `Clone` to `#[derive(Debug)]` should do the trick.

Is this possible? Thanks.

**Comment by tustvold** [comment]
Is there a reason to not just wrap `AmazonS3` in `Arc`? Whilst for S3 I can appreciate there is limited ambiguity, for stores like `InMemory` the shared nature of the underlying clone could be surprising, whereas the behaviour of `Arc` is clearly communicated

**Comment by itytophile** [comment]
Wrapping `AmazonS3` in `Arc` adds a level of indirection that can be avoided. I think this is quite common for libraries to implement `Clone` for a struct that contains `Arc`; `Client` in the `reqwest` crate or `Pool<T>` in the `sqlx` crate.
