### ISSUE TITLE
Convenience method to create `DataType::List` correctly

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#4544]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The embedded field type of a List must always be called "item" -- you can see this is done everywhere in the arrow-rs codebase that a `DataType::List` is created: https://github.com/search?q=repo%3Aapache%2Farrow-rs+%22%5C%22item%5C%22%22&type=code

While working on https://github.com/influxdata/influxdb_iox/pull/8247 I had to make this change

```diff
-       DataType::List(Arc::new(Field::new("state", dt.clone(), false))),
+       DataType::List(Arc::new(Field::new("item", dt.clone(), true))),
```

to align the type with expected

Having to do this is both verbose/annoying but more to the point means we are exposing some sort of implementation detail that must be [cargo-culted](https://en.wikipedia.org/wiki/Cargo_cult_programming) in many places  

**Describe the solution you'd like**
I would like a method like this (with good documentation) to create a 

```rust
let dt = DataType::new_list(DataType::Float64, true);
```

That would do the same thing as 

```rust
let df = DataType::List(Arc::new(Field::new("item", DataType::Float64, true))),
```

cc @tustvold for your thoughts

**Describe alternatives you've considered**
Do nothing

**Additional context**

**Comment by alamb** [comment]
This is a nice self contained project for someone if they wanted to try their hand at the arrow codebase

**Comment by tustvold** [comment]
It isn't a requirement that the name be "item", it is purely a convention. If code is relying on this, that code is incorrect

**Comment by alamb** [comment]
> It isn't a requirement that the name be "item", it is purely a convention. If code is relying on this, that code is incorrect

At the very least perhaps we can agree that the arrow-rs codebase has very little test coverage of a `DataType::List` that does not follow the convention (I found one example)

**Comment by fansehep** [comment]
it seems just add a pub fn in arrow-schema/src/datatype.rs ? and the default name is "item" ?
