### ISSUE TITLE
Like with wildcards fail to match fields with new lines.

### ISSUE THREAD

**Issue by nl5887** [apache/arrow-rs#4547]
**Describe the bug**
When having new lines in fields, LIKEs with wildcards (%data%) fail to match those fields.

**To Reproduce**
Have a field with like:
```
test
Air
```

LIKE '%Air%' won't match the field

**Expected behavior**
LIKE '%Air%' should match the field.

**Additional context**
This can be fixed by adding the s flag to the regex.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4548
