### ISSUE TITLE
Make object_store::multipart public

### ISSUE THREAD

**Issue by yjshen** [apache/arrow-rs#4569]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Discovered the remarkable pull request apache/arrow-datafusion#6987, which enables writing data through the Object Store API with AsyncWriter. After checking the put_multipart implementation, it appears that `object_store::multipart` is the missing piece needed to extend HDFS support for this functionality.

**Describe the solution you'd like**

Make several interface parts of `object_store::multipart` public

**Describe alternatives you've considered**

Don't do this.

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #4570

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4569](https://github.com/apache/arrow-rs/issues/4569)
