### ISSUE TITLE
[BUG] CAST f64 to Decimals gives incorrect result

### ISSUE THREAD

**Issue by comphead** [apache/arrow-rs#4577]
**Describe the bug**

CAST f64 to Decimals gives incorrect result
**To Reproduce**

Both Decimal128, Decimal256 are wrong
```
    #[test]
    fn test_cast() {
        let array = Float64Array::from(vec![6.4053151420411946063694043751862251568]);
        let array = Arc::new(array) as ArrayRef;
        let casted_array = cast_with_options(
            &array,
            &DataType::Decimal256(38, 37),
            &CastOptions {
                safe: true,
                format_options: FormatOptions::default(),
            },
        ).unwrap();

        let casted_array = casted_array.as_primitive::<Decimal256Type>();
        assert_eq!(casted_array.value_as_string(0), "6.4053151420411946063694043751862251568");
    }

thread 'cast::tests::test_cast' panicked at 'assertion failed: `(left == right)`
  left: `"6.4053151420411954619510965656866521088"`,
 right: `"6.4053151420411946063694043751862251568"`', arrow-cast/src/cast.rs:7839:9
```

**Expected behavior**

Should cast correctly

**Additional context**

Found on https://github.com/apache/arrow-datafusion/issues/7121

**Comment by viirya** [comment]
As I replied in https://github.com/apache/arrow-datafusion/issues/7121, I'm not sure if this can be treated as a bug.

**Comment by comphead** [comment]
As discussed in original ticket, the problem was that DF forcibly casted numeric literals to float before cast to decimal, which lead to precision loss. DF has a config key that regulates how numeric literal will be parsed, it was float by default
