### ISSUE TITLE
bug(parquet): Disabling global statistics but enabling for particular column breaks reading

### ISSUE THREAD

**Issue by ozgrakkurt** [apache/arrow-rs#4587]
If I write files with:
```
.set_statistics_enabled(EnabledStatistics::None)
.set_column_statistics_enabled("block_number".into(), EnabledStatistics::Page)
```

When I query it with datafusion or just `parquet::ParquetRecordBatchReaderBuilder`, it errors with: "missing offset index"

Seems like it is skipping writing offset indices if page statistics are globally disabled?

I would expect, if it doesn't write offset indices then it shouldn't try to filter pages by statistics, also it should be documented that `set_column_statistics_enabled` doesn't override global settings in this way.

**Comment by tustvold** [comment]
This appears to have been fixed by https://github.com/apache/arrow-rs/pull/4567, https://github.com/apache/arrow-rs/pull/4589 adds a test for this

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #4589
