### ISSUE TITLE
Datum Based String Kernels

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4595]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently arrow-string provides methods like

* contains_dyn
* contains_utf8_scalar_dyn
* contains_utf8

We should update it to provide a single `contains` method taking the `Datum` abstraction, and deprecate and eventually remove the old APIs.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alexandreyc** [comment]
I'm starting to work on this one 👍

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4766

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow-flight'} from #4732
