### ISSUE TITLE
bug: Parquet writer missing row group metadata fields such as `compressed_size`, `file offset`.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/arrow-rs#4610]
**Describe the bug**

Parquet writer missing row group metadata fields such as `compressed_size`, `file offset`.

**To Reproduce**

**Expected behavior**

It should fill these fields.

**Additional context**

These fields are important for other readers.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #4636
