### ISSUE TITLE
[object_store] when Create a AmazonS3 instance  work with MinIO without set endpoint got error MissingRegion

### ISSUE THREAD

**Issue by jiangzhx** [apache/arrow-rs#4617]
**Which part is this question about**

library api

**Describe your question**

When I tested creating an AmazonS3 instance to work with MinIO, it appeared that providing the region endpoint may be unnecessary. 
In fact, both .
`with_region("") and .with_region("   ")`
worked equally well.

maybe we can set a default value for with_region or add a example for work with minIO

**Additional context**

**Comment by tustvold** [comment]
See https://github.com/apache/arrow-rs/issues/3827#issuecomment-1468880201

The region is technically required for request signing, although it would appear some stores don't care what it is set to. I'm not sure if there is a general recommendation for what minio says it should be set to?

**Comment by jiangzhx** [comment]
Thank you for your response. Perhaps I could add an example to introduce how to use MinIO in the object_store.

i will close this issue.
