### ISSUE TITLE
Empty lists in FixedSizeListArray::try_new is not handled

### ISSUE THREAD

**Issue by smiklos** [apache/arrow-rs#4623]
**Describe the bug**

Passing 0 as size to FixedSizeListArray::try_new panics with division by zero.

**To Reproduce**

Call FixedSizeListArray::try_new with 0 as size. 

**Expected behavior**

If FixedSizeListArrays should not hold empty values, an ArrowError::InvalidArgumentError should be returned, otherwise it should be possible to construct it with 0 as length of lists contained within.

**Additional context**

**Comment by smiklos** [comment]
Can't seem to find forbidding empty values in the specification.

**Comment by tustvold** [comment]
What is the point of a FixedSizeListArray with size of 0, it can never hold any data? It's just a worse NullArray?

**Comment by tustvold** [comment]
We should make this work, as you say the specification doesn't forbid it, although the utility of such a construction alludes me 😅

**Comment by smiklos** [comment]
I'll make a pr

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4626
