### ISSUE TITLE
Add AzureConfigKey::ContainerName

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4629]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

There is currently no way to configure the container name for MicrosoftAzure using environment variables

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #4686

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4629](https://github.com/apache/arrow-rs/issues/4629)
