### ISSUE TITLE
Better explanation in docs for Dictionary field encoding using RowConverter

### ISSUE THREAD

**Issue by JayjeetAtGithub** [apache/arrow-rs#4639]
[This](https://github.com/apache/arrow-rs/blob/c2b0aa5fae68eedfadd9285a0b4d76e48dc29a6d/arrow-row/src/lib.rs#L272-L321) part of the docs explains the process of encoding dictionary fields to the Row format using the RowConverter. But, the part which explains and illustrates how the mappings are generated and used, isn't much clear or might be out of date.

Current illustration:
```
/// ┌──────────┐                 ┌─────┐
/// │  "Bar"   │ ───────────────▶│ 01  │
/// └──────────┘                 └─────┘
/// ┌──────────┐                 ┌─────┬─────┐
/// │"Fabulous"│ ───────────────▶│ 01  │ 02  │
/// └──────────┘                 └─────┴─────┘
/// ┌──────────┐                 ┌─────┐
/// │  "Soup"  │ ───────────────▶│ 05  │
/// └──────────┘                 └─────┘
/// ┌──────────┐                 ┌─────┐
/// │   "ZZ"   │ ───────────────▶│ 07  │
/// └──────────┘                 └─────┘
///
///                           ┌─────┬─────┬─────┬─────┐
///    "Fabulous"             │ 01  │ 03  │ 05  │ 00  │
///                           └─────┴─────┴─────┴─────┘
///
///                           ┌─────┬─────┬─────┐
///    "ZZ"                   │ 01  │ 07  │ 00  │
///                           └─────┴─────┴─────┘
///
///                           ┌─────┐
///     NULL                  │ 00  │
///                           └─────┘
///
///      Input                  Row Format
///
```

I presume, the correct illustration might be,

```
/// ┌──────────┐                 ┌─────┐
/// │  "Bar"   │ ───────────────▶│ 01  │
/// └──────────┘                 └─────┘
/// ┌──────────┐                 ┌─────┬─────┐
/// │"Fabulous"│ ───────────────▶│ 01  │ 02  │
/// └──────────┘                 └─────┴─────┘
/// ┌──────────┐                 ┌─────┐
/// │  "Soup"  │ ───────────────▶│ 05  │
/// └──────────┘                 └─────┘
/// ┌──────────┐                 ┌─────┐
/// │   "ZZ"   │ ───────────────▶│ 07  │
/// └──────────┘                 └─────┘
///
///                           ┌─────┬─────┬─────┬─────┐
///    "Fabulous"             │ 01  │ 01  │ 02  │ 00  │
///                           └─────┴─────┴─────┴─────┘
///
///                           ┌─────┬─────┬─────┐
///    "ZZ"                   │ 01  │ 07  │ 00  │
///                           └─────┴─────┴─────┘
///
///                           ┌─────┐
///     NULL                  │ 00  │
///                           └─────┘
///
///      Input                  Row Format
///
```

**Comment by JayjeetAtGithub** [comment]
@tustvold Is the above guess correct ? If yes, then I can raise a PR. Thanks.

**Comment by tustvold** [comment]
Looks correct to me

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4657

**Comment by jayhan94** [comment]
This blog is still not correct: https://arrow.apache.org/blog/2022/11/07/multi-column-sorts-in-arrow-rust-part-2/

<img width="784" alt="Image" src="https://github.com/user-attachments/assets/20be60cf-a568-4446-8687-a898776ab3e0" />

**Comment by alamb** [comment]
> This blog is still not correct: https://arrow.apache.org/blog/2022/11/07/multi-column-sorts-in-arrow-rust-part-2/
> 
> <img alt="Image" width="784" src="https://private-user-images.githubusercontent.com/194190421/420266570-20be60cf-a568-4446-8687-a898776ab3e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEzNDc3MzAsIm5iZiI6MTc0MTM0NzQzMCwicGF0aCI6Ii8xOTQxOTA0MjEvNDIwMjY2NTcwLTIwYmU2MGNmLWE1NjgtNDQ0Ni04Njg3LWE4OTg3NzZhYjNlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwN1QxMTM3MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTZlZGRmMDkzZDdiZDM2OGNhNDBhMjIwMTY3MGZmMGY1M2FiOTIxOWU3MTg5ZWJkNTkyNWE3YWI1MGIzNGMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BglTQm75miGN6By_q6RjJVZJz9dbH-raPuDBiziPpC4">

Thanks for the report @jayhan94 . Could you propose a fix?

https://github.com/apache/arrow-site/blob/main/_posts/2022-11-07-multi-column-sorts-in-arrow-rust-part-2.md

Thanks!

**Comment by jayhan94** [comment]
> > This blog is still not correct: https://arrow.apache.org/blog/2022/11/07/multi-column-sorts-in-arrow-rust-part-2/
> > <img alt="Image" width="784" src="https://private-user-images.githubusercontent.com/194190421/420266570-20be60cf-a568-4446-8687-a898776ab3e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEzNDc3MzAsIm5iZiI6MTc0MTM0NzQzMCwicGF0aCI6Ii8xOTQxOTA0MjEvNDIwMjY2NTcwLTIwYmU2MGNmLWE1NjgtNDQ0Ni04Njg3LWE4OTg3NzZhYjNlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwN1QxMTM3MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTZlZGRmMDkzZDdiZDM2OGNhNDBhMjIwMTY3MGZmMGY1M2FiOTIxOWU3MTg5ZWJkNTkyNWE3YWI1MGIzNGMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BglTQm75miGN6By_q6RjJVZJz9dbH-raPuDBiziPpC4">
> 
> Thanks for the report [@jayhan94](https://github.com/jayhan94) . Could you propose a fix?
> 
> https://github.com/apache/arrow-site/blob/main/_posts/2022-11-07-multi-column-sorts-in-arrow-rust-part-2.md
> 
> Thanks!

I raise a pr: https://github.com/apache/arrow-site/pull/616 @alamb

**Comment by alamb** [comment]
The fix has been applied: https://github.com/apache/arrow-site/pull/616#issuecomment-2708826128

Thank you @jayhan94
