### ISSUE TITLE
Decimal PrimitiveArray change datatype after try_unary 

### ISSUE THREAD

**Issue by jackwener** [apache/arrow-rs#4644]
**Describe the bug**

**To Reproduce**
```rs
        let a = Decimal128Array::from(vec![1, 3, -44, 2, 4])
            .with_precision_and_scale(9, 6)
            .unwrap();

        let f: PrimitiveArray<Decimal128Type> = a.unary(|i| i.add(1));
```

datatype from (9, 6) -> (38, 10)

**Expected behavior**

**Additional context**

**Comment by viirya** [comment]
That is default datatype. In `unary`, it doesn't keep parameter of datatype e.g. precision/scale and timezone, I think.
