### ISSUE TITLE
`filter_record_batch` should support filtering record batch without columns

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-rs#4647]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
In DataFusion, I would like to pass an empty record batch without columns to `filter_record_batch`.
Currently, this errors.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4648
