### ISSUE TITLE
CI Failing On Packed SIMD

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4651]
**Describe the bug**

Compilation of packed_simd appears to be failing on the latest nightly

**To Reproduce**

https://github.com/apache/arrow-rs/actions/runs/5770622516/job/15643845432?pr=4650

**Expected behavior**

**Additional context**

**Comment by tustvold** [comment]
Upstream report - https://github.com/rust-lang/packed_simd/issues/356

**Comment by jhorstmann** [comment]
This is probably already fixed by https://github.com/rust-lang/packed_simd/pull/350 (and released as [0.3.9](https://crates.io/crates/packed_simd/0.3.9))

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4654
