### ISSUE TITLE
API improvement: `batches_to_flight_data` forces clone

### ISSUE THREAD

**Issue by amunra** [apache/arrow-rs#4656]
The API is pretty inconsistent, sometimes requiring a `Schema` and sometimes a `SchemaRef`.

For example I hold a `SchemaRef`, but `batches_to_flight_data` requires a `Schema`, forcing me to create a clone of the ref counted object.

Instead, the function should just take a `&Schema`.

```rust
pub fn batches_to_flight_data(
    schema: Schema,
    batches: Vec<RecordBatch>,
) -> Result<Vec<FlightData>, ArrowError> {
    let options = IpcWriteOptions::default();
    let schema_flight_data: FlightData = SchemaAsIpc::new(&schema, &options).into();
                                                          ^___ it's borrowed later anyways!
```

**Comment by jackwener** [comment]
Make sense to me
