### ISSUE TITLE
Double free in C Stream Interface

### ISSUE THREAD

**Issue by wjones127** [apache/arrow-rs#4659]
**Describe the bug**

Got a double free when consuming a stream and trying to return the error. Right now the C Stream Interface import tries to take ownership of the error string, but once the release callback is called that string gets freed.

https://github.com/apache/arrow-rs/blob/f16ceedf981c7230167ff858eabb9a8cdc87ffda/arrow/src/ffi_stream.rs#L317-L327

From [the C stream interface docs](https://arrow.apache.org/docs/format/CStreamInterface.html#c.ArrowArrayStream.get_last_error):

> The returned pointer is only guaranteed to be valid until the next call of one of the stream’s callbacks. The character string it points to should be copied to consumer-managed storage if it is intended to survive longer.

**To Reproduce**

**Expected behavior**

We should probably clone the string as suggested by the interface docs.

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4660
