### ISSUE TITLE
[Question] equal don't need `lhs_start` `rhs_start` `len`

### ISSUE THREAD

**Issue by jackwener** [apache/arrow-rs#4675]
**content**

when I investigate #4637, I read code about `equal` of `arrow-data/src/equal`.

I find `lhs_start` `rhs_start` `len` look like is useless, these parameters have never been used.

**Comment by jackwener** [comment]
cc @viirya @tustvold @alamb

**Comment by tustvold** [comment]
These parameters are very important for nested equality, in particular for lists

**Comment by jackwener** [comment]
thanks @tustvold

**Comment by viirya** [comment]
Yea, not sure what you mean they are useless. They are used in `list.rs`, for example.
