### ISSUE TITLE
object_store documentation is broken

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#4683]
**Describe the bug**
I was trying to render the docs while working on https://github.com/apache/arrow-rs/pull/4682 and I hit an error

```
error: unresolved link to `ObjectStore::copy_if_not_exists`
  --> src/aws/copy.rs:20:32
   |
20 | /// Configure how to provide [`ObjectStore::copy_if_not_exists`] for [`AmazonS3`]
   |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no item named `ObjectStore` in scope
   |
note: the lint level is defined here
  --> src/lib.rs:18:9
   |
18 | #![deny(rustdoc::broken_intra_doc_links, rustdoc::bare_urls, rust_2018_idioms)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: unresolved link to `AmazonS3`
  --> src/aws/copy.rs:20:72
   |
20 | /// Configure how to provide [`ObjectStore::copy_if_not_exists`] for [`AmazonS3`]
   |                                                                        ^^^^^^^^ no item named `AmazonS3` in scope
   |
   = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

error: unresolved link to `ObjectStore::copy_if_not_exists`
  --> src/aws/copy.rs:27:19
   |
27 |     /// If set, [`ObjectStore::copy_if_not_exists`] will perform a normal copy operation
   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no item named `ObjectStore` in scope

```

This appears to have been added in https://github.com/apache/arrow-rs/pull/4239 but I couldn't find any CI jobs that check the object_store docs

**To Reproduce**
```shell
cd object_store
cargo doc --all-features
```

**Expected behavior**
Docs should build cleanly, and that should be verified by CI

**Additional context**

**Comment by tustvold** [comment]
This is intentional, docs.rs is built with all features - https://github.com/apache/arrow-rs/blob/master/object_store/Cargo.toml#L30

Conditionally compiling links based on feature flags is... Pretty grim

**Comment by alamb** [comment]
> This is intentional, docs.rs is built with all features - https://github.com/apache/arrow-rs/blob/master/object_store/Cargo.toml#L30

I ran `cargo doc --all-features` and it still failed 🤔

**Comment by tustvold** [comment]
Oh... In that case this must be fallout from splitting object_store into its own crate :+1:

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #4684
