### ISSUE TITLE
Implement parsing for ParquetWriterOptions

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#4693]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
We are  implementing configurable parquet writing in DataFusion

We want to be able to allow users to specify the parquet writing options (like compression) via a string like

```
set parquet.writer_version = 2.0
set parquet.compression = zstd(5)
```

**Describe the solution you'd like**
Implement [`FromStr`](https://doc.rust-lang.org/std/str/trait.FromStr.html) for the following structures, with some tests. 
- [ ] [Encoding](https://docs.rs/parquet/45.0.0/parquet/format/struct.Encoding.html)
- [ ] [Compression](https://docs.rs/parquet/45.0.0/parquet/basic/enum.Compression.html#)
- [ ] [WriterVersion](https://docs.rs/parquet/45.0.0/parquet/file/properties/enum.WriterVersion.html#)
- [ ] [EnabledStatistics](https://docs.rs/parquet/45.0.0/parquet/file/properties/enum.EnabledStatistics.html#)

Each of these can be done via a separate PR

The basic code can probably be ported from DataFusion here and add some unit tests: https://github.com/apache/arrow-datafusion/blob/ed85abbb878ef3d60e43797376cb9a40955cd89a/datafusion/core/src/datasource/file_format/parquet.rs#L13 

Bonus points for good error messages that give example values (like "Invalid encoding. Valid values: plain_dictionary, rle, etc

**Describe alternatives you've considered**

**Additional context**

@devinjdangelo  implemented parsing for these in https://github.com/apache/arrow-datafusion/pull/7244 however, I think these features could be more generally useful to others

**Comment by fansehep** [comment]
Looks you want the last like this:
```rust
let writer_properties = WriterProperties::from_str("
  set parquet.writer_version = 2.0
  set parquet.compression = zstd(5)").unwrap();
```

I want to try it. and should we really need the prefix word  'set' and `parquet.*` ?

**Comment by alamb** [comment]
> I want to try it. 

Hi @fansehep  -- thank you.

> should we really need the prefix word 'set' and parquet.* ?

No.  I am sorry for the confusion, the `set ...` terminology is from DataFusion. This ticket in arrow-rs only covers the parsing of the values

so for example, we would implement `FromStr` for https://docs.rs/parquet/45.0.0/parquet/format/struct.Encoding.html would allow something like this:

```rust
// call `parse` to implement FromStr
let encoding: Encoding = "PLAIN".parse().unwrap();
// call parse again, case insensitive
let encoding: Encoding = "plain".parse().unwrap();
```

**Comment by fansehep** [comment]
> so for example, we would implement `FromStr` for https://docs.rs/parquet/45.0.0/parquet/format/struct.Encoding.html would allow something like this:例如，我们为 https://docs.rs/parquet/45.0.0/parquet/format/struct.Encoding.html 实现 `FromStr` 将允许这样的事情：
> 
> ```rust
> // call `parse` to implement FromStr
> let encoding: Encoding = "PLAIN".parse().unwrap();
> // call parse again, case insensitive
> let encoding: Encoding = "plain".parse().unwrap();
> ```

Thanks for your help. 😃

**Comment by alamb** [comment]
> Thanks for your help. 😃

Thank YOU!

**Comment by raulcd** [comment]
This one seems to be finished by:
- https://github.com/apache/arrow-rs/pull/4938
@alamb is there anything missing from what you were expecting? Can we close it?

**Comment by alamb** [comment]
I agree this looks reasonable to me.

Thanks @raulcd and @fansehep
