### ISSUE TITLE
Support references in i256 arithmetic ops

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#4694]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Got `cannot add &i256 to &i256` while working with i256 value.

**Describe the solution you'd like**

Make i256 arithmetic operations support references.

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4692
