### ISSUE TITLE
bug: DataType's contains method should consider decimal's precision and scale.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/arrow-rs#4708]
**Describe the bug**

```rust
let a = DataType::Decimal(28, 10);
let b = DataType::Decimal(20, 10);
assert!(a.contains(b));
```

The above assertation failed, but a is a superset of b. 

**To Reproduce**

See above code.

**Expected behavior**

It should not fail.

**Additional context**

**Comment by viirya** [comment]
I think `contains` checks superset only for nested type. For primitive types, the function simply checks two types are same or not. How do you define "contains" between two primitive types?

**Comment by liurenjie1024** [comment]
The definition of supertype is kind of confusing, I think sth like compatible type maybe better.
