### ISSUE TITLE
Improve the performance of "DictionaryValue" row encoding

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#4712]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We are consider using the "don't use dictionary interning" in DataFusion for high cardinality columns: https://github.com/apache/arrow-datafusion/issues/7200#issuecomment-1679274520

@tustvold  mentioned this mode could be made faster

**Describe the solution you'd like**
Review and optimize `Code::DictionaryValues`

https://github.com/apache/arrow-rs/blob/b810e8f207bbc70294b01acba4be32153c18a6ab/arrow-row/src/lib.rs#L437C14-L437C14

Perhaps this could be made faster: https://github.com/apache/arrow-rs/blob/b810e8f207bbc70294b01acba4be32153c18a6ab/arrow-row/src/lib.rs#L1417 

(I am not sure)

**Describe alternatives you've considered**
There may not be any way to make this faster, but I wanted to file the ticket as follow on to the meeting

**Additional context**

**Comment by alamb** [comment]
For the record, this was fixed b/c we deleted the code that it tracked optimizing 🔥

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4819

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow-flight'} from #4819
