### ISSUE TITLE
Why do not have Time32MicrosecondArray and Time32NanosecondArray

### ISSUE THREAD

**Issue by ZENOTME** [apache/arrow-rs#4722]
**Which part is this question about**

library api

**Describe your question**

There is Time32SecondArray, Time32MillisecondArray. But it doesn't have Time32MicrosecondArray and Time32NanosecondArray. 

**Additional context**

**Comment by ZENOTME** [comment]
I think this may should be a feature request.

**Comment by tustvold** [comment]
The arrow format doesn't contain such types

**Comment by ZENOTME** [comment]
Thanks! I thought that was missed.🤣 This issue can be closed now.
