### ISSUE TITLE
Add the repo to the `arrow` GitHub topic 

### ISSUE THREAD

**Issue by alippai** [apache/arrow-rs#473]
Maybe some other topics should be considered as well.

Context:
![image](https://user-images.githubusercontent.com/240729/122648830-351faf80-d12b-11eb-9c83-158c0453e6c9.png)

**Comment by ByteBaker** [comment]
@alamb @tustvold this seems like a tiny work. We should do this.

**Comment by alamb** [comment]
If you can figure out how to do it  that would be great

I would have expected the topic lists to be controllled by asf.yam here:  https://github.com/apache/infrastructure-asfyaml

However, I couldn't find any mention after a quick look

Maybe we have to file a JIRA ticket with apache INFRA 🤔

**Comment by ByteBaker** [comment]
Actually it's easier than that AFAIK. I've done it in a few of my repos as well. 

[Here's a reference](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics). Should take no more than a minute.

**Comment by alamb** [comment]
I don't have admin access to this repo so I don't seem to be able to follow the instructions

<img width="457" alt="Screenshot 2024-10-03 at 9 51 42 AM" src="https://github.com/user-attachments/assets/d2e9ce67-2729-4925-9721-02506ebf5307">

I don't fully understand how the repos are administered via apache

**Comment by ByteBaker** [comment]
If none of these work, then yes, we will have to file a ticket on ASF JIRA. Preferably a maintainer.

**Comment by alamb** [comment]
I found some example existing INFRA tickets: https://issues.apache.org/jira/browse/INFRA-17201?jql=%20text%20~%20%22ADD%20%20topic%20to%20repo%22

I filed one for Arrow: https://issues.apache.org/jira/browse/INFRA-26184

Thanks again for helping to clean up the ticket backlog @ByteBaker

**Comment by martin-g** [comment]
I think you are looking for `github > labels` in .asf.yaml.
Please see https://github.com/apache/avro-rs/blob/6484f21bf938f9e7dd528f69329d85c82995b36a/.asf.yaml#L24 for example

**Comment by ByteBaker** [comment]
> Thanks again for helping to clean up the ticket backlog @ByteBaker

Happy to help however little I can. :bow:

**Comment by alamb** [comment]
@martin-g  you are entirely correct -- it is even documented 🤦 : https://github.com/apache/infrastructure-asfyaml?tab=readme-ov-file#repository-features

I swear I looked for the feature before and did not find it, but clearly I did not or did not look hard enough. 

I have closed the JIRA ticket

Ok, so all that is needed for this issue is to make a PR to the `asf.yml` file in this repo to add the labels

**Comment by ByteBaker** [comment]
@alamb I'm taking this. Seems like an easy fix. What topics should I add? I'm thinking of `arrow`, `parquet`, `object-store`, `rust`. Anything else?

**Comment by alamb** [comment]
Those sound good to me - thank you @ByteBaker

**Comment by ByteBaker** [comment]
@alamb done. Please review.

**Comment by alamb** [comment]
The labels appear to have been successfully added:

![Screenshot 2024-10-06 at 7 30 16 AM](https://github.com/user-attachments/assets/8f428a90-8bd6-442a-87b2-a1a64e07fe3e)

Thanks again @ByteBaker
