### ISSUE TITLE
Support IntoPyArrow for impl RecordBatchReader

### ISSUE THREAD

**Issue by wjones127** [apache/arrow-rs#4730]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

It's a little awkward to export RBR, since you have to export them manually like:

```
let batch_reader = ...

let stream = FFI_ArrowArrayStream::new(Box::new(batch_reader));
let stream_reader = ArrowArrayStreamReader::try_new(stream).unwrap();

Ok(PyArrowType(stream_reader))
```

**Describe the solution you'd like**
As a convenience, we can implement `IntoPyArrow` for `RecordBatchReader`.

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'bug'} from #4751
