### ISSUE TITLE
LocalFileSystem Copy is not Atomic

### ISSUE THREAD

**Issue by chebbyChefNEQ** [apache/arrow-rs#4758]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

In most object stores `copy` operation is atomic, the file will not appear partially written.

However, on *nix, `copy` is usually not atomic and partially written file can appear.

**Describe the solution you'd like**

It would be nice if `object_store` had a `atomic_copy` api

**Describe alternatives you've considered**

I have been doing
```rust
store.copy(source, staging_file).await?;
store.rename(staging_file, dest).await?;
```

**Comment by tustvold** [comment]
This is actually a bug, ObjectStore operations should be atomic except for where explicitly stated otherwise (append)

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #4759

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4758](https://github.com/apache/arrow-rs/issues/4758)
