### ISSUE TITLE
LocalFileSystem Copy and Rename Don't Create Intermediate Directories

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4760]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by tustvold** [comment]
It looks like this might also impact HttpStore

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #4759

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4760](https://github.com/apache/arrow-rs/issues/4760)
