### ISSUE TITLE
Replace lexical

### ISSUE THREAD

**Issue by jqnatividad** [apache/arrow-rs#4774]
**Describe the bug**
There are recent advisories for lexical, mainly for soundness and being unmaintained.

https://rustsec.org/advisories/RUSTSEC-2023-0055.html
https://github.com/advisories/GHSA-c2hm-mjxv-89r4

**Expected behavior**
lexical replaced with alternative techniques/crates.

**Comment by tustvold** [comment]
Marking this help wanted and good first issue as it should be fairly straightforward to make the changes and check for regressions. Marking this as a feature request not a bug as AFAICT we do not use any of the impacted methods.

**Comment by tustvold** [comment]
Re-reading the advisory it appears to be for lexical, not lexical-core? Additionally I'm not seeing any soundness issues reported against lexical-core?

**Comment by tustvold** [comment]
Given this regresses performance, and the advisory is for lexical not lexical-core, I am closing this for now. Feel free to reopen if I am mistaken

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4785
