### ISSUE TITLE
Retry 409 conflict response

### ISSUE THREAD

**Issue by alextes** [apache/arrow-rs#4777]
**Describe the bug**
Our service sometimes hits a conflict while putting. We'd like to retry, the lib offers an option, but it appears a 409 response is not retried.

First it'd be fair to ask, should 409 generally be retried? For us the error literally says to do so, but perhaps in the general case it makes less sense. If it does make sense, it'd be lovely to have this feature. We're having to retry manually now. Not the worst, but definitely more complex than then simple `.with_retry(RetryConfig::default())` 

```
Generic S3 error: response error "<?xml version='1.0' encoding='UTF-8'?> <Error><Code>OperationAborted</Code><Message>A conflicting conditional operation is currently in progress against this resource. Please try again.</Message><RequestId>tx29de9421407d406eb7588-0064f72112</RequestId></Error>", after 0 retries: HTTP status client error (409 Conflict) for url (https://s3.gra.perf.cloud.ovh.net//block-submission-archive-prod/2023/09/05/12/29/7257748/0x26c152f988d9b3c47d5cbb0cf5571981b9684501df4713a8e0c18881a7124cdc.json.gz) Caused by: 0: response error "<?xml version='1.0' encoding='UTF-8'?> <Error><Code>OperationAborted</Code><Message>A conflicting conditional operation is currently in progress against this resource. Please try again.</Message><RequestId>tx29de9421407d406eb7588-0064f72112</RequestId></Error>", after 0 retries: HTTP status client error (409 Conflict) for url (https://s3.gra.perf.cloud.ovh.net//block-submission-archive-prod/2023/09/05/12/29/7257748/0x26c152f988d9b3c47d5cbb0cf5571981b9684501df4713a8e0c18881a7124cdc.json.gz) 1: HTTP status client error (409 Conflict) for url (https://s3.gra.perf.cloud.ovh.net//block-submission-archive-prod/2023/09/05/12/29/7257748/0x26c152f988d9b3c47d5cbb0cf5571981b9684501df4713a8e0c18881a7124cdc.json.gz
```

**To Reproduce**
Store an item which is already in the process of being stored.

**Expected behavior**
Retry 409.

**Additional context**
-

**Comment by tustvold** [comment]
What is the conditional operation being performed? From the HTTP specification

> The 409 (Conflict) status code indicates that the request could not be completed due to a conflict with the current state of the target resource. This code is used in situations where the user might be able to resolve the conflict and resubmit the request. The server SHOULD generate content that includes enough information for a user to recognize the source of the conflict.

In particular a 409 error code should not be being used for a transient error

> s3.gra.perf.cloud.ovh.net

Are you talking to S3 or some S3-compatible API?

**Comment by alextes** [comment]
Operation is (object_store.put)[https://docs.rs/object_store/latest/object_store/trait.ObjectStore.html#tymethod.put]. Nothing special. API is advertised as an S3 API. The specific error returned also appears in the Amazon S3 reference, so it appears to all be to spec. It also makes sense to me. If a user makes two calls to put at the same path at the same time the server can write both (broken), queue the second, abort either, or abort both. Apparently S3 elects to abort the second and reply 409. I'm guessing that's what the error is saying.

<img width="1552" alt="Screenshot 2023-09-06 at 08 39 31" src="https://github.com/apache/arrow-rs/assets/2011351/1cf0d12e-6a35-480f-a352-f73dc40fa97c">

imo a retry is reasonable here, but looking closer at the S3 reference, not on any 409, although `OperationAborted` looks ok to retry.

Reading the (HTTP 409 semantics)[https://www.rfc-editor.org/rfc/rfc9110#name-409-conflict]:
> The 409 (Conflict) status code indicates that the request could not be completed due to a conflict with the current state of the target resource. This code is used in situations where the user might be able to resolve the conflict and resubmit the request. The server SHOULD generate content that includes enough information for a user to recognize the source of the conflict.

After diving into this more deeply, I personally lean: we shouldn't retry this by default. It is totally reasonable to retry a concurrency conflict, but the user might want to be made aware instead of simply retrying and having one version overwrite the other. At most I'd suggest a feature where a user can specify what they want to be retried, and sets the `OperationAborted` code to be retried. I'd understand if maintainers feel that large a feature needs a bunch of upvotes first.

Side note: in our case I started ignoring 409s. I'm fairly sure these are duplicates in our case and storing one is enough. I'm having to string match the error now, it'd be neat if this lib could return its (AlreadyExists)[https://docs.rs/object_store/latest/object_store/enum.Error.html#variant.AlreadyExists] if it's correct `OperationAborted` is only a concurrent write error.

**Comment by tustvold** [comment]
I'm fairly certain S3 only returns OperationAborted for the bucket level APIs, concurrent upserts simply follow last writer wins. 

> If two PUT	requests are simultaneously made to the same key, the request with the	latest timestamp wins

From https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html#ConsistencyModel

I suspect your S3 compatible API is only vaguely compatible 😅

**Comment by alextes** [comment]
Interesting. I think we can close the issue here. If more people on other platforms show up with similar errors, especially AWS, it may be worth taking another look.

Thanks for the swift replies and a great lib 💛

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4777](https://github.com/apache/arrow-rs/issues/4777)
