### ISSUE TITLE
Automatically Cleanup LocalFileSystem Temporary Files

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4778]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

LocalFileSystem stages uploads to temporary paths ending with `#\d+`. These are ignored by all APIs exposed by LocalFileSystem, however, will still be visible to systems that interact with the filesystem directly, and will continue to consume disk space.

In most cases these will be cleaned up automatically, however, in the event of a crash or an aborted future, these files will be left around

**Describe the solution you'd like**

Some mechanism to automatically reap these files. In the abscence of some asynchronous drop mechanism for futures, it is unclear how this would work, but creating the ticket to track.

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
>  as Rust futures don't have an async Drop facility...

Maybe we could implement it with an `Arc<>` or use `TempDir` or some other library to handle the dropping for us

**Comment by tustvold** [comment]
> Maybe we could implement it with an Arc<> or use TempDir or some other library to handle the dropping for us

This would mean doing potentially blocking IO on the calling thread, whatever that may be... I'm not entirely sure what the implications of blocking when tokio drops a scheduled task, but I suspect they may be undesirable...

I did wonder about some sort of cleanup thread, but this then introduces all sorts of interesting race potential...

A further wrinkle that may also fall under this ticket, is we don't currently cleanup directories when perhaps we should

**Comment by DDtKey** [comment]
Just as an option to consider: is to [spawn blocking task](https://docs.rs/tokio/latest/tokio/task/fn.spawn_blocking.html#) and don't block on it. 
Technically file deletion still may fail, and drop won't guarantee that file is really deleted. 

Cleanup/sweeper thread/task is also possible solution - send a message to channel on `Drop` and do the deletion in this worker task. Probably even combination of both approaches: spawn_blocking task to delete a file and in case of fail send a message to cleanup task.

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4778](https://github.com/apache/arrow-rs/issues/4778)
