### ISSUE TITLE
[Parquet] Plain encoded boolean column chunks limited to 2048 values

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#48]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-6189

encoding::PlainEncoder::new creates a BitWriter with 256 bytes of storage, which limits the data page size that can be used. 

I suggest that in

{{impl Encoder<BoolType> for PlainEncoder<BoolType>}}

the return value of put_value is tested and the BitWriter flushed+cleared whenever it runs out of space.

**Comment by nevi-me** [comment]
Fixed by #443
