### ISSUE TITLE
`NullArray::is_null()` returns `false` incorrectly

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#4835]
**Describe the bug**
Found by @jonahgao  in https://github.com/apache/arrow-datafusion/pull/7568

**To Reproduce**
```rust
fn main() {
    let arr = NullArray::new(1);
    println!("arr.is_null(0): {}", arr.is_null(0))
}
```

Prints 
```
arr.is_null(0): false
```

**Expected behavior**
`NullArray::is_null()` should return true for all elements

**Additional context**

**Comment by alamb** [comment]
I think this is a good one for someone who wants to make a contribution to Arrow

**Comment by tustvold** [comment]
This was actually an intentional change in https://github.com/apache/arrow-rs/pull/4691/files#r1292317464

**Comment by alamb** [comment]
I think it is a bug -- having `NullArray::is_null()` return `false` seems simply incorrect, as well as being very confusing. 

Practically it means we can't use `is_null` to check if an element is null -- instead we have to also special case `DataType::is_null` as @jonahgao  did in https://github.com/apache/arrow-datafusion/pull/7568 

Maybe the problem is that `NullArray::new(1)` doesn't set up the buffers correctly 🤔

**Comment by tustvold** [comment]
> Maybe the problem is that NullArray::new(1) doesn't set up the buffers correctly 🤔

The difficulty is the arrow spec very clearly states that a `NullArray` has no buffers, including no null buffer. A NullArray technically isn't nullable, instead the only values are null... It is definitely strange...

**Comment by alamb** [comment]
Do you agree, from a user's perspective, that `NullArray::is_null()` return `false` is incorrect? I don't have any opinions on how to best fix this internally

**Comment by tustvold** [comment]
No, as per the standard a NullArray is not nullable, its values are just null

**Comment by alamb** [comment]
I don't understand what "is not nullable, its values are just null" means. 

https://arrow.apache.org/docs/format/Columnar.html#null-layout says

> "We provide a simplified memory-efficient layout for the Null data type where all values are null. In this case no memory buffers are allocated."

The  arrow-rs https://docs.rs/arrow/latest/arrow/array/trait.Array.html#method.is_null says
 says

> Returns whether the element at index is null. 

Therefore shouldn't `Array::is_null` return null for all values in a `NullArray` because all the values are null. 🤔  

I didn't find anything contradicting this position in the .fbs format
https://github.com/apache/arrow/blob/440dc92caa73ca67c8ca98cebfb74f33788150bf/format/Schema.fbs#L82-L83

**Comment by tustvold** [comment]
> Therefore shouldn't Array::is_null return null for all values in a NullArray because all the values are null. 🤔

The problem is doing this would be inconsistent with the values returned by `Array::nulls()`, so the following would not hold

```
assert_eq!(array.nulls().is_some_and(|n| n.is_null(idx)), array.is_null(idx));
```

**Comment by alamb** [comment]
> The problem is doing this would be inconsistent with the values returned by Array::nulls() so the following would not hold

If this property doesn't hold for some arrays it isn't an invariant, is it?

It is not clear that making `NullArray::is_null` return such a confusingly and seeming incorrect answer helps people understand the nuance

**Comment by tustvold** [comment]
> If this property doesn't hold for some arrays it isn't an invariant, is it?

It does hold, what you are proposing would break this :smile: 

> It is not clear that making NullArray::is_null return such a confusingly and seeming incorrect answer helps people understand the nuance

I don't disagree, but I also don't agree that making it return an incorrect value to make it fit people's logical models is a good solution either :smile:

**Comment by alamb** [comment]
> I don't disagree, but I also don't agree that making it return an incorrect value to make it fit people's logical models is a good solution either 😄

I think we disagree on what the correct value is 😆

**Comment by tustvold** [comment]
Currently the Array methods consistently return nullability as determined by the null buffer, irrespective of the array's logical value, i.e. if a dictionary value is null, this won't be reflected in is_null.

We could change this, but doing so would significantly regress performance, especially for RunArray.

I agree the current situation is unfortunate, but I do feel strongly that we should be consistent about what these methods mean.

**Comment by alamb** [comment]
Maybe we can solve this with some additional documentation 

Or perhaps we can add a function like `value_is_null()` that has the more intuitive definition

**Comment by tustvold** [comment]
> Maybe we can solve this with some additional documentation

I'm open to suggestions, the current docs are pretty clear imo - 
https://docs.rs/arrow-array/latest/arrow_array/array/trait.Array.html#method.is_null

https://docs.rs/arrow-array/latest/arrow_array/array/trait.Array.html#method.logical_nulls

**Comment by alamb** [comment]
PR is https://github.com/apache/arrow-rs/pull/4838
