### ISSUE TITLE
object-store: http shouldn't perform range requests unless `accept-ranges: bytes` header is present

### ISSUE THREAD

**Issue by universalmind303** [apache/arrow-rs#4839]
**Describe the bug**
if you have a remote file `https://somewhere.com/file.parquet` and your server does not support ranges as specified by the `accept-ranges: bytes` header, the object store should not try to perform range scans. 
**To Reproduce**

```rust
#[tokio::main]
async fn main() {
    let http = HttpBuilder::new().with_url("https://not.arealwebsite.com/file.parquet");
    let store = http.build().unwrap();
    let path = Path::default();
    let mut options = GetOptions::default();
    let some_range = 100..2000;
    options.range = Some(some_range);
    let data = store.get_opts(&path, options).await.unwrap();
}
```

**Expected behavior**
the range is ignored as the server doesn't specify it can handle it. 

**Additional context**

**Comment by tustvold** [comment]
The RFC would suggest this is not a requirement - https://www.rfc-editor.org/rfc/rfc9110#section-14.3

**Comment by universalmind303** [comment]
Hmm. If we'd error on a 200, wouldn't we have still performed the full request at that point though? 

... But i guess there's no good way to actually **_know_** if a server supports it without actually trying to perform the request.

**Comment by tustvold** [comment]
> performed the full request at that point though

We will have read the response headers but not streamed the majority of the request body
