### ISSUE TITLE
parquet `Row` construct `recordbatch`

### ISSUE THREAD

**Issue by smallzhongfeng** [apache/arrow-rs#4844]
**Which part is this question about**

**Describe your question**

**Additional context**

**Comment by smallzhongfeng** [comment]
For now, can we let parquet's row generate a reoctdBatch?

**Comment by tustvold** [comment]
I'm not sure I follow what you're requesting, there are native readers for reading parquet files as arrow RecordBatch?

**Comment by smallzhongfeng** [comment]
Thanks for you reply ! What I mean is that the data of the parquet file is read out through rowIter, and then after certain processing, it is converted into recordBatch or written into the parquet file. Is this currently allowed? @tustvold

**Comment by tustvold** [comment]
This is not currently supported, and I would be hesitant to add support for this.

What is the motivation for using RowIter and not just doing the processing on arrow data? If you can describe the processing I can suggest how you might achieve this? Keeping the data in a columnar representation will yield orders of magnitude better performance

**Comment by smallzhongfeng** [comment]
For our business needs, we have made corresponding changes to datafusion. Now in order to meet some needs, we need to merge multiple parquet files. At the same time, we need to maintain order (through a certain field) after merging, so that order can be achieved. Read to increase data processing speed for our business needs.

**Comment by tustvold** [comment]
> At the same time, we need to maintain order (through a certain field) after merging

This sounds like something [SortPreservingMergeExec](https://docs.rs/datafusion/latest/datafusion/physical_plan/sorts/sort_preserving_merge/struct.SortPreservingMergeExec.html) could handle for you?

**Comment by smallzhongfeng** [comment]
Add other question:

Could `SerializedFileReader` read hdfs path? Doesn't seem to work. @tustvold

**Comment by smallzhongfeng** [comment]
> > At the same time, we need to maintain order (through a certain field) after merging
> 
> This sounds like something [SortPreservingMergeExec](https://docs.rs/datafusion/latest/datafusion/physical_plan/sorts/sort_preserving_merge/struct.SortPreservingMergeExec.html) could handle for you?

This really help me. thanks!

**Comment by tustvold** [comment]
> Could SerializedFileReader read hdfs path? Doesn't seem to work.

You will likely want to use https://github.com/datafusion-contrib/datafusion-objectstore-hdfs

**Comment by smallzhongfeng** [comment]
I think not, I want to use like this https://docs.rs/parquet/latest/parquet/file/index.html#example-of-reading-an-existing-file, It seems not to support hdfs path, right?

**Comment by tustvold** [comment]
It won't support anything that isn't a real filesystem path, correct. If you wish to use a networked API such as HDFS you will need to provide an implementation of IO for this, or use one already implemented for you

**Comment by tustvold** [comment]
I'm going to close this as the question I believe has been answered, feel free to open a new ticket/discussion/get in touch on Discord if you have any further questions
