### ISSUE TITLE
make_primitive_scalar function loses DataType Internal information

### ISSUE THREAD

**Issue by JasonLi-cn** [apache/arrow-rs#4851]
**Describe the bug**

[make_primitive_scalar](https://github.com/apache/arrow-rs/blob/master/arrow-ord/src/comparison.rs#L55) function loses DataType Internal information.

Example:

Arg `d` is `DataType::Timestamp(TimeUnit::Millisecond, Some("+08:00"))`, but the DataType of the return ScalarValue is `DataType::Timestamp(TimeUnit::Millisecond, None)`, which loses the tz `Some("+08:00")`.

**To Reproduce**

**Expected behavior**

The DataType of the return ScalarValue is `DataType::Timestamp(TimeUnit::Millisecond, Some("+08:00"))`

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4852
