### ISSUE TITLE
object_store Azure Government Cloud functionality?

### ISSUE THREAD

**Issue by DnOberon** [apache/arrow-rs#4853]
**Which part is this question about**
object_store

**Describe your question**
Need to figure out how we can make object_store work with Azure government cloud, if at all.

**Comment by tustvold** [comment]
I'm afraid I'm not familiar with Azure Government Cloud but presuming it talks the same APIs it should just be a case of overriding the endpoint??

**Comment by DnOberon** [comment]
It should be roughly the same API yes - how do you override the endpoint? I must be missing something in the docs

**Comment by tustvold** [comment]
My mistake, I thought we already exposed this. Could you try out https://github.com/apache/arrow-rs/pull/4854 and report back. Should be something like

```
let store = MicrosoftAzureBuilder::new()
        .with_account("") // removed for security
        .with_access_key("") // removed for security
        .with_container_name("") // removed for security
        .with_endpoint("https://blob.core.usgovcloudapi.net")
        .build()
        .unwrap();
```

Although it might be 

```
let store = MicrosoftAzureBuilder::new()
        .with_account("") // removed for security
        .with_access_key("") // removed for security
        .with_container_name("") // removed for security
        .with_endpoint("https://<ACCOUNT>.blob.core.usgovcloudapi.net")
        .build()
        .unwrap();
```

I couldn't find docs for the government cloud functionality so not sure which it will be :sweat_smile:

**Comment by DnOberon** [comment]
@tustvold  this works perfectly! When can we get it merged in? :D

**Comment by tustvold** [comment]
As soon as another maintainer has reviewed it, likely a day or so

**Comment by DnOberon** [comment]
Awesome. Really helps us out, thank you.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #4854

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4853](https://github.com/apache/arrow-rs/issues/4853)
