### ISSUE TITLE
Is there a function similar to `make_primitive_scalar` available?

### ISSUE THREAD

**Issue by ACking-you** [apache/arrow-rs#4855]
Since [`xxx_dyn_scalar`](https://github.com/apache/arrow-rs/blob/master/arrow-ord/src/comparison.rs#L670) is deprecated, use [`arrow_ord::cmp::xxx`](https://github.com/apache/arrow-rs/blob/master/arrow-ord/src/cmp.rs#L73) instead as prompted. All now I need to use [`make_primitive_scalar`](https://github.com/apache/arrow-rs/blob/master/arrow-ord/src/comparison.rs#L55) to get Array, is there a similar function being exported?

**Comment by tustvold** [comment]
https://docs.rs/arrow-array/latest/arrow_array/array/struct.PrimitiveArray.html#method.new_scalar perhaps

**Comment by ACking-you** [comment]
> https://docs.rs/arrow-array/latest/arrow_array/array/struct.PrimitiveArray.html#method.new_scalar perhaps

Thanks, that's a great way to go. But it will ignore some type details, for example Timestamp type will be ignored for timezone, can Array be created correctly with known DataType?

**Comment by tustvold** [comment]
> Array be created correctly with known DataType

Sure

```
let scalar = Scalar::new(PrimitiveArray::from(vec![23]).with_timezone("+01:00"));
```

**Comment by ACking-you** [comment]
> > Array be created correctly with known DataType
> 
> Sure
> 
> ```
> let scalar = Scalar::new(TimestampNanosecondArray::from(vec![23]).with_timezone("+01:00"));
> let scalar = Scalar::new(Decimal128Array::from(vec![23]).with_data_type(...));
> ```

Thanks for the help, I have replaced it successfully!
