### ISSUE TITLE
Check precision overflow for casting floating to decimal

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#4865]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

As we now check precision overflow for casting string to decimal, it is good to have consistent behavior on floating too.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4866
