### ISSUE TITLE
Enable C Data Integration Tests

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4867]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

https://github.com/apache/arrow-rs/pull/4862#issuecomment-1735712205

**Describe the solution you'd like**

Integration test the C Data interface against other implementations

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
The logs also appear to contain

```
Rust does not support IPC

Rust does not support Flight
```

Which would appear to suggest there may be additional test coverage that isn't enabled properly

**Comment by pitrou** [comment]
Which logs exactly?

**Comment by tustvold** [comment]
For example https://github.com/apache/arrow-rs/actions/runs/6637236852/job/18031126773?pr=4988

**Comment by pitrou** [comment]
I also see messages such as "Skipping test because producer Java does not support IPC", which is clearly wrong.

**Comment by pitrou** [comment]
Oh, actually, the messages are confusing, but they simply correspond to the registered skips:
https://github.com/apache/arrow/blob/25e5d19b98511310e617c8b6e3c6ce6af39dfcde/dev/archery/archery/integration/datagen.py#L1787-L1870
and
https://github.com/apache/arrow/blob/25e5d19b98511310e617c8b6e3c6ce6af39dfcde/dev/archery/archery/integration/runner.py#L151-L162

**Comment by pitrou** [comment]
I'm going to give this a try.
