### ISSUE TITLE
ObjectStore multiple_append Test is Flaky

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4868]
**Describe the bug**

I have seen this test fail a couple of times in CI lately, most recently

https://github.com/apache/arrow-rs/actions/runs/6324042685/job/17172783580

This test was added in #3824 by @metesynnada 

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #4869

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4868](https://github.com/apache/arrow-rs/issues/4868)
