### ISSUE TITLE
creates_dir_if_not_present_append Test is Flaky

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4872]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

https://github.com/apache/arrow-rs/actions/runs/6329018079

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #4874

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4872](https://github.com/apache/arrow-rs/issues/4872)
