### ISSUE TITLE
parquet: Field Ids are not read from a Parquet file without serialized arrow schema

### ISSUE THREAD

**Issue by Samrose-Ahmed** [apache/arrow-rs#4877]
**Describe the bug**

If a parquet file that does not have the serialized arrow schema in the metadata (e.g. written by parquet-mr) is read by parquet crate and written back to parquet, the new file does not contain Parquet field ids.

**To Reproduce**

* Have Parquet file with field ids and no arrow serialized schema in metadata
* Read with `parquet` and write back to parquet file.
* New parquet file does not have field ids.

**Expected behavior**

New parquet file should have same field ids.

**Additional context**

related: #4702, #3548

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #4878
