### ISSUE TITLE
Conditional Put Support

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4879]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

All ObjectStores apart from S3 support conditional predicates on PUT. This is incredibly useful for building transactions on top of object storage. 

**Describe the solution you'd like**

I would like to propose a new put_opts call, in a similar vein to the existing get_opts. This would take a `PutOptions` similar to `GetOptions` and containing these predicates.

**Describe alternatives you've considered**

**Additional context**

#4754 would likely also benefit from a put_opts call

**Comment by tustvold** [comment]
So it turns out that despite [docs](https://cloud.google.com/storage/docs/request-preconditions) that would suggest it is supported, GCS doesn't support preconditions on write other than based on the version number. This is why we test :sweat_smile:

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4879](https://github.com/apache/arrow-rs/issues/4879)
