### ISSUE TITLE
Implement Take for UnionArray

### ISSUE THREAD

**Issue by avantgardnerio** [apache/arrow-rs#4882]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Presently, if a user tries to sort a DataFusion RecordBatchStream with a Union column, the receive an error:

```
Take not supported for data type UnionAray
```

**Describe the solution you'd like**

Implement Take for UnionArray

**Describe alternatives you've considered**

Leave it broken?

**Additional context**

N/A

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4883
