### ISSUE TITLE
Plans for supporting Extension Array to support Fixed shape tensor Array

### ISSUE THREAD

**Issue by haixuanTao** [apache/arrow-rs#4890]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently, there is no way easy way to support tensor data, which could be handy to do things like AI. And it seems that there is no tracking issue.

See: https://arrow.apache.org/docs/format/CanonicalExtensions.html
And example python implementation:
See: https://arrow.apache.org/docs/python/generated/pyarrow.ExtensionArray.html
 
**Describe the solution you'd like**
Implementation should be pretty straightforward as there already a Tensor Primitive Type.

**Additional context**
Related issue: https://github.com/apache/arrow-rs/issues/4805

**Comment by tustvold** [comment]
See https://github.com/apache/arrow-rs/issues/4472 for prior discussion on this topic

**Comment by JackKelly** [comment]
For anyone else who (like me) stumbles across this issue: `FixedShapeTensor`, and the other canonical extension types, were merged into `arrow-rs` in version 54.1.0  (Feb 2025).

- [Docs for `FixedShapeTensor`](https://arrow.apache.org/rust/arrow_schema/extension/canonical/fixed_shape_tensor/struct.FixedShapeTensor.html)
- PR #5822
