### ISSUE TITLE
Add option to FlightDataEncoder to always send dictionaries

### ISSUE THREAD

**Issue by alexwilcoxson-rel** [apache/arrow-rs#4895]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Per #3389 dictionaries are not supported over flight and right now they are cast into their underlying value type array.

**Describe the solution you'd like**
In lieu of the solution described on #3389 to provide initial support for dictionary arrays we can have opt in behavior to always send dictionaries with each record batch, replacing the previous

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow-flight'} from #4896
