### ISSUE TITLE
concat should preallocate for FixedSizeList

### ISSUE THREAD

**Issue by wjones127** [apache/arrow-rs#4897]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Right now, concat only pre-allocates for string, binary, dictionary and primitive arrays (IIUC):

https://github.com/apache/arrow-rs/blob/208da03979b2903c3182c20ef382b2895756380a/arrow-select/src/concat.rs#L129-L139

We use `FixedSizeList<{FloatType}>` as a storage type for tensor arrays, and not pre-allocating can get very expensive in plans. https://github.com/lancedb/lance/issues/1360

**Describe the solution you'd like**

Should provide capacities for fixed size list array. We likely need to add an entry to this enum:

https://github.com/apache/arrow-rs/blob/b46ea46aa65149fac763671b0adcb9c4e406ec11/arrow-data/src/transform/mod.rs#L323-L344

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
FYI @judahrand has made a PR for this: https://github.com/apache/arrow-rs/pull/5862
