### ISSUE TITLE
Support for reading JSON Array to Arrow

### ISSUE THREAD

**Issue by mnpw** [apache/arrow-rs#4905]
**Which part is this question about**

Reading from JSON to Arrow ([arrow_json](https://docs.rs/arrow-json/47.0.0/arrow_json/index.html)::[reader](https://docs.rs/arrow-json/47.0.0/arrow_json/reader/index.html#) module)

**Describe your question**

[arrow_json::reader](https://docs.rs/arrow-json/47.0.0/arrow_json/reader/index.html#) mentions
> This JSON reader allows **JSON line-delimited files** to be read into the Arrow memory model...

I'm curious as to why does the reader not support Array JSON type (`[{...}, {...}, {...}, ...]`)? I found that `arrow2` is able to [do so](https://jorgecarleitao.github.io/arrow2/io/json_read.html) but not `arrow-rs`.

**Additional context**
N/A

**Comment by tustvold** [comment]
It's a consequence of the formulation of the reader in terms of `RecordBatch` and by extension `Schema`, which correspond to JSON structs. The reader supports lists, just currently not at the root of the schema.

This could probably be relaxed without too much difficulty, is this important to your use-case or just an observation?

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4911
