### ISSUE TITLE
Support StructArray in Cast Kernel

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4908]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

There is currently extremely limited support for `StructArray` in the cast kernel

**Describe the solution you'd like**

We should support combinations of:

* Re-ordering columns
* Adding new nullable fields by adding entirely null columns as appropriate
* Casting columns within the array

**Describe alternatives you've considered**

**Additional context**

**Comment by fansehep** [comment]
Hi @tustvold I want to try this. Can you in detail and with specific reference to these three points? I am not very sure what you want.

**Comment by tustvold** [comment]
> Re-ordering columns

Casting from

```
DataType::Struct(Fields::new(vec![
    Field::new("a", DataType::Int32, false),
    Field::new("b", DataType::Int32, false),
])
```

To

```
DataType::Struct(Fields::new(vec![
    Field::new("b", DataType::Int32, false),
    Field::new("a", DataType::Int32, false),
])
```

> Adding new nullable fields by adding entirely null columns as appropriate

Casting from 
```
DataType::Struct(Fields::new(vec![
    Field::new("a", DataType::Int32, false),
    Field::new("b", DataType::Int32, false),
])
```

To

```
DataType::Struct(Fields::new(vec![
    Field::new("a", DataType::Int32, false),
    Field::new("b", DataType::Int32, false),
    Field::new("c", DataType::Int32, true),
])
```

> Casting columns within the array

```
DataType::Struct(Fields::new(vec![
    Field::new("a", DataType::Int32, false),
    Field::new("b", DataType::Int32, false),
])
```

To

```
DataType::Struct(Fields::new(vec![
    Field::new("a", DataType::Int32, true),
    Field::new("b", DataType::Int64, false),
])
```

> We should support combinations of:

So the eventual goal would be to support

```
DataType::Struct(Fields::new(vec![
    Field::new("a", DataType::Int32, false),
    Field::new("b", DataType::Int32, false),
])
```

To

```
DataType::Struct(Fields::new(vec![
    Field::new("c", DataType::Float32, true),
    Field::new("b", DataType::Int64, false),
    Field::new("a", DataType::Int32, false),
])
```

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4902

**Comment by tustvold** [comment]
Looks like https://github.com/apache/arrow-rs/pull/4985 prematurely closed this

**Comment by tustvold** [comment]
FYI @my-vegetable-has-exploded this is the broader issue

**Comment by alamb** [comment]
See https://github.com/apache/arrow-rs/pull/6726#issuecomment-2473316362 for a non trivial discussion about this API

**Comment by alamb** [comment]
For the reasons described in https://github.com/apache/arrow-rs/issues/6735, closing this in favor of a more generic solution
