### ISSUE TITLE
Get Object By Version

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4925]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Many stores support the notion of an object versioning:

* https://docs.aws.amazon.com/AmazonS3/latest/userguide/Versioning.html
* https://learn.microsoft.com/en-us/azure/storage/blobs/versioning-overview
* https://cloud.google.com/storage/docs/object-versioning

On update or delete, a new version of the object is created. Importantly the prior version remains accessible, which can be important for being able to provide consistency in the face of updates.

**Describe the solution you'd like**

I would like to add an optional version to `ObjectMeta` and `GetOptions`

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4925](https://github.com/apache/arrow-rs/issues/4925)
