### ISSUE TITLE
Support Not Signing Requests in AmazonS3

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4927]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

https://github.com/apache/arrow-datafusion/discussions/7770#discussioncomment-7259835

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

We already support something similar for GCS, although this is only used for testing

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #4929

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4927](https://github.com/apache/arrow-rs/issues/4927)
