### ISSUE TITLE
[FlightSQL] SubstraitPlan structure is not exported

### ISSUE THREAD

**Issue by amartins23** [apache/arrow-rs#4932]
**Describe the bug**
The arrow_flight crate defines commands that use substraitplans, but does not export the structure that holds those plans `SubstraitPlan` in the `arrow_flight::sql` module, making it impossible to use [CommandStatementSubstraitPlan](https://docs.rs/arrow-flight/latest/arrow_flight/sql/struct.CommandStatementSubstraitPlan.html#) and [ActionCreatePreparedSubstraitPlanRequest](https://docs.rs/arrow-flight/latest/arrow_flight/sql/struct.ActionCreatePreparedSubstraitPlanRequest.html#).

**To Reproduce**
Try to use structure in code, or just look at the docs in crates.io.

**Expected behavior**
Structure should be exported.

**Additional context**

**Comment by amartins23** [comment]
It would be nice if the fix could be back ported to older arrow versions, namely 43 and 47.

**Comment by alamb** [comment]
> It would be nice if the fix could be back ported to older arrow versions, namely 43 and 47.

Thanks @amartins23  -- we don't currently have the bandwidth to do releases for older versions, though we could certainly do so with some more help. Any chance you have some time to help with such a thing (basically make a branch, and then create the README, / bump versions). If so I an provide more details

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4933
