### ISSUE TITLE
Connecting to GCS locally works, on remote server DNS lookup breaks

### ISSUE THREAD

**Issue by alextes** [apache/arrow-rs#4936]
**Describe the bug**
Running locally object_store connects to GCS just fine, on a remote Ubuntu server it seems to attempt to resolve a google cloud local address and fails to resolve it. Resulting it errors like this:
```
Encountered request e
rror (error sending request for url (http://metadata/computeMetadata/v1/instance/ser
vice-accounts/default/token?audience=https%3A%2F%2Fwww.googleapis.com%2Foauth2%2Fv4%
2Ftoken): error trying to connect: dns error: failed to lookup address information:
Temporary failure in name resolution) backing off for 0.5767765 seconds, retry 5 of
10
```

**To Reproduce**
Run object_store with a downloaded service account key on a OVH dedicated server.

Obviously this will mostly be for me to figure out but I'm fairly lost as to what's different between my local machine and the server. I've checked the service account key file three times, tried installing gcloud and authenticating on the remote machine (I can list the buckets with gcloud storage ls now), still same DNS resolution error.

Here's the keyfile just to rule out there's a problem in there.

```json
{
  "type": "service_account",
  "project_id": "ultra-sound-relay",
  "private_key_id": "5e9cfc9bca6d86a0a3940e2579e0d4e009dcb697",
  "private_key": "****",
  "client_email": "migrate-payloads@ultra-sound-relay.iam.gserviceaccount.com",
  "client_id": "115776541199447156360",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/migrate-payloads%40ultra-sound-relay.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
```

Could OVH be breaking the lookup somehow?

**Comment by alextes** [comment]
Okay, think I found my answer. Tried to lookup the token_uri on the server and my local machine. Server gives:
```
nslookup oauth2.googleapis.com
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   oauth2.googleapis.com
Address: 172.217.20.202
```

That looks broken. Can probably close this. I'll report back if I find a solution just in case others end up here.

**Comment by tustvold** [comment]
The error response suggests it is trying to communicate with the local metadata endpoint, which would suggest it isn't picking up the service account credentials.

**Comment by alextes** [comment]
Thanks that helped! Found it. Stupid issue. At some point copilot rewrote the with_service_account_path to using the env based setup. But there was nothing in the server's env. Error message could be a bit more helpful than simply hanging forever in this case but either way, user error, thanks for the pointer in the right direction ❤️ !
