### ISSUE TITLE
Consider Vec::from_iter in Buffer::from_iter

### ISSUE THREAD

**Issue by shinmao** [apache/arrow-rs#4937]
### The source of unsoundness
Hi, we are the Rust researchers from [SunLab](https://sunlab-gmu.github.io/). Recently, we are trying to test our static analysis tool and find the potential unsound function in the package of `arrow-buffer`:
https://github.com/apache/arrow-rs/blob/90bc5ec96b5ae5162f469f9784dde7b1a53a5bdd/arrow-buffer/src/buffer/immutable.rs#L417-L432
In line 429, when the mutable pointer is cast to generic type, it is actually casting from `u8` to any-aligned type which could create a misaligned pointer. However, it seems that the programmers are also aware of the bugs in the test case:
https://github.com/apache/arrow-rs/blob/90bc5ec96b5ae5162f469f9784dde7b1a53a5bdd/arrow-buffer/src/buffer/scalar.rs#L224-L231
Here, `u8` is cast to `i32` and create a misaligned pointer and panic occurs.  
We consider that it should not happen in safe API anyway based on the [safety requirement](https://doc.rust-lang.org/std/ptr/fn.write.html) of `ptr.write()`. The problem could be fixed by passing the layout of `element` to allocate the memory.
We would love to have more discussion, and please correct if we are wrong.

**Comment by tustvold** [comment]
> it is actually casting from u8 to any-aligned type which could create a misaligned pointer

MutableBuffer uses an aligned allocator, with an alignment exceeding that of any ArrowNativeType

**Comment by shinmao** [comment]
@tustvold thanks for the response. Then, why does it still panic?

**Comment by tustvold** [comment]
Because the Buffer::slice which comes after in the test is shifting it so that Buffer is no longer aligned, but unlike MutableBuffer, Buffer has no alignment restrictions so this is safe

**Comment by shinmao** [comment]
Fair enough. Thanks!

**Comment by shinmao** [comment]
Yes. I just realized these two lines after discussion with you :joy:
https://github.com/apache/arrow-rs/blob/90bc5ec96b5ae5162f469f9784dde7b1a53a5bdd/arrow-buffer/src/buffer/mutable.rs#L72-L73

**Comment by tustvold** [comment]
I've taken the liberty of updating the issue title to rephrase this into an enhancement proposal. I think this should be relatively straightforward, and less unsafe is always a good thing, the major task would be making sure it doesn't regress anything
