### ISSUE TITLE
`arrow_json`: support `binary` deserialization

### ISSUE THREAD

**Issue by Folyd** [apache/arrow-rs#4945]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I have a bunch of parquet files that contain a binary column, here is the schema:

```sql
CREATE EXTERNAL TABLE `buildings`(
  `id` string,
  `updateTime` string,
  `version` int,
  `names` string,
  `level` int,
  `height` double,
  `geometry` binary
)
```

The `geometry` column is binary.  Here is my struct:

```rust
#[derive(Deserialize)]
struct Building {
    // omit for brevity ...

    #[serde(default)]
    geometry: Vec<u8>,
}
```

However, it failed to deserialize the parquet data with `arrow::json::writer::record_batches_to_json_rows()`, here is the error:

```
Error: Json error: data type Binary not supported in nested map for json writer
```

**Describe the solution you'd like**

`arrow_json` should support deserialize binary to `Vec<u8>`.

**Comment by tustvold** [comment]
So if I understand correctly you are reading binary data from a parquet file and are trying to write it to JSON?

Unfortunately JSON does not define a mechanism to transport binary data, you have two common options:

* If the binary data is actually UTF-8 you could cast the column to a StringArray
* You could use a crate like base64 to base64 encode the binary data prior to writing it

**Comment by Folyd** [comment]
In my example, the `geometry` is actually a [wkb](https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry#Well-known_binary) (well-known-binary) type. Does arrow support `wkb`?

**Comment by tustvold** [comment]
Arrow supports WKB, but JSON would only support WKT

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4967
