### ISSUE TITLE
Simplify ObjectStore::List

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4946]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Having two layers of asynchrony and fallibility makes for a rather obnoxious interface. Removing this makes for better client ergonomics, at the expense of slightly more arcane logic to implement the ObjectStore

**Describe the solution you'd like**

I would like `ObjectStore::list` to synchronously return an async stream

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #4930

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4946](https://github.com/apache/arrow-rs/issues/4946)
