### ISSUE TITLE
Support `RecordBatch::remove_column()` and `Schema::remove_field()`

### ISSUE THREAD

**Issue by Folyd** [apache/arrow-rs#4952]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Arrow C++ implementation support removes column and field for `RecordBatch` and `Schema` respectively, `arrow-rs` doesn't have such APIs.

**Describe the solution you'd like**

Add `RecordBatch::remove_column()` and `Schema::remove_field()`, similar to C++:

- https://github.com/apache/arrow/blob/883a439076233f3f2836f281614ebe01601ccab9/cpp/src/arrow/record_batch.cc#L137
- https://github.com/apache/arrow/blob/883a439076233f3f2836f281614ebe01601ccab9/cpp/src/arrow/type.h#L1171

**Comment by tustvold** [comment]
This should be a relatively straightforward task and can likely be modeled on the existing project methods

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4964
