### ISSUE TITLE
Add take_record_batch kernel

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#4958]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
When trying to divide up data in `RecordBatches` into subsets such as when writing partitioned output in DataFusion or in lancedb, we end up creating a new `RecordBatch` that is a subset of the input eventually using the underlying arrow [take](https://docs.rs/arrow-select/latest/arrow_select/take/fn.take.html) kernel

See slack discussion in https://the-asf.slack.com/archives/C01QUFS30TD/p1696014226063749

**Describe the solution you'd like**
Similarly to [`filter_record_batch`](https://docs.rs/arrow-select/latest/arrow_select/filter/fn.filter_record_batch.html) I would like an ergnomic version of  [`take_record_batch`] that can be used like

```rust
let batch: RecordBatch = ...;
let indices = vec![1,3,5];
// new_batch contains rows 1, 3, and 5 of `batch`
let new_batch = take_record_batch(&batch, &indices)?;
```

Here is the lancedb version: https://github.com/lancedb/lance/pull/1337/

Here is the code from DataFuson here (thanks @devinjdangelo  for the link)

https://github.com/apache/arrow-datafusion/blob/85f3578f5fb47d28a8bc3a7b9be0284b3ced0fcd/datafusion/physical-plan/src/repartition/mod.rs#L193-L212

**Describe alternatives you've considered**

**Additional context**
cc @devinjdangelo  @westonpace

**Comment by alamb** [comment]
Given this is well specified and there is existing code, I think this would be a great project for new members of the community.

**Comment by alamb** [comment]
The upside of `RecordBatch::take` is that it is easier to discover than a free function in another crate.

For this reason, an extension trait (perhaps in the `arrow` crate) along with links from `RecordBatch` documentation would be preferable in my mind.

**Comment by tustvold** [comment]
> The upside of RecordBatch::take is that it is easier to discover than a free function in another crate.

It would need to be a trait implemented in arrow-select to not run into the orphan rule

**Comment by alamb** [comment]
Making a bunch of traits in different crates certainly doesn't feel like it would make this functionality easier to discover. Perhaps the best thing  is to use free functions and make sure the documentation clearly points people at them

**Comment by alamb** [comment]
FWIW this came up again in IOx internally

BTW the idea in  https://github.com/lancedb/lance/pull/1337 is pretty neat (add a `RecordBatchExt` extension trait for RecordBatch -- which perhaps could be a way to work aroudn this - put the `RecordBatchExtc` in the main arrow crate rather than the `record_batch` crate) 🤔
