### ISSUE TITLE
Re-enable Java Integration Tests

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4963]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Pending a better way to orchestrate the integration tests, the Java tests were disabled so as to get master green

**Describe the solution you'd like**

I would like a mechanism for orchestrating the integration tests that doesn't rely on mirroring changes to the apache/arrow repository, resulting in an ever more complex CI definition.

**Describe alternatives you've considered**

**Additional context**

**Comment by pitrou** [comment]
PR https://github.com/apache/arrow/pull/38403 should ideally make this simpler.
