### ISSUE TITLE
Handle Body Errors in AWS CompleteMultipartUpload

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#4965]
**Describe the bug**

CompleteMultipartUpload has an _interesting_ approach to error handling

> Processing of a Complete Multipart Upload request could take several minutes to complete. After Amazon S3 begins processing the request, it sends an HTTP response header that specifies a 200 OK response. While processing is in progress, Amazon S3 periodically sends white space characters to keep the connection from timing out. A request could fail after the initial 200 OK response has been sent. This means that a 200 OK response can contain either a success or an error. If you call the S3 API directly, make sure to design your application to parse the contents of the response and handle it appropriately. If you use AWS SDKs, SDKs handle this condition. The SDKs detect the embedded error and apply error handling per your configuration settings (including automatically retrying the request as appropriate). If the condition persists, the SDKs throws an exception (or, for the SDKs that don't use exceptions, they return the error). 

From https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html

**To Reproduce**

Not entirely sure how to test this, but we should at the very least return an error

**Expected behavior**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #4971

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4965](https://github.com/apache/arrow-rs/issues/4965)
