### ISSUE TITLE
Panic when using an azure object store with an invalid access key

### ISSUE THREAD

**Issue by scsmithr** [apache/arrow-rs#4972]
**Describe the bug**

When using an azure object store configured with an invalid access key, attempting to use the store will result in a panic.

**To Reproduce**

Example:

```rust
use object_store::azure::MicrosoftAzureBuilder;
use object_store::{path::Path, ObjectStore};

#[tokio::main]
async fn main() {
    let store = MicrosoftAzureBuilder::new()
        .with_account("my_account")
        .with_container_name("my_container")
        .with_access_key("invalid")
        .build()
        .unwrap();

    let path = &Path::parse("/my_path").unwrap();
    let _res = store.get(&path).await;
}
```

Results in a panic during the `get`:

```
thread 'main' panicked at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/object_store-0.7.1/src/azure/credential.rs:189:56:
called `Result::unwrap()` on an `Err` value: InvalidPadding
```

**Expected behavior**

No panic and instead an error gets returned.

The easy fix is to just propagate the error up from here: https://github.com/apache/arrow-rs/blob/03d0505fc864c09e6dcd208d3cdddeecefb90345/object_store/src/azure/credential.rs#L170-L182

**Additional context**

Our use case is we configure object stores based on user provided values, and so a panic when provided with an invalid value is undesirable.

**Comment by tustvold** [comment]
Agreed, we should probably check this on construction within the builder

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #4974

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#4972](https://github.com/apache/arrow-rs/issues/4972)
