### ISSUE TITLE
Add Float16/Half-float logical type to Parquet

### ISSUE THREAD

**Issue by anjakefala** [apache/arrow-rs#4986]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
There is a proposal for an addition of Logical Float-16 (with Fixed Length Byte Array physical typed) to the Parquet Format: https://github.com/apache/parquet-format/pull/184.

The [vote has passed](https://lists.apache.org/thread/odm5pmxssyd9kw1wvgdkg8hd044czqnk). Close to completion are a [Java implementation](https://github.com/apache/parquet-mr/pull/1142), [C++ implementation](https://github.com/apache/arrow/pull/36073), and a [Go](https://github.com/apache/arrow/pull/37599). 

**Describe the solution you'd like**
Float-16 is supported in [arrow-rs](https://github.com/apache/arrow-rs/pull/888), and it would be great to expand that support to Rust Parquet.

**Comment by Jefffrey** [comment]
I'd like to take a stab at this if no one has yet

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #5003
