### ISSUE TITLE
[objects-store]: periods/dots error in GCP bucket

### ISSUE THREAD

**Issue by ritchie46** [apache/arrow-rs#4991]
**Describe the bug**

Backported from: https://github.com/pola-rs/polars/issues/12006

```rust
use object_store::gcp::GoogleCloudStorageBuilder;

pub fn run() -> Option<()> {

    GoogleCloudStorageBuilder::new()
        .with_url("gs://example.com/test.parquet")
        .build().unwrap();

    Some(())
}
```

The snippet above does not run, because of the `.` in the bucket url. According to the [docs](https://cloud.google.com/storage/docs/buckets), they should be allowed, but require some extra [verification](https://cloud.google.com/storage/docs/domain-name-verification).

**Expected behavior**
Expected the builder to accept the URL.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #4992
