### ISSUE TITLE
[FlightSQL] Allow custom commands in get-flight-info

### ISSUE THREAD

**Issue by amartins23** [apache/arrow-rs#4996]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
The current FlightSqlService trait allows the implementer to handle custom commands in the `DoGet` call via `do_get_fallback` method implementation. However, the corresponding `GetFlightInfo` call does not allow obtaining tickets for custom commands.

**Describe the solution you'd like**
Create new methods (with default implementations) in the `FlightSqlService` trait: `get_flight_info_fallback`

**Describe alternatives you've considered**
The alternative is to create a wrapper `FlightService` implementation that has custom handling, then forwards everything to the existing implementation provided by implementing `FlightSqlService`.

**Additional context**
See previous issue #4463.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #4997

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow-flight'} from #4997
