### ISSUE TITLE
Include onelake fabric path for https

### ISSUE THREAD

**Issue by vmuddassir-msft** [apache/arrow-rs#5000]
Need to add onelake fabric path for https 

dfs.fabric.microsoft.com
blob.fabric.microsoft.com

https://github.com/apache/arrow-rs/blob/5601b7a8c8fa7ebdd34a7ab0a90aff7958913143/object_store/src/parse.rs#L84

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #5002

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5000](https://github.com/apache/arrow-rs/issues/5000)
