### ISSUE TITLE
Dynamic parquet row group size option for record batch writer?

### ISSUE THREAD

**Issue by b4l** [apache/arrow-rs#5004]
**Which part is this question about**

Parquet record batch writer row group size

**Describe your question**

Is it possible to create a row group for each record batch written?

**Additional context**

When writing record batches, the parquet record batch writer creates row groups of size `max row group size`. This is unfortunate when the record batches are partitioned in a way to have high locality as they get split up and the statistic become less usable since the batches are `rechuncked`.

**Comment by tustvold** [comment]
You can manually call https://docs.rs/parquet/latest/parquet/arrow/arrow_writer/struct.ArrowWriter.html#method.flush

I would, however, caution against lots of small row groups as it will hurt read performance and file size

**Comment by b4l** [comment]
@tustvold thanks for the pointer! Was looking at the wrong place, this works nicely.

The batches are about half the default row group size, the tradeoffs negligible in this case compared to the range query performance improvements.
