### ISSUE TITLE
Return row count when inferring schema from JSON

### ISSUE THREAD

**Issue by asayers** [apache/arrow-rs#5007]
arrow-csv's `infer_schema()` returns the number of records read, along with the schema.  This is useful information!  arrow-json's `infer_json_schema()`, on the other hand, only returns the schema itself.  It would be nice if it matched arrow-csv.

**Comment by asayers** [comment]
Arguably it's less important in arrow-json than it is in arrow-csv, since with NDJSON you can just count the newline characters to get the row count.  (As opposed to CSV, where quoted fields may contain newline characters without indicating a new row, so you really need to parse it to get the row count.)

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5008
