### ISSUE TITLE
Release `object_store `0.8.0`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#5010]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I would like an object store release

New features that would be nice to release:
- [ ]  Conditional reads/writes (https://github.com/apache/arrow-rs/pull/4984)
- [ ] `MultiPartStore` API https://github.com/apache/arrow-rs/pull/4971

I believe @tustvold  is planning to make an official release 🔜  and this ticket is just tracking the work

**Describe the solution you'd like**
Make a new object_store crate release (official apache release and release it to crates.io)

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
I think the outstanding list of PRs is:

* https://github.com/apache/arrow-rs/pull/5020
* https://github.com/apache/arrow-rs/pull/5018
* https://github.com/apache/arrow-rs/pull/5016
* https://github.com/apache/arrow-rs/pull/5002

It would be nice to get https://github.com/apache/arrow-rs/pull/4918 in, but it is a larger one and not strictly necessary as it doesn't introduce API breakage

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5010](https://github.com/apache/arrow-rs/issues/5010)
