### ISSUE TITLE
Allow `zip` compute kernel to take `Scalar` / `Datum` 

### ISSUE THREAD

**Issue by Nathan-Fenner** [apache/arrow-rs#5011]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I currently have a `mask: &BooleanArray`, `if_true: &dyn Datum`, `if_false: &dyn Datum`, and I know that `if_true.data_type() == if_false.data_type()`, and I'd like to call `zip(mask, if_true, if_false)` to obtain an `Arc<dyn Array>`.

However, `zip` currently has the signature:

```rs
/// # Arguments
/// * `mask` - Boolean values used to determine from which array to take the values.
/// * `truthy` - Values of this array are taken if mask evaluates `true`
/// * `falsy` - Values of this array are taken if mask evaluates `false`
pub fn zip(
    mask: &BooleanArray,
    truthy: &dyn Array,
    falsy: &dyn Array,
) -> Result<ArrayRef, ArrowError> { ... }
```

Since it accepts `&dyn Array` instead of `&dyn Datum`, I can pass in the underlying arrays for each of my datum... but this will crash if `if_true` is a scalar and `if_false` is an array (or vice-versa), since in that case they will have different lengths (1 and 300, say).

I want to be able to call `zip()` function just like `arrow::compute::kernels::numeric::add`, where scalar values will be repeated to match `mask`:

```rs
/// # Arguments
/// * `mask` - Boolean values used to determine from which array to take the values.
/// * `truthy` - Values of this array are taken if mask evaluates `true`
/// * `falsy` - Values of this array are taken if mask evaluates `false`
pub fn zip(
    mask: &BooleanArray,
    truthy: &dyn Datum, // a `Datum` instead of `Array`
    falsy: &dyn Datum, // a `Datum` instead of `Array`
) -> Result<ArrayRef, ArrowError> { ... }
```

Currently, a caller with a (possibly) scalar value for one of the arguments needs to essentially implement `zip` from scratch, and requires downcasting the arrays in order to be able to obtain and copy the (singleton) scalar value.

**Describe the solution you'd like**

Update the `zip` function to accept `if_true: &dyn Datum` and `if_false: &dyn Datum` parameters (just like `add`) with logic to copy the values to each output row if needed, or make a new `zip` function which  takes those parameters as the type `&dyn Datum`.

(`mask` does not need to be a `&dyn Datum`, since when the `mask` is a scalar, it is easy to avoid calling `zip` entirely)

**Describe alternatives you've considered**

Manually replicating the `if_true` or `if_false` values into an array prior to calling `.zip` would work, but requires some tedious downcasting to support every type, and is also probably less efficient because it requires constructing (and then probably throwing away) a temporary array of the same value repeated multiple times.

**Comment by tustvold** [comment]
This makes sense to me

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5086
