### ISSUE TITLE
ObjectStore: hard to determine the cause of the error thrown from retry

### ISSUE THREAD

**Issue by Rachelint** [apache/arrow-rs#5013]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I found hard to determine the cause of the error thrown from retry when using `object_store` in our project, due to not enough information in error msg.

**Describe the solution you'd like**

Add more detailed information in error msg.

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #5012

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5013](https://github.com/apache/arrow-rs/issues/5013)
