### ISSUE TITLE
Support casting from integer to binary

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#5014]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The cast kernel doesn't support casting from integer to binary. While working on integrating DataFusion, found that this is supported by Spark but lacked in DataFusion. It's great if we can fill the gap.

**Describe the solution you'd like**

Support casting from integer to binary

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5015
