### ISSUE TITLE
ObjectStore parse_url Incorrectly Handles URLs with Spaces

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#5017]
**Describe the bug**

`ObjectStore::parse_url` does not correctly decode URL paths, resulting in incorrect behaviour for paths containing spaces (or other non URL-safe characters).

**To Reproduce**

**Expected behavior**

```
#[test]
fn test_url_spaces() {
    let url = Url::parse("file:///my file with spaces").unwrap();
    assert_eq!(url.path(), "/my%20file%20with%20spaces");
    let (_, path) = parse_url(&url).unwrap();
    assert_eq!(path.as_ref(), "my file with spaces");
}
```

**Additional context**

Relates to https://github.com/apache/arrow-datafusion/pull/8012 and https://github.com/apache/arrow-datafusion/issues/7877

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #5018

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5017](https://github.com/apache/arrow-rs/issues/5017)
