### ISSUE TITLE
Relax Path Safety on Parse

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#5019]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently `PathPart::parse` and by extension `Path::parse` disallow paths containing "unsafe" characters. 

This feels unnecessarily puritanical given:

* Most stores and filesystems do actually support UTF-8
* We don't exclude characters that some filesystems don't support, e.g. `:` on Mac OSX
* We don't exclude filenames that are forbidden on some systems, e.g. `COM1` on Windows
* We exclude characters that are fairly common, e.g. `~`
* We actually add `%` characters to paths, which the stores recommend against including in object names

**Describe the solution you'd like**

I think we should preserve the existing percent encoding behaviour when using the infallible methods, this gives people a safe default behaviour. 

However, I would propose we change `PathPart::parse` to only reject segments that

* Are `""` or `"."` or `".."`
* Contain ASCII control characters
* Contain a delimiter

This broadly conforms to what is supported by most filesystems - https://en.wikipedia.org/wiki/Filename

**Describe alternatives you've considered**

**Additional context**

https://github.com/apache/arrow-datafusion/pull/8014

**Comment by crepererum** [comment]
Do file-based object stores count as a "sandbox"? If so, we should probably double-check that there aren't some weird ways to escape the root directory via some bizarre unknown features.

Slightly related: do we follow symlinks?

**Comment by tustvold** [comment]
> Do file-based object stores count as a "sandbox"

I don't think we have ever billed it as such, I certainly wouldn't rely on it, but that doesn't mean people aren't using it as such.

> do we follow symlinks

Yes and they can allow escaping the "sandbox", this is documented here - https://docs.rs/object_store/latest/object_store/local/struct.LocalFileSystem.html#symlinks

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #5020

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5019](https://github.com/apache/arrow-rs/issues/5019)
