### ISSUE TITLE
Async Arrow Reader

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#5021]
_This is largely a placeholder and would need further fleshing out if someone wishes to work on this_

**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Current we only support reading IPC files from a synchronous buffer. This limits the ability to read parts of files.

**Describe the solution you'd like**

I high-level implementation inspired by parquet might look like

* A low-level mechanism to decode a footer from bytes - https://docs.rs/parquet/latest/parquet/file/footer/index.html
* A higher-level mechanism to fetch and decode a footer from an async source - https://docs.rs/parquet/latest/parquet/arrow/async_reader/fn.fetch_parquet_metadata.html
* An API to decode a RecordBatch from a data block, with an optional projection

This would then naturally lend itself to being wrapped up in an async interface similar to ParquetRecordBatchStream

**Describe alternatives you've considered**

**Additional context**

**Comment by Jefffrey** [comment]
FYI a duplicate/related issue exists: https://github.com/apache/arrow-rs/issues/1207
