### ISSUE TITLE
Re-evaluate Explicit SIMD Aggregations

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#5032]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We currently only have explicit SIMD kernels for min, max and sum. This is a non-trivial additional complexity, and relies on features not present in stable Rust.

**Describe the solution you'd like**

Historically LLVM has struggled with auto-vectorisation of horizontal operations like aggregates, and this has been why we've kept these kernels, however, it is possible this has since improved. We should assess whether it is possible to eliminate the need for explicit SIMD kernels, and potentially remove them

**Describe alternatives you've considered**

**Additional context**

https://github.com/apache/arrow-rs/pull/4560 contains some experiments for improving the auto-vectorisation of aggregates

**Comment by jhorstmann** [comment]
I started working on this and #5031 and think I have found a way to generalize the approach from #4560 and get auto-vectorization also for MIN/MAX. Still need to clean up the code further and run more benchmarks.

**Comment by tustvold** [comment]
Awesome, I presume you are also aware of https://github.com/apache/arrow-rs/issues/5031?

**Comment by jhorstmann** [comment]
@tustvold I must have missed or forgotten that the `compare` kernels and arithmetic `div`/`mod` also no longer use explicit simd. Just to confirm, all the methods in `ArrowNumericType` behind the `simd` feature would no longer be needed once aggregation stops using them?

**Comment by tustvold** [comment]
Correct, it would definitely simplify things to no longer have nightly only functionality

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5100
