### ISSUE TITLE
cast format 'yyyymmdd'  to Date32 give a error

### ISSUE THREAD

**Issue by Tangruilin** [apache/arrow-rs#5044]
**Describe the bug**
when cast string like '19990819' to Date32, it will give a error， but for '1999-08-19' it secceed

**To Reproduce**
In arrow-datafusion
For a date column run a query with the date in string format 'yyyymmdd' as shown below
```
--this query fails
select * from orders where o_orderdate = '19961006'
```
it get 
```
Arrow error: Cast error: Cannot cast string '19961006' to value of Date32 type
```

**Expected behavior**
This should return the correct result and not fail

**Additional context**

**Comment by Tangruilin** [comment]
@alamb hey! the bug for [https://github.com/apache/arrow-datafusion/issues/7465](https://github.com/apache/arrow-datafusion/issues/7465) is belong to this, maybe this issue can be assigned to me and i will fix it

**Comment by alamb** [comment]
Assigned -- thanks @Tangruilin  

@tustvold  can you confirm this is a reasonable change to add to arrow-rs? If not, I think we should add the code to DataFusion instead

**Comment by tustvold** [comment]
I see no issue with this

**Comment by Tangruilin** [comment]
@alamb @tustvold

**Comment by Tangruilin** [comment]
I have initiated a PR, thanks for review

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5078
