### ISSUE TITLE
Could we tag release candidates in GitHub?

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-rs#5057]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I wanted to upgrade DataFusion to use arrow-rs 48.0.0-rc1 but could not find that tag in the repo. I know I can reference the commit instead, but tagging release candidates seems like a better practice.

**Describe the solution you'd like**

It would be nice if arrow-rs followed the same convention as DataFusion, where we create a git tag for each release candidate, and then tag with the final release number once the release is approved and published.

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
Makes sense to me, I have pushed 49.0.0-rc1
