### ISSUE TITLE
JSON writer - write null structs as null, instead of struct with nulls

### ISSUE THREAD

**Issue by Jefffrey** [apache/arrow-rs#5066]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

See note here:

https://github.com/apache/arrow-rs/blob/31b5724332666d68fe94a5b3572a13a51022ea81/arrow-json/src/writer.rs#L1315-L1328

**Describe the solution you'd like**

When writing a struct array, if there is a null then should write null instead of `{}`

**Describe alternatives you've considered**

Keep behaviour as is, writing `{}` for null entry in struct array. Remove above note in code and clearly document this is expected behaviour.

**Additional context**

**Comment by tustvold** [comment]
I think this is actually just a bug

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5133

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #5065

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5066](https://github.com/apache/arrow-rs/issues/5066)
