### ISSUE TITLE
Parquet: derive boundary order when writing columns

### ISSUE THREAD

**Issue by Jefffrey** [apache/arrow-rs#5074]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

See https://github.com/apache/arrow-rs/blob/7ba36b012322e08b06184c806f8ba339181cebc1/parquet/src/file/metadata.rs#L888-L889

From parquet thrift:

https://github.com/apache/parquet-format/blob/46cc3a0647d301bb9579ca8dd2cc356caf2a72d2/src/main/thrift/parquet.thrift#L982-L988

```
  /**
   * Stores whether both min_values and max_values are ordered and if so, in
   * which direction. This allows readers to perform binary searches in both
   * lists. Readers cannot assume that max_values[i] <= min_values[i+1], even
   * if the lists are ordered.
   */
  4: required BoundaryOrder boundary_order
```

**Describe the solution you'd like**

Be able to set this boundary order when writing parquet files

**Describe alternatives you've considered**

**Additional context**

Some additional reading/discussion;

https://github.com/apache/parquet-format/blob/master/PageIndex.md

https://github.com/apache/arrow-rs/pull/5003#discussion_r1389675899

- Need to ensure for special types like Float16 where sort order differs from its physical type representation that this is accounted for & tested

**Comment by Jefffrey** [comment]
Planning to take a shot at this

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #5110
