### ISSUE TITLE
Parquet: don't truncate min/max statistics for float16 and decimal when writing file

### ISSUE THREAD

**Issue by Jefffrey** [apache/arrow-rs#5075]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

See discussion:

https://github.com/apache/arrow-rs/pull/5003#discussion_r1389675899

https://github.com/apache/arrow-rs/pull/5003 added support for float16 type which is a logical type on top of fixed len byte array

When writing statistics, truncation can occur for binary physical type:

https://github.com/apache/arrow-rs/blob/7ba36b012322e08b06184c806f8ba339181cebc1/parquet/src/column/writer/mod.rs#L634-L643

Which might be troublesome for f16 type, if the `column_index_truncate_length` config is set to 1, as a truncated f16 wouldn't represent the min and max correctly anymore as it has a sort order different from fixed len byte array

**Describe the solution you'd like**

Ignore truncation for f16 when writing min/max statistics

**Describe alternatives you've considered**

**Additional context**

Do we need to worry about this for other types based on binary physical types? i.e. decimal

**Comment by Jefffrey** [comment]
Potentially has relation to https://github.com/apache/arrow-rs/issues/5037?

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #5154
