### ISSUE TITLE
Parquet: Bring ArrowWriter methods over to AsyncArrowWriter

### ISSUE THREAD

**Issue by wjones127** [apache/arrow-rs#5099]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I noticed that [AsyncArrowWriter](https://docs.rs/parquet/latest/parquet/arrow/async_writer/struct.AsyncArrowWriter.html) is missing a bunch of methods that [ArrowWriter](https://docs.rs/parquet/latest/parquet/arrow/arrow_writer/struct.ArrowWriter.html) has, such as `in_progress_size()`.

Also on either, it's not clear how to get the total size of data written + total size buffered, which I think most users want. IIUC that's a documentation issue, since I think folks have already enabled that information to be retrieved.

**Describe the solution you'd like**

Port methods and improve usage docs.

**Describe alternatives you've considered**

**Additional context**

**Comment by AdamGS** [comment]
We use the async writer a lot, and I would be happy to try and take a stab at this issue, should have the time and bandwidth in the next couple of weeks.

**Comment by AdamGS** [comment]
Ok took a look and it was actually shorter than I expected from the description. Got a draft open but its still missing some things.
