### ISSUE TITLE
Expose a path for converting `bytes::Bytes` into `arrow_buffer::Buffer` without copy

### ISSUE THREAD

**Issue by chebbyChefNEQ** [apache/arrow-rs#5104]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

It would be nice if we can call `let buffer: Buffer = bytes.into()` without incurring a copy, since `object_store` returns `bytes::Bytes`.

**Describe the solution you'd like**

I see that `arrow_buffer::bytes::Bytes` already implements `From<bytes::Bytes>` [here](https://github.com/apache/arrow-rs/tree/master/arrow-buffer/src#L148-L156)

I guess we just need to add a implementation of `From<bytes::Bytes> for Buffer`

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
As you've identified this should be a relatively straightforward addition. I will, however, temper your expectations that this will only be possible when the buffer is sufficiently aligned for the array - you will need to be careful here to avoid panics

**Comment by chebbyChefNEQ** [comment]
Yeah, I noticed that the in memory object store implementation doesn't guarantee 8-byte aligns buffers, which is sufficient for most types.

I was debating if I should open an issue and make object store return aligned buffers. Since there is no mmap in the object store I think this is doable?

**Comment by tustvold** [comment]
> Since there is no mmap in the object store I think this is doable?

The challenge is that hyper, etc... use Bytes to avoid copying data when they slice up HTTP data frames. I'm therefore not sure this is tractable without introducing potential performance regressions. It also seems like something object_store should not be concerned with

**Comment by wjones127** [comment]
> I was debating if I should open an issue and make object store return aligned buffers. Since there is no mmap in the object store I think this is doable?

I think there might be a way to get aligned buffers more optimally within the existing APIs: Right now, the body is read as a stream of `Bytes` and then concatenated here:

https://github.com/apache/arrow-rs/blob/6d4b8bbad95c7e4fec0c4f1fb755ad7a1c542983/object_store/src/lib.rs#L1021

The concatenation does a mem copy already, so we could mem copy them into an buffer of our preferred alignment. The `GetResult` struct seems to have a pretty open API, so I think users could achieve this themselves if they want:

https://github.com/apache/arrow-rs/blob/6d4b8bbad95c7e4fec0c4f1fb755ad7a1c542983/object_store/src/lib.rs#L969-L976

**Comment by tustvold** [comment]
> The concatenation does a mem copy already

Not always, if there is only a single `Bytes` object it won't. But as you allude to, we're really just playing with where the copy takes place, the current API is flexible enough that users can make this judgement call themselves

**Comment by tustvold** [comment]
Closed by https://github.com/apache/arrow-rs/pull/4260
