### ISSUE TITLE
Support Casting List To/From LargeList in Cast Kernel

### ISSUE THREAD

**Issue by Weijun-H** [apache/arrow-rs#5113]
**Describe the bug**

In https://github.com/apache/arrow-datafusion/issues/8305#issue-2006427098, datafuction cannot cast nested `List` to `LargeList` because of `can_cast_types` function

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by tustvold** [comment]
This should be a relatively straightforward task of casting the offsets buffer

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5124
