### ISSUE TITLE
Cast from floating/timestamp to timestamp/floating

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#5122]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Similar to #5039, floating types cannot be casted to/from timestamp types for now. This is supported by Spark. We'd like to fill this gap too.

**Describe the solution you'd like**

Supporting casting from floating/timestamp to timestamp/floating by cast kernel.

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5123
