### ISSUE TITLE
Parquet: read parquet metadata with page index in async and with size hints

### ISSUE THREAD

**Issue by AdamGS** [apache/arrow-rs#5129]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We have multiple cases where we want to just load parquet file metadata with the page index, we already have metadata and file sizes stored externally but there doesn't seem to be a way to read that data without using `object_store`.
`fetch_parquet_metadata` doesn't load the page index and but does use hints, and `ArrowReaderMetadata` doesn't use hints and forces us to jump through hoops and have an additional implementation of `AsyncFileReader`.

**Describe the solution you'd like**

I think that adding an argument to `fetch_parquet_metadata` is easier than stabilizing `MetadataLoader`, and will work with many other readers that can read byte ranges.

**Describe alternatives you've considered**

We currently just maintain a minor fork with `MetadataLoader` and `MetadataFetch` made public.

Will be glad to do any and all work required here (either adding an argument to `fetch_parquet_metadata`, helping stabilize `MetadataLoader` or anything else), but I would like to make sure I'm doing something that's actually valuable and not just spamming the maintainers here.

**Comment by tustvold** [comment]
I don't see a compelling reason not to make MetadataLoader public and would be happy to review a PR doing so, the API seems unlikely to change in the near future

**Comment by AdamGS** [comment]
Awesome! I'll hopefully have a PR ready today.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #5137
