### ISSUE TITLE
`object_store`: Allow 403 Forbidden for `copy_if_not_exists` S3 status code

### ISSUE THREAD

**Issue by emcake** [apache/arrow-rs#5132]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Currently `object_store` implements `copy_if_not_exists` behaviour for S3 object stores that can specify how to do this via a header. Currently Cloudflare R2 does this with support from the `COPY_IF_NOT_EXISTS` env variable configured to append a header and matching on `PRECONDITION_FAILED` return status code.

I have another S3 implementation that can implement something like this via a header, but the return status code is 403 (`FORBIDDEN`) instead.

**Describe the solution you'd like**
Extend the match case on error when copying to include 403 as a return code that indicates that the file cannot be overwritten.

**Describe alternatives you've considered**
I considered catching this later in user code and handling it, but by the time it reaches me it's wrapped in a `Generic` object store error with `Box<dyn Error>` and I can't even use `Any` to match against the inner error.

**Additional context**

**Comment by tustvold** [comment]
Out of interest what store returns this? 403 forbidden is meant for authorization failure not precondition??

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #5134

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5132](https://github.com/apache/arrow-rs/issues/5132)
