### ISSUE TITLE
Support casting of Float16 with other numeric types

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#5138]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We support casting between various numeric types (signed/unsigned integers, floating), but for floating types, Float16 is not in supported list.

**Describe the solution you'd like**

Make sure Float16 is supported as like Float32/64 in numeric type casting.

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5139
