### ISSUE TITLE
Support specifying `quote` and `escape` in Csv `WriterBuilder`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#5146]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
In DataFusion https://github.com/apache/arrow-datafusion/pull/8351 we are adding support to specify the escaping and quote characters used for CSV reading.

It turns out that the Arrow CSV writer does not support specifying the escape and quoting characters

**Describe the solution you'd like**
I would like the following in the CSV [WriterBuilder](https://docs.rs/arrow-csv/49.0.0/arrow_csv/writer/struct.WriterBuilder.html#):
* with_escape (analogous to [ReaderBuilder::with_escape](https://docs.rs/arrow-csv/49.0.0/arrow_csv/reader/struct.ReaderBuilder.html#method.with_escape) )
* with_quote (analogous to [ReaderBuilder::with_quote](https://docs.rs/arrow-csv/49.0.0/arrow_csv/reader/struct.ReaderBuilder.html#method.with_quote) )

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
This should be a relatively straightforward first issue.

I would highlight though that "escape" is advised against by the CSV library we use - https://docs.rs/csv/latest/csv/struct.WriterBuilder.html#method.escape

> In some variants of CSV, quotes are escaped using a special escape character like \ (instead of escaping quotes by doubling them).
> By default, writing these idiosyncratic escapes is disabled, and is only used when double_quote is disabled.

**Comment by my-vegetable-has-exploded** [comment]
I'd like to have a try.
