### ISSUE TITLE
Request to Memmap Arrow IPC files on disk

### ISSUE THREAD

**Issue by comath** [apache/arrow-rs#5153]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I have machine learning dataset that exceed my system's ram which I access in a random pattern. I currently split the data into a flat f32 array written to the disk, and a set of parquet files. This is awkward and requires complex glue code. 

**Describe the solution you'd like**
I'd like to use a memmap like this: https://huggingface.co/docs/datasets/about_arrow

**Describe alternatives you've considered**
Switching to another format. rkvy works, but is not nearly as interoperable. 

**Additional context**

**Comment by tustvold** [comment]
I believe this should already be possible if you create a Buffer from an external allocation and them feed this into the IPC decoder

**Comment by comath** [comment]
I thought that was the case, but couldn't find a way to do that. The public function that reads [record batches](https://docs.rs/arrow-ipc/49.0.0/arrow_ipc/reader/fn.read_record_batch.html) in the IPC crate needs a lot of [boilerplate](https://github.com/apache/arrow-rs/blob/master/arrow-ipc/src/reader.rs#L550C1-L778) to adequately read an IPC file. The functions in the flight crate requires you go through a few hoops. The simplest pair is this [read](https://docs.rs/arrow-flight/latest/arrow_flight/utils/fn.batches_to_flight_data.html) and [write](https://docs.rs/arrow-flight/latest/arrow_flight/utils/fn.batches_to_flight_data.html) pair. 

I implemented it using the IPC file reader code [here](https://github.com/comath/arrow-rs/blob/ipc-memmap-read/arrow-ipc/src/reader.rs#L1035).

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5165
