### ISSUE TITLE
EnabledStatistics::Page  does not take effect on ByteArrayEncoder

### ISSUE THREAD

**Issue by karellincoln** [apache/arrow-rs#5162]
**Describe the bug**
when I used below WriterProperties to close column Statistics
```
let w_opt = WriterProperties::builder()
.set_compression(Compression::SNAPPY)
.set_max_row_group_size(1024 * 1024)
.set_data_page_row_count_limit(1024)
.set_statistics_enabled(EnabledStatistics::None)
.set_column_statistics_enabled("taskId".into(), EnabledStatistics::Page) // the only column I want to build ColumnIndex, in Page level
.build();
```

**actual behavior**
I find all column which type is string build ColumnIndex, but I set it did not build.
```
    let mut file = tokio::fs::File::open(file_path).await.unwrap();
    let metadata =
        ArrowReaderMetadata::load_async(&mut file, ArrowReaderOptions::new().with_page_index(true))
            .await
            .unwrap();

use this get metadata like below:
                }), NONE, BYTE_ARRAY(NativeIndex { indexes: [PageIndex { min: Some(ByteArray { data: "ok"
                            }), max: Some(ByteArray { data: "ok"
                            }), null_count: Some(0)
                        }, PageIndex { min: Some(ByteArray { data: "ok"
                            }), max: Some(ByteArray { data: "ok"
                            }), null_count: Some(0)
                        }
                    ], boundary_order: BoundaryOrder(0)
                }), BYTE_ARRAY(NativeIndex { indexes: [PageIndex { min: Some(ByteArray { data: "ok"
                            }), max: Some(ByteArray { data: "ok"
                            }), null_count: Some(0)
                        }, PageIndex { min: Some(ByteArray { data: "ok"
                            }), max: Some(ByteArray { data: "ok"
                            }), null_count: Some(0)
                        }
                    ], boundary_order: BoundaryOrder(0)
                }), BYTE_ARRAY(NativeIndex { indexes: [PageIndex { min: Some(ByteArray { data: "60b6a5dd99c75"
                            }), max: Some(ByteArray { data: "60b6a5dd99c75"
                            }), null_count: Some(0)
                        }, PageIndex { min: Some(ByteArray { data: "60b6a5dd99c75"
                            }), max: Some(ByteArray { data: "60b6a5dd99c75"
                            }), null_count: Some(0)
                        }
                    ], boundary_order: BoundaryOrder(0)
```

**Expected behavior**

I found [ByteArrayEncoder](https://github.com/apache/arrow-rs/blob/master/parquet/src/arrow/arrow_writer/byte_array.rs#L501) not use EnabledStatistics value to control that, 
![image](https://github.com/apache/arrow-rs/assets/12014068/04064c61-0de2-4294-ac42-3664ad4dd40f)
like [ColumnValueEncoderImpl](https://github.com/apache/arrow-rs/blob/master/parquet/src/column/writer/encoder.rs#L139) 
![image](https://github.com/apache/arrow-rs/assets/12014068/d4f9ff22-3bfc-40cd-874b-33a0aa87fd07)

**Comment by karellincoln** [comment]
In my scenario,  it is necessary to set `data_page_row_count_limit` to a relatively small value. Additionally, the most of  type of columns are  String. excessive metadata is slowing down the queries. I hope fix it soon.

**Comment by tustvold** [comment]
In the short-term have you experimented with using  - https://docs.rs/parquet/latest/parquet/file/properties/struct.WriterProperties.html#method.column_index_truncate_length

**Comment by karellincoln** [comment]
Thanks a lot.
I try [column_index_truncate_length](https://docs.rs/parquet/latest/parquet/file/properties/struct.WriterProperties.html#method.column_index_truncate_length) and it can improve performance.

Yes, 1024 is very low. But in some reason，I need to frequently fetch a few records from parquet, not for OLTP. I understand that Parquet is not well-suited for this, but unfortunately, we cannot change the underlying storage.

**Comment by AdamGS** [comment]
@tustvold I would love to take a stab at this if no one else started on it, read some of the code and I think I understand the general area where the fix should be.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #5181
