### ISSUE TITLE
Add data type field to `NullArray`

### ISSUE THREAD

**Issue by waynexia** [apache/arrow-rs#5173]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

`NullArray::data_type()` returns `Null` type unconditionally. This limits its use case to `Null`s only array. I'm trying to leverage `NullArray` in some scenarios where I know all the values of an array are `Null` (but typed). This can save lots of memory.

**Describe the solution you'd like**

Add a `data_type` field to `NullArray`, something like
```rust
pub struct NullArray {
    data_type: DataType,
    len: usize,
}
```

I've referenced the CPP `NullArray` implementation, which inherits a complete `ArrayData` from `Array` class. We don't need to do the same in `arrow-rs` but can consider adding useful fields like `len` and `data_type` separately. 

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
I'm not sure this will work, aside from this diverging from the arrow standard, DataType must correspond to the appropriate array variant. Perhaps you might consider using RunArray instead?

**Comment by waynexia** [comment]
BTW, I also find the behavior of `Array::is_null()` is different between CPP and Rust implementations. Related discussion is https://github.com/apache/arrow-rs/issues/4835 cc @alamb @tustvold. CPP impl always return `true` and Rust always returns `false`.

[source](https://github.com/apache/arrow/blob/1cc1f4c752895301371ee59d315ebffe74224c66/cpp/src/arrow/array/array_base.h#L62-L80):

```cpp
  /// \brief Return true if value at index is null. Does not boundscheck
  bool IsNull(int64_t i) const { return !IsValid(i); }

  /// \brief Return true if value at index is valid (not null). Does not
  /// boundscheck
  bool IsValid(int64_t i) const {
    if (null_bitmap_data_ != NULLPTR) {
      return bit_util::GetBit(null_bitmap_data_, i + data_->offset);
    }
    // Dispatching with a few conditionals like this makes IsNull more
    // efficient for how it is used in practice. Making IsNull virtual
    // would add a vtable lookup to every call and prevent inlining +
    // a potential inner-branch removal.
    if (type_id() == Type::SPARSE_UNION) {
      return !internal::IsNullSparseUnion(*data_, i);
    }
    if (type_id() == Type::DENSE_UNION) {
      return !internal::IsNullDenseUnion(*data_, i);
    }
    if (type_id() == Type::RUN_END_ENCODED) {
      return !internal::IsNullRunEndEncoded(*data_, i);
    }
    return data_->null_count != data_->length;
  }
```

Hence I come across another question: should we strive to maintain consistent behavior of common APIs across various implementations?

**Comment by tustvold** [comment]
See https://github.com/apache/arrow-rs/issues/4840

**Comment by waynexia** [comment]
> I'm not sure this will work, aside from this diverging from the arrow standard, DataType must correspond to the appropriate array variant. Perhaps you might consider using RunArray instead?

Thanks for replying. I find what confuses me is how to understand the `Null` type. For some time it indicates the missing value (maybe this is the "logical null" in #4840), thus it should have another type of the possible value. Like `None` for `Option<i64>`. And this is how I interpret the `NullArray` -- a container that is only for `None`.

But when `Null` means null itself (maybe `nullptr`? not an appropriate analogy), it doesn't ship any other extra info. Like the `NullArray` implementation at present. 

From the [spec](https://arrow.apache.org/docs/format/Columnar.html#null-layout) I can't figure out which way accord with the `NullArray`'s definition.
>We provide a simplified memory-efficient layout for the Null data type where all values are null. In this case no memory buffers are allocated.

**Comment by tustvold** [comment]
NullArray is a bit of an odd one, but it is for the case where there is no value, e.g. a SQL NULL literal.

**Comment by fabianmurariu** [comment]
@alamb We have found quite a lot of use cases where NullArray would benefit from type.

1. we need to track global schema separate from the arrow files if we write some of the chunk with null arrays. 
2. In our use case the memory savings of using NullArray are quite significant but handling types is extra work
3. We have to write our own recursive null supporting concat
4. Schema merge doesn't work with null datatype.
5. We lost data_type on null arrays after migrating to arrow-rs from [polars-arrow](https://docs.rs/polars-arrow/latest/polars_arrow/array/struct.NullArray.html)

I think if NullArray would function as an identity element if some of the some operations like, concat, or schema merge I think that would be quite useful even without it having a designated data_type.

**Comment by alamb** [comment]
> I think if NullArray would function as an identity element if some of the some operations like, concat, or schema merge I think that would be quite useful even without it having a designated data_type.

Thanks @fabianmurariu  -- i am not quite sure what you are proposing here 

Is it to automatically convert an array of all nulls to `NullArray` / have more efficient runtime handling of "array of all nulls"?

Do you have any specific proposal?
