### ISSUE TITLE
Parquet list reader not reading correct element lengths

### ISSUE THREAD

**Issue by nevi-me** [apache/arrow-rs#518]
**Describe the bug**

This is https://issues.apache.org/jira/browse/ARROW-13120 moved here, with a bit more details.

The issue is that the list reader does not check repetitions to calculate the correct number of values to read in order to correctly compose a list.

**To Reproduce**

Given an array:

```json
{"list": [1, 2, 3]}
{"list": [4, 5]}
```

Reading 2 values should return the 5 child values, but only 1 and 2 are returned.

**Expected behavior**

List reader should calculate the correct number of child values to read, then return those values instead of slicing between arrays.

**Additional context**

This bug seems to have existed before the new arrow reader contributed by @yordan-pavlov

**Comment by nevi-me** [comment]
@mcassels I've opened this issue to track the bug that you identified

**Comment by alamb** [comment]
@helgikrs  has been recently working on some fixes for this type of issue in https://github.com/apache/arrow-rs/pull/1187 https://github.com/apache/arrow-rs/pull/1166 and https://github.com/apache/arrow-rs/pull/1185 . I wonder if someone could check if it is still an issue

**Comment by tustvold** [comment]
This does not appear to be an issue anymore, possibly closed by #1588 or some prior pr
