### ISSUE TITLE
Remove nightly-only simd feature and related code in ArrowNumericType

### ISSUE THREAD

**Issue by jhorstmann** [apache/arrow-rs#5185]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

With the merge of #5100 all users of the feature-gated methods in `ArrowNumericType` should be gone and those functions can be removed.

**Describe the solution you'd like**

 - Remove simd related functions from `ArrowNumericType` trait
 - Remove `bit_util::bitwise_bin_op_simd` which seems to be unused
 - Remove `simd` feature and `packed_simd` dependency

**Describe alternatives you've considered**

The `ArrowNumericType` seems a little bit redundant with `ArrowNativeTypeOp`, but removing it completely would involve a lot of little api changes, so it's probably better to keep it as an empty marker trait.

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5184
