### ISSUE TITLE
[object_store,gcp] Document GoogleCloudStorage Default Credentials

### ISSUE THREAD

**Issue by justinabrahms** [apache/arrow-rs#5187]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I'd like to authenticate via object_store to GCP, but I don't want to have to pass around a json file of credentials.

**Describe the solution you'd like**

Ideally, I could use the service principal configured on my compute instance to issue requests. It can be fetched via https://cloud.google.com/compute/docs/metadata/predefined-metadata-keys#instance-metadata 

As a less good, but also fine solution.. I'd like access to TokenProvider so that I can just issue the relevant API call myself.

**Describe alternatives you've considered**

I think I'll have to code my own CredentialProvider, but you already have a higher level abstraction I can't get access to.

**Additional context**

**Comment by tustvold** [comment]
I believe this is the default behaviour if you don't configure any credential provider, is this not working for some reason?

**Comment by justinabrahms** [comment]
We were using credential files for local testing, and there was an error when we went to deploy them. Looking through the docs, I couldn't see anything that mentioned getting creds from instance metadata.

Digging in the source, I finally came across https://github.com/apache/arrow-rs/blob/master/object_store/src/gcp/credential.rs#L322 but I think this needs to be a documentation improvement, not a code change.

This is where I was looking and hoping to find something useful: https://docs.rs/object_store/0.7.1/object_store/gcp/type.GcpCredentialProvider.html or https://docs.rs/object_store/0.7.1/object_store/gcp/struct.GoogleCloudStorage.html#method.credentials

**Comment by tustvold** [comment]
> but I think this needs to be a documentation improvement, not a code change.

I agree, this is not very clearly documented. I would definitely welcome a PR to improve this.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #5188

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5187](https://github.com/apache/arrow-rs/issues/5187)
