### ISSUE TITLE
Decimal128 and Decimal256 types are not supported in arrow_json

### ISSUE THREAD

**Issue by matthewgapp** [apache/arrow-rs#5198]
**Describe the bug**

When trying to write record batches to json using `arrow_json` that contain a column with Decimal128, I get the following error 

```
Decimal128(10, 2) not supported in nested map for json writer
```

**To Reproduce**

**Expected behavior**

Writing record batches with column with types Decimal128 or Decimal256 should be supported. 

**Additional context**

**Comment by phillipleblanc** [comment]
This is supported now in #6606
