### ISSUE TITLE
Support equality of StructArray

### ISSUE THREAD

**Issue by my-vegetable-has-exploded** [apache/arrow-rs#5199]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

In [datafusion #6635](https://github.com/apache/arrow-datafusion/issues/6635), we think convert tuple to struct will be helpful to implement multi column In list. 

But StructAray is not comparable in arrow-rs since it is nested.

https://github.com/apache/arrow-rs/blob/7e289134a8d9f46a92a2759a7b2488b17993fd5b/arrow-ord/src/cmp.rs#L201-L205.

**Describe the solution you'd like**

I don't know if this feature is already implemented in arrow.

In my view,  compare PrimitiveArray may be rather different from NestedArray. Take equality of StrutArray as an example, I think it may need those steps:

- check equality of datatype
- check equality of PrimitiveArray for each field
- perform conjunction operation on the results of each field

The process slightly differs from the ```apply_op``` process.

https://github.com/apache/arrow-rs/blob/7e289134a8d9f46a92a2759a7b2488b17993fd5b/arrow-ord/src/cmp.rs#L361-L364

**Describe alternatives you've considered**

**Additional context**

The equality of other array type may need more further consideration. Like equality for ListArray, shall we considerate out of order between list(which means that whether [[1,2]] and [[2,1]] are equal or not)?

**Comment by alamb** [comment]
@tustvold  is there any fundamental reason we can't compare struct arrays for equality (by recursively checking each field)?

**Comment by tustvold** [comment]
Not that I am aware of, should be fairly straightfoward

**Comment by my-vegetable-has-exploded** [comment]
Thanks for the reply. If this enhancement is not so urgent, I am willing to submit a pr later.

**Comment by tustvold** [comment]
I don't believe there is any particular urgency on this one, thank you

**Comment by alamb** [comment]
I agree there is no urgency from my perspective
