### ISSUE TITLE
into_inner() for CSV Writer

### ISSUE THREAD

**Issue by joshuataylor** [apache/arrow-rs#520]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I would love an `into_inner()` for the CSV writer, this is what I have been using:
```
    pub fn into_inner(self) -> W {
        self.writer.into_inner().unwrap()
    }
```

In the CSV Writer, and it has been working well for my project. It exists in the JSON Writer.

**Describe the solution you'd like**
Add the function to CSV writer.

**Describe alternatives you've considered**
Not sure how else I would access the writer, it exists in the JSON writer.

**Comment by alamb** [comment]
This would be a great new issue for someone to add ❤️
