### ISSUE TITLE
`parquet::arrow::AsyncArrowWrite` have memory leak

### ISSUE THREAD

**Issue by nooberfsh** [apache/arrow-rs#5214]
**Describe the bug**
`parquet::arrow::AsyncArrowWrite` have memory leak

**To Reproduce**
I have managed to create a [repo](https://github.com/nooberfsh/parquet_mem_leak) to reproduce it, the program write 
a bunch of `RecordBatch` using `parquet::arrow::AsyncArrowWrite`, after finish writing, the program still remains about
3GB memory according to htop.

**Additional context**
```
rustc 1.74.0 (79e9716c9 2023-11-13)
```

**Comment by tustvold** [comment]
Could you try using an actual memory profiler - e.g. https://github.com/KDE/heaptrack or Mac OS Instruments.

Most system allocators do not return memory to the system even once freed, and programs like htop will not reflect this

**Comment by nooberfsh** [comment]
Thanks for the tip. According to heaptrack the program does not have memory leak.
In our real application,  when we write large volume of data, it just oom. I will dig deeper and try to find the problem.
BTW: heaptrack is awesome.

**Comment by nooberfsh** [comment]
Hi, I I have simplify the code and use `ArrowWriter` directly.
I found  `ArrowWriter` will not release memory after `ArrowWriter::close()` according to heaptrack.

```
fn main() -> Result<()> {
    leak()?;
    println!("sleep");
    std::thread::sleep(Duration::from_secs(1000));
    Ok(())
}

fn leak() -> Result<()> {
    let schema = Arc::new(Schema::new(vec![Field::new("col1", DataType::Utf8, true)]));

    let mut writer = ArrowWriter::try_new(Empty::default(), schema.clone(), None)?;
    for _ in 0..1000 {
        let batch = gen_batch(1000, schema.clone());
        writer.write(&batch)?;
    }
    writer.close()?;
    Ok(())
}

fn gen_batch(size: usize, schema: SchemaRef) -> RecordBatch {
    let mut buf = StringBuilder::new();
    for i in 0..size {
        let s = vec![i as u8; 1000];
        let s = String::from_utf8_lossy(&s);
        buf.append_value(s);
    }
    let col1 = Arc::new(buf.finish());
    RecordBatch::try_new(schema, vec![col1]).unwrap()
}

```

Steps to reproduce:

- cargo build --release
- heaptrack ./target/release/parquet_mem_leak
- wait screen to show *sleep* which means `ArrowWriter` has finished writing and closed
- kill the program with `Ctrl-C`, heaptrack will popup and show the leaks,  the program above leaks ~10MB on my machine.

If I comment out `std::thread::sleep(Duration::from_secs(1000));` , heaptrack does not show any leaks related to `arrow`.
So the question is does `arrow` manages some global buffer or something?  What I am expected is memory should released immediately after closing the writer.

![parquet_mem_leak](https://github.com/apache/arrow-rs/assets/6291629/97ef061e-762c-407d-9e1b-d3f770caf051)

**Comment by tustvold** [comment]
What is Empty?

**Comment by nooberfsh** [comment]
[Empty](https://doc.rust-lang.org/std/io/struct.Empty.html) ignores any data written via [Write](https://github.com/apache/arrow-rs/issues/trait.Write.html), it is a defined in `std`.
Full code is in this [repo](https://github.com/nooberfsh/parquet_mem_leak)

here is the allocations graph
![parquet_mem_leak_allocations](https://github.com/apache/arrow-rs/assets/6291629/7e46c1e5-ea87-4a51-8cd3-fe6fd4171bc5)

Call stack
![Screenshot_20231217_193746](https://github.com/apache/arrow-rs/assets/6291629/28178252-3fc7-4306-9db8-78297ec128df)

So is it leaking?

**Comment by nooberfsh** [comment]
Just updated the code in the repo.

**Comment by nooberfsh** [comment]
Thanks for the suggestion.

**Comment by DDtKey** [comment]
Just wondering if it can be related to https://github.com/apache/arrow-rs/issues/5450
