### ISSUE TITLE
json schema inference can't handle null field turned into object field in subsequent rows

### ISSUE THREAD

**Issue by kskalski** [apache/arrow-rs#5215]
**Describe the bug**
Such scenario produces
`JsonError("Expected object json type, found: Any")`

**To Reproduce**
```rust
    #[test]
    fn test_infer_from_null_then_object() {
        let data = r#"
            {"obj":null}
            {"obj":{"foo":1}}
        "#;
        let (inferred_schema, _) =
            infer_json_schema_from_seekable(Cursor::new(data), None).expect("infer");
    }
```

**Expected behavior**
Schema should be inferred and have struct data type for `obj` field

**Additional context**
arrow-rs master / v49.0.0

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5216
