### ISSUE TITLE
object_store: support directly provided GCP access tokens

### ISSUE THREAD

**Issue by erikamundson** [apache/arrow-rs#5223]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

In some cases, we want to authenticate to GCP and load files, etc. on behalf of the user. For example, deploying a Jupyterhub instance that has data loading libraries installed. In this case, it may not make sense for the environment to have access to a service account credential file or for the server to have an application default credential that has data access. Our current main use case is loading parquet files using polars into such an environment, where we want traceability access requests.

We can generate a refresh + access token from the oauth flow, but cannot currently pass it into the object store gcs reader. 

**Describe the solution you'd like**

It appears that the service account json is being used to generate a [struct with a bearer token](https://github.com/apache/arrow-rs/blob/9e060dc6c68e6aac30d0ae643d1d1854db44a378/object_store/src/gcp/credential.rs#L86-L90). Ideally the storage builder would be able to directly accept an access token and create the `GcpCredential` object from that access token (which would be the bearer token). 

**Describe alternatives you've considered**

One alternative that could work would be passing a client id + secret and a refresh token, then the client can generate a temporary token as it does with a service account.

**Comment by tustvold** [comment]
The [https://docs.rs/object_store/latest/object_store/gcp/struct.GoogleCloudStorageBuilder.html](https://docs.rs/object_store/latest/object_store/gcp/struct.GoogleCloudStorageBuilder.html) supports a number of different credential options, which can also be configured using [https://docs.rs/object_store/latest/object_store/gcp/enum.GoogleConfigKey.html](https://docs.rs/object_store/latest/object_store/gcp/enum.GoogleConfigKey.html). If none of these meet your use-case you can provide a custom credential provider using [with_credentials](https://docs.rs/object_store/latest/object_store/gcp/struct.GoogleCloudStorageBuilder.html#method.with_credentials).
