### ISSUE TITLE
Azure Signed URL Support

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#5232]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

https://github.com/apache/arrow-rs/pull/4876 added support for generating S3 URLs, via the [Signer](https://docs.rs/object_store/latest/object_store/signer/trait.Signer.html) trait. This ticket tracks implementing Signer for [MicrosoftAzure](https://docs.rs/object_store/latest/object_store/azure/struct.MicrosoftAzure.html)
**Describe the solution you'd like**

Azure calls this functionality a [Shared Access Signature](https://learn.microsoft.com/en-us/rest/api/storageservices/delegate-access-with-shared-access-signature).

Depending on the type of credential available to [MicrosoftAzure](https://docs.rs/object_store/latest/object_store/azure/struct.MicrosoftAzure.html) there are different ways to generate a signed URL:

* [AzureAccessKey](https://docs.rs/object_store/latest/object_store/azure/enum.AzureCredential.html#variant.AccessKey) - [Service SAS](https://learn.microsoft.com/en-us/rest/api/storageservices/create-account-sas)
* [BearerToken](https://docs.rs/object_store/latest/object_store/azure/enum.AzureCredential.html#variant.BearerToken) - [User Delegation SAS](https://learn.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas)
* [SASToken](https://docs.rs/object_store/latest/object_store/azure/enum.AzureCredential.html#variant.SASToken) - not supported (I think)

In both cases, there are a lot of options for further restricting the signatures with access policies, encryption, IP restrictions, etc... an initial implementation should stick to using the defaults as a first step.

**Describe alternatives you've considered**

**Additional context**

Split out from https://github.com/apache/arrow-rs/issues/3027

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #5259

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5232](https://github.com/apache/arrow-rs/issues/5232)
