### ISSUE TITLE
Release arrow-rs version 50.0.0

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#5234]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
49.0.0 was released about a month ago: https://crates.io/crates/arrow/49.0.0

**Describe the solution you'd like**
I would like to release version 50.0.0 with the accumulated changes since then

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
@tustvold  is this something I can do / help with, or are you planning to do it?

**Comment by tustvold** [comment]
I hope to do it after the object store release probably in mid-January. I'm not aware of anything major that is waiting on the next release, and I'm experimenting with a slightly more sedate release cadence

**Comment by alamb** [comment]
Ok, if anyone needs a release sooner I am happy to run the process (It would be good to get the practice)

**Comment by tustvold** [comment]
> Ok, if anyone needs a release sooner I am happy to run the process (It would be good to get the practice)

If you do decide to do this, just give me a heads up. There have been a couple of contributors working on some things across multiple PRs, and I need to take some time to double check that we're at a coherent stopping point.

**Comment by alamb** [comment]
As I understand it the ETA for this release is later this week / early next week

**Comment by changhiskhan** [comment]
Hi just curious if this is still happening this week or early next week. We're waiting for a bug fix in arrow-rs plus the next datafusion release to support upsert in Lance. Thanks! 🙏

**Comment by tustvold** [comment]
It intend to cut the release on Monday

**Comment by tustvold** [comment]
Unfortunately there are issues with the DF upgrade that I've yet to track down, and I have run out of time for today. If someone is able to help track down the issues, I have a very hard time debugging the sqllogictests, that would help me get the release cut promptly tomorrow.

**Comment by tustvold** [comment]
Release thread - https://lists.apache.org/thread/v0htvt1x0vy5rcmrkygtrtjw2ml1qqzy
