### ISSUE TITLE
Cannot access pen state website on arrow-row

### ISSUE THREAD

**Issue by thomas-k-cameron** [apache/arrow-rs#5238]
**Describe the bug**
Arrow-row has a link to pen state's website but it is not accessible; It says `Token is required`.

[link](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.83.1080&rep=rep1&type=pdf)
```
{"message":"Token is required"}
```

**To Reproduce**
Click the part that it says `normalized for sorting` here.
https://docs.rs/arrow-row/49.0.0/arrow_row/index.html

![image](https://github.com/apache/arrow-rs/assets/68596478/30eaf4e1-37e5-4081-a9c4-e666e3e5a42c)

**Expected behavior**
It shows whatever that it has to show.

**Additional context**
NA

**Comment by tustvold** [comment]
Can be replaced with a link to http://wwwlgis.informatik.uni-kl.de/archiv/wwwdvs.informatik.uni-kl.de/courses/DBSREAL/SS2005/Vorlesungsunterlagen/Implementing_Sorting.pdf

**Comment by thomas-k-cameron** [comment]
@tustvold 
Would it possible to include these pdf file onto this repository?

**Comment by tustvold** [comment]
I would prefer not to, as it stands a good chance of causing legal headaches down the line

**Comment by thomas-k-cameron** [comment]
OK, I made a PR. Hope this helps!
https://github.com/apache/arrow-rs/pull/5239

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5239
