### ISSUE TITLE
Make regexp_match take scalar pattern and flag

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#5246]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

`regexp_match` kernel currently assumes patterns and flags are all arrays with same length as string array. For the kernel, one usual case is to use scalar pattern and flag, we don't need to build pattern hash map.

**Describe the solution you'd like**

Make `regexp_match` kernel take scalar pattern and flag

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5245
