### ISSUE TITLE
Support get offsets or blocks info from arrow file. 

### ISSUE THREAD

**Issue by my-vegetable-has-exploded** [apache/arrow-rs#5252]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

It seems that there isn't a pub function to provide offsets or blocks info from arrow file. 

**Describe the solution you'd like**

In arrow-ipc/src/reader.rs, 
```rust
impl<R: Read + Seek> FileReader<R> {
    pub fn blocks(&self) -> Vec<Block> {
        &self.blocks
    }
   //OR
    pub fn offsets(&self) -> Vec<i64> {
        &self.blocks.iter().map(Block::offset).collect()
    }
}
```

**Describe alternatives you've considered**

**Additional context**

related to https://github.com/apache/arrow-datafusion/issues/8503

**Comment by tustvold** [comment]
See https://github.com/apache/arrow-rs/pull/5249

**Comment by my-vegetable-has-exploded** [comment]
> See #5249

Sorry, I didn't find what I was looking for in this project. Could you give me more hints？

**Comment by tustvold** [comment]
The FileDecoder provides a mechanism to control how the various parts of a file are decoded and processed, as per the linked DF ticket.

Getting the blocks and offsets from FileReader isn't very useful as there is no way to actually control the IO that it performs.

**Comment by my-vegetable-has-exploded** [comment]
> The FileDecoder provides a mechanism to control how the various parts of a file are decoded and processed, as per the linked DF ticket.FileDecoder 提供了一种机制来控制如何根据链接的 DF 票证对文件的各个部分进行解码和处理。
> 

I'm not sure if I understand it correctly.  According to the doctest of FileDecoder, we can get footer firstly, then use FileDecoder to read different recordBatches.

**Comment by tustvold** [comment]
Correct, which gives you the ability to decode said RecordBatch in parallel in much the same way as we do for parquet row groups

**Comment by my-vegetable-has-exploded** [comment]
> Correct, which gives you the ability to decode said RecordBatch in parallel in much the same way as we do for parquet row groups

Get it! Thanks.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5249
