### ISSUE TITLE
parquet: add method to get both the inner writer and the file metadata when closing SerializedFileWriter

### ISSUE THREAD

**Issue by conradludgate** [apache/arrow-rs#5253]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I want to access the `FileMetadata` from a closed parquet file so that I can add some logging, but I also need to access the inner writer for further processing.

**Describe the solution you'd like**

`SerializedFileWriter` offers
* `into_inner() -> Result<W>`
* `close() -> Result<FileMetadata>`.

The bodies of both functions are almost identical. Perhaps close can return `Result<(FileMetadata, W)>`.

**Describe alternatives you've considered**

For now, I will use `into_inner()` and then open the file with `SerializedFileReader` to get the metadata.

**Additional context**

1. `close()` does not flush the file, which will ignore errors.
2. I would like async support, but I don't want to go through arrow. For now I am writing to an in memory buffer and then flushing the buffer over the network after I close the file.
3. TrackedWriter forces a BufWriter which means I am now double buffered. I would prefer if `W: BufWriter` instead of forcing the buffer on top.

**Comment by tustvold** [comment]
Adding a finish method that returns both makes sense to me

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #5471
