### ISSUE TITLE
`concat::tests::test_string_dictionary_merge failure` fails on Mac /  has different results in different platforms

### ISSUE THREAD

**Issue by doki23** [apache/arrow-rs#5255]
**Describe the bug**

I ran `test_string_dictionary_merge` both in `linux x86_64` and `macos aarch64` platforms and got different results. It succeeded in `linux x86_64` whose values' len is 33 and failed in `macos aarch64` whose values' len is 32. It's because `interner.intern` produces different results  when build interleave indices for new values array.

**To Reproduce**

Run `cargo test` both in above 2 platforms.

**Expected behavior**

The test can successfully pass in both platforms.

**Comment by doki23** [comment]
Yes, it's expected, but the test will failed. Maybe we should introduce conditional compilation in this test?

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5461
