### ISSUE TITLE
Remove Localstack DynamoDB Workaround Once Fixed Upstream

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#5267]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We currently have a special code path to support localstack, as it does not currently implement ReturnValuesOnConditionCheckFailure.

**Describe the solution you'd like**

Once the upstream issue (https://github.com/localstack/localstack/issues/9040) is fixed we can remove this logic

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #5307

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5267](https://github.com/apache/arrow-rs/issues/5267)
