### ISSUE TITLE
Object_store: s3 with_endpoint usage

### ISSUE THREAD

**Issue by troychiu** [apache/arrow-rs#5273]
**Which part is this question about**
Object store 

**Describe your question**
I would like to use object_store to communicate with my local object store (which is a minio object store)
I initialize the client like this
```Rust
let s3 = AmazonS3Builder::new()
    .with_endpoint("http://localhost:30002")
    .with_region("us-east-1") // Dummy region for local testing
    .with_bucket_name("my-bucket")
    .with_access_key_id("minio")
    .with_secret_access_key("miniostorage")
    .build()
    .expect("error creating s3");
```
However, when I call get like `let result = self.store.get(&path).await;` I got error `(http://localhost:30002/my-bucket/32M.txt): URL scheme is not allowed`.

I am wondering if there is any example about using local endpoint that I can refer to.

Thank you!

**Comment by Xuanwo** [comment]
Please enable `with_allow_http` too if you want to connect http endpoint: https://docs.rs/object_store/latest/object_store/aws/struct.AmazonS3Builder.html#method.with_allow_http

**Comment by troychiu** [comment]
This works perfect! Thank you for the instant help!

**Comment by Xuanwo** [comment]
cc @tustvold, should we consider a PR to mention `with_allow_http` in the `with_endpoint` documentation?

**Comment by tustvold** [comment]
SGTM that would be most appreciated, may also apply to stores other than S3, I can't remember off the top of my head
