### ISSUE TITLE
Support casting strings like '2001-01-01 01:01:01' to Date32

### ISSUE THREAD

**Issue by gruuya** [apache/arrow-rs#5280]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I'd like to be able to cast strings that represent timestamps into Date32 objects.

This is currently not possible (as per DataFusion CLI)
```sql
❯ SELECT '1998-11-30 00:00:00'::date;
Optimizer rule 'simplify_expressions' failed
caused by
Arrow error: Cast error: Cannot cast string '1998-11-30 00:00:00' to value of Date32 type
```

On the other hand this works in Postgres
```sql
postgres=# SELECT '1998-01-30 00:00:00'::date;
    date    
------------
 1998-01-30
(1 row)
```

It seems like this is the cause of the issue
https://github.com/apache/arrow-rs/blob/a9470d3eb083303350fc109f94865666fd0f062f/arrow-cast/src/parse.rs#L547-L550

**Describe the solution you'd like**

One option would be to do

```rust
fn parse_date(string: &str) -> Option<NaiveDate> {
    if string.len() > 10 {
        // Try to parse as timestamp and return just the date part
        return TimestampParser::new(string.as_bytes()).date();
    }
```

That would handle the most common case (i.e. `'yyyy-mm-dd ...'`).

Alternatively to handle other potential cases (single digit month and/or day, which PG also parses correctly) it might be better to `split_whitespace` and proceed with parsing the first element.

**Describe alternatives you've considered**

Perhaps this doesn't make sense to do in arrow-rs, and should instead be facilitated through a DataFusion optimizer rule.

**Additional context**

Related issue: #3492

**Comment by tustvold** [comment]
What is the postgres behaviour if given a non-zero time?

**Comment by doki23** [comment]
I've tried this: 
```
postgres=# select '1998-11-30 23:59:59'::date;
    date
------------
 1998-11-30
```
It seems that pgsql ignores the time part.

**Comment by gruuya** [comment]
> It seems that pgsql ignores the time part.

That is correct, it just throws it away.

In fact it seems it tries to parse it as a timestamp first, and if it fails it errors out.

```rust
postgres=# SELECT '1998-01-30 01-02-03'::date;
ERROR:  invalid input syntax for type date: "1998-01-30 01-02-03"
LINE 1: SELECT '1998-01-30 01-02-03'::date;
               ^

postgres=# SELECT '1998-01-30 01-02-03'::timestamp;
ERROR:  invalid input syntax for type timestamp: "1998-01-30 01-02-03"
LINE 1: SELECT '1998-01-30 01-02-03'::timestamp;
               ^

postgres=# SELECT '1998-01-30 01:2'::date;
    date    
------------
 1998-01-30
(1 row)

postgres=# SELECT '1998-01-30 01:2'::timestamp;
      timestamp      
---------------------
 1998-01-30 01:02:00
(1 row)

```

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5282
