### ISSUE TITLE
Add support for providing Chrono formats when parsing strings -> datetime/nanos and Parser implementations

### ISSUE THREAD

**Issue by Omega359** [apache/arrow-rs#5303]
This is related to https://github.com/apache/arrow-datafusion/issues/5398 where functions for parsing string -> datetime and string -> nanos would be added to include a second 'format' parameter. The format would be a chrono format (https://docs.rs/chrono/latest/chrono/format/strftime/index.html) and would return an Err if the string couldn't be parsed with the provided format.

The proposed two new functions that would be added would be :
* ```pub fn string_to_datetime_formatted<T: TimeZone>(timezone: &T, s: &str, format: &str) -> Result<DateTime<T>, ArrowError>```  (mirrors the existing string_to_datetime function)
* ```pub fn string_to_timestamp_nanos_formatted(s: &str, format: &str) -> Result<i64, ArrowError>```  (mirrors the existing string_to_timestamp_nanos function)

In addition, for completeness all the existing Parser implementations in that file would be updated to include a 'parse_formatted' implementation where missing.

**Comment by tustvold** [comment]
A few points:

* The current logic is quite highly optimised, we need to be careful not to introduce any performance regressions
* There are a couple of known bugs with the chrono format strings where the parser is overly permissive - https://github.com/chronotope/chrono/issues/332
* Timestamp parsing, especially timezones is very fiddly. I would request we keep code changes small, as it is very easy to subtly break things

Overall I am rather lukewarm on this functionality, but I will endeavour to review well tested and focused changes to this logic

**Comment by Omega359** [comment]
> Overall I am rather lukewarm on this functionality, as it is by definition diverging from established standards, but I will endeavour to review well tested and focused changes to this logic that don't regress existing workloads.

Would you prefer this to not be in arrow-cast and rather be left in datafusion? I'm only adding it here to mirror the existing functionality - I have no desire to change any of the current implementation details.

**Comment by tustvold** [comment]
Incubating functionality in DataFusion before lifting it into arrow-rs has been a successful model in the past, and might be a quicker way to iterate on https://github.com/apache/arrow-datafusion/issues/5398 without having to wait on an arrow-rs releases.

**Comment by Omega359** [comment]
Sounds good, I'll pull in my changes to DataFusion for now and we can close this issue.

**Comment by Omega359** [comment]
Closing this issue with https://github.com/apache/arrow-datafusion/issues/5398 as an alternative.
