### ISSUE TITLE
object-store: change logging level in aws/builder to debug or trace

### ISSUE THREAD

**Issue by universalmind303** [apache/arrow-rs#5305]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Currently the info logs in aws/builder really spam the logs when calling the builder many times, such as is the case with automated tests. 

**Describe the solution you'd like**

just change the logging level to debug or trace. 

**Describe alternatives you've considered**

log filtering on our end

**Additional context**
example of said logs 

![image](https://github.com/apache/arrow-rs/assets/21327470/0664c1d9-bb3e-4c64-b26f-a7851d9e762d)

**Comment by tustvold** [comment]
I'm not sure about this, as knowing what credentials are being used can be very important for being able to quickly diagnose certain classes of misconfiguration. Perhaps you could use something like lazy_static to avoid needing to initialise the builder for every test?
