### ISSUE TITLE
Broken Link in README (Rust Object Store) Content

### ISSUE THREAD

**Issue by llama90** [apache/arrow-rs#5309]
**Describe the bug**

I've noticed that there is a broken link in the README.

https://github.com/apache/arrow-rs/blob/3ed7cc61d4157263ef2ab5c2d12bc7890a5315b3/object_store/README.md?plain=1#L36

The `InfluxDB IOx` link is broken.

**Expected behavior**

I don't know what is the correct link. Maybe it's a link related to InfluxDB?

**Comment by tustvold** [comment]
Aah yes, that repo was made private. Will update

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #5312

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5309](https://github.com/apache/arrow-rs/issues/5309)
