### ISSUE TITLE
Pass Options to HttpBuilder in parse_url_opts

### ISSUE THREAD

**Issue by CarlKCarlK** [apache/arrow-rs#5310]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

*Summary* 

I am trying to use `parse_url_opts` to create an `ObjectPath` and `StorePath` completely from strings (and lists of string pairs). This will make it much easier for my users to access genomic data from the cloud. I can't, however, set the needed timeout option.

*Details*

I love parse_url_opts. It lets me set options such as "aws_access_key_id".

```rust
    let options = [
        ("aws_region", "us-west-2"),
        ("aws_access_key_id", credentials.aws_access_key_id()),
        ("aws_secret_access_key", credentials.aws_secret_access_key()),
    ];
```

It (apparently) does not, however, let me set client options such as "timeout". This is especially important for
Http.

**Describe the solution you'd like**

Perhaps the client options could be allowed and prefixed with "client_", for example,

    let options = [
        ("client_time_out", "1000"),
    ];

> Aside: I don't know how to set the default units for a duration.

**Describe alternatives you've considered**
**Additional context**

**Comment by tustvold** [comment]
This could definitely be documented better but it should work to specify `timeout`

https://docs.rs/object_store/latest/src/object_store/aws/builder.rs.html#381

**Comment by CarlKCarlK** [comment]
Thanks for looking at this. I'm wondering if it works with Http?

Here is the code--I think all options are ignored in the Http case

https://docs.rs/object_store/latest/src/object_store/parse.rs.html#136-180
```
        #[cfg(feature = "http")]
        ObjectStoreScheme::Http => {
            let url = &url[..url::Position::BeforePath];
            Box::new(crate::http::HttpBuilder::new().with_url(url).build()?) as _
        }
```

(I also tried it with Http and it didn't seem to work.)

**Comment by tustvold** [comment]
Aah yes, it would appear #4516 did not update parse_url. Will get a fix up for you

**Comment by CarlKCarlK** [comment]
[Also added to the PR]

You need to add line 167 back in of this fix doesn't work:

            let url = &url[..url::Position::BeforePath];

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #5316

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5310](https://github.com/apache/arrow-rs/issues/5310)
