### ISSUE TITLE
arrow-ipc backwards compatibility 

### ISSUE THREAD

**Issue by mokhaled2992** [apache/arrow-rs#5313]
Arrow-IPC 

- Does the format used by arrow-ipc reader/writer have any guarantees in terms of backwards compatibility? i.e a newer version would be able to read a filer written by an older version.
- If not, would a Reader in a new library version be able to detect that a file was written by a Writer from an older library version and fail gracefully?

**Comment by tustvold** [comment]
The format is forwards compatible

**Comment by mokhaled2992** [comment]
@tustvold  Thanks alot for the quick response!
