### ISSUE TITLE
Mention "Http" support in REAME

### ISSUE THREAD

**Issue by CarlKCarlK** [apache/arrow-rs#5320]
Http support is a great feature. Mentioning it in https://github.com/apache/arrow-rs/blob/master/object_store/README.md would let more users (and potential users) know about it.

**Comment by tustvold** [comment]
I intend to do a pass over the docs before the next release, but contributions in this space are also always welcome

**Comment by Xuanwo** [comment]
I'm ready to add documentation for HTTP. Please assign it to me if no one else has begun.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #5409
