### ISSUE TITLE
Support Arrow columnar format v1.4

### ISSUE THREAD

**Issue by spencerwilson** [apache/arrow-rs#5326]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

My initial problem was "I'm not sure what version of the Arrow spec(s) the `arrow` crate complies with". Documenting the level of support would be great.

After some searching it seems that the `arrow` crate presently supports "Arrow columnar format version 1.3", as defined here: https://github.com/apache/arrow/blob/3fe598ae4dfd7805ab05452dd5ed4b0d6c97d8d5/format/Schema.fbs#L20-L26

I'm creating this tracking issue since I didn't see anything about 1.4 by trying obvious searches in GitHub issue search. To be clear, I'm not suffering from a lack of support for 1.4 features currently.

**Describe the solution you'd like**

Support everything in Arrow columnar format version 1.4. Based on
- https://github.com/apache/arrow/commit/9d6d501fb654a93496070b59fbe7f36f4f1ed604, which initially defined 1.4
- https://github.com/apache/arrow/commit/6d551aa88237325978f51dbe02773a0aec2bfe9d, which retroactively added to 1.4

This would include support for 
- [ ] https://github.com/apache/arrow-rs/issues/3520
- [ ] https://github.com/apache/arrow-rs/issues/5374
- [ ] https://github.com/apache/arrow-rs/issues/5375

**Describe alternatives you've considered**

Declare an intention not to support things from 1.4, giving some rationale.

**Additional context**
n/a

**Comment by tustvold** [comment]
FWIW we don't currently support the array view types for which this functionality was added -  https://github.com/apache/arrow-rs/issues/4253

Always happy to review documentation PRs

**Comment by alamb** [comment]
Filed https://github.com/apache/arrow-rs/issues/5374 to track adding `StringViewArray` and https://github.com/apache/arrow-rs/issues/5375 to track adding `ListView`s and I updated the description on this ticket

**Comment by spencerwilson** [comment]
Similarly, I added a reference to #3520 , where the `RunEndEncoded` type was actually designated as part of columnar format v1.3.

**Comment by tustvold** [comment]
Closed by #5502, follow on work to flesh out support for ListView and StringViewArray are tracked in #5375 and #5374
