### ISSUE TITLE
Removing a column from a `RecordBatch` drops schema metadata

### ISSUE THREAD

**Issue by kylebarron** [apache/arrow-rs#5327]
**Describe the bug**

Calling `remove_column` on a `RecordBatch` object deletes any schema metadata.

In https://github.com/apache/arrow-rs/blob/a0148ba4cea1756bd22c534dff14e362cb5ee242/arrow-array/src/record_batch.rs#L357-L362

It creates the new `SchemaBuilder` exclusively from the fields which calls this `From impl`

https://github.com/apache/arrow-rs/blob/a0148ba4cea1756bd22c534dff14e362cb5ee242/arrow-schema/src/schema.rs#L125-L132

instead of also taking into account the schema metadata.

**To Reproduce**

I don't have a full repro example but can create one if needed.

**Expected behavior**

Schema metadata not to be dropped

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5328
