### ISSUE TITLE
Debug output of Time32/Time64 arrays with invalid values has confusing nulls

### ISSUE THREAD

**Issue by Jefffrey** [apache/arrow-rs#5336]
**Describe the bug**

When debug printing a Time32/Time64 array with values outside of the expected range (between 0 seconds (inclusive) and 86,400 seconds (exclusive), adjusted based on milli/micro/nano), then it shows `null` for those values, which can be confused with actual null values.

**To Reproduce**

```rust
    #[test]
    fn test_pretty_format_time_32_second_invalid() {
        let array: Time32SecondArray = vec![
            Some(-1),
            Some(0),
            Some(86_399),
            Some(86_400),
            Some(86_401),
            None,
        ]
        .into();
        println!("{:?}", array);

        let schema = Arc::new(Schema::new(vec![Field::new(
            "f",
            array.data_type().clone(),
            true,
        )]));
        let batch = RecordBatch::try_new(schema, vec![Arc::new(array)]).unwrap();

        let table = pretty_format_batches(&[batch]).unwrap().to_string();
        println!("{}", table);
    }
```

Outputs:

```
PrimitiveArray<Time32(Second)>
[
  null,
  00:00:00,
  23:59:59,
  null,
  null,
  null,
]
+---------------------------------------------------------------------------+
| f                                                                         |
+---------------------------------------------------------------------------+
| ERROR: Cast error: Failed to convert -1 to temporal for Time32(Second)    |
| 00:00:00                                                                  |
| 23:59:59                                                                  |
| ERROR: Cast error: Failed to convert 86400 to temporal for Time32(Second) |
| ERROR: Cast error: Failed to convert 86401 to temporal for Time32(Second) |
|                                                                           |
+---------------------------------------------------------------------------+
```

**Expected behavior**

Either:

- Document this behaviour
- Print some other value for invalid values, like `<invalid>`, instead of just `null`

**Additional context**

Seems to be due to this code:

https://github.com/apache/arrow-rs/blob/8fff5e4a075c20619690c967e217163cd74e0656/arrow-array/src/array/primitive_array.rs#L1104-L1110

**Comment by tustvold** [comment]
I think we should print an error, rather than null. This would be consistent with what ArrayFormatter would do. It may even be possible we could use that here :thinking:

**Comment by Monkwire3** [comment]
If this is unclaimed, I would like to give it a try.

**Comment by Monkwire3** [comment]
I just submitted a pull request. I did not end up using ArrayFormatter because it looked like it would require more refactoring than the solution I went with. However, I would be happy to try again using ArrayFormatter if that would be preferable.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5428
