### ISSUE TITLE
support cast 'UTF8' to `FixedSizeList`

### ISSUE THREAD

**Issue by Weijun-H** [apache/arrow-rs#5339]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I noticed that the List supports casting from UTF8 to List with a single size. Therefore, I think FixedSizeList should also support it. 
```
select arrow_cast('1', 'LargeList(Int64)');
----
[1]
```

_Originally posted by @Weijun-H in https://github.com/apache/arrow-datafusion/pull/8344#discussion_r1458219694_

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5340
