### ISSUE TITLE
Read row groups with random access from parquet files

### ISSUE THREAD

**Issue by xmakro** [apache/arrow-rs#5343]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I'd like to read row groups from a parquet file with random access. Ideally both for async and sync API. Currently, this seems only possible if all row groups are known when constructing the `ParquetRecordBatchStreamBuilder`. In my use case however, row groups are fetched with random access during the lifetime of the program, and the row group indices are not known ahead of time.

**Describe alternatives you've considered**

Currently, I'm constructing a new `ParquetRecordBatchStreamBuilder` for every row group that I'm reading. This has high overhead, as it needs to reopen the file and re-read the metadata each time.

**Describe the solution you'd like**

I'm agnostic to the API, but I found the modular API from `arrow2` works very well for this use case. Maybe something like:

```rust
let reader = tokio::fs::File::open(...).await?;
let metadata = read_metadata(&mut reader).await?;
let row_group: RecordBatch = read_row_group(&mut reader, &metadata, row_group_index, Some(projection)).await?;
```

An alternative would be to add a method that can get the metadata and file pointer when finishing a `ParquetRecordBatchStreamBuilder`, and then providing a constructor for `ParquetRecordBatchStream` that allows passing the metadata along with the file, so that the metadata doesn't have to be re-read. This feels more cumbersome.

**Comment by tustvold** [comment]
Perhaps https://docs.rs/parquet/latest/parquet/arrow/async_reader/type.ParquetRecordBatchStreamBuilder.html#method.new_with_metadata might work for you?
