### ISSUE TITLE
Can the ArrayBuilder trait be made Sync?

### ISSUE THREAD

**Issue by dvic** [apache/arrow-rs#5344]
**Problem**

I encountered an issue when working with async functions and storing a `Box<dyn ArrayBuilder>` (explicitly using `Box<dyn ArrayBuilder + Sync>` solved the issue.

**Proposed solution**

I noticed that currently ArrayBuilder is `ArrayBuilder: Any + Send`, but we can make that into `ArrayBuilder: Any + Send + Sync` can't we? I just tried it locally and `cargo check` didn't give any errors.

**Alternatives**
Manually specifying the `Sync` bound

**Comment by tustvold** [comment]
I don't see any issues with this, but a mutable container shouldn't need to be Sync, only Send. You can't do much useful with a shared reference to an ArrayBuilder

**Comment by dvic** [comment]
Hmm I might be confusing then something else, it seems that Vec<Box<...>> is requiring this

```rust
error[E0277]: `(dyn arrow_array::builder::ArrayBuilder + 'static)` cannot be shared between threads safely
   --> src/main.rs:89:5
    |
89  |     tokio::spawn(f);
    |     ^^^^^^^^^^^^ `(dyn arrow_array::builder::ArrayBuilder + 'static)` cannot be shared between threads safely
    |
    = help: the trait `Sync` is not implemented for `(dyn arrow_array::builder::ArrayBuilder + 'static)`
    = note: required for `Unique<(dyn arrow_array::builder::ArrayBuilder + 'static)>` to implement `Sync`
note: required because it appears within the type `Box<dyn ArrayBuilder>`
   --> /Users/dvic/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:195:12
    |
195 | pub struct Box<
    |            ^^^
    = note: required for `Unique<Box<(dyn arrow_array::builder::ArrayBuilder + 'static)>>` to implement `Sync`
note: required because it appears within the type `RawVec<Box<dyn ArrayBuilder>>`
   --> /Users/dvic/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/raw_vec.rs:51:19
    |
51  | pub(crate) struct RawVec<T, A: Allocator = Global> {
    |                   ^^^^^^
note: required because it appears within the type `Vec<Box<dyn ArrayBuilder>>`
   --> /Users/dvic/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:396:12
    |
396 | pub struct Vec<T, #[unstable(feature = "allocator_api", issue = "32838")] A: Allocator = Global> {
    |            ^^^
note: required because it appears within the type `UpsertsBuilder`
   --> /Users/dvic/Development/qamion/src/ticketmatic.rs:196:8
    |
196 | struct UpsertsBuilder {
    |        ^^^^^^^^^^^^^^
note: required because it appears within the type `TableState<1>`
```

`UpsertsBuilder` contains `Vec<Box<dyn ArrayBuilder>>`

**Comment by tustvold** [comment]
The following compiles for me

```
async fn spawn_builders(schema: &SchemaRef) {
    let builders: Vec<_> = schema.fields.iter().map(|f| make_builder(f.data_type(), 1024)).collect();
    tokio::spawn(async move {
        drop(builders)
    });
}
```

Is it possible that `f` is borrowing the builders `Vec` instead of moving it?

**Comment by dvic** [comment]
I can't replicate the compile error current in my code because I switched things around. I'll see if I can produce a standalone example. If you don't see any value in adding the `Sync` feel free to close the issue for now.

**Comment by Xuanwo** [comment]
I agree with @tustvold that adding `Sync` doesn't make sense for `ArrayBuilder`, which only has mutable APIs. In this case, all `Box<dyn ArrayBuilder>` are already `Sync`.

**Comment by tustvold** [comment]
Yes, that would cause the compilation errors, I suppose you could also call finish_cloned as well :thinking: 

We can probably add `Sync` without it causing too much downstream pain

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5353
