### ISSUE TITLE
Buffer memory usage for custom allocations is reported as 0

### ISSUE THREAD

**Issue by jhorstmann** [apache/arrow-rs#5346]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

**Describe the solution you'd like**

I'd like to keep track of the buffer length in `Buffer::from_custom_allocation` in order to more accurately report the memory usage of arrays created from custom allocations.

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5347
