### ISSUE TITLE
get_buffer_memory_size() returns an incorrect larger size

### ISSUE THREAD

**Issue by Yifeng-Sigma** [apache/arrow-rs#5352]
**Which part is this question about**

Question about `get_buffer_memory_size()` method

**Describe your question**

We have an arrow chunk which consists of two columns, all generic string type. 
If we use `value()` method to pull out each string value and add up, the total size is 108684 bytes.
If we use `value_data().len()`, gives us 108684 bytes
If we use `value_offsets().len()` gives us 5430 bytes
But use `get_buffer_memory_size()` gives us 521664 bytes
NullBuffer is 0.

Noticed that the implementation of `get_buffer_memory_size()` is basically to add up `value_offsets`, `value_data` and null buffer. But why there's a significant difference? Here 108684 is what we expect. 

**Additional context**

**Comment by Jefffrey** [comment]
I think this PR might help clear up confusion, as it enhances the docstring of `get_buffer_memory_size()`: https://github.com/apache/arrow-rs/pull/5347

```rust
    /// Note that this does not always correspond to the exact memory usage of an array,
    /// since multiple arrays can share the same buffers or slices thereof.
```

Note that `value_data().len()` gives the len, i.e. how many bytes are used in the buffer, whilst `get_buffer_memory_size()` calculates using the capacity of the buffer (how much memory is allocated to it), which might be larger than the len:

https://github.com/apache/arrow-rs/blob/31cf5ce23febf076104f064358a24fe8af09ee4b/arrow-array/src/array/byte_array.rs#L464-L471

This should help explain the discrepancy.

**Comment by tustvold** [comment]
To further expand on the above, the IPC reader avoids copying by slicing buffers, and this I'd a common source of arrays with such shared buffers

**Comment by tustvold** [comment]
There is https://docs.rs/arrow-data/latest/arrow_data/struct.ArrayData.html#method.get_slice_memory_size but if you're only interested in strings you could do something like

```
let offsets = array.offsets();
let total_length = offsets.last().unwrap().as_usize() - offsets.first().unwrap().as_usize();
```

**Comment by Yifeng-Sigma** [comment]
> There is https://docs.rs/arrow-data/latest/arrow_data/struct.ArrayData.html#method.get_slice_memory_size but if you're only interested in strings you could do something like
> 
> ```
> let offsets = array.offsets();
> let total_length = offsets.last().unwrap().as_usize() - offsets.first().unwrap().as_usize();
> ```
> 
> I should highlight that this will ignore the overheads from encoding field names in JSON though, and will be a pretty crude approximation.

We are interested in types other than string as well. get_slice_memory_size() is exactly what I'm looking for! 
Seems only `get_buffer_memory_size()` and `get_array_memory_size` are implemented for array, but get_slice_memory_size() is implemented for `ArrayData` only, wondering what's the recommendation for array here?

**Comment by tustvold** [comment]
You can call `Array::data` to convert to the `ArrayData` representation

**Comment by tustvold** [comment]
Clone is cheap on buffers, as the underlying storage is reference counted.
