### ISSUE TITLE
Parquet: Match generated RecordBatch number of rows to Parquet row group size 

### ISSUE THREAD

**Issue by kylebarron** [apache/arrow-rs#5356]
**Which part is this question about**

Parquet record batch reader row group size

**Describe your question**

I have a use case where the size of each RecordBatch is chosen very intentionally by the writer (pyarrow). In this case, pyarrow writes each Arrow RecordBatch to a single Parquet row group. But it appears impossible with the `parquet` crate to recreate a sequence of RecordBatches with the same original row groups. In particular [`with_batch_size`](https://docs.rs/parquet/latest/parquet/arrow/arrow_reader/struct.ArrowReaderBuilder.html#method.with_batch_size) will default to `1024` if unset, and there appears no way to match the row group size.

Coming from other Parquet implementations like pyarrow and arrow2, it seems surprising to not have this option.

**Additional context**

I asked this [here on discord](https://discord.com/channels/885562378132000778/885562378132000781/1193645000957886494) but didn't really get a satisfactory answer. I understand that for e.g. DataFusion use cases it's very valuable to push down row filtering to the page level, but feel there should be _some way_ to recreate Arrow batches.

Related to this issue on the writing side: https://github.com/apache/arrow-rs/issues/5004.

**Comment by tustvold** [comment]
I would suggest that decoding entire RowGroups at a time is a recipe for either blowing your memory budget or creating row groups that are far too small.

However, you could use https://docs.rs/parquet/latest/parquet/arrow/arrow_reader/struct.ArrowReaderBuilder.html#method.new_with_metadata to explicitly read a single row group at a time

**Comment by kylebarron** [comment]
> or relying on row groups that are far too small.

What ballpark do you think of for optimal size row groups?

**Comment by tustvold** [comment]
You would typically be aiming for pages of around 1MB, so ideally no smaller than 1MB per column in the schema.

**Comment by tustvold** [comment]
Closing as I believe the question has been answered
