### ISSUE TITLE
Support check similar datatype but with different magnitudes

### ISSUE THREAD

**Issue by Weijun-H** [apache/arrow-rs#5358]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

In the original post by https://github.com/apache/arrow-datafusion/issues/9093#issue-2111248281, we found arrow-rs doesn't provide a way to check `DataType` with similar type but magnitudes

**Describe the solution you'd like**

Add a function `equal_similar_type` in DataType

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5359
