### ISSUE TITLE
Support `PrimitiveTypeBuilder` when Logical type is `Timestamp` and Physical type is `BYTE_ARRAY`

### ISSUE THREAD

**Issue by Weijun-H** [apache/arrow-rs#5365]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I got an error when I was trying to build `PrimitiveTypeBuilder ` on https://github.com/apache/arrow-datafusion/pull/9129.

```
thread 'datasource::physical_plan::parquet::row_groups::tests::row_group_pruning_predicate_timestamp' panicked at datafusion/core/src/datasource/physical_plan/parquet/row_groups.rs:1206:42:
called `Result::unwrap()` on an `Err` value: General("Cannot annotate Timestamp { is_adjusted_to_u_t_c: false, unit: NANOS(NanoSeconds) } from BYTE_ARRAY for field 'c1'")
```

**Describe the solution you'd like**

Add `(LogicalType::Timestamp { _, _}, PhysicalType::BYTE_ARRAY)=>{}` in 

https://github.com/apache/arrow-rs/blob/bd19a624469df652f24ee37b65056535ff665769/parquet/src/schema/types.rs#L303-L309
**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
The parquet logical type for timestamps can only annotate an int64 - https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#timestamp
