### ISSUE TITLE
Update Flight proto

### ISSUE THREAD

**Issue by Jefffrey** [apache/arrow-rs#5367]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

From mailing list: https://lists.apache.org/thread/4t664cj5z52brmbshjb6gknfq30ckhcn

> Now, here lies the issue: neither FlightEndpoint nor the FlightInfo message in the arrow.flight.protocol.rs file of arrow-rs includes an 'app_metadata' field (It seems outdated). Consequently, I am currently facing a roadblock.
Is there a plan to update the flight implementation of arrow-rs?

Need to update the Flight & FlightSql proto as they are outdated.

See arrow source:

- https://github.com/apache/arrow/blob/0993b369c4b91d81a17166d1427e7c26cd9beee4/format/Flight.proto
- https://github.com/apache/arrow/blob/0993b369c4b91d81a17166d1427e7c26cd9beee4/format/FlightSql.proto

**Describe the solution you'd like**

Update format files and generated code (and interop code, refer to PR below for previous example)

**Describe alternatives you've considered**

**Additional context**

For reference, last update PR: https://github.com/apache/arrow-rs/pull/4250

**Comment by Jefffrey** [comment]
I can take a stab at this next week or so, unless someone else is interested in picking this up :eyes:

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5413

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow-flight'} from #5413
