### ISSUE TITLE
Support for additional URL formats in object_store for Azure blob

### ISSUE THREAD

**Issue by bradvoth** [apache/arrow-rs#5370]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
In azure storage blobs can be referred to with a URL format like: `https://<account>.blob.core.windows.net/<container>/...`

**Describe the solution you'd like**
I would like to be able to use the `from_url` method on `MicrosoftAzureBuilder` to construct a `MicrosoftAzure` instance including the container name directly from a URL in this format.

**Describe alternatives you've considered**
I currently have built a parser that will do this as an extra layer in my application.

**Additional context**
None?

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #5371

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5370](https://github.com/apache/arrow-rs/issues/5370)
