### ISSUE TITLE
Add a mutable builder for `Offset`s

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#5384]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Part of a discussion in Discord: https://discord.com/channels/885562378132000778/885562378132000781/1205552581422878730

@kylebarron  notes that arrow-rs has an immutable [`OffsetBuffer`](https://docs.rs/arrow-buffer/latest/arrow_buffer/buffer/struct.OffsetBuffer.html) but no mutable builder counterpart. 

arrow2 had a mutable builder called [`Offsets`](https://docs.rs/arrow2/latest/arrow2/offset/struct.Offsets.html) to help building up the offsets, with helpers like try_push_usize that would enforce the monotonically increasing invariant

As part of his  arrow2 -> arrow-rs conversion he vendored that builder in my own code https://github.com/geoarrow/geoarrow-rs/blob/011e77736ac25c55141608c135852c1f5d3198dd/src/array/offset_builder.rs

**Describe the solution you'd like**
Consider upstreaming `OffsetBuilder` into arrow-rs

**Describe alternatives you've considered**
We can leave the current situation alone.

**Additional context**

**Comment by alamb** [comment]
FWIW I built the offsets directly via `Vec<O>` while working on a native string grouping accumulator in https://github.com/apache/arrow-datafusion/pull/8827 but having an Offsets builder would likely have made the code more convenient and easier to follow.

**Comment by doki23** [comment]
When I try to implement `fn try_push_length(&mut self, length: O)`, I'd hope that `O: ArrowNativeType` implements trait `std::ops::Add` so that I can got next `offset` by `offset + length`. So maybe we need a PR which makes the trait `ArrowNativeType` extends `std::ops::Add` first?

**Comment by alamb** [comment]
The code in geoarrow seems to use to `from_usize` / `to_usize` to convert to/from usize and `O`:

https://github.com/geoarrow/geoarrow-rs/blob/011e77736ac25c55141608c135852c1f5d3198dd/src/array/offset_builder.rs#L122-L130

**Comment by doki23** [comment]
I notice that `geoarrow-rs` uses `OffsetSizeTrait` instead of `ArrowNativeType` which implements `std::ops::AddAssign`.

**Comment by tustvold** [comment]
Given OffsetBuffer is used to track offsets within what is effectively a `Vec<usize>`, and the offets must be monotonically increasing, I would recommend consistently using `usize` in the interface. This is not only simpler, but easier to use.

**Comment by doki23** [comment]
As the [discussion](https://github.com/apache/arrow-rs/pull/5440/files#r1504609930), `Vec<usize>` causes the conversion from builder to buffer to require O(n) complexity.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5440
