### ISSUE TITLE
Make ffi consume variable layout arrays with empty offsets

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#5391]
**Describe the bug**

We encountered an error when exchanging string array from Java to Rust through Arrow C data interface. At Rust side, it complains that the buffer at position 1 (offset buffer) is null. After tracing down and some debugging, it looks like the issue is Java Arrow `BaseVariableWidthVector` class assigns an empty offset buffer if the array is empty (value count 0).

First, I thought it is a bug at Java Arrow (https://github.com/apache/arrow/pull/40043). But given some additional context:

https://lists.apache.org/thread/w7g1zfqrjxx0bvrct0mt5zwxvdnc9nob
https://github.com/apache/arrow-rs/issues/1620

Looks like Arrow allows empty offsets.

This is how we did in `ArrayData`.

So for ffi, we probably need to make it able to consume variable layout arrays with empty offset. Otherwise, we cannot pass valid arrays into this crate using Arrow C data interface.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by pitrou** [comment]
Arrow C++ will not allow this either: https://github.com/apache/arrow/blob/135b3640665992457ff39acdedab3a6d19bd00f2/cpp/src/arrow/c/bridge.cc#L1847-L1848

**Comment by viirya** [comment]
Interesting. Then I was mislead or confused by the comments at the Java PR. 😅

**Comment by viirya** [comment]
For who are interested, some more discussion happens in the Java PR (https://github.com/apache/arrow/pull/40043). This null offset buffer looks like something disallowed in Arrow. And needs to be fixed at Java Arrow C data interface, I think.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5392
