### ISSUE TITLE
Cast kernel doesn't return null for string to integral cases when overflowing under safe option enabled

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#5397]
**Describe the bug**

We found that cast kernel doesn't return null for string to integral cases when overflowing: https://github.com/apache/arrow-datafusion-comet/issues/15

`lexical_core` parser doesn't actually do the overflow check.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5398
