### ISSUE TITLE
[object-store] hide sensitive information in error messages

### ISSUE THREAD

**Issue by ritchie46** [apache/arrow-rs#5400]
Taken from https://github.com/coiled/benchmarks/pull/1394.

If accessing s3 fails somehow due to incorrect/misconfigured variables the secrets are shown in the error messages. It's probably better to mask them out by default.

**Comment by tustvold** [comment]
The only thing I can see in the error message is AWSAccessKeyId which is not a secret, and is known to the calling process anyway? What am I missing here?

**Comment by ritchie46** [comment]
Oh.. fair enough. I didn't actually check that. You are right. That's not secret.
