### ISSUE TITLE
Prmitive casts to floats are not handled properly

### ISSUE THREAD

**Issue by psvri** [apache/arrow-rs#5403]
**Describe the bug**
Realised this while playing around with datafusion that we are not handling conversion from primitve types like uint32/int32 to float32 is not handled properly and can result in loss of precision as shown below.
```
❯ select arrow_cast(arrow_cast(4294967295, 'UInt32'), 'Float32');
+-------------------+
| Int64(4294967295) |
+-------------------+
| 4294967300.0      |
+-------------------+
```

**To Reproduce**
```
let array = UInt32Array::from(vec![10, 20, u32::MAX, u32::MIN]);
let b = cast(&array, &DataType::Float32).unwrap();
let c = b.as_primitive::<Float32Type>();
assert!(!c.is_valid(2)); // This assertion fails here
```

**Expected behavior**
A panic or error should be thrown

**Additional context**

We are internally using num traits for the conversion of types and [they consider loss of precision to be valid](https://github.com/rust-num/num-traits/issues/175#issuecomment-653918603) .

I want to work on this but before I start I want to confirm with the community if the above is expected or we should fix this ?

**Comment by tustvold** [comment]
This is expected, floats are inherently lossy, if you require guaranteed precision you should use decimals

**Comment by psvri** [comment]
Yes, but out of the box I would expect the value to be none in those cases since overflows return none and are not saturated, I was thinking we should do the same here as well.

**Comment by tustvold** [comment]
The expectation of a floating point type is that you are happy for precision loss to occur, it's an inherent property of the representation. If we disallowed this it would prevent casting integers to floats larger than a given magnitude, which would be surprising and a major functionality regression

**Comment by psvri** [comment]
Okay, Thanks for the info
