### ISSUE TITLE
delete_stream fails in MinIO

### ISSUE THREAD

**Issue by paraseba** [apache/arrow-rs#5414]
Running `delete_stream` against a MinIO deployment runs into

> Missing required header for this request: Content-Md5.

**Additional context**

S3 API [specification](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html) requires the presence of this header for all `DeleteObjects` requests to general purpose buckets:

> The Content-MD5 request header is required for all Multi-Object Delete requests

AWS does in fact accept the request without the header, but object_store should include it for compatibility with the spec and other platforms.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #5415

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5414](https://github.com/apache/arrow-rs/issues/5414)
