### ISSUE TITLE
[object_store] Enable anonymous read access for Azure

### ISSUE THREAD

**Issue by andrebsguedes** [apache/arrow-rs#5424]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently we are unable to use `object_store` without authorization on Azure, as not providing credentials defaults to fetching managed identity tokens. Skipping authorization is required for interacting with public containers that allow anonymous read access.

Another related problem is that when `use_emulator` is `true` we again cannot disable the credentials and are unable to test for missing credential scenarios or test anonymous read access.

**Describe the solution you'd like**

Introduction of two configs to allow for _no authorization_ behavior:
- `azure_skip_signature`: This disables the injection of the Authorization header in the request, just like its S3 counterpart.
- `azure_disable_emulator_key`: This disables the default of using the EMULATOR_KEY when no credentials are provided in emulator mode. 

**Describe alternatives you've considered**

I could not find a way to disable credentials.

**Additional context**

The proposed solution does not introduce a breaking change.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #5425

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5424](https://github.com/apache/arrow-rs/issues/5424)
