### ISSUE TITLE
MicrosoftAzure store list result omits empty objects

### ISSUE THREAD

**Issue by andrebsguedes** [apache/arrow-rs#5451]
**Describe the bug**

Due to a workaround for gen2 accounts with hierarchical namespaces, the list operation filters out objects that have zero size  when using `object_store::azure::MicrosoftAzure` store.

The behavior is inconsistent with other stores as `AmazonS3` properly returns empty blobs.

**To Reproduce**

Execute a list operation on a container with empty blobs with `MicrosoftAzure` store.

**Expected behavior**

Empty blobs are returned on the list operation result.

**Additional context**

In order to correctly filter out any directory entries on the list result when hierarchical namespaces are enabled we should check if the `ResourceType` blob property is not `directory`.

**Comment by tustvold** [comment]
ResourceType returns an error if specified against a non-gen2 bucket unfortunately

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #5452

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5451](https://github.com/apache/arrow-rs/issues/5451)
