### ISSUE TITLE
Release arrow-rs / parquet version (`51.0.0` or `50.1.0`)

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#5453]
## Is your feature request related to a problem or challenge? Please describe what you are trying to do.
50.0.0 [was released](https://github.com/apache/arrow-rs/issues/5234) about 2 months ago: https://crates.io/crates/arrow/50.0.0 (Jan 12, 2024)

## Describe the solution you'd like
I would like to release the next version (`51.0.0` or `50.1.0` if there are no API changes) with the accumulated changes since then

## Additional context

**Comment by alamb** [comment]
I am happy to help with the logistics of this release

I don't think it is blocked on the object store release (which is minor) https://github.com/apache/arrow-rs/issues/5436

I filed this ticket as I saw https://github.com/apache/arrow-rs/pull/5293 which looks like a useful feature

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #5293

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5505
