### ISSUE TITLE
object store ApplicationDefaultCredentials auth is not working on windows 

### ISSUE THREAD

**Issue by itay-jether** [apache/arrow-rs#5466]
Object store default authentication (ApplicationDefaultCredentials) works with looks for a json file, which on linusx is on usually on `~/.config/gcloud/application_default_credentials.json`. The path is determined by using concatentating the path of `HOME`  environment variable with the string `.config/gcloud/application_default_credentials.json`

However, on windows it can be in other paths, like `C:\Users\[User]\AppData\Roaming\gcloud` directory, the directroy can be retrieved by `gcloud info`, under 'User Config Directory'.

**Comment by tustvold** [comment]
I'm afraid I don't have a windows machine on which to test this, but would welcome a PR. I presume this information must be encoded in the environment somehow

**Comment by Xuanwo** [comment]
> However, on windows it can be in other paths, like `C:\Users\[User]\AppData\Roaming\gcloud` directory, the directroy can be retrieved by `gcloud info`, under 'User Config Directory'.

On windows, we should read `%APPDATA%\gcloud\application_default_credentials.json` instead.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #5473

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5466](https://github.com/apache/arrow-rs/issues/5466)
