### ISSUE TITLE
Add `DataType::Utf8View` and `DataType::BinaryView`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#5468]
This is part of the larger project to implement `StringViewArray` -- see https://github.com/apache/arrow-rs/issues/5374

The first thing we will need is a new variant in `DataType` to support this type

So the basic task is to
1. Add the appropriate variants in `DataType`
2. Update the rest of arrow-rs to handle that new variant (largely would be an exercise in returning `NotYetImplemented` errors)

For inspiration I think you can look at https://github.com/apache/arrow-rs/pull/4585 (specifically `types.rs` https://github.com/apache/arrow-rs/pull/4585/files#diff-ff91e9fd06b025009cc1d0f9360ecdb8c3d9ea972e8f87b4419eab01e1e8fb7c)

I reviewed the Arrow spec that was approved and there does not appear to be any equivalent to `LargeUtf8` (e.g there is no `LargeUtf8View`): 

https://github.com/apache/arrow/blob/c4e088a1d6227868e020c71d596970f35bb9e4c9/format/Schema.fbs#L187-L205

**Comment by alamb** [comment]
FYI @ariesdevil

**Comment by XiangpengHao** [comment]
I can work on this if no one else is working on it.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #5470

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5470
