### ISSUE TITLE
 object_store 0.9.1 breaks Azure Storage Emulator Config

### ISSUE THREAD

**Issue by aersam** [apache/arrow-rs#5475]
delta-rs is using this config to connect to Azure Storage Emulator:

```python
dict(
        AZURE_STORAGE_ACCOUNT_NAME="devstoreaccount1",
        AZURE_STORAGE_ACCOUNT_KEY="Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==",
        AZURE_STORAGE_CONTAINER_NAME="deltars",
        AZURE_STORAGE_USE_EMULATOR="true",
        AZURE_STORAGE_USE_HTTP="true",
    )
```

this is passed via python, but it basically just sets the configs in object_store.

In 0.9.1, this started to cause an authentication error:

```
E       OSError: Generic MicrosoftAzure error: Client error with status 403 Forbidden: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
E       <Error>
E         <Code>AuthorizationFailure</Code>
E         <Message>Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.
E       RequestId:44a1c5ff-8a6b-491a-a890-e07d0d823e87
E       Time:2024-03-05T11:31:55.140Z</Message>
E       </Error>
```

 Can you check this?

Since there was a change in Azure Authentication in object_store 0.9.1, is there some different config required? I was assuming a bug since it's only a minor version increase and the config looks good

**Comment by tustvold** [comment]
This is likely related to https://github.com/apache/arrow-rs/pull/5425

**Comment by andrebsguedes** [comment]
@aersam The current version of `object_store` respects other kind of credentials that were being ignored before. So if your test code is passing a dummy SAS token or bearer token it will fail to authenticate.

I saw [this kind of pattern](https://github.com/delta-io/delta-rs/blob/d8366cfdc9eda68aa7ef1cd4ef5ff5c6ea55d5de/crates/azure/tests/context.rs#L84) on your repo, could that be an example of this?

**Comment by ion-elgreco** [comment]
@andrebsguedes @tustvold the test fails in our python integration tests. I checked but we don't have any env variables set for azure while this test is being executed

**Comment by giacomorebecchi** [comment]
Hi @ion-elgreco, I deep-dived into this as I'm looking to upgrade my `deltalake` dep in python, but some integration tests using `azurite` with code-generated SAS tokens started failing.

Basically, in `object-store==0.9.0`, when `use_emulator="true"`, an account key is always passed, and the SAS token is ignored:
https://github.com/apache/arrow-rs/blob/cb16050ec732872d5995c7420cc6858749bbf743/object_store/src/azure/builder.rs#L801-L811
whereas, in `object-store==0.9.1`, the actual SAS token is passed:
https://github.com/apache/arrow-rs/blob/30151220c29fa5e01365c2a4e153de01d5d2c041/object_store/src/azure/builder.rs#L826-L846

Thus, I suspect that the issue you are encountering is rather linked to this issue:
- https://github.com/Azure/Azurite/issues/1263

I'll try to implement the fix to create a valid SAS token in my repo, and, if it works, I will try to open a PR also on `delta-rs`!

**Comment by ion-elgreco** [comment]
@giacomorebecchi Cool! Just ping me when you push a PR in Delta-RS 😄
