### ISSUE TITLE
Unused import in nightly rust

### ISSUE THREAD

**Issue by XiangpengHao** [apache/arrow-rs#5476]
**Describe the bug**

With this pr been merged to nightly rust: https://github.com/rust-lang/rust/pull/117772
The tracking for unused import has been improved, resulting numerous compiler warnings when building arrow-rs with nightly rust.

**To Reproduce**

```rust
rustup default nightly
cargo check
```

**Expected behavior**

**Additional context**

**Comment by XiangpengHao** [comment]
Maybe it should be a `feature request` not `bug`...

**Comment by Kikkon** [comment]
Hi, @tustvold . Following the above method.  I have reproduced the issue on my machine, and there are  over 40 warnings. I think i can submit a pull request to clean up these unused import ?

**Comment by tustvold** [comment]
I believe this is already being worked on in https://github.com/apache/arrow-rs/pull/5477

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #5477

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5477

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow-flight'} from #5477

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet-derive'} from #5477
