### ISSUE TITLE
Support Creating Non-Nullable Lists and Maps within a Struct

### ISSUE THREAD

**Issue by lasantosr** [apache/arrow-rs#5482]
**Describe the bug**

When I try to write a Map with non-nullable values into parquet, an error happens. This is similar to https://github.com/apache/arrow-rs/issues/5330.

Also, when I try to write an Struct that contains any List or Map with null able values, the same error happens.

**Expected behavior**

The data is properly written.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5483
