### ISSUE TITLE
Improve documentation around handling of dictionary arrays in arrow flight

### ISSUE THREAD

**Issue by thinkharderdev** [apache/arrow-rs#5487]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Documentation around handling of dictionary arrays in arrow flight is confusing. 

**Describe the solution you'd like**

Improve doc comments so it is more clear how it works and what the different options mean concretely

**Describe alternatives you've considered**

Leave people confused and let them figure it out through trial and error like I did :)

**Additional context**

**Comment by alamb** [comment]
Related slack thread: https://the-asf.slack.com/archives/C01QUFS30TD/p1709986070881859?thread_ts=1709815827.985999&cid=C01QUFS30TD

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5488

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow-flight'} from #5488
