### ISSUE TITLE
Unable to access builder on List type column with List<Struct> type of field. 

### ISSUE THREAD

**Issue by istvan-fodor** [apache/arrow-rs#5494]
Hi All,
As per @alamb 's advice, I am cross posting my question from Discord. 

I have a question about how to use ListBuilders with StructBuilders. 

I am building an array that has a column with a list type. There are structs in the list. When I create a builder for the column, I am unable to append to it. Whenever I try to get a field builder for the structs, I am unable to do so. 

I debugged through StructBuilder::make_builder and seems like everything is correctly created (List builder with StructBuilder type). I am attaching a small snippet that reproduces my issue. Any advice is very much appreciated! Thanks! 

Here is an example code to reproduce my issue:

```rust
use arrow::datatypes::{DataType, Field, Fields};
use std::sync::Arc;

fn main() {
    let mut status = arrow::array::builder::ListBuilder::new(
        arrow::array::StructBuilder::from_fields(status_schema(), 0),
    );

    let mut struct_builder: &mut arrow::array::StructBuilder = status.values();

    let mut list_builder_option = struct_builder
        .field_builder::<arrow::array::builder::ListBuilder<arrow::array::StructBuilder>>(1usize)
        .unwrap();
}

pub fn status_schema() -> Vec<Field> {
    vec![
        Field::new("id", DataType::Utf8, true),
        Field::new(
            "values",
            DataType::List(Arc::new(Field::new(
                "item",
                DataType::Struct(Fields::from(key_value_schema())),
                true,
            ))),
            true,
        ),
    ]
}
pub fn key_value_schema() -> Vec<Field> {
    vec![
        Field::new("key", DataType::Utf8, true),
        Field::new("value", DataType::Utf8, true),
    ]
}
```

The line `let mut list_builder_option = struct_builder.field_builder::<arrow::array::builder::ListBuilder<arrow::array::StructBuilder>>(1usize).unwrap();` panics. I expected it to to return a builder where I can start adding the struct fields.

**Comment by tustvold** [comment]
Ok so the issue here is that whilst #5109 added support for lists within make_builder, it did so by implementing `ArrayBuilder` for `Box<dyn ArrayBuilder>`.

What this means is that `StructBuilder` actually creates a `ListBuilder<Box<dyn ArrayBuilder>>` instead of `ListBuilder<StructArray>`. 

There are a couple of ways to solve this:

* Use `struct_builder.field_builder::<ListBuilder<Box<dyn ArrayBuilder>>>(1usize).unwrap()`
* Manually create the `ListBuilder<StructArray>` and use `StructBuilder::new`

We should definitely better document this, I was not aware of this behaviour myself

**Comment by istvan-fodor** [comment]
Hi @tustvold ,
Is there a way to cast the result to a ListBuilder<StructBuilder> or ListBuilder<Box<StructBuilder>> ? 

I tried this and it fails on the unwrap: 
```rust
    let mut list_builder_option = struct_builder
        .field_builder::<arrow::array::builder::ListBuilder<Box<dyn arrow::array::ArrayBuilder>>>(
            1usize,
        )
        .unwrap();

    let mut list_struct_builder = list_builder_option
        .as_any_mut()
        .downcast_mut::<arrow::array::builder::ListBuilder<arrow::array::StructBuilder>>()
        .unwrap();
} 
```

Downcasting with `<arrow::array::builder::ListBuilder<Box<arrow::array::StructBuilder>>>` outright fails compilation.

**Comment by tustvold** [comment]
No, Rust sees them as completely independent types

**Comment by istvan-fodor** [comment]
@tustvold @alamb I was able to get this to work with the following code. Took the Box<any ArrayBuilder> and downcasted it.

```rust
use arrow::{
    array::{ArrayBuilder, StructBuilder},
    datatypes::{DataType, Field, Fields},
};
use std::sync::Arc;

fn main() {
    let mut status = arrow::array::builder::ListBuilder::new(
        arrow::array::StructBuilder::from_fields(status_schema(), 0),
    );

    let mut struct_builder: &mut arrow::array::StructBuilder = status.values();

    let mut list_builder_option = struct_builder
        .field_builder::<arrow::array::builder::ListBuilder<Box<dyn arrow::array::ArrayBuilder>>>(
            1usize,
        );
    let mut struct_builder = list_builder_option.as_mut().unwrap();
    let mut struct_builder: &mut arrow::array::StructBuilder = struct_builder
        .values()
        .as_any_mut()
        .downcast_mut::<StructBuilder>()
        .unwrap();
}

pub fn status_schema() -> Vec<Field> {
    vec![
        Field::new("id", DataType::Utf8, true),
        Field::new(
            "values",
            DataType::List(Arc::new(Field::new(
                "item",
                DataType::Struct(Fields::from(key_value_schema())),
                true,
            ))),
            true,
        ),
    ]
}
pub fn key_value_schema() -> Vec<Field> {
    vec![
        Field::new("key", DataType::Utf8, true),
        Field::new("value", DataType::Utf8, true),
    ]
}

```

**Comment by alamb** [comment]
@istvan-fodor is there any way you might be willing to make a PR to improve the documentation in arrow-rs to help future users ?

**Comment by istvan-fodor** [comment]
@alamb , yes I can do that. Also, I can put together some example code if that's helpful.

**Comment by tustvold** [comment]
I think we should probably document this as a doc comment on StructBuilder

**Comment by alamb** [comment]
Thank you so much @istvan-fodor  🙏
