### ISSUE TITLE
Prototype Arrow over HTTP in Rust

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#5496]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
@ianmcook  is working to prototype a protocol for sending Arrow over HTTP (rather than gRPC)

I would like to make sure that whatever is added to the arrow spec also works within the Rust ecosystem / tonic/hyper ecosystem

Mailing List Discussion https://lists.apache.org/thread/vfz74gv1knnhjdkro47shzd1z5g5ggnf

**Describe the solution you'd like**

Implement a server example that works in rust, with the clients from 

> So far there are client examples in six languages and server examples
> in two languages (Python and Go). They all have READMEs describing how
> to use them.

https://github.com/apache/arrow-experiments/tree/main/http

Here is a PR with a Java proposal:  https://github.com/apache/arrow-experiments/pull/4

**Describe alternatives you've considered**
Wait for the spec to be finalized and then implement it in Rust

**Additional context**

**Comment by mbrobbel** [comment]
https://github.com/apache/arrow-experiments/pull/8

**Comment by alamb** [comment]
> [apache/arrow-experiments#8](https://github.com/apache/arrow-experiments/pull/8)

Thanks @mbrobbel  -- I hadn't seen that 🙏  -- thank you

**Comment by ianmcook** [comment]
Closed by https://github.com/apache/arrow-experiments/pull/8

I hope we can update the examples to use [hyper](https://hyper.rs) after #1207 is done.

**Comment by alamb** [comment]
Sorry -- I should have known the arrow community was already on this. Thanks a lot
