### ISSUE TITLE
`filter` kernel support for `StringViewArray` and `BinaryViewArray`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#5510]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
This is part of the larger project to implement `StringViewArray` -- see https://github.com/apache/arrow-rs/issues/5374

In https://github.com/apache/arrow-rs/pull/5481 we added support for `StringViewArray` and `ByteViewArray`.

This ticket tracks supporting `StringViewArray` and `ByteViewArray` in the `filter` kernel: https://docs.rs/arrow/latest/arrow/compute/kernels/filter/index.html

**Describe the solution you'd like**
1. Support `StringViewArray` and `ByteViewArray`  the filter kernel
2. Add tests

Notes: 
1. you should be able to follow the model of `DictionaryArray` as the idea is similar
2. Filtering should *not* copy any strings, it should just manipulate the fixed size views

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5481
