### ISSUE TITLE
Why write to azure onelake with object store will change the SSL environment variable？

### ISSUE THREAD

**Issue by RobinLin666** [apache/arrow-rs#5517]
**Describe the bug**
Why write to azure onelake with object store will change the SSL environment variable？
<img width="1490" alt="image" src="https://github.com/apache/arrow-rs/assets/128118209/23434cf4-4d61-425c-9e01-25ed759c6655">

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by tustvold** [comment]
Perhaps you might file an issue upstream on delta-rs, I suspect the issue may be in that codebase

**Comment by RobinLin666** [comment]
from the delta-rs code, it called arrow-rs object_store::azure apis, so, I filed here.

**Comment by tustvold** [comment]
This is correct, but I am fairly certain we don't override environment variables, and so I suspect this is a behaviour of code within delta-rs

**Comment by ion-elgreco** [comment]
@RobinLin666 can you change the write to engine="rust", then we can narrow it down a bit

**Comment by RobinLin666** [comment]
> @RobinLin666 can you change the write to engine="rust", then we can narrow it down a bit

<img width="1165" alt="image" src="https://github.com/apache/arrow-rs/assets/128118209/19a3a954-b134-4ddd-9db7-042e2ba317e6">

**Comment by ion-elgreco** [comment]
@RobinLin666  It doesn't reset for me, but it also doesn't work in general..

```python
import pandas as pd
from deltalake import DeltaTable, write_deltalake
df = pd.DataFrame({"id":[1,2], "value": ["foo", "boo"]})

!echo $SSL_CERT_DIR
!echo $SSL_CERT_FILE
!echo $REQUESTS_CA_BUNDLE

try:
    write_deltalake(
        "abfss://<redacted>@onelake.dfs.fabric.microsoft.com/<redacted>/Tables/new_delta", 
        df, 
        mode='overwrite',
        storage_options={"bearer_token": mssparkutils.credentials.getToken("storage"),"use_fabric_endpoint": "true"} )
except Exception as e:
    print(e)
    pass

!echo $SSL_CERT_DIR
!echo $SSL_CERT_FILE
!echo $REQUESTS_CA_BUNDLE
```

```
/etc/pki/ca-trust/extracted/openssl:/opt/olcclient

/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt

Generic MicrosoftAzure error: Error after 10 retries in 3.226602633s, max_retries:10, retry_timeout:180s, source:error sending request for url (https://onelake.blob.fabric.microsoft.com/<redacted>/<redacted>/Tables/new_delta/_delta_log/_last_checkpoint): error trying to connect: invalid peer certificate: UnknownIssuer

/etc/pki/ca-trust/extracted/openssl:/opt/olcclient

/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
```

**Comment by cmettler** [comment]
@ion-elgreco I have a connection exception similar to yours after upgrading from deltalake 0.16.1 to 0.16.3. I use a minio for dev with a self signed certificate. Writing fails with: 

OSError: Generic S3 error: Error after 10 retries in 2.2691492s, max_retries:10, retry_timeout:180s, source:error sending request for url (..): error trying to connect: invalid peer certificate: UnknownIssuer 

i need to set "allow_invalid_certificates": "true" to get it working.
