### ISSUE TITLE
parquet: "not yet implemented" error when codec is actually implemented but disabled

### ISSUE THREAD

**Issue by progval** [apache/arrow-rs#5520]
**Describe the bug**
When a codec is disabled (with `parquet = { version = ..., default-features = false }`) and such a codec is requested, the error message is incorrect

**To Reproduce**
"The codec type XXX is not supported yet"

**Expected behavior**
"The codec type XXX is disabled" or "feature YYY is disabled"

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #5521
