### ISSUE TITLE
Inconsistency between documentation and code

### ISSUE THREAD

**Issue by YichiZhang0613** [apache/arrow-rs#5527]
In arrow-rs-master/arrow-array/src/record_batch.rs, what the documentation mentions is column length while  assert!((offset + length) <= self.num_rows()) checks the number of rows.
```rust
    /// # Panics
    ///
    /// Panics if `offset` with `length` is greater than column length.
    pub fn slice(&self, offset: usize, length: usize) -> RecordBatch {
        assert!((offset + length) <= self.num_rows());
```

**Comment by tustvold** [comment]
This is actually correct, the number of rows is the length of the columns
