### ISSUE TITLE
ArrayData::slice() does not work for nested types such as StructArray

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#554]
**Describe the bug**
`ArrayData::slice()` does not work for nested types, because only the `ArrayData::buffers` are updated with the new offset and length. This has caused a lot of issues in the past.

This blocks us from being able to implement `RecordBatch::slice()`, and has led to creating #381 to sidestep this issue.

**Comment by nevi-me** [comment]
Thanks for this @alamb, I hadn't noticed that not linking PRs to existing issues affects the changelog.

**Comment by alamb** [comment]
> Thanks for this @alamb, I hadn't noticed that not linking PRs to existing issues affects the changelog.

Yes @nevi-me  I don't fully understand the intricacies of the changelog generator that @jorgecarleitao  found but it seems to be mostly derived from issues (rather than PRs) 🤷  I figured I will keep honing the process in future releases
