### ISSUE TITLE
Cannot access example Flight SQL Server from dbeaver

### ISSUE THREAD

**Issue by freddieptf** [apache/arrow-rs#5540]
**Describe the bug**
I ran the example Flight SQL server in https://github.com/apache/arrow-rs/blob/master/arrow-flight/examples/flight_sql_server.rs and could not access it from dbeaver using the JDBC driver version 15.0.1. Got it working with some minor changes https://github.com/freddieptf/arrow-rs/commit/a20a16825031db2d669aba5b05c9114e7ab3b427. Is this the intended behavior or am i doing something wrong?

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
> and could not access it from dbeaver using the JDBC driver version 15.0.1. 

I don't think that is the intended behavior 

Can you explain what symptoms you were seeing?

Also, creating a PR with your changes would be most appreciated 🙏

**Comment by freddieptf** [comment]
I could successfully connect to the database but could not view any catalogs. After a bit of poking around i realized calls for catalogs, schema and tables were being handled by `do_get_fallback` due to the ticket not being encoded correctly; so dbeaver was not getting the correct response.

**Comment by alamb** [comment]
Thanks @freddieptf  -- makes sense to me

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5543

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow-flight'} from #5543
