### ISSUE TITLE
Add scientific notation decimal parsing in `parse_decimal`

### ISSUE THREAD

**Issue by ion-elgreco** [apache/arrow-rs#5549]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
In Delta-RS we write min and max stats of a particular column, depending on the value of a decimal this is written in scientific notation. When we interact with a table we parse the logs to get a table state. As a result some users can't read tables that had written these stats.

See related issues:
-  https://github.com/delta-io/delta-rs/issues/2221
- https://github.com/delta-io/delta-rs/issues/2193

**Describe the solution you'd like**
Add support for scientific notation parsing.

**Describe alternatives you've considered**
None at the moment, our new table replay is deeply tied with the arrow json parser  :)

**Comment by vdelbaen** [comment]
Thank you for creating this issue.

With Delta-RS, I can't read a delta table containing decimals in scientific notation.

Example:

```python
table_url = 'abfss://xxx@xx.dfs.core.windows.net/path/to/delta/table'
dt = dl.DeltaTable(table_url, storage_options={"bearer_token": AZ_TOKEN})
```

I get the following error:

```
File [c:\///.venv/Lib/site-packages/deltalake/table.py:401), in DeltaTable.__init__(self, table_uri, version, storage_options, without_files, log_buffer_size)
(...)
    398 
    399 """
    400 self._storage_options = storage_options
--> 401 self._table = RawDeltaTable(
    402     str(table_uri),
    403     version=version,
    404     storage_options=storage_options,
    405     without_files=without_files,
    406     log_buffer_size=log_buffer_size,
    407 )

Exception: Parser error: can't parse the string value 0E-8 to decimal
```

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5611
