### ISSUE TITLE
Support for `AVRO` format (trying to use `arrow_avro`)

### ISSUE THREAD

**Issue by dsalv** [apache/arrow-rs#5562]
**Which part is this question about**

`arrow_avro`

**Describe your question**

- I see that there is `arrow_avro` module but it doesn't have documentation. Is there any example of how we can use it? Most of the things in that module are private and cannot be used. 

- Is `arrow_avro` still in development? If so, is there any expected timeline for adding the support?

- What's the recommended way to handle `AVRO` format with arrow?

Thank you in advance

**Additional context**

**Comment by tustvold** [comment]
See https://github.com/apache/arrow-rs/issues/4886

Development has somewhat stalled but I hope to finish it up over the next few months

**Comment by dsalv** [comment]
> See #4886
> 
> Development has somewhat stalled but I hope to finish it up over the next few months

Thanks for your quick reply. Is it possible to somehow use `arrow_avro` as is? I wanted to avoid reading AVRO file using `avro-rs` and then converting them to arrow format (which will be similar to what you're developing)

**Comment by tustvold** [comment]
> Is it possible to somehow use arrow_avro as is

The support isn't yet at a state where it is usable

**Comment by alamb** [comment]
Thanks to the epic work from @jecsand838 and @nathaniel-d-ef  arrow-avro will be available in the next release
