### ISSUE TITLE
Make FixedSizedList Json serializable

### ISSUE THREAD

**Issue by colin99d** [apache/arrow-rs#5568]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I would like for the arrow-json library to automatically implement the FixedSizedList.

**Describe the solution you'd like**
It seems like adding FixedSizedList should be trivial, since it would be encoded in the same way as a list, I would be happy to try it myself, I just wanted to start this first to make sure there is nothing I am missing.

**Describe alternatives you've considered**
The alternative is I continue to implement this manually.

**Comment by Russ741** [comment]
I'd like to work on this issue.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5646
