### ISSUE TITLE
Make `filter` in `filter_leaves` API propagate error

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#5574]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently `filter_leaves` API takes a closure which returns a `bool`. In some cases, e.g., https://github.com/apache/iceberg-rust/pull/245#discussion_r1545181844, we may like to propagate error from it.

**Describe the solution you'd like**

Changing the `filter` in `filter_leaves` to return `Result<bool>`.

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5575
