### ISSUE TITLE
Improve Error Message for Timestamps Outside Supported Range

### ISSUE THREAD

**Issue by Abdi-29** [apache/arrow-rs#5581]
**Describe the bug**
When executing a query with a timestamp outside the supported range in the arrow cast, users receive a confusing error message about nanosecond overflow. This error message does not clearly explain the limitation of timestamp queries in Datafusion, confusing users.

**To Reproduce**
1. Execute a query with a timestamp outside the supported range (e.g., SELECT * FROM t WHERE a < '1650-01-01 01:01:01'::timestamp).

**Expected behaviour**
I expected to receive a clear error message that explains the limitation of timestamp queries in Datafusion (1677 to 2262) and suggests using timestamps within this range.

**Additional context**
This issue affects users who query timestamps outside the supported range in the arrow-cast. Improving the error message handling to provide clearer guidance would enhance user experience and reduce confusion.

**Comment by Abdi-29** [comment]
I did some investigation and the error message is coming from [here](https://github.com/apache/arrow-rs/blob/77a3132bbd27ebb3cef0d79f24a9a839f125343c/arrow-cast/src/cast/mod.rs#L2114). I'll be happy working on this issue

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5730

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow-flight'} from #1

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #1

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5581](https://github.com/apache/arrow-rs/issues/5581)
