### ISSUE TITLE
GIT tag for `object_store` version 0.9.1 is missing

### ISSUE THREAD

**Issue by crepererum** [apache/arrow-rs#5627]
**Describe the bug**
GIT tag for `object_store` version 0.9.1 is missing.

**To Reproduce**
Use one of:

- GitHub tags page
- `git pull && git tag -l`

**Expected behavior**
Tag is there.

**Additional context**
Having GIT tags is useful for various reasons:

- being able to patch/modify a certain version to test changes in a larger software context
- data lineage
- consistency checks (i.e. is the code published on crates.io the same as we have on GitHub)

The latter two ones are somewhat important in vein of the recent `xz` story.

**Comment by alamb** [comment]
The git sha is stored in the voting thread https://lists.apache.org/thread/zhb72l3z28rg7r18yqmpgxmmb0z3jbmd  and the official release is what is on the apache download site (not, eg. what is on crates.io, though we use the official release to upload).

Note the 0.9.1 release came from 30151220c29fa5e01365c2a4e153de01d5d2c041

It would be good to add explicit tags in the repo as well.

**Comment by tustvold** [comment]
Sorry I forgot to push the tags, they should be there now
