### ISSUE TITLE
[object_store] minor bug: typos present in local variable 

### ISSUE THREAD

**Issue by Silemo** [apache/arrow-rs#5628]
**Describe the bug**

In the object_store/gcp folder, few of the files contain some minor typos.

**To Reproduce**

Search in the following files the respective terms: 
* `object_store/gcp/builder.rs` : 
   * `signing_cedentials` (it should be `signing_credentials`); 
* `object_store/gcp/client.rs` :  
   * `repsonse` (it should be `response`); 
* `object_store/gcp/credentials.rs` : 
   * `methond` (it should be `method` ), 
   * `canaonical_headers` (it should be `canonical_headers`), 
   * `caninical_request` (it should be `canonical_request`)

**Expected behavior**

The code works smoothly as expected, it is just written incorrectly on a grammar level.

**Additional context**

I just opened a PR to fix these small typos. I created the issue for clarity as requested in the PR template.

**Comment by Xuanwo** [comment]
Maybe we can introduce `typos` in CI.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #5629

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5628](https://github.com/apache/arrow-rs/issues/5628)
