### ISSUE TITLE
Rust Interval definition incorrect

### ISSUE THREAD

**Issue by david542542** [apache/arrow-rs#5654]
It seems the Rust `INTERVAL` definition is incorrect. Please see https://github.com/duckdb/duckdb-wasm/issues/1696#issuecomment-2047021075 for more details on the bug and where it occurs in the code.

Particularly this definition: https://github.com/apache/arrow-rs/blob/36a6e515f99866eae5332dfc887c6cb5f8135064/arrow-array/src/types.rs#L265-L269

**Comment by tustvold** [comment]
@pitrou do you know if the integration tests cover the interval types?

**Comment by avantgardnerio** [comment]
> @avantgardnerio as the author of #2235 which appears to have switched these round, perhaps you could weigh in here

Honestly, I don't recall the reasoning. I know at the time I was working with JDBC interop, so I assume it was to make that work.

I agree we should do whatever arrow-cpp does, as that seems to be the reference implementation, to the extent that there is one.

**Comment by pitrou** [comment]
> @pitrou do you know if the integration tests cover the interval types?

Yes, they do.
https://github.com/apache/arrow/blob/7003e90c113cec58a620deddf56af71eb305af2a/dev/archery/archery/integration/datagen.py#L1653-L1669

**Comment by tustvold** [comment]
One way to avoid this leading to subtle downstream breakage might be to do something along the lines of https://github.com/apache/arrow-rs/issues/3125

**Comment by alamb** [comment]
@tustvold  reports is that it is unlikely that this will be done this week due to other higher priorities

**Comment by tustvold** [comment]
It turns out the reason we didn't detect this with our integration tests, is that they were actually using different, correct, logic for constructing the expected values from the JSON data - https://github.com/apache/arrow-rs/pull/5765

**Comment by david542542** [comment]
That's great to know. Any idea on the ETA on this fix?

**Comment by alamb** [comment]
We are holding the [`52.0.0` release for this](https://github.com/apache/arrow-rs/issues/5688). I expect it will be available in about 2 weeks but no promises, etc

**Comment by alamb** [comment]
Proposed PR: https://github.com/apache/arrow-rs/pull/5769

**Comment by david542542** [comment]
@alamb any idea on when https://github.com/apache/arrow-rs/issues/5688 will be deployed?

**Comment by alamb** [comment]
> @alamb any idea on when [52.0.0](https://github.com/apache/arrow-rs/issues/5688) will be deployed?

The plan as I understand it is next week

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet'} from #5769

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5769
