### ISSUE TITLE
Provide Arrow Schema Hint to Parquet Reader

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#5657]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The parquet reader automatically uses an embedded arrow schema to hint type inference for decode. In particular if the hinted type is compatible with the underlying parquet type, it performs a cast.

**Describe the solution you'd like**

In situations where the writer was not an arrow writer this schema is not available, and therefore the arrow types are inferred from the parquet schema. This is not always desirable:

* https://github.com/apache/arrow-rs/issues/5655
* https://github.com/apache/arrow-rs/pull/5605#issuecomment-2060960080

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
Here is one potential API

```rust
let file = File::open("data.parquet").unwrap();

let reader = ParquetRecordBatchReaderBuilder::try_new(file)?
  // specify column "time" should be UTC
  // will error if this type can not be read from parquet
  .with_column_type("time", DateTime::Timestamp(Nanoseconds, Some("UTC"))

println!("Converted arrow schema is: {}", builder.schema());
```

I am not quite sure how to handle identifying nested types with a single column name

Like if the parquet file has
```json
{
  "my_object": { 
    "time": "12-01-02"
  }
}
```

maybe we would refer to the `time` field like `"my_object.time"`?

**Comment by tustvold** [comment]
I think my expectation would be for you to provide the `SchemaRef` for the entire file

**Comment by Lordworms** [comment]
Let me try the remaining part if it is ok

**Comment by liukun4515** [comment]
> ```rust
> ParquetRecordBatchReaderBuilder
> ```

In the datafusion, the `ParquetExec` of `FileScanConfig` contains the schema for the parquet file, but I think the provided `SchemaRef` should be the optional for the parquet reader when infer the data type

**Comment by liukun4515** [comment]
> I think my expectation would be for you to provide the `SchemaRef` for the entire file

In the datafusion, the `ParquetExec` of `FileScanConfig` contains the schema for the parquet file, but I think the provided `SchemaRef` should be the optional for the parquet reader when infer the data type

**Comment by liukun4515** [comment]
> > I think my expectation would be for you to provide the `SchemaRef` for the entire file
> 

Basically agree with your idea
In the datafusion, the `ParquetExec` of `FileScanConfig` contains the schema for the parquet file, but I think the provided `SchemaRef` should be the optional for the parquet reader when infer the data type

**Comment by alamb** [comment]
Something like

```rust
let file = File::open("data.parquet").unwrap();

let reader = ParquetRecordBatchReaderBuilder::try_new(file)?
  // specify the arrow schema to read from this parquet file
  // will error if the types in the parquet file can not be converted
  // into the specific types. 
  // Will ignore any embedded metadata about types when written
  .schema(schema)

println!("Converted arrow schema is: {}", builder.schema());
```

**Comment by liukun4515** [comment]
> Something like
> 
> ```rust
> let file = File::open("data.parquet").unwrap();
> 
> let reader = ParquetRecordBatchReaderBuilder::try_new(file)?
>   // specify the arrow schema to read from this parquet file
>   // will error if the types in the parquet file can not be converted
>   // into the specific types. 
>   // Will ignore any embedded metadata about types when written
>   .schema(schema)
> 
> println!("Converted arrow schema is: {}", builder.schema());
> ```

Do we need to add some checker in the function of the `schema` which is used to compare the schema with schema inferred from the parquet file?

**Comment by tustvold** [comment]
The inference logic is already setup to use the arrow schema as a hint as opposed to authoritative , if you give it something invalid it will just ignore it

**Comment by liukun4515** [comment]
> The inference logic is already setup to use the arrow schema as a hint as opposed to authoritative , if you give it something invalid it will just ignore it

thanks, got it.

**Comment by efredine** [comment]
I noticed this seemed to have stalled, so I thought I would have a go at it. 

The implemented API is different from the one discussed. In particular, the schema is supplied as an ArrowReaderOption. 

```
let file = File::open("file.parquet");
let schema = Arc::new(Schema::new(vec![Fields::new("col", DataType::Int32, false)]));
let options = ArrowReaderOptions::new().with_schema(schema);
// This may fail as described above.
let builder = ParquetRecordBatchReaderBuilder::try_new_with_options(file, options).unwrap();
let reader = builder.build().unwrap();
```
This is necessary because it needs to be provided as a hint when the metadata is read from the parquet file.

The tests are incomplete and there are some questions in the PR with respect to how error handling should be handled.

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5605

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #5939
