### ISSUE TITLE
Arrow FLight SQL: invalid location in get_flight_info_prepared_statement

### ISSUE THREAD

**Issue by istvan-fodor** [apache/arrow-rs#5669]
**Describe the bug**

The flight_sql_server.rs is not compatible with the Arrow JDBC driver. The following changes are necessary:

1. #5665 needs to be fixed. 
1. The location field returned by `get_flight_info_prepared_statement` uses a "grpc+tcp://127.0.0.1" as its location. Instead it should include the host and the port. 
1. do_action_close_prepared_statement needs to include at least an empty stub (return ` Ok(())`). 

With these changes a simple query can be executed from JDBC on a TCP connection. 

**To Reproduce**

Use a simple Java / JDBC example that queries for the static data in the example.  

**Expected behavior**

I can fetch the `Hello, FlightSQL!` result.

**Comment by Curricane** [comment]
Is there any progress on this matter?

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5666

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow-flight'} from #5666
