### ISSUE TITLE
Avoid using `arrow_schema` in `downcast_dictionary_array`

### ISSUE THREAD

**Issue by jayzhan211** [apache/arrow-rs#5676]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I found that I need to import `arrow-schema` for this macro although I have imported `arrow` already. I expect to call this macro with `arrow::array::` without import `arrow-schema`. I think changing the prefix of Datatype solves this problem

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
This would break usage for people who don't wish to take a dependency on arrow, only arrow-array, I'm not sure there is a way around this...

**Comment by jayzhan211** [comment]
> This would break usage for people who don't wish to take a dependency on arrow, only arrow-array, I'm not sure there is a way around this...

I see, agree with it.
