### ISSUE TITLE
object_store: visibility over maybe_spawn_blocking method, PutPayload object and MultiPartUpload

### ISSUE THREAD

**Issue by Silemo** [apache/arrow-rs#5677]
**Which part is this question about**

Hi there! Young dev here. I recently opened an issue about having HDFS support, and after your suggestions I am now working on a refactor of [datafusion-contrib/datafusion-objectstore-hdfs](https://github.com/datafusion-contrib/datafusion-objectstore-hdfs). 

While working there I noticed a problem that can easily be solved with a change in some modules visibility. 

**Describe your question**

Would it be possible to refactor the current repo so to be able to expose object_store::util::maybe_spawn_blocking, object_store::util::PutPayLoad, object_store::upload::MultipartUpload?

**Additional context**

This is necessary as an external implementation of the ObjectStore, needs these objects and method to implement the interface. Leaving the visibility like this would mean that I would make a copy of the object_store::util::maybe_spawn_blocking method, as [currently is in the datafusion-contrib/datafusion-objectstore-hdfs](https://github.com/datafusion-contrib/datafusion-objectstore-hdfs/blob/master/hdfs/src/object_store/hdfs.rs#L578).

Looking in-depth to various of the object_store implementation that you have in the repo, you often import these methods using crate:: , but this is not possible for external repositories. 

I think that this change would enable external implementation of the ObjectStore interface to be complete and use the code already present in this repository.

**Comment by tustvold** [comment]
PutPayload and MultiparrUpload are already re-exported at the root.

I would prefer not to expose maybe_spawn_blocking as it is specific to LocalFilesystem

**Comment by Silemo** [comment]
Don't you agree that maybe_spawn_blocking is used also in external implementations such as HDFS? An example can be seen [here](https://github.com/datafusion-contrib/datafusion-objectstore-hdfs/blob/master/hdfs/src/object_store/hdfs.rs#L578)

**Comment by tustvold** [comment]
I would rather not commit to maintaining it in a public api

**Comment by Silemo** [comment]
I got why I didn't see the imports for PutPayload and MultipartUpload (it was solved in version 0.10).

> I would rather not commit to maintaining it in a public api

I am sorry to hear this, but I get it. 

---

### Related question

Any suggestion on how I could access `Range<usize>` contained in `GetRange`? There is a method (`as_range()`) but even if re-exported this is still private (I think is related to writing `pub(crate)`, but correct me if I am mistaken.

This access is necessary to implement correctly get_opts as you can see from the [old implementation ](https://github.com/datafusion-contrib/datafusion-objectstore-hdfs/blob/master/hdfs/src/object_store/hdfs.rs#L226)(based on the version that didn't have `GetRange`, but just `Range`), and the `LocalFileSystem` implementation [here](https://github.com/apache/arrow-rs/blob/master/object_store/src/local.rs#L430).

**Comment by tustvold** [comment]
The variants are public so you can match on them - https://docs.rs/object_store/latest/object_store/enum.GetRange.html
