### ISSUE TITLE
parquet_derive: invalid examples/documentation

### ISSUE THREAD

**Issue by kasparthommen** [apache/arrow-rs#5687]
**Describe the bug**
There are references to `SerializedFileWriter::close_row_group()` in the following files, which is a method that doesn't seem to exist, rendering the examples un-compileable:
- https://github.com/apache/arrow-rs/blob/11450ae8ddf902b57cb42491a3d824d9550a05ea/parquet_derive/README.md?plain=1#L76
- https://github.com/apache/arrow-rs/blob/11450ae8ddf902b57cb42491a3d824d9550a05ea/parquet_derive/src/lib.rs#L72

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'parquet-derive'} from #5823
