### ISSUE TITLE
Release arrow-rs / parquet version `52.0.0`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#5688]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
50.1.0 https://github.com/apache/arrow-rs/issues/5453 was released about 2 months ago: https://crates.io/crates/arrow/51.0.0 (March 18, 2024)

**Describe the solution you'd like**
A new release. 

**Describe alternatives you've considered**

**Additional context**
Suggested content for the release: 
- [x] https://github.com/apache/arrow-rs/issues/5654 
- [x] https://github.com/apache/arrow-rs/pull/5753
- [x] https://github.com/apache/arrow-rs/issues/5731

**Comment by konjac** [comment]
Hi @tustvold, could we consider to prioritize this?

**Comment by alamb** [comment]
(I can handle the release mechanics when we decide it is time)

**Comment by tustvold** [comment]
I think https://github.com/apache/arrow-rs/issues/5654 and getting the various view arrays to a somewhat stable state, e.g. if we do decide to add a view abstraction or similar.

I intend to cut the release towards the end of May as a stepping stone to the 3 month breaking release cadence that people are asking for.

**Comment by alamb** [comment]
I see -- so perhaps we release `52` at the end of may and then target `52.1.0` in June and `52.2.0` in July and then `53.0.0`  (next breaking API) release in August 🤔

**Comment by tustvold** [comment]
I'm loathe to commit to a rigid cadence, there isn't much point going through the rigmarole if not much has changed, but I think we can commit to the next breaking release afterwards being no earlier than August

**Comment by alamb** [comment]
> I'm loathe to commit to a rigid cadence, there isn't much point going through the rigmarole if not much has changed, but I think we can commit to the next breaking release afterwards being no earlier than August

The reason to have a regular cadence is so that we don't hold up releasing things like bug fixes . I agree it is overhead on maintainers

**Comment by alamb** [comment]
I filed https://github.com/apache/arrow-rs/pull/5737# to try and document what the current thinking for releases is. Feedback welcome.

**Comment by Xuanwo** [comment]
Hi @alamb, I'd like to include https://github.com/apache/arrow-rs/pull/5753 in our release train for version 52.

**Comment by alamb** [comment]
Thanks @Xuanwo  -- added to the list above. 🚋

**Comment by matthewmturner** [comment]
I think getting a resolution / fix on https://github.com/apache/arrow-rs/issues/5731 would be valuable for this release.

**Comment by alamb** [comment]
Added to the list @matthewmturner  -- thank you

Are you driving the resolution on https://github.com/apache/arrow-rs/issues/5731 ?

**Comment by matthewmturner** [comment]
@alamb i am happy to, i will review and propose next steps

**Comment by tustvold** [comment]
Definitely not a necessity, but sorting out null handling for nested comparison is something that may need breaking changes and would therefore be something we may want to include in this release - https://github.com/apache/arrow-rs/issues/5426

I can try to find some time to look into this, I know I keep promising this, but it keeps getting ousted by more urgent things :sweat_smile:

**Comment by alamb** [comment]
Quick update:
* I believe we have the last PR we are waiting for https://github.com/apache/arrow-rs/pull/5817 (which is approved and I expect it to merge very soon)
* @tustvold plans to make the release candidate next week, so we are looking like we'll have the release on crates.io at the end of next week (June 6)

**Comment by tustvold** [comment]
I think we should at least try to get https://github.com/apache/arrow-rs/issues/5827 and #TBD in as well, now that we're not able to make breaking changes as frequently

**Comment by alamb** [comment]
> I think we should at least try to get #5827 and #5777 in as well, now that we're not able to make breaking changes as frequently

I think this release has waited long enough already. There is too much in this release already (and too many people waiting on it)   (like the object store update, and now the datafusion upgrade). We need a new major release asap

If there is critical demand for new breaking features before the end of the summer we can handle them separately (like consider more breaking releases) but I don't think we should hold this release any longer

**Comment by waynexia** [comment]
It would be great to include https://github.com/apache/arrow-rs/pull/5832 as a supplement for #5769

**Comment by tustvold** [comment]
I would observe that it hasn't been 3 months since the last breaking release yet (March 18th), and people are waiting on breaking changes. This is ultimately what people asked for 😅

I'll cut the release today, but I suspect the release cadence may need review in a month or so's time

**Comment by alamb** [comment]
Release thread: https://lists.apache.org/thread/vmo9dt0s9hx73o09vb09ztyl369r1gks

**Comment by alamb** [comment]
Filed https://github.com/apache/arrow-rs/issues/5905 to track next release
