### ISSUE TITLE
Add more attributes to `object_store::Attribute`

### ISSUE THREAD

**Issue by netthier** [apache/arrow-rs#5689]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I want to set attribute headers currently not included in `Attribute` but supported by providers such as GCP, AWS and Azure, such as `Content-Disposition`.

**Describe the solution you'd like**

More variants should be added to `object_store::Attribute` and implemented accordingly.
Specifically, I think `Content-Disposition`, `Content-Encoding` and `Content-Language` should be added, as they're well-supported.

**Describe alternatives you've considered**

It's possible to set the same headers using default headers per-client, but that is unwieldy if one wants to set these headers dynamically.

**Additional context**

https://cloud.google.com/storage/docs/metadata#content-disposition (and following)
https://learn.microsoft.com/en-us/rest/api/storageservices/put-blob?tabs=microsoft-entra-id#request-headers-all-blob-types
https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #5690

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5689](https://github.com/apache/arrow-rs/issues/5689)
