### ISSUE TITLE
Allow specifying PUT options when using `BufWriter`

### ISSUE THREAD

**Issue by netthier** [apache/arrow-rs#5692]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I want to specify attributes for objects uploaded via the `BufWriter` interface.

**Describe the solution you'd like**

I'd like to be able to pass options similar to those accepted by `put_opts` and `put_multipart_opts` to a new `BufWriter` instance.

**Describe alternatives you've considered**

An alternative would be to use `put_opts` and `put_multipart_opts` directly, but I'd prefer not to re-implement the `BufWriter` interface. Alternatively the options could be set on the object after the fact, though I'm unsure how that can be done with this crate.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'object-store'} from #5693

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5692](https://github.com/apache/arrow-rs/issues/5692)
