### ISSUE TITLE
[object_store] Self-signed certificates used by OneLake (Azure)

### ISSUE THREAD

**Issue by martroben** [apache/arrow-rs#5696]
# Which part is this question about
object_store features

# Describe your question
Is there some setting for object_store that would enable accessing Azure storage if the storage is using a self-signed certificate?

# Additional context
I would like to use the Python polars library on the [Microsoft Fabric](https://www.microsoft.com/en-us/microsoft-fabric) platform.

[Polars](https://docs.pola.rs/py-polars/html/reference/) uses [delta-rs](https://delta-io.github.io/delta-rs/) which in turn uses object_store to interact with OneLake. ([OneLake](https://learn.microsoft.com/en-us/fabric/onelake/onelake-api-parity) is the Azure Data Lake Storage Gen2 flavor used for storage in Fabric).

Everything works fine when accessing OneLake from a local device. However, when I try to use Polars in a Fabric notebook, I get the following error: `error trying to connect: invalid peer certificate: Other(CaUsedAsEndEntity)`.

I checked the certificate with `openssl s_client -connect onelake.blob.fabric.microsoft.com:443 -showcerts | openssl x509 -text` in the Fabric Notebook environment. It turns out that onelake.blob.fabric.microsoft.com indeed uses a self-signed Certificate Authority (CA) certificate for connections coming from Fabric Notebooks. If I run the same check from a local device, the server provides a normal End Entity certificate.

I suspect that the error is caused by some upstream certificate validator function in [webpki](https://docs.rs/webpki/latest/webpki/), which is in turn used by [rustls](https://docs.rs/rustls/latest/rustls/). I don't speak rust very well, but I assume that object_store also uses rustls.

The issue [has](https://github.com/briansmith/webpki/issues/114) been [raised](https://github.com/rustls/rustls/issues/143) before [in](https://github.com/rustls/rustls/issues/772) webpki and rustls repos, but the maintainers of both have made it clear that they're [not](https://github.com/briansmith/webpki/pull/170) going [to](https://github.com/rustls/rustls/blob/513e374b2e2ce9f1fb57ac78ab3ca053afc8f133/rustls/src/manual/features.rs#L46) provide an out-of-the-box option for accepting connections that are trying to use CA certificate as EE.

rustls includes an option to [implement](https://github.com/rustls/rustls/pull/1368) [custom](https://github.com/rustls/rustls/issues/1360) [certificate](https://github.com/rustls/rustls/blob/992e2364a006b2e84a8cf6a7c3eaf0bdb773c9de/examples/src/bin/tlsclient-mio.rs#L318) verifier. However, since I don't speak the language, I'm not sure if it is already included in object_store - and if not, could it be done?

The only check that would need to be omitted is the one asserting that `CA` needs to be `FALSE` in the certificate:
```
Certificate:
    Data:
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:FALSE
```

I have also opened a support case with the Microsoft Fabric team, asking them to start using valid certificates (request #2404260050002071). However, if anybody's going to solve it, my money is on the open source community. As of now, rust-based libraries are basically unusable in Microsoft Fabric, which is unfortunate.

PS: I'm aware of the [`allow_invalid_certificates`](https://docs.rs/object_store/latest/object_store/struct.ClientOptions.html#method.with_allow_invalid_certificates) option and it does fix the problem. But my love for polars isn't big enough to start using unsecure connections in production.

**Comment by tustvold** [comment]
Following https://github.com/apache/arrow-rs/pull/5056 we by default use the system trust store to source the CA. 

I am not very familiar with Microsoft Fabric, but if they are using self-signed certificates I would have expected them to populate this. If they aren't, you may be able to override `SSL_CERT_DIR` to wherever they are placing the certs (I presume they must be placing them somewhere).

https://github.com/apache/arrow-rs/issues/5517 may also be related.

> However, if anybody's going to solve it, my money is on the open source community

This is depressingly likely true, although FWIW I grow increasingly frustrated at the amount of bodgery required to support Azure... They're up to 4 or possibly 5 object store like products that are all slightly different, and expose slightly different functionality, it's getting kind of ridiculous...

@roeap I don't suppose you know anything about this?

**Comment by tustvold** [comment]
Other than perhaps trying building with OpenSSL which may be more permissive about certificates being used in non-spec compliant ways, rustls is quite right to refuse to accept this, I don't really know what to suggest.

Ultimately the onus is on Microsoft to fix this, especially given the security critical nature of this area, Microsoft should really do better

**Comment by hnasrullakhan** [comment]
https://www.ibm.com/docs/en/informix-servers/14.10?topic=openssl-x509v3-certificate-extension-basic-constraints

If you want your self-signed certificate to be recognized as a trusted CA certificate by systems like CentOS, you need to include the basicConstraints = CA:TRUE field in the certificate. This field specifies that the certificate is a CA certificate, allowing it to be recognized as such by the trust store mechanisms.

Without this field set to CA:TRUE, your self-signed certificate won't be recognized as a CA certificate, and therefore it won't be added to the CA trust store when you run the update-ca-trust command. This is why you're observing that the CA trust store isn't updated when basicConstraints is omitted or set to CA:FALSE.

So, to ensure that your self-signed certificate is added to the CA trust store and recognized as a CA certificate, you need to include basicConstraints = CA:TRUE when generating the certificate.

Looks like this change introduces this issue above where self signed certs used are faling.
https://github.com/apache/arrow-rs/pull/5056/files.

**Comment by tustvold** [comment]
Yes but the issue as far as I understand is that Azure is then using a CA certificate as an endpoint certificate which is not only terrible practice, but also not really permitted by the specification

**Comment by hnasrullakhan** [comment]
I maybe assuming because only that maybe the related change between object_store version.

**Comment by tustvold** [comment]
Is there a version that works currently, the information presented thus far would suggest Azure changed something on their end

**Comment by hnasrullakhan** [comment]
deltalake==0.16.2 which was before object_store version 0.9.1 . works fine.

**Comment by tustvold** [comment]
The TLS changes were in 0.9.0 not 0.9.1, is it possible there was a change in delta-rs? I know they used to override and use openssl

**Comment by hnasrullakhan** [comment]
https://github.com/delta-io/delta-rs/issues/2449
they claim they have no changes. 

CaUsedAsEndEntity and self signed certs related issues have been reported before on webpki. is there regression recently ?

**Comment by hnasrullakhan** [comment]
OSError: Generic MicrosoftAzure error: Error after 10 retries in 6.067636775s, max_retries:10, retry_timeout:180s, source:error sending request for url (https://onelake.blob.fabric.microsoft.com/TEST1/test2.Lakehouse/Tables/Test/_delta_log/_last_checkpoint): error trying to connect: invalid peer certificate: Other(CaUsedAsEndEntity)

**Comment by tustvold** [comment]
I'm afraid I don't know why this worked on older versions, perhaps webpki got more strict. You could file an upstream ticket but to be completely honest the error is correct, the problem is onelake

**Comment by hnasrullakhan** [comment]
@martroben  can you also confirm that it works with deltalake-0.16.2

**Comment by roeap** [comment]
> FWIW I grow increasingly frustrated at the amount of bodgery required to support Azure

@tustvold @martroben - unfortunately I can only agree with this for now.

I'll investigate if I can find something in delta-rs that has changed, but why MSFT is putting us through all of this is hard to understand ...

**Comment by konjac** [comment]
The One Lake endpoint inside Fabric Spark is actually resolved to a local proxy. And the proxy is using the self-signed cert.

![image](https://github.com/apache/arrow-rs/assets/2101973/33f0b3bd-0a6a-430f-ab98-1d7920a1c9f5)

So the observed self-signed cert is the cert of that proxy.

**Comment by hnasrullakhan** [comment]
@roeap any luck with findings. 0.16.2 is the one which causes the issue. builds before that have no issues.

**Comment by hnasrullakhan** [comment]
@roeap any findings?

**Comment by martroben** [comment]
It seems that upstream packages with object store 0.10.1 are [no longer experiencing this error](https://github.com/delta-io/delta-rs/issues/2449#issuecomment-2196730072). I'm not sure if it was object store that fixed it or something else up or down the chain.
