### ISSUE TITLE
What is the rationale for the current NullBuilder capacity behavior?

### ISSUE THREAD

**Issue by HadrienG2** [apache/arrow-rs#5711]
**Which part is this question about**

Library API of `arrow_array::builder::NullBuilder`.

**Describe your question**

As far as I can tell, `NullBuilder` is the only builder for which `capacity == len`. The way this is currently handled is quite surprising, for example `NullBuilder::with_capacity(123)` is not empty, but has an initial length of 123, i.e. the final array length is not defined only by what is pushed, but also by what the initial builder capacity was.

Now, I understand that the reason why this happens is that the designer of `NullBuilder` wanted to only store a length, since that's enough information to encode an "array of nulls", and managing a capacity would be pointless overhead.

But my question is, why was the current design favored over the following alternatives?

1. Do not expose capacity setters or getters at all (i.e. no `NullBuilder::with_capacity()` and no `NullBuilder::capacity()`).
2. Make `with_capacity()` a no-op and make `capacity()` return either the current length or `usize::MAX`.

I think these alternatives are better because they shift the surprising part of the API to the behavior of capacity, rather than the length. And I believe people are used to container capacity being an implementation detail that can behave in a slightly surprising way (e.g. allocate more than the user requested), whereas length is normally expected to have a very predictable behavior.

**Additional context**

This particular behavior gets in the way of cleanly integrating `NullBuilder` into my prototype for https://github.com/apache/arrow-rs/issues/5700 .

**Comment by tustvold** [comment]
I think the behaviour is probably a bug, it shouldn't behave that way

**Comment by HadrienG2** [comment]
Which behavior would you prefer then? Don't expose capacity at all? Ignore constructor-specified capacity + expose `usize::MAX` capacity? Something else?

**Comment by tustvold** [comment]
I would probably deprecate exposing capacity as it doesn't really make sense, but I don't feel strongly

**Comment by mbrobbel** [comment]
I'd suggest removing the capacity functions from the null builder.

**Comment by HadrienG2** [comment]
I tried to go down the "deprecate everything capacity-related" path, but what should happen to the `NullArray::builder()` method, which currently takes a capacity as an argument? Should I remove that capacity argument (which is an API breaking change)? Or should I make the method ignore the capacity argument for now, and write down somewhere (where?) that in the next API-breaking release, one should consider dropping that argument?
