### ISSUE TITLE
Why are null buffers / validity slices exposed by some builders, but not others?

### ISSUE THREAD

**Issue by HadrienG2** [apache/arrow-rs#5749]
**Which part is this question about**
API of `arrow_array::builder`.

**Describe your question**
`BooleanBuilder` and `PrimitiveBuilder` provide read-only access to their null buffer via a `validity_slice()` method. However, `GenericListBuilder` does not provided such access, even though it does expose list offsets via the `offsets_slice()` method.

Is there a reason why this is the case, or may I submit a PR to add `validity_slice()` methods to this builder, and possibly other builders with a null buffer along the way?

**Additional context**
In the context of #5700, I'm investigating which strongly typed builders could expose their contents via a generalized slice type. Right now, I would able to do so for builders of non-nullable lists, but not for builders of nullable lists, due to lack of access to the list builder's null buffer. Exposing offsets but not the null buffer seems odd, hence my asking.

**Comment by tustvold** [comment]
I see no reason not to add this to ListBuilder
