### ISSUE TITLE
Would you be open to exposing the contents of BooleanBuilder?

### ISSUE THREAD

**Issue by HadrienG2** [apache/arrow-rs#5757]
**Which part is this question about**
API of `arrow_array::builder::BooleanBuilder`.

**Describe your question**
Unlike `PrimitiveBuilder`, `BooleanBuilder` does not expose a slice of values. I assume that is because the booleans are bit-packed and there was either fear of user confusion, or a desire to be able to change the storage representation later on. How open would you be to exposing these bits somehow, possibly behind an abstraction layer that hides the exact storage layout?

**Additional context**
This would enable a more uniform API in my prototype for #5700.

**Comment by tustvold** [comment]
I see no issue with exposing the bit packed representation in a read only fashion, we do this for validity anyway.
