### ISSUE TITLE
Serialize `Binary` and `LargeBinary` as HEX with JSON Writer

### ISSUE THREAD

**Issue by hiltontj** [apache/arrow-rs#5783]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

`Binary` and `LargeBinary` types are not currently supported by the JSON writer, while they are serialized as HEX in the standard Arrow formatter.

**Describe the solution you'd like**

I would like to have `Binary` and `LargeBinary` data types serialized by the JSON writer as HEX. This would follow the behaviour for `FixedSizeBinary` (see https://github.com/apache/arrow-rs/issues/5620).

**Describe alternatives you've considered**

Have not considered any alternatives at the moment.

**Additional context**

The encoding of `Binary` and `LargeBinary` may resemble that of, or share the implementation of, `FixedSizeBinary`, which is here: https://github.com/apache/arrow-rs/blob/a126d5097b71273428fba68d1c430f3d4beee684/arrow-json/src/writer/encoder.rs#L512-L529

**Comment by v1gnesh** [comment]
Some tricks from https://github.com/nervosnetwork/faster-hex could be useful.

**Comment by hiltontj** [comment]
@v1gnesh perhaps (if this proposal is accepted) that should be addressed in a follow-on issue?

First let's make it do the thing, then we can make it go fast, if necessary.
