### ISSUE TITLE
Limit Parquet Page Row Count By Default to reduce writer memory requirements with highly compressable columns

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#5797]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

There is a [discussion](https://lists.apache.org/thread/vsxmbvnx9gy5414cfo25mnwcj17h1xyp) on the mailing list about default settings for page sizing, and one of the suggestions is that the page row count limit should be enabled by default, where currently it is not. Row groups are limited to 1M rows by default, there is some suggestion pages should be limited to 20,000.

Creating this issue to track

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
Maybe we can use some data from @XiangpengHao 's analysis in https://github.com/apache/arrow-rs/issues/5770 as part of this decision

**Comment by alamb** [comment]
Specifically I think @tustvold 's proposal is to change the default value of this 

https://docs.rs/parquet/latest/parquet/file/properties/struct.WriterProperties.html#method.data_page_row_count_limit

Currently it seems there is no row count limit (limit is usize::max):

https://github.com/apache/arrow-rs/blob/5a24119f6634d66b83556ecbcfbd54ae3f1620c7/parquet/src/file/properties.rs#L356

Note that @XiangpengHao  hit this when trying to write large numbers of rows: https://github.com/apache/arrow-rs/issues/5828

**Comment by alamb** [comment]
I think setting a default page size to 20k is a good idea -- the default "no limit" can result in substantial memory usage on the writer, that people seem to think is a limit of the parquet format itself.

Another potential default value per page would be 64K (the size used in [BtrBlocks](https://www.cs.cit.tum.de/fileadmin/w00cfj/dis/papers/btrblocks.pdf))

**Comment by alamb** [comment]
We just found another example in InfluxDB where setting the data page limit to 64k dramatically lowered the amount of memory written to the parquet writer

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #5957
