### ISSUE TITLE
`binary_mut` kernel requires both args to be the same type (which is inconsistent with `binary`)

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#5818]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
As part of documenting the `_mut` compute kernels better in https://github.com/apache/arrow-rs/pull/5798 I noticed in https://github.com/apache/arrow-rs/pull/5798#discussion_r1613555891 thta 

[binary_mut](https://docs.rs/arrow/latest/arrow/compute/fn.binary_mut.html) is inconsistent with [`binary`](https://docs.rs/arrow/latest/arrow/compute/fn.binary.html) as it requires both `a` and `b` to be the same type of array (where `binary` can take different types)

**Describe the solution you'd like**
I would like to have the argument types to `binary_mut` be different -- so for example, I could write a kernel using `binary_mut` that took a `Float32Array` and a `Int32Array` and added the int32 vale to the float in place. 

**Describe alternatives you've considered**
Leave as is

**Additional context**
@viirya I think added this API in https://github.com/apache/arrow-rs/pull/3144

**Comment by viirya** [comment]
It's not intentional but just for the usage at the moment. It could be more general to have different types. I can open a PR to do it.

**Comment by tustvold** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5798
