### ISSUE TITLE
Add BufUploader to implement same feature upon `WriteMultipart` like `BufWriter`

### ISSUE THREAD

**Issue by Xuanwo** [apache/arrow-rs#5834]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

During implementing https://github.com/apache/arrow-rs/issues/5766, I find a missing piece of our current API set:

`BufWriter` adaptively uses `put` or `put_multipart`, depending on the volume of data written. However, there is no native implementation for `PutPayload`. This forces users to either use `BufWriter`, which requires an extra copy, or manually implement the adaptive logic.

**Describe the solution you'd like**

I plan to introduce `BufUploader` that fill this gap.

**Describe alternatives you've considered**

None.

**Additional context**

The PR has been sunmitted at https://github.com/apache/arrow-rs/pull/5835.

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'object-store'} from #5835

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5834](https://github.com/apache/arrow-rs/issues/5834)
