### ISSUE TITLE
Make `TimeUnit` and `IntervalUnit` `Copy`

### ISSUE THREAD

**Issue by hiltontj** [apache/arrow-rs#5839]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The [`TimeUnit`](https://github.com/apache/arrow-rs/blob/f42218ae5d9c9f0b9ea3365f2b1e6025a43b8c71/arrow-schema/src/datatype.rs#L329-L341) and [`IntervalUnit`](https://github.com/apache/arrow-rs/blob/f42218ae5d9c9f0b9ea3365f2b1e6025a43b8c71/arrow-schema/src/datatype.rs#L343-L360) types in the `arrow-schema` crate are not `Copy`, but they are enums with only unit variants, so they should be cheaply `Copy`.

**Describe the solution you'd like**

Derive `Copy` for these types.

**Describe alternatives you've considered**

Can cheaply use clone, which is not the end of the world, but unless there is a reason to keep these types not-`Copy`, this would be an ergonomic improvement.

**Additional context**

N/A.

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5840
