### ISSUE TITLE
Add a way to move `fields` out of parquet `Row`

### ISSUE THREAD

**Issue by SHaaD94** [apache/arrow-rs#5841]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
In our system, we read a lot of strings, stored in parquet. Until recently we've been using `row.get_column_iter()` and cloning all column values. It would be really nice if there would be a way move the ownership of column values out of the row.

**Describe the solution you'd like**
Move of internal fields structure out like this would work for us:
```
    pub fn into_columns(self) -> Vec<(String, Field)> {
        self.fields
    }
```

**Describe alternatives you've considered**
Currently, I just transmute the row into columns vector, but I don't really like keeping something as unsafe in my code base.

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #5842
