### ISSUE TITLE
Write parquet statistics for `IntervalDayTimeArray` , `IntervalMonthDayNanoArray` and `IntervalYearMonthArray`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#5847]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

As we worked on filling out support for converting parquet statistics into ArrayRefs in DataFusion (see https://github.com/apache/datafusion/issues/10453) @marvinlanhenke discovered that 

**Describe the solution you'd like**
Support writing the following types of data with statistics in the parquet [ArrowWriter](https://docs.rs/parquet/latest/parquet/arrow/arrow_writer/struct.ArrowWriter.html#)
* [IntervalDayTimeArray](https://docs.rs/arrow/latest/arrow/array/type.IntervalDayTimeArray.html)
* [IntervalMonthDayNanoArray](https://docs.rs/arrow/latest/arrow/array/type.IntervalMonthDayNanoArray.html)
* [IntervalYearMonthArray](https://docs.rs/arrow/latest/arrow/array/type.IntervalYearMonthArray.html)

This might be the location: https://github.com/apache/arrow-rs/blob/fa8d3502388d7cfac724f7b9fae92abc3a716b6f/parquet/src/arrow/arrow_writer/mod.rs#L747

**Describe alternatives you've considered**

**Additional context**

https://github.com/apache/datafusion/pull/10801#issuecomment-2149452632

**Comment by marvinlanhenke** [comment]
for additional context and possibly [code pointers](https://github.com/apache/datafusion/issues/10752#issuecomment-2150024521) where Interval support is missing.

**Comment by alamb** [comment]
@marvinlanhenke  also points out that to completely support this ticket probably requires completing https://github.com/apache/arrow-rs/issues/5849 first

**Comment by tustvold** [comment]
It is incorrect to write statistics for interval types, as per the format specification - https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#interval

**Comment by alamb** [comment]
That makes sense. Thank you @tustvold
