### ISSUE TITLE
Add attributes and tags support for BufUploader

### ISSUE THREAD

**Issue by Xuanwo** [apache/arrow-rs#5867]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Part of https://github.com/apache/arrow-rs/pull/5835

**Describe the solution you'd like**

Add `attributes` and `tags` support in BufUploader

**Describe alternatives you've considered**

None

**Additional context**

I'm willing to implement this.

**Comment by tustvold** [comment]
I believe this is no longer planned as we instead added a `put` API to `BufWriter`. Feel free to reopen if I am mistaken
