### ISSUE TITLE
Cleanup ByteView construction

### ISSUE THREAD

**Issue by XiangpengHao** [apache/arrow-rs#5878]
**Describe the solution you'd like**

Now we have `try_append_view`, `append_view_unchecked`,  and manual construction of `ByteView` in the code base.
We should clean up the implementation to be consistent and potentially more performant, specifically, avoiding manually build ByteView, use `append_view_unchecked` when we are sure it is safe.

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #5879

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5879
