### ISSUE TITLE
Investigate why `InstanceCredentialProvider::cache` is flagged as dead code

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#5884]
**Describe the bug**
In https://github.com/apache/arrow-rs/pull/5883 a new version of Clippy flagged  `InstanceCredentialProvider::cache` as not used

To get CI clean again I disabled the clippy lint, but @Xuanwo  rightly suggests we look into the root cause: https://github.com/apache/arrow-rs/pull/5883/files#r1638538556

**To Reproduce**

**Expected behavior**
TLDR we should figure out why this was flagged as not used, and either fix the underlying issue or decide that it is not a problem

**Additional context**

**Comment by Xuanwo** [comment]
Let me do this.

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5884](https://github.com/apache/arrow-rs/issues/5884)
