### ISSUE TITLE
New null with view types are not supported

### ISSUE THREAD

**Issue by XiangpengHao** [apache/arrow-rs#5893]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The following test case should pass, but failed because view types are not handled in `ArrayData::new_null` (https://github.com/XiangpengHao/arrow-rs/blob/master/arrow-data/src/data.rs#L564)
```rust
    #[test]
    fn test_null_view_types() {
        let array_len = 32;
        let array = ArrayData::new_null(&DataType::BinaryView, array_len);
        assert_eq!(array.len(), array_len);
        for i in 0..array.len() {
            assert!(array.is_null(i));
        }
    }
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5894
