### ISSUE TITLE
Implement `compare_op` for `GenericBinaryView` 

### ISSUE THREAD

**Issue by XiangpengHao** [apache/arrow-rs#5897]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently the following test case(s) will fail:

```rust
    #[test]
    fn test_utf8_view_eq() {
        let values = vec![Some("small"), None, Some("larger than 12 bytes string")];
        let left = StringViewArray::from_iter(values.iter());
        let right = StringViewArray::from_iter(values.iter());
        crate::cmp::eq(&left, &right).unwrap();
    }

```

Because we haven't implemented the code to compare two view types in `compare_op` https://github.com/XiangpengHao/arrow-rs/blob/master/arrow-ord/src/cmp.rs#L227

I believe this is required to unblock https://github.com/apache/datafusion/issues/10919

**Describe the solution you'd like**

The solution should be fairly simple.

**Describe alternatives you've considered**

**Additional context**

**Comment by XiangpengHao** [comment]
take

**Comment by XiangpengHao** [comment]
> take

Seems arrow don't have the fancy `take` command as DataFusion's https://datafusion.apache.org/contributor-guide/index.html#finding-and-creating-issues-to-work-on

Can you assign me @alamb ?

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5900
