### ISSUE TITLE
FixedSizeList got out of range when the total length of the underlying values over i32::MAX

### ISSUE THREAD

**Issue by BubbleCal** [apache/arrow-rs#5901]
**Describe the bug**
I have a `Float32Array` which is with length over `i32::MAX`,
and then create FixedSizeList from this array values.
when access with index `i` where `i * value_length` is over the `i32::MAX`, get panic or error "offset overflow"

**To Reproduce**
```
#[test]
fn test_arrow_fsl() {
    let arr = Float32Array::from_iter_values(iter::repeat(0.0).take(i32::MAX as usize + 2));
    let fsl = FixedSizeListArray::try_new_from_values(arr.clone(), 1).unwrap();
    let value = fsl.value(arr.len() - 1);
    assert_eq!(value.len(), 1);
}
```

**Expected behavior**
access the value without panic/error if `i * value_length` is not over `usize::MAX`

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5902
