### ISSUE TITLE
Implement benchmarks for `compare_op` for `GenericBinaryView`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#5903]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Part of https://github.com/apache/arrow-rs/issues/5374

@XiangpengHao  added very nice support to compare kernels for GenericBinaryArray in https://github.com/apache/arrow-rs/pull/5900

**Describe the solution you'd like**
We should add benchmark coverage for these kernels to ensure we don't regress their performance and to help with future optimizations

**Describe alternatives you've considered**
Add tests for `=` and `!=` in https://github.com/apache/arrow-rs/blob/master/arrow/benches/comparison_kernels.rs

**Additional context**

**Comment by XiangpengHao** [comment]
take

Also relevant to https://github.com/apache/arrow-rs/pull/5922

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5924
