### ISSUE TITLE
Release arrow-rs / parquet minor version `52.1.0`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#5905]
## Is your feature request related to a problem or challenge? Please describe what you are trying to do.
52.0.0  https://crates.io/crates/arrow/52.0.0 was released June 6, 2024

Our release schedule is here  https://github.com/apache/arrow-rs?tab=readme-ov-file#release-versioning-and-schedule

## Describe the solution you'd like
A new release

## Describe alternatives you've considered

According to the release schedule, the next release should be a minor, non breaking release `52.1.0` released around early July 2024

## Additional context
Suggested content:
- [x] https://github.com/apache/arrow-rs/pull/5939
- [x] https://github.com/apache/arrow-rs/pull/5967
- [x] https://github.com/apache/arrow-rs/pull/5965

**Comment by alamb** [comment]
See also https://github.com/apache/arrow-rs/issues/5907 for a discussion on what to do with breaking API changes

**Comment by tustvold** [comment]
I intend to cut this in the first week of July

**Comment by alamb** [comment]
@tustvold  would it be ok if I handled this release (so I have practice doing the details)?

**Comment by tustvold** [comment]
That would be most appreciated, thank you

**Comment by alamb** [comment]
I am testing for breaking changes by testing the upgrade prior to releasing.
*  DataFusion upgrade seems to have gone without issue (no breaking changes): https://github.com/apache/datafusion/pull/11202
* I also ran the InfluxDB 3.0 tests against this branch and they seem to be fine

**Comment by alamb** [comment]
I am hoping  we can get  these PRs merged today

- [ ] https://github.com/apache/arrow-rs/pull/5967
- [ ]  https://github.com/apache/arrow-rs/pull/5965

I will create the release regardless at the end of today

**Comment by alamb** [comment]
Features merged. Working on making a release

**Comment by alamb** [comment]
Started vote thread: https://lists.apache.org/thread/3q859mgx3p2ltozqxojk8mxq75vq673o

**Comment by alamb** [comment]
Filed https://github.com/apache/arrow-rs/issues/5998 to track `52.0.0`

**Comment by alamb** [comment]
The release is available here:
  https://dist.apache.org/repos/dist/release/arrow/arrow-rs-52.1.0

It has also been published to crates.io 
* https://crates.io/crates/arrow/52.1.0
* https://crates.io/crates/parquet/52.1.0

https://lists.apache.org/thread/1g19f9oym5b6codwjt2lbr7zkr9wwy4d

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #5860

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5994
