### ISSUE TITLE
[DISCUSS] Release arrow-rs / parquet patch release `52.0.1`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#5906]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
52.0.0 https://crates.io/crates/arrow/52.0.0 was released June 6, 2024

52.1.0 is likely coming in early July: https://github.com/apache/arrow-rs/issues/5905

However, there may be a desire to do an earlier release, per @andygrove  -- https://github.com/apache/arrow-rs/pull/5895#issuecomment-2173998513

**Describe the solution you'd like**
Make a arrow 52.0.1 patch release

**Potential Content**
- [x] https://github.com/apache/arrow-rs/pull/5895 (per https://github.com/apache/arrow-rs/pull/5895#issuecomment-2173998513 / @andygrove )

**Comment by alamb** [comment]
Another potential alternative is to ait for 52.1.0 (the scheduled release https://github.com/apache/arrow-rs/issues/5905), perhaps accelerating its timeline

**Comment by tustvold** [comment]
Given the 52.1.0 release is slated for the first week of July unless this is especially urgent, I think I would prefer to wait - https://github.com/apache/arrow-rs/issues/5905#issuecomment-2184930141

**Comment by alamb** [comment]
Looks like we shall simply release 52.1.0: https://github.com/apache/arrow-rs/issues/5905 so closing this PR

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5895
