### ISSUE TITLE
Make ObjectStoreScheme in the object_store crate public

### ISSUE THREAD

**Issue by orf** [apache/arrow-rs#5911]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I want to parse an object store URL into a type. Using `parse_url` and `parse_url_opts` casts the result into a `Box<dyn ...>` which makes it impossible to get the underlying type from. 

**Describe the solution you'd like**

Making `ObjectStoreScheme` public will allow me to do:

```rust
let (scheme, path) = ObjectStoreScheme::parse("s3://foo/bar")
```

**Comment by drmorr0** [comment]
+1, I want to support all the different cloud providers in my app, but I need more fine-grained control over how the `ObjectStore` is constructed, so I can't just use `parse_url` -- having this public would be very useful, I literally just came here to submit a PR to do the same thing :)

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'object-store'} from #5912

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5911](https://github.com/apache/arrow-rs/issues/5911)
