### ISSUE TITLE
Implement arrow-row en/decoding for GenericByteView types

### ISSUE THREAD

**Issue by XiangpengHao** [apache/arrow-rs#5921]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I believe it is used in RowConverter, the code was triggered when trying to run tpc-h with StringView.

Reached unreachable code in https://github.com/apache/arrow-rs/blob/master/arrow-row/src/lib.rs#L1061
with StringViewArray.

**Describe the solution you'd like**

Implement it.

**Describe alternatives you've considered**

**Additional context**

**Comment by XiangpengHao** [comment]
take

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5922
