### ISSUE TITLE
Slicing list<struct<...>> doesn't pass the list offsets to struct children

### ISSUE THREAD

**Issue by nevi-me** [apache/arrow-rs#594]
**Describe the bug**

We resolved struct slices by passing the offset and length to child data, but this doesn't work on lists that have struct children, because when slicing lists, we don't pass its offset and length to its child data (a list has 1 child datum). This is because we can calculate this at runtime when indexing into a list.

**To Reproduce**

* Create a `list<struct<[int]>>` or a `map` array.
* Slice the array
* Try to slice into the array

**Expected behavior**

We should correctly slice into lists of structs, and maps

**Additional context**

I picked this up while addressing reviews on #491

**Comment by tustvold** [comment]
Closed by #4061
