### ISSUE TITLE
Error message in ArrowNativeTypeOp::neg_checked doesn't include the operation

### ISSUE THREAD

**Issue by LorrensP-2158466** [apache/arrow-rs#5944]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

When fixing issue https://github.com/apache/datafusion/issues/11076, I noticed the error message when overflowing in `ArrowNativeTypeOp::neg_checked` doesn't include the operation that caused the overflow, only the number itself.
```text
DataFusion CLI v39.0.0
> select (- -9223372036854775808);
Arrow error: Compute error: Overflow happened on: -9223372036854775808
```
**Describe the solution you'd like**

Shouldn't this be:
```text
DataFusion CLI v39.0.0
> select (- -9223372036854775808);
Arrow error: Compute error: Overflow happened on: - -9223372036854775808
```
**Describe alternatives you've considered**
 
**Additional context**

**Comment by zhao-gang** [comment]
take

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5980
