### ISSUE TITLE
Optimize StringView row decoding

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#5945]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Part of https://github.com/apache/arrow-rs/issues/5374

@XiangpengHao  implemented row format --> ByteView (StringView / BinaryView) encoding/decoing in https://github.com/apache/arrow-rs/pull/5922/files

**Describe the solution you'd like**
1. Add a benchmark for StringView to https://github.com/apache/arrow-rs/blob/master/arrow/benches/row_format.rs
2. Make the row conversion faster

**Describe alternatives you've considered**
@tustvold  noted that a potential performance improvement  https://github.com/apache/arrow-rs/pull/5922/files#r1650032068 -- namely to build the array directly rather than build a StringArray and then convert to StringView

**Additional context**

**Comment by XiangpengHao** [comment]
take, as it seems that decoding string view is taking longer than it should be.

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6044
