### ISSUE TITLE
Add `min_bytes` and `max_bytes` to `PageIndex`

### ISSUE THREAD

**Issue by tshauck** [apache/arrow-rs#5949]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently `PageIndex`, while similar to `Statistics`, doesn't support `max_bytes` and `min_bytes`.

**Describe the solution you'd like**

Add `max_bytes` and `min_bytes` to `PageIndex<T>` where `T: AsBytes`.

**Describe alternatives you've considered**

**Additional context**

There was some discussion of this w.r.t. this ticket: https://github.com/apache/datafusion/issues/10951 because f16's physical type is a fixed len binary array. Ultimately the better solution is for parquet to natively support f16 that may take longer and be more involved when it's implemented.

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #5950
