### ISSUE TITLE
Optimize `like`/`ilike` kernels for StringView

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#5951]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

@XiangpengHao  added support for `StringView` to the like/ilike kernels in https://github.com/apache/arrow-rs/pull/5931

https://github.com/apache/arrow-rs/pull/5931#pullrequestreview-2133304771

This PR does not leverage the special 4 bytes inlined prefix for large string views, which might be able to optimize certain cases (specifically for quickly testing if the `starts_with` variant of like doesn't match without having to consult the actual strings, as @wjones127 discusses in https://github.com/apache/arrow-rs/pull/5931#pullrequestreview-2133304771

>> does not leverage the inlined 4 bytes to shortcut some comparison. I plan to leave this as a future work as it can significantly complicate the code. (I also doubt that we can gain any benefit)
>
> I agree we should only start adding specialized paths if we determine it is worth it. starts_with might be, especially if the parameter is short enough to always be able to use the prefix. We can decide based on benchmarks which are appropriate.

I added a benchmark in https://github.com/apache/arrow-rs/pull/5931

**Describe the solution you'd like**
Investigate various ways to make the benchmark faster. Run the benchmark like this:

```shell
cargo bench --bench comparison_kernels -- utf8view
```

**Describe alternatives you've considered**
Maybe it is fast enough as is

**Additional context**

**Comment by xinlifoobar** [comment]
take

**Comment by xinlifoobar** [comment]
I read through the code and have some initial ideas. There are serval sub-optimizations:

Good to go:
- Startwith/IStartwith when the needle has length < 4

Side effects (might be, this could be removed completed by specialized string view functions):
- Contains: when the needle has length < 4 and the first 4 bytes match.
- Regex: when the regex has match expected < 4 and the first 4 bytes match.

I would start with startwith and istartwith and needs some inputs for the latter 2. Please let me know your thoughts on generating better implementations :).

CC @alamb  @XiangpengHao

**Comment by XiangpengHao** [comment]
Sounds good to me! Here's the current comparsion function that has similar handling for 4/12 bytes:

https://github.com/apache/arrow-rs/blob/master/arrow-array/src/array/byte_view_array.rs#L340-L399

**Comment by alamb** [comment]
It seems to me like this ticket was completed with https://github.com/apache/arrow-rs/pull/6231

@xinlifoobar has some ideas for improving other kernels (like regexp) here https://github.com/apache/arrow-rs/issues/5951#issuecomment-2283949913

I did file https://github.com/apache/arrow-rs/issues/6370 for `regexp_is_match_utf8`

Let me know if there are other kernels that we should update
