### ISSUE TITLE
FFI implementation deviates from specification for memory management on export

### ISSUE THREAD

**Issue by roee88** [apache/arrow-rs#596]
The FFI implementation deviates from the C Data Interface specification in [Member allocation](https://arrow.apache.org/docs/format/CDataInterface.html#member-allocation).

> The ArrowSchema and ArrowArray structures follow the same conventions for memory management. The term “base structure” below refers to the ArrowSchema or ArrowArray that is passed between producer and consumer – not any child structure thereof.
>
> Member allocation
>
> It is intended for the base structure to be stack- or heap-allocated by the consumer. In this case, the producer API should take a pointer to the consumer-allocated structure.

Taking an _example_ of a pyarrow consumer and arrow-rs producer, my understanding is that the intended behavior is:
1. pyarrow allocates empty ffi structure(s) 
2. pyarrow pass the empty ffi structure(s) to arrow-rs
3. arrow-rs fills the empty ffi structure(s) from a rust Array/Schema/RecordBatch
4. when done with the data pyarrow calls the release callback on the ffi structure(s) that it allocated in step 1

This doesn't seem to be supported currently. The current implementation for exporting through the C Data Interface only allows converting an arrow array/schema to ffi array/schema, both allocated by arrow-rs. A solution to this must also take into account that the release callback must be called explicitly by the consumer, avoiding calling release unintentionally by drop.

The opposite path is correctly implemented (although a bit too complex IMHO) as demonstrated in https://github.com/apache/arrow-rs/blob/9f40f899e439d072fc859e0b4abf46776387e0d1/arrow-pyarrow-integration-testing/src/lib.rs#L174 (rust allocates empty, pass to the the a python exporter that fills those structs).

**Comment by jorgecarleitao** [comment]
I agree.

What I am not following is which pyarrow API we should use to create the two pointers: `pyarrow.cffi` is not public, so we can't really allocate from within pyarrow/c++ to populate it.

**Comment by roee88** [comment]
This issue is not related to pyarrow, we're actually starting to experiment with other arrow implementations. However, what makes you say it's not public? I see it in https://github.com/apache/arrow/blob/apache-arrow-5.0.0/python/pyarrow/cffi.py and if I `pip install pyarrow` (pyarrow-4.0.1) I can successfully run `from pyarrow.cffi import ffi`.

**Comment by jorgecarleitao** [comment]
Ups, you are right; I was using an older version of pyarrow that did not have this exposed.

**Comment by roee88** [comment]
I think that the current implementation also leaks memory. For example in https://github.com/apache/arrow-rs/blob/6bf1988852f87da21a163203eec4c83a7b692901/arrow-pyarrow-integration-testing/src/lib.rs#L192-L202 array.to_raw internally calls Arc::into_raw on the structures but nothing ever calls Arc::from_raw to release them. Is that correct? 
cc @kszucs
