### ISSUE TITLE
Implement `eq` comparison for StructArray

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#5960]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
[arrow](https://docs.rs/arrow/latest/arrow/index.html)::[compute](https://docs.rs/arrow/latest/arrow/compute/index.html)::[kernels](https://docs.rs/arrow/latest/arrow/compute/kernels/index.html)::[cmp](https://docs.rs/arrow/latest/arrow/compute/kernels/cmp/index.html)::[eq](https://docs.rs/arrow/latest/arrow/compute/kernels/cmp/fn.eq.html#) does not support `StructArray`

Here is an example

```rust
use arrow::array::{ArrayRef, Int32Array, StructArray};
use arrow::compute::kernels::cmp::eq;
use arrow::datatypes::{DataType, Field, Schema};
use std::sync::Arc;

fn main() {
    let nested_schema = Arc::new(Schema::new(vec![
        Field::new("id", DataType::Int32, true),
        Field::new("lat", DataType::Int32, true),
        Field::new("long", DataType::Int32, true),
    ]));
    let schema = Arc::new(Schema::new(vec![
        Field::new("value", DataType::Int32, true),
        Field::new(
            "nested",
            DataType::Struct(nested_schema.fields.clone()),
            true,
        ),
    ]));

    let arr1: ArrayRef = Arc::new(StructArray::from(vec![
        (
            Arc::new(Field::new("id", DataType::Int32, true)),
            Arc::new(Int32Array::from(vec![1, 2, 3])) as ArrayRef,
        ),
        (
            Arc::new(Field::new("lat", DataType::Int32, true)),
            Arc::new(Int32Array::from(vec![1, 2, 3])) as ArrayRef,
        ),
        (
            Arc::new(Field::new("long", DataType::Int32, true)),
            Arc::new(Int32Array::from(vec![1, 2, 3])) as ArrayRef,
        ),
    ]));

    let arr2: ArrayRef = Arc::new(StructArray::from(vec![
        (
            Arc::new(Field::new("id", DataType::Int32, true)),
            Arc::new(Int32Array::from(vec![1, 2, 3])) as ArrayRef,
        ),
        (
            Arc::new(Field::new("lat", DataType::Int32, true)),
            Arc::new(Int32Array::from(vec![1, 2, 3])) as ArrayRef,
        ),
        (
            Arc::new(Field::new("long", DataType::Int32, true)),
            Arc::new(Int32Array::from(vec![1, 2, 3])) as ArrayRef,
        ),
    ]));

    let eq_result = eq(&arr1, &arr2).unwrap();
    println!("{:?}", eq_result);
}
```

It currenty fails like this:

```
thread 'main' panicked at src/main.rs:56:38:
called `Result::unwrap()` on an `Err` value: InvalidArgumentError("Invalid comparison operation: Struct([Field { name: \"id\", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \"lat\", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \"long\", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }]) == Struct([Field { name: \"id\", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \"lat\", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \"long\", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }])")
```

**Describe the solution you'd like**
I would like `eq` and the other comparison kernels to support StructArray and the example to pass

**Describe alternatives you've considered**
We can implement comparison downstream  via [arrow](https://docs.rs/arrow/latest/arrow/index.html)::[array](https://docs.rs/arrow/latest/arrow/array/index.html)::[make_comparator](https://docs.rs/arrow/latest/arrow/array/fn.make_comparator.html#) as done in https://github.com/apache/datafusion/pull/11117

**Additional context**
This was reported upstream in datafusion: https://github.com/apache/datafusion/issues/10749

@jayzhan211  added comparison to the dynamic comparator in https://github.com/apache/arrow-rs/pull/5792

**Comment by alamb** [comment]
Here is the relevant error that is happening: https://github.com/apache/arrow-rs/blob/0e56fd5c4dbc61c03595c6a54068d229e6996778/arrow-ord/src/cmp.rs#L236

**Comment by jayzhan211** [comment]
Note that we have a discussion about where to implement comparison for List https://github.com/apache/arrow-rs/issues/5407

The conclusion is that we implement it in datafusion, which the related PR is https://github.com/apache/datafusion/pull/11091

If we have the similar configurable null issue for struct, we should also implement it in datafusion.

**Comment by alamb** [comment]
Thanks @jayzhan211  -- I didn't know that.

If this is a design decision in arrow-rs perhaps we can update the documentation / the error message to make it clear that not only is operation not supported, it will not be (and hint to use make_comparator instead)

**Comment by jayzhan211** [comment]
There is docs in `make_comparator` https://github.com/apache/arrow-rs/pull/5942

**Comment by alamb** [comment]
> There is docs in `make_comparator` #5942 . But error message could be improved

Ah, thanks I missed that. I will make a PR to improve the error message

**Comment by alamb** [comment]
https://github.com/apache/arrow-rs/pull/5961
