### ISSUE TITLE
why not implement ArrowPrimitiveType trait for Boolean

### ISSUE THREAD

**Issue by zhuliquan** [apache/arrow-rs#5962]
**Which part is this question about**

arrow-array/types.rs

**Describe your question**

I notice that arrow implement ArrowPrimitiveType for int8/int16/int32/.... . why not ignore boolean type.
https://github.com/apache/arrow-rs/blob/0e56fd5c4dbc61c03595c6a54068d229e6996778/arrow-array/src/types.rs#L96

**Additional context**

**Comment by tustvold** [comment]
Arrow stores booleans as packed bitmaps and so they need a distinct array type from integers, etc...

**Comment by zhuliquan** [comment]
> Arrow stores booleans as packed bitmaps and so they need a distinct array type from integers, etc...

Is this done to make Boolean storage more compact？

**Comment by tustvold** [comment]
More compact and more efficient to process
