### ISSUE TITLE
Relax `WriteMultipart` API to support aborting after completion

### ISSUE THREAD

**Issue by fsdvh** [apache/arrow-rs#5977]
In the current implementation `finish` will consume our writer and in case of an error during the finish call we wound be able to abort our write.

I suggest changing the following:

```rust
pub async fn finish(mut self) -> Result<PutResult>
```
to something like this:

```rust
pub async fn finish(&mut self) -> Result<PutResult>
```

To be able to call the abort method after that

We potentially can safeguard ourselves from multiple finish calls by adding an `is_finished` flag to the writer

**Comment by fsdvh** [comment]
So I made a change to make a cleanup automatic process during complete, wdyt @tustvold?

```
pub async fn finish(mut self) -> Result<PutResult> {
        if !self.buffer.is_empty() {
            let part = std::mem::take(&mut self.buffer);
            self.put_part(part.into())
        }

        self.wait_for_capacity(0).await?;

        match self.upload.complete().await {
            Err(e) => {
                self.tasks.shutdown().await;
                self.upload.abort().await?;
                Err(e)
            }
            Ok(result) => Ok(result),
        }
    }
```

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'object-store'} from #5974

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#5977](https://github.com/apache/arrow-rs/issues/5977)
