### ISSUE TITLE
Wrong error type in case of invalid amount in Interval components

### ISSUE THREAD

**Issue by DDtKey** [apache/arrow-rs#5986]
**Describe the bug**
Currently, if Interval value contains invalid amount component `NotYetImplemented` error type is returned.
That doesn't seem correct, because such values are not going to be supported (or at least, it's confusing)

Let's take a look at such example:

```sql
INTERVAL '1 MONTH DAY'
```
This is an obvious typo/mistake which leads to such error, but in fact it's just invalid value (missing number before `DAY`)

**To Reproduce**
There are tests for this case already:

https://github.com/apache/arrow-rs/blob/bb1250ceb8afe9367fe577821d2d384cd38c2d6e/arrow-cast/src/cast/mod.rs#L4403-L4417

**Expected behavior**
Return `ParseError`, like other errors from `parse_interval_components` 

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #5987
