### ISSUE TITLE
Format timestamps that have a timezone using RFC339 format

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#599]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I have timestamps from UTC and I want to format them in RFC3339 format, such as `2021-07-20T23:28:50Z`

Right now, the only formatting supported by Arrow is "naive" timestamps (aka without any timezone) format, such as `2021-07-20 23:28:50` (note missing Z)

**Describe the solution you'd like**
I would like to to be able to specify that a timestamp is printed with the specified embedded timezone, ideally in RFC3339 format

**Describe alternatives you've considered**

**Additional context**
It is not even possible to create arrays that hold such timestamps yet. See https://github.com/apache/arrow-rs/issues/597 for details

**Comment by tustvold** [comment]
Timezones are supported
