### ISSUE TITLE
[object_store] Support constructing `object_store::path::Path` without encoding or decoding

### ISSUE THREAD

**Issue by nameexhaustion** [apache/arrow-rs#5993]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Given a `String` that is already percent-encoded, I want to be able to construct a `Path` without any percent encoding or decoding (i.e. maintain the string value as-is). This currently isn't possible with the available ways to construct `Path`:

* `Path::parse` / `from` will percent-encode the string
* `Path::from_url_path` will percent-decode the string

**Describe alternatives you've considered**
* Double percent-encoding then passing it to `from_url_path`
* `unsafe transmute`

**Comment by tustvold** [comment]
`Path::parse` doesn't percent encode?

**Comment by nameexhaustion** [comment]
Ah - I think I mistakenly thought the `From<&str>` was the same as parse. Thanks for the tip!
