### ISSUE TITLE
use GCE_METADATA_HOST and GCE_METADATA_IP env vars in object_store GCP auth

### ISSUE THREAD

**Issue by barronw** [apache/arrow-rs#6014]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I'm trying to use the GCP integration through a proxy metadata server, but the server host and IP are hardcoded.

**Describe the solution you'd like**

`object_store` should check `GCE_METADATA_HOST` and `GCE_METADATA_IP` env vars before defaulting to the currently hardcoded values. The Google Python libraries do this ([example](https://github.com/googleapis/google-auth-library-python/blob/1270217556a0249b6be8824e2b6209371f24e400/google/auth/compute_engine/_metadata.py#L38)). 

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#6014](https://github.com/apache/arrow-rs/issues/6014)
