### ISSUE TITLE
Release arrow-rs / parquet major version `53.0.0` (September 2024)

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#6016]
## Is your feature request related to a problem or challenge? Please describe what you are trying to do.

https://github.com/apache/arrow-rs/issues/5998 tracks releasing `52.2.0` in early August 2024

Our release schedule is here  https://github.com/apache/arrow-rs?tab=readme-ov-file#release-versioning-and-schedule

## Describe the solution you'd like
Checklist:
- [x] Release notes and bump version: https://github.com/apache/arrow-rs/pull/6338
- [x] Vote thread: https://lists.apache.org/thread/91fckqxwpvcov26ty4s2wn11czkcxxbf
- [ ] Document feature branch process: https://github.com/apache/arrow-rs/pull/6067
- [x] Update main crate docs with next quarter release schedules: https://github.com/apache/arrow-rs/pull/6125

## Describe alternatives you've considered

According to the release schedule, the next release should be major `53.0.0` (including API changes) released early September 2024

## Additional context
Suggested content:
- [x] Upgrade py03: https://github.com/apache/arrow-rs/pull/6018

**Comment by alamb** [comment]
Per discussion on https://github.com/apache/arrow-rs/issues/6050 we are going to make a 53.0.0-dev feature branch so we can merge / integrate breaking API changes before `master` opens for `53.0.0`.

**Comment by alamb** [comment]
I am preparing the RC now

**Comment by alamb** [comment]
I hit an error validating the RC1: https://github.com/apache/arrow-rs/issues/6343

I have a fix and I will make an RC2 today if no one beats me to it

**Comment by alamb** [comment]
Release thread: https://lists.apache.org/thread/91fckqxwpvcov26ty4s2wn11czkcxxbf

**Comment by alamb** [comment]
The release is now available on crates.io: https://crates.io/crates/arrow/53.0.0

The next release is tracked with https://github.com/apache/arrow-rs/issues/6340

**Comment by niebayes** [comment]
Great work! The newly introduced `execute_ingest` is very helpful!

**Comment by alamb** [comment]
> Great work! The newly introduced `execute_ingest` is very helpful!

I think we can thank @djanderson  for that https://github.com/apache/arrow-rs/pull/6201  ❤️
