### ISSUE TITLE
Release object store minor `0.10.2` ~or major `0.11.0`~ (Mid July 2024)

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#6022]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

https://github.com/apache/arrow-rs/tree/master?tab=readme-ov-file#object_store-crate

> The [object_store](https://crates.io/crates/object_store) crate is released independently of the arrow and parquet crates and follows [Semantic Versioning](https://semver.org/). We aim to release new versions approximately every 2 months.

Last release was May 14, 2024, that means the next release should be approximately July 14, 2024

**Describe the solution you'd like**
Make a new object store release

**Describe alternatives you've considered**
Here are the commits that went into object_store: https://github.com/apache/arrow-rs/commits/master/object_store

**Additional context**

**Comment by alamb** [comment]
As of today there do not appear to be any breaking API changes to object store and thus I think we can release a minor `0.10.1` version

**Comment by alamb** [comment]
@Xuanwo  asked about this in https://github.com/apache/arrow-rs/pull/6013

**Comment by alamb** [comment]
Unless someone else wants to do this I will plan do make a release candidate early next week with a release timeline of mid next week

**Comment by Xuanwo** [comment]
> As of today there do not appear to be any breaking API changes to object store and thus I think we can release a minor `0.10.1` version

object_store 0.10.0 has already released, we will need a `0.10.2`

**Comment by alamb** [comment]
> > As of today there do not appear to be any breaking API changes to object store and thus I think we can release a minor `0.10.1` version
> 
> object_store 0.10.0 has already released, we will need a `0.10.2`

You are right -- https://crates.io/crates/object_store/0.10.1

Thank you @Xuanwo  I updated the description

**Comment by alamb** [comment]
I plan to work on this this week

**Comment by Xuanwo** [comment]
Thanks a lot!

**Comment by alamb** [comment]
I am beginning to make the release now

**Comment by alamb** [comment]
Vote thread: 
https://lists.apache.org/thread/8yzk5zrrwg0lx45706dcrs05xcvfy6y1
Crates.io release: https://crates.io/crates/object_store/0.10.2

We have a release 🎉

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #6013
