### ISSUE TITLE
Min/max support for String/BinaryViewArray

### ISSUE THREAD

**Issue by XiangpengHao** [apache/arrow-rs#6052]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Part of #5374 
We haven't support them yet. In DataFusion query like below, we will need to call min_string_view(), which is not yet implemented
```sql
SELECT "SearchPhrase", MIN("URL"), COUNT(*) AS c FROM hits WHERE "URL" LIKE '%google%' AND "SearchPhrase" <> '' GROUP BY "SearchPhrase" ORDER BY c DESC LIMIT 10;
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by XiangpengHao** [comment]
take

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6053
