### ISSUE TITLE
Upgrade arrow-flight to tonic 0.12

### ISSUE THREAD

**Issue by sergiimk** [apache/arrow-rs#6072]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Release of http 1.0 and hyper 1.0 created a cascade of major upgrades in many protocol libraries. These upgrades have not been yet incorporated into `arrow-flight` which causes a significant duplication of dependencies including crates like tonic, axum, hyper, http, h2...

Note that this causes dependency duplication even within the `arrow-rs` libraries alone, as `object_store` has already migrated to the new http stack.

**Describe the solution you'd like**

Upgrade `arrow-flight` to:
- tonic 0.12
- prost 0.13

**Comment by alamb** [comment]
This is currently scheduled for release in `53.0.0` (Early September 2023).  The work is on the 53 dev branch -- thanks again @BugenZhao https://github.com/apache/arrow-rs/pull/6041

**Comment by alamb** [comment]
We have merged this code to main so marking this issue is resolved
https://github.com/apache/arrow-rs/blob/df59cddcec98003b8e235b03c52eafeeb7573e08/arrow-flight/Cargo.toml#L51
