### ISSUE TITLE
RecordReader other than Int32Type?

### ISSUE THREAD

**Issue by Luosuu** [apache/arrow-rs#6078]
**Which part is this question about**

I know that we can construct a `RecordReader` like

```rust
let mut record_reader: GenericRecordReader<Vec<i32>, ColumnValueDecoderImpl<Int32Type>> =
        RecordReader::<Int32Type>::new(column_desc.clone());
```

In many tests, there are
```rust
 let mut record_reader = RecordReader::<Int32Type>::new(desc.clone());
```
But I don't see types other than Int32Type, such as ByteArrayType.

**Describe your question**

Is RecordReader exclusive to Int32Type?
When I naively try to construct a RecordReader for ByteArrayType like:

```rust
let mut record_reader = RecordReader::<ByteArrayType>::new(desc.clone());
```

I got errors like

```
error[E0599]: the function or associated item `new` exists for struct `GenericRecordReader<Vec<ByteArray>, ColumnValueDecoderImpl<ByteArrayType>>`, but its trait bounds were not satisfied
....
    |
387 |     let mut record_reader = RecordReader::<ByteArrayType>::new(column_desc.clone());
    |                                                            ^^^ function or associated item cannot be called due to unsatisfied trait bounds
    |
   ::: parquet/src/data_type.rs:106:1
    |
106 | pub struct ByteArray {
    | -------------------- doesn't satisfy `data_type::ByteArray: std::marker::Copy`
```

**Additional context**

I am just learning about the codebase.

**Comment by alamb** [comment]
Sorry I am not faimilar with this API -- depending on what you are trying to do, it may make sense to look at ArrowReader to read the data out as ArrowArrays and that supports all types

**Comment by Luosuu** [comment]
@alamb Thank you for your reply and suggestion! Yes maybe I should deal with this myself..
