### ISSUE TITLE
Faster min/max for string/binary view arrays

### ISSUE THREAD

**Issue by XiangpengHao** [apache/arrow-rs#6088]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Current min/max support was added in #6053, with a template solution for generic strings. This is suboptimal, as string view can benefit from faster min/max just like it can have faster `cmp` operations.

**Describe the solution you'd like**

Use the fast string view cmp operation instead of the generic one. My local testing shows that a special implementation can be twice as fast.

Part of #5374, and https://github.com/apache/datafusion/issues/10918

**Describe alternatives you've considered**

**Additional context**

**Comment by XiangpengHao** [comment]
take

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6089
