### ISSUE TITLE
Allow flushing or non-buffered writes from `arrow::ipc::writer::StreamWriter`

### ISSUE THREAD

**Issue by V0ldek** [apache/arrow-rs#6099]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I am designing an API boundary that uses Arrow IPC to pass messages around. My requirement is that I need control at granularity of individual encapsulated messages, so for example I want to be able to force that at a given moment the initial Schema has definitely been written to the stream, or that all RecordBatches written thus far have been flushed.

I am using a custom `Writer` implementation with `StreamWriter`. Currently this is impossible to achieve because the `StreamWriter` [internally wraps any passed `Writer` into a `BufWriter`](https://github.com/apache/arrow-rs/blob/ee5694078c86c8201549654246900a4232d531a9/arrow-ipc/src/writer.rs#L1035) and exposes no way to flush.

**Describe the solution you'd like**
The simplest solution would be to expose an `fn flush(&mut self)` on the `StreamWriter` that would force the internal `BufWriter` to flush to the user-provided `Writer`.

**Describe alternatives you've considered**
As an alternative and a bigger (IMO) improvement, an option could be given to `IpcWriteOptions` to disable internal buffering. In my case the custom `Writer` implementation is quite complex and well-optimised already, and the `BufWriter` on top does not actually give any benefit, rather creates an additional overhead. A simple flag `use_buf_writer` set to `true` by default but possible to override would solve this. Internally the `writer` field of `StreamWriter` would need to be changed to some more complicated writer, e.g.

```rust
enum MaybeBuffered<W> {
  Raw(W),
  Buffered(BufWriter<W>)
}
```

EDIT: I looked more into the codebase and I can see there is `try_new_unbuffered` in `StreamReader` already, but that API is a bit different - the "buffered" version explicitly returns `StreamReader<BufReader<R>>`, so this wouldn't be possible to do for the writer API without a breaking change.

I'd be willing to make a PR for either of those changes, but wanted to ask you whether these make sense and would be accepted. This is quite important and blocking for me at the moment.

**Comment by V0ldek** [comment]
I proposed the `flush` method in #6108, it's a small change.

Actually I think the buffering change can be done without a breaking change?

1. The `try_new` and `try_new_with_options` would not wrap the `Writer` in the `BufWrite`. This is not a breaking change as the `writer` field is private and never exposed directly.
2. We can add `try_new_buffered` as a convenience method to create `StreamWriter<BufWriter<W>>` directly.

A cosmetic issue is that this is inverted wrt. the `reader` API. But maybe it should be that way for `reader` as well? As in, remove `try_new_unbuffered` from reader and switch so that the default is unbuffered?

**Comment by alamb** [comment]
> Actually I think the buffering change can be done without a breaking change?

I am not sure -- but since our next release will have breaking changes in it anyways, I think it would be fine to make

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6108
