### ISSUE TITLE
Allow Position to support arbitrary Cursor type

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#61]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-8170

Hi, I'm currently writing in-memory page writer in order to support buffered row group writer (just like in C++ version), and...
 * I'd like to reuse SerializedPageWriter
 * SerializedPageWriter requires sink supports util::Position (which is private)
 * There's Position impl for Cursor, but unnecessarily restricts to mutable references for internal type.

So I'd like to make one line change in order to lift that type restriction and allow me implementation.

**Comment by tustvold** [comment]
Closed by #1719
