### ISSUE TITLE
Implement `Into<Arc<dyn Array>>` for `ArrayData`

### ISSUE THREAD

**Issue by ParkMyCar** [apache/arrow-rs#6104]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

At a serialization layer I want to go from `ArrayData` to an `Arc<dyn Array>` and some logic higher up will downcast the `Arc<dyn Array>` into a specific type.

**Describe the solution you'd like**

Concrete array types, e.g. `UInt32Array`, implement [`From<ArrayData>`](https://docs.rs/arrow/latest/arrow/array/type.UInt32Array.html#impl-From%3CArrayData%3E-for-PrimitiveArray%3CT%3E). Implementing `Into<Arc<dyn Array>> for ArrayData` seems like it would be symmetrical.

**Describe alternatives you've considered**

The `Array` trait implements [`to_data(&self) -> ArrayData`](https://docs.rs/arrow/latest/arrow/array/trait.Array.html#tymethod.to_data), maybe `ArrayData` could implement `to_array(&self) -> Arc<dyn Array>`

**Additional context**

Apologies if this is already possible, I couldn't find it in the docs

**Comment by alamb** [comment]
Seems like a nice improvement to me.

**Comment by tustvold** [comment]
There is a `make_array` method that does this

**Comment by ParkMyCar** [comment]
Perfect, `make_array` is what I was looking for! Do you think it would still be worthwhile to implement `Into<Arc<dyn Array>> for ArrayData`? If not, feel free to close out this issue!

**Comment by alamb** [comment]
> Perfect, `make_array` is what I was looking for! Do you think it would still be worthwhile to implement `Into<Arc<dyn Array>> for ArrayData`? If not, feel free to close out this issue!

I think it would be worthwhile as it would make it more discoverable -- could you make a PR @ParkMyCar ?

**Comment by tustvold** [comment]
I could be mistaken, but I believe the orphan rules may prevent you from doing so

**Comment by ParkMyCar** [comment]
> > Perfect, `make_array` is what I was looking for! Do you think it would still be worthwhile to implement `Into<Arc<dyn Array>> for ArrayData`? If not, feel free to close out this issue!
> 
> I think it would be worthwhile as it would make it more discoverable -- could you make a PR @ParkMyCar ?

Yeah I'll whip this up! Hopefully orphan rules don't prevent it :)

**Comment by ParkMyCar** [comment]
Darn, yeah orphan rules and crate layout currently prevent it.

```
// approach 1 
//
// In the `arrow-data` crate, this doesn't work because `arrow-array` depends on `arrow-data`
// and we'd end up with a circular dependency.
impl Into<Arc<dyn Array>> for ArrayData { ... }
```

```
// approach 2
//
// In the `arrow-array` crate. I thought this would work, and it does if we used
// `Box<dyn Array>`, but `Arc` is not marked as "fundamental" like Box is.
//
// See: https://users.rust-lang.org/t/how-to-bypass-or-relax-orphan-rules/82999
impl From<ArrayData>  for Arc<dyn Array> { ... }
```

**Comment by alamb** [comment]
Thanks for trying 🙏
