### ISSUE TITLE
Release object store `0.11.0` (breaking API) around Aug 15 2024

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#6121]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Following on from https://github.com/apache/arrow-rs/issues/6022

There are several breaking changes queued up:
- [x] https://github.com/apache/arrow-rs/pull/6070
- [x] https://github.com/apache/arrow-rs/pull/6165

**Describe the solution you'd like**
Let's plan for a major release

**Describe alternatives you've considered**
Do a minor release
**Additional context**

**Comment by tustvold** [comment]
This probably needs to sync up with a major arrow-rs release, although I have to confess to being a tad confused what is happening there

**Comment by alamb** [comment]
The next major arrow release is 53.0.0 and scheduled for early September. I am tracking it here https://github.com/apache/arrow-rs/issues/6016

**Comment by tustvold** [comment]
Right so the object_store breaking release would need to come before this

**Comment by alamb** [comment]
> Tbh I'm not sure there is really enough pending changes to warrant a breaking object_store release at this point

The only one I know of is https://github.com/apache/arrow-rs/pull/6070.

On the other hand having an easy to update version might not be terrible 🤔 

Maybe we can reasses in 2 weeks and see what else has come up

**Comment by alamb** [comment]
I am beginning to prepare a release candidate

**Comment by alamb** [comment]
We have an RC and a vote thread https://lists.apache.org/thread/dzo578l67jz2v60y14gr4zwz35o3fv05

**Comment by alamb** [comment]
I needed to create a second RC due to https://github.com/apache/arrow-rs/issues/6233

Many thanks again to @Xuanwo  reporting and helping review the changes

The RC2 voting thread is here: https://lists.apache.org/thread/33oqdlmwnsxm9zs68rmtx7bpo948tf34

**Comment by Xuanwo** [comment]
Thank you very much for driving this. One risk I observed is that only @alamb and @tustvold participate in the release process. I will find some time to help improve the release process and encourage more people to join in.

**Comment by alamb** [comment]
The release is available here:
  https://dist.apache.org/repos/dist/release/arrow/arrow-object-store-rs-0.11.0

It is also available on crates.io: https://crates.io/crates/object_store/0.11.0

I am tracking the next release here https://github.com/apache/arrow-rs/issues/6263

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#6121](https://github.com/apache/arrow-rs/issues/6121)
