### ISSUE TITLE
Use `LevelHistogram` throughout Parquet metadata

### ISSUE THREAD

**Issue by etseidl** [apache/arrow-rs#6134]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Related to #6129. #6105 added a new `LevelHistogram` struct to represent histograms recently added to the spec. There remain places where this histogram data is still represented with a `Vec<i64>`.

**Describe the solution you'd like**
Replace the remaining bare vectors (in `PageIndex` and `ColumnIndexBuilder` with the new struct.

**Describe alternatives you've considered**
The vectors in `ColumnIndexBuilder` could be left as is since they are closer to the thrift representation, but I think it's cleaner for all level histograms outside actual thrift structs to share the same interface.

**Additional context**
See https://github.com/apache/arrow-rs/pull/6105#discussion_r1693378223

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #6135
