### ISSUE TITLE
Offset of sliced Array is 0

### ISSUE THREAD

**Issue by kylebarron** [apache/arrow-rs#6152]
**Describe the bug**

In Python with pyarrow, we can check that an array has been sliced by checking its `offset`:

```py
import pyarrow as pa
arr = pa.array([1, 2, 3, 4])
arr.offset
# 0
sliced = arr.slice(2, 2)
sliced.offset
# 2
```

However it seems that in arrow-rs `offset` is hard-coded to be `0`:
https://github.com/apache/arrow-rs/blob/80ed7128510bac114c6feec08c34ef3beed3a44a/arrow-array/src/array/primitive_array.rs#L1112-L1114

So that means this simple test fails:

```rs
#[cfg(test)]
mod test {
    use arrow::datatypes::Int64Type;
    use arrow_array::{Array, PrimitiveArray};

    #[test]
    fn test_offset() {
        let arr: PrimitiveArray<Int64Type> = PrimitiveArray::from(vec![1, 2, 3, 4]);
        let offset = 2;
        let sliced = arr.slice(offset, 2);
        assert_eq!(sliced.offset(), offset);
    }
}
```

```
assertion `left == right` failed
  left: 0
 right: 2
```

This seems like a bug, or am I missing something?

**To Reproduce**

Above test.

**Expected behavior**

Expected `array.offset()` to reflect the array's slice.

**Additional context**

This was found while researching https://github.com/apache/arrow-rs/issues/6151, and is somewhat related.

**Comment by wjones127** [comment]
I'm guessing the reason is we slice the underlying buffer here:

https://github.com/apache/arrow-rs/blob/80ed7128510bac114c6feec08c34ef3beed3a44a/arrow-array/src/array/primitive_array.rs#L747-L748

It does make me wonder if we should just remove `offset` from the Array and expose APIs on the buffers themselves for seeing if it's sliced. Is there a use case you have for wanting to know this offset?

**Comment by kylebarron** [comment]
In a general sense, it can be useful to know "is the array at hand sliced". In the specific task at hand, in https://github.com/kylebarron/arro3 I'm trying to match core pyarrow APIs using arrow-rs. And so I'm trying to match pyarrow's [offset](https://arrow.apache.org/docs/python/generated/pyarrow.Array.html#pyarrow.Array.offset) attribute.

**Comment by tustvold** [comment]
> And so I'm trying to match pyarrow's [offset](https://arrow.apache.org/docs/python/generated/pyarrow.Array.html#pyarrow.Array.offset) attribute

I don't think this is possible, arrow-rs handles slicing at the granularity of buffers not arrays

> It does make me wonder if we should just remove offset from the Array

IIRC it gets used for BooleanArray
