### ISSUE TITLE
Implement `filter` kernel specially for `FixedSizeByteArray`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#6153]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
We are trying to store UUIDs in arrow Arrays and one obvious thing to do is use `FixedSizeByteArray`

However @samuelcolvin  did some experiments (see https://github.com/apache/datafusion/issues/11170) and found that non obviously using `Decimal128` was actually faster than `FixedSizeByteArray`

One reason for this may be that `FixedSizeByteArray` does not have special case handling in the `filter` kernel 

https://github.com/apache/arrow-rs/blob/f42d2420525a05a9b55461d83b359779ca5cc2a3/arrow-select/src/filter.rs#L320-L383

**Describe the solution you'd like**

1. Add special case code for `FixedSizeByteArray`
2. Add benchmark showing it is faster
3. Add unit tests for functional test coverage

**Describe alternatives you've considered**

**Additional context**
This was pointed out by @samuelcolvin  on  https://github.com/apache/datafusion/issues/11170#issuecomment-2253527396

**Comment by chloro-pn** [comment]
This requirement doesn't seem difficult to implement. If no one is available, please assign it to me. : )

**Comment by alamb** [comment]
Thanks @chloro-pn  - that would be super helpful 🙏

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6186
