### ISSUE TITLE
Support BinaryView Types in C Schema FFI

### ISSUE THREAD

**Issue by a10y** [apache/arrow-rs#6170]
**Describe the bug**

Continuation of #6163 

When attempting to bridge arrow-rs to PyArrow, seeing the following error:

```
E       pyarrow.lib.ArrowException: C Data interface error: The datatype "BinaryView" is still not supported in Rust implementation
```

**Comment by tustvold** [comment]
Marking as a feature request

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6171
