### ISSUE TITLE
Parquet Statistics null_count does not distinguish between `0` and not specified

### ISSUE THREAD

**Issue by jp0317** [apache/arrow-rs#6215]
**Describe the bug**

Please close if this is intended: currently the [null_count](https://github.com/apache/arrow-rs/blob/master/parquet/src/file/statistics.rs#L129-L130) in `Statistics` defaults to 0 and the [has_nulls()](https://github.com/apache/arrow-rs/blob/master/parquet/src/file/statistics.rs#L393) is based on `null_count > 0`, leading to ambiguity when `null_count` equals `0`: either all values are non-null, or just that the null count stat is missing.

**To Reproduce**
n/a

**Expected behavior**

it feels reasonable to distinguish `no null` and `null_count not set`.

**Additional context**
n/a

**Comment by alamb** [comment]
I agree. Perhaps we can make `Statstics::null_count` to return `Option<u64>` instead of `u64`

Maybe we could do it as part of https://github.com/apache/arrow-rs/issues/6093 to use `Option` in general

Thank you for the report @jp0317

**Comment by alamb** [comment]
I didn't even realize that there was already a PR for this: https://github.com/apache/arrow-rs/pull/6216 from @Michael-J-Ward ❤️

**Comment by Michael-J-Ward** [comment]
@alamb I added this change to the #6216.

The tests are green locally and may be ready for merge as is, but I did leave some clarification Q's in my own review of my PR.

**Comment by jp0317** [comment]
thanks @alamb @Michael-J-Ward !

**Comment by jp0317** [comment]
thanks @alamb  @Michael-J-Ward  for changing the `null_count` to `null_count_opt`, but iiuc the ambiguity still exists on  `Some(0)` given the following code

https://github.com/apache/arrow-rs/blob/master/parquet/src/file/statistics.rs#L129-L142

**Comment by alamb** [comment]
> thanks @alamb @Michael-J-Ward for changing the `null_count` to `null_count_opt`, but iiuc the ambiguity still exists on `Some(0)` given the following code??
> 
> https://github.com/apache/arrow-rs/blob/master/parquet/src/file/statistics.rs#L129-L142

You are correct @jp0317  -- we have a PR up that proposes changing this behavior too:  https://github.com/apache/arrow-rs/pull/6257 but I have been worried about unintended consequences of merging it

**Comment by jp0317** [comment]
> > thanks @alamb @Michael-J-Ward for changing the `null_count` to `null_count_opt`, but iiuc the ambiguity still exists on `Some(0)` given the following code??
> > https://github.com/apache/arrow-rs/blob/master/parquet/src/file/statistics.rs#L129-L142
> 
> You are correct @jp0317 -- we have a PR up that proposes changing this behavior too: #6257 but I have been worried about unintended consequences of merging it

Thanks, regarding statistics, do you https://github.com/apache/arrow-rs/discussions/6405 should be a bug?
