### ISSUE TITLE
Support server-side encryption with customer-provided keys (SSE-C)

### ISSUE THREAD

**Issue by jiachengdb** [apache/arrow-rs#6229]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We want to use SSE-C in the object_store library:

https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerSideEncryptionCustomerKeys.html

**Describe the solution you'd like**

Support passing SSE-C related options to the object_store library.

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#6229](https://github.com/apache/arrow-rs/issues/6229)
