### ISSUE TITLE
Port `take` workflow to use `oktokit`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#6242]
Hi, I recommend using [GitHub scripts](https://github.com/actions/github-script) instead of `curl` for easier maintainance.

We can use simple js code here instead:

```js

octokit.rest.issues.addAssignees({
  owner,
  repo,
  issue_number,
  assignees,
});
```

ref: https://octokit.github.io/rest.js/v20#issues

_Originally posted by @Xuanwo in https://github.com/apache/arrow-rs/pull/6059#discussion_r1677710508_

**Comment by dsgibbons** [comment]
take
