### ISSUE TITLE
Implement `date_part` for `Duration`

### ISSUE THREAD

**Issue by nrc** [apache/arrow-rs#6245]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We'd like to be able to use `extract` in DataFusion with `Duration`s in the same way as `Interval`s (see https://github.com/apache/arrow-rs/issues/6113, https://github.com/apache/datafusion/issues/6327)

**Describe the solution you'd like**

Similar to https://github.com/apache/arrow-rs/pull/6071, implement `date_part` for `Interval`s

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6246
