### ISSUE TITLE
Add ParquetObjectReader::with_runtime

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#6248]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Tokio is a cooperative threadpool and has strong assumptions that tasks yield frequently. Running CPU-bound work on the same threadpool results in poor throughput and can lead to connections getting dropped.

**Describe the solution you'd like**

We should add a with_runtime option to ParquetObjectReader that takes a tokio handle and spawns all work to the provided runtime. This encourages decoupling CPU-bound query execution / parquet decoding, from cooperatively scheduled IO.

**Describe alternatives you've considered**

I'm aware of a number of codebases, such as InfluxDB IOx, that implement this spawning logic at the ObjectStore boundary instead.

**Additional context**

https://github.com/apache/arrow-rs/pull/4040 attempted to add something similar to object_store, but concluded this really belongs in the integrations

https://github.com/apache/arrow-rs/issues/5882 may be related to this

**Comment by alamb** [comment]
I believe @wiedld  plans to pick this one up

**Comment by wiedld** [comment]
take

**Comment by itsjunetime** [comment]
take
