### ISSUE TITLE
Release object store `0.11.1` (non breaking API) around Oct 15 2024

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#6263]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Follow on to https://github.com/apache/arrow-rs/issues/6121

object_store `0.11.0` was released Aug 16, 2024

Per release schedule here https://github.com/apache/arrow-rs/tree/master?tab=readme-ov-file#object_store-crate we aim for 
2 months release

We can make a 0.11.1 release earlier if there is demand for features earlier

**Describe the solution you'd like**
- [x] https://github.com/apache/arrow-rs/pull/6566
- [x] Prepare release candidate + begin vote thread: https://lists.apache.org/thread/kkj1whjktwwcr73hyo0d77q124frpwvm
- [ ] Release to crates.io

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
If this is a non-breaking release it would be 0.11.1?

**Comment by alamb** [comment]
> If this is a non-breaking release it would be 0.11.1?

Yes good call -- updated the title

Note that the current stated guideline is "we aim to release new versions every 2 months" https://github.com/apache/arrow-rs?tab=readme-ov-file#object_store-crate

So I don't think we have committed one way or the other to what is in a release 

So per the discussion on https://github.com/apache/arrow-rs/pull/6266 i think it would be possible to release `0.12.0` in October

**Comment by alamb** [comment]
I plan to begin creating the release candidate for this tomorrow (will likely take the opportunity to update the documentation in preparation to maybe pull it into its own release)

**Comment by alamb** [comment]
I am behind on this -- I will work on this later today

**Comment by alamb** [comment]
The vote has begun: https://lists.apache.org/thread/kkj1whjktwwcr73hyo0d77q124frpwvm

**Comment by alamb** [comment]
The release is approved and available on crates.io: https://lists.apache.org/thread/63p3mjxb9l3c76c72ob6rxm7o299rsb6

**Comment by alamb** [comment]
Filed https://github.com/apache/arrow-rs/issues/6596 to track next release
