### ISSUE TITLE
Printing schema metadata includes possibly incorrect compression level

### ISSUE THREAD

**Issue by ttencate** [apache/arrow-rs#6270]
**Describe the bug**
`print_parquet_metadata` always reports ZSTD compression level 1, regardless of the level used when creating the file:
```
compression: ZSTD(ZstdLevel(1))
```
The cause is that the compression level is not actually stored anywhere. The value `1` is just the `Default` of `ZstdLevel`, needed to construct the `Compression` enum.

**To Reproduce**
Call `print_parquet_metadata` on a file using `ZSTD` compression using a non-default level. E.g. I used level 6.

**Expected behavior**
```
compression: ZSTD
```

**Additional context**
Discovered on https://github.com/manojkarthick/pqrs/issues/53.

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #6271
