### ISSUE TITLE
Add direction to `list_with_offset`

### ISSUE THREAD

**Issue by ion-elgreco** [apache/arrow-rs#6274]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
It would be nice if you can provide a direction for the list_with_offset comparison. It's always greater than by default, but smaller than can also be useful in some cases.

I can push a PR for this, if this ok?

**Comment by Xuanwo** [comment]
Hi, could you elaborate a bit on how this could be implemented? Take S3 as an example.

**Comment by ion-elgreco** [comment]
@Xuanwo we can't :P I realized after digging through the code and supported headers that s3 and GCS only has a start-after

**Comment by Xuanwo** [comment]
Yes, services like S3 and GCS only support listing in one order. `list_with_offset` is specially implemented for local file systems since they don't have native `start_after` support.

**Comment by ion-elgreco** [comment]
Do you perhaps know why? I am quite curious why these object store services only implement a one directional listing, as listing in descending order seems quite useful to me

**Comment by ion-elgreco** [comment]
I see, so it could be limitations of the chosen data structures or simply the maintenance overhead of supporting multiple sorting methods.

Thanks for the explanation! :) I'll close this issue then since this beyond our control

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#6274](https://github.com/apache/arrow-rs/issues/6274)
