### ISSUE TITLE
Support writing `UTC adjusted time` arrow array to parquet

### ISSUE THREAD

**Issue by aykut-bozkurt** [apache/arrow-rs#6277]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
To support writing `Time with timezone` array to parquet in a similar way to how we write `Timestamp with timezone`. Currently, `Time` arrays are always converted to parquet with no timezone. (see `fn arrow_to_parquet_type`)

**Describe the solution you'd like**
We can check optional metadata key called `adjusted_to_utc` instead of always filling parquet's `is_adjusted_to_utc` false during the conversion. That would not cause any API change.

**Describe alternatives you've considered**
Add timezone string as second tuple field to `arrow_schema::DataType::Time32` and `arrow_schema::DataType::Time64`. This is how it is done for `Timestamp`, which would cause an API change.

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #6278
