### ISSUE TITLE
PROPOSAL: Mark the `alloc` and `buffer` and `bitmap` crates private

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#629]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
As explained in https://github.com/apache/arrow-rs/pull/628 and linked mailing list comments, the `alloc` and `buffer` and `bitmap` crates are easy to misuse and can create undefined behavior. 

Also, as part of the `arrow2` project @jorgecarleitao  has effectively rewritten / removed them all anyways, so when we make the switch to an `arrow2` based future, any code that relies on these modules needs to be rewritten anyways. 

**Describe the solution you'd like**
Mark the `alloc` and `buffer` and `bitmap` crates private so that users of the crate can not use them and can start preparing for the arrow2 transition

Proposed Transition plan:
1. Add a feature `unsafe` that publicly exposes these modules which is off by default. Users who need backwards compatibility can enable that feature.
2. Release said feature in 6.0.0 
3. in 7.0.0 remove the feature flag

**Comment by paddyhoran** [comment]
Seems like a reasonable way to start to transition to the new arrow2 crate.

**Comment by ritchie46** [comment]
> Add a feature unsafe that publicly exposes these modules which is off by default. Users who need backwards compatibility can enable that feature.

As long as it stays possible to use it I am all for. Polars is dependent on those inner features and accepts the risk, as long as it is obviously properly tagged `unsafe`. :slightly_smiling_face:

**Comment by tustvold** [comment]
These modules are no longer unsound, and so closing. Feel free to re-open if I am mistaken
