### ISSUE TITLE
Add support for Utf8View in arrow_string::length

### ISSUE THREAD

**Issue by Omega359** [apache/arrow-rs#6305]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

This came up as a result of a bug report in DataFusion: https://github.com/apache/datafusion/issues/12149 where `length(StringViewArray)` throws an error.

**Describe the solution you'd like**

The length function has StringViewArray support added and tests added to cover this case.

**Describe alternatives you've considered**

**Additional context**

**Comment by Omega359** [comment]
I suspect a simple implementation would be 
````
DataType::Utf8View => {
            let list = array.as_string_view();
            let v = list.views().iter().map(|v| *v as i32).collect::<Vec<_>>();
            Ok(Arc::new(PrimitiveArray::<Int32Type>::new(v.into(), list.nulls().cloned())))
        }
``` 
however I don't know if that would perform as best as possible.

**Comment by Omega359** [comment]
take

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6345
