### ISSUE TITLE
Invalid `ColumnIndex` written in parquet

### ISSUE THREAD

**Issue by samuelcolvin** [apache/arrow-rs#6310]
See #6295 — we had an issue with `MetadataLoader::load_page_index` panicing, with invalid metadata, which I "fixed" (Err instead of panic).

But since the invalid metadata was written by a very recent version of this crate, I also wanted to work out why invalid metadata was being written in the first place

The problem (as shown in the `test_invalid_column_index` test in #6295) is an invalid `ColumnIndex`, specifically the invalid data looked like this:

```rs
[parquet/src/file/page_index/index_reader.rs:167:5] &index = ColumnIndex {
    null_pages: [
        true,
        true,
        true,
        true,
        true,
        true,
        false,
    ],
    min_values: [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
    ],
    max_values: [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
    ],
    boundary_order: BoundaryOrder(
        1,
    ),
    null_counts: Some(
        [
            10944,
            10240,
            10240,
            10240,
            10240,
            10240,
            7677,
        ],
    ),
    repetition_level_histograms: None,
    definition_level_histograms: Some(
        [
            10944,
            0,
            10240,
            0,
            10240,
            0,
            10240,
            0,
            10240,
            0,
            10240,
            0,
            7677,
            30,
        ],
    ),
}
```

Note that the list item in `null_pages` is `false`, but all values in `min_values` and `max_values` are empty, that causes the `Err` from:

https://github.com/apache/arrow-rs/blob/ee2f75a66278dbd3e7aa6b85b5322951c792a58d/parquet/src/file/page_index/index.rs#L204-L211

`is_null` is false, so `from_le_slice::<T>(min)` (and `max`) are called, 4 bytes are expected since `T` is `i32`, but the vec is empty.

I've tried in vane to work out where the code its that's writing that data.

cc @adriangb @alamb.

**Comment by etseidl** [comment]
I think the relevant code is https://github.com/apache/arrow-rs/blob/ee2f75a66278dbd3e7aa6b85b5322951c792a58d/parquet/src/column/writer/mod.rs#L752-L779. 

For the final page (with 30 values), `null_page` should be false, and we should wind up at https://github.com/apache/arrow-rs/blob/ee2f75a66278dbd3e7aa6b85b5322951c792a58d/parquet/src/column/writer/mod.rs#L811-L816

The chunk statistics look ok (min 1, max 1), so you'd think the page stats would similarly be ok. They are created here
https://github.com/apache/arrow-rs/blob/ee2f75a66278dbd3e7aa6b85b5322951c792a58d/parquet/src/column/writer/mod.rs#L889-L902

Again, if the min/max were invalid in the page, then you'd expect garbage in the chunk stats.  Perhaps some print statements or breakpoints would help here.

If the original file isn't sensitive could you share it here? 

cc @adriangb

**Comment by samuelcolvin** [comment]
Thanks @etseidl, my guess is that the problem comes because either `num_buffered_rows` or `num_page_nulls` is wrong in in the last page, hence

```rs
        let null_page =
            (self.page_metrics.num_buffered_rows as u64) == self.page_metrics.num_page_nulls;
```

wrongly makes `null_page` false when it should be true.

The parquet file doesn't seem to have anything particularly sensitive in it, but I wouldn't be happy sharing it on github, happy to email it to you if you're interested.

**Comment by alamb** [comment]
I am sorry I am mostly on vacation this week so I haven't been following along as much as normal.

This sounds to me like a bug that was introduced in https://github.com/apache/arrow-rs/pull/6105 but has not yet been released.  Given that I think it means we should hold 53.0.0 (https://github.com/apache/arrow-rs/issues/6016) until we fixed this issue

@etseidl  is this something you can look into? It seems like https://github.com/apache/arrow-rs/issues/6315 is tracking a somewhat different issue

**Comment by etseidl** [comment]
> @etseidl is this something you can look into? It seems like #6315 is tracking a somewhat different issue

I worked offline with @samuelcolvin and @adriangb and identified a potential fix. Hopefully a PR will be coming soon.

**Comment by alamb** [comment]
> > @etseidl is this something you can look into? It seems like #6315 is tracking a somewhat different issue
> 
> I worked offline with @samuelcolvin and @adriangb and identified a potential fix. Hopefully a PR will be coming soon.

Thank you everyone -- https://github.com/apache/arrow-rs/pull/6319 is queued up and I plan to merge it shortly

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #6319
