### ISSUE TITLE
Allow converting empty `pyarrow.RecordBatch` to `arrow::RecordBatch`

### ISSUE THREAD

**Issue by Michael-J-Ward** [apache/arrow-rs#6318]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
`datafusion-python` currently errors when calling `select count(*) from t` when `t` is a `pyarrow.Dataset`.

The resulting `pyarrow.RecordBatch` contains no rows and has a schema with no columns, but it does have `num_rows` set to the correct number.

**Describe the solution you'd like**
Support was added to arrow-rs in https://github.com/apache/arrow-rs/pull/1552 for a `RecordBatch` with zero columns but non zero row count. 

I'd like `impl FromPyArrow for RecordBatch` to use this functionality. 

https://github.com/apache/arrow-rs/blob/b711f23a136e0b094a70a4aafb020d4bb9f60619/arrow/src/pyarrow.rs#L334-L392

**Additional Context**

datafusion-python issue: https://github.com/apache/datafusion-python/issues/800

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6320
