### ISSUE TITLE
Azure SAS tokens are visible when retry errors are logged via object_store

### ISSUE THREAD

**Issue by alexwilcoxson-rel** [apache/arrow-rs#6322]
**Describe the bug**
object_store retry module will info log retryable errors. When using SASToken as the azure credential this results in the SAS token ending up in logs.

**To Reproduce**
Use azure sas token and trigger a retry with logging enabled

**Expected behavior**
URL when using SAS token is replaced with sensitive

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'object-store'} from #6323

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#6322](https://github.com/apache/arrow-rs/issues/6322)
