### ISSUE TITLE
Better Document Backoff Algorithm

### ISSUE THREAD

**Issue by westonpace** [apache/arrow-rs#6324]
**Describe the bug**

In `object_store::BackoffConfig` we have:

```
Exponential backoff with jitter

See https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/
```

However, the actual implementation is "decorrelated jitter" (which is not exponential).

**To Reproduce**
N/A docs bug

**Expected behavior**
Docs describe implementation

**Additional context**
N/A

**Comment by tustvold** [comment]
It is still exponential backoff, in that it multiples the last delay by some base? The linked docs also describe it thus?

**Comment by westonpace** [comment]
Sort of...it's kind of "exponential with restarts" in the sense that it can always randomly jump back to a very small value:

![image](https://github.com/user-attachments/assets/e41dd714-11bc-4645-9fc0-18566d127d56)

It can also just randomly choose not to grow at all (e.g. 70-80 in the chart).  I think my problem is that both "exponential backoff" and "exponential backoff with jitter" are well known approaches (they've been around since before AWS) and if anyone sees "exponential backoff" they aren't going to bother to read the linked document.

Also, the linked document treats exponential backoff as an algorithm of its own.  E.g. it has its own bar in the legend:

![image](https://github.com/user-attachments/assets/57b60fe7-e150-4149-895b-68e8d8b8c8cf)

**Comment by tustvold** [comment]
I take your point, however, it is a jittered exponential backoff, i.e. the base is exponential backoff which is then jittered. This is reflected both in the wording of the linked doc, and the naming in the various AWS codebases, e.g. - https://github.com/aws-samples/aws-arch-backoff-simulator/blob/master/src/backoff_simulator.py#L40

The backoff growth is still non-linear, and this is important to convey IMO

**Comment by westonpace** [comment]
I disagree (chart included), but I don't really want to fight the point.  As long as the actual process is clearly documented readers should figure it out.  I've accepted your PR suggestion.

![image](https://github.com/user-attachments/assets/23442e68-6d53-45ab-b749-a7fae98a9f39)

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#6324](https://github.com/apache/arrow-rs/issues/6324)
