### ISSUE TITLE
Add Catalog DB Schema subcommands to `flight_sql_client`

### ISSUE THREAD

**Issue by nathanielc** [apache/arrow-rs#6331]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

When using the `flight_sql_client` it can be helpful to interrogate the Flight SQL server for information about available catalogs, db schemas and tables. 

**Describe the solution you'd like**
Adding subcommands to the CLI that mirror the various FlightSQL commands about catalogs, schemas and tables.

**Describe alternatives you've considered**
 We could support `SHOW ...` variant queries and map them to the FlightSQL commands, however this is likely not as portable as a direct mapping of CLI subcommand to FlightSQL command.

**Additional context**

I have PR in progress.

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6332

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow-flight'} from #6332
