### ISSUE TITLE
Different numeric type may be able to compare

### ISSUE THREAD

**Issue by tisonkun** [apache/arrow-rs#6357]
https://github.com/apache/arrow-rs/blob/6bf2bda568d4da48d4e4d199b96def7f717eff37/arrow-ord/src/cmp.rs#L239-L243

Crates like [num-cmp](https://github.com/lifthrasiir/num-cmp/) shows that different numeric type (e.g., u64 and i64) is comparable.

Is it possible to extend arrow array comparison to support compare these two kind of datum?

**Comment by tustvold** [comment]
The major difficulty here is combinatorial explosion of code generation that would result, something that is already a major issue.

Instead what most query engines, such as DataFusion do, is use the cast kernels to coerce the inputs to a common type before performing the comparison.

**Comment by alamb** [comment]
It is also fairly straightforward to implement your own kernels for specific comparisons if you have special cases that are not handled by arrow-rs (the challenge is mananging the code complexity for all the possible type combinations, as alluded to above by @tustvold )

**Comment by ByteBaker** [comment]
@alamb @tustvold based on the discussion, should this be closed as not planned?

**Comment by alamb** [comment]
I agree -- thanks for the ping @ByteBaker 

I recommend users who want to native kernels for comparing different data types is to use existing functions such as https://docs.rs/arrow/latest/arrow/compute/fn.binary.html  to generate the combinations they need for their application

**Comment by tisonkun** [comment]
> https://docs.rs/arrow/latest/arrow/compute/fn.binary.html

This is helpful. Thank you!

**Comment by tisonkun** [comment]
@alamb I use binary to implement num_cmp between int and uint successfully.

But when trying to implement distinct/not_distinct, I notice that `binary` hide the processing of nulls but just union nulls in both operands. It is possible or is there already a `binary_nullable` which accept an `op: F` where `F: F: Fn(Option<A::Native>, Option<B::Native>) -> Option<O::Native>`?

**Comment by tustvold** [comment]
If you don't care about performance you could just use the iterators, however, processing the null masks per value is very innefficient.

If you want to make this fast I recommend looking at how this is implemented in arrow-ord
