### ISSUE TITLE
Add support for BinaryView in arrow_string::length

### ISSUE THREAD

**Issue by Omega359** [apache/arrow-rs#6358]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Add support for binary view in the length fn. This was brought up in a code review in #6345

**Describe the solution you'd like**

Code, tests added for calculating length for binary view.

**Describe alternatives you've considered**

Do not implement.

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6345
