### ISSUE TITLE
Primitive `binary`/`unary` are not as fast as they could be

### ISSUE THREAD

**Issue by AdamGS** [apache/arrow-rs#6364]
While implementing on spiraldb/vortex#726 Implementing our own version of `unary/binary`, I realized that operating on fixed-sized slices yields much better performance (at least on my machine).

**Comment by AdamGS** [comment]
Code had a bug, tests passed because the case wasn't covered (arrays with more than 1024 elements)

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6365
