### ISSUE TITLE
Exporting Binary/Utf8View from arrow-rs to pyarrow fails

### ISSUE THREAD

**Issue by robert3005** [apache/arrow-rs#6366]
**Describe the bug**
Exporting binaryview arrow to pyarrow fails with 

`Expected at least 3 buffers for imported type binary_view, ArrowArray struct has 2`

**To Reproduce**
Construct binaryview array and export it over c data interface to pyarrow 

**Expected behavior**
Export should succeed without error

**Additional context**
I think there's ambiguity in the spec https://github.com/apache/arrow/issues/43989. However, regardless of that issue it seems that export binaryview array has to do a bit extra work to produce buffer lengths

**Comment by a10y** [comment]
```
>>> pa.array(["a"], type=pa.string_view()).buffers()
[None, <pyarrow.Buffer address=0x31dec030180 size=16 is_cpu=True is_mutable=True>, <pyarrow.Buffer address=0x1121c2b40 size=0 is_cpu=True is_mutable=True>]
```

The failure seems to be happening within the C++ code here:
https://github.com/apache/arrow/blob/ab0a40ee34217070f14027776682074c55d0b507/cpp/src/arrow/c/bridge.cc#L1739-L1760


Digging in a bit more, it looks like the buffer in slot 0 is for validity, and for some reason is not being populated when StringViewArray is being passed back to Python

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6368
