### ISSUE TITLE
`compute::binary_mut` returns `Err(PrimitiveArray<T>)` only with certain arrays

### ISSUE THREAD

**Issue by MaxenceMaire** [apache/arrow-rs#6374]
**Describe the bug**
[`compute::binary_mut`](https://docs.rs/arrow/latest/arrow/compute/fn.binary_mut.html) returns `Err(PrimitiveArray<T>)` in cases when the underlying buffer is not shared (as described in [the documentation](https://docs.rs/arrow/latest/arrow/compute/fn.binary_mut.html#buffer-reuse)). It only happens when passing certain arrays.

**To Reproduce**

- Err case:
```
let a = Int32Array::from(vec![
    Some(3),
    Some(4),
    Some(5),
    Some(6),
    None,
]);

let b = Int32Array::from(vec![
    Some(10),
    Some(11),
    Some(12),
    Some(13),
    Some(14),
]);

let a = binary_mut(a, &b, |a, b| a + b);
```
produces
```
Err(PrimitiveArray<Int32>
[
  3,
  4,
  5,
  6,
  null,
])
```
- Ok case:
```
let a = Int32Array::from(vec![
    Some(3),
    Some(4),
    Some(5),
    Some(6),
    None,
]);

let b = Int32Array::from(vec![
    Some(10),
    Some(11),
    None,
    Some(13),
    Some(14),
]);

let a = binary_mut(a, &b, |a, b| a + b);
```
produces
```
Ok(Ok(PrimitiveArray<Int32>
[
  13,
  15,
  null,
  19,
  null,
]))
```

**Expected behavior**
I would have expected the first case to produce
```
Ok(Ok(PrimitiveArray<Int32>
[
  13,
  15,
  17,
  19,
  null,
]))
```

**Additional context**

<details>
<summary>Additional cases</summary>

- Err case:

```
let a = Int32Array::from(vec![
    Some(3),
    Some(4),
    Some(5),
    Some(6),
    None,
    Some(8)
]);

let b = Int32Array::from(vec![
    Some(10),
    Some(11),
    Some(12),
    Some(13),
    Some(14),
    Some(15),
]);

let a = binary_mut(a, &b, |a, b| a + b);
```
produces
```
Err(PrimitiveArray<Int32>
[
  3,
  4,
  5,
  6,
  null,
  8,
])
```
- Ok case:
```
let a = Int32Array::from(vec![
    Some(3),
    Some(4),
    Some(5),
    Some(6),
    None,
    Some(8)
]);

let b = Int32Array::from(vec![
    Some(10),
    Some(11),
    Some(12),
    Some(13),
    Some(14),
    None,
]);

let a = binary_mut(a, &b, |a, b| a + b);
```
produces
```
Ok(Ok(PrimitiveArray<Int32>
[
  13,
  15,
  17,
  19,
  null,
  null,
]))
```
</details>

The errors seem to be associated with an uneven number of null values.

**Comment by MaxenceMaire** [comment]
Note that I get the expected result when constructing the array with a separate null buffer:

```
let a = Int32Array::new(
    vec![3, 4, 5, 6, 7].into(),
    Some(vec![true, true, true, true, false].into()),
);

let b = Int32Array::new(
    vec![10, 11, 12, 13, 14].into(),
    Some(vec![true, true, true, true, true].into()),
);

let a = binary_mut(a, &b, |a, b| a + b);
```

produces:

```
Ok(Ok(PrimitiveArray<Int32>
[
  13,
  15,
  17,
  19,
  null,
]))
```

Unfortunately I haven't had time to dig deeper into it yet, but it would seem to indicate that the null buffer references the scalar buffer when using [the `From<Vec<Option<T>>>` trait](https://docs.rs/arrow/latest/arrow/array/type.Int32Array.html#impl-From%3CVec%3COption%3C%3CInt32Type+as+ArrowPrimitiveType%3E::Native%3E%3E%3E-for-PrimitiveArray%3CInt32Type%3E) to construct the array, which in turns causes the shared buffer error on `binary_mut`?

**Comment by alamb** [comment]
this sounds like a good find. Perhaps @viirya  has some thoughts / ideas on this (as I think Comet uses binary_mut a lot)

**Comment by viirya** [comment]
Looking into this.

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6396
