### ISSUE TITLE
LocalFileSystem `list` operation returns objects in wrong order

### ISSUE THREAD

**Issue by paraseba** [apache/arrow-rs#6375]
**Describe the bug**
The `LocalFileSystem` `list` implementation returns objects in what looks like arbitrary order.

S3's `ListObjectsV2` returns objects in lexicographical order of their keys:
> General purpose bucket - For general purpose buckets, ListObjectsV2 returns objects in lexicographical order based on their key names.

**To Reproduce**
The following code fails the assertion:

```rust
use futures::TryStreamExt;
use object_store::{local::LocalFileSystem, ObjectStore, PutPayload};
use std::assert_eq;
use std::fs::create_dir_all;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let dir = "/tmp/reproducer";
    create_dir_all(dir)?;

    let store = LocalFileSystem::new_with_prefix(dir)?;
    for i in 0..=9 {
        store.put(&(i.to_string()).into(), PutPayload::from_static(b"42")).await?;
    }

    let actual = store
        .list(None)
        .map_ok(|om| om.location.to_string())
        .try_collect::<Vec<_>>()
        .await?;

    let expected = (0..=9).map(|s| s.to_string()).collect::<Vec<_>>();
    assert_eq!(actual, expected);
    Ok(())
}

```
**Expected behavior**
`LocalFileSystem` should mimic what `ListObjectsV2` does, returning objects in lexicographical order of their keys.

**Additional context**
`InMemory` doesn't fail this test.

**Comment by Xuanwo** [comment]
> `LocalFileSystem` should mimic what `ListObjectsV2` does, returning objects in lexicographical order of their keys.

Hi, this behavior is expected. We can't perform sorting over the LocalFileSystem since we don't have such an API, and we can't collect keys and sort them in-memory. The best we can do is return objects in the order that the filesystem provides.

**Comment by paraseba** [comment]
@Xuanwo I see. Would it make sense to have sorting behavior as optional? Intended only for small stores that fin in memory? `walkdir` library has the option to do that. Otherwise, is the listing behavior documented somewhere? I'm not sure what level of "compatibility" the different stores implementations try to achieve.

**Comment by alamb** [comment]
Another potential option is to implement your own wrapper over `LocalFileSystem` that sorted the results by file name

like
```rust
struct SortedLocalFileSystem {
  inner: LocalFileSystem 
}

impl ObjectStore for SortedLocalFileSystem {
  // in the implementation you could intercept the various calls and implement 
  // whatever behavior you wanted
}
```

**Comment by Xuanwo** [comment]
> Would it make sense to have sorting behavior as optional?

Sorry, but it doesn't make sense to me now. If you care about the order, you can implement something like what @alamb mentioned, which should be simple.

>  Intended only for small stores that fin in memory?

The most interesting part is this: we don't know how many items there are until we list them all. This inconsistent behavior based on item size might introduce more issues. For example, users might find the object_store behaves one way when there are only 10 items, but differently in production services.


> I'm not sure what level of "compatibility" the different stores implementations try to achieve.

https://github.com/apache/arrow-rs/blob/7a5155c5f0e21559203d4a5363cffd7ec0394817/object_store/src/lib.rs#L721C1-L721C69

No guarantee has been provided so far.

**Comment by paraseba** [comment]
Thanks for the quick responses. Closing this.
