### ISSUE TITLE
Add union_extract kernel

### ISSUE THREAD

**Issue by gstvg** [apache/arrow-rs#6386]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Retrieve the value of the given union variant, or NULL if it's not currently selected
This is will be used at https://github.com/apache/datafusion/issues/11081

**Describe the solution you'd like**

A kernel in `arrow_select` with the following signature:
 `fn union_extract(union_array: &UnionArray, field: &str) -> Result<ArrayRef>`

**Describe alternatives you've considered**

Implement this in datafusion, but after comments from @samuelcolvin and @alamb at https://github.com/apache/arrow-rs/issues/6247#issuecomment-2307370777 and https://github.com/apache/arrow-rs/issues/6247#issuecomment-2307418058, I decided to do here

**Additional context**

**Comment by alamb** [comment]
I think this is needed for https://github.com/datafusion-contrib/datafusion-functions-json

I will put it on my review queue

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6387
