### ISSUE TITLE
Bump lexical-core to 1.0

### ISSUE THREAD

**Issue by Jefffrey** [apache/arrow-rs#6397]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

`lexical-core` is currently being used for JSON, CSV and cast:

https://github.com/apache/arrow-rs/blob/ba85fa3bc68fd6fdc2b401adcf5eddb9f482b7c9/arrow-json/Cargo.toml#L48

https://github.com/apache/arrow-rs/blob/ba85fa3bc68fd6fdc2b401adcf5eddb9f482b7c9/arrow-csv/Cargo.toml#L46

https://github.com/apache/arrow-rs/blob/ba85fa3bc68fd6fdc2b401adcf5eddb9f482b7c9/arrow-cast/Cargo.toml#L52

A `1.0.0` release is out now, which fixes some soundness issues.

According to [the reddit post](https://www.reddit.com/r/rust/comments/1fgyopo/lexicalcore_version_100_released_major_security/
), pre `1.0.0` versions will be yanked soon.

**Describe the solution you'd like**

Bump to `lexical-core=1.0.0`

**Describe alternatives you've considered**

**Additional context**

#5422 may become redundant

We also switched to `atoi` in this PR for arrow-cast: https://github.com/apache/arrow-rs/pull/5398. Could see if it's worth switching back to lexical-core, if can confirm the correctness issues are resolved and if performance might benefit (otherwise can stay as is).

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6402

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'auto-dependencies'} from #6401
