### ISSUE TITLE
Release candidate verifying script seems work on macOS

### ISSUE THREAD

**Issue by waynexia** [apache/arrow-rs#640]
**Describe the bug**
In this [document](https://github.com/apache/arrow-rs/blob/master/dev/README.md#verifying-release-candidates) it says
> Currently this only works on Linux (patches to expand to macOS welcome!).

I think this document might be outdated? I can run the script on macOS (Intel chip, Catalina). Or there is some other environment that can't run it.

**To Reproduce**
n/a

**Expected behavior**
n/a

**Additional context**
BTW, I'm wondering whether this issue can be tagged as `Bug`. Maybe we need another type like "Question" or something like that?

**Comment by alamb** [comment]
@waynexia   i also run the verification script on mac without issue I think the comment is outdated

**Comment by alamb** [comment]
FWIW the question label already exists (I added it to this issue). It isn't clear to me if everyone can add labels to issues in arrow-rs. Does it work for you @waynexia ?

Perhaps we could add a template for a "question" to make it easier for people to file such questions: https://github.com/apache/arrow-rs/tree/master/.github/ISSUE_TEMPLATE

**Comment by waynexia** [comment]
Thanks @alamb!

I cannot edit labels. It seems like this operation requires write permission to this repo or something.

I opened #649 to add the "question" template, please check it out :smiley:
