### ISSUE TITLE
`downcast_primitive_array` and `downcast_dictionary_array` are not hygienic wrt imports

### ISSUE THREAD

**Issue by davidhewitt** [apache/arrow-rs#6400]
**Describe the bug**

Using `downcast_primitive_array` and `downcast_dictionary_array` require `arrow_schema` to be in scope of the expanded code.

**To Reproduce**

1. use `arrow::downcast_primitive_array` without `arrow_schema` included as a direct dependency
2. failure to compile due to expanded code using paths from `arrow_schema`

**Expected behavior**

Compile should succeed.

**Additional context**

A workaround is to manually insert something which roughly matches `arrow_schema` into the namespace, e.g.

```rust
    use datafusion::arrow::datatypes as arrow_schema;  // using datafusion facade
    downcast_primitive_array!( ... ); // ^ will now use the above-defined arrow_schema
```

**Comment by tustvold** [comment]
This isn't a bug, it's inherent to the nature of macros and the limitations thereof. I'm not aware of any way to avoid this

**Comment by alamb** [comment]
In general, I think most/many users use the `arrow` crate (not one of the subcrates) and therefore I believe anything we can do to make that usage easier (e.g. re-exporting things from the subcrates / improving macros, etc) is valuable overall

I don't think we should prevent / make it harder for people to use the subcrates (doing so reduces the dependency burden on downstream projects) but I think it has a higher barrier to entry. I think it is important to make it as easy as possible for people to start using arrow and then if they find it useful they can spend time to optimize their usage more

**Comment by tustvold** [comment]
I wonder if we could create a meta-macro that generates the downcast_primitive_array macro, this would avoid duplication, and allow redefining the downcast macro when re-exporting :thinking:

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6620
