### ISSUE TITLE
Invalid struct arrays in IPC data causes panic during read

### ISSUE THREAD

**Issue by alexwilcoxson-rel** [apache/arrow-rs#6416]
**Describe the bug**
We're using Arrow Flight with a dotnet client. One of our client applications accidentally was sending StructArray's with different length child arrays. Not sure why the dotnet side batch building didn't catch it, but on the flight decode in IPC there is a panic. This causes the request task to die and the response to the flight client to be not helpful.

```
thread 'general' panicked at /.../arrow-array-52.2.0/src/array/struct_array.rs:90:46:
called `Result::unwrap()` on an `Err` value: InvalidArgumentError("Incorrect array length for StructArray field \"field\", expected 2 got 1")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
libunwind: stepWithCompactEncoding - invalid compact unwind encoding
```

**To Reproduce**
Create IPC data with different length child arrays in a struct. Attempt to read that data.

**Expected behavior**
Error is returned without panicing.

**Additional context**
n/a

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6417
