### ISSUE TITLE
Add a method to return the number of skipped rows in a `RowSelection`

### ISSUE THREAD

**Issue by progval** [apache/arrow-rs#6428]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

`RowSelection` has a `row_count` method that returns the number of selected rows, but is missing a way to count the number of de-selected rows without iterating on the selectors

**Describe the solution you'd like**

Implement it as `RowSelection::skipped_row_count`

**Describe alternatives you've considered**

current state, which is that users have to reimplement it themselves

**Additional context**

Datafusion had to implement it here:

https://github.com/apache/datafusion/blob/f2159e6cae658a0a3f561ec2d15ea948213fd0f8/datafusion/core/src/datasource/physical_plan/parquet/page_filter.rs#L271-L277

Suggested by @alamb here: https://github.com/apache/datafusion/pull/12545#discussion_r1768748882

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #6429
