### ISSUE TITLE
Should `FileMetadata::num_rows` return `u64`?

### ISSUE THREAD

**Issue by ByteBaker** [apache/arrow-rs#6435]
**Which part is this question about**
The method `parquet::file::metadata::FileMetaData::num_rows` returns `i64`. But intuitively, this would never be negative and should be unsigned through and through.

Oddly enough [the spec](https://parquet.apache.org/docs/file-format/metadata/) also uses `i64` which seems wrong. This is also for other values such as `num_children`. Even the [thrift definition](https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift) is using signed types.

Is this something fundamentally wrong, and should be changed everywhere, or is there a rationale to this that I'm missing?

**Comment by tustvold** [comment]
Java historically had limited support for unsigned 64-bit integers. Consequently many specifications, such as parquet and arrow, avoid using them

**Comment by ByteBaker** [comment]
So are we trying to remain compatible with Java here? Because unless that's the case, I think we should move towards unsigned numbers.

Also, IMHO any compatibility on this should be implemented in Java APIs, and not the other way around. This would standardize things everywhere, and Java caveat can be dealt on a use-case basis. What are your thoughts?

**Comment by etseidl** [comment]
We're trying to remain compatible with the Parquet spec. The specification is (currently) expressed in Thrift, and Thrift has no unsigned integer support.

**Comment by ByteBaker** [comment]
Noted. I'm closing this.
