### ISSUE TITLE
Failing CI: Prost requires Rust 1.71.1

### ISSUE THREAD

**Issue by gstvg** [apache/arrow-rs#6436]
**Describe the bug**

Prost bumped it's MSRV from 1.70 to 1.71.1 on it's [v0.13.3 release ](https://github.com/tokio-rs/prost/releases/tag/v0.13.3)
This clashes with arrow-flight MSRV 1.70, causing [CI errors](https://github.com/apache/arrow-rs/actions/runs/10984024899/job/30494124939?pr=6387#step:9:18)

**Additional info**

The 1.70 MSRV was set on https://github.com/apache/arrow-rs/pull/4490, on Jul 8, 2023, more than one year ago
[Rust 1.70 was released on 1 June, 2023](https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html), while [1.71.1 on 3 August, 2023](https://blog.rust-lang.org/2023/08/03/Rust-1.71.1.html):  ~2 months of difference

I think we can safely bump arrow-flight MSRV from 1.70 to 1.71.1, otherwise pin prost to v0.13.2.

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6437

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow-flight'} from #6437

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'documentation'} from #6434
