### ISSUE TITLE
List equality doesn't match the C data interface spec

### ISSUE THREAD

**Issue by joseph-isaacs** [apache/arrow-rs#6467]
**Describe the bug**

Two lists should be equal, irrespective of this field name, which is an implementation detail.
In the arrow [C data interface spec](https://arrow.apache.org/docs/format/CDataInterface.html), the list data type format string is defined excluding names from list types, however arrow-rs defines a them as `List(FieldRef)` and defines equality structurally (using `derive(PartialEq)`)

**To Reproduce**

```rust
let arr = make_array(ArrayData::new_null(
    &DataType::List(Arc::new(Field::new("abc", DataType::Int32, true))),
    1,
));
let schema = Arc::new(Schema::new(vec![Field::new(
    "l",
    DataType::List(Arc::new(Field::new_list_field(DataType::Int32, true))),
    false,
)]));

let rb = RecordBatch::try_new(schema, vec![arr]);
assert!(rb.is_ok())
```
The error is 
```
Err(InvalidArgumentError("column types must match schema types, expected List(Field { name: \"item\", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }) but found List(Field { name: \"abc\", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }) at column index 0"))
```

**Expected behaviour**

I expect that these two schemas `s1` and `s2` should be equal see the C ABI schema [here](https://arrow.apache.org/docs/format/CDataInterface.html#examples), "A list<uint64> array has format string `+l`, and its single child has format string `L.`" and therefore the above test should pass.

**Additional context**

This has caused a problem when writing a parquet file using pyarrow and reading it using arrow-rs.

I end up with these two fields one on the array and the the other on the schema.
```
Field { name: "column_ids", data_type: List(Field { name: "item", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} })
Field { name: "column_ids", data_type: List(Field { name: "element", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} })
```
Which when I pass into `RecordBatch::try_new()` there is a failure.

**Comment by joseph-isaacs** [comment]
One solution this might would be to defined equality manually over `DataType`.

**Comment by tustvold** [comment]
Two lists should be equal regardless of field name correct, but this does not mean the schemas should compare equal. The approach taken by this crate is that metadata is part of equality, as this is the safe-by-default option. There are methods where users can opt-in to looser comparison, e.g. equals_datatype, where this is acceptable for that use-case

**Comment by joseph-isaacs** [comment]
Thanks for the explanation it does look like I did a silly, I got caught out, `use_compliant_nested_type` from arrow-c++ [see](https://arrow.apache.org/docs/python/generated/pyarrow.parquet.write_table.html).

**Comment by tustvold** [comment]
> it does look like I did a silly

No worries at all, this is a rather confusing edge of the specification that trips up lots of people
