### ISSUE TITLE
Object Store: Azure access using DefaultAzureCredential possible?

### ISSUE THREAD

**Issue by francesco086** [apache/arrow-rs#6470]
**Which part is this question about**
[object_store](https://docs.rs/object_store/latest/object_store/index.html)::[azure](https://docs.rs/object_store/latest/object_store/azure/index.html)::[AzureConfigKey](https://docs.rs/object_store/latest/object_store/azure/enum.AzureConfigKey.html#)

**Describe your question**
Coming from systems that use [adlfs](https://github.com/fsspec/adlfs), it has always been possible to use "Auto credential solving using Azure's DefaultAzureCredential()", by setting in the storage options `anon=False`.
I could not find an equivalent in AzureConfigKey. Is there a way to achieve the same?

**Additional context**
I am trying to use polars and raised this question in polars already: https://github.com/pola-rs/polars/issues/18931.
Notice that [a workaround](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-user-delegation-sas-create-python?tabs=container) has been suggested, but it's quite cumbersome, so I am checking if there is a simpler way that perhaps I could not see.

**Comment by francesco086** [comment]
Thanks for your answer @tustvold !
Right, I just checked and on an Azure VM it works as you described. 

But what about my local machine where I did a simple `az login`? Is there a way to make it source the credentials from the azure account I am logged in with in my session?

**Comment by tustvold** [comment]
Perhaps https://docs.rs/object_store/latest/object_store/azure/struct.MicrosoftAzureBuilder.html#method.with_use_azure_cli ?

https://docs.rs/object_store/latest/object_store/azure/enum.AzureConfigKey.html#variant.UseAzureCli

**Comment by francesco086** [comment]
That works in the `az login` scenario from my laptop, thanks @tustvold !

So, basically what is missing is support for [`DefaultAzureCredential`](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet), that would automatically resolve between the two (and more).

Do you know if there is a deep reason for this, or it could make sense to raise a feature request to add support for this very handy option?

**Comment by tustvold** [comment]
DefaultAzureCredential is a feature of the .NET SDK, trying to mirror all the authentication options the various cloud providers have in their various SDKs is out of scope for this crate.

**Comment by francesco086** [comment]
Thanks for the explanation!
