### ISSUE TITLE
Remove reliance on `raw-entry` feature of Hashbrown

### ISSUE THREAD

**Issue by Jefffrey** [apache/arrow-rs#6498]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

When upgrading to hashbrown `v0.15.0`: https://github.com/apache/arrow-rs/pull/6493

Changelog notes:

> Raw entry API is now under `raw-entry` feature, to be eventually removed

https://github.com/rust-lang/hashbrown/blob/master/CHANGELOG.md#v0150---2024-10-01

**Describe the solution you'd like**

Remove reliance on this feature so future upgrades to hashbrown versions will be smooth

https://github.com/apache/arrow-rs/blob/581c6470d36b12c5234555b5094ab6816044007a/parquet/src/util/interner.rs#L19

https://github.com/apache/arrow-rs/blob/581c6470d36b12c5234555b5094ab6816044007a/arrow-array/src/builder/generic_bytes_dictionary_builder.rs#L23

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #6537

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6537

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow-flight'} from #6493
