### ISSUE TITLE
Handle UnionArray in get_fb_field_type

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#65]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-8546

None

**Comment by Jefffrey** [comment]
Resolved by #1135

(Btw @alamb or @tustvold, is there a particular preference to how to close these old issues that were already resolved, if it makes a difference to how changelog is generated for releases? Completed vs not planned?)

**Comment by tustvold** [comment]
I suppose you could put the development process label on them, so they're excluded, but I haven't been doing so

**Comment by alamb** [comment]
I added the label for now -- I agree it would be nice to exclude them from the changelog, but also it isnt' the end of the world if they are in there too
