### ISSUE TITLE
How to determine when a client disconnects

### ISSUE THREAD

**Issue by cisaacson** [apache/arrow-rs#6509]
**Which part is this question about**
`arrow-flight-sql`, but it could apply to `arrow-flight` as well

**Describe your question**
I do not see anything in the `arrow-flight-sql` protocol to determine when a client has disconnected. We need this to be able to reliably close a server side session.

If there is a way to do this please let me know.

**Comment by tustvold** [comment]
gRPC, on which flight is built, is a request oriented protocol, not a connection oriented protocol. If you want a notion of a session that spans multiple requests, you will need to implement this on top, e.g. using some sort of session token.

**Comment by cisaacson** [comment]
Thanks @tustvold, this is helpful. We will investigate how to implement this. We are using the provided auth token mechanism, that could be the session token. We already store the open sessions, so the only thing missing is when a client closes its connection or disconnects. Do you have any advice on how to implement that?

**Comment by tustvold** [comment]
Timeouts would be the most common approach

**Comment by tustvold** [comment]
Closing as the question has been answered
