### ISSUE TITLE
Enable unreachable_pub in object_store

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#6511]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The `object_store` crate has a large amount of implementation details that are marked public, but are kept crate-private by being part of a crate-private module.

When reviewing a PR it can be hard to reason about what is/isn't public, and therefore what is/isn't a breaking change.

It also runs a greater risk of implementation details accidentally being exposed during a refactor.

**Describe the solution you'd like**

I would like to enable the `unreachable_pub` lint and update the relevant sites with `pub(crate)`

**Describe alternatives you've considered**

**Additional context**

**Comment by ByteBaker** [comment]
take

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'object-store'} from #6512

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#6511](https://github.com/apache/arrow-rs/issues/6511)
