### ISSUE TITLE
Missing tonic `GRPC_STATUS`

### ISSUE THREAD

**Issue by cisaacson** [apache/arrow-rs#6515]
The current master does not compile, it is missing this status:

```
no associated item named `GRPC_STATUS` found for struct `Status` in the current scope
    --> arrow-flight/src/arrow.flight.protocol.rs:1578:48
```

Changing the version of `prost` in `arrow-flight/Cargo.toml` to the following fixes this:

```
tonic = { version = "0.12.3", default-features = false, features = ["transport", "codegen", "prost"] }
```
The current version of tonic is "0.12.1"

**Comment by tustvold** [comment]
I suspect your local checkout has a lockfile that is pinning the version to the old version, we should uodate the dependency though if we're depending on something added in a newer patch release

**Comment by cisaacson** [comment]
@tustvold I did update to the latest code and the issue still exists. This patch allows it to compile for me now. Let me know what you think.

**Comment by tustvold** [comment]
> I did update to the latest code and the issue still exists

The lockfile is in the `.gitignore`, you need to either delete `Cargo.lock` or run `cargo update`

**Comment by alamb** [comment]
For anyone else that hits this, a workaround is likely to do `cargo update` for your project, as @tustvold  says

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6517

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow-flight'} from #6517
