### ISSUE TITLE
`append_many` for Dictionary builders

### ISSUE THREAD

**Issue by adriangb** [apache/arrow-rs#6529]
I have some data that I know is very repeated because it's essentially denormalized data, so the denormalized column is repeated for many rows. Because of this I'm using a dictionary, but I find myself forced into calling `append_value` in a loop to add the value multiple times. Under the hood this is going to hash it, find that it exists and append to the keys. I'd like a way to skip the extra hashing and instead add the value repeated `n` times.

I realize this can also be done via run encoding but I think this would be a simple and flexible API to add for dictionaries.

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6534
