### ISSUE TITLE
Support signed urls in parquet `object_store::http::HttpStore` (in `object_store::path::Path`)

### ISSUE THREAD

**Issue by joseph-isaacs** [apache/arrow-rs#6532]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I am trying to fetch a file from an object store using a [signed url](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html). Signed urls are urls with signed GET parameters.
I am trying provide this url to `object_store::http::HttpStore`, however the `object_store` path will url encode parameters `"https://example/a?abc=123"` => `https:/example/a%3Fabc=123` removing the GET parameters.

**Describe the solution you'd like**

It would be good to provide a way to construct a Path without url encoding all characters. Maybe as a new builder?

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
I don't think it makes sense to support signed URLs within HTTPStore, as a signed URL is necessarily specific to a particular path.

However, if you have a signed URL you can just pass it to a standard HTTP client, e.g. reqwest? This should just work?

**Comment by joseph-isaacs** [comment]
Okay, thanks.
