### ISSUE TITLE
How to use object_store AmazonS3 list()

### ISSUE THREAD

**Issue by matthias-Q** [apache/arrow-rs#6533]
**Which part is this question about**
I want to list files in a S3 bucket

**Describe your question**

I have prepared the connection to the S3 bucket using:
```rust
let storage_container_key = object_store::aws::AmazonS3Builder::from_env()
        .with_bucket_name("my_bucket")
        .build()
        .expect(""),
);

let key_prefix = &object_store::path::Path::from(key);
let stream = storage_container_key.list(Some(key_prefix));
```
How can I access the stream? Documentation is not helping here. I think this needs n code example.

Thanks

**Comment by joseph-isaacs** [comment]
What about `stream.into_stream()` and then use futures crate?

For example `stream.into_stream().collect::<Vec<_>>()` gives a vec of all items as a future.

**Comment by matthias-Q** [comment]
stream does not have the method `into_stream()`

**Comment by joseph-isaacs** [comment]
Did you include the futures crate.

**Comment by tustvold** [comment]
Perhaps https://docs.rs/object_store/latest/object_store/#list-objects

**Comment by matthias-Q** [comment]
Ah well, I was looking in the API reference. Thanks that helped alot.
