### ISSUE TITLE
Interval parsing from string - accept "mon" and "mons" token

### ISSUE THREAD

**Issue by epsio-banay** [apache/arrow-rs#6548]
I'm trying to parse Postgres time interval type string representation to datafusion, unfortunately it fails because Postgres uses "mon" / "mons" token instead of "month" / months".

I'd like to add "mon" and "mons" as accepted keywords for months in interval parsing from string

**Comment by epsio-banay** [comment]
Just noticed it was recently merged closing

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6549
