### ISSUE TITLE
Make casting from a timestamp without timezone to a timestamp with timezone configurable

### ISSUE THREAD

**Issue by niebayes** [apache/arrow-rs#6555]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

In our time-series database project, we always interpret timestamps without a timezone as being in the UTC timezone. However, when we use the [arrow cast](https://docs.rs/arrow/latest/arrow/compute/fn.cast.html) function to convert a timestamp without a timezone to a specific timezone, the result isn't what we expect. This is because the cast function enforces an adjustment internally, which causes an unintended modification to the timestamp values during the cast process.

As specified in the [doc](https://docs.rs/arrow/latest/arrow/compute/fn.cast_with_options.html#casting-timestamps-without-timezone-to-timestamps-with-timezone) and in the comment of [codes](https://github.com/apache/arrow-rs/blob/9633f14f8d9e5b9b8fdf3514b7acb77217b30584/arrow-cast/src/cast/mod.rs#L1785-L1818),  arrow cast will adjust the timestamp values if casting from a timestamp array without a timezone to a timestamp array with a timezone. 

I propose to make such a behavior configurable and optional. 

**Describe the solution you'd like**

A sound solution may be adding a boolean flag to [`CastOptions`](https://docs.rs/arrow/latest/arrow/compute/struct.CastOptions.html) to make the arrow cast function not perform such an adjustment. This boolean flag may be named `enable_timestamp_adjustment`.

**Describe alternatives you've considered**

**Additional context**

#5827 stated that the behavior of the arrow cast function is somewhat confusing.

**Comment by tustvold** [comment]
Whilst perhaps not ideal, this behaviour can be achieved by first casting to a timestamp with a timezone of UTC and then casting to the desired target TZ.

That being said, if all timestamps are UTC, why not just store them as UTC timestamps?
