### ISSUE TITLE
How to construct a Decimal field backed by Int64?

### ISSUE THREAD

**Issue by jembishop** [apache/arrow-rs#6556]
**Which part is this question about**
Library API

**Describe your question**
I wanted to use a decimal type which can fit in an Int64 which appears to be supported by parquet according to the docs. I noticed that this type is not included as part of the `arrow::datatypes::DataType` enum, there is only the Decimal128, which I didn't want to use because it would double my column size compared to using a Int64. Any idea if there is a way to do this? Thanks

**Comment by tustvold** [comment]
The arrow specification does not currently support 64-bit decimals

**Comment by jembishop** [comment]
Thanks for your reply. So it is supported by parquet but not arrow?

**Comment by tustvold** [comment]
That depends what you mean, arrow readers will read and write 64-bit integer decimals to/from parquet, but the in-memory arrow representation will use at least 128-bit per value.

**Comment by jembishop** [comment]
Thanks. I wanted to use it in the context of using the [`ArrowWriter`](https://arrow.apache.org/rust/parquet/arrow/arrow_writer/struct.ArrowWriter.html) to write parquet files, but I imagine that won't work, as that requires only using the arrow types?

**Comment by tustvold** [comment]
Yes you will need to convert to a Decimal128, provided you stream the batches the additional memory usage shouldn't be noticeable.

**Comment by jembishop** [comment]
Oh great! Thanks very much for your help.

**Comment by jembishop** [comment]
Sorry one issue I am having with this, if  Error writing: Invalid argument error: column types must match schema types, expected Decimal128(18, 18) but found Decimal128(38, 10) at column index 5 exchange=Binance
