### ISSUE TITLE
`object_store` coverage job is failing: cargo-tarpaulin: error while loading shared libraries: libssl.so.1.1: cannot open shared object file

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#6567]
**Describe the bug**
The CI on the `master` branch is failing

here is an example https://github.com/apache/arrow-rs/actions/runs/11354119817/job/31580642096

```
...
    Updating crates.io index
 Downloading crates ...
  Downloaded cargo-tarpaulin v0.18.2
     Ignored package `cargo-tarpaulin v0.18.2` is already installed, use --force to override
/home/runner/.cargo/bin/cargo-tarpaulin: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**To Reproduce**
On CI

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
Maybe we can just disable this job, as I am not aware of anyone else using it

**Comment by tustvold** [comment]
I think we should just disable it, I honestly had no idea it was even there

**Comment by alamb** [comment]
I will make a PR to do so

**Comment by alamb** [comment]
Removal PR:  https://github.com/apache/arrow-rs/pull/6602

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#6567](https://github.com/apache/arrow-rs/issues/6567)
