### ISSUE TITLE
Arrow flight CI test failing on `master`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#6568]
**Describe the bug**

Arrow flight CI test failing on master 

Example: 
https://github.com/apache/arrow-rs/actions/runs/11354119801/job/31580643040

```

running 3 tests
test tests::test_execute_update ... FAILED
test tests::test_select ... FAILED
test tests::test_auth ... FAILED

failures:

---- tests::test_execute_update stdout ----
testing uds client
Client finished!
=======
testing http client
Client finished!
=======
testing https client
thread 'tests::test_execute_update' panicked at arrow-flight/examples/flight_sql_server.rs:834:65:
called `Result::unwrap()` on an `Err` value: IpcError("Can't handshake status: Unknown, message: \"transport error\", details: [], metadata: MetadataMap { headers: {} }")
stack backtrace:
```

**To Reproduce**
RunC CI

**Expected behavior**
Should pass

**Additional context**

**Comment by alamb** [comment]
First started happening with 04fa369aa7b6c2c980909943b40abc264e873494 which is unrelated to flight

I suspect something changed in one of the underlying libraries

**Comment by alamb** [comment]
Starting to look at this one

**Comment by tustvold** [comment]
@viirya perhaps you could take a look, as it appears you added these in https://github.com/apache/arrow-rs/pull/3388

**Comment by alamb** [comment]
I looked into these certificates a bit -- they appear to be copied from the tonic repo. I also tried my hand at regenerating them and failed to get the tests to pass. I will try my hand again either later today or tomorrow if no one beats me to it

**Comment by viirya** [comment]
Hmm, I forgot where I got these certificates...
I will try taking a look if @alamb doesn't fix it.

**Comment by itsjunetime** [comment]
I think I've got this fixed with #6585, a review would be appreciated :)

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6572

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow-flight'} from #6585
