### ISSUE TITLE
WASM in Browser Performance Improvements

### ISSUE THREAD

**Issue by brettsaunders21** [apache/arrow-rs#6570]
**Which part is this question about**

Library performance when compiled for Web Assembly in the browser

**Describe your question**

We're building a browser based library with WASM to power a tabular data display in the browser. The plan is to allow the user to carry out actions like filter, sort, split/pivot and group-by 

We've looked at libraries like polars, duck-db and data fusion, but they all seem to have a large footprint when compiled to WASM. Or there features like group by don't work quite right for us

We've been using this library so far to back our library, but would like to get the most performance out of it we can. So have the follow three questions

- Does this support SIMD in WASM on browser? I see from looking at your code you use it, but seems to only work with a rust flag and seems to be 512 bit AVX512. From research I've only seen 128 bit support mentioned for WASM?
- If yes to the following questions, do you have benchmarks in WASM environment, docs or any details on what uses SIMD?
- Lastly, are there any other options for performance features I can make use of?

**Additional context**

**Comment by tustvold** [comment]
https://github.com/apache/arrow-rs/pull/6554 is probably relevant. I'm not hugely knowledgable about WASM's SIMD support, but presuming you set the appropriate target CPU it should work.

As for performance/support, I know people use this library in WASM contexts but it hasn't been a major development focus, and I am afraid I don't habe any benchmarks. There are also possibly some kernels that assume 64-bit architectures, given this isn't actually tested, bugs may be present related to this.
