### ISSUE TITLE
Compilation fail where `c_char = u8`

### ISSUE THREAD

**Issue by itsjunetime** [apache/arrow-rs#6571]
**Describe the bug**
Arrow integration tests assume that `c_char` = `i8`. While this is true on most platforms, there are many where it is not true (such as arm linux and risc-v linux). This causes a compilation failure in arrow-integration-testing

**To Reproduce**
Compile on a target where `c_char` =  `u8` (e.g. `aarch64-unknown-linux-gnu`)

**Expected behavior**
It should compile fine

**Additional context**
I'll file a PR to fix this.

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6572
