### ISSUE TITLE
Support DataType::Dictionary in `make_builder` within struct_builder.rs

### ISSUE THREAD

**Issue by kszlim** [apache/arrow-rs#6589]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Make it so that dictionary encoded sub-builders can be constructed from Fields.

**Describe the solution you'd like**
As described above

**Describe alternatives you've considered**
n/a

**Additional context**
I don't see any reason why it's unsupported besides it just not being feature complete yet.

**Comment by tustvold** [comment]
The challenge with dictionaries is the combinatorial explosion of possible types, we don't want to pay the codegen and consequently compile time costs for hundreds of different combinations of dictionary builder.

Might I suggest we just cover the cases with Int32 keys, and values of Utf8, LargeUtf8, Binary and LargeBinary.

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6593
