### ISSUE TITLE
Support DataType::FixedSizeList in make_builder within struct_builder.rs

### ISSUE THREAD

**Issue by kszlim** [apache/arrow-rs#6594]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Add the FixedSizeList datatype to `make_builder` in `struct_builder`

**Describe the solution you'd like**
Add the appropriate code

**Describe alternatives you've considered**
Adding the appropriate code

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6595
