### ISSUE TITLE
Implement `append_n` for `BooleanBuilder`

### ISSUE THREAD

**Issue by jayzhan211** [apache/arrow-rs#6634]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

**Describe the solution you'd like**

It has potential to improve the speed if we want to append n false

Currently, we can only do `append_slice`.

```rust
    #[inline]
    pub fn append_slice(&mut self, v: &[bool]) {
        self.values_builder.append_slice(v);
        self.null_buffer_builder.append_n_non_nulls(v.len());
    }
```

If we want to append n false, the first line code can be ignored, since it only appends value if it is true

**Describe alternatives you've considered**

**Additional context**

Could be helpful for https://github.com/apache/datafusion/pull/13134

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6646
