### ISSUE TITLE
ObjectStore: Ability To Write Line-By-Line / Update Via LocalFileSystem

### ISSUE THREAD

**Issue by just-a-stream** [apache/arrow-rs#6656]
It appears it's not possible to use this library's LocalFileSystem store to: 
1. Create a file, writing the first line (eg/ Borsh bytes). 
2. Update an existing file, writing the second line. 
3. Etc. 

It would be great to have this functionality. 

Thanks!

**Comment by tustvold** [comment]
We used to support this in form of ObjectStore::append, however, this was removed in https://github.com/apache/arrow-rs/pull/5016.

Ultimately supporting this sort of API is at odds with the goals of the crate to provide an atomic API that is portable to object stores.

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#6656](https://github.com/apache/arrow-rs/issues/6656)
