### ISSUE TITLE
Make rand an optional dependency

### ISSUE THREAD

**Issue by roee88** [apache/arrow-rs#671]
Following https://github.com/apache/arrow-rs/pull/488 arrow-rs compiles to wasm32-unknown-unknowm only with the "js" feature of rand enabled. However, when the "js" feature is enabled the produced wasm modules are no longer stand alone and require JavaScript, which is not necessarily available. For example, these modules can't run in runtimes like wasmer (in contrast to modules compiled to wasm32-unknown-unknowm with arrow-rs 4.x).

**Describe the solution you'd like**

Make rand an optional dependency so we can opt out. In arrow2 this is already the case (and at least there rand is only used in benchmarks). 

**Describe alternatives you've considered**

If it's only use for benchmarks and testing in arrow-rs too then make it an optional dependency that is only enabled when feature flags for benchmarks are set (if that exists already).

**Comment by alamb** [comment]
sounds like a good idea to me -- @roee88  do you plan to work on this one or would you like help?
