### ISSUE TITLE
Add support for Utf8View -> numeric in can_cast_types

### ISSUE THREAD

**Issue by Omega359** [apache/arrow-rs#6715]
**Describe the bug**

It looks like utf8View -> numeric support is available in [cast_with_options](https://github.com/apache/arrow-rs/blob/28878d375c5bb1c2f5adb46b287e16cea768b6e7/arrow-cast/src/cast/mod.rs#L1287) however can_cast_types does not reflect that.

can_cast_types should be gone over closely to verify it reflects what is actually supported wrt Utf8Views 

**To Reproduce**

Done via DF's slt tests
```
query B
select arrow_cast(arrow_cast('1', 'Utf8View'), 'Int32') < 2;
----
true
```
 DataFusion error: This feature is not implemented: Unsupported CAST from Utf8View to Int32

**Expected behavior**

This should work as expected

**Additional context**

**Comment by tlm365** [comment]
take
