### ISSUE TITLE
Improve error message for unsupported cast between struct and other types

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-rs#6724]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

In general, we have detailed error messages for unsupported casts, such as:

```rust
_ => Err(ArrowError::CastError(format!(
    "Casting from {from_type:?} to {to_type:?} not supported"
```

However, the messages for casting between struct and non-struct types does not provide information on the types that were attempted to be cast, making it harder to debug issues.

```rust
(Struct(_), _) => Err(ArrowError::CastError(
    "Cannot cast from struct to other types except struct".to_string(),
)),
(_, Struct(_)) => Err(ArrowError::CastError(
    "Cannot cast to struct from other types except struct".to_string(),
)),
```

**Describe the solution you'd like**

I would like the error message to follow the same format as other unsupported casts:

```rust
"Casting from {from_type:?} to {to_type:?} not supported"
```

**Describe alternatives you've considered**

**Additional context**

**Comment by Silverviles** [comment]
Hello! I'd like to compete this task.

**Comment by Silverviles** [comment]
take

**Comment by Silverviles** [comment]
take

**Comment by takaebato** [comment]
@Silverviles 
Are you working on this? I'm thinking of tackling it :)

**Comment by Silverviles** [comment]
@takaebato Please go ahead. You can work on it.

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6919
