### ISSUE TITLE
StructArray take doesn't make fields nullable

### ISSUE THREAD

**Issue by gatesn** [apache/arrow-rs#6727]
**Describe the bug**
When calling `arrow::compute::take` on a StructArray with non-nullable fields and passing take indices that contain null values, the resulting StructArray still has non-nullable fields. This is an invalid state.

**Expected behavior**
The take function should convert all fields to nullable _iff_ the take indices contain any nulls.

https://docs.rs/arrow-select/53.2.0/src/arrow_select/take.rs.html#238-239

**Comment by tustvold** [comment]
Generally I wouldn't expect a selection kernel to alter the schema, so I think in this case it should raise an error

**Comment by gatesn** [comment]
Yes that's also reasonable

**Comment by tustvold** [comment]
> It's a bit annoying that Arrow DataTypes don't themselves have a nullable flat

One way to get this is to use StructArray in place of RecordBatch, this is actually what a lot of the IO logic in arrow-rs does, converting to RecordBatch at the edges.

IMO RecordBatch is confusing and arrow would be better off without it, but it's too late for that now 😅

**Comment by malikrohail** [comment]
can i fix

**Comment by midnattsol** [comment]
Hello, I'd be happy to work on this.

I'm already making some tests, adding the validation to the struct datatype:

```rust
        DataType::Struct(fields) => {
            let array: &StructArray = values.as_struct();
            for (field, _) in fields.iter().zip(array.columns()) {
                if !field.is_nullable() && indices.null_count() > 0 {
                    return Err(ArrowError::ComputeError(format!(
                        "Cannot introduce nulls in non-nullable field '{}'",
                        field.name()
                    )));
                }
            }
```

Testing it, it seems to work when I try to use take over a StructArray:
```rust
use arrow::array::{Int32Array, StringArray, StructArray};
use arrow::compute::take;
use arrow::datatypes::{DataType, Field};
use std::sync::Arc;

fn main() {
    let field1 = Int32Array::from(vec![Some(1), Some(2), Some(3)]);
    let field2 = StringArray::from(vec![Some("a"), Some("b"), Some("c")]);
    let struct_array = StructArray::from(vec![
        (
            Arc::new(Field::new("field1", DataType::Int32, false)),
            Arc::new(field1) as Arc<dyn arrow::array::Array>,
        ),
        (
            Arc::new(Field::new("field2", DataType::Utf8, false)),
            Arc::new(field2) as Arc<dyn arrow::array::Array>,
        ),
    ]);

    let indices = Int32Array::from(vec![Some(0), None, Some(2)]);

    // Aplicar la función take
    let result = take(&struct_array, &indices, None).unwrap();
    let result_struct = result.as_any().downcast_ref::<StructArray>().unwrap();

    println!("Resultado StructArray: {:?}", result_struct);
```

**Result**
```sh
     Running `target/debug/arrow-playground`
thread 'main' panicked at src/main.rs:25:54:
called `Result::unwrap()` on an `Err` value: ComputeError("Cannot introduce nulls in non-nullable field 'field1'")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

But when I try to use take over specific Fields, the issue stays the same. I can try to solve this too, but I just want to be sure that I'm not misanderstanding anything.

I would appreciate feedback, it's my first issue related with `Arrow` ecosystem.

Regards

**Comment by midnattsol** [comment]
I've updated my code to add the validation in the right place (take instead of take_impl, what solves the issue for the StructArray and the columns as well

```rust
pub fn take(
    values: &dyn Array,
    indices: &dyn Array,
    options: Option<TakeOptions>,
) -> Result<ArrayRef, ArrowError> {
    let options = options.unwrap_or_default();
    macro_rules! helper {
        ($t:ty, $values:expr, $indices:expr, $options:expr) => {{
            let indices = indices.as_primitive::<$t>();
            if $options.check_bounds {
                check_bounds($values.len(), indices)?;
            }
            if values.nulls().is_none() && indices.null_count() > 0 {
                return Err(ArrowError::ComputeError(
                    "Cannot use null indices on non-nullable array".to_string(),
                ));
            }
            let indices = indices.to_indices();
            take_impl($values, &indices)
        }};
    }
    downcast_integer! {
        indices.data_type() => (helper, values, indices, options),
        d => Err(ArrowError::InvalidArgumentError(format!("Take only supported for integers, got {d:?}")))
    }
}
```

I will open a PR if it looks good for you @gatesn @tustvold

**Comment by gatesn** [comment]
The other possibly reasonable fix is that the null take indices should turn the StructArray's null buffer, rather than the null buffers of each of the fields.

But there doesn't seem to be good support for dealing with nullable struct arrays, e.g. DataFusion doesn't have a nullable struct scalar.

**Comment by midnattsol** [comment]
> The other possibly reasonable fix is that the null take indices should turn the StructArray's null buffer, rather than the null buffers of each of the fields.

The issue I see with this approach is that managing nulls at the StructArray's null buffer, but not in the null buffers of each of the fields, can lead to uninitialized or default values in those fields. So, if someone tries to access those values using `column_by_name` without checking the StructArray's null bitmap, they could encounter unexpected behavior, right?

**Comment by tustvold** [comment]
The logic https://github.com/apache/arrow-rs/blob/main/arrow-select/src/take.rs#L235 is correct and should not be changed.

Additionally https://github.com/apache/arrow-rs/blob/main/arrow-select/src/take.rs#L257 will perform the necessary validation to ensure the StructArray is valid.

However, the case could be made that an error would be more helpful, and this should be relatively straighforward case of changing https://github.com/apache/arrow-rs/blob/main/arrow-select/src/take.rs#L257 to use [StructArray::try_new](https://docs.rs/arrow-array/latest/arrow_array/array/struct.StructArray.html#method.try_new) which will return an error instead of panicking

**Comment by tustvold** [comment]
Re-reading the ticket again the premise is incorrect

> the resulting StructArray still has non-nullable fields. This is an invalid state.

A non-nullable field can contain nulls provided these are masked by the parent StructArray, otherwise it would be impossible to have a structure where the StructArray is nullable but not its fields.

**Comment by gatesn** [comment]
> > The other possibly reasonable fix is that the null take indices should turn the StructArray's null buffer, rather than the null buffers of each of the fields.
> 
> The issue I see with this approach is that managing nulls at the StructArray's null buffer, but not in the null buffers of each of the fields, can lead to uninitialized or default values in those fields. So, if someone tries to access those values using `column_by_name` without checking the StructArray's null bitmap, they could encounter unexpected behavior, right?

That's correct. But that's also true if I access a PrimitiveArray value buffer and don't check the null bitmap.

I think I've come round to agreeing with @tustvold, although it is a little odd, that a non-nullable field can contain nulls provided they are masked by the struct array's own validity bitmap. If a row is invalid in the struct array, then all bets are off when looking at that index in one of the struct's fields.

As such, I'm going to close this. Happy for someone else to re-open if they disagree with this conclusion
