### ISSUE TITLE
Formalize the name of the nested `Field` in a list

### ISSUE THREAD

**Issue by gruuya** [apache/arrow-rs#6784]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
As discussed in https://github.com/apache/datafusion/pull/13468#discussion_r1848580504, currently it is a convention to have list field member fields (i.e. the inner field) names be `item`. However this is not formalized in any way, and consequently there's a large number of `item` literals thrown around the codebase.

**Describe the solution you'd like**
Add a `Field::LIST_FIELD_DEFAULT_NAME` constant set to `item`, and use it in `Field::new_list_field`. 

Also replace any calls to `Field::new` with explicit `item` name to use `Field::new_list_field` instead.

**Describe alternatives you've considered**
Could also make a free-standing as opposed to an associated constant (or not extract into a constant at all).

**Additional context**
Spin-off out of https://github.com/apache/datafusion/pull/13468

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'parquet'} from #6785

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6785

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow-flight'} from #6785
