### ISSUE TITLE
[FlightSQL] GetCatalogsBuilder does not sort the catalog names

### ISSUE THREAD

**Issue by niebayes** [apache/arrow-rs#6807]
The GetCatalogsBuilder does not apply sorting as specified in the documentation comments. In contrast, other builders, such as GetDbSchemasBuilder and GetTablesBuilder, sort the record batch exactly as described in their documentation.

See: https://github.com/apache/arrow-rs/blob/e1e881405ce9b180858d5ba278803b4795b63e74/arrow-flight/src/sql/arrow.flight.protocol.sql.rs#L120-L122

And see: https://github.com/apache/arrow-rs/blob/e1e881405ce9b180858d5ba278803b4795b63e74/arrow-flight/src/sql/metadata/catalogs.rs#L70-L79

**Comment by alamb** [comment]
Thank you for the report @niebayes

**Comment by niebayes** [comment]
take

**Comment by alamb** [comment]
Feel free to @ mention me on the PR and I can review

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6864

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow-flight'} from #6864
