### ISSUE TITLE
Change `DataType::Dictionary(DataType,DataType)` to `DataType::Dictionary(DataType,Field)`

### ISSUE THREAD

**Issue by jorgecarleitao** [apache/arrow-rs#681]
The dictionary metadata in FFI (and IPC AFAIK) stores not only the type, but also a name and nullability of the dictionary of the array. However, we currently can't store that information in `DataType::Dictionary`, therefore failing to roundtrip it.

Changing it to `DataType::Dictionary(DataType,Field)` (with the boxes for sizing) would allow these rountrips.

(Note, this is not 100% certain for me; I am opening the discussion here)

**Comment by jorgecarleitao** [comment]
cc @nevi-me , as you may know why we do not use `Field` here.

**Comment by tustvold** [comment]
IPC does not encode this information as far as I can tell, with nullability only encoded on the `Field` and not `DictionaryEncoding`

Feel free to reopen if I am mistaken
