### ISSUE TITLE
Allow casting from `DataType::Null` to any other type 

### ISSUE THREAD

**Issue by bjchambers** [apache/arrow-rs#684]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

It seems like converting a null column to other types should be trivially supported (all null values). Right now when operations require this, I need to have a function that creates an array of null values of the given data type.

**Describe the solution you'd like**
Casting an array with `DataType::Null` to any other type produces an array of the given type containing all null values.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by alamb** [comment]
We might end up implementing this for DataFusion as well in https://github.com/apache/arrow-datafusion/issues/1188

**Comment by alamb** [comment]
Note there is https://docs.rs/arrow/latest/arrow/array/fn.new_null_array.html which can create an array full of nulls of any type. This ticket would entail hooking it into the cast kernel I think

**Comment by alamb** [comment]
The cast kernels are here: https://github.com/apache/arrow-rs/blob/master/arrow/src/compute/kernels/cast.rs

To support casting requires:
1. add entry to `can_cast_types`
2. Add actual cast code to `cast_with_options`
3. Add relevant tests

**Comment by WinkerDu** [comment]
> The cast kernels are here: https://github.com/apache/arrow-rs/blob/master/arrow/src/compute/kernels/cast.rs
> 
> To support casting requires:
> 
> 1. add entry to `can_cast_types`
> 2. Add actual cast code to `cast_with_options`
> 3. Add relevant tests

@alamb here is a rough fix #1572 , plz have a review, thank you.
