### ISSUE TITLE
`object_store` errors when `reqwest` `gzip` feature is enabled

### ISSUE THREAD

**Issue by phillipleblanc** [apache/arrow-rs#6842]
**Describe the bug**

Reqwest has a non-default feature `gzip` that will add the `Content-Encoding: gzip` headers and [automatically decompresses] the gzipped responses, with the side-effect of removing the `Content-Length` header. The `object_store` crate expects the `Content-Length` [header to be present] and will error otherwise.

[automatically decompresses]: https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.gzip
[header to be present]: https://github.com/apache/arrow-rs/blob/30c14abd3340735e5e4ab9375628f8d8ba7223b4/object_store/src/client/header.rs#L123

This has the side-effect of code that was previously working could suddenly stop working if any dependency in the project enables the `gzip` feature for `reqwest` AND the HTTP server supports the `Accept-Encoding: gzip` header.

**To Reproduce**

I've created a minimal repro illustrating the bug here: https://github.com/phillipleblanc/object_store_gzip_repro

**Expected behavior**

Even if the `gzip` feature is enabled for `reqwest`, the `object_store` client should continue to work when making requests against HTTP servers that support gzip compression.

**Additional context**

N/A

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'object-store'} from #6843

**Comment by alamb** [comment]
Migrating from arrow-rs issue [#6842](https://github.com/apache/arrow-rs/issues/6842)
