### ISSUE TITLE
Add builder support for Int8 keys

### ISSUE THREAD

**Issue by ajwerner** [apache/arrow-rs#6844]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I would like to be able to create a DictionaryBuilder with an int8 key type. https://github.com/apache/arrow-rs/issues/6589 added support for some dictionaries to the builder, but it didn't support all the key types. There was some concern about code bloat, and that is warranted, but it's also the case that dictionaries with small numbers of values (sometimes just 1) come up. 

**Describe the solution you'd like**
Also support int8 keys.

**Describe alternatives you've considered**
Fork the entire builder infrastructure?

**Comment by alamb** [comment]
`label_issue.py` automatically added labels {'arrow'} from #6845
