### ISSUE TITLE
Implement casting between duration/intervals and numbers

### ISSUE THREAD

**Issue by bjchambers** [apache/arrow-rs#685]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

After computing the days between two timestamps to produce an interval days, it would be useful to be able to convert that to a number. This is helpful because (1) some output formats don't support durations/intervals and (2) it may be desirable to do math on the number of days / months / seconds.

**Describe the solution you'd like**

The cast kernel extended to support casting from Duration and Interval Types to at least the corresponding primitive type.

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
It seems as if we are going with a dual approach here: 
1. Allow casting to the underlying primitive type - #1196 
2. Additional temporal kernels to extract parts of it, e.g https://docs.rs/arrow/7.0.0/arrow/compute/kernels/temporal/index.html#
