### ISSUE TITLE
Iterator over Parquet page headers

### ISSUE THREAD

**Issue by trungda** [apache/arrow-rs#6880]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Hi team, 
I am reading through the different `*SerializedReaders` and I haven't seen a way to iterate through only the Parquet page headers. Maybe I am missing something? If not, I am happy to take this issue. 

**Describe the solution you'd like**

A `SerializedPageHeaderReader` (I am happy to take feedback) that only returns back the page headers. 

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
https://docs.rs/parquet/latest/parquet/column/page/trait.PageReader.html#tymethod.peek_next_page

**Comment by trungda** [comment]
> https://docs.rs/parquet/latest/parquet/column/page/trait.PageReader.html#tymethod.peek_next_page

Thank you! Looks like `peek_next_page` can only be used along side with `read_records` , i.e., we can only peek the next page's header when we are at the end of the current page. Please correct me if I am wrong. 
What I am trying to do is to scan through all the page headers of a file.

**Comment by tustvold** [comment]
You can alternate peeking and skipping, or alternatively just inspect the column index structures directly

https://docs.rs/parquet/latest/parquet/file/metadata/struct.ParquetMetaData.html

**Comment by trungda** [comment]
> You can alternate peeking and skipping, or alternatively just inspect the column index structures directly
> 
> https://docs.rs/parquet/latest/parquet/file/metadata/struct.ParquetMetaData.html

I see. So we would (1) peek; (2) get number of records from the header (`n`); (3) skip `n` records. That could work. Thank you! I don't want to rely on column index structures since some files (Parquet v1?) don't really have them.

**Comment by tustvold** [comment]
> since some files (Parquet v1?) don't really have them.

All files from recent writers _should_ have them, there is no good reason not to write them.

Without the at least the offset index there isn't a way to determine where the pages are located, and therefore decoding the pages headers is very expensive.

**Comment by trungda** [comment]
> All files from recent writers _should_ have them, there is no good reason not to write them, they're a backward compatible addition that fix a lot of issues.

Ya, I am working with Parquet generated by Spark and indeed some don't really have the column indexes. Thank you for your suggestions tho. I think this can be closed.

**Comment by trungda** [comment]
Hmm, actually `PageMetadata` loses some information that I need, such as `uncompressed_page_size`. Probably I need to hand roll my own iterator based on `SerializedPageReader`.

**Comment by tustvold** [comment]
https://github.com/apache/arrow-rs/blob/main/parquet%2Fsrc%2Fbin%2Fparquet-layout.rs may contain some inspiration. It definitely could be made easier

**Comment by trungda** [comment]
Thank you! We are going to build our own internal page header iterator. Maybe we can upstream it later.
