### ISSUE TITLE
Adds a `contains_unordered` method for Schema to support unordered schema matching

### ISSUE THREAD

**Issue by niebayes** [apache/arrow-rs#6883]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

The Schema struct provides a helper method `contains` to perform schema matching, where two schemas are considered a match if and only if their fields are identical and in the same order.

However, there are scenarios where unordered schema matching is preferable. For instance:

1. In an INSERT statement like `INSERT INTO <table_name> (a, c, b) VALUES (...)`, the value schema is defined as "a, c, b", while the table schema is "a, b, c".
2. In the case of prepared statements, a parameter needs to be bound to the prepared statement. For a parameter to be valid, its schema must be a subset of the table schema, but it does not need to have identical field order.

To address these use cases, we propose adding a `contains_unordered` helper method to the Schema struct:

``` rust
fn contains_unordered(&self, other: &Schema) -> Result<()>;
```

This method returns Ok if and only if the schema of self is a superset of the schema of other, without requiring the order of fields to match.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
I think rather than continuing to add increasingly specialized methods to Schema directly, we would be better off defining an actual schema adaptor mechanism.

Closing in favour of https://github.com/apache/arrow-rs/issues/6735
