### ISSUE TITLE
Add documentation examples for `regexp_match` kernels 

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#696]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
The current documentation for the `regexp_match` kernel is quite sparse:
https://docs.rs/arrow/5.2.0/arrow/compute/kernels/regexp/fn.regexp_match.html

![Screen Shot 2021-08-18 at 9 50 12 AM](https://user-images.githubusercontent.com/490673/129910047-fbcb7f02-b798-4cfb-ae11-02770f160b39.png)

Also, since this function returns `ArrayRef` (aka untyped generic Array), I was personally a bit confused that `regexp_match` actually returns a `ListArray` with the matches. Having this documented would help a lot. 

**Describe the solution you'd like**
1. A description of the type of the array that is returned
2. A doc example (can probably adapt a test in the code) that shows how to invoke `regexp_match` and use the returned `ListArray`

**Comment by matthewmturner** [comment]
I can give this a shot

**Comment by matthewmturner** [comment]
@alamb im playing around with the regexp_match function and struggling to produce the expected results.  I tried to do something similar to the test `match_single_group`.  

I have the following:
```
let array = StringArray::from(vec![Some("Animal"), None, Some("House")]);
let pat = StringArray::from(vec![r"^[A]"; 3]);
let m = regexp_match(&array, &pat, None).unwrap();
let result = m.as_any().downcast_ref::<ListArray>().unwrap();

let elem_builder: GenericStringBuilder<i32> = GenericStringBuilder::new(0);
let mut expected_builder = ListBuilder::new(elem_builder);
expected_builder.values().append_value("A").unwrap();
expected_builder.append(true).unwrap();
expected_builder.append(false).unwrap();
expected_builder.append(false).unwrap();
let expected = expected_builder.finish();
assert_eq!(&expected, result);
```

But get the following:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `ListArray
[
  StringArray
[
  "A",
],
  null,
  null,
]`,
 right: `ListArray
[
  StringArray
[
],
  null,
  null,
]`', src/main.rs:54:5
```
It's not clear to me why the result StringArray at the first index of the ListArray doesnt have "A" - its just an empty StringArray.

Any thoughts?

**Comment by alamb** [comment]
@matthewmturner I also don't understand that -- if you remove the caret and use `[A]` as the regex does it do the right thing? Perhaps @seddonm1  has some hints as well

**Comment by matthewmturner** [comment]
@alamb unfortunately not, same result.

**Comment by alamb** [comment]
🤔  I don't have a good answer then. It would require some more debugging

**Comment by seddonm1** [comment]
@alamb Sorry I didn't do this one. It does appear there may be a defect.

@matthewmturner are you able to reproduce the behaviour to verify that it behaves differently to Postgres? (https://www.postgresql.org/docs/current/functions-matching.html)

**Comment by matthewmturner** [comment]
@seddonm1 sure, will give it a shot.

**Comment by matthewmturner** [comment]
@seddonm1 i believe postgres works as expected. i did the below.

```
postgres=# WITH vals(a) AS (VALUES ('Animal'), (null),  ('House')) 
SELECT a, regexp_matches(a, '^[A]') m from vals;
```

Resulting in
```
   a    |  m  
--------+-----
 Animal | {A}
(1 row)
```

**Comment by seddonm1** [comment]
Thanks @matthewmturner i will have a look
