### ISSUE TITLE
Empty or null list of struct cannot be written to parquet 

### ISSUE THREAD

**Issue by mosyp** [apache/arrow-rs#703]
**Describe the bug**
When writing arrow batch with empty or null list struct, it fails with `General("Inconsistent length of definition and repetition levels: 0 != 1")`

**To Reproduce**
Write record batch which contain empty or null list of struct. Here's the PR with full repro behaviour https://github.com/apache/arrow-rs/pull/704

**Expected behavior**
The batch is successfully written

**Additional context**
WHat I could debug is that this line should fail https://github.com/apache/arrow-rs/blob/master/parquet/src/arrow/levels.rs#L646, because at some point the `array_mask` becomes empty slice which leads to the _Inconsistent length of definition and repetition levels_

I feel like this might be somehow connected https://github.com/apache/arrow-rs/issues/594.

**Comment by chadbrewbaker** [comment]
I'm getting the same issue on darwin-aarch64 using the [json2parquet](https://lib.rs/crates/json2parquet) CLI.

```bash

wget https://raw.githubusercontent.com/json-iterator/test-data/master/large-file.json
# Convert it into newline delimited JSON or else Arrow complains
cat large-file.json | jq -c '.[]' > lf.json  
json2parquet  lf.json bork.pq

# Error: General("Inconsistent length of definition and repetition levels: 891 != 1388")
```

**Comment by chadbrewbaker** [comment]
This line of JSON is barfing in json2parquet with: 

```bash
thread 'main' panicked at 'Cannot filter indices on a non-primitive array, found List(true)'
```
https://github.com/apache/arrow-rs/blob/e0abda2c178be0c38d4257d22de2e4a3bfafde82/parquet/src/arrow/levels.rs#L757

```json
{"ts":1331901001.88,"fuid":"Fd3cGk2agqUftBeFx4","tx_hosts":["192.168.229.251"],"rx_hosts":["192.168.202.79"],"conn_uids":["CaJMZy195M8cuXfxn4"],"source":"HTTP","depth":0,"analyzers":[],"mime_type":"text/html","duration":0.0,"is_orig":false,"seen_bytes":1433,"total_bytes":1433,"missing_bytes":0,"overflow_bytes":0,"timedout":false}
```

**Comment by chadbrewbaker** [comment]
Looks like we might have to translate  https://github.com/apache/arrow/blob/master/python/pyarrow/tests/test_json.py

Better yet add a json directory for all the arrow clients:
https://github.com/apache/arrow-testing/tree/master/data
