### ISSUE TITLE
Support for nested data types

### ISSUE THREAD

**Issue by kyogesha** [apache/arrow-rs#720]
While reading a parquet file using arrow rust, I ran into an issue 
```
ArrowError("reading List(GroupType ... into arrow not supported yet")
```

Any timeline for supporting nested structures would be of great help.

Thanks!

**Comment by kesavkolla** [comment]
@kyogesha can you add the actual type definition that is involved in this exception?

**Comment by Igosuki** [comment]
@kesavkolla Here are two parquet-files that cannot be read by arrow-rs : 
https://github.com/Igosuki/arrow2/blob/main/part-00000-b4749aa1-94e4-4ddb-bab2-954c4d3a290f.c000.snappy.parquet
https://github.com/chauhanVritul/sampleparquet/blob/main/part-00000-8e5acb24-eb4e-491c-8c85-88799f25d1f0-c000.snappy.parquet
