### ISSUE TITLE
Question: Is there no way to create a DictionaryArray with a pre-arranged mapping?

### ISSUE THREAD

**Issue by jmrgibson** [apache/arrow-rs#729]
It would appear from [the docs](https://docs.rs/arrow/5.2.0/arrow/array/struct.DictionaryArray.html) that you cannot create a `DictionaryArray` by defining both the keys and and values? This is opposed to the [python API](https://arrow.apache.org/docs/python/data.html#dictionary-arrays) which does. This is quite useful for cases where the dictionary mapping is defined elsewhere (e.g., a C enum). Are there plans to add this? Or am I reading the docs wrong. Thanks!

**Comment by jhorstmann** [comment]
There is [StringDictionaryBuilder::new_with_dictionary](https://docs.rs/arrow/5.2.0/arrow/array/struct.StringDictionaryBuilder.html#method.new_with_dictionary) which allows specifying existing dictionary values when building an array.

There is also a low-level way of [building array from an underlying ArrayData struct](https://docs.rs/arrow/5.2.0/arrow/array/struct.DictionaryArray.html#impl-From%3CArrayData%3E), but this is much more complex than the python api you pointed too. So I agree, such an api would be quite useful.

**Comment by jmrgibson** [comment]
Ah neat, yeah `new_with_dictionary` is what I wanted, I was just looking in the wrong place. Thanks!

**Comment by jhorstmann** [comment]
For combining keys with an existing dictionary there is also [PrimitiveBuilder::finish_dict](https://docs.rs/arrow/5.3.0/arrow/array/struct.PrimitiveBuilder.html#method.finish_dict). This is not that obvious to find in the documentation and I also forgot about it.
