### ISSUE TITLE
Support equality on RecordBatch

### ISSUE THREAD

**Issue by bjchambers** [apache/arrow-rs#735]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

This would simplify testing. Right now, if I have two record batches that I want to test for equality I need to either look at their individual columns, or convert the batch to a `StructArray`.

**Describe the solution you'd like**

It seems like we should be able to implement `PartialEq` (and possibly `Eq`) for `RecordBatch` to perform equality on the schema and columns.

**Describe alternatives you've considered**

**Additional context**

**Comment by matthewmturner** [comment]
@bjchambers I can give this a shot.
