### ISSUE TITLE
length on slices with null doesn't work

### ISSUE THREAD

**Issue by bjchambers** [apache/arrow-rs#744]
**Describe the bug**

`length` kernel (for string length) doesn't work on sliced string arrays containing null.

**To Reproduce**

Modify the existing tests to include null:

```
    /// Tests with an offset
    #[test]
    fn bit_length_offsets() -> Result<()> {
        let a = StringArray::from(vec![Some("hello"), Some(" "), Some("world"), None]);
        let b = a.slice(1, 3);
        let result = bit_length(b.as_ref())?;
        let result: &Int32Array = as_primitive_array(&result);

        let expected = Int32Array::from(vec![Some(8), Some(40), None]);
        assert_eq!(&expected, result);

        Ok(())
    }
```

**Expected behavior**
Test passes.

**Actual behavior**
Test does not pass.

**Comment by matthewmturner** [comment]
@bjchambers i can try looking into this.

**Comment by bjchambers** [comment]
@matthewmturner I think it should be addressed by #745.

**Comment by matthewmturner** [comment]
@bjchambers ah missed the linked pull. thx.

**Comment by matthewmturner** [comment]
@bjchambers out of curiousity - do you know why the `length_offsets` test uses `bit_length` function instead of `length`?

**Comment by bjchambers** [comment]
Hmm... probably a copy-paste error when updating/adding the tests. Could you comment on the PR and I'll update/resolve when I get a chance?
