### ISSUE TITLE
Add examples to Rust Docs for arrow::array::UnionArray

### ISSUE THREAD

**Issue by matthewmturner** [apache/arrow-rs#751]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I would like to see examples of how to use UnionArrays in the Rust docs (https://docs.rs/arrow/5.3.0/arrow/array/struct.UnionArray.html).  The explanations are good, but examples would improve my understanding.

**Describe the solution you'd like**
Add examples for `new` and try_new`

**Describe alternatives you've considered**

**Additional context**
I thought of this while I was looking into #654

**Comment by HaoYang670** [comment]
I'd like to try if no one has been doing it.
