### ISSUE TITLE
parquet benchmark is out of sync with the current code base

### ISSUE THREAD

**Issue by houqp** [apache/arrow-rs#770]
**Describe the bug**

parquet benchmark run is broken with the following error message:

```
error[E0432]: unresolved imports `parquet::util::DataPageBuilder`, `parquet::util::DataPageBuilderImpl`, `parquet::util::InMemoryPageIterator`
  --> parquet/benches/arrow_array_reader.rs:19:21
   |
19 | use parquet::util::{DataPageBuilder, DataPageBuilderImpl, InMemoryPageIterator};
   |                     ^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^ no `InMemoryPageIterator` in `util`
   |                     |                |
   |                     |                no `DataPageBuilderImpl` in `util`
   |                     no `DataPageBuilder` in `util`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `parquet` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**To Reproduce**

run `cargo bench`

**Expected behavior**

benchmark should compile without error.

**Additional context**

would be good if we test for benchmark builds in CI by running `cargo bench --no-run`

**Comment by carols10cents** [comment]
I just ran into this too. Looks like [these types are now behind the `test_common` feature](https://github.com/apache/arrow-rs/blob/9fb2a5fab32d50feacc1f600b45606ba402017df/parquet/src/util/mod.rs#L27-L30); running `cargo check --benches --features=test_common -p parquet` *does* compile.

I'm not sure if it would be ok to remove the `#[cfg(any(test, feature = "test_common"))]` for these types, or if running parquet benches should be documented to need the test_common features and tested in CI. I'm going to open a PR for the latter two, at least.

**Comment by alamb** [comment]
I think this was fixed in https://github.com/apache/arrow-rs/pull/1001

I now run `cargo bench` and it compiles just fine for me locally

**Comment by alamb** [comment]
Thanks again @carols10cents
