### ISSUE TITLE
Expose Plasma: In-Memory Object Store API

### ISSUE THREAD

**Issue by munro** [apache/arrow-rs#783]
Has anyone looked into adding the Arrow Plasma API [1] to rust lib?

I would love to use it for doing IPC, but I'm guessing people are using other libraries to do that?

[1] https://arrow.apache.org/docs/python/plasma.html

**Comment by tustvold** [comment]
Plasma is being removed from arrow, so closing this one - https://github.com/apache/arrow/issues/33243
