### ISSUE TITLE
Add doc examples of writing parquet files using `ArrowWriter`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#788]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
When people ask how to create a parquet file in Rust, I would like to point them at the docs for the arrow writer. 
https://docs.rs/parquet/5.4.0/parquet/arrow/arrow_writer/index.html#

An example when this would be helpful is on https://github.com/apache/arrow-datafusion/pull/1024: https://github.com/apache/arrow-datafusion/pull/1024#issuecomment-923151473

**Describe the solution you'd like**
I would like an example on https://docs.rs/parquet/5.4.0/parquet/arrow/index.html#example-of-reading-parquet-file-into-arrow-record-batch  that shows how to *write* files. The existing example shows how to read such files.

**Comment by matthewmturner** [comment]
@alamb ill work on this
