### ISSUE TITLE
Buffer::bit_slice has incorrect length for aligned offset

### ISSUE THREAD

**Issue by bjchambers** [apache/arrow-rs#807]
**Describe the bug**
Because `buf.bit_slice(...)` falls back to a slice that ignores the length when the offset is byte-aligned, the resulting buffer has an incorrect length. This leads to problems when applying bitwise operations such as `&`, for instance.

**To Reproduce**

The following test fails:

```
    #[test]
    fn test_bit_slice_aligned() {
        let buf = Buffer::from(&[2, 4, 6, 8, 10]);
        let slice = buf.bit_slice(8, 8);
        let expected = Buffer::from(&[4]);
        assert_eq!(slice.len(), 1); // actual length is 4!!
        assert_eq!(&slice, &expected);
    }
```

**Expected behavior**
Test passes.

**Additional context**

**Comment by bjchambers** [comment]
Unfortunately, I don't see an easy way to fix this without affecting performance. Specifically, the buffer doesn't have a length, so we can't just use `buf.slice(1)` and have the length be correct for later operations. On the other hand, actually creating a new buffer just to have a shorter length seems like it would be more expensive from a performance perspective.

**Comment by bjchambers** [comment]
See https://github.com/bjchambers/arrow-rs/commit/9aec6dcf0d0d0ded9f8ff392e1c34990d0bd89ef for example test.

**Comment by bjchambers** [comment]
If the intention of `Buffer` is to not have a length, then maybe like `bit_slice` shouldn't accept a length / affect the length. Instead, it should only take an `offset` (like `Buffer::slice`).

**Comment by HaoYang670** [comment]
Maybe an alternative way is to add the `length` field for `Buffer`, such as:
```rust
pub struct Buffer {
    /// the internal byte buffer.
    data: Arc<Bytes>,

    /// The offset into the buffer.
    offset: usize,

    /// byte length
    length: usize,
}
```

Then we can always give buffer the correct length and reuse `data` when doing `slice` or `bit_slice`.

**Comment by HaoYang670** [comment]
cc @alamb @viirya @tustvold

**Comment by tustvold** [comment]
Currently, as alluded to @bjchambers, the length of a `Buffer` is somewhat immaterial, with length solely a property of the Array / ArrayData, and the size of the underlying buffers kind of arbitrary. This is in fact key to how ArrayData and Array slicing currently works - it doesn't actually slice the underlying `Buffer` at all.

There are suggestions to change aspects of this, e.g. @jhorstmann on https://github.com/apache/arrow-rs/pull/1499, but I'm not sure where they've gotten. I personally need a better idea of where we're headed w.r.t buffer offset handling before I'd want to weigh in on what we should do here.

**Comment by HaoYang670** [comment]
BTW, is it better to move `bit_slice` to `Bitmap`, as it is a bitwise operation?

**Comment by alamb** [comment]
>  BTW, is it better to move bit_slice to Bitmap, as it is a bitwise operation?


This  certainly sounds like a good idea to me

**Comment by tustvold** [comment]
Closing as expected behavior, buffers can only be correctly interpreted in the context of an ArrayData which provides a length and offset
