### ISSUE TITLE
Panic when writing empty List inside a Struct

### ISSUE THREAD

**Issue by hohav** [apache/arrow-rs#823]
**Describe the bug**
I get a panic when trying to write a parquet file containing a `StructArray` with a `ListArray` inside it, when there's at least one empty list.

**To Reproduce**
`cargo run` this: https://github.com/hohav/arrow-parquet-list-test/blob/v4/src/main.rs

**Expected behavior**
A parquet file is written.

**Actual behavior**
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/parquet-5.5.0/src/util/bit_util.rs:347:9
```

**Additional context**
Possibly related:
- #385 
- #703

**Comment by alamb** [comment]
Here is a PR with a proposed fix: https://github.com/apache/arrow-rs/pull/1166

@hohav can you possibly check to see if it fixes your usecase?
