### ISSUE TITLE
Re-export TimeUnit internal types from parquet_format?

### ISSUE THREAD

**Issue by aldanor** [apache/arrow-rs#841]
Minor/cosmetic/consistency request:

Would it make sense to re-export `NanoSeconds` etc since, technically, they're used in `TimeUnit` which is re-exported in `parquet::basic`? (or provide helper constructors like `TimeUnit::nanoseconds()`, or even `TimestampType::nanoseconds(bool)` to reduce the boilerplate even further)

// Yes, you can do `parquet::basic::TimeUnit::NANOS(Default::default())` - which clippy would complain about.

**Comment by tustvold** [comment]
Closed by #2626
