### ISSUE TITLE
Implement Union validity bitmap changes from ARROW-9222

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#85]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-9324

The implementation of Union in arrow has evolved from the current arrow-rs implementation. We need to update arrow-rs to follow the updated Arrow spec, including the updated validity bitmap changes from https://issues.apache.org/jira/browse/ARROW-9222 

Related: Null/Sparse Union Array support: https://github.com/apache/arrow-rs/issues/814

As part of implementing the new Union handling, we should also update the checks in `ArrayData::validate` added in https://github.com/apache/arrow-rs/pull/810

**Comment by paddyhoran** [comment]
Context: https://lists.apache.org/thread.html/r5664e13d0a28ef36f6244864b3b96217d082bdfafb29e866cbefbfa4%40%3Cdev.arrow.apache.org%3E

**Comment by alamb** [comment]
FYI @paddyhoran  I have a proposed implementation in https://github.com/apache/arrow-rs/pull/885 (look at the last commit)

**Comment by paddyhoran** [comment]
Excellent, I’ll find some time to take a look.  Thanks @alamb
