### ISSUE TITLE
[Rust][Dev] Cache packages and/or compilation in docker images

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#86]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-9359

To improve the local development experience, it would be nice if the Docker setup for Rust builds could cache packages from run to run.

**Comment by alamb** [comment]
Comment from Jorge Leitão(jorgecarleitao) @ 2020-07-14T13:22:14.139+0000:
<pre>One idea that I often use:


{code}
# use specific version here to freeze layer
FROM rust:1.44.1-buster AS backend-builder

# freeze the version for deterministic builds
RUN rustup update nightly-2020-07-03 && rustup default nightly-2020-07-03

# Compile a dummy program, so that the dependencies are compiled and cached on a layer
# see https://stackoverflow.com/a/58474618/931303 for details
RUN echo "fn main() {}" > dummy.rs
## if cargo.lock or cargo changes, we trigger a build of all dependencies.
COPY backend/Cargo.lock backend/Cargo.toml /
RUN sed -i 's@src/main.rs@dummy.rs@' Cargo.toml
RUN cargo build --release
RUN sed -i 's@dummy.rs@src/main.rs@' Cargo.toml

# compile the actual program
COPY ...

RUN cargo build --release
{code}
</pre>

Comment from Jorge Leitão(jorgecarleitao) @ 2020-07-19T15:47:36.675+0000:
<pre>I believe that this is a duplicate of ARROW-7136

 </pre>

**Comment by tustvold** [comment]
I think this is referring to a build system that no longer exists, or exists in a different repository, so closing
