### ISSUE TITLE
Add native comparison kernel support for `DictionaryArray`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#869]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Today,  DataFusion's expression evaluation does not work natively on `DictionaryArray`s; Instead what happens is that the DictionaryArrays are unpacked into their base type (e.g. a string dictionary gets unpacked into a `StringArray`)

This is very inefficient, especially for expressions like `col != 'foo'` -- if `col` is a `DictionaryArray` this filter could be applied by finding `'foo'` in the dictionary and then checking for values with that dictionary index, and the dictionary could be reused at the output.

**Describe the solution you'd like**
1. Add kernels that can compare `DictionaryArrays` (`eq_dict`, `lt_dict`, etc)
2. Add `DataType::Dictionary` to the the `eq_dyn` and the other dynamic kernels implemented in https://github.com/apache/arrow-rs/pull/858/

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by matthewmturner** [comment]
@alamb im interested in taking this. will start looking into it.

**Comment by alamb** [comment]
sounds great @matthewmturner  -- thank you!

**Comment by alamb** [comment]
I think we have a proposed interface in https://github.com/apache/arrow-rs/pull/1074

**Comment by matthewmturner** [comment]
> I believe this task is now complete. Thanks again @matthewmturner 

Thanks for patience and guidance @alamb :)
