### ISSUE TITLE
Unresolved import `arrow::ipc`

### ISSUE THREAD

**Issue by MrKhan0747** [apache/arrow-rs#872]
**Describe the bug**

Added parquet dependency in Cargo.toml file while running command Cargo build got an error saying " Unresolved import `arrow::ipc`" and package build failed in MacOs.

<img width="719" alt="Screenshot 2021-10-27 at 5 58 20 PM" src="https://user-images.githubusercontent.com/37217654/139065422-741bb13d-35e3-49a4-9bde-e8390a2ab230.png">

**Comment by alamb** [comment]
looks like this may be related to feature flags? Did you ever resolve this @MrKhan0747 ?

**Comment by MrKhan0747** [comment]
I was facing this issue in parquet version 6.0 but in parquet version 5.0+ it was working fine

**Comment by alamb** [comment]
I wonder if you also have an arrow dependency defined in your `Cargo.toml`, perhaps with `default-features = false`?

**Comment by tustvold** [comment]
Parquet has its arrow dependency defined as

```
arrow = { path = "../arrow", version = "25.0.0", optional = true, default-features = false, features = ["ipc"] }
```

Closing as I can't reproduce this issue anymore

**Comment by tustvold** [comment]
It was fixed by https://github.com/apache/arrow-rs/pull/1822/files#diff-80059dfe16b44840ad582c536226512e8631a13f412994f1b33d3976232fa1faR64
