### ISSUE TITLE
MIRI check is failing on master 

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#879]
**Describe the bug**
The MIRI check has started to fail on master:

https://github.com/apache/arrow-rs/commits/master

![Screen Shot 2021-10-29 at 9 14 17 AM](https://user-images.githubusercontent.com/490673/139441201-1a871182-48d7-4ee9-9de3-66fa1ded6e7f.png)

Example failure: https://github.com/apache/arrow-rs/runs/4023917285?check_suite_focus=true

**To Reproduce**
Run CI MIRI test on master

**Expected behavior**
Test should pass

**Additional context**
The MIRI version was recently updated in https://github.com/apache/arrow-rs/pull/875 by @Jimexist

**Comment by alamb** [comment]
I could not reproduce this locally (on MacOS):

Here is what i tried:

```shell
rustup toolchain install nightly-2021-10-23
rustup component add miri --toolchain nightly-2021-10-23
MIRIFLAGS="-Zmiri-disable-isolation" cargo +nightly-2021-10-23  miri test -p arrow -- --skip csv --skip ipc --skip json
```

Results in 
```
...
test src/record_batch.rs - record_batch::RecordBatch::try_from_iter (line 284) ... ok
test src/record_batch.rs - record_batch::RecordBatch::try_from_iter_with_nullable (line 321) ... ok
test src/compute/kernels/window.rs - compute::kernels::window::shift (line 32) ... ok
test src/util/test_util.rs - util::test_util::arrow_test_data (line 73) ... ok
test src/util/test_util.rs - util::test_util::parquet_test_data (line 95) ... ok
test src/util/string_writer.rs - util::string_writer (line 25) ... ok
test src/compute/kernels/comparison.rs - compute::kernels::comparison::like_utf8 (line 239) ... ok

test result: ok. 117 passed; 0 failed; 0 ignored; 0 measured; 14 filtered out; finished in 5.76s


Compilation finished at Sat Oct 30 09:58:38
```

Going to try it on Linux next

**Comment by Jimexist** [comment]
Nor can I on MacBook Pro intel CPU

**Comment by alamb** [comment]
🤔  the same commands passed for me on Ubuntu 20.04 on x86 as well

```
test src/util/string_writer.rs - util::string_writer (line 25) ... ok
test src/compute/kernels/comparison.rs - compute::kernels::comparison::like_utf8 (line 239) ... ok

test result: ok. 117 passed; 0 failed; 0 ignored; 0 measured; 14 filtered out; finished in 5.85s
```

**Comment by Jimexist** [comment]
Can it because of memory consumption?

**Comment by alamb** [comment]
> Can it because of memory consumption?

"Great minds think alike" -- lol I tried setting to `--test-threads=1` in this commit but that didn't seem to work

https://github.com/apache/arrow-rs/pull/891/commits/0dd0d62d7277d127afbb7c1648dd168a2f2faf82

However, I have had better luck clearing out the old cache. I'll get a new PR up shortly

**Comment by alamb** [comment]
It appears to have resurfaced: https://github.com/apache/arrow-rs/commits/master

![Screen Shot 2021-11-01 at 6 53 13 AM](https://user-images.githubusercontent.com/490673/139660913-366c71d7-26b5-4566-8355-e4d1af4aa1d8.png)

I am going to try to disable caching entirely for MIRI job and see if that looks promising

**Comment by alamb** [comment]
Still happening: https://github.com/apache/arrow-rs/runs/4069047142?check_suite_focus=true

Passes sometimes on rerun....
