### ISSUE TITLE
 verify-release-candidate.sh includes unpassable `cargo publish checks`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#881]
**Describe the bug**
The newly added `cargo publish` checks I added in #856 (see  https://github.com/apache/arrow-rs/pull/856/files#diff-82f32771b6ac9daaadbfb77bd77062d63e131ad18ecd9014ff90eff17865964fR137-R152) do not actually work for any crate other than `arrow`

The issue is that `cargo publish` ignores the 'path' annotations in Cargo.toml

Basically the issue is that they can't find the correct version of arrow for some reason

Here is an example failure:
```

/var/folders/s3/h5hgj43j0bv83shtmz_t_w400000gn/T/arrow-6.1.0.XXXXX.1Si6YRcT/apache-arrow-rs-6.1.0 /var/folders/s3/h5hgj43j0bv83shtmz_t_w400000gn/T/arrow-6.1.0.XXXXX.1Si6YRcT
+ pushd arrow-flight
/var/folders/s3/h5hgj43j0bv83shtmz_t_w400000gn/T/arrow-6.1.0.XXXXX.1Si6YRcT/apache-arrow-rs-6.1.0/arrow-flight /var/folders/s3/h5hgj43j0bv83shtmz_t_w400000gn/T/arrow-6.1.0.XXXXX.1Si6YRcT/apache-arrow-rs-6.1.0 /var/folders/s3/h5hgj43j0bv83shtmz_t_w400000gn/T/arrow-6.1.0.XXXXX.1Si6YRcT
+ cargo publish --dry-run
    Updating crates.io index
   Packaging arrow-flight v6.1.0 (/private/var/folders/s3/h5hgj43j0bv83shtmz_t_w400000gn/T/arrow-6.1.0.XXXXX.1Si6YRcT/apache-arrow-rs-6.1.0/arrow-flight)
error: failed to prepare local package for uploading

Caused by:
  failed to select a version for the requirement `arrow = "^6.1.0"`
  candidate versions found which didn't match: 6.0.0, 5.5.0, 5.4.0, ...
  location searched: crates.io index
  required by package `arrow-flight v6.1.0 (/private/var/folders/s3/h5hgj43j0bv83shtmz_t_w400000gn/T/arrow-6.1.0.XXXXX.1Si6YRcT/apache-arrow-rs-6.1.0/arrow-flight)`
+ cleanup
+ '[' no = yes ']'
+ echo 'Failed to verify release candidate. See /var/folders/s3/h5hgj43j0bv83shtmz_t_w400000gn/T/arrow-6.1.0.XXXXX.1Si6YRcT for details.'
Failed to verify release candidate. See /var/folders/s3/h5hgj43j0bv83shtmz_t_w400000gn/T/arrow-6.1.0.XXXXX.1Si6YRcT for details.
```

**To Reproduce**
```
./dev/release/verify-release-candidate.sh 6.1.0 1
```

**Expected behavior**
Check should pass 

**Additional context**
 #856

**Comment by houqp** [comment]
@alamb in order for path dependency to work, we need to supply an extra version that matches with the version we have in the arrow crate. For example, this is how we made it work for datafusion: https://github.com/apache/arrow-datafusion/blob/master/ballista/rust/core/Cargo.toml#L48

**Comment by alamb** [comment]
Thanks @houqp  -- I messed around a little with this

The Cargo.toml in `arrow-flight` already uses https://github.com/apache/arrow-rs/blob/active_release/arrow-flight/Cargo.toml#L29

> [dependencies]
> arrow = { path = "../arrow", version = "6.1.0" }

In fact `cargo build` works just fine -- the the issue is that `cargo publish --dry-run` seems to ignore the local `path` override. 

This behavior kind of makes sense given the discussion on https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-path-dependencies

> Note: crates.io does not allow packages to be published with path dependencies (path dev-dependencies are ignored). See the Multiple locations section for a fallback alternative.

So I don't have any other ideas at this time 😢

**Comment by houqp** [comment]
ha, you are right @alamb , the upstream path based dependencies need to be published to crates first.
