### ISSUE TITLE
Validation error when manually copying array data for a slice array

### ISSUE THREAD

**Issue by bjchambers** [apache/arrow-rs#940]
**Describe the bug**

The only commit in this branch https://github.com/bjchambers/arrow-rs/tree/reproduce-validation-error demonstrates the issue. See the added test https://github.com/bjchambers/arrow-rs/blob/reproduce-validation-error/arrow/src/array/data.rs#L1648 here.

Specifically, it creates a struct array, it slices it, then it gets all of the data from that array and attempts to create an identical array data. This fails in the validation due as follows:

```
thread 'array::data::tests::test_try_new_sliced_struct' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("Struct([Field { name: \"a\", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: None }, Field { name: \"b\", data_type: Boolean, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: None }]) child array #0 for field a has length smaller than expected for struct array (3 < 4)")', arrow/src/array/data.rs:1738:10
stack backtrace:
```

**To Reproduce**

**Expected behavior**
The array data can be constructed since it is a copy of existing (valid) data.

**Additional context**

**Comment by bjchambers** [comment]
@alamb in case you have thoughts, since this looks to be in the new validation code.

**Comment by alamb** [comment]
@bjchambers  sounds like a bug introduced in https://github.com/apache/arrow-rs/pull/810 -- are you planning to look at it, or shall I?

**Comment by bjchambers** [comment]
I haven't looked into it much. If you're able that's great otherwise 

I did see a comment near the failure that is suspicious (something about comparing length to length plus offset). But I'm not sure about the intended behavior.

**Comment by alamb** [comment]
I'll look into it tomorrow first thing in the morning

**Comment by alamb** [comment]
@bjchambers  -- PR with proposed fix is https://github.com/apache/arrow-rs/pull/942
