### ISSUE TITLE
Check Apache Arrow Rust 6.2.0 RC1 failure

### ISSUE THREAD

**Issue by xudong963** [apache/arrow-rs#948]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by xudong963** [comment]
Hi @alamb, After receiving your email about `[VOTE][RUST] Release Apache Arrow Rust 6.2.0 RC1`. I tested it and got the following error.

```
error: failed to prepare local package for uploading

Caused by:
  failed to select a version for the requirement `arrow = "^6.2.0"`
  candidate versions found which didn't match: 6.1.0, 6.0.0, 5.5.0, ...
  location searched: crates.io index
  required by package `arrow-flight v6.2.0
```
My testing environment is macOS Monterey.

**Comment by alamb** [comment]
Hi @xudong963  -- thanks for reporting this issue

I think this is the same problem as fixed in  https://github.com/apache/arrow-rs/pull/882 but which I did not backport to active_release (and thus it is not in the tarball). I will backport that now 🤦 

FYI @andygrove  reported something similar

**Comment by alamb** [comment]
resolved in https://github.com/apache/arrow-rs/pull/949
