### ISSUE TITLE
Add boolean comparison to scalar kernels for less then, greater than

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#959]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
We are implementing general purpose implementations of `<`, `<=`, `>`, and `>=` in DataFusion -- see https://github.com/apache/arrow-datafusion/pull/1163

DataFusion uses different implementations if the left or right sides are scalar values vs if the left or right sides are both arrays. 

Arrow has the `lt_bool`, `lt_eq_bool`, `gt_bool`, and `gt_eq_bool`  kernels  🎉  added in https://github.com/apache/arrow-rs/pull/860 by @Jimexist [see docs for `lt_bool`](https://docs.rs/arrow/6.2.0/arrow/compute/kernels/comparison/fn.lt_bool.html)

However, it does not have corresponding `scalar` variants, so I implemented simple versions in DataFusion to get the feature but they are not as optimized as they could be. 

**Describe the solution you'd like**
Implement optimized kernels of `lt_bool_scalar`, `lt_eq_bool_scalar` `gt_bool_scalar`, `gt_eq_bool_scalar`

Simple versions are implemented in https://github.com/apache/arrow-datafusion/pull/1163. The optimized versions should follow the pattern demonstrated in @Dandandan 's pr for `eq_bool` https://github.com/apache/arrow-rs/pull/844 -- namely doing the comparisons in 64-bit chunks when possible.

**Comment by xudong963** [comment]
I want to do it! @alamb
