### ISSUE TITLE
About cherry-pick automatically

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-rs#971]
**Which part is this question about**
![image](https://user-images.githubusercontent.com/7450163/142960126-d9068565-dd93-4f56-b660-63a9aef7f47d.png)

every day, @alamb should cherry pick some pull request to the `active_release` branch automatically.
I have a question about what kind of pull request should be cherry pick?

**Describe your question**
A clear and concise description of what the question is.

**Additional context**

**Comment by alamb** [comment]
Hi @liukun4515  -- the process I am following is documented here: https://github.com/apache/arrow-rs/blob/master/dev/release/README.md#backporting

Specifically I try to cherry-pick everything that is "backwards compatible" (in the rust Semantic Versioning sense that someone upgrading from 6.1.0 to 6.2.0 would not have to change any of their code). 

Does that answer your question?

**Comment by liukun4515** [comment]
thank you for your reply.
