### ISSUE TITLE
Confused import/export API when interacting with C++

### ISSUE THREAD

**Issue by hu6360567** [apache/arrow-rs#994]
**Which part is this question about**
FFI apis and raw pointer management

**Describe your question**
I'm trying to import/export arrow arrays between C++ and Rust, when it crashes when C++ is compiled in release mode.
ref: https://github.com/apache/arrow/issues/11846

To be confused, when import/expore array/schema on Rust side, the input pointer is `const`.
However, C++ API`arrow::ImportRecordBatch` moves the payload from input array/schema pointers.
Is there any code to show best practice on import/export between Rust and C++?

My implementation of exporting arrow array allocated from Rust
Rust part:
```rust
fn export<T>(array: T, content: *mut *const FFI_ArrowArray, schema: *mut *const FFI_ArrowSchema) where T: Array {
    match array.to_raw() {
        Ok((c, s)) => unsafe {
            // Is it right to directly copy pointer address, when does `c` and `s` actually dropped?
            // Should I use `copy_to` or `replace` from `std::mem::ptr` ?
            *content = c;
            *schema = s;
        }
        Err(e) => {
            eprintln!("{}", e);
        }
    }
}

#[no_mangle]
pub extern "C" fn export_array(content: *mut *const FFI_ArrowArray, schema: *mut *const FFI_ArrowSchema) {
    let sa = StringArray::from(vec!["a", "b", "c"]);

    export(sa, content, schema);
}
```
C++ part
```C++
void func(){
    const ArrowArray *content = nullptr;
    const ArrowSchema *schema = nullptr;
    export_array(&content, &schema);

    // I have to const_cast the pointers
    auto array = *arrow::ImportRecordBatch(const_cast<ArrowArray *>(content), const_cast<ArrowSchema *>(schema));
    std::cout << array->ToString() << std::endl;
}
```

**Additional context**
ref: https://github.com/apache/arrow/issues/11846

**Comment by hu6360567** [comment]
In `pyarrow.rs`, I found some snippet.
https://github.com/apache/arrow-rs/blob/e9be49d962560ce5b87544a2933d8b207322cf60/arrow/src/pyarrow.rs#L110-L132

The desired workflow of importing array from FFI:
1. prepare ArrowArray and leak both pointers to FFI
2. write C Data Interface into both pointers
3. Import from both pointers, allocated in first step

**Comment by alamb** [comment]
It appears this was a user error and has been resolved upstream: https://github.com/apache/arrow/issues/11846

Please reopen if there is still a problem
