### ISSUE TITLE
Update rust version to 1.57

### ISSUE THREAD

**Issue by xudong963** [apache/arrow-rs#995]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
https://blog.rust-lang.org/2021/12/02/Rust-1.57.0.html
https://github.com/apache/arrow-datafusion/pull/1395

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
Thanks @xudong963 -- note also https://github.com/apache/arrow-rs/pull/992 from @carols10cents  which cleaned up the new clippy lints. I can't remember if we pin the rust version in arrow-rs or not

**Comment by xudong963** [comment]
> I can't remember if we pin the rust version in arrow-rs or not

I have checked, we don't have.

**Comment by alamb** [comment]
> I have checked, we don't have.

 👍  so ti may be that #992 is the only thing that is needed
